import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> af = {
  AppKeys.lblChooseLanguage: "Kies taal",
  "All": "Alles",
  "AI Story Generator": "KI Storie Generator",
  "Story Generator": "Storie Generator",
  "Essay Writer": "Opstel Skrywer",
  "Essay length": "Opstel lengte",
  "Script Generator": "Skrip Generator",
  "Create original stories in seconds":
      "Skep oorspronklike stories in sekondes",
  "Academic writing made simple": "Akademiese skryfwerk maklik gemaak",
  "Generate powerful scripts for any medium":
      "Genereer kragtige skrifte vir enige medium",
  "Start Writing": "Begin Skryf",
  "Create Now": "Skep Nou",
  "Start Generating": "Begin Genereer",
  "Your Stories": "Jou Stories",
  "No stories yet": "Nog geen stories nie",
  "Start creating your first story!": "Begin om jou eerste storie te skep!",
  "Your Story Space Awaits": "Jou Storie Ruimte Wag",
  "Start your first story and see it appear here":
      "Begin jou eerste storie en sien dit hier verskyn",
  "Language": "Taal",
  "Rate us": "Beoordeel ons",
  "Share us": "Deel ons",
  "Privacy Policy": "Privaatheidsbeleid",
  "Settings": "Instellings",
  "Select Language": "Kies Taal",
  "Dashboard": "Kontroleskerm",
  "BENEFITS": "VOORDELE",
  "Subscribe": "Teken in",
  "Weekly": "Weekliks",
  "Monthly": "Maandeliks",
  "Yearly": "Jaarliks",
  "week": "week",
  "months": "maande",
  "year": "jaar",
  "Terms & Condition": "Terme & Voorwaardes",
  "No Commitment. Cancel anytime": "Geen verpligting. Kanselleer enige tyd",
  "No Payment Now": "Geen Betaling Nou",
  "3 days free": "3 dae gratis",
  "Start your free trial": "Begin jou gratis proeftydperk",
  "More detailed answers": "Meer gedetailleerde antwoorde",
  "Instant responds": "Onmiddellike reaksie",
  "Text recognition": "Teksherkenning",
  "Powered by AI": "Aangedryf deur KI",
  "Storytelleing": "Storievertelling",
  ' Power': " Krag",
  "Unlock your \nFill ": "Ontsluit jou \nFill ",
  "Your History": "Jou Geskiedenis",
  "Terms and Conditions": "Terme en Voorwaardes",
  "Short": "Kort",
  "Medium": "Medium",
  "Long": "Lank",
  "Length": "Lengte",
  "Describe your topic...": "Beskryf jou onderwerp...",
  "Set Creativity": "Stel Kreatiwiteit",
  "Standard": "Standaard",
  "Creative": "Kreatief",
  "Complex": "Kompleks",
  "Select Genre": "Kies Genre",
  "Fantasy": "Fantasie",
  "Mystery": "Raaisel",
  "Thriller": "Riller",
  "Script Tone": "Skrip Toon",
  "Script Type": "Skrip Tipe",
  "Comedy": "Komedie",
  "Drama": "Drama",
  "Horror": "Gruwel",
  "Action": "Aksie",
  "Romance": "Romanse",
  "Go Premium": "Gaan Premium",
  "Unlock Everything": "Ontsluit Alles",
  "Unlimited Story Generation": "Onbeperkte Storie Generasie",
  "Write Longer & Detailed Essays": "Skryf Langer & Gedetailleerde Opstelle",
  "Advanced Script Writer": "Gevorderde Skrip Skrywer",
  "Unlock All Styles & Tones": "Ontsluit Alle Style & Tone",
  "No Word/Length Limit": "Geen Woord/Lengte Limiet",
  "Remove All Ads": "Verwyder Alle Advertensies",
  "Restore": "Herstel",
  "YouTube Video": "YouTube Video",
  "Podcast": "Podgooi",
  "Reel": "Reel",
  "Motivational": "Motiverend",
  "Advertisement": "Advertensie",
  "Fairy Tale": "Sprokie",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Kies Styl",
  "Imaginative": "Verbeeldingryk",
  "Innovative": "Innoverend",
  "AI Story Writer": "KI Storie Skrywer",
  "Generate": "Genereer",
  "Please wait...": "Wag asseblief...",
  "Result": "Resultaat",
  "Regenerate": "Hergenereer",
  "Download": "Aflaai",
  "Text copied to clipboard!": "Teks na knipbord gekopieer!",
  "Please enter a topic": "Voer asseblief 'n onderwerp in",
  "Story Magic": "Storie Magie",
  "Let AI bring your thoughts to a full story":
      "Laat KI jou gedagtes na 'n volledige storie bring",
  "Smart Scripts": "Slim Skrifte",
  "From concept to script—fast, easy, and creative":
      "Van konsep tot skrip—vinnig, maklik en kreatief",
  "Perfect Essays": "Perfekte Opstelle",
  "You have reached your free limit": "Jy het jou gratis limiet bereik",
  "Donwload": "Aflaai",
  "Press again to exit app": "Druk weer om app te verlaat",
  "Saved to files": "TXT-lêer suksesvol gestoor!",
  "Error: Please try again": "Fout: Probeer asseblief weer",
  "Subscription expired": "Intekening verval",
  "Purchase cancelled": "Aankoop gekanselleer",
  "Purchase failed": "Aankoop misluk",
  "Restore failed": "Herstel misluk",
  "Purchase Successful!": "Aankoop Suksesvol!",
  "Short (200-500 words)": "Kort (200-500 woorde)",
  "Medium (500-1000 words)": "Medium (500-1000 woorde)",
  "Large (1000+ words)": "Groot (1000+ woorde)",
  "Academic Level": "Akademiese Vlak",
  "Type of Paper": "Tipe Papier",
  "High School": "Hoërskool",
  "College": "Kollege",
  "Short Film": "Kortfilm",
  "University": "Universiteit",
  "Masters": "Meesters",
  "Custom": "Aangepas",
  "Tiktok Video": "TikTok Video",
  "Movie": "Film",
  "Expository": "Verklarend",
  "Argumentative": "Argumenterend",
  "Narrative": "Verhalend",
  "Descriptive": "Beskrywend",
  "We're sorry to hear that 😔": "Ons is jammer om dit te hoor 😔",
  "We'll try to improve 🙁": "Ons sal probeer verbeter 🙁",
  "Thanks for your feedback 🙂": "Dankie vir jou terugvoer 🙂",
  "Great! We're glad you like it 😊": "Wonderlik! Ons is bly jy hou daarvan 😊",
  "Awesome! Thank you so much! 🎉": "Fantasties! Baie dankie! 🎉",
  "Maybe Later": "Miskien Later",
  "Tap a star to rate your experience":
      "Tik op 'n ster om jou ervaring te beoordeel",
  "Enjoying AI Math Solver?": "Geniet jy KI Wiskunde Oplosser?",
  "Thank you for rating us": "Dankie dat jy ons beoordeel het",
  "Submit Rating": "Dien Beoordeling In",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Geniet jy KI Storie Generator?",
  AppKeys.arabic: "Arabies",
  AppKeys.chinese: "Sjinees",
  AppKeys.english: "Engels",
  AppKeys.french: "Frans",
  AppKeys.german: "Duits",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesies",
  AppKeys.japanese: "Japannees",
  AppKeys.korean: "Koreaans",
  AppKeys.portuguese: "Portugees",
  AppKeys.russian: "Russies",
  AppKeys.spanish: "Spaans",
  AppKeys.turkish: "Turks",
  'Download As': 'Laai Af As',
  'Choose format to download': 'Kies formaat om af te laai',
  'Text File': 'Teks Lêer',
  'PDF File': 'PDF Lêer',
  'Copy': 'Kopieer',
  'Share': 'Deel',
  'Text copied!': 'Teks gekopieer!',
  'PDF saved successfully!': 'PDF suksesvol gestoor!',
  'Error creating PDF: Please try again':
      'Fout met PDF skep: Probeer asseblief weer',
  'Character Story': 'Karakter Storie',
  'Character Details': 'Karakter Besonderhede',
  'Character Name': 'Karakter Naam',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Ouderdom (bv., 25, Jong Volwassene, Antiek)',
  'Personality (e.g., brave, shy, cunning)':
      'Persoonlikheid (bv., dapper, skaam, slu)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (bv., Held, Skurk, Mentor)',
  'Additional Details (optional)': 'Addisionele Besonderhede (opsioneel)',
  'Output Style': 'Uitvoer Styl',
  'Generate Character': 'Genereer Karakter',
  'Please enter character name': 'Voer asseblief karakter naam in',
  'Please enter character role': 'Voer asseblief karakter rol in',
  'Detailed': 'Gedetailleerd',
  'Brief': 'Kort',
  'Elaborate': 'Uitgebreid',
  'Create detailed character backstories':
      'Skep gedetailleerde karakter agtergrondstories',
  'Create Character': 'Skep Karakter',
  'Transform and improve your existing stories':
      'Transformeer en verbeter jou bestaande stories',
  'Rewrite Now': 'Herskryf Nou',
  'Generate catchy titles for your stories':
      'Genereer pakkende titels vir jou stories',
  'Generate Titles': 'Genereer Titels',
  'Rewrite Story': 'Herskryf Storie',
  'Paste Your Story': 'Plak Jou Storie',
  'Paste your story here to rewrite...':
      'Plak jou storie hier om te herskryf...',
  'Select Tone': 'Kies Toon',
  'Rewrite Style': 'Herskryf Styl',
  'Output Length': 'Uitvoer Lengte',
  'Please paste your story': 'Plak asseblief jou storie',
  'Story is too short. Please provide more content.':
      'Storie is te kort. Verskaf asseblief meer inhoud.',
  'Same': 'Dieselfde',
  'More Dramatic': 'Meer Dramaties',
  'More Humorous': 'Meer Humoristies',
  'More Emotional': 'Meer Emosioneel',
  'More Suspenseful': 'Meer Spanningsvol',
  'Lighter': 'Ligter',
  'Improved': 'Verbeter',
  'Simplified': 'Vereenvoudig',
  'More Descriptive': 'Meer Beskrywend',
  'More Dialogue': 'Meer Dialoog',
  'More Action': 'Meer Aksie',
  'Literary': 'Literêr',
  'Shorter': 'Korter',
  'Longer': 'Langer',
  'Much Longer': 'Baie Langer',
  'Title Generator': 'Titel Generator',
  'Story/Book Topic': 'Storie/Boek Onderwerp',
  'Keywords (Optional)': 'Sleutelwoorde (Opsioneel)',
  'Describe your story topic or theme...':
      'Beskryf jou storie onderwerp of tema...',
  'e.g., magic, dragon, adventure': 'bv., magie, draak, avontuur',
  'Title For': 'Titel Vir',
  'Title Style': 'Titel Styl',
  "Adventure": "Avontuur",
  'Number of Titles': 'Aantal Titels',
  'Book': 'Boek',
  'Short Story': 'Kortverhaal',
  'Novel': 'Roman',
  'Chapter': 'Hoofstuk',
  'Series': 'Reeks',
  'Simple': 'Eenvoudig',
  'Mysterious': 'Geheimsinnig',
  'Dramatic': 'Dramaties',
  'Catchy': 'Pakkend',
  'Poetic': 'Poëties',
  'Kids': 'Kinders',
  'Blog Writer': 'Blog Skrywer',
  'Blog Topic': 'Blog Onderwerp',
  'Target Keywords': 'Teiken Sleutelwoorde',
  'Target Audience (Optional)': 'Teiken Gehoor (Opsioneel)',
  'Enter your blog topic or title...': 'Voer jou blog onderwerp of titel in...',
  'e.g., AI writing, content marketing, SEO tips':
      'bv., KI skryfwerk, inhoud bemarking, SEO wenke',
  'e.g., small business owners, bloggers':
      'bv., klein besigheidseienaars, bloggers',
  'Article Type': 'Artikel Tipe',
  'Writing Tone': 'Skryf Toon',
  'Article Length': 'Artikel Lengte',
  'SEO Options': 'SEO Opsies',
  'Include Meta Description': 'Sluit Meta Beskrywing In',
  'Include Keyword Suggestions': 'Sluit Sleutelwoord Voorstelle In',
  'Include FAQs Section': 'Sluit Vrae Afdeling In',
  'Please enter a blog topic': 'Voer asseblief \'n blog onderwerp in',
  'Generate Blog': 'Genereer Blog',
  'SEO optimized articles with keywords':
      'SEO geoptimaliseerde artikels met sleutelwoorde',
  'Write Blog': 'Skryf Blog',
  'SEO Article': 'SEO Artikel',
  'How-To Guide': 'Hoe-Om Gids',
  'Listicle': 'Lys Artikel',
  'Product Review': 'Produk Resensie',
  'Opinion Piece': 'Mening Stuk',
  'News Article': 'Nuus Artikel',
  'Professional': 'Professioneel',
  'Casual': 'Informeel',
  'Informative': 'Insiggewend',
  'Persuasive': 'Oortuigend',
  'Friendly': 'Vriendelik',
  'Authoritative': 'Gesaghebbend',
  'Short (500-800)': 'Kort (500-800)',
  'Medium (800-1500)': 'Medium (800-1500)',
  'Long (1500-2500)': 'Lank (1500-2500)',
  'Detailed (2500+)': 'Gedetailleerd (2500+)',
  'YouTube Script': 'YouTube Skrip',
  'Video Topic': 'Video Onderwerp',
  'Key Points (Optional)': 'Sleutelpunte (Opsioneel)',
  'What is your video about?': 'Waaroor gaan jou video?',
  'List key points to cover (optional)...':
      'Lys sleutelpunte om te dek (opsioneel)...',
  'Video Duration': 'Video Duur',
  'Script Options': 'Skrip Opsies',
  'Include Hook/Intro': 'Sluit Haak/Inleiding In',
  'Include Call-to-Action': 'Sluit Oproep-tot-Aksie In',
  'Include Timestamps': 'Sluit Tydstempels In',
  'Please enter a video topic': 'Voer asseblief \'n video onderwerp in',
  'Generate Script': 'Genereer Skrip',
  'Create scripts for videos & reels': 'Skep skrifte vir videos & reels',
  'Create Script': 'Skep Skrip',
  'Storytime': 'Storietyd',
  'Documentary': 'Dokumentêr',
  'Short Reel': 'Kort Reel',
  'Educational': 'Opvoedkundig',
  'Review': 'Resensie',
  'Tutorial': 'Handleiding',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Boeiend',
  'Energetic': 'Energiek',
  'Calm': 'Kalm',
  'Funny': 'Snaaks',
  'Inspired': 'Geïnspireer',
  'Film Script': 'Film Skrip',
  'Stage Play': 'Verhoogspel',
  'Scene Breakdown': 'Toneel Uiteensetting',
  'Dialogue Only': 'Slegs Dialoog',
  'Ad loading please wait..': 'Advertensie laai, wag asseblief..',
  'Words:': 'Woorde:',
  'Reading:': 'Lees:',
};
