import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> am = {
  AppKeys.lblChooseLanguage: "ቋንቋ ይምረጡ",
  "All": "ሁሉም",
  "AI Story Generator": "AI ታሪክ ጀነሬተር",
  "Story Generator": "ታሪክ ጀነሬተር",
  "Essay Writer": "ድርሰት ጸሐፊ",
  "Essay length": "የድርሰት ርዝመት",
  "Script Generator": "ስክሪፕት ጀነሬተር",
  "Create original stories in seconds": "በሰከንዶች ውስጥ ኦሪጅናል ታሪኮችን ይፍጠሩ",
  "Academic writing made simple": "የአካዳሚክ ጽሑፍ ቀላል ተደርጓል",
  "Generate powerful scripts for any medium": "ለማንኛውም ሚዲያ ኃይለኛ ስክሪፕቶችን ያመንጩ",
  "Start Writing": "መጻፍ ይጀምሩ",
  "Create Now": "አሁን ይፍጠሩ",
  "Start Generating": "ማመንጨት ይጀምሩ",
  "Your Stories": "ታሪኮችዎ",
  "No stories yet": "እስካሁን ታሪኮች የሉም",
  "Start creating your first story!": "የመጀመሪያውን ታሪክዎን መፍጠር ይጀምሩ!",
  "Your Story Space Awaits": "የታሪክ ቦታዎ እየጠበቀ ነው",
  "Start your first story and see it appear here":
      "የመጀመሪያውን ታሪክዎን ይጀምሩ እና እዚህ ሲታይ ይመልከቱ",
  "Language": "ቋንቋ",
  "Rate us": "ደረጃ ይስጡን",
  "Share us": "ያጋሩን",
  "Privacy Policy": "የግላዊነት ፖሊሲ",
  "Settings": "ቅንብሮች",
  "Select Language": "ቋንቋ ይምረጡ",
  "Dashboard": "ዳሽቦርድ",
  "BENEFITS": "ጥቅሞች",
  "Subscribe": "ይመዝገቡ",
  "Weekly": "ሳምንታዊ",
  "Monthly": "ወርሃዊ",
  "Yearly": "ዓመታዊ",
  "week": "ሳምንት",
  "months": "ወራት",
  "year": "ዓመት",
  "Terms & Condition": "ውሎች እና ሁኔታዎች",
  "No Commitment. Cancel anytime": "ምንም ግዴታ የለም። በማንኛውም ጊዜ ይሰርዙ",
  "No Payment Now": "አሁን ክፍያ የለም",
  "3 days free": "3 ቀናት ነፃ",
  "Start your free trial": "ነፃ ሙከራዎን ይጀምሩ",
  "More detailed answers": "የበለጠ ዝርዝር መልሶች",
  "Instant responds": "ፈጣን ምላሽ",
  "Text recognition": "የጽሑፍ ማወቂያ",
  "Powered by AI": "በAI የተጎለበተ",
  "Storytelleing": "ታሪክ መተረት",
  ' Power': " ኃይል",
  "Unlock your \nFill ": "ያንሎክ ያድርጉ \nFill ",
  "Your History": "ታሪኮ",
  "Terms and Conditions": "ውሎች እና ሁኔታዎች",
  "Short": "አጭር",
  "Medium": "መካከለኛ",
  "Long": "ረጅም",
  "Length": "ርዝመት",
  "Describe your topic...": "ርዕስዎን ይግለጹ...",
  "Set Creativity": "ፈጠራ ያዘጋጁ",
  "Standard": "መደበኛ",
  "Creative": "ፈጠራ",
  "Complex": "ውስብስብ",
  "Select Genre": "ዘውግ ይምረጡ",
  "Fantasy": "ምናባዊ",
  "Mystery": "ምስጢር",
  "Thriller": "ስሪለር",
  "Script Tone": "የስክሪፕት ቃና",
  "Script Type": "የስክሪፕት ዓይነት",
  "Comedy": "ኮሜዲ",
  "Drama": "ድራማ",
  "Horror": "አስፈሪ",
  "Action": "ድርጊት",
  "Romance": "ፍቅር",
  "Go Premium": "ፕሪሚየም ይሁኑ",
  "Unlock Everything": "ሁሉንም ያንሎክ ያድርጉ",
  "Unlimited Story Generation": "ያልተገደበ ታሪክ ማመንጨት",
  "Write Longer & Detailed Essays": "ረጅምና ዝርዝር ድርሰቶች ይጻፉ",
  "Advanced Script Writer": "የላቀ ስክሪፕት ጸሐፊ",
  "Unlock All Styles & Tones": "ሁሉንም ቅጦች እና ቃናዎች ያንሎክ ያድርጉ",
  "No Word/Length Limit": "የቃል/ርዝመት ገ��ብ የለም",
  "Remove All Ads": "ሁሉንም ማስታወቂያዎች ያስወግዱ",
  "Restore": "ይመልሱ",
  "YouTube Video": "ዩቲዩብ ቪዲዮ",
  "Podcast": "ፖድካስት",
  "Reel": "ሪል",
  "Motivational": "አነሳሽ",
  "Advertisement": "ማስታወቂያ",
  "Fairy Tale": "ተረት",
  "Sci-Fi": "ሳይንስ ፊክሽን",
  "Select Style": "ቅጥ ይምረጡ",
  "Imaginative": "ምናባዊ",
  "Innovative": "ፈጠራ",
  "AI Story Writer": "AI ታሪክ ጸሐፊ",
  "Generate": "ያመንጩ",
  "Please wait...": "እባክዎ ይጠብቁ...",
  "Result": "ውጤት",
  "Regenerate": "እንደገና ያመንጩ",
  "Download": "ያውርዱ",
  "Text copied to clipboard!": "ጽሑፍ ወደ ክሊፕቦርድ ተቀድቷል!",
  "Please enter a topic": "እባክዎ ርዕስ ያስገቡ",
  "Story Magic": "የታሪክ አስማት",
  "Let AI bring your thoughts to a full story":
      "AI ሐሳቦችዎን ወደ ሙሉ ታሪክ እንዲያመጣ ይፍቀዱ",
  "Smart Scripts": "ስማርት ስክሪፕቶች",
  "From concept to script—fast, easy, and creative":
      "ከጽንሰ-ሐ���ብ ወደ ስክሪፕት—ፈጣን፣ ቀላል እና ፈጠራ",
  "Perfect Essays": "ፍፁም ድርሰቶች",
  "You have reached your free limit": "ነፃ ገደብዎን ደርሰዋል",
  "Donwload": "ያውርዱ",
  "Press again to exit app": "ከመተግበሪያ ለመውጣት እንደገና ይጫኑ",
  "Saved to files": "TXT ፋይል በተሳካ ሁኔታ ተቀምጧል!",
  "Error: Please try again": "ስህተት: እባክዎ እንደገና ይሞክሩ",
  "Subscription expired": "ምዝገባ ጊዜው ያለፈ",
  "Purchase cancelled": "ግዢ ተሰርዟል",
  "Purchase failed": "ግዢ አልተሳካም",
  "Restore failed": "መመለስ አልተሳካም",
  "Purchase Successful!": "ግዢ ተሳክቷል!",
  "Short (200-500 words)": "አጭር (200-500 ቃላት)",
  "Medium (500-1000 words)": "መካከለኛ (500-1000 ቃላት)",
  "Large (1000+ words)": "ትልቅ (1000+ ቃላት)",
  "Academic Level": "የአካዳሚክ ደረጃ",
  "Type of Paper": "የወረቀት ዓይነት",
  "High School": "ሁለተኛ ደረጃ ትምህርት ቤት",
  "College": "ኮሌጅ",
  "Short Film": "አጭር ፊልም",
  "University": "ዩኒቨርሲቲ",
  "Masters": "ማስተርስ",
  "Custom": "ብጁ",
  "Tiktok Video": "ቲክቶክ ቪዲዮ",
  "Movie": "ፊልም",
  "Expository": "ገላጭ",
  "Argumentative": "ክርክራዊ",
  "Narrative": "ትረካ",
  "Descriptive": "ገላጭ",
  "We're sorry to hear that 😔": "ይህን ሰምቶ ያዝናል 😔",
  "We'll try to improve 🙁": "ለማሻሻል እንሞክራለን 🙁",
  "Thanks for your feedback 🙂": "ለአስተያየትዎ እናመሰግናለን 🙂",
  "Great! We're glad you like it 😊": "አሪፍ! ወደውት ስለሆነ ደስ ይለናል 😊",
  "Awesome! Thank you so much! 🎉": "አስደናቂ! በጣም እናመሰግናለን! 🎉",
  "Maybe Later": "ምናልባት በኋላ",
  "Tap a star to rate your experience": "ተሞክሮዎን ለመገምገም ኮከብ ይንኩ",
  "Enjoying AI Math Solver?": "AI ማት ሶልቨርን እየተደሰቱ ነው?",
  "Thank you for rating us": "ደረጃ ስለሰጡን እናመሰግናለን",
  "Submit Rating": "ደረጃ ያስገቡ",
  "Hindi": "ሂንዲ",
  "Enjoying AI Story Generator?": "AI ታሪክ ጀነሬተርን እየተደሰቱ ነው?",
  AppKeys.arabic: "ዓረብኛ",
  AppKeys.chinese: "ቻይንኛ",
  AppKeys.english: "እንግሊዝኛ",
  AppKeys.french: "ፈረንሳይኛ",
  AppKeys.german: "ጀርመንኛ",
  AppKeys.hindi: "ሂንዲ",
  AppKeys.indonesian: "ኢንዶኔዥያኛ",
  AppKeys.japanese: "ጃፓንኛ",
  AppKeys.korean: "ኮሪያኛ",
  AppKeys.portuguese: "ፖርቱጋልኛ",
  AppKeys.russian: "ሩስኛ",
  AppKeys.spanish: "ስፓኒሽ",
  AppKeys.turkish: "ቱርክኛ",
  'Download As': 'ያውርዱ እንደ',
  'Choose format to download': 'ለማውረድ ቅርጸት ይምረጡ',
  'Text File': 'የጽሑፍ ፋይል',
  'PDF File': 'PDF ፋይል',
  'Copy': 'ቅዳ',
  'Share': 'ያጋሩ',
  'Text copied!': 'ጽሑፍ ተቀድቷል!',
  'PDF saved successfully!': 'PDF በተሳካ ሁኔታ ተቀምጧል!',
  'Error creating PDF: Please try again': 'PDF በመፍጠር ላይ ስህተት: እባክዎ እንደገና ይሞክሩ',
  'Character Story': 'የገፀ ባሕርይ ታሪክ',
  'Character Details': 'የገፀ ባሕርይ ዝርዝሮች',
  'Character Name': 'የገፀ ባሕርይ ስም',
  'Age (e.g., 25, Young Adult, Ancient)': 'ዕድሜ (ለምሳሌ 25፣ ወጣት አዋቂ፣ ጥንታዊ)',
  'Personality (e.g., brave, shy, cunning)': 'ባሕርይ (ለምሳሌ ድፍረተኛ፣ አፍራች፣ ተንኮለኛ)',
  'Role (e.g., Hero, Villain, Mentor)': 'ሚና (ለምሳሌ ጀግና፣ ክፉ፣ አማካሪ)',
  'Additional Details (optional)': 'ተጨማሪ ዝርዝሮች (አማራጭ)',
  'Output Style': 'የውጤት ቅጥ',
  'Generate Character': 'ገፀ ባሕርይ ያመንጩ',
  'Please enter character name': 'እባክዎ የገፀ ባሕርይ ስም ያስገቡ',
  'Please enter character role': 'እባክዎ የገፀ ባሕርይ ሚና ያስገቡ',
  'Detailed': 'ዝርዝር',
  'Brief': 'አጭር',
  'Elaborate': 'ሰፊ',
  'Create detailed character backstories': 'ዝርዝር የገፀ ባሕርይ ዳራ ታሪኮች ይፍጠሩ',
  'Create Character': 'ገፀ ባሕርይ ይፍጠሩ',
  'Transform and improve your existing stories': 'ያሉ ታሪኮችዎን ይቀይሩ እና ያሻሽሉ',
  'Rewrite Now': 'አሁን እንደገና ይጻፉ',
  'Generate catchy titles for your stories': 'ለታሪኮችዎ ማራኪ ርዕሶች ያመንጩ',
  'Generate Titles': 'ርዕሶች ያመንጩ',
  'Rewrite Story': 'ታሪክ እንደገና ይጻፉ',
  'Paste Your Story': 'ታሪክዎን ይለጥፉ',
  'Paste your story here to rewrite...': 'እንደገና ለመጻፍ ታሪክዎን እዚህ ይለጥፉ...',
  'Select Tone': 'ቃና ይምረጡ',
  'Rewrite Style': 'የድጋሚ ጽሑፍ ቅጥ',
  'Output Length': 'የውጤት ርዝመት',
  'Please paste your story': 'እባክዎ ታሪክዎን ይለጥፉ',
  'Story is too short. Please provide more content.':
      'ታሪኩ በጣም አጭር ነው። እባክዎ ተጨማሪ ይዘት ያቅርቡ።',
  'Same': 'ተመሳሳይ',
  'More Dramatic': 'የበለጠ ድራማዊ',
  'More Humorous': 'የበለጠ አስቂኝ',
  'More Emotional': 'የበለጠ ስሜታዊ',
  'More Suspenseful': 'የበለጠ ጉጉት ቀስቃሽ',
  'Lighter': 'ቀላል',
  'Improved': 'የተሻሻለ',
  'Simplified': 'የቀለለ',
  'More Descriptive': 'የበለጠ ገላጭ',
  'More Dialogue': 'የበለጠ ውይይት',
  'More Action': 'የበለጠ ድርጊት',
  'Literary': 'ስነ-ጽሑፋዊ',
  'Shorter': 'አጭር',
  'Longer': 'ረጅም',
  'Much Longer': 'በጣም ረጅም',
  'Title Generator': 'ርዕስ ጀነሬተር',
  'Story/Book Topic': 'የታሪክ/መጽሐፍ ርዕስ',
  'Keywords (Optional)': 'ቁልፍ ቃላት (አማራጭ)',
  'Describe your story topic or theme...': 'የታሪክ ርዕስዎን ወይም ጭብጥ ይግለጹ...',
  'e.g., magic, dragon, adventure': 'ለምሳሌ ቅዠት፣ ድራጎን፣ ጀብድ',
  'Title For': 'ርዕስ ለ',
  'Title Style': 'የርዕስ ቅጥ',
  "Adventure": "ጀብድ",
  'Number of Titles': 'የርዕሶች ብዛት',
  'Book': 'መጽሐፍ',
  'Short Story': 'አጭር ታሪክ',
  'Novel': 'ልብ ወለድ',
  'Chapter': 'ምዕራፍ',
  'Series': 'ተከታታይ',
  'Simple': 'ቀላል',
  'Mysterious': 'ምስጢራዊ',
  'Dramatic': 'ድራማዊ',
  'Catchy': 'ማራኪ',
  'Poetic': 'ግጥማዊ',
  'Kids': 'ልጆች',
  'Blog Writer': 'ብሎግ ጸሐፊ',
  'Blog Topic': 'የብሎግ ርዕስ',
  'Target Keywords': 'ኢላማ ቁልፍ ቃላት',
  'Target Audience (Optional)': 'ኢላማ ተመልካች (አማራጭ)',
  'Enter your blog topic or title...': 'የብሎግ ርዕስዎን ያስገቡ...',
  'e.g., AI writing, content marketing, SEO tips':
      'ለምሳሌ AI ጽሑፍ፣ ይዘት ግብይት፣ SEO ምክሮች',
  'e.g., small business owners, bloggers': 'ለምሳሌ ትንንሽ ንግድ ባለቤቶች፣ ብሎገሮች',
  'Article Type': 'የጽሑፍ ዓይነት',
  'Writing Tone': 'የጽሑፍ ቃና',
  'Article Length': 'የጽሑፍ ርዝመት',
  'SEO Options': 'SEO አማራጮች',
  'Include Meta Description': 'ሜታ መግለጫ ያካትቱ',
  'Include Keyword Suggestions': 'የቁልፍ ቃል ጥቆማዎች ያካትቱ',
  'Include FAQs Section': 'ተደጋጋሚ ጥያቄዎች ክፍል ያካትቱ',
  'Please enter a blog topic': 'እባክዎ የብሎግ ርዕስ ያስገቡ',
  'Generate Blog': 'ብሎግ ያመንጩ',
  'SEO optimized articles with keywords': 'ከቁልፍ ቃላት ጋር SEO የተሻሻለ ጽሑፎች',
  'Write Blog': 'ብሎግ ይጻፉ',
  'SEO Article': 'SEO ጽሑፍ',
  'How-To Guide': 'እንዴት-ማድረግ መመሪያ',
  'Listicle': 'ዝርዝር ጽሑፍ',
  'Product Review': 'የምርት ግምገማ',
  'Opinion Piece': 'የአስተያየት ጽሑፍ',
  'News Article': 'የዜና ጽሑፍ',
  'Professional': 'ሙያዊ',
  'Casual': 'ተራ',
  'Informative': 'መረጃ ሰጪ',
  'Persuasive': 'አሳማኝ',
  'Friendly': 'ወዳጃዊ',
  'Authoritative': 'ስልጣናዊ',
  'Short (500-800)': 'አጭር (500-800)',
  'Medium (800-1500)': 'መካከለኛ (800-1500)',
  'Long (1500-2500)': 'ረጅም (1500-2500)',
  'Detailed (2500+)': 'ዝርዝር (2500+)',
  'YouTube Script': 'ዩቲዩብ ስክሪፕት',
  'Video Topic': 'የቪዲዮ ርዕስ',
  'Key Points (Optional)': 'ዋና ነጥቦች (አማራጭ)',
  'What is your video about?': 'ቪዲዮዎ ስለ ምንድነው?',
  'List key points to cover (optional)...': 'የሚሸፈኑ ዋና ነጥቦችን ዘርዝሩ (አማራጭ)...',
  'Video Duration': 'የቪዲዮ ቆይታ',
  'Script Options': 'የስክሪፕት አማራጮች',
  'Include Hook/Intro': 'መንጠቆ/መግቢያ ያካትቱ',
  'Include Call-to-Action': 'ለድርጊት ጥሪ ያካትቱ',
  'Include Timestamps': 'የጊዜ ምልክቶች ያካትቱ',
  'Please enter a video topic': 'እባክዎ የቪዲዮ ርዕስ ያስገቡ',
  'Generate Script': 'ስክሪፕት ያመንጩ',
  'Create scripts for videos & reels': 'ለቪዲዮዎች እና ሪሎች ስክሪፕቶች ይፍጠሩ',
  'Create Script': 'ስክሪፕት ይፍጠሩ',
  'Storytime': 'ታሪክ ጊዜ',
  'Documentary': 'ዘጋቢ ፊልም',
  'Short Reel': 'አጭር ሪል',
  'Educational': 'ትምህርታዊ',
  'Review': 'ግምገማ',
  'Tutorial': 'ማጠናከሪያ',
  '< 1 min (Shorts)': '< 1 ደቂቃ (ሾርትስ)',
  '1-3 min': '1-3 ደቂቃ',
  '5-10 min': '5-10 ደቂቃ',
  '10-20 min': '10-20 ደቂቃ',
  '20+ min': '20+ ደቂቃ',
  'Engaging': 'ማራኪ',
  'Energetic': 'ንቁ',
  'Calm': 'ረጋ ያለ',
  'Funny': 'አስቂኝ',
  'Inspired': 'ተመስጦ',
  'Film Script': 'ፊልም ስክሪፕት',
  'Stage Play': 'የመድረክ ተውኔት',
  'Scene Breakdown': 'የትዕይንት ትንተና',
  'Dialogue Only': 'ውይይት ብቻ',
  'Ad loading please wait..': 'ማስታወቂያ እየጫነ ነው እባክዎ ይጠብቁ..',
  'Words:': 'ቃላት:',
  'Reading:': 'ማንበብ:',
};
