import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ar = {
  AppKeys.lblChooseLanguage: "اختر اللغة",
  "All": "الجميع",
  "AI Story Generator": "مولد القصص بالذكاء الاصطناعي",
  "Story Generator": "مولد القصص",
  "Essay Writer": "كاتب المقالات",
  "Essay length": "طول المقال",
  "Script Generator": "كاتب النصوص",
  "Create original stories in seconds": "أنشئ قصصًا أصلية في ثوانٍ",
  "Academic writing made simple": "الكتابة الأكاديمية أصبحت بسيطة",
  "Generate powerful scripts for any medium": "أنشئ نصوصًا قوية لأي وسيلة",
  "Start Writing": "ابدأ الكتابة",
  "Create Now": "أنشئ الآن",
  "Start Generating": "ابدأ التوليد",
  "Your Stories": "قصصك",
  "No stories yet": "لا توجد قصص بعد",
  "Start creating your first story!": "ابدأ بإنشاء قصتك الأولى!",
  "Your Story Space Awaits": "مساحة قصصك في انتظارك",
  "Start your first story and see it appear here":
      "ابدأ قصتك الأولى وشاهدها تظهر هنا",
  "Language": "اللغة",
  "Rate us": "قيمنا",
  "Share us": "شاركنا",
  "Privacy Policy": "سياسة الخصوصية",
  "Settings": "الإعدادات",
  "Select Language": "اختر اللغة",
  "Dashboard": "لوحة التحكم",
  "BENEFITS": "المزايا",
  "Subscribe": "يشترك",
  "Weekly": "أسبوعي",
  "Monthly": "شهريا",
  "Yearly": "سنوي",
  "week": "أسبوع",
  "months": "شهور",
  "year": "سنة",
  "Terms & Condition": "الشروط والأحكام",
  "No Commitment. Cancel anytime": "لا يوجد التزام. يمكنك الإلغاء في أي وقت.",
  "No Payment Now": "لا يوجد دفع الآن",
  "3 days free": "3 أيام مجانية",
  "Start your free trial": "ابدأ تجربتك المجانية",
  "More detailed answers": "إجابات أكثر تفصيلاً",
  "Instant responds": "استجابة فورية",
  "Text recognition": "التعرف على النصوص",
  "Powered by AI": "مدعوم بالذكاء الاصطناعي",
  "Storytelleing": "رواية القصص",
  ' Power': "قوة",
  "Unlock your \nFill ": "افتح قفل \nFill الخاص بك",
  "Your History": "سجلك",
  "Terms and Conditions": "الشروط والأحكام",
  "Short": "قصير",
  "Medium": "متوسط",
  "Long": "طويل",
  "Length": "الطول",
  "Describe your topic...": "صف موضوعك...",
  "Set Creativity": "تحديد الإبداع",
  "Standard": "قياسي",
  "Creative": "إبداعي",
  "Complex": "معقد",
  "Select Genre": "اختر النوع",
  "Fantasy": "خيال",
  "Mystery": "غموض",
  "Thriller": "إثارة",
  "Script Tone": "نغمة البرنامج النصي",
  "Script Type": "نوع البرنامج النصي",
  "Comedy": "كوميديا",
  "Drama": "دراما",
  "Horror": "رعب",
  "Action": "أكشن",
  "Romance": "رومانسي",
  "Motivational": "تحفيزي",
  "Advertisement": "إعلان",
  "Fairy Tale": "حكاية خيالية",
  "Sci-Fi": "خيال علمي",
  "Select Style": "اختر الأسلوب",
  "Imaginative": "خيالي",
  "Innovative": "مبتكر",
  "Generate": "توليد",
  "Please wait...": "يرجى الانتظار...",
  "Result": "النتيجة",
  "Regenerate": "إعادة التوليد",
  "Download": "تحميل",
  "AI Story Writer": "كاتب القصص بالذكاء الاصطناعي",
  "Text copied to clipboard!": "تم نسخ النص إلى الحافظة!",
  "Please enter a topic": "يرجى إدخال موضوع",
  "Story Magic": "سحر القصص",
  "Let AI bring your thoughts to a full story":
      "دع الذكاء الاصطناعي يحول أفكارك إلى قصة كاملة",
  "Go Premium": "انتقل إلى البريميوم",
  "Unlock Everything": "فتح كل شيء",
  "Unlimited Story Generation": "توليد قصص غير محدود",
  "Write Longer & Detailed Essays": "اكتب مقالات أطول وأكثر تفصيلاً",
  "Advanced Script Writer": "كاتب السيناريو المتقدم",
  "Unlock All Styles & Tones": "فتح جميع الأنماط والنبرات",
  "No Word/Length Limit": "بدون حد للكلمات/الطول",
  "Remove All Ads": "إزالة جميع الإعلانات",
  "3 days free": "3 أيام مجاني",
  "Restore": "استعادة",
  "YouTube Video": "فيديو YouTube",
  "Podcast": "بودكاست",

  "AI Story Writer": "كاتب قصص ذكي",
  "Reel": "ريل",
  "Smart Scripts": "نصوص ذكية",
  "From concept to script—fast, easy, and creative":
      "من الفكرة إلى النص—بسرعة وسهولة وإبداع",
  "Perfect Essays": "مقالات مثالية",
  "You have reached your free limit":
      "لقد وصلت إلى الحد الأقصى المجاني الخاص بك",
  "Donwload": "التنزيلات",
  "Press again to exit app": "اضغط مرة أخرى للخروج من التطبيق",
  "Saved to files": "تم حفظ ملف TXT بنجاح!",
  "Error: Please try again": "خطأ: الرجاء المحاولة مرة أخرى",
  "Subscription expired": "انتهت صلاحية الاشتراك",
  "Purchase cancelled": "تم إلغاء الشراء",
  "Purchase failed": "فشل الشراء",
  "Restore failed": "فشلت عملية الاستعادة",
  "Purchase Successful!": "عملية الشراء ناجحة!",
  "Short (200-500 words)": "قصير (200-500 كلمة)",
  "Medium (500-1000 words)": "متوسط ​​(500-1000 كلمة)",
  "Large (1000+ words)": "كبير (1000+ كلمة)",
  "Academic Level": "المستوى الأكاديمي",
  "Type of Paper": "نوع الورقة",
  "High School": "المدرسة الثانوية",
  "College": "الكلية",
  "Short Film": "فيلم قصير",
  "University": "الجامعة",
  "Masters": "الماجستير",
  "Custom": "مخصص",
  "YouTube Video": "فيديو يوتيوب",
  "Podcast": "بودكاست",
  "Reel": "ريل",
  "Tiktok Video": "فيديو تيك توك",
  "Movie": "فيلم",
  "Expository": "توضيحي",
  "Argumentative": "جدلي",
  "Narrative": "سردي",
  "Descriptive": "وصفي",
  "Enjoying AI Story Generator?":
      "هل تستمتع باستخدام مولد القصص بالذكاء الاصطناعي؟",

  "We're sorry to hear that 😔": "نأسف لسماع ذلك 😔",
  "We'll try to improve 🙁": "سنحاول التحسن 🙁",
  "Thanks for your feedback 🙂": "شكرًا لملاحظاتك 🙂",
  "Great! We're glad you like it 😊": "رائع! يسعدنا أنك أحببته 😊",
  "Awesome! Thank you so much! 🎉": "مذهل! شكرًا جزيلاً لك! 🎉",
  "Maybe Later": "ربما لاحقًا",
  "Tap a star to rate your experience": "اضغط على نجمة لتقييم تجربتك",
  "Enjoying AI Math Solver?": "هل تستمتع باستخدام AI Math Solver؟",
  "Thank you for rating us": "شكرًا لتقييمك لنا",
  "Submit Rating": "إرسال التقييم",
  "Hindi": "الهندية",
  AppKeys.arabic: "العربية",
  AppKeys.chinese: "الصينية",
  AppKeys.english: "الإنجليزية",
  AppKeys.french: "الفرنسية",
  AppKeys.german: "الألمانية",
  AppKeys.hindi: "الهندية",
  AppKeys.indonesian: "الإندونيسية",
  AppKeys.japanese: "اليابانية",
  AppKeys.korean: "الكورية",
  AppKeys.portuguese: "البرتغالية",
  AppKeys.russian: "الروسية",
  AppKeys.spanish: "الإسبانية",
  AppKeys.turkish: "التركية",
};
