import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ar = {
  AppKeys.lblChooseLanguage: "اختر اللغة",
  "All": "الجميع",
  "AI Story Generator": "مولد القصص بالذكاء الاصطناعي",
  "Story Generator": "مولد القصص",
  "Essay Writer": "كاتب المقالات",
  "Essay length": "طول المقال",
  "Script Generator": "كاتب النصوص",
  "Create original stories in seconds": "أنشئ قصصًا أصلية في ثوانٍ",
  "Academic writing made simple": "الكتابة الأكاديمية أصبحت بسيطة",
  "Generate powerful scripts for any medium": "أنشئ نصوصًا قوية لأي وسيلة",
  "Start Writing": "ابدأ الكتابة",
  "Create Now": "أنشئ الآن",
  "Start Generating": "ابدأ التوليد",
  "Your Stories": "قصصك",
  "No stories yet": "لا توجد قصص بعد",
  "Start creating your first story!": "ابدأ بإنشاء قصتك الأولى!",
  "Your Story Space Awaits": "مساحة قصصك في انتظارك",
  "Start your first story and see it appear here":
      "ابدأ قصتك الأولى وشاهدها تظهر هنا",
  "Language": "اللغة",
  "Rate us": "قيمنا",
  "Share us": "شاركنا",
  "Privacy Policy": "سياسة الخصوصية",
  "Settings": "الإعدادات",
  "Select Language": "اختر اللغة",
  "Dashboard": "لوحة التحكم",
  "BENEFITS": "المزايا",
  "Subscribe": "يشترك",
  "Weekly": "أسبوعي",
  "Monthly": "شهريا",
  "Yearly": "سنوي",
  "week": "أسبوع",
  "months": "شهور",
  "year": "سنة",
  "Terms & Condition": "الشروط والأحكام",
  "No Commitment. Cancel anytime": "لا يوجد التزام. يمكنك الإلغاء في أي وقت.",
  "No Payment Now": "لا يوجد دفع الآن",
  "3 days free": "3 أيام مجانية",
  "Start your free trial": "ابدأ تجربتك المجانية",
  "More detailed answers": "إجابات أكثر تفصيلاً",
  "Instant responds": "استجابة فورية",
  "Text recognition": "التعرف على النصوص",
  "Powered by AI": "مدعوم بالذكاء الاصطناعي",
  "Storytelleing": "رواية القصص",
  ' Power': "قوة",
  "Unlock your \nFill ": "افتح قفل \nFill الخاص بك",
  "Your History": "سجلك",
  "Terms and Conditions": "الشروط والأحكام",
  "Short": "قصير",
  "Medium": "متوسط",
  "Long": "طويل",
  "Length": "الطول",
  "Describe your topic...": "صف موضوعك...",
  "Set Creativity": "تحديد الإبداع",
  "Standard": "قياسي",
  "Creative": "إبداعي",
  "Complex": "معقد",
  "Select Genre": "اختر النوع",
  "Fantasy": "خيال",
  "Mystery": "غموض",
  "Thriller": "إثارة",
  "Script Tone": "نغمة البرنامج النصي",
  "Script Type": "نوع البرنامج النصي",
  "Comedy": "كوميديا",
  "Drama": "دراما",
  "Horror": "رعب",
  "Action": "أكشن",
  "Romance": "رومانسي",
  "Motivational": "تحفيزي",
  "Advertisement": "إعلان",
  "Fairy Tale": "حكاية خيالية",
  "Sci-Fi": "خيال علمي",
  "Select Style": "اختر الأسلوب",
  "Imaginative": "خيالي",
  "Innovative": "مبتكر",
  "Generate": "توليد",
  "Please wait...": "يرجى الانتظار...",
  "Result": "النتيجة",
  "Regenerate": "إعادة التوليد",
  "Download": "تحميل",
  "AI Story Writer": "كاتب القصص بالذكاء الاصطناعي",
  "Text copied to clipboard!": "تم نسخ النص إلى الحافظة!",
  "Please enter a topic": "يرجى إدخال موضوع",
  "Story Magic": "سحر القصص",
  "Let AI bring your thoughts to a full story":
      "دع الذكاء الاصطناعي يحول أفكارك إلى قصة كاملة",
  "Go Premium": "انتقل إلى البريميوم",
  "Unlock Everything": "فتح كل شيء",
  "Unlimited Story Generation": "توليد قصص غير محدود",
  "Write Longer & Detailed Essays": "اكتب مقالات أطول وأكثر تفصيلاً",
  "Advanced Script Writer": "كاتب السيناريو المتقدم",
  "Unlock All Styles & Tones": "فتح جميع الأنماط والنبرات",
  "No Word/Length Limit": "بدون حد للكلمات/الطول",
  "Remove All Ads": "إزالة جميع الإعلانات",
  "Restore": "استعادة",
  "Smart Scripts": "نصوص ذكية",
  "From concept to script—fast, easy, and creative":
      "من الفكرة إلى النص—بسرعة وسهولة وإبداع",
  "Perfect Essays": "مقالات مثالية",
  "You have reached your free limit":
      "لقد وصلت إلى الحد الأقصى المجاني الخاص بك",
  "Donwload": "التنزيلات",
  "Press again to exit app": "اضغط مرة أخرى للخروج من التطبيق",
  "Saved to files": "تم حفظ ملف TXT بنجاح!",
  "Error: Please try again": "خطأ: الرجاء المحاولة مرة أخرى",
  "Subscription expired": "انتهت صلاحية الاشتراك",
  "Purchase cancelled": "تم إلغاء الشراء",
  "Purchase failed": "فشل الشراء",
  "Restore failed": "فشلت عملية الاستعادة",
  "Purchase Successful!": "عملية الشراء ناجحة!",
  "Short (200-500 words)": "قصير (200-500 كلمة)",
  "Medium (500-1000 words)": "متوسط ​​(500-1000 كلمة)",
  "Large (1000+ words)": "كبير (1000+ كلمة)",
  "Academic Level": "المستوى الأكاديمي",
  "Type of Paper": "نوع الورقة",
  "High School": "المدرسة الثانوية",
  "College": "الكلية",
  "Short Film": "فيلم قصير",
  "University": "الجامعة",
  "Masters": "الماجستير",
  "Custom": "مخصص",
  "Tiktok Video": "فيديو تيك توك",
  "Movie": "فيلم",
  "Expository": "توضيحي",
  "Argumentative": "جدلي",
  "Narrative": "سردي",
  "Descriptive": "وصفي",
  "Enjoying AI Story Generator?":
      "هل تستمتع باستخدام مولد القصص بالذكاء الاصطناعي؟",

  "We're sorry to hear that 😔": "نأسف لسماع ذلك 😔",
  "We'll try to improve 🙁": "سنحاول التحسن 🙁",
  "Thanks for your feedback 🙂": "شكرًا لملاحظاتك 🙂",
  "Great! We're glad you like it 😊": "رائع! يسعدنا أنك أحببته 😊",
  "Awesome! Thank you so much! 🎉": "مذهل! شكرًا جزيلاً لك! 🎉",
  "Maybe Later": "ربما لاحقًا",
  "Tap a star to rate your experience": "اضغط على نجمة لتقييم تجربتك",
  "Enjoying AI Math Solver?": "هل تستمتع باستخدام AI Math Solver؟",
  "Thank you for rating us": "شكرًا لتقييمك لنا",
  "Submit Rating": "إرسال التقييم",
  "Hindi": "الهندية",
  AppKeys.arabic: "العربية",
  AppKeys.chinese: "الصينية",
  AppKeys.english: "الإنجليزية",
  AppKeys.french: "الفرنسية",
  AppKeys.german: "الألمانية",
  AppKeys.hindi: "الهندية",
  AppKeys.indonesian: "الإندونيسية",
  AppKeys.japanese: "اليابانية",
  AppKeys.korean: "الكورية",
  AppKeys.portuguese: "البرتغالية",
  AppKeys.russian: "الروسية",
  AppKeys.spanish: "الإسبانية",
  AppKeys.turkish: "التركية",

  // New strings for download & actions
  'Download As': 'تنزيل كـ',
  'Choose format to download': 'اختر تنسيق التنزيل',
  'Text File': 'ملف نصي',
  'PDF File': 'ملف PDF',
  'Copy': 'نسخ',
  'Share': 'مشاركة',
  'Text copied!': 'تم نسخ النص!',
  'PDF saved successfully!': 'تم حفظ PDF بنجاح!',
  'Error creating PDF: Please try again':
      'خطأ في إنشاء PDF: يرجى المحاولة مرة أخرى',

  // Character Story Tool
  'Character Story': 'قصة الشخصية',
  'Character Details': 'تفاصيل الشخصية',
  'Character Name': 'اسم الشخصية',
  'Age (e.g., 25, Young Adult, Ancient)': 'العمر (مثلاً: 25، شاب، قديم)',
  'Personality (e.g., brave, shy, cunning)':
      'الشخصية (مثلاً: شجاع، خجول، ماكر)',
  'Role (e.g., Hero, Villain, Mentor)': 'الدور (مثلاً: بطل، شرير، مرشد)',
  'Additional Details (optional)': 'تفاصيل إضافية (اختياري)',
  'Output Style': 'نمط الإخراج',
  'Generate Character': 'إنشاء الشخصية',
  'Please enter character name': 'يرجى إدخال اسم الشخصية',
  'Please enter character role': 'يرجى إدخال دور الشخصية',
  'Detailed': 'مفصل',
  'Brief': 'موجز',
  'Elaborate': 'مفصل جداً',

  // Home Screen Tool Cards
  'Create detailed character backstories': 'إنشاء قصص خلفية مفصلة للشخصيات',
  'Create Character': 'إنشاء شخصية',
  'Transform and improve your existing stories': 'تحويل وتحسين قصصك الحالية',
  'Rewrite Now': 'أعد الكتابة الآن',
  'Generate catchy titles for your stories': 'إنشاء عناوين جذابة لقصصك',
  'Generate Titles': 'إنشاء عناوين',

  // Rewrite Story Tool
  'Rewrite Story': 'إعادة كتابة القصة',
  'Paste Your Story': 'الصق قصتك',
  'Paste your story here to rewrite...': 'الصق قصتك هنا لإعادة كتابتها...',
  'Select Tone': 'اختر النبرة',
  'Rewrite Style': 'نمط إعادة الكتابة',
  'Output Length': 'طول الإخراج',
  'Please paste your story': 'يرجى لصق قصتك',
  'Story is too short. Please provide more content.':
      'القصة قصيرة جداً. يرجى تقديم المزيد من المحتوى.',
  // Tone options
  'Same': 'نفس',
  'More Dramatic': 'أكثر دراماتيكية',
  'More Humorous': 'أكثر فكاهة',
  'More Emotional': 'أكثر عاطفية',
  'More Suspenseful': 'أكثر تشويقاً',
  'Lighter': 'أخف',
  // Style options
  'Improved': 'محسّن',
  'Simplified': 'مبسط',
  'More Descriptive': 'أكثر وصفاً',
  'More Dialogue': 'مزيد من الحوار',
  'More Action': 'مزيد من الأحداث',
  'Literary': 'أدبي',
  // Length options
  'Shorter': 'أقصر',
  'Longer': 'أطول',
  'Much Longer': 'أطول بكثير',

  // Title Generator Tool
  'Title Generator': 'مولد العناوين',
  'Story/Book Topic': 'موضوع القصة/الكتاب',
  'Keywords (Optional)': 'الكلمات المفتاحية (اختياري)',
  'Describe your story topic or theme...': 'صف موضوع أو سمة قصتك...',
  'e.g., magic, dragon, adventure': 'مثلاً: سحر، تنين، مغامرة',
  'Title For': 'عنوان لـ',
  'Title Style': 'نمط العنوان',
  'Number of Titles': 'عدد العناوين',
  // Type options
  'Book': 'كتاب',
  'Short Story': 'قصة قصيرة',
  'Novel': 'رواية',
  'Chapter': 'فصل',
  'Series': 'سلسلة',
  // Title Style options
  'Simple': 'بسيط',
  'Mysterious': 'غامض',
  'Dramatic': 'درامي',
  'Catchy': 'جذاب',
  'Poetic': 'شعري',
  // Genre options
  'Kids': 'أطفال',

  // Blog Writer Tool
  'Blog Writer': 'كاتب المدونات',
  'Blog Topic': 'موضوع المدونة',
  'Target Keywords': 'الكلمات المفتاحية المستهدفة',
  'Target Audience (Optional)': 'الجمهور المستهدف (اختياري)',
  'Enter your blog topic or title...': 'أدخل موضوع أو عنوان مدونتك...',
  'e.g., AI writing, content marketing, SEO tips':
      'مثلاً: كتابة الذكاء الاصطناعي، تسويق المحتوى، نصائح SEO',
  'e.g., small business owners, bloggers':
      'مثلاً: أصحاب الأعمال الصغيرة، المدونين',
  'Article Type': 'نوع المقال',
  'Writing Tone': 'نبرة الكتابة',
  'Article Length': 'طول المقال',
  'SEO Options': 'خيارات SEO',
  'Include Meta Description': 'تضمين الوصف التعريفي',
  'Include Keyword Suggestions': 'تضمين اقتراحات الكلمات المفتاحية',
  'Include FAQs Section': 'تضمين قسم الأسئلة الشائعة',
  'Please enter a blog topic': 'يرجى إدخال موضوع المدونة',
  'Generate Blog': 'إنشاء مدونة',
  'SEO optimized articles with keywords':
      'مقالات محسنة لـ SEO مع كلمات مفتاحية',
  'Write Blog': 'كتابة مدونة',
  // Article Types
  'SEO Article': 'مقال SEO',
  'How-To Guide': 'دليل إرشادي',
  'Listicle': 'مقال قائمة',
  'Product Review': 'مراجعة منتج',
  'Opinion Piece': 'مقال رأي',
  'News Article': 'مقال إخباري',
  // Blog Tones
  'Professional': 'احترافي',
  'Casual': 'غير رسمي',
  'Informative': 'إعلامي',
  'Persuasive': 'إقناعي',
  'Friendly': 'ودود',
  'Authoritative': 'موثوق',
  // Blog Lengths
  'Short (500-800)': 'قصير (500-800)',
  'Medium (800-1500)': 'متوسط (800-1500)',
  'Long (1500-2500)': 'طويل (1500-2500)',
  'Detailed (2500+)': 'مفصل (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'سكريبت يوتيوب',
  'Video Topic': 'موضوع الفيديو',
  'Key Points (Optional)': 'النقاط الرئيسية (اختياري)',
  'What is your video about?': 'ما موضوع الفيديو الخاص بك؟',
  'List key points to cover (optional)...': 'اذكر النقاط الرئيسية (اختياري)...',
  'Video Duration': 'مدة الفيديو',
  'Script Options': 'خيارات السكريبت',
  'Include Hook/Intro': 'تضمين مقدمة جذابة',
  'Include Call-to-Action': 'تضمين دعوة للعمل',
  'Include Timestamps': 'تضمين الطوابع الزمنية',
  'Please enter a video topic': 'يرجى إدخال موضوع الفيديو',
  'Generate Script': 'إنشاء سكريبت',
  'Create scripts for videos & reels': 'إنشاء سكريبتات للفيديوهات والريلز',
  'Create Script': 'إنشاء سكريبت',
  // Script Types
  'Storytime': 'وقت القصة',
  'Documentary': 'وثائقي',
  'Short Reel': 'ريل قصير',
  'Educational': 'تعليمي',
  'Review': 'مراجعة',
  'Tutorial': 'درس تعليمي',
  // Durations
  '< 1 min (Shorts)': '< 1 دقيقة (شورتس)',
  '1-3 min': '1-3 دقائق',
  '5-10 min': '5-10 دقائق',
  '10-20 min': '10-20 دقيقة',
  '20+ min': '20+ دقيقة',
  // Script Tones
  'Engaging': 'جذاب',
  'Energetic': 'حيوي',
  'Calm': 'هادئ',
  'Funny': 'مضحك',

  // Story Generator - Styles
  'Inspired': 'مُلهَم',

  // Script Writer - Script Tones (formats)
  'Film Script': 'سيناريو فيلم',
  'Stage Play': 'مسرحية',
  'Scene Breakdown': 'تحليل المشهد',
  'Dialogue Only': 'حوار فقط',

  // Ad & UI
  'Ad loading please wait..': 'جاري تحميل الإعلان، يرجى الانتظار..',

  // Word Counter & Reading Time
  'Words:': 'الكلمات:',
  'Reading:': 'القراءة:',

  // Missing strings from hi.dart
  'Adventure': 'مغامرة',
};
