import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> az = {
  AppKeys.lblChooseLanguage: "Dil seçin",
  "All": "Hamısı",
  "AI Story Generator": "AI Hekayə Generatoru",
  "Story Generator": "Hekayə Generatoru",
  "Essay Writer": "Esse Yazıçısı",
  "Essay length": "Esse uzunluğu",
  "Script Generator": "Ssenari Generatoru",
  "Create original stories in seconds":
      "Saniyələr ərzində orijinal hekayələr yaradın",
  "Academic writing made simple": "Akademik yazı sadələşdirildi",
  "Generate powerful scripts for any medium":
      "İstənilən mühit üçün güclü ssenarilər yaradın",
  "Start Writing": "Yazmağa Başla",
  "Create Now": "İndi Yarat",
  "Start Generating": "Yaratmağa Başla",
  "Your Stories": "Hekayələriniz",
  "No stories yet": "Hələ hekayə yoxdur",
  "Start creating your first story!": "İlk hekayənizi yaratmağa başlayın!",
  "Your Story Space Awaits": "Hekayə Məkanınız Gözləyir",
  "Start your first story and see it appear here":
      "İlk hekayənizi başlayın və burada görün",
  "Language": "Dil",
  "Rate us": "Bizi qiymətləndirin",
  "Share us": "Bizi paylaşın",
  "Privacy Policy": "Gizlilik Siyasəti",
  "Settings": "Parametrlər",
  "Select Language": "Dil Seçin",
  "Dashboard": "İdarə Paneli",
  "BENEFITS": "FAYDALAR",
  "Subscribe": "Abunə ol",
  "Weekly": "Həftəlik",
  "Monthly": "Aylıq",
  "Yearly": "İllik",
  "week": "həftə",
  "months": "ay",
  "year": "il",
  "Terms & Condition": "Şərtlər və Qaydalar",
  "No Commitment. Cancel anytime":
      "Heç bir öhdəlik yoxdur. İstənilən vaxt ləğv edin",
  "No Payment Now": "İndi Ödəniş Yoxdur",
  "3 days free": "3 gün pulsuz",
  "Start your free trial": "Pulsuz sınağınıza başlayın",
  "More detailed answers": "Daha ətraflı cavablar",
  "Instant responds": "Ani cavab",
  "Text recognition": "Mətn tanıma",
  "Powered by AI": "AI ilə işləyir",
  "Storytelleing": "Hekayə Danışma",
  ' Power': " Güc",
  "Unlock your \nFill ": "Açın \nFill ",
  "Your History": "Tarixçəniz",
  "Terms and Conditions": "Şərtlər və Qaydalar",
  "Short": "Qısa",
  "Medium": "Orta",
  "Long": "Uzun",
  "Length": "Uzunluq",
  "Describe your topic...": "Mövzunuzu təsvir edin...",
  "Set Creativity": "Yaradıcılığı Təyin Et",
  "Standard": "Standart",
  "Creative": "Yaradıcı",
  "Complex": "Mürəkkəb",
  "Select Genre": "Janr Seçin",
  "Fantasy": "Fantaziya",
  "Mystery": "Sirr",
  "Thriller": "Triller",
  "Script Tone": "Ssenari Tonu",
  "Script Type": "Ssenari Növü",
  "Comedy": "Komediya",
  "Drama": "Dram",
  "Horror": "Dəhşət",
  "Action": "Hərəkət",
  "Romance": "Romantika",
  "Go Premium": "Premium Ol",
  "Unlock Everything": "Hər Şeyi Aç",
  "Unlimited Story Generation": "Limitsiz Hekayə Yaratma",
  "Write Longer & Detailed Essays": "Daha Uzun və Ətraflı Esselər Yazın",
  "Advanced Script Writer": "Qabaqcıl Ssenari Yazıçısı",
  "Unlock All Styles & Tones": "Bütün Üslub və Tonları Açın",
  "No Word/Length Limit": "Söz/Uzunluq Limiti Yoxdur",
  "Remove All Ads": "Bütün Reklamları Silin",
  "Restore": "Bərpa Et",
  "YouTube Video": "YouTube Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivasion",
  "Advertisement": "Reklam",
  "Fairy Tale": "Nağıl",
  "Sci-Fi": "Elmi Fantastika",
  "Select Style": "Üslub Seçin",
  "Imaginative": "Təxəyyüllü",
  "Innovative": "İnnovativ",
  "AI Story Writer": "AI Hekayə Yazıçısı",
  "Generate": "Yarat",
  "Please wait...": "Zəhmət olmasa gözləyin...",
  "Result": "Nəticə",
  "Regenerate": "Yenidən Yarat",
  "Download": "Yüklə",
  "Text copied to clipboard!": "Mətn buferə kopyalandı!",
  "Please enter a topic": "Zəhmət olmasa mövzu daxil edin",
  "Story Magic": "Hekayə Sehri",
  "Let AI bring your thoughts to a full story":
      "AI düşüncələrinizi tam hekayəyə çevirsin",
  "Smart Scripts": "Ağıllı Ssenarilər",
  "From concept to script—fast, easy, and creative":
      "Konseptdən ssenariyə—sürətli, asan və yaradıcı",
  "Perfect Essays": "Mükəmməl Esselər",
  "You have reached your free limit": "Pulsuz limitinizə çatdınız",
  "Donwload": "Yüklə",
  "Press again to exit app": "Tətbiqdən çıxmaq üçün yenidən basın",
  "Saved to files": "TXT faylı uğurla saxlanıldı!",
  "Error: Please try again": "Xəta: Zəhmət olmasa yenidən cəhd edin",
  "Subscription expired": "Abunə müddəti bitdi",
  "Purchase cancelled": "Alış ləğv edildi",
  "Purchase failed": "Alış uğursuz oldu",
  "Restore failed": "Bərpa uğursuz oldu",
  "Purchase Successful!": "Alış Uğurlu!",
  "Short (200-500 words)": "Qısa (200-500 söz)",
  "Medium (500-1000 words)": "Orta (500-1000 söz)",
  "Large (1000+ words)": "Böyük (1000+ söz)",
  "Academic Level": "Akademik Səviyyə",
  "Type of Paper": "Kağız Növü",
  "High School": "Orta Məktəb",
  "College": "Kollec",
  "Short Film": "Qısametrajlı Film",
  "University": "Universitet",
  "Masters": "Magistr",
  "Custom": "Xüsusi",
  "Tiktok Video": "TikTok Video",
  "Movie": "Film",
  "Expository": "İzahedici",
  "Argumentative": "Arqumentativ",
  "Narrative": "Nəqli",
  "Descriptive": "Təsviri",
  "We're sorry to hear that 😔": "Bunu eşitdiyimizə üzgünük 😔",
  "We'll try to improve 🙁": "Yaxşılaşdırmağa çalışacağıq 🙁",
  "Thanks for your feedback 🙂": "Rəyiniz üçün təşəkkürlər 🙂",
  "Great! We're glad you like it 😊": "Əla! Bəyəndiyinizə sevinirik 😊",
  "Awesome! Thank you so much! 🎉": "Möhtəşəm! Çox təşəkkürlər! 🎉",
  "Maybe Later": "Bəlkə Sonra",
  "Tap a star to rate your experience":
      "Təcrübənizi qiymətləndirmək üçün ulduza toxunun",
  "Enjoying AI Math Solver?": "AI Riyaziyyat Həlledicisini bəyənirsiniz?",
  "Thank you for rating us": "Bizi qiymətləndirdiyiniz üçün təşəkkürlər",
  "Submit Rating": "Reytinqi Göndər",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "AI Hekayə Generatorunu bəyənirsiniz?",
  AppKeys.arabic: "Ərəb",
  AppKeys.chinese: "Çin",
  AppKeys.english: "İngilis",
  AppKeys.french: "Fransız",
  AppKeys.german: "Alman",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "İndoneziya",
  AppKeys.japanese: "Yapon",
  AppKeys.korean: "Koreya",
  AppKeys.portuguese: "Portuqal",
  AppKeys.russian: "Rus",
  AppKeys.spanish: "İspan",
  AppKeys.turkish: "Türk",
  'Download As': 'Olaraq Yüklə',
  'Choose format to download': 'Yükləmək üçün format seçin',
  'Text File': 'Mətn Faylı',
  'PDF File': 'PDF Faylı',
  'Copy': 'Kopyala',
  'Share': 'Paylaş',
  'Text copied!': 'Mətn kopyalandı!',
  'PDF saved successfully!': 'PDF uğurla saxlanıldı!',
  'Error creating PDF: Please try again':
      'PDF yaratma xətası: Zəhmət olmasa yenidən cəhd edin',
  'Character Story': 'Xarakter Hekayəsi',
  'Character Details': 'Xarakter Təfərrüatları',
  'Character Name': 'Xarakter Adı',
  'Age (e.g., 25, Young Adult, Ancient)': 'Yaş (məs., 25, Gənc Yetkin, Qədim)',
  'Personality (e.g., brave, shy, cunning)':
      'Şəxsiyyət (məs., cəsur, utancaq, hiyləgər)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (məs., Qəhrəman, Cani, Mentor)',
  'Additional Details (optional)': 'Əlavə Təfərrüatlar (isteğe bağlı)',
  'Output Style': 'Çıxış Üslubu',
  'Generate Character': 'Xarakter Yarat',
  'Please enter character name': 'Zəhmət olmasa xarakter adı daxil edin',
  'Please enter character role': 'Zəhmət olmasa xarakter rolu daxil edin',
  'Detailed': 'Ətraflı',
  'Brief': 'Qısa',
  'Elaborate': 'Geniş',
  'Create detailed character backstories':
      'Ətraflı xarakter keçmiş hekayələri yaradın',
  'Create Character': 'Xarakter Yarat',
  'Transform and improve your existing stories':
      'Mövcud hekayələrinizi dəyişdirin və yaxşılaşdırın',
  'Rewrite Now': 'İndi Yenidən Yaz',
  'Generate catchy titles for your stories':
      'Hekayələriniz üçün cəlbedici başlıqlar yaradın',
  'Generate Titles': 'Başlıqlar Yarat',
  'Rewrite Story': 'Hekayəni Yenidən Yaz',
  'Paste Your Story': 'Hekayənizi Yapışdırın',
  'Paste your story here to rewrite...':
      'Yenidən yazmaq üçün hekayənizi buraya yapışdırın...',
  'Select Tone': 'Ton Seçin',
  'Rewrite Style': 'Yenidən Yazma Üslubu',
  'Output Length': 'Çıxış Uzunluğu',
  'Please paste your story': 'Zəhmət olmasa hekayənizi yapışdırın',
  'Story is too short. Please provide more content.':
      'Hekayə çox qısadır. Zəhmət olmasa daha çox məzmun təqdim edin.',
  'Same': 'Eyni',
  'More Dramatic': 'Daha Dramatik',
  'More Humorous': 'Daha Yumorlu',
  'More Emotional': 'Daha Emosional',
  'More Suspenseful': 'Daha Gərginlikli',
  'Lighter': 'Daha Yüngül',
  'Improved': 'Təkmilləşdirilmiş',
  'Simplified': 'Sadələşdirilmiş',
  'More Descriptive': 'Daha Təsviri',
  'More Dialogue': 'Daha Çox Dialoq',
  'More Action': 'Daha Çox Hərəkət',
  'Literary': 'Ədəbi',
  'Shorter': 'Daha Qısa',
  'Longer': 'Daha Uzun',
  'Much Longer': 'Çox Daha Uzun',
  'Title Generator': 'Başlıq Generatoru',
  'Story/Book Topic': 'Hekayə/Kitab Mövzusu',
  'Keywords (Optional)': 'Açar Sözlər (İsteğe bağlı)',
  'Describe your story topic or theme...':
      'Hekayə mövzunuzu və ya temanızı təsvir edin...',
  'e.g., magic, dragon, adventure': 'məs., sehr, əjdaha, macəra',
  'Title For': 'Başlıq Üçün',
  'Title Style': 'Başlıq Üslubu',
  "Adventure": "Macəra",
  'Number of Titles': 'Başlıq Sayı',
  'Book': 'Kitab',
  'Short Story': 'Qısa Hekayə',
  'Novel': 'Roman',
  'Chapter': 'Fəsil',
  'Series': 'Seriya',
  'Simple': 'Sadə',
  'Mysterious': 'Sirli',
  'Dramatic': 'Dramatik',
  'Catchy': 'Cəlbedici',
  'Poetic': 'Poetik',
  'Kids': 'Uşaqlar',
  'Blog Writer': 'Bloq Yazıçısı',
  'Blog Topic': 'Bloq Mövzusu',
  'Target Keywords': 'Hədəf Açar Sözlər',
  'Target Audience (Optional)': 'Hədəf Auditoriya (İsteğe bağlı)',
  'Enter your blog topic or title...':
      'Bloq mövzunuzu və ya başlığınızı daxil edin...',
  'e.g., AI writing, content marketing, SEO tips':
      'məs., AI yazı, kontent marketinq, SEO məsləhətləri',
  'e.g., small business owners, bloggers':
      'məs., kiçik biznes sahibləri, bloqqerlər',
  'Article Type': 'Məqalə Növü',
  'Writing Tone': 'Yazı Tonu',
  'Article Length': 'Məqalə Uzunluğu',
  'SEO Options': 'SEO Seçimləri',
  'Include Meta Description': 'Meta Təsviri Daxil Et',
  'Include Keyword Suggestions': 'Açar Söz Təklifləri Daxil Et',
  'Include FAQs Section': 'Tez-tez Verilən Suallar Bölməsini Daxil Et',
  'Please enter a blog topic': 'Zəhmət olmasa bloq mövzusu daxil edin',
  'Generate Blog': 'Bloq Yarat',
  'SEO optimized articles with keywords':
      'Açar sözlərlə SEO optimallaşdırılmış məqalələr',
  'Write Blog': 'Bloq Yaz',
  'SEO Article': 'SEO Məqaləsi',
  'How-To Guide': 'Necə Etməli Bələdçi',
  'Listicle': 'Siyahı Məqaləsi',
  'Product Review': 'Məhsul İcmalı',
  'Opinion Piece': 'Fikir Yazısı',
  'News Article': 'Xəbər Məqaləsi',
  'Professional': 'Peşəkar',
  'Casual': 'Sərbəst',
  'Informative': 'Məlumatlandırıcı',
  'Persuasive': 'İnandırıcı',
  'Friendly': 'Dostcasına',
  'Authoritative': 'Nüfuzlu',
  'Short (500-800)': 'Qısa (500-800)',
  'Medium (800-1500)': 'Orta (800-1500)',
  'Long (1500-2500)': 'Uzun (1500-2500)',
  'Detailed (2500+)': 'Ətraflı (2500+)',
  'YouTube Script': 'YouTube Ssenarisi',
  'Video Topic': 'Video Mövzusu',
  'Key Points (Optional)': 'Əsas Nöqtələr (İsteğe bağlı)',
  'What is your video about?': 'Videonuz nə haqqındadır?',
  'List key points to cover (optional)...':
      'Əhatə ediləcək əsas nöqtələri sadalayın (isteğe bağlı)...',
  'Video Duration': 'Video Müddəti',
  'Script Options': 'Ssenari Seçimləri',
  'Include Hook/Intro': 'Kanca/Giriş Daxil Et',
  'Include Call-to-Action': 'Fəaliyyətə Çağırış Daxil Et',
  'Include Timestamps': 'Zaman Damğaları Daxil Et',
  'Please enter a video topic': 'Zəhmət olmasa video mövzusu daxil edin',
  'Generate Script': 'Ssenari Yarat',
  'Create scripts for videos & reels':
      'Videolar və reellər üçün ssenarilər yaradın',
  'Create Script': 'Ssenari Yarat',
  'Storytime': 'Hekayə Vaxtı',
  'Documentary': 'Sənədli',
  'Short Reel': 'Qısa Reel',
  'Educational': 'Təhsil',
  'Review': 'İcmal',
  'Tutorial': 'Dərslik',
  '< 1 min (Shorts)': '< 1 dəq (Shorts)',
  '1-3 min': '1-3 dəq',
  '5-10 min': '5-10 dəq',
  '10-20 min': '10-20 dəq',
  '20+ min': '20+ dəq',
  'Engaging': 'Cəlbedici',
  'Energetic': 'Enerjili',
  'Calm': 'Sakit',
  'Funny': 'Məzəli',
  'Inspired': 'İlhamlanmış',
  'Film Script': 'Film Ssenarisi',
  'Stage Play': 'Səhnə Pyesi',
  'Scene Breakdown': 'Səhnə Təhlili',
  'Dialogue Only': 'Yalnız Dialoq',
  'Ad loading please wait..': 'Reklam yüklənir, zəhmət olmasa gözləyin..',
  'Words:': 'Sözlər:',
  'Reading:': 'Oxuma:',
};
