import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> be = {
  AppKeys.lblChooseLanguage: "Выберыце мову",
  "All": "Усё",
  "AI Story Generator": "AI Генератар Гісторый",
  "Story Generator": "Генератар Гісторый",
  "Essay Writer": "Аўтар Эсэ",
  "Essay length": "Даўжыня эсэ",
  "Script Generator": "Генератар Сцэнарыяў",
  "Create original stories in seconds":
      "Ствараце арыгінальныя гісторыі за секунды",
  "Academic writing made simple": "Акадэмічнае пісьмо стала простым",
  "Generate powerful scripts for any medium":
      "Генеруйце магутныя сцэнарыі для любога сродку",
  "Start Writing": "Пачаць Пісаць",
  "Create Now": "Стварыць Зараз",
  "Start Generating": "Пачаць Генерацыю",
  "Your Stories": "Вашы Гісторыі",
  "No stories yet": "Пакуль няма гісторый",
  "Start creating your first story!": "Пачніце ствараць сваю першую гісторыю!",
  "Your Story Space Awaits": "Ваша Прастора для Гісторый Чакае",
  "Start your first story and see it appear here":
      "Пачніце сваю першую гісторыю і ўбачце яе тут",
  "Language": "Мова",
  "Rate us": "Ацаніце нас",
  "Share us": "Падзяліцеся намі",
  "Privacy Policy": "Палітыка Прыватнасці",
  "Settings": "Налады",
  "Select Language": "Выберыце Мову",
  "Dashboard": "Панэль Кіравання",
  "BENEFITS": "ПЕРАВАГІ",
  "Subscribe": "Падпісацца",
  "Weekly": "Штотыднёва",
  "Monthly": "Штомесяц",
  "Yearly": "Штогод",
  "week": "тыдзень",
  "months": "месяцы",
  "year": "год",
  "Terms & Condition": "Умовы і Палажэнні",
  "No Commitment. Cancel anytime":
      "Без абавязацельстваў. Адмяніць можна ў любы час",
  "No Payment Now": "Без Аплаты Зараз",
  "3 days free": "3 дні бясплатна",
  "Start your free trial": "Пачніце бясплатны пробны перыяд",
  "More detailed answers": "Больш падрабязныя адказы",
  "Instant responds": "Імгненны адказ",
  "Text recognition": "Распазнаванне тэксту",
  "Powered by AI": "На базе AI",
  "Storytelleing": "Апавяданне",
  ' Power': " Сіла",
  "Unlock your \nFill ": "Разблакуйце ваш \nFill ",
  "Your History": "Ваша Гісторыя",
  "Terms and Conditions": "Умовы і Палажэнні",
  "Short": "Кароткі",
  "Medium": "Сярэдні",
  "Long": "Доўгі",
  "Length": "Даўжыня",
  "Describe your topic...": "Апішыце вашу тэму...",
  "Set Creativity": "Усталяваць Крэатыўнасць",
  "Standard": "Стандартны",
  "Creative": "Крэатыўны",
  "Complex": "Складаны",
  "Select Genre": "Выберыце Жанр",
  "Fantasy": "Фэнтэзі",
  "Mystery": "Таямніца",
  "Thriller": "Трылер",
  "Script Tone": "Тон Сцэнарыя",
  "Script Type": "Тып Сцэнарыя",
  "Comedy": "Камедыя",
  "Drama": "Драма",
  "Horror": "Жахі",
  "Action": "Баявік",
  "Romance": "Раманс",
  "Go Premium": "Стаць Прэміум",
  "Unlock Everything": "Разблакаваць Усё",
  "Unlimited Story Generation": "Неабмежаваная Генерацыя Гісторый",
  "Write Longer & Detailed Essays": "Пішыце Даўжэйшыя і Падрабязныя Эсэ",
  "Advanced Script Writer": "Пашыраны Аўтар Сцэнарыяў",
  "Unlock All Styles & Tones": "Разблакаваць Усе Стылі і Тоны",
  "No Word/Length Limit": "Без Абмежавання Слоў/Даўжыні",
  "Remove All Ads": "Выдаліць Усю Рэкламу",
  "Restore": "Аднавіць",
  "YouTube Video": "YouTube Відэа",
  "Podcast": "Падкаст",
  "Reel": "Рэел",
  "Motivational": "Матывацыйны",
  "Advertisement": "Рэклама",
  "Fairy Tale": "Казка",
  "Sci-Fi": "Навукова-фантастычны",
  "Select Style": "Выберыце Стыль",
  "Imaginative": "Уяўны",
  "Innovative": "Інавацыйны",
  "AI Story Writer": "AI Аўтар Гісторый",
  "Generate": "Генераваць",
  "Please wait...": "Калі ласка, пачакайце...",
  "Result": "Вынік",
  "Regenerate": "Рэгенераваць",
  "Download": "Спампаваць",
  "Text copied to clipboard!": "Тэкст скапіяваны ў буфер абмену!",
  "Please enter a topic": "Калі ласка, увядзіце тэму",
  "Story Magic": "Магія Гісторый",
  "Let AI bring your thoughts to a full story":
      "Дазвольце AI ператварыць вашы думкі ў поўную гісторыю",
  "Smart Scripts": "Разумныя Сцэнарыі",
  "From concept to script—fast, easy, and creative":
      "Ад канцэпцыі да сцэнарыя—хутка, лёгка і крэатыўна",
  "Perfect Essays": "Ідэальныя Эсэ",
  "You have reached your free limit": "Вы дасягнулі бясплатнага ліміту",
  "Donwload": "Спампаваць",
  "Press again to exit app": "Націсніце зноў, каб выйсці з праграмы",
  "Saved to files": "TXT файл паспяхова захаваны!",
  "Error: Please try again": "Памылка: Калі ласка, паспрабуйце зноў",
  "Subscription expired": "Падпіска скончылася",
  "Purchase cancelled": "Пакупка адменена",
  "Purchase failed": "Пакупка не ўдалася",
  "Restore failed": "Аднаўленне не ўдалося",
  "Purchase Successful!": "Пакупка Паспяховая!",
  "Short (200-500 words)": "Кароткі (200-500 слоў)",
  "Medium (500-1000 words)": "Сярэдні (500-1000 слоў)",
  "Large (1000+ words)": "Вялікі (1000+ слоў)",
  "Academic Level": "Акадэмічны Ўзровень",
  "Type of Paper": "Тып Працы",
  "High School": "Сярэдняя Школа",
  "College": "Каледж",
  "Short Film": "Кароткаметражны Фільм",
  "University": "Універсітэт",
  "Masters": "Магістр",
  "Custom": "Карыстальніцкі",
  "Tiktok Video": "TikTok Відэа",
  "Movie": "Фільм",
  "Expository": "Тлумачальны",
  "Argumentative": "Аргументацыйны",
  "Narrative": "Наратыўны",
  "Descriptive": "Апісальны",
  "We're sorry to hear that 😔": "Нам шкада гэта чуць 😔",
  "We'll try to improve 🙁": "Мы паспрабуем палепшыць 🙁",
  "Thanks for your feedback 🙂": "Дзякуй за ваш водгук 🙂",
  "Great! We're glad you like it 😊": "Выдатна! Мы рады, што вам падабаецца 😊",
  "Awesome! Thank you so much! 🎉": "Цудоўна! Вялікі дзякуй! 🎉",
  "Maybe Later": "Магчыма Пазней",
  "Tap a star to rate your experience":
      "Націсніце на зорку, каб ацаніць ваш вопыт",
  "Enjoying AI Math Solver?": "Вам падабаецца AI Math Solver?",
  "Thank you for rating us": "Дзякуй, што ацанілі нас",
  "Submit Rating": "Адправіць Ацэнку",
  "Hindi": "Хіндзі",
  "Enjoying AI Story Generator?": "Вам падабаецца AI Генератар Гісторый?",
  AppKeys.arabic: "Арабская",
  AppKeys.chinese: "Кітайская",
  AppKeys.english: "Англійская",
  AppKeys.french: "Французская",
  AppKeys.german: "Нямецкая",
  AppKeys.hindi: "Хіндзі",
  AppKeys.indonesian: "Інданезійская",
  AppKeys.japanese: "Японская",
  AppKeys.korean: "Карэйская",
  AppKeys.portuguese: "Партугальская",
  AppKeys.russian: "Руская",
  AppKeys.spanish: "Іспанская",
  AppKeys.turkish: "Турэцкая",
  'Download As': 'Спампаваць Як',
  'Choose format to download': 'Выберыце фармат для спампоўкі',
  'Text File': 'Тэкставы Файл',
  'PDF File': 'PDF Файл',
  'Copy': 'Капіяваць',
  'Share': 'Падзяліцца',
  'Text copied!': 'Тэкст скапіяваны!',
  'PDF saved successfully!': 'PDF паспяхова захаваны!',
  'Error creating PDF: Please try again':
      'Памылка стварэння PDF: Калі ласка, паспрабуйце зноў',
  'Character Story': 'Гісторыя Персанажа',
  'Character Details': 'Дэталі Персанажа',
  'Character Name': 'Імя Персанажа',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Узрост (напр., 25, Малады Дарослы, Старажытны)',
  'Personality (e.g., brave, shy, cunning)':
      'Характар (напр., адважны, сарамлівы, хітры)',
  'Role (e.g., Hero, Villain, Mentor)':
      'Роля (напр., Герой, Злачынец, Настаўнік)',
  'Additional Details (optional)': 'Дадатковыя Дэталі (неабавязкова)',
  'Output Style': 'Стыль Вываду',
  'Generate Character': 'Генераваць Персанажа',
  'Please enter character name': 'Калі ласка, увядзіце імя персанажа',
  'Please enter character role': 'Калі ласка, увядзіце ролю персанажа',
  'Detailed': 'Падрабязны',
  'Brief': 'Кароткі',
  'Elaborate': 'Разгорнуты',
  'Create detailed character backstories':
      'Стварыце падрабязныя гісторыі персанажаў',
  'Create Character': 'Стварыць Персанажа',
  'Transform and improve your existing stories':
      'Пераўтварыце і палепшыце вашы існуючыя гісторыі',
  'Rewrite Now': 'Перапісаць Зараз',
  'Generate catchy titles for your stories':
      'Генеруйце прывабныя загалоўкі для вашых гісторый',
  'Generate Titles': 'Генераваць Загалоўкі',
  'Rewrite Story': 'Перапісаць Гісторыю',
  'Paste Your Story': 'Устаўце Вашу Гісторыю',
  'Paste your story here to rewrite...':
      'Устаўце вашу гісторыю тут, каб перапісаць...',
  'Select Tone': 'Выберыце Тон',
  'Rewrite Style': 'Стыль Перапісвання',
  'Output Length': 'Даўжыня Вываду',
  'Please paste your story': 'Калі ласка, устаўце вашу гісторыю',
  'Story is too short. Please provide more content.':
      'Гісторыя занадта кароткая. Калі ласка, дадайце больш зместу.',
  'Same': 'Такі ж',
  'More Dramatic': 'Больш Драматычны',
  'More Humorous': 'Больш Гумарыстычны',
  'More Emotional': 'Больш Эмацыйны',
  'More Suspenseful': 'Больш Інтрыгуючы',
  'Lighter': 'Лягчэйшы',
  'Improved': 'Палепшаны',
  'Simplified': 'Спрошчаны',
  'More Descriptive': 'Больш Апісальны',
  'More Dialogue': 'Больш Дыялогу',
  'More Action': 'Больш Дзеянняў',
  'Literary': 'Літаратурны',
  'Shorter': 'Карацейшы',
  'Longer': 'Даўжэйшы',
  'Much Longer': 'Значна Даўжэйшы',
  'Title Generator': 'Генератар Загалоўкаў',
  'Story/Book Topic': 'Тэма Гісторыі/Кнігі',
  'Keywords (Optional)': 'Ключавыя Словы (Неабавязкова)',
  'Describe your story topic or theme...':
      'Апішыце тэму або тэматыку вашай гісторыі...',
  'e.g., magic, dragon, adventure': 'напр., магія, дракон, прыгоды',
  'Title For': 'Загаловак Для',
  'Title Style': 'Стыль Загалоўка',
  "Adventure": "Прыгоды",
  'Number of Titles': 'Колькасць Загалоўкаў',
  'Book': 'Кніга',
  'Short Story': 'Апавяданне',
  'Novel': 'Раман',
  'Chapter': 'Раздзел',
  'Series': 'Серыя',
  'Simple': 'Просты',
  'Mysterious': 'Таямнічы',
  'Dramatic': 'Драматычны',
  'Catchy': 'Прывабны',
  'Poetic': 'Паэтычны',
  'Kids': 'Дзеці',
  'Blog Writer': 'Блог Аўтар',
  'Blog Topic': 'Тэма Блога',
  'Target Keywords': 'Мэтавыя Ключавыя Словы',
  'Target Audience (Optional)': 'Мэтавая Аўдыторыя (Неабавязкова)',
  'Enter your blog topic or title...': 'Увядзіце тэму або загаловак блога...',
  'e.g., AI writing, content marketing, SEO tips':
      'напр., AI пісьмо, кантэнт-маркетынг, SEO парады',
  'e.g., small business owners, bloggers':
      'напр., уладальнікі малога бізнесу, блогеры',
  'Article Type': 'Тып Артыкула',
  'Writing Tone': 'Тон Пісьма',
  'Article Length': 'Даўжыня Артыкула',
  'SEO Options': 'SEO Параметры',
  'Include Meta Description': 'Уключыць Мета Апісанне',
  'Include Keyword Suggestions': 'Уключыць Прапановы Ключавых Слоў',
  'Include FAQs Section': 'Уключыць Раздзел FAQ',
  'Please enter a blog topic': 'Калі ласка, увядзіце тэму блога',
  'Generate Blog': 'Генераваць Блог',
  'SEO optimized articles with keywords':
      'SEO аптымізаваныя артыкулы з ключавымі словамі',
  'Write Blog': 'Напісаць Блог',
  'SEO Article': 'SEO Артыкул',
  'How-To Guide': 'Інструкцыя',
  'Listicle': 'Спіс-Артыкул',
  'Product Review': 'Агляд Прадукту',
  'Opinion Piece': 'Думка',
  'News Article': 'Навіна',
  'Professional': 'Прафесійны',
  'Casual': 'Нефармальны',
  'Informative': 'Інфарматыўны',
  'Persuasive': 'Пераканаўчы',
  'Friendly': 'Сяброўскі',
  'Authoritative': 'Аўтарытэтны',
  'Short (500-800)': 'Кароткі (500-800)',
  'Medium (800-1500)': 'Сярэдні (800-1500)',
  'Long (1500-2500)': 'Доўгі (1500-2500)',
  'Detailed (2500+)': 'Падрабязны (2500+)',
  'YouTube Script': 'YouTube Сцэнарый',
  'Video Topic': 'Тэма Відэа',
  'Key Points (Optional)': 'Асноўныя Пункты (Неабавязкова)',
  'What is your video about?': 'Пра што ваша відэа?',
  'List key points to cover (optional)...':
      'Пералічыце асноўныя пункты (неабавязкова)...',
  'Video Duration': 'Працягласць Відэа',
  'Script Options': 'Параметры Сцэнарыя',
  'Include Hook/Intro': 'Уключыць Хук/Уступ',
  'Include Call-to-Action': 'Уключыць Заклік да Дзеяння',
  'Include Timestamps': 'Уключыць Часовыя Пазнакі',
  'Please enter a video topic': 'Калі ласка, увядзіце тэму відэа',
  'Generate Script': 'Генераваць Сцэнарый',
  'Create scripts for videos & reels': 'Стварайце сцэнарыі для відэа і рэелаў',
  'Create Script': 'Стварыць Сцэнарый',
  'Storytime': 'Час Гісторый',
  'Documentary': 'Дакументальны',
  'Short Reel': 'Кароткі Рэел',
  'Educational': 'Адукацыйны',
  'Review': 'Агляд',
  'Tutorial': 'Урок',
  '< 1 min (Shorts)': '< 1 хв (Shorts)',
  '1-3 min': '1-3 хв',
  '5-10 min': '5-10 хв',
  '10-20 min': '10-20 хв',
  '20+ min': '20+ хв',
  'Engaging': 'Прываблівы',
  'Energetic': 'Энергічны',
  'Calm': 'Спакойны',
  'Funny': 'Смешны',
  'Inspired': 'Натхнёны',
  'Film Script': 'Кінасцэнарый',
  'Stage Play': 'П\'еса',
  'Scene Breakdown': 'Разбор Сцэны',
  'Dialogue Only': 'Толькі Дыялог',
  'Ad loading please wait..': 'Рэклама загружаецца, калі ласка, пачакайце..',
  'Words:': 'Словы:',
  'Reading:': 'Чытанне:',
};
