import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> bg = {
  AppKeys.lblChooseLanguage: "Изберете език",
  "All": "Всички",
  "AI Story Generator": "AI Генератор на Истории",
  "Story Generator": "Генератор на Истории",
  "Essay Writer": "Автор на Есета",
  "Essay length": "Дължина на есето",
  "Script Generator": "Генератор на Сценарии",
  "Create original stories in seconds":
      "Създайте оригинални истории за секунди",
  "Academic writing made simple": "Академичното писане стана просто",
  "Generate powerful scripts for any medium":
      "Генерирайте мощни сценарии за всяка медия",
  "Start Writing": "Започнете да Пишете",
  "Create Now": "Създайте Сега",
  "Start Generating": "Започнете Генериране",
  "Your Stories": "Вашите Истории",
  "No stories yet": "Все още няма истории",
  "Start creating your first story!":
      "Започнете да създавате първата си история!",
  "Your Story Space Awaits": "Вашето Пространство за Истории Ви Очаква",
  "Start your first story and see it appear here":
      "Започнете първата си история и я вижте тук",
  "Language": "Език",
  "Rate us": "Оценете ни",
  "Share us": "Споделете ни",
  "Privacy Policy": "Политика за Поверителност",
  "Settings": "Настройки",
  "Select Language": "Изберете Език",
  "Dashboard": "Табло",
  "BENEFITS": "ПРЕДИМСТВА",
  "Subscribe": "Абонирайте се",
  "Weekly": "Седмично",
  "Monthly": "Месечно",
  "Yearly": "Годишно",
  "week": "седмица",
  "months": "месеци",
  "year": "година",
  "Terms & Condition": "Условия и Правила",
  "No Commitment. Cancel anytime": "Без ангажимент. Отменете по всяко време",
  "No Payment Now": "Без Плащане Сега",
  "3 days free": "3 дни безплатно",
  "Start your free trial": "Започнете безплатния си пробен период",
  "More detailed answers": "По-подробни отговори",
  "Instant responds": "Мигновен отговор",
  "Text recognition": "Разпознаване на текст",
  "Powered by AI": "Задвижван от AI",
  "Storytelleing": "Разказване на Истории",
  ' Power': " Сила",
  "Unlock your \nFill ": "Отключете вашия \nFill ",
  "Your History": "Вашата История",
  "Terms and Conditions": "Условия и Правила",
  "Short": "Кратко",
  "Medium": "Средно",
  "Long": "Дълго",
  "Length": "Дължина",
  "Describe your topic...": "Опишете вашата тема...",
  "Set Creativity": "Задайте Креативност",
  "Standard": "Стандартен",
  "Creative": "Креативен",
  "Complex": "Сложен",
  "Select Genre": "Изберете Жанр",
  "Fantasy": "Фантастика",
  "Mystery": "Мистерия",
  "Thriller": "Трилър",
  "Script Tone": "Тон на Сценария",
  "Script Type": "Тип на Сценария",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Horror": "Ужас",
  "Action": "Екшън",
  "Romance": "Романтика",
  "Go Premium": "Станете Премиум",
  "Unlock Everything": "Отключете Всичко",
  "Unlimited Story Generation": "Неограничено Генериране на Истории",
  "Write Longer & Detailed Essays": "Пишете По-дълги и Подробни Есета",
  "Advanced Script Writer": "Усъвършенстван Автор на Сценарии",
  "Unlock All Styles & Tones": "Отключете Всички Стилове и Тонове",
  "No Word/Length Limit": "Без Ограничение на Думи/Дължина",
  "Remove All Ads": "Премахнете Всички Реклами",
  "Restore": "Възстановете",
  "YouTube Video": "YouTube Видео",
  "Podcast": "Подкаст",
  "Reel": "Рийл",
  "Motivational": "Мотивационен",
  "Advertisement": "Реклама",
  "Fairy Tale": "Приказка",
  "Sci-Fi": "Научна Фантастика",
  "Select Style": "Изберете Стил",
  "Imaginative": "Въображаем",
  "Innovative": "Иновативен",
  "AI Story Writer": "AI Автор на Истории",
  "Generate": "Генерирайте",
  "Please wait...": "Моля, изчакайте...",
  "Result": "Резултат",
  "Regenerate": "Регене��ирайте",
  "Download": "Изтеглете",
  "Text copied to clipboard!": "Текстът е копиран в клипборда!",
  "Please enter a topic": "Моля, въведете тема",
  "Story Magic": "Магия на Историите",
  "Let AI bring your thoughts to a full story":
      "Нека AI превърне мислите ви в пълна история",
  "Smart Scripts": "Умни Сценарии",
  "From concept to script—fast, easy, and creative":
      "От концепция до сценарий—бързо, лесно и креативно",
  "Perfect Essays": "Перфектни Есета",
  "You have reached your free limit": "Достигнахте безплатния си лимит",
  "Donwload": "Изтеглете",
  "Press again to exit app": "Натиснете отново за изход от приложението",
  "Saved to files": "TXT файлът е запазен успешно!",
  "Error: Please try again": "Грешка: Моля, опитайте отново",
  "Subscription expired": "Абонаментът изтече",
  "Purchase cancelled": "Покупката е отменена",
  "Purchase failed": "Покупката е неуспешна",
  "Restore failed": "Възстановяването е неуспешно",
  "Purchase Successful!": "Покупката е Успешна!",
  "Short (200-500 words)": "Кратко (200-500 думи)",
  "Medium (500-1000 words)": "Средно (500-1000 думи)",
  "Large (1000+ words)": "Голямо (1000+ думи)",
  "Academic Level": "Академично Ниво",
  "Type of Paper": "Тип на Работата",
  "High School": "Гимназия",
  "College": "Колеж",
  "Short Film": "Кратък Филм",
  "University": "Университет",
  "Masters": "Магистър",
  "Custom": "Персонализиран",
  "Tiktok Video": "TikTok Видео",
  "Movie": "Филм",
  "Expository": "Обяснителен",
  "Argumentative": "Аргументативен",
  "Narrative": "Повествователен",
  "Descriptive": "Описателен",
  "We're sorry to hear that 😔": "Съжаляваме да чуем това 😔",
  "We'll try to improve 🙁": "Ще се опитаме да се подобрим 🙁",
  "Thanks for your feedback 🙂": "Благодарим за обратната връзка 🙂",
  "Great! We're glad you like it 😊": "Страхотно! Радваме се, че ви харесва 😊",
  "Awesome! Thank you so much! 🎉": "Невероятно! Благодарим ви много! 🎉",
  "Maybe Later": "Може би По-късно",
  "Tap a star to rate your experience":
      "Докоснете звезда, за да оцените преживяването си",
  "Enjoying AI Math Solver?": "Харесва ли ви AI Math Solver?",
  "Thank you for rating us": "Благодарим ви, че ни оценихте",
  "Submit Rating": "Изпратете Оценка",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "Харесва ли ви AI Генератор на Истории?",
  AppKeys.arabic: "Арабски",
  AppKeys.chinese: "Китайски",
  AppKeys.english: "Английски",
  AppKeys.french: "Френски",
  AppKeys.german: "Немски",
  AppKeys.hindi: "Хинди",
  AppKeys.indonesian: "Индонезийски",
  AppKeys.japanese: "Японски",
  AppKeys.korean: "Корейски",
  AppKeys.portuguese: "Португалски",
  AppKeys.russian: "Руски",
  AppKeys.spanish: "Испански",
  AppKeys.turkish: "Турски",
  'Download As': 'Изтеглете Като',
  'Choose format to download': 'Изберете формат за изтегляне',
  'Text File': 'Текстов Файл',
  'PDF File': 'PDF Файл',
  'Copy': 'Копирай',
  'Share': 'Споделете',
  'Text copied!': 'Текстът е копиран!',
  'PDF saved successfully!': 'PDF е запазен успешно!',
  'Error creating PDF: Please try again':
      'Грешка при създаване на PDF: Моля, опитайте отново',
  'Character Story': 'История на Персонаж',
  'Character Details': 'Детайли на Персонажа',
  'Character Name': 'Име на Персонажа',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Възраст (напр., 25, Млад Възрастен, Древен)',
  'Personality (e.g., brave, shy, cunning)':
      'Личност (напр., смел, срамежлив, хитър)',
  'Role (e.g., Hero, Villain, Mentor)': 'Роля (напр., Герой, Злодей, Ментор)',
  'Additional Details (optional)': 'Допълнителни Детайли (по избор)',
  'Output Style': 'Изходен Стил',
  'Generate Character': 'Генерирайте Персонаж',
  'Please enter character name': 'Моля, въведете име на персонажа',
  'Please enter character role': 'Моля, въведете роля на персонажа',
  'Detailed': 'Подробен',
  'Brief': 'Кратък',
  'Elaborate': 'Разширен',
  'Create detailed character backstories':
      'Създайте подробни истории на персонажи',
  'Create Character': 'Създайте Персонаж',
  'Transform and improve your existing stories':
      'Трансформирайте и подобрете съществуващите си истории',
  'Rewrite Now': 'Пренапишете Сега',
  'Generate catchy titles for your stories':
      'Генерирайте завладяващи заглавия за вашите истории',
  'Generate Titles': 'Генерирайте Заглавия',
  'Rewrite Story': 'Пренапишете История',
  'Paste Your Story': 'Поставете Вашата История',
  'Paste your story here to rewrite...':
      'Поставете история��а си тук, за да я пренапишете...',
  'Select Tone': 'Изберете Тон',
  'Rewrite Style': 'Стил на Пренаписване',
  'Output Length': 'Изходна Дължина',
  'Please paste your story': 'Моля, поставете вашата история',
  'Story is too short. Please provide more content.':
      'Историята е твърде кратка. Моля, предоставете повече съдържание.',
  'Same': 'Същият',
  'More Dramatic': 'По-драматичен',
  'More Humorous': 'По-хумористичен',
  'More Emotional': 'По-емоционален',
  'More Suspenseful': 'По-напрегнат',
  'Lighter': 'По-лек',
  'Improved': 'Подобрен',
  'Simplified': 'Опростен',
  'More Descriptive': 'По-описателен',
  'More Dialogue': 'Повече Диалог',
  'More Action': 'Повече Екшън',
  'Literary': 'Литературен',
  'Shorter': 'По-кратък',
  'Longer': 'По-дълъг',
  'Much Longer': 'Много По-дълъг',
  'Title Generator': 'Генератор на Заглавия',
  'Story/Book Topic': 'Тема на История/Книга',
  'Keywords (Optional)': 'Ключови Думи (По избор)',
  'Describe your story topic or theme...':
      'Опишете темата или тематиката на вашата история...',
  'e.g., magic, dragon, adventure': 'напр., магия, дракон, приключение',
  'Title For': 'Заглавие За',
  'Title Style': 'Стил на Заглавието',
  "Adventure": "Приключение",
  'Number of Titles': 'Брой Заглавия',
  'Book': 'Книга',
  'Short Story': 'Кратък Разказ',
  'Novel': 'Роман',
  'Chapter': 'Глава',
  'Series': 'Серия',
  'Simple': 'Прост',
  'Mysterious': 'Мистериозен',
  'Dramatic': 'Драматичен',
  'Catchy': 'Завладяващ',
  'Poetic': 'Поетичен',
  'Kids': 'Деца',
  'Blog Writer': 'Блог Автор',
  'Blog Topic': 'Тема на Блог',
  'Target Keywords': 'Целеви Ключови Думи',
  'Target Audience (Optional)': 'Целева Аудитория (По избор)',
  'Enter your blog topic or title...': 'Въведете тема или заглавие на блога...',
  'e.g., AI writing, content marketing, SEO tips':
      'напр., AI писане, контент маркетинг, SEO съвети',
  'e.g., small business owners, bloggers':
      'напр., собственици на малък бизнес, блогъри',
  'Article Type': 'Тип на Статията',
  'Writing Tone': 'Тон на Писане',
  'Article Length': 'Дължина на Статията',
  'SEO Options': 'SEO Опции',
  'Include Meta Description': 'Включете Мета Описание',
  'Include Keyword Suggestions': 'Включете Предложения за Ключови Думи',
  'Include FAQs Section': 'Включете Раздел с ЧЗВ',
  'Please enter a blog topic': 'Моля, въведете тема на блога',
  'Generate Blog': 'Генерирайте Блог',
  'SEO optimized articles with keywords':
      'SEO оптимизирани статии с ключови думи',
  'Write Blog': 'Напишете Блог',
  'SEO Article': 'SEO Статия',
  'How-To Guide': 'Ръководство',
  'Listicle': 'Списък Статия',
  'Product Review': 'Ревю на Продукт',
  'Opinion Piece': 'Мнение',
  'News Article': 'Новинарска Статия',
  'Professional': 'Професионален',
  'Casual': 'Неформален',
  'Informative': 'Информативен',
  'Persuasive': 'Убедителен',
  'Friendly': 'Приятелски',
  'Authoritative': 'Авторитетен',
  'Short (500-800)': 'Кратко (500-800)',
  'Medium (800-1500)': 'Средно (800-1500)',
  'Long (1500-2500)': 'Дълго (1500-2500)',
  'Detailed (2500+)': 'Подробно (2500+)',
  'YouTube Script': 'YouTube Сценарий',
  'Video Topic': 'Тема на Видео',
  'Key Points (Optional)': 'Ключови Точки (По избор)',
  'What is your video about?': 'За какво е вашето видео?',
  'List key points to cover (optional)...':
      'Изброете ключови точки за покриване (по избор)...',
  'Video Duration': 'Продължителност на Видеото',
  'Script Options': 'Опции на Сценария',
  'Include Hook/Intro': 'Включете Кука/Въведение',
  'Include Call-to-Action': 'Включете Призив за Действие',
  'Include Timestamps': 'Включете Времеви Маркери',
  'Please enter a video topic': 'Моля, въведете тема н�� видеото',
  'Generate Script': 'Генерирайте Сценарий',
  'Create scripts for videos & reels': 'Създавайте сценарии за видеа и рийлове',
  'Create Script': 'Създайте Сценарий',
  'Storytime': 'Време за Истории',
  'Documentary': 'Документален',
  'Short Reel': 'Кратък Рийл',
  'Educational': 'Образователен',
  'Review': 'Ревю',
  'Tutorial': 'Урок',
  '< 1 min (Shorts)': '< 1 мин (Shorts)',
  '1-3 min': '1-3 мин',
  '5-10 min': '5-10 мин',
  '10-20 min': '10-20 мин',
  '20+ min': '20+ мин',
  'Engaging': 'Увлекателен',
  'Energetic': 'Енергичен',
  'Calm': 'Спокоен',
  'Funny': 'Смешен',
  'Inspired': 'Вдъхновен',
  'Film Script': 'Филмов Сценарий',
  'Stage Play': 'Театрална Пиеса',
  'Scene Breakdown': 'Разбивка на Сцени',
  'Dialogue Only': 'Само Диалог',
  'Ad loading please wait..': 'Рекламата се зарежда, моля изчакайте..',
  'Words:': 'Думи:',
  'Reading:': 'Четене:',
};
