import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> bn = {
  AppKeys.lblChooseLanguage: "ভাষা নির্বাচন করুন",
  "All": "সব",
  "AI Story Generator": "এআই গল্প জেনারেটর",
  "Story Generator": "গল্প জেনারেটর",
  "Essay Writer": "প্রবন্ধ লেখক",
  "Essay length": "প্রবন্ধের দৈর্ঘ্য",
  "Script Generator": "স্ক্রিপ্ট জেনারেটর",
  "Create original stories in seconds": "সেকেন্ডে মৌলিক গল্প তৈরি করুন",
  "Academic writing made simple": "একাডেমিক লেখা সহজ করা হয়েছে",
  "Generate powerful scripts for any medium":
      "যেকোনো মাধ্যমের জন্য শক্তিশালী স্ক্রিপ্ট তৈরি করুন",
  "Start Writing": "লেখা শুরু করুন",
  "Create Now": "এখনই তৈরি করুন",
  "Start Generating": "জেনারেট করা শুরু করুন",
  "Your Stories": "আপনার গল্প",
  "No stories yet": "এখনো কোনো গল্প নেই",
  "Start creating your first story!": "আপনার প্রথম গল্প তৈরি করা শুরু করুন!",
  "Your Story Space Awaits": "আপনার গল্পের জায়গা অপেক্ষা করছে",
  "Start your first story and see it appear here":
      "আপনার প্রথম গল্প শুরু করুন এবং এটি এখানে দেখুন",
  "Language": "ভাষা",
  "Rate us": "আমাদের রেটিং দিন",
  "Share us": "আমাদের শেয়ার করুন",
  "Privacy Policy": "গোপনীয়তা নীতি",
  "Settings": "সেটিংস",
  "Select Language": "ভাষা নির্বাচন করুন",
  "Dashboard": "ড্যাশবোর্ড",
  "BENEFITS": "সুবিধা",
  "Subscribe": "সাবস্ক্রাইব করুন",
  "Weekly": "সাপ্তাহিক",
  "Monthly": "মাসিক",
  "Yearly": "বার্ষিক",
  "week": "সপ্তাহ",
  "months": "মাস",
  "year": "বছর",
  "Terms & Condition": "শর্তাবলী",
  "No Commitment. Cancel anytime":
      "কোনো প্রতিশ্রুতি নেই। যেকোনো সময় বাতিল করুন",
  "No Payment Now": "এখন কোনো পেমেন্ট নেই",
  "3 days free": "৩ দিন বিনামূল্যে",
  "Start your free trial": "আপনার বিনামূল্যে ট্রায়াল শুরু করুন",
  "More detailed answers": "আরো বিস্তারিত উত্তর",
  "Instant responds": "তাৎক্ষণিক প্রতিক্রিয়া",
  "Text recognition": "পাঠ্য শনাক্তকরণ",
  "Powered by AI": "এআই দ্বারা চালিত",
  "Storytelleing": "গল্প বলা",
  ' Power': " শক্তি",
  "Unlock your \nFill ": "আনলক করুন আপনার \nFill ",
  "Your History": "আপনার ইতিহাস",
  "Terms and Conditions": "শর্তাবলী",
  "Short": "ছোট",
  "Medium": "মাঝারি",
  "Long": "লম্বা",
  "Length": "দৈর্ঘ্য",
  "Describe your topic...": "আপনার বিষয় বর্ণনা করুন...",
  "Set Creativity": "সৃজনশীলতা সেট করুন",
  "Standard": "স্ট্যান্ডার্ড",
  "Creative": "সৃজনশীল",
  "Complex": "জটিল",
  "Select Genre": "ধরন নির্বাচন করুন",
  "Fantasy": "কল্��না",
  "Mystery": "রহস্য",
  "Thriller": "থ্রিলার",
  "Script Tone": "স্ক্রিপ্ট টোন",
  "Script Type": "স্ক্রিপ্ট ধরন",
  "Comedy": "কমেডি",
  "Drama": "নাটক",
  "Horror": "ভয়ঙ্কর",
  "Action": "অ্যাকশন",
  "Romance": "রোমান্স",
  "Go Premium": "প্রিমিয়াম যান",
  "Unlock Everything": "সবকিছু আনলক করুন",
  "Unlimited Story Generation": "সীমাহীন গল্প জেনারেশন",
  "Write Longer & Detailed Essays": "দীর্ঘ এবং বিস্তারিত প্রবন্ধ লিখুন",
  "Advanced Script Writer": "উন্নত স্ক্রিপ্ট লেখক",
  "Unlock All Styles & Tones": "সব স্টাইল ও টোন আনলক করুন",
  "No Word/Length Limit": "কোনো শব্দ/দৈর্ঘ্য সীমা নেই",
  "Remove All Ads": "সব বিজ্ঞাপন সরান",
  "Restore": "পুনরুদ্ধার করুন",
  "YouTube Video": "ইউটিউব ভিডিও",
  "Podcast": "পডকাস্ট",
  "Reel": "রিল",
  "Motivational": "অনুপ্রেরণামূলক",
  "Advertisement": "বিজ্ঞাপন",
  "Fairy Tale": "রূপকথা",
  "Sci-Fi": "বিজ্ঞান কল্পকাহিনী",
  "Select Style": "স্টাইল নির্বাচন করুন",
  "Imaginative": "কল্পনাপ্রবণ",
  "Innovative": "উদ্ভাবনী",
  "AI Story Writer": "এআই গল্প লেখক",
  "Generate": "জেনারেট করুন",
  "Please wait...": "অনুগ্রহ করে অপেক্ষা করুন...",
  "Result": "ফলাফল",
  "Regenerate": "পুনরায় জেনারেট করুন",
  "Download": "ডাউনলোড",
  "Text copied to clipboard!": "পাঠ্য ক্লিপবোর্ডে কপি হয়েছে!",
  "Please enter a topic": "অনুগ্রহ করে একটি বিষয় লিখুন",
  "Story Magic": "গল্পের জাদু",
  "Let AI bring your thoughts to a full story":
      "এআই-কে আপনার চিন্তাকে একটি পূর্ণ গল্পে রূপান্তরিত করতে দিন",
  "Smart Scripts": "স্মার্ট স্ক্রিপ্ট",
  "From concept to script—fast, easy, and creative":
      "ধারণা থেকে স্ক্রিপ্ট—দ্রুত, সহজ এবং সৃজনশীল",
  "Perfect Essays": "নিখুঁত প্রবন্ধ",
  "You have reached your free limit": "আপনি আপনার বিনামূল্যে সীমায় পৌঁছেছেন",
  "Donwload": "ডাউনলোড",
  "Press again to exit app": "অ্যাপ থেকে বের হতে আবার চাপুন",
  "Saved to files": "TXT ফাইল সফলভাবে সেভ হয়েছে!",
  "Error: Please try again": "ত্রুটি: অনুগ্রহ করে আবার চেষ্টা করুন",
  "Subscription expired": "সাবস্ক্রিপশনের মেয়াদ শেষ",
  "Purchase cancelled": "ক্রয় বাতিল হয়েছে",
  "Purchase failed": "ক্রয় ব্যর্থ হয়েছে",
  "Restore failed": "পুনরুদ্ধার ব্যর্থ হয়েছে",
  "Purchase Successful!": "ক্রয় সফল!",
  "Short (200-500 words)": "ছোট (২০০-৫০০ শব্দ)",
  "Medium (500-1000 words)": "মাঝারি (৫০০-১০০০ শব্দ)",
  "Large (1000+ words)": "বড় (১০০০+ শব্দ)",
  "Academic Level": "একাডেমিক স্তর",
  "Type of Paper": "পেপারের ধরন",
  "High School": "উচ্চ বিদ্যালয়",
  "College": "কলেজ",
  "Short Film": "শর্ট ফিল্ম",
  "University": "বিশ্ববিদ্যালয়",
  "Masters": "মাস্টার্স",
  "Custom": "কাস্টম",
  "Tiktok Video": "টিকটক ভিডিও",
  "Movie": "সিনেমা",
  "Expository": "ব্যাখ্যামূলক",
  "Argumentative": "যুক্তিমূলক",
  "Narrative": "বর্ণনামূলক",
  "Descriptive": "বিবরণমূলক",
  "We're sorry to hear that 😔": "এটি শুনে আমরা দুঃখিত 😔",
  "We'll try to improve 🙁": "আমরা উন্নতি করার চেষ্টা করব 🙁",
  "Thanks for your feedback 🙂": "আপনার মতামতের জন্য ধন্যবাদ 🙂",
  "Great! We're glad you like it 😊":
      "দারুণ! আমরা খুশি যে আপনি এটি পছন্দ করেছেন 😊",
  "Awesome! Thank you so much! 🎉": "অসাধারণ! অনেক ধন্যবাদ! 🎉",
  "Maybe Later": "হয়তো পরে",
  "Tap a star to rate your experience":
      "আপনার অভিজ্ঞতা রেটিং দিতে একটি তারায় ট্যাপ করুন",
  "Enjoying AI Math Solver?": "এআই ম্যাথ সলভার উপভোগ করছেন?",
  "Thank you for rating us": "আমাদের রেটিং দেওয়ার জন্য ধন্যবাদ",
  "Submit Rating": "রেটিং জমা দিন",
  "Hindi": "হিন্দি",
  "Enjoying AI Story Generator?": "এআই গল্প জেনারেটর উপভোগ করছেন?",
  AppKeys.arabic: "আরবি",
  AppKeys.chinese: "চীনা",
  AppKeys.english: "ইংরেজি",
  AppKeys.french: "ফরাসি",
  AppKeys.german: "জার্মান",
  AppKeys.hindi: "হিন্দি",
  AppKeys.indonesian: "ইন্দোনেশীয়",
  AppKeys.japanese: "জাপানি",
  AppKeys.korean: "কোরিয়ান",
  AppKeys.portuguese: "পর্তুগিজ",
  AppKeys.russian: "রাশিয়ান",
  AppKeys.spanish: "স্প্যানিশ",
  AppKeys.turkish: "তুর্কি",
  'Download As': 'হিসাবে ডাউনলোড করুন',
  'Choose format to download': 'ডাউনলোডের জন্য ফরম্যাট নির্বাচন করুন',
  'Text File': 'টেক্সট ফাইল',
  'PDF File': 'পিডিএফ ফাইল',
  'Copy': 'কপি',
  'Share': 'শেয়ার করুন',
  'Text copied!': 'পাঠ্য কপি হয়েছে!',
  'PDF saved successfully!': 'পিডিএফ সফলভাবে সেভ হয়েছে!',
  'Error creating PDF: Please try again':
      'পিডিএফ তৈরিতে ত্রুটি: অনুগ্রহ করে আবার চেষ্টা করুন',
  'Character Story': 'চরিত্রের গল্প',
  'Character Details': 'চরিত্রের বিবরণ',
  'Character Name': 'চরিত্রের নাম',
  'Age (e.g., 25, Young Adult, Ancient)':
      'বয়স (যেমন, ২৫, তরুণ প্রাপ্তবয়স্ক, প্রাচীন)',
  'Personality (e.g., brave, shy, cunning)':
      'ব্যক্তিত্ব (যেমন, সাহসী, লাজুক, চতুর)',
  'Role (e.g., Hero, Villain, Mentor)':
      'ভূমিকা (যেমন, নায়ক, খলনায়ক, পরামর্শদাতা)',
  'Additional Details (optional)': 'অতিরিক্ত বিবরণ (ঐচ্ছিক)',
  'Output Style': 'আউটপুট স্টাইল',
  'Generate Character': 'চরিত্র জেনারেট করুন',
  'Please enter character name': 'অনুগ্রহ করে চরিত্রের নাম লিখুন',
  'Please enter character role': 'অনুগ্রহ করে চরিত্রের ভূমিকা লিখুন',
  'Detailed': 'বিস্তারিত',
  'Brief': 'সংক্ষিপ্ত',
  'Elaborate': 'বিশদ',
  'Create detailed character backstories':
      'বিস্তারিত চরিত্রের পটভূমি তৈরি করুন',
  'Create Character': 'চরিত্র তৈরি করুন',
  'Transform and improve your existing stories':
      'আপনার বিদ্যমান গল্পগুলো রূপান্তরিত ও উন্নত করুন',
  'Rewrite Now': 'এখনই পুনরায় লিখুন',
  'Generate catchy titles for your stories':
      'আপনার গল্পের জন্য আকর্ষণীয় শিরোনাম তৈরি করুন',
  'Generate Titles': 'শিরোনাম তৈরি করুন',
  'Rewrite Story': 'গল্প পুনরায় লিখুন',
  'Paste Your Story': 'আপনার গল্প পেস্ট করুন',
  'Paste your story here to rewrite...':
      'পুনরায় লিখতে আপনার গল্প এখানে পেস্ট করুন...',
  'Select Tone': 'টোন নির্বাচন করুন',
  'Rewrite Style': 'পুনর্লিখন স্টাইল',
  'Output Length': 'আউটপুট দৈর্ঘ্য',
  'Please paste your story': 'অনুগ্রহ করে আপনার গল্প পেস্ট করুন',
  'Story is too short. Please provide more content.':
      'গল্প খুব ছোট। অনুগ্রহ করে আরো বিষয়বস্তু দিন।',
  'Same': 'একই',
  'More Dramatic': 'আরো নাটকীয়',
  'More Humorous': 'আরো হাস্যকর',
  'More Emotional': 'আরো আবেগপূর্ণ',
  'More Suspenseful': 'আরো রোমাঞ্চকর',
  'Lighter': 'হালকা',
  'Improved': 'উন্নত',
  'Simplified': 'সরলীকৃত',
  'More Descriptive': 'আরো বিবরণমূলক',
  'More Dialogue': 'আরো সংলাপ',
  'More Action': 'আরো অ্যাকশন',
  'Literary': 'সাহিত্যিক',
  'Shorter': 'ছোট',
  'Longer': 'লম্বা',
  'Much Longer': 'অনেক লম্বা',
  'Title Generator': 'শিরোনাম জেনারেটর',
  'Story/Book Topic': 'গল্প/বইয়ের বিষয়',
  'Keywords (Optional)': 'কীওয়ার্ড (ঐচ্ছিক)',
  'Describe your story topic or theme...':
      'আপনার গল্পের বিষয় বা থিম বর্ণনা করুন...',
  'e.g., magic, dragon, adventure': 'যেমন, জাদু, ড্রাগন, দুঃসাহসিক অভিযান',
  'Title For': 'শিরোনাম এর জন্য',
  'Title Style': 'শিরোনাম স্টাইল',
  "Adventure": "দুঃসাহসিক অভিযান",
  'Number of Titles': 'শিরোনামের সংখ্যা',
  'Book': 'বই',
  'Short Story': 'ছোটগল্প',
  'Novel': 'উপন্যাস',
  'Chapter': 'অধ্যায়',
  'Series': 'সিরিজ',
  'Simple': 'সরল',
  'Mysterious': 'রহ��্যময়',
  'Dramatic': 'নাটকীয়',
  'Catchy': 'আকর্ষণীয়',
  'Poetic': 'কাব্যিক',
  'Kids': 'শিশু',
  'Blog Writer': 'ব্লগ লেখক',
  'Blog Topic': 'ব্লগ বিষয়',
  'Target Keywords': 'লক্ষ্য কীওয়ার্ড',
  'Target Audience (Optional)': 'লক্ষ্য দর্শক (ঐচ্ছিক)',
  'Enter your blog topic or title...': 'আপনার ব্লগের বিষয় বা শিরোনাম লিখুন...',
  'e.g., AI writing, content marketing, SEO tips':
      'যেমন, এআই লেখা, কন্টেন্ট মার্কেটিং, এসইও টিপস',
  'e.g., small business owners, bloggers': 'যেমন, ছোট ব্যবসার মালিক, ব্লগার',
  'Article Type': 'আর্টিকেলের ধরন',
  'Writing Tone': 'লেখার টোন',
  'Article Length': 'আর্টিকেলের দৈর্ঘ্য',
  'SEO Options': 'এসইও অপশন',
  'Include Meta Description': 'মেটা বিবরণ অন্তর্ভুক্ত করুন',
  'Include Keyword Suggestions': 'কীওয়ার্ড পরামর্শ অন্তর্ভুক্ত করুন',
  'Include FAQs Section': 'প্রায়শই জিজ্ঞাসিত প্রশ্ন বিভাগ অন্তর্ভুক্ত করুন',
  'Please enter a blog topic': 'অনুগ্রহ করে একটি ব্লগ বিষয় লিখুন',
  'Generate Blog': 'ব্লগ জেনারেট করুন',
  'SEO optimized articles with keywords':
      'কীওয়ার্ড সহ এসইও অপটিমাইজড আর্টিকেল',
  'Write Blog': 'ব্লগ লিখুন',
  'SEO Article': 'এসইও আর্টিকেল',
  'How-To Guide': 'কিভাবে করবেন গাইড',
  'Listicle': 'তালিকা আর্টিকেল',
  'Product Review': 'পণ্য পর্যালোচনা',
  'Opinion Piece': 'মতামত',
  'News Article': 'সংবাদ আর্টিকেল',
  'Professional': 'পেশাদার',
  'Casual': 'অনানুষ্ঠানিক',
  'Informative': 'তথ্যবহুল',
  'Persuasive': 'প্রেরণাদায়ক',
  'Friendly': 'বন্ধুত্বপূর্ণ',
  'Authoritative': 'কর্তৃত্বপূর্ণ',
  'Short (500-800)': 'ছোট (৫০০-৮০০)',
  'Medium (800-1500)': 'মাঝারি (৮০০-১৫০০)',
  'Long (1500-2500)': 'লম্বা (১৫০০-২৫০০)',
  'Detailed (2500+)': 'বিস্তারিত (২৫০০+)',
  'YouTube Script': 'ইউটিউব স্ক্রিপ্ট',
  'Video Topic': 'ভিডিও বিষয়',
  'Key Points (Optional)': 'মূল পয়েন্ট (ঐচ্ছিক)',
  'What is your video about?': 'আপনার ভিডিও কি সম্পর্কে?',
  'List key points to cover (optional)...':
      'কভার করার মূল পয়েন্ট তালিকা করুন (ঐচ্ছিক)...',
  'Video Duration': 'ভিডিওর সময়কাল',
  'Script Options': 'স্ক্রিপ্ট অপশন',
  'Include Hook/Intro': 'হুক/ভূমিকা অন্তর্ভুক্ত করুন',
  'Include Call-to-Action': 'কল-টু-অ্যাকশন অন্তর্ভুক্ত করুন',
  'Include Timestamps': 'টাইমস্ট্যাম্প অন্তর্ভুক্ত করুন',
  'Please enter a video topic': 'অনুগ্রহ করে একটি ভিডিও বিষয় লিখুন',
  'Generate Script': 'স্ক্রিপ্ট জেনারেট করুন',
  'Create scripts for videos & reels':
      'ভিডিও ও রিলসের জন্য স্ক্রিপ্ট তৈরি করুন',
  'Create Script': 'স্ক্রিপ্ট তৈরি করুন',
  'Storytime': 'গল্পের সময়',
  'Documentary': 'ডকুমেন্টারি',
  'Short Reel': 'ছোট রিল',
  'Educational': 'শিক্ষামূলক',
  'Review': 'পর্যালোচনা',
  'Tutorial': 'টিউটোরিয়াল',
  '< 1 min (Shorts)': '< ১ মিনিট (শর্টস)',
  '1-3 min': '১-৩ মিনিট',
  '5-10 min': '৫-১০ মিনিট',
  '10-20 min': '১০-২০ মিনিট',
  '20+ min': '২০+ মিনিট',
  'Engaging': 'আকর্ষণীয়',
  'Energetic': 'প্রাণবন্ত',
  'Calm': 'শান্ত',
  'Funny': 'মজার',
  'Inspired': 'অনুপ্রাণিত',
  'Film Script': 'চলচ্চিত্র স্ক্রিপ্ট',
  'Stage Play': 'মঞ্চ নাটক',
  'Scene Breakdown': 'দৃশ্য বিশ্লেষণ',
  'Dialogue Only': 'শুধু সংলাপ',
  'Ad loading please wait..': 'বিজ্ঞাপন লোড হচ্ছে অনুগ্রহ করে অপেক্ষা করুন..',
  'Words:': 'শব্দ:',
  'Reading:': 'পড়া:',
};
