import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ca = {
  AppKeys.lblChooseLanguage: "Trieu l'idioma",
  "All": "Tot",
  "AI Story Generator": "Generador d'Històries IA",
  "Story Generator": "Generador d'Històries",
  "Essay Writer": "Escriptor d'Assaigs",
  "Essay length": "Llargada de l'assaig",
  "Script Generator": "Generador de Guions",
  "Create original stories in seconds": "Creeu històries originals en segons",
  "Academic writing made simple": "L'escriptura acadèmica feta senzilla",
  "Generate powerful scripts for any medium":
      "Genereu guions potents per a qualsevol mitjà",
  "Start Writing": "Comença a Escriure",
  "Create Now": "Crea Ara",
  "Start Generating": "Comença a Generar",
  "Your Stories": "Les Teves Històries",
  "No stories yet": "Encara no hi ha històries",
  "Start creating your first story!":
      "Comença a crear la teva primera història!",
  "Your Story Space Awaits": "El Teu Espai d'Històries T'Espera",
  "Start your first story and see it appear here":
      "Comença la teva primera història i mira-la aparèixer aquí",
  "Language": "Idioma",
  "Rate us": "Valora'ns",
  "Share us": "Comparteix-nos",
  "Privacy Policy": "Política de Privadesa",
  "Settings": "Configuració",
  "Select Language": "Selecciona Idioma",
  "Dashboard": "Tauler",
  "BENEFITS": "BENEFICIS",
  "Subscribe": "Subscriu-te",
  "Weekly": "Setmanal",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "week": "setmana",
  "months": "mesos",
  "year": "any",
  "Terms & Condition": "Termes i Condicions",
  "No Commitment. Cancel anytime":
      "Sense compromís. Cancel·la en qualsevol moment",
  "No Payment Now": "Sense Pagament Ara",
  "3 days free": "3 dies gratis",
  "Start your free trial": "Comença la teva prova gratuïta",
  "More detailed answers": "Respostes més detallades",
  "Instant responds": "Resposta instantània",
  "Text recognition": "Reconeixement de text",
  "Powered by AI": "Impulsat per IA",
  "Storytelleing": "Narració",
  ' Power': " Poder",
  "Unlock your \nFill ": "Desbloqueja el teu \nFill ",
  "Your History": "El Teu Historial",
  "Terms and Conditions": "Termes i Condicions",
  "Short": "Curt",
  "Medium": "Mitjà",
  "Long": "Llarg",
  "Length": "Llargada",
  "Describe your topic...": "Descriu el teu tema...",
  "Set Creativity": "Estableix Creativitat",
  "Standard": "Estàndard",
  "Creative": "Creatiu",
  "Complex": "Complex",
  "Select Genre": "Selecciona Gènere",
  "Fantasy": "Fantasia",
  "Mystery": "Misteri",
  "Thriller": "Thriller",
  "Script Tone": "To del Guió",
  "Script Type": "Tipus de Guió",
  "Comedy": "Comèdia",
  "Drama": "Drama",
  "Horror": "Terror",
  "Action": "Acció",
  "Romance": "Romanç",
  "Go Premium": "Fes-te Premium",
  "Unlock Everything": "Desbloqueja-ho Tot",
  "Unlimited Story Generation": "Generació Il·limitada d'Històries",
  "Write Longer & Detailed Essays": "Escriu Assaigs Més Llargs i Detallats",
  "Advanced Script Writer": "Escriptor de Guions Avançat",
  "Unlock All Styles & Tones": "Desbloqueja Tots els Estils i Tons",
  "No Word/Length Limit": "Sense Límit de Paraules/Llargada",
  "Remove All Ads": "Elimina Tots els Anuncis",
  "Restore": "Restaura",
  "YouTube Video": "Vídeo de YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivacional",
  "Advertisement": "Anunci",
  "Fairy Tale": "Conte de Fades",
  "Sci-Fi": "Ciència Ficció",
  "Select Style": "Selecciona Estil",
  "Imaginative": "Imaginatiu",
  "Innovative": "Innovador",
  "AI Story Writer": "Escriptor d'Històries IA",
  "Generate": "Genera",
  "Please wait...": "Si us plau, espereu...",
  "Result": "Resultat",
  "Regenerate": "Regenera",
  "Download": "Descarrega",
  "Text copied to clipboard!": "Text copiat al porta-retalls!",
  "Please enter a topic": "Si us plau, introduïu un tema",
  "Story Magic": "Màgia d'Històries",
  "Let AI bring your thoughts to a full story":
      "Deixa que la IA converteixi els teus pensaments en una història completa",
  "Smart Scripts": "Guions Intel·ligents",
  "From concept to script—fast, easy, and creative":
      "Del concepte al guió—ràpid, fàcil i creatiu",
  "Perfect Essays": "Assaigs Perfectes",
  "You have reached your free limit": "Has arribat al teu límit gratuït",
  "Donwload": "Descarrega",
  "Press again to exit app": "Prem de nou per sortir de l'aplicació",
  "Saved to files": "Fitxer TXT desat correctament!",
  "Error: Please try again": "Error: Si us plau, torneu a intentar-ho",
  "Subscription expired": "La subscripció ha expirat",
  "Purchase cancelled": "Compra cancel·lada",
  "Purchase failed": "Compra fallida",
  "Restore failed": "Restauració fallida",
  "Purchase Successful!": "Compra Exitosa!",
  "Short (200-500 words)": "Curt (200-500 paraules)",
  "Medium (500-1000 words)": "Mitjà (500-1000 paraules)",
  "Large (1000+ words)": "Llarg (1000+ paraules)",
  "Academic Level": "Nivell Acadèmic",
  "Type of Paper": "Tipus de Treball",
  "High School": "Institut",
  "College": "Col·legi",
  "Short Film": "Curtmetratge",
  "University": "Universitat",
  "Masters": "Màster",
  "Custom": "Personalitzat",
  "Tiktok Video": "Vídeo TikTok",
  "Movie": "Pel·lícula",
  "Expository": "Expositiu",
  "Argumentative": "Argumentatiu",
  "Narrative": "Narratiu",
  "Descriptive": "Descriptiu",
  "We're sorry to hear that 😔": "Lamentem sentir això 😔",
  "We'll try to improve 🙁": "Intentarem millorar 🙁",
  "Thanks for your feedback 🙂": "Gràcies pels teus comentaris 🙂",
  "Great! We're glad you like it 😊": "Genial! Ens alegrem que t'agradi 😊",
  "Awesome! Thank you so much! 🎉": "Increïble! Moltes gràcies! 🎉",
  "Maybe Later": "Potser Més Tard",
  "Tap a star to rate your experience":
      "Toca una estrella per valorar la teva experiència",
  "Enjoying AI Math Solver?": "T'agrada AI Math Solver?",
  "Thank you for rating us": "Gràcies per valorar-nos",
  "Submit Rating": "Envia Valoració",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "T'agrada el Generador d'Històries IA?",
  AppKeys.arabic: "Àrab",
  AppKeys.chinese: "Xinès",
  AppKeys.english: "Anglès",
  AppKeys.french: "Francès",
  AppKeys.german: "Alemany",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesi",
  AppKeys.japanese: "Japonès",
  AppKeys.korean: "Coreà",
  AppKeys.portuguese: "Portuguès",
  AppKeys.russian: "Rus",
  AppKeys.spanish: "Espanyol",
  AppKeys.turkish: "Turc",
  'Download As': 'Descarrega Com',
  'Choose format to download': 'Tria el format per descarregar',
  'Text File': 'Fitxer de Text',
  'PDF File': 'Fitxer PDF',
  'Copy': 'Copia',
  'Share': 'Comparteix',
  'Text copied!': 'Text copiat!',
  'PDF saved successfully!': 'PDF desat correctament!',
  'Error creating PDF: Please try again':
      'Error en crear PDF: Si us plau, torneu a intentar-ho',
  'Character Story': 'Història del Personatge',
  'Character Details': 'Detalls del Personatge',
  'Character Name': 'Nom del Personatge',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Edat (p. ex., 25, Jove Adult, Antic)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalitat (p. ex., valent, tímid, astut)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (p. ex., Heroi, Vilà, Mentor)',
  'Additional Details (optional)': 'Detalls Addicionals (opcional)',
  'Output Style': "Estil de Sortida",
  'Generate Character': 'Genera Personatge',
  'Please enter character name': 'Si us plau, introduïu el nom del personatge',
  'Please enter character role': 'Si us plau, introduïu el rol del personatge',
  'Detailed': 'Detallat',
  'Brief': 'Breu',
  'Elaborate': 'Elaborat',
  'Create detailed character backstories':
      "Crea històries detallades dels personatges",
  'Create Character': 'Crea Personatge',
  'Transform and improve your existing stories':
      'Transforma i millora les teves històries existents',
  'Rewrite Now': 'Reescriu Ara',
  'Generate catchy titles for your stories':
      'Genera títols atractius per a les teves històries',
  'Generate Titles': 'Genera Títols',
  'Rewrite Story': 'Reescriu Història',
  'Paste Your Story': 'Enganxa la Teva Història',
  'Paste your story here to rewrite...':
      'Enganxa la teva història aquí per reescriure...',
  'Select Tone': 'Selecciona To',
  'Rewrite Style': "Estil de Reescriptura",
  'Output Length': 'Llargada de Sortida',
  'Please paste your story': 'Si us plau, enganxa la teva història',
  'Story is too short. Please provide more content.':
      "La història és massa curta. Si us plau, proporciona més contingut.",
  'Same': 'Igual',
  'More Dramatic': 'Més Dramàtic',
  'More Humorous': 'Més Humorístic',
  'More Emotional': 'Més Emocional',
  'More Suspenseful': 'Més Suspens',
  'Lighter': 'Més Lleuger',
  'Improved': 'Millorat',
  'Simplified': 'Simplificat',
  'More Descriptive': 'Més Descriptiu',
  'More Dialogue': 'Més Diàleg',
  'More Action': 'Més Acció',
  'Literary': 'Literari',
  'Shorter': 'Més Curt',
  'Longer': 'Més Llarg',
  'Much Longer': 'Molt Més Llarg',
  'Title Generator': 'Generador de Títols',
  'Story/Book Topic': "Tema d'Història/Llibre",
  'Keywords (Optional)': 'Paraules Clau (Opcional)',
  'Describe your story topic or theme...':
      'Descriu el tema de la teva història...',
  'e.g., magic, dragon, adventure': 'p. ex., màgia, drac, aventura',
  'Title For': 'Títol Per',
  'Title Style': 'Estil del Títol',
  "Adventure": "Aventura",
  'Number of Titles': 'Nombre de Títols',
  'Book': 'Llibre',
  'Short Story': 'Conte Curt',
  'Novel': 'Novel·la',
  'Chapter': 'Capítol',
  'Series': 'Sèrie',
  'Simple': 'Simple',
  'Mysterious': 'Misteriós',
  'Dramatic': 'Dramàtic',
  'Catchy': 'Atractiu',
  'Poetic': 'Poètic',
  'Kids': 'Nens',
  'Blog Writer': 'Escriptor de Blog',
  'Blog Topic': 'Tema del Blog',
  'Target Keywords': 'Paraules Clau Objectiu',
  'Target Audience (Optional)': 'Públic Objectiu (Opcional)',
  'Enter your blog topic or title...':
      'Introdueix el tema o títol del teu blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'p. ex., escriptura IA, màrqueting de continguts, consells SEO',
  'e.g., small business owners, bloggers':
      'p. ex., propietaris de petites empreses, bloggers',
  'Article Type': "Tipus d'Article",
  'Writing Tone': "To d'Escriptura",
  'Article Length': "Llargada de l'Article",
  'SEO Options': 'Opcions SEO',
  'Include Meta Description': 'Inclou Meta Descripció',
  'Include Keyword Suggestions': 'Inclou Suggeriments de Paraules Clau',
  'Include FAQs Section': 'Inclou Secció de FAQ',
  'Please enter a blog topic': 'Si us plau, introdueix un tema de blog',
  'Generate Blog': 'Genera Blog',
  'SEO optimized articles with keywords':
      'Articles optimitzats per SEO amb paraules clau',
  'Write Blog': 'Escriu Blog',
  'SEO Article': 'Article SEO',
  'How-To Guide': 'Guia Pràctica',
  'Listicle': 'Llista Article',
  'Product Review': 'Ressenya de Producte',
  'Opinion Piece': "Peça d'Opinió",
  'News Article': 'Article de Notícies',
  'Professional': 'Professional',
  'Casual': 'Informal',
  'Informative': 'Informatiu',
  'Persuasive': 'Persuasiu',
  'Friendly': 'Amigable',
  'Authoritative': 'Autoritari',
  'Short (500-800)': 'Curt (500-800)',
  'Medium (800-1500)': 'Mitjà (800-1500)',
  'Long (1500-2500)': 'Llarg (1500-2500)',
  'Detailed (2500+)': 'Detallat (2500+)',
  'YouTube Script': 'Guió de YouTube',
  'Video Topic': 'Tema del Vídeo',
  'Key Points (Optional)': 'Punts Clau (Opcional)',
  'What is your video about?': 'De què tracta el teu vídeo?',
  'List key points to cover (optional)...':
      'Llista els punts clau a cobrir (opcional)...',
  'Video Duration': 'Durada del Vídeo',
  'Script Options': 'Opcions del Guió',
  'Include Hook/Intro': 'Inclou Ganxo/Introducció',
  'Include Call-to-Action': "Inclou Crida a l'Acció",
  'Include Timestamps': 'Inclou Marques de Temps',
  'Please enter a video topic': 'Si us plau, introdueix un tema de vídeo',
  'Generate Script': 'Genera Guió',
  'Create scripts for videos & reels': 'Crea guions per a vídeos i reels',
  'Create Script': 'Crea Guió',
  'Storytime': "Hora del Conte",
  'Documentary': 'Documental',
  'Short Reel': 'Reel Curt',
  'Educational': 'Educatiu',
  'Review': 'Ressenya',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Captivador',
  'Energetic': 'Energètic',
  'Calm': 'Tranquil',
  'Funny': 'Divertit',
  'Inspired': 'Inspirat',
  'Film Script': 'Guió de Pel·lícula',
  'Stage Play': 'Obra de Teatre',
  'Scene Breakdown': 'Desglossament de Escenes',
  'Dialogue Only': 'Només Diàleg',
  'Ad loading please wait..': "L'anunci s'està carregant, si us plau espereu..",
  'Words:': 'Paraules:',
  'Reading:': 'Lectura:',
};
