import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> cs = {
  AppKeys.lblChooseLanguage: "Vyberte jazyk",
  "All": "Vše",
  "AI Story Generator": "AI Generátor Příběhů",
  "Story Generator": "Generátor Příběhů",
  "Essay Writer": "Autor Esejí",
  "Essay length": "Délka eseje",
  "Script Generator": "Generátor Scénářů",
  "Create original stories in seconds":
      "Vytvořte originální příběhy za sekundy",
  "Academic writing made simple": "Akademické psaní jednoduše",
  "Generate powerful scripts for any medium":
      "Generujte silné scénáře pro jakékoliv médium",
  "Start Writing": "Začít Psát",
  "Create Now": "Vytvořit Nyní",
  "Start Generating": "Začít Generovat",
  "Your Stories": "Vaše Příběhy",
  "No stories yet": "Zatím žádné příběhy",
  "Start creating your first story!": "Začněte vytvářet svůj první příběh!",
  "Your Story Space Awaits": "Váš Prostor pro Příběhy Čeká",
  "Start your first story and see it appear here":
      "Začněte svůj první příběh a uvidíte ho zde",
  "Language": "Jazyk",
  "Rate us": "Ohodnoťte nás",
  "Share us": "Sdílejte nás",
  "Privacy Policy": "Zásady Ochrany Osobních Údajů",
  "Settings": "Nastavení",
  "Select Language": "Vyberte Jazyk",
  "Dashboard": "Přehled",
  "BENEFITS": "VÝHODY",
  "Subscribe": "Předplatit",
  "Weekly": "Týdně",
  "Monthly": "Měsíčně",
  "Yearly": "Ročně",
  "week": "týden",
  "months": "měsíce",
  "year": "rok",
  "Terms & Condition": "Podmínky a Pravidla",
  "No Commitment. Cancel anytime": "Bez závazků. Zrušte kdykoli",
  "No Payment Now": "Bez Platby Nyní",
  "3 days free": "3 dny zdarma",
  "Start your free trial": "Začněte bezplatnou zkušební verzi",
  "More detailed answers": "Podrobnější odpovědi",
  "Instant responds": "Okamžitá odpověď",
  "Text recognition": "Rozpoznávání textu",
  "Powered by AI": "Poháněno AI",
  "Storytelleing": "Vyprávění Příběhů",
  ' Power': " Síla",
  "Unlock your \nFill ": "Odemkněte svůj \nFill ",
  "Your History": "Vaše Historie",
  "Terms and Conditions": "Podmínky a Pravidla",
  "Short": "Krátký",
  "Medium": "Střední",
  "Long": "Dlouhý",
  "Length": "Délka",
  "Describe your topic...": "Popište své téma...",
  "Set Creativity": "Nastavit Kreativitu",
  "Standard": "Standardní",
  "Creative": "Kreativní",
  "Complex": "Komplexní",
  "Select Genre": "Vyberte Žánr",
  "Fantasy": "Fantasy",
  "Mystery": "Mystérium",
  "Thriller": "Thriller",
  "Script Tone": "Tón Scénáře",
  "Script Type": "Typ Scénáře",
  "Comedy": "Komedie",
  "Drama": "Drama",
  "Horror": "Horor",
  "Action": "Akce",
  "Romance": "Romantika",
  "Go Premium": "Přejít na Premium",
  "Unlock Everything": "Odemknout Vše",
  "Unlimited Story Generation": "Neomezené Generování Příběhů",
  "Write Longer & Detailed Essays": "Pište Delší a Podrobnější Eseje",
  "Advanced Script Writer": "Pokročilý Autor Scénářů",
  "Unlock All Styles & Tones": "Odemknout Všechny Styly a Tóny",
  "No Word/Length Limit": "Bez Omezení Slov/Délky",
  "Remove All Ads": "Odstranit Všechny Reklamy",
  "Restore": "Obnovit",
  "YouTube Video": "YouTube Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivační",
  "Advertisement": "Reklama",
  "Fairy Tale": "Pohádka",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Vyberte Styl",
  "Imaginative": "Imaginativní",
  "Innovative": "Inovativní",
  "AI Story Writer": "AI Autor Příběhů",
  "Generate": "Generovat",
  "Please wait...": "Prosím čekejte...",
  "Result": "Výsledek",
  "Regenerate": "Regenerovat",
  "Download": "Stáhnout",
  "Text copied to clipboard!": "Text zkopírován do schránky!",
  "Please enter a topic": "Prosím zadejte téma",
  "Story Magic": "Kouzlo Příběhů",
  "Let AI bring your thoughts to a full story":
      "Nechte AI přeměnit vaše myšlenky v celý příběh",
  "Smart Scripts": "Chytré Scénáře",
  "From concept to script—fast, easy, and creative":
      "Od konceptu ke scénáři—rychle, snadno a kreativně",
  "Perfect Essays": "Perfektní Eseje",
  "You have reached your free limit": "Dosáhli jste bezplatného limitu",
  "Donwload": "Stáhnout",
  "Press again to exit app": "Stiskněte znovu pro ukončení aplikace",
  "Saved to files": "TXT soubor úspěšně uložen!",
  "Error: Please try again": "Chyba: Prosím zkuste to znovu",
  "Subscription expired": "Předplatné vypršelo",
  "Purchase cancelled": "Nákup zrušen",
  "Purchase failed": "Nákup selhal",
  "Restore failed": "Obnovení selhalo",
  "Purchase Successful!": "Nákup Úspěšný!",
  "Short (200-500 words)": "Krátký (200-500 slov)",
  "Medium (500-1000 words)": "Střední (500-1000 slov)",
  "Large (1000+ words)": "Velký (1000+ slov)",
  "Academic Level": "Akademická Úroveň",
  "Type of Paper": "Typ Práce",
  "High School": "Střední Škola",
  "College": "Vysoká Škola",
  "Short Film": "Krátký Film",
  "University": "Univerzita",
  "Masters": "Magisterský",
  "Custom": "Vlastní",
  "Tiktok Video": "TikTok Video",
  "Movie": "Film",
  "Expository": "Výkladový",
  "Argumentative": "Argumentační",
  "Narrative": "Narativní",
  "Descriptive": "Popisný",
  "We're sorry to hear that 😔": "Je nám líto to slyšet 😔",
  "We'll try to improve 🙁": "Pokusíme se zlepšit 🙁",
  "Thanks for your feedback 🙂": "Děkujeme za vaši zpětnou vazbu 🙂",
  "Great! We're glad you like it 😊": "Skvělé! Jsme rádi, že se vám to líbí 😊",
  "Awesome! Thank you so much! 🎉": "Úžasné! Moc děkujeme! 🎉",
  "Maybe Later": "Možná Později",
  "Tap a star to rate your experience":
      "Klepněte na hvězdu pro ohodnocení vašeho zážitku",
  "Enjoying AI Math Solver?": "Líbí se vám AI Math Solver?",
  "Thank you for rating us": "Děkujeme za vaše hodnocení",
  "Submit Rating": "Odeslat Hodnocení",
  "Hindi": "Hindština",
  "Enjoying AI Story Generator?": "Líbí se vám AI Generátor Příběhů?",
  AppKeys.arabic: "Arabština",
  AppKeys.chinese: "Čínština",
  AppKeys.english: "Angličtina",
  AppKeys.french: "Francouzština",
  AppKeys.german: "Němčina",
  AppKeys.hindi: "Hindština",
  AppKeys.indonesian: "Indonéština",
  AppKeys.japanese: "Japonština",
  AppKeys.korean: "Korejština",
  AppKeys.portuguese: "Portugalština",
  AppKeys.russian: "Ruština",
  AppKeys.spanish: "Španělština",
  AppKeys.turkish: "Turečtina",
  'Download As': 'Stáhnout Jako',
  'Choose format to download': 'Vyberte formát ke stažení',
  'Text File': 'Textový Soubor',
  'PDF File': 'PDF Soubor',
  'Copy': 'Kopírovat',
  'Share': 'Sdílet',
  'Text copied!': 'Text zkopírován!',
  'PDF saved successfully!': 'PDF úspěšně uložen!',
  'Error creating PDF: Please try again':
      'Chyba při vytváření PDF: Prosím zkuste to znovu',
  'Character Story': 'Příběh Postavy',
  'Character Details': 'Detaily Postavy',
  'Character Name': 'Jméno Postavy',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Věk (např. 25, Mladý Dospělý, Starověký)',
  'Personality (e.g., brave, shy, cunning)':
      'Osobnost (např. odvážný, stydlivý, mazaný)',
  'Role (e.g., Hero, Villain, Mentor)': 'Role (např. Hrdina, Padouch, Mentor)',
  'Additional Details (optional)': 'Další Detaily (volitelné)',
  'Output Style': 'Výstupní Styl',
  'Generate Character': 'Generovat Postavu',
  'Please enter character name': 'Prosím zadejte jméno postavy',
  'Please enter character role': 'Prosím zadejte roli postavy',
  'Detailed': 'Podrobný',
  'Brief': 'Stručný',
  'Elaborate': 'Rozsáhlý',
  'Create detailed character backstories': 'Vytvořte podrobné příběhy postav',
  'Create Character': 'Vytvořit Postavu',
  'Transform and improve your existing stories':
      'Transformujte a vylepšete své stávající příběhy',
  'Rewrite Now': 'Přepsat Nyní',
  'Generate catchy titles for your stories':
      'Generujte chytlavé titulky pro vaše příběhy',
  'Generate Titles': 'Generovat Titulky',
  'Rewrite Story': 'Přepsat Příběh',
  'Paste Your Story': 'Vložte Svůj Příběh',
  'Paste your story here to rewrite...': 'Vložte svůj příběh sem k přepsání...',
  'Select Tone': 'Vyberte Tón',
  'Rewrite Style': 'Styl Přepsání',
  'Output Length': 'Výstupní Délka',
  'Please paste your story': 'Prosím vložte svůj příběh',
  'Story is too short. Please provide more content.':
      'Příběh je příliš krátký. Prosím poskytněte více obsahu.',
  'Same': 'Stejný',
  'More Dramatic': 'Více Dramatický',
  'More Humorous': 'Více Humorný',
  'More Emotional': 'Více Emocionální',
  'More Suspenseful': 'Více Napínavý',
  'Lighter': 'Lehčí',
  'Improved': 'Vylepšený',
  'Simplified': 'Zjednodušený',
  'More Descriptive': 'Více Popisný',
  'More Dialogue': 'Více Dialogu',
  'More Action': 'Více Akce',
  'Literary': 'Literární',
  'Shorter': 'Kratší',
  'Longer': 'Delší',
  'Much Longer': 'Mnohem Delší',
  'Title Generator': 'Generátor Titulků',
  'Story/Book Topic': 'Téma Příběhu/Knihy',
  'Keywords (Optional)': 'Klíčová Slova (Volitelné)',
  'Describe your story topic or theme...': 'Popište téma svého příběhu...',
  'e.g., magic, dragon, adventure': 'např. magie, drak, dobrodružství',
  'Title For': 'Titulek Pro',
  'Title Style': 'Styl Titulku',
  "Adventure": "Dobrodružství",
  'Number of Titles': 'Počet Titulků',
  'Book': 'Kniha',
  'Short Story': 'Povídka',
  'Novel': 'Román',
  'Chapter': 'Kapitola',
  'Series': 'Série',
  'Simple': 'Jednoduchý',
  'Mysterious': 'Tajemný',
  'Dramatic': 'Dramatický',
  'Catchy': 'Chytlavý',
  'Poetic': 'Poetický',
  'Kids': 'Děti',
  'Blog Writer': 'Autor Blogu',
  'Blog Topic': 'Téma Blogu',
  'Target Keywords': 'Cílová Klíčová Slova',
  'Target Audience (Optional)': 'Cílové Publikum (Volitelné)',
  'Enter your blog topic or title...': 'Zadejte téma nebo název blogu...',
  'e.g., AI writing, content marketing, SEO tips':
      'např. AI psaní, obsahový marketing, SEO tipy',
  'e.g., small business owners, bloggers':
      'např. majitelé malých firem, blogeři',
  'Article Type': 'Typ Článku',
  'Writing Tone': 'Tón Psaní',
  'Article Length': 'Délka Článku',
  'SEO Options': 'SEO Možnosti',
  'Include Meta Description': 'Zahrnout Meta Popis',
  'Include Keyword Suggestions': 'Zahrnout Návrhy Klíčových Slov',
  'Include FAQs Section': 'Zahrnout Sekci FAQ',
  'Please enter a blog topic': 'Prosím zadejte téma blogu',
  'Generate Blog': 'Generovat Blog',
  'SEO optimized articles with keywords':
      'SEO optimalizované články s klíčovými slovy',
  'Write Blog': 'Napsat Blog',
  'SEO Article': 'SEO Článek',
  'How-To Guide': 'Návod',
  'Listicle': 'Seznamový Článek',
  'Product Review': 'Recenze Produktu',
  'Opinion Piece': 'Názorový Článek',
  'News Article': 'Zpravodajský Článek',
  'Professional': 'Profesionální',
  'Casual': 'Neformální',
  'Informative': 'Informativní',
  'Persuasive': 'Přesvědčivý',
  'Friendly': 'Přátelský',
  'Authoritative': 'Autoritativní',
  'Short (500-800)': 'Krátký (500-800)',
  'Medium (800-1500)': 'Střední (800-1500)',
  'Long (1500-2500)': 'Dlouhý (1500-2500)',
  'Detailed (2500+)': 'Podrobný (2500+)',
  'YouTube Script': 'YouTube Scénář',
  'Video Topic': 'Téma Videa',
  'Key Points (Optional)': 'Klíčové Body (Volitelné)',
  'What is your video about?': 'O čem je vaše video?',
  'List key points to cover (optional)...':
      'Uveďte klíčové body k pokrytí (volitelné)...',
  'Video Duration': 'Délka Videa',
  'Script Options': 'Možnosti Scénáře',
  'Include Hook/Intro': 'Zahrnout Háček/Úvod',
  'Include Call-to-Action': 'Zahrnout Výzvu k Akci',
  'Include Timestamps': 'Zahrnout Časové Značky',
  'Please enter a video topic': 'Prosím zadejte téma videa',
  'Generate Script': 'Generovat Scénář',
  'Create scripts for videos & reels': 'Vytvářejte scénáře pro videa a reely',
  'Create Script': 'Vytvořit Scénář',
  'Storytime': 'Čas na Příběhy',
  'Documentary': 'Dokumentární',
  'Short Reel': 'Krátký Reel',
  'Educational': 'Vzdělávací',
  'Review': 'Recenze',
  'Tutorial': 'Tutoriál',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Poutavý',
  'Energetic': 'Energický',
  'Calm': 'Klidný',
  'Funny': 'Vtipný',
  'Inspired': 'Inspirovaný',
  'Film Script': 'Filmový Scénář',
  'Stage Play': 'Divadelní Hra',
  'Scene Breakdown': 'Rozbor Scén',
  'Dialogue Only': 'Pouze Dialog',
  'Ad loading please wait..': 'Reklama se načítá, prosím čekejte..',
  'Words:': 'Slova:',
  'Reading:': 'Čtení:',
};
