import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> da = {
  AppKeys.lblChooseLanguage: "Vælg sprog",
  "All": "Alt",
  "AI Story Generator": "AI Story Generator",
  "Story Generator": "Story Generator",
  "Essay Writer": "Essay Forfatter",
  "Essay length": "Essaylængde",
  "Script Generator": "Manuskript Generator",
  "Create original stories in seconds": "Opret originale historier på sekunder",
  "Academic writing made simple": "Akademisk skrivning gjort enkel",
  "Generate powerful scripts for any medium":
      "Generer kraftfulde scripts til ethvert medium",
  "Start Writing": "Begynd at skrive",
  "Create Now": "Opret nu",
  "Start Generating": "Begynd at generere",
  "Your Stories": "Dine historier",
  "No stories yet": "Ingen historier endnu",
  "Start creating your first story!": "Begynd at oprette din første historie!",
  "Your Story Space Awaits": "Dit historirum venter",
  "Start your first story and see it appear here":
      "Start din første historie og se den dukke op her",
  "Language": "Sprog",
  "Rate us": "Bedøm os",
  "Share us": "Del os",
  "Privacy Policy": "Privatlivspolitik",
  "Settings": "Indstillinger",
  "Select Language": "Vælg sprog",
  "Dashboard": "Dashboard",
  "BENEFITS": "FORDELE",
  "Subscribe": "Abonner",
  "Weekly": "Ugentlig",
  "Monthly": "Månedligt",
  "Yearly": "Årligt",
  "week": "uge",
  "months": "måneder",
  "year": "år",
  "Terms & Condition": "Vilkår og betingelser",
  "No Commitment. Cancel anytime": "Ingen forpligtelse. Annuller når som helst",
  "No Payment Now": "Ingen betaling nu",
  "3 days free": "3 dage gratis",
  "Start your free trial": "Start din gratis prøveperiode",
  "More detailed answers": "Mere detaljerede svar",
  "Instant responds": "Øjeblikkelig reaktion",
  "Text recognition": "Tekstgenkendelse",
  "Powered by AI": "Drevet af AI",
  "Storytelleing": "Historiefremstilling",
  " Power": "Kraft",
  "Unlock your \nFill ": "Lås op for din \nFill",
  "Your History": "Din historie",
  "Terms and Conditions": "Vilkår og betingelser",
  "Short": "Kort",
  "Medium": "Medium",
  "Long": "Lang",
  "Length": "Længde",
  "Describe your topic...": "Beskriv dit emne...",
  "Set Creativity": "Indstil kreativitet",
  "Standard": "Standard",
  "Creative": "Kreativ",
  "Complex": "Kompleks",
  "Select Genre": "Vælg genre",
  "Fantasy": "Fantasy",
  "Mystery": "Mysterium",
  "Thriller": "Thriller",
  "Script Tone": "Manuskripttone",
  "Script Type": "Manuskripttype",
  "Comedy": "Komedie",
  "Drama": "Drama",
  "Horror": "Horror",
  "Action": "Action",
  "Romance": "Romance",
  "Go Premium": "Gå Premium",
  "Unlock Everything": "Lås alt op",
  "Unlimited Story Generation": "Ubegrænset historiegenerering",
  "Write Longer & Detailed Essays": "Skriv længere og mere detaljerede essays",
  "Advanced Script Writer": "Avanceret manuskriptforfatter",
  "Unlock All Styles & Tones": "Lås alle stilarter og toner op",
  "No Word/Length Limit": "Ingen ord-/længdebegrænsning",
  "Remove All Ads": "Fjern alle annoncer",
  "3 days free": "3 dage gratis",
  "Restore": "Gendan",
  "YouTube Video": "YouTube-video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motiverende",
  "Advertisement": "Annonce",
  "Fairy Tale": "Eventyr",
  "Sci-Fi": "Science Fiction",
  "Select Style": "Vælg stil",
  "Imaginative": "Fantasisyg",
  "Innovative": "Innovativ",
  "AI Story Writer": "AI Story Writer",
  "Generate": "Generer",
  "Please wait...": "Venligst vent...",
  "Result": "Resultat",
  "Regenerate": "Regenerer",
  "Download": "Download",
  "Text copied to clipboard!": "Tekst kopieret til udklipsholder!",
  "Please enter a topic": "Venligst angiv et emne",
  "Story Magic": "Story Magic",
  "Let AI bring your thoughts to a full story":
      "Lad AI bringe dine tanker til en fuld historie",
  "Smart Scripts": "Smart Scripts",
  "From concept to script—fast, easy, and creative":
      "Fra koncept til script—hurtigt, nemt og kreativt",
  "Perfect Essays": "Perfekte essays",
  "You have reached your free limit": "Du har nået din gratis grænse",
  "Donwload": "Download",
  "Press again to exit app": "Tryk igen for at afslutte appen",
  "Saved to files": "TXT-fil gemt med succes!",
  "Error: Please try again": "Fejl: Prøv igen",
  "Subscription expired": "Abonnement udløbet",
  "Purchase cancelled": "Køb annulleret",
  "Purchase failed": "Køb mislykkedes",
  "Restore failed": "Gendannelse mislykkedes",
  "Purchase Successful!": "Køb succesfuldt!",
  "Short (200-500 words)": "Kort (200-500 ord)",
  "Medium (500-1000 words)": "Medium (500-1000 ord)",
  "Large (1000+ words)": "Stort (1000+ ord)",
  "Academic Level": "Akademisk niveau",
  "Type of Paper": "Papertype",
  "High School": "Gymnasiet",
  "College": "Kollegium",
  "Short Film": "Kortfilm",
  "University": "Universitet",
  "Masters": "Masters",
  "Custom": "Tilpasset",
  "YouTube Video": "YouTube-video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "TikTok-video",
  "Movie": "Film",
  "Expository": "Fremstillet",
  "Argumentative": "Argumentativ",
  "Narrative": "Fortælling",
  "Descriptive": "Beskrivende",
  "We're sorry to hear that 😔": "Vi er kede af at høre det 😔",
  "We'll try to improve 🙁": "Vi vil prøve at forbedre 🙁",
  "Thanks for your feedback 🙂": "Tak for din feedback 🙂",
  "Great! We're glad you like it 😊":
      "Fantastisk! Vi er glade for, at du kan lide det 😊",
  "Awesome! Thank you so much! 🎉": "Awesome! Tak skal du have! 🎉",
  "Maybe Later": "Måske senere",
  "Tap a star to rate your experience":
      "Tryk på en stjerne for at bedømme din oplevelse",
  "Enjoying AI Math Solver?": "Nyder du AI Math Solver?",
  "Thank you for rating us": "Tak for at bedømme os",
  "Submit Rating": "Indsend vurdering",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Nyder du AI Story Generator?",
  AppKeys.arabic: "Arabisk",
  AppKeys.chinese: "Kinesisk",
  AppKeys.english: "Engelsk",
  AppKeys.french: "Fransk",
  AppKeys.german: "Tysk",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesisk",
  AppKeys.japanese: "Japansk",
  AppKeys.korean: "Koreansk",
  AppKeys.portuguese: "Portugisisk",
  AppKeys.russian: "Russisk",
  AppKeys.spanish: "Spansk",
  AppKeys.turkish: "Tyrkisk",
  "Download As": 'Download som',
  "Choose format to download": 'Vælg format til download',
  "Text File": 'Tekstfil',
  "PDF File": 'PDF-fil',
  "Copy": 'Kopi',
  "Share": 'Del',
  "Text copied!": 'Tekst kopieret!',
  "PDF saved successfully!": 'PDF gemt med succes!',
  "Error creating PDF: Please try again":
      'Fejl ved oprettelse af PDF: Prøv igen',
  "Character Story": 'Karakterhistorie',
  "Character Details": 'Karakterdetaljer',
  "Character Name": 'Karakternavn',
  "Age (e.g., 25, Young Adult, Ancient)":
      'Alder (f.eks. 25, ung voksen, gammel)',
  "Personality (e.g., brave, shy, cunning)":
      'Personlighed (f.eks. dristig, sky, listig)',
  "Role (e.g., Hero, Villain, Mentor)": 'Rolle (f.eks. helt, skurk, mentor)',
  "Additional Details (optional)": 'Yderligere detaljer (valgfrit)',
  "Output Style": 'Outputstil',
  "Generate Character": 'Generer karakter',
  "Please enter character name": 'Venligst angiv karakternavn',
  "Please enter character role": 'Venligst angiv karakterrolle',
  "Detailed": 'Detaljeret',
  "Brief": 'Kort',
  "Elaborate": 'Udarbejde',
  "Create detailed character backstories":
      'Opret detaljerede karakterbaghistorier',
  "Create Character": 'Opret karakter',
  "Transform and improve your existing stories":
      'Transformer og forbedre dine eksisterende historier',
  "Rewrite Now": 'Omskriv nu',
  "Generate catchy titles for your stories":
      'Generer fængslende titler til dine historier',
  "Generate Titles": 'Generer titler',
  "Rewrite Story": 'Omskriv historie',
  "Paste Your Story": 'Indsæt din historie',
  "Paste your story here to rewrite...":
      'Indsæt din historie her for at omskrive...',
  "Select Tone": 'Vælg tone',
  "Rewrite Style": 'Omskrivningsstil',
  "Output Length": 'Outputlængde',
  "Please paste your story": 'Venligst indsæt din historie',
  "Story is too short. Please provide more content.":
      'Historien er for kort. Venligst giv mere indhold.',
  "Same": 'Samme',
  "More Dramatic": 'Mere dramatisk',
  "More Humorous": 'Mere humoristisk',
  "More Emotional": 'Mere følelsesmæssigt',
  "More Suspenseful": 'Mere spændende',
  "Lighter": 'Lettere',
  "Improved": 'Forbedret',
  "Simplified": 'Forenklet',
  "More Descriptive": 'Mere beskrivende',
  "More Dialogue": 'Mere dialog',
  "More Action": 'Mere handling',
  "Literary": 'Litterær',
  "Shorter": 'Kortere',
  "Longer": 'Længere',
  "Much Longer": 'Meget længere',
  "Title Generator": 'Titalgenerator',
  "Story/Book Topic": 'Historier-/bogafsnittet',
  "Keywords (Optional)": 'Nøgleord (valgfrit)',
  "Describe your story topic or theme...":
      'Beskriv dit historieemne eller tema...',
  "e.g., magic, dragon, adventure": 'f.eks. magi, drage, eventyr',
  "Title For": 'Titel til',
  "Title Style": 'Titel stil',
  "Number of Titles": 'Antal titler',
  "Book": 'Bog',
  "Short Story": 'Novelle',
  "Novel": 'Roman',
  "Chapter": 'Kapitel',
  "Series": 'Serie',
  "Simple": 'Enkel',
  "Mysterious": 'Mystisk',
  "Dramatic": 'Dramatisk',
  "Catchy": 'Fængslende',
  "Poetic": 'Poetisk',
  "Kids": 'Børn',
  "Blog Writer": 'Blog Forfatter',
  "Blog Topic": 'Blog-emne',
  "Target Keywords": 'Mål nøgleord',
  "Target Audience (Optional)": 'Målgruppe (valgfrit)',
  "Enter your blog topic or title...": 'Angiv dit blog-emne eller titel...',
  "e.g., AI writing, content marketing, SEO tips":
      'f.eks. AI-skrivning, indholdsmarkedsføring, SEO-tips',
  "e.g., small business owners, bloggers":
      'f.eks. små virksomhedseiere, bloggere',
  "Article Type": 'Artikeltype',
  "Writing Tone": 'Skrivetone',
  "Article Length": 'Artikellængde',
  "SEO Options": 'SEO-indstillinger',
  "Include Meta Description": 'Inkluder metabeskrivelse',
  "Include Keyword Suggestions": 'Inkluder nøgleordsforslag',
  "Include FAQs Section": 'Inkluder OSS-afsnit',
  "Please enter a blog topic": 'Venligst angiv et blog-emne',
  "Generate Blog": 'Generer blog',
  "SEO optimized articles with keywords":
      'SEO-optimerede artikler med nøgleord',
  "Write Blog": 'Skriv blog',
  "SEO Article": 'SEO-artikel',
  "How-To Guide": 'Vejledning til hvordan',
  "Listicle": 'Listeartikel',
  "Product Review": 'Produktanmeldelse',
  "Opinion Piece": 'Meningsudlignelse',
  "News Article": 'Nyhedsartikel',
  "Professional": 'Professionel',
  "Casual": 'Afslappet',
  "Informative": 'Informativ',
  "Persuasive": 'Overbevisende',
  "Friendly": 'Venligt',
  "Authoritative": 'Myndighedsperson',
  "Short (500-800)": 'Kort (500-800)',
  "Medium (800-1500)": 'Medium (800-1500)',
  "Long (1500-2500)": 'Lang (1500-2500)',
  "Detailed (2500+)": 'Detaljeret (2500+)',
  "YouTube Script": 'YouTube-script',
  "Video Topic": 'Videoemne',
  "Key Points (Optional)": 'Vigtigste punkter (valgfrit)',
  "What is your video about?": 'Hvad handler din video om?',
  "List key points to cover (optional)...":
      'List vigtigste punkter til dækning (valgfrit)...',
  "Video Duration": 'Videolængde',
  "Script Options": 'Scriptindstillinger',
  "Include Hook/Intro": 'Inkluder krog/intro',
  "Include Call-to-Action": 'Inkluder opfordring til handling',
  "Include Timestamps": 'Inkluder tidsstempler',
  "Please enter a video topic": 'Venligst angiv et videoemne',
  "Generate Script": 'Generer script',
  "Create scripts for videos & reels": 'Opret scripts til videoer og reels',
  "Create Script": 'Opret script',
  "Storytime": 'Historietime',
  "Documentary": 'Dokumentar',
  "Short Reel": 'Kort reel',
  "Educational": 'Uddannelse',
  "Review": 'Anmeldelse',
  "Tutorial": 'Vejledning',
  "< 1 min (Shorts)": '< 1 min (Shorts)',
  "1-3 min": '1-3 min',
  "5-10 min": '5-10 min',
  "10-20 min": '10-20 min',
  "20+ min": '20+ min',
  "Engaging": 'Fængslende',
  "Energetic": 'Energisk',
  "Calm": 'Rolig',
  "Funny": 'Sjovt',
  "Inspired": 'Inspireret',
  "Film Script": 'Filmscript',
  "Stage Play": 'Sceneteaterstykke',
  "Scene Breakdown": 'Opbygning af scene',
  "Dialogue Only": 'Kun dialog',
  "Ad loading please wait..": 'Annoncen indlæses, venligst vent..',
  "Words:": 'Ord:',
  "Reading:": 'Læsning:',
};
