import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> de = {
  AppKeys.lblChooseLanguage: "Sprache wählen",
  "All": "Alle",
  "AI Story Generator": "KI-Geschichtengenerator",
  "Story Generator": "Geschichtengenerator",
  "Essay Writer": "Aufsatzschreiber",
  "Essay length": "Aufsatzlänge",
  "Script Generator": "Drehbuchgenerator",
  "Create original stories in seconds":
      "Erstellen Sie originelle Geschichten in Sekunden",
  "Academic writing made simple": "Akademisches Schreiben leicht gemacht",
  "Generate powerful scripts for any medium":
      "Erstellen Sie leistungsstarke Drehbücher für jedes Medium",
  "Start Writing": "Mit dem Schreiben beginnen",
  "Create Now": "Jetzt erstellen",
  "Start Generating": "Generierung starten",
  "Your Stories": "Ihre Geschichten",
  "No stories yet": "Noch keine Geschichten",
  "Start creating your first story!":
      "Beginnen Sie mit Ihrer ersten Geschichte!",
  "Your Story Space Awaits": "Ihr Geschichtenraum wartet auf Sie",
  "Start your first story and see it appear here":
      "Beginnen Sie Ihre erste Geschichte und sehen Sie sie hier erscheinen",
  "Language": "Sprache",
  "Rate us": "Bewerten Sie uns",
  "Share us": "Teilen Sie uns",
  "Privacy Policy": "Datenschutzrichtlinie",
  "Settings": "Einstellungen",
  "Select Language": "Sprache auswählen",
  "Dashboard": "Dashboard",
  "BENEFITS": "VORTEILE",
  "Subscribe": "Abonnieren",
  "Weekly": "Wöchentlich",
  "Monthly": "Monatlich",
  "Yearly": "Jährlich",
  "week": "Woche",
  "months": "Monate",
  "year": "Jahr",
  "Terms & Condition": "Geschäftsbedingungen",
  "No Commitment. Cancel anytime": "Keine Verpflichtung. Jederzeit kündbar",
  "No Payment Now": "Jetzt keine Zahlung",
  "3 days free": "3 Tage kostenlos",
  "Start your free trial": "Starten Sie Ihre kostenlose Testversion",
  "More detailed answers": "Detailliertere Antworten",
  "Instant responds": "Sofortige Antworten",
  "Text recognition": "Texterkennung",
  "Powered by AI": "Angetrieben von KI",
  "Storytelleing": "Geschichtenerzählen",
  ' Power': "Kraft",
  "Unlock your \nFill ": "Entsperren Sie Ihr \nFill",
  "Your History": "Ihr Verlauf",
  "Terms and Conditions": "Allgemeine Geschäftsbedingungen",
  "Short": "Kurz",
  "Medium": "Mittel",
  "Long": "Lang",
  "Length": "Länge",
  "Describe your topic...": "Beschreiben Sie Ihr Thema...",
  "Set Creativity": "Kreativität einstellen",
  "Standard": "Standard",
  "Creative": "Kreativ",
  "Complex": "Komplex",
  "Select Genre": "Genre auswählen",
  "Fantasy": "Fantasy",
  "Mystery": "Geheimnis",
  "Thriller": "Thriller",
  "Script Tone": "Drehbuchton",
  "Script Type": "Drehbuchtyp",
  "Comedy": "Komödie",
  "Drama": "Drama",
  "Horror": "Horror",
  "Action": "Action",
  "Romance": "Romantik",
  "Motivational": "Motivierend",
  "Advertisement": "Werbung",
  "Fairy Tale": "Märchen",
  "Sci-Fi": "Science-Fiction",
  "Select Style": "Stil auswählen",
  "Imaginative": "Fantasievoll",
  "Innovative": "Innovativ",
  "Generate": "Generieren",
  "Please wait...": "Bitte warten...",
  "Result": "Ergebnis",
  "Regenerate": "Neu generieren",
  "Download": "Herunterladen",
  "Text copied to clipboard!": "Text in Zwischenablage kopiert!",
  "Please enter a topic": "Bitte geben Sie ein Thema ein",
  "Story Magic": "Geschichtenmagie",
  "Let AI bring your thoughts to a full story":
      "Lassen Sie KI Ihre Gedanken zu einer vollständigen Geschichte werden",
  "Smart Scripts": "Intelligente Skripte",
  "From concept to script—fast, easy, and creative":
      "Vom Konzept zum Drehbuch—schnell, einfach und kreativ",
  "Perfect Essays": "Perfekte Aufsätze",
  "You have reached your free limit":
      "Sie haben Ihr kostenloses Limit erreicht",
  "Donwload": "Downloads",
  "Press again to exit app": "Drücken Sie erneut, um die App zu beenden",
  "Saved to files": "TXT-Datei erfolgreich gespeichert!",
  "Error: Please try again": "Fehler: Bitte versuchen Sie es erneut",
  "Subscription expired": "Abonnement abgelaufen",
  "Purchase cancelled": "Kauf abgebrochen",
  "Purchase failed": "Kauf fehlgeschlagen",
  "Restore failed": "Wiederherstellung fehlgeschlagen",
  "Purchase Successful!": "Kauf erfolgreich!",
  "Short (200-500 words)": "Kurz (200-500 Wörter)",
  "Medium (500-1000 words)": "Mittel (500-1000 Wörter)",
  "Large (1000+ words)": "Groß (1000+ Wörter)",
  "Academic Level": "Akademisches Niveau",
  "Type of Paper": "Art des Papiers",
  "High School": "Gymnasium",
  "College": "Hochschule",
  "Short Film": "Kurzfilm",
  "University": "Universität",
  "Masters": "Master",
  "Custom": "Benutzerdefiniert",
  "YouTube Video": "YouTube-Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Tiktok-Video",
  "Movie": "Film",
  "Expository": "Erklärend",
  "Argumentative": "Argumentativ",
  "Narrative": "Erzählend",
  "Descriptive": "Beschreibend",

  AppKeys.arabic: "Arabisch",
  AppKeys.chinese: "Chinesisch",
  AppKeys.english: "Englisch",
  AppKeys.french: "Französisch",
  AppKeys.german: "Deutsch",
  AppKeys.hindi: "Hindi",
  "We're sorry to hear that 😔": "Es tut uns leid, das zu hören 😔",
  "We'll try to improve 🙁": "Wir werden versuchen, uns zu verbessern 🙁",
  "Thanks for your feedback 🙂": "Danke für dein Feedback 🙂",
  "Great! We're glad you like it 😊":
      "Großartig! Wir freuen uns, dass es dir gefällt 😊",
  "Awesome! Thank you so much! 🎉": "Fantastisch! Vielen Dank! 🎉",
  "Maybe Later": "Vielleicht später",
  "Tap a star to rate your experience":
      "Tippe auf einen Stern, um deine Erfahrung zu bewerten",
  "Enjoying AI Math Solver?": "Gefällt dir der AI Math Solver?",
  "Thank you for rating us": "Danke für deine Bewertung",
  "Submit Rating": "Bewertung absenden",
  "Hindi": "Hindi",
  "Go Premium": "Premium erhalten",
  "Unlock Everything": "Alles freischalten",
  "Unlimited Story Generation": "Unbegrenzte Geschichtsgenerierung",
  "Write Longer & Detailed Essays":
      "Schreiben Sie längere und detaillierte Essays",
  "Advanced Script Writer": "Erweiterter Script-Writer",
  "Unlock All Styles & Tones": "Alle Stile und Töne freischalten",
  "No Word/Length Limit": "Keine Wort-/Längenbegrenzung",
  "Remove All Ads": "Alle Anzeigen entfernen",
  "3 days free": "3 Tage kostenlos",
  "Enjoying AI Story Generator?": "Gefällt dir der AI Story Generator?",
  "Restore": "Wiederherstellen",
  "YouTube Video": "YouTube-Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  AppKeys.indonesian: "Indonesisch",
  AppKeys.japanese: "Japanisch",
  AppKeys.korean: "Koreanisch",
  AppKeys.portuguese: "Portugiesisch",
  AppKeys.russian: "Russisch",
  AppKeys.spanish: "Spanisch",
  AppKeys.turkish: "Türkisch",
  "AI Story Writer": "KI-Geschichtenschreiber",
};
