import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> el = {
  AppKeys.lblChooseLanguage: "Επιλέξτε Γλώσσα",
  AppKeys.arabic: "Αραβικά",
  AppKeys.chinese: "Κινέζικα",
  AppKeys.english: "Αγγλικά",
  AppKeys.french: "Γαλλικά",
  AppKeys.german: "Γερμανικά",
  AppKeys.hindi: "Χίντι",
  AppKeys.indonesian: "Ινδονησιακά",
  AppKeys.japanese: "Ιαπωνικά",
  AppKeys.korean: "Κορεάτικα",
  AppKeys.portuguese: "Πορτογαλικά",
  AppKeys.russian: "Ρωσικά",
  AppKeys.spanish: "Ισπανικά",
  AppKeys.turkish: "Τουρκικά",
  AppKeys.btnNext: "Επόμενο",
  AppKeys.dahsboard: "Πίνακας Ελέγχου",
  AppKeys.yourStories: "Οι Ιστορίες Σας",
  AppKeys.setting: "Ρυθμίσεις",
  AppKeys.btngetStarted: "Ξεκινήστε",
  '': "Ξεκινήστε",

  'Download As': 'Λήψη Ως',
  'Choose format to download': 'Επιλέξτε μορφή για λήψη',
  'Text File': 'Αρχείο Κειμένου',
  'PDF File': 'Αρχείο PDF',
  'Copy': 'Αντιγραφή',
  'Share': 'Κοινοποίηση',
  'Download': 'Λήψη',
  'Text copied!': 'Το κείμενο αντιγράφηκε!',
  'PDF saved successfully!': 'Το PDF αποθηκεύτηκε επιτυχώς!',
  'Saved to files': 'Αποθηκεύτηκε στα αρχεία',
  'Error: Please try again': 'Σφάλμα: Παρακαλώ δοκιμάστε ξανά',
  'Error creating PDF: Please try again':
      'Σφάλμα δημιουργίας PDF: Παρακαλώ δοκιμάστε ξανά',

  'Character Story': 'Ιστορία Χαρακτήρα',
  'Character Details': 'Λεπτομέρειες Χαρακτήρα',
  'Character Name': 'Όνομα Χαρακτήρα',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Ηλικία (π.χ., 25, Νεαρός Ενήλικας, Αρχαίος)',
  'Personality (e.g., brave, shy, cunning)':
      'Προσωπικότητα (π.χ., γενναίος, ντροπαλός, πονηρός)',
  'Role (e.g., Hero, Villain, Mentor)': 'Ρόλος (π.χ., Ήρωας, Κακός, Μέντορας)',
  'Additional Details (optional)': 'Πρόσθετες Λεπτομέρειες (προαιρετικό)',
  'Select Genre': 'Επιλέξτε Είδος',
  'Output Style': 'Στυλ Εξόδου',
  'Generate Character': 'Δημιουργία Χαρακτήρα',
  'Please enter character name': 'Παρακαλώ εισάγετε όνομα χαρακτήρα',
  'Please enter character role': 'Παρακαλώ εισάγετε ρόλο χαρακτήρα',
  'Fantasy': 'Φαντασία',
  'Sci-Fi': 'Επιστημονική Φαντασία',
  'Romance': 'Ρομαντικό',
  'Horror': 'Τρόμου',
  'Comedy': 'Κωμωδία',
  'Drama': 'Δράμα',
  'Adventure': 'Περιπέτεια',
  'Detailed': 'Λεπτομερές',
  'Brief': 'Σύντομο',
  'Elaborate': 'Εκτεταμένο',

  'Create detailed character backstories':
      'Δημιουργήστε λεπτομερείς ιστορίες υπόβαθρου χαρακτήρων',
  'Create Character': 'Δημιουργία Χαρακτήρα',
  'Transform and improve your existing stories':
      'Μεταμορφώστε και βελτιώστε τις υπάρχουσες ιστορίες σας',
  'Rewrite Now': 'Ξαναγράψτε Τώρα',
  'Generate catchy titles for your stories':
      'Δημιουργήστε ελκυστικούς τίτλους για τις ιστορίες σας',
  'Generate Titles': 'Δημιουργία Τίτλων',

  'Rewrite Story': 'Ξαναγράψτε Ιστορία',
  'Paste Your Story': 'Επικολλήστε την Ιστορία Σας',
  'Paste your story here to rewrite...':
      'Επικολλήστε την ιστορία σας εδώ για ξαναγραφή...',
  'Select Tone': 'Επιλέξτε Τόνο',
  'Rewrite Style': 'Στυλ Ξαναγραφής',
  'Output Length': 'Μήκος Εξόδου',
  'Please paste your story': 'Παρακαλώ επικολλήστε την ιστορία σας',
  'Story is too short. Please provide more content.':
      'Η ιστορία είναι πολύ σύντομη. Παρακαλώ δώστε περισσότερο περιεχόμενο.',
  'Same': 'Ίδιο',
  'More Dramatic': 'Πιο Δραματικό',
  'More Humorous': 'Πιο Χιουμοριστικό',
  'More Emotional': 'Πιο Συναισθηματικό',
  'More Suspenseful': 'Πιο Αγωνιώδες',
  'Lighter': 'Πιο Ελαφρύ',
  'Improved': 'Βελτιωμένο',
  'Simplified': 'Απλοποιημένο',
  'More Descriptive': 'Πιο Περιγραφικό',
  'More Dialogue': 'Περισσότερος Διάλογος',
  'More Action': 'Περισσότερη Δράση',
  'Literary': 'Λογοτεχνικό',
  'Shorter': 'Πιο Σύντομο',
  'Longer': 'Πιο Μακρύ',
  'Much Longer': 'Πολύ Πιο Μακρύ',

  'Title Generator': 'Δημιουργός Τίτλων',
  'Story/Book Topic': 'Θέμα Ιστορίας/Βιβλίου',
  'Keywords (Optional)': 'Λέξεις-κλειδιά (Προαιρετικό)',
  'Describe your story topic or theme...':
      'Περιγράψτε το θέμα της ιστορίας σας...',
  'e.g., magic, dragon, adventure': 'π.χ., μαγεία, δράκος, περιπέτεια',
  'Title For': 'Τίτλος Για',
  'Title Style': 'Στυλ Τίτλου',
  'Number of Titles': 'Αριθμός Τίτλων',
  'Please enter a topic': 'Παρακαλώ εισάγετε θέμα',
  'Book': 'Βιβλίο',
  'Short Story': 'Διήγημα',
  'Novel': 'Μυθιστόρημα',
  'Chapter': 'Κεφάλαιο',
  'Series': 'Σειρά',
  'Creative': 'Δημιουργικό',
  'Simple': 'Απλό',
  'Mysterious': 'Μυστηριώδες',
  'Dramatic': 'Δραματικό',
  'Catchy': 'Ελκυστικό',
  'Poetic': 'Ποιητικό',
  'Mystery': 'Μυστήριο',
  'Thriller': 'Θρίλερ',
  'Kids': 'Παιδιά',

  'Blog Writer': 'Συγγραφέας Blog',
  'Blog Topic': 'Θέμα Blog',
  'Target Keywords': 'Στοχευμένες Λέξεις-κλειδιά',
  'Target Audience (Optional)': 'Στοχευμένο Κοινό (Προαιρετικό)',
  'Enter your blog topic or title...': 'Εισάγετε το θέμα ή τίτλο του blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'π.χ., συγγραφή AI, μάρκετινγκ περιεχομένου, συμβουλές SEO',
  'e.g., small business owners, bloggers':
      'π.χ., ιδιοκτήτες μικρών επιχειρήσεων, bloggers',
  'Article Type': 'Τύπος Άρθρου',
  'Writing Tone': 'Τόνος Γραφής',
  'Article Length': 'Μήκος Άρθρου',
  'SEO Options': 'Επιλογές SEO',
  'Include Meta Description': 'Συμπερίληψη Μετα-περιγραφής',
  'Include Keyword Suggestions': 'Συμπερίληψη Προτάσεων Λέξεων-κλειδιών',
  'Include FAQs Section': 'Συμπερίληψη Ενότητας Συχνών Ερωτήσεων',
  'Please enter a blog topic': 'Παρακαλώ εισάγετε θέμα blog',
  'Generate Blog': 'Δημιουργία Blog',
  'SEO optimized articles with keywords':
      'Βελτιστοποιημένα για SEO άρθρα με λέξεις-κλειδιά',
  'Write Blog': 'Γράψτε Blog',
  'SEO Article': 'Άρθρο SEO',
  'How-To Guide': 'Οδηγός Πώς-να',
  'Listicle': 'Άρθρο Λίστας',
  'Product Review': 'Κριτική Προϊόντος',
  'Opinion Piece': 'Άρθρο Γνώμης',
  'News Article': 'Ειδησεογραφικό Άρθρο',
  'Professional': 'Επαγγελματικό',
  'Casual': 'Ανεπίσημο',
  'Informative': 'Ενημερωτικό',
  'Persuasive': 'Πειστικό',
  'Friendly': 'Φιλικό',
  'Authoritative': 'Αυθεντικό',
  'Short (500-800)': 'Σύντομο (500-800)',
  'Medium (800-1500)': 'Μεσαίο (800-1500)',
  'Long (1500-2500)': 'Μακρύ (1500-2500)',
  'Detailed (2500+)': 'Λεπτομερές (2500+)',

  'YouTube Script': 'Σενάριο YouTube',
  'Script Type': 'Τύπος Σεναρίου',
  'Video Topic': 'Θέμα Βίντεο',
  'Key Points (Optional)': 'Βασικά Σημεία (Προαιρετικό)',
  'What is your video about?': 'Ποιο είναι το θέμα του βίντεό σας;',
  'List key points to cover (optional)...':
      'Αναφέρετε τα βασικά σημεία (προαιρετικό)...',
  'Video Duration': 'Διάρκεια Βίντεο',
  'Script Tone': 'Τόνος Σεναρίου',
  'Script Options': 'Επιλογές Σεναρίου',
  'Include Hook/Intro': 'Συμπερίληψη Άγκιστρου/Εισαγωγής',
  'Include Call-to-Action': 'Συμπερίληψη Πρόσκλησης για Δράση',
  'Include Timestamps': 'Συμπερίληψη Χρονοσημάνσεων',
  'Please enter a video topic': 'Παρακαλώ εισάγετε θέμα βίντεο',
  'Generate Script': 'Δημιουργία Σεναρίου',
  'Create scripts for videos & reels':
      'Δημιουργήστε σενάρια για βίντεο και reels',
  'Create Script': 'Δημιουργία Σεναρίου',
  'Storytime': 'Ώρα Ιστορίας',
  'Documentary': 'Ντοκιμαντέρ',
  'Short Reel': 'Σύντομο Reel',
  'Motivational': 'Παρακινητικό',
  'Educational': 'Εκπαιδευτικό',
  'Review': 'Κριτική',
  'Tutorial': 'Οδηγός',
  '< 1 min (Shorts)': '< 1 λεπτό (Shorts)',
  '1-3 min': '1-3 λεπτά',
  '5-10 min': '5-10 λεπτά',
  '10-20 min': '10-20 λεπτά',
  '20+ min': '20+ λεπτά',
  'Engaging': 'Ελκυστικό',
  'Energetic': 'Ενεργητικό',
  'Calm': 'Ήρεμο',
  'Funny': 'Αστείο',

  'Inspired': 'Εμπνευσμένο',
  'Standard': 'Τυπικό',
  'Imaginative': 'Φαντασιοπληκτικό',
  'Innovative': 'Καινοτόμο',

  'Short Film': 'Ταινία Μικρού Μήκους',
  'Film Script': 'Σενάριο Ταινίας',
  'Stage Play': 'Θεατρικό Έργο',
  'Advertisement': 'Διαφήμιση',
  'Tiktok Video': 'Βίντεο Tiktok',
  'Movie': 'Ταινία',
  'Scene Breakdown': 'Ανάλυση Σκηνής',
  'Dialogue Only': 'Μόνο Διάλογος',

  'Action': 'Δράση',
  'Fairy Tale': 'Παραμύθι',

  'Ad loading please wait..': 'Η διαφήμιση φορτώνει, παρακαλώ περιμένετε..',
  'Words:': 'Λέξεις:',
  'Reading:': 'Ανάγνωση:',
};
