import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> en = {
  AppKeys.lblChooseLanguage: "Choose Language",
  "All": "All",
  "AI Story Generator": "AI Story Generator",
  "Story Generator": "Story Generator",
  "Essay Writer": "Essay Writer",
  "Essay length": "Essay length",
  "Script Generator": "Script Generator",
  "Create original stories in seconds": "Create original stories in seconds",
  "Academic writing made simple": "Academic writing made simple",
  "Generate powerful scripts for any medium":
      "Generate powerful scripts for any medium",
  "Start Writing": "Start Writing",
  "Create Now": "Create Now",
  "Start Generating": "Start Generating",
  "Your Stories": "Your Stories",
  "No stories yet": "No stories yet",
  "Start creating your first story!": "Start creating your first story!",
  "Your Story Space Awaits": "Your Story Space Awaits",
  "Start your first story and see it appear here":
      "Start your first story and see it appear here",
  "Language": "Language",
  "Rate us": "Rate us",
  "Share us": "Share us",
  "Privacy Policy": "Privacy Policy",
  "Settings": "Settings",
  "Select Language": "Select Language",
  "Dashboard": "Dashboard",
  "BENEFITS": "BENEFITS",
  "Subscribe": "Subscribe",
  "Weekly": "Weekly",
  "Monthly": "Monthly",
  "Yearly": "Yearly",
  "week": "week",
  "months": "months",
  "year": "year",
  "Terms & Condition": "Terms & Condition",
  "No Commitment. Cancel anytime": "No Commitment. Cancel anytime",
  "No Payment Now": "No Payment Now",
  "3 days free": "3 days free",
  "Start your free trial": "Start your free trial",
  "More detailed answers": "More detailed answers",
  "Instant responds": "Instant responds",
  "Text recognition": "Text recognition",
  "Powered by AI": "Powered by AI",
  "Storytelleing": "Storytelling",
  ' Power': " Power",
  "Unlock your \nFill ": "Unlock your \nFill ",
  "Your History": "Your History",
  "Terms and Conditions": "Terms and Conditions",
  "Short": "Short",
  "Medium": "Medium",
  "Long": "Long",
  "Length": "Length",
  "Describe your topic...": "Describe your topic...",
  "Set Creativity": "Set Creativity",
  "Standard": "Standard",
  "Creative": "Creative",
  "Complex": "Complex",
  "Select Genre": "Select Genre",
  "Fantasy": "Fantasy",
  "Mystery": "Mystery",
  "Thriller": "Thriller",
  "Script Tone": "Script Tone",
  "Script Type": "Script Type",
  "Comedy": "Comedy",
  "Drama": "Drama",
  "Horror": "Horror",
  "Action": "Action",
  "Romance": "Romance",
  "Go Premium": "Go Premium",
  "Unlock Everything": "Unlock Everything",
  "Unlimited Story Generation": "Unlimited Story Generation",
  "Write Longer & Detailed Essays": "Write Longer & Detailed Essays",
  "Advanced Script Writer": "Advanced Script Writer",
  "Unlock All Styles & Tones": "Unlock All Styles & Tones",
  "No Word/Length Limit": "No Word/Length Limit",
  "Remove All Ads": "Remove All Ads",
  "Restore": "Restore",
  "YouTube Video": "YouTube Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivational",
  "Advertisement": "Advertisement",
  "Fairy Tale": "Fairy Tale",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Select Style",
  "Imaginative": "Imaginative",
  "Innovative": "Innovative",
  "AI Story Writer": "AI Story Writer",
  "Generate": "Generate",
  "Please wait...": "Please wait...",
  "Result": "Result",
  "Regenerate": "Regenerate",
  "Download": "Download",
  "Text copied to clipboard!": "Text copied to clipboard!",
  "Please enter a topic": "Please enter a topic",
  "Story Magic": "Story Magic",
  "Let AI bring your thoughts to a full story":
      "Let AI bring your thoughts to a full story",
  "Smart Scripts": "Smart Scripts",
  "From concept to script—fast, easy, and creative":
      "From concept to script—fast, easy, and creative",
  "Perfect Essays": "Perfect Essays",
  "You have reached your free limit": "You have reached your free limit",
  "Donwload": "Download",
  "Press again to exit app": "Press again to exit app",
  "Saved to files": "TXT file saved successfully!",
  "Error: Please try again": "Error: Please try again",
  "Subscription expired": "Subscription expired",
  "Purchase cancelled": "Purchase cancelled",
  "Purchase failed": "Purchase failed",
  "Restore failed": "Restore failed",
  "Purchase Successful!": "Purchase Successful!",
  "Short (200-500 words)": "Short (200-500 words)",
  "Medium (500-1000 words)": "Medium (500-1000 words)",
  "Large (1000+ words)": "Large (1000+ words)",
  "Academic Level": "Academic Level",
  "Type of Paper": "Type of Paper",
  "High School": "High School",
  "College": "College",
  "Short Film": "Short Film",
  "University": "University",
  "Masters": "Masters",
  "Custom": "Custom",
  "Tiktok Video": "Tiktok Video",
  "Movie": "Movie",
  "Expository": "Expository",
  "Argumentative": "Argumentative",
  "Narrative": "Narrative",
  "Descriptive": "Descriptive",
  "We're sorry to hear that 😔": "We're sorry to hear that 😔",
  "We'll try to improve 🙁": "We'll try to improve 🙁",
  "Thanks for your feedback 🙂": "Thanks for your feedback 🙂",
  "Great! We're glad you like it 😊": "Great! We're glad you like it 😊",
  "Awesome! Thank you so much! 🎉": "Awesome! Thank you so much! 🎉",
  "Maybe Later": "Maybe Later",
  "Tap a star to rate your experience": "Tap a star to rate your experience",
  "Enjoying AI Math Solver?": "Enjoying AI Math Solver?",
  "Thank you for rating us": "Thank you for rating us",
  "Submit Rating": "Submit Rating",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Enjoying AI Story Generator?",
  AppKeys.arabic: "Arabic",
  AppKeys.chinese: "Chinese",
  AppKeys.english: "English",
  AppKeys.french: "French",
  AppKeys.german: "German",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesian",
  AppKeys.japanese: "Japanese",
  AppKeys.korean: "Korean",
  AppKeys.portuguese: "Portuguese",
  AppKeys.russian: "Russian",
  AppKeys.spanish: "Spanish",
  AppKeys.turkish: "Turkish",
  'Download As': 'Download As',
  'Choose format to download': 'Choose format to download',
  'Text File': 'Text File',
  'PDF File': 'PDF File',
  'Copy': 'Copy',
  'Share': 'Share',
  'Text copied!': 'Text copied!',
  'PDF saved successfully!': 'PDF saved successfully!',
  'Error creating PDF: Please try again':
      'Error creating PDF: Please try again',
  'Character Story': 'Character Story',
  'Character Details': 'Character Details',
  'Character Name': 'Character Name',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Age (e.g., 25, Young Adult, Ancient)',
  'Personality (e.g., brave, shy, cunning)':
      'Personality (e.g., brave, shy, cunning)',
  'Role (e.g., Hero, Villain, Mentor)': 'Role (e.g., Hero, Villain, Mentor)',
  'Additional Details (optional)': 'Additional Details (optional)',
  'Output Style': 'Output Style',
  'Generate Character': 'Generate Character',
  'Please enter character name': 'Please enter character name',
  'Please enter character role': 'Please enter character role',
  'Detailed': 'Detailed',
  'Brief': 'Brief',
  'Elaborate': 'Elaborate',
  'Create detailed character backstories':
      'Create detailed character backstories',
  'Create Character': 'Create Character',
  'Transform and improve your existing stories':
      'Transform and improve your existing stories',
  'Rewrite Now': 'Rewrite Now',
  'Generate catchy titles for your stories':
      'Generate catchy titles for your stories',
  'Generate Titles': 'Generate Titles',
  'Rewrite Story': 'Rewrite Story',
  'Paste Your Story': 'Paste Your Story',
  'Paste your story here to rewrite...': 'Paste your story here to rewrite...',
  'Select Tone': 'Select Tone',
  'Rewrite Style': 'Rewrite Style',
  'Output Length': 'Output Length',
  'Please paste your story': 'Please paste your story',
  'Story is too short. Please provide more content.':
      'Story is too short. Please provide more content.',
  'Same': 'Same',
  'More Dramatic': 'More Dramatic',
  'More Humorous': 'More Humorous',
  'More Emotional': 'More Emotional',
  'More Suspenseful': 'More Suspenseful',
  'Lighter': 'Lighter',
  'Improved': 'Improved',
  'Simplified': 'Simplified',
  'More Descriptive': 'More Descriptive',
  'More Dialogue': 'More Dialogue',
  'More Action': 'More Action',
  'Literary': 'Literary',
  'Shorter': 'Shorter',
  'Longer': 'Longer',
  'Much Longer': 'Much Longer',
  'Title Generator': 'Title Generator',
  'Story/Book Topic': 'Story/Book Topic',
  'Keywords (Optional)': 'Keywords (Optional)',
  'Describe your story topic or theme...':
      'Describe your story topic or theme...',
  'e.g., magic, dragon, adventure': 'e.g., magic, dragon, adventure',
  'Title For': 'Title For',
  'Title Style': 'Title Style',
  "Adventure": "Adventure",
  'Number of Titles': 'Number of Titles',
  'Book': 'Book',
  'Short Story': 'Short Story',
  'Novel': 'Novel',
  'Chapter': 'Chapter',
  'Series': 'Series',
  'Simple': 'Simple',
  'Mysterious': 'Mysterious',
  'Dramatic': 'Dramatic',
  'Catchy': 'Catchy',
  'Poetic': 'Poetic',
  'Kids': 'Kids',
  'Blog Writer': 'Blog Writer',
  'Blog Topic': 'Blog Topic',
  'Target Keywords': 'Target Keywords',
  'Target Audience (Optional)': 'Target Audience (Optional)',
  'Enter your blog topic or title...': 'Enter your blog topic or title...',
  'e.g., AI writing, content marketing, SEO tips':
      'e.g., AI writing, content marketing, SEO tips',
  'e.g., small business owners, bloggers':
      'e.g., small business owners, bloggers',
  'Article Type': 'Article Type',
  'Writing Tone': 'Writing Tone',
  'Article Length': 'Article Length',
  'SEO Options': 'SEO Options',
  'Include Meta Description': 'Include Meta Description',
  'Include Keyword Suggestions': 'Include Keyword Suggestions',
  'Include FAQs Section': 'Include FAQs Section',
  'Please enter a blog topic': 'Please enter a blog topic',
  'Generate Blog': 'Generate Blog',
  'SEO optimized articles with keywords':
      'SEO optimized articles with keywords',
  'Write Blog': 'Write Blog',
  'SEO Article': 'SEO Article',
  'How-To Guide': 'How-To Guide',
  'Listicle': 'Listicle',
  'Product Review': 'Product Review',
  'Opinion Piece': 'Opinion Piece',
  'News Article': 'News Article',
  'Professional': 'Professional',
  'Casual': 'Casual',
  'Informative': 'Informative',
  'Persuasive': 'Persuasive',
  'Friendly': 'Friendly',
  'Authoritative': 'Authoritative',
  'Short (500-800)': 'Short (500-800)',
  'Medium (800-1500)': 'Medium (800-1500)',
  'Long (1500-2500)': 'Long (1500-2500)',
  'Detailed (2500+)': 'Detailed (2500+)',
  'YouTube Script': 'YouTube Script',
  'Video Topic': 'Video Topic',
  'Key Points (Optional)': 'Key Points (Optional)',
  'What is your video about?': 'What is your video about?',
  'List key points to cover (optional)...':
      'List key points to cover (optional)...',
  'Video Duration': 'Video Duration',
  'Script Options': 'Script Options',
  'Include Hook/Intro': 'Include Hook/Intro',
  'Include Call-to-Action': 'Include Call-to-Action',
  'Include Timestamps': 'Include Timestamps',
  'Please enter a video topic': 'Please enter a video topic',
  'Generate Script': 'Generate Script',
  'Create scripts for videos & reels': 'Create scripts for videos & reels',
  'Create Script': 'Create Script',
  'Storytime': 'Storytime',
  'Documentary': 'Documentary',
  'Short Reel': 'Short Reel',
  'Educational': 'Educational',
  'Review': 'Review',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Engaging',
  'Energetic': 'Energetic',
  'Calm': 'Calm',
  'Funny': 'Funny',
  'Inspired': 'Inspired',
  'Film Script': 'Film Script',
  'Stage Play': 'Stage Play',
  'Scene Breakdown': 'Scene Breakdown',
  'Dialogue Only': 'Dialogue Only',
  'Ad loading please wait..': 'Ad loading please wait..',
  'Words:': 'Words:',
  'Reading:': 'Reading:',
};
