import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> es = {
  AppKeys.lblChooseLanguage: "Elegir idioma",
  "All": "Todos",
  "AI Story Generator": "Generador de historias de IA",
  "Story Generator": "Generador de historias",
  "Essay Writer": "Escritor de ensayos",
  "Essay length": "Longitud del ensayo",
  "Script Generator": "Generador de guiones",
  "Create original stories in seconds": "Crea historias originales en segundos",
  "Academic writing made simple": "Escritura académica simplificada",
  "Generate powerful scripts for any medium":
      "Genera guiones poderosos para cualquier medio",
  "Start Writing": "Comenzar a escribir",
  "Create Now": "Crear ahora",
  "Start Generating": "Comenzar a generar",
  "Your Stories": "Tus historias",
  "No stories yet": "Aún no hay historias",
  "Start creating your first story!": "¡Comienza a crear tu primera historia!",
  "Your Story Space Awaits": "Tu espacio de historias te espera",
  "Start your first story and see it appear here":
      "Comienza tu primera historia y mírala aparecer aquí",
  "Language": "Idioma",
  "Rate us": "Califícanos",
  "Share us": "Compártenos",
  "Privacy Policy": "Política de privacidad",
  "Settings": "Configuraciones",
  "Select Language": "Seleccionar idioma",
  "Dashboard": "Tablero",
  "BENEFITS": "BENEFICIOS",
  "Subscribe": "Suscribirse",
  "Weekly": "Semanal",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "week": "semana",
  "months": "meses",
  "year": "año",
  "Terms & Condition": "Términos y condiciones",
  "No Commitment. Cancel anytime":
      "Sin compromiso. Cancela en cualquier momento",
  "No Payment Now": "Sin pago ahora",
  "3 days free": "3 días gratis",
  "Start your free trial": "Comienza tu prueba gratuita",
  "More detailed answers": "Respuestas más detalladas",
  "Instant responds": "Respuestas instantáneas",
  "Text recognition": "Reconocimiento de texto",
  "Powered by AI": "Impulsado por IA",
  "Storytelleing": "Narración de historias",
  ' Power': "Poder",
  "Unlock your \nFill ": "Desbloquea tu \nFill",
  "Your History": "Tu historial",
  "Terms and Conditions": "Términos y condiciones",
  "Short": "Breve",
  "Medium": "Medio",
  "Long": "Largo",

  "We're sorry to hear that 😔": "Lamentamos escuchar eso 😔",
  "We'll try to improve 🙁": "Intentaremos mejorar 🙁",
  "Thanks for your feedback 🙂": "Gracias por tus comentarios 🙂",
  "Great! We're glad you like it 😊": "¡Genial! Nos alegra que te guste 😊",
  "Awesome! Thank you so much! 🎉": "¡Increíble! ¡Muchas gracias! 🎉",
  "Maybe Later": "Quizás más tarde",
  "Tap a star to rate your experience":
      "Toca una estrella para calificar tu experiencia",
  "Enjoying AI Math Solver?": "¿Disfrutando AI Math Solver?",
  "Thank you for rating us": "Gracias por calificarnos",
  "Submit Rating": "Enviar calificación",
  "Hindi": "Hindi",
  "Length": "Longitud",
  "Describe your topic...": "Describe tu tema...",
  "Set Creativity": "Establecer creatividad",
  "Standard": "Estándar",
  "Creative": "Creativo",
  "Complex": "Complejo",
  "Select Genre": "Seleccionar género",
  "Fantasy": "Fantasía",
  "Mystery": "Misterio",
  "Thriller": "Suspenso",
  "Script Tone": "Tono del guion",
  "Script Type": "Tipo de guion",
  "Comedy": "Comedia",
  "Drama": "Drama",
  "Enjoying AI Story Generator?":
      "¿Disfrutando del Generador de Historias de IA?",
  "Horror": "Terror",
  "Action": "Acción",
  "Romance": "Romance",
  "Motivational": "Motivacional",
  "Advertisement": "Publicidad",
  "Fairy Tale": "Cuento de hadas",
  "Sci-Fi": "Ciencia ficción",
  "Select Style": "Seleccionar estilo",
  "Imaginative": "Imaginativo",
  "Innovative": "Innovador",
  "Generate": "Generar",
  "Please wait...": "Por favor espera...",
  "Result": "Resultado",
  "Regenerate": "Regenerar",
  "Download": "Descargar",
  "Text copied to clipboard!": "¡Texto copiado al portapapeles!",
  "Please enter a topic": "Por favor ingresa un tema",
  "Story Magic": "Magia de historias",
  "Let AI bring your thoughts to a full story":
      "Deja que la IA convierta tus pensamientos en una historia completa",
  "Smart Scripts": "Guiones inteligentes",
  "From concept to script—fast, easy, and creative":
      "Del concepto al guion—rápido, fácil y creativo",
  "Perfect Essays": "Ensayos perfectos",
  "You have reached your free limit": "Has alcanzado tu límite gratuito",
  "Donwload": "Descargas",
  "Press again to exit app": "Presiona de nuevo para salir de la aplicación",
  "Saved to files": "¡Archivo TXT guardado exitosamente!",
  "Error: Please try again": "Error: Por favor intenta de nuevo",
  "Subscription expired": "Suscripción expirada",
  "Purchase cancelled": "Compra cancelada",
  "Purchase failed": "Compra fallida",
  "Restore failed": "Restauración fallida",
  "Purchase Successful!": "¡Compra exitosa!",
  "Short (200-500 words)": "Corto (200-500 palabras)",
  "Medium (500-1000 words)": "Medio (500-1000 palabras)",
  "Large (1000+ words)": "Grande (1000+ palabras)",
  "Academic Level": "Nivel académico",
  "Type of Paper": "Tipo de documento",
  "High School": "Escuela secundaria",
  "College": "Universidad",
  "Short Film": "Cortometraje",
  "University": "Universidad",
  "Masters": "Maestría",
  "Custom": "Personalizado",
  "YouTube Video": "Video de YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Video de Tiktok",
  "Go Premium": "Obtener Premium",
  "Unlock Everything": "Desbloquea Todo",
  "Unlimited Story Generation": "Generación de Historias Ilimitada",
  "Write Longer & Detailed Essays": "Escribe Ensayos Más Largos y Detallados",
  "Advanced Script Writer": "Escritor de Scripts Avanzado",
  "Unlock All Styles & Tones": "Desbloquea Todos los Estilos y Tonos",
  "No Word/Length Limit": "Sin Límite de Palabras/Longitud",
  "Remove All Ads": "Eliminar Todos los Anuncios",
  "3 days free": "3 días gratis",
  "Restore": "Restaurar",

  "AI Story Writer": "Escritor de Historias con IA",
  "YouTube Video": "Video de YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Movie": "Película",
  "Expository": "Expositivo",
  "Argumentative": "Argumentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descriptivo",

  AppKeys.arabic: "Árabe",
  AppKeys.chinese: "Chino",
  AppKeys.english: "Inglés",
  AppKeys.french: "Francés",
  AppKeys.german: "Alemán",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesio",
  AppKeys.japanese: "Japonés",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Portugués",
  AppKeys.russian: "Ruso",
  AppKeys.spanish: "Español",
  "AI Story Writer": "Escritor de historias de IA",
  AppKeys.turkish: "Turco",
};
