import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> es = {
  AppKeys.lblChooseLanguage: "Elegir idioma",
  "All": "Todos",
  "AI Story Generator": "Generador de historias IA",
  "Story Generator": "Generador de historias",
  "Essay Writer": "Escritor de ensayos",
  "Essay length": "Longitud del ensayo",
  "Script Generator": "Generador de guiones",
  "Create original stories in seconds": "Crea historias originales en segundos",
  "Academic writing made simple": "Escritura académica simplificada",
  "Generate powerful scripts for any medium":
      "Genera guiones poderosos para cualquier medio",
  "Start Writing": "Empezar a escribir",
  "Create Now": "Crear ahora",
  "Start Generating": "Empezar a generar",
  "Your Stories": "Tus historias",
  "No stories yet": "Aún no hay historias",
  "Start creating your first story!": "¡Empieza a crear tu primera historia!",
  "Your Story Space Awaits": "Tu espacio de historias te espera",
  "Start your first story and see it appear here":
      "Comienza tu primera historia y mírala aparecer aquí",
  "Language": "Idioma",
  "Rate us": "Califícanos",
  "Share us": "Compártenos",
  "Privacy Policy": "Política de privacidad",
  "Settings": "Configuración",
  "Select Language": "Seleccionar idioma",
  "Dashboard": "Panel",
  "BENEFITS": "BENEFICIOS",
  "Subscribe": "Suscribirse",
  "Weekly": "Semanal",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "week": "semana",
  "months": "meses",
  "year": "año",
  "Terms & Condition": "Términos y condiciones",
  "No Commitment. Cancel anytime":
      "Sin compromiso. Cancela en cualquier momento",
  "No Payment Now": "Sin pago ahora",
  "3 days free": "3 días gratis",
  "Start your free trial": "Comienza tu prueba gratuita",
  "More detailed answers": "Respuestas más detalladas",
  "Instant responds": "Respuestas instantáneas",
  "Text recognition": "Reconocimiento de texto",
  "Powered by AI": "Impulsado por IA",
  "Storytelleing": "Narración",
  ' Power': " Poder",
  "Unlock your \nFill ": "Desbloquea tu \nFill ",
  "Your History": "Tu historial",
  "Terms and Conditions": "Términos y condiciones",
  "Short": "Corto",
  "Medium": "Medio",
  "Long": "Largo",
  "Length": "Longitud",
  "Describe your topic...": "Describe tu tema...",
  "Set Creativity": "Ajustar creatividad",
  "Standard": "Estándar",
  "Creative": "Creativo",
  "Complex": "Complejo",
  "Select Genre": "Seleccionar género",
  "Fantasy": "Fantasía",
  "Mystery": "Misterio",
  "Thriller": "Suspenso",
  "Script Tone": "Tono del guión",
  "Script Type": "Tipo de guión",
  "Comedy": "Comedia",
  "Drama": "Drama",
  "Horror": "Terror",
  "Action": "Acción",
  "Romance": "Romance",
  "Go Premium": "Hazte Premium",
  "Unlock Everything": "Desbloquea todo",
  "Unlimited Story Generation": "Generación ilimitada de historias",
  "Write Longer & Detailed Essays": "Escribe ensayos más largos y detallados",
  "Advanced Script Writer": "Escritor de guiones avanzado",
  "Unlock All Styles & Tones": "Desbloquea todos los estilos y tonos",
  "No Word/Length Limit": "Sin límite de palabras/longitud",
  "Remove All Ads": "Eliminar todos los anuncios",
  "Restore": "Restaurar",
  "YouTube Video": "Video de YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivacional",
  "Advertisement": "Anuncio",
  "Fairy Tale": "Cuento de hadas",
  "Sci-Fi": "Ciencia ficción",
  "Select Style": "Seleccionar estilo",
  "Imaginative": "Imaginativo",
  "Innovative": "Innovador",
  "AI Story Writer": "Escritor de historias IA",
  "Generate": "Generar",
  "Please wait...": "Por favor espera...",
  "Result": "Resultado",
  "Regenerate": "Regenerar",
  "Download": "Descargar",
  "Text copied to clipboard!": "¡Texto copiado al portapapeles!",
  "Please enter a topic": "Por favor ingresa un tema",
  "Story Magic": "Magia de historias",
  "Let AI bring your thoughts to a full story":
      "Deja que la IA convierta tus pensamientos en una historia completa",
  "Smart Scripts": "Guiones inteligentes",
  "From concept to script—fast, easy, and creative":
      "Del concepto al guión—rápido, fácil y creativo",
  "Perfect Essays": "Ensayos perfectos",
  "You have reached your free limit": "Has alcanzado tu límite gratuito",
  "Donwload": "Descargar",
  "Press again to exit app": "Presiona de nuevo para salir de la app",
  "Saved to files": "¡Archivo TXT guardado exitosamente!",
  "Error: Please try again": "Error: Por favor intenta de nuevo",
  "Subscription expired": "Suscripción expirada",
  "Purchase cancelled": "Compra cancelada",
  "Purchase failed": "Compra fallida",
  "Restore failed": "Restauración fallida",
  "Purchase Successful!": "¡Compra exitosa!",
  "Short (200-500 words)": "Corto (200-500 palabras)",
  "Medium (500-1000 words)": "Medio (500-1000 palabras)",
  "Large (1000+ words)": "Grande (1000+ palabras)",
  "Academic Level": "Nivel académico",
  "Type of Paper": "Tipo de ensayo",
  "High School": "Secundaria",
  "College": "Universidad",
  "Short Film": "Cortometraje",
  "University": "Universidad",
  "Masters": "Maestría",
  "Custom": "Personalizado",
  "Tiktok Video": "Video de TikTok",
  "Movie": "Película",
  "Expository": "Expositivo",
  "Argumentative": "Argumentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descriptivo",
  "We're sorry to hear that 😔": "Lamentamos escuchar eso 😔",
  "We'll try to improve 🙁": "Intentaremos mejorar 🙁",
  "Thanks for your feedback 🙂": "Gracias por tu opinión 🙂",
  "Great! We're glad you like it 😊": "¡Genial! Nos alegra que te guste 😊",
  "Awesome! Thank you so much! 🎉": "¡Increíble! ¡Muchas gracias! 🎉",
  "Maybe Later": "Quizás después",
  "Tap a star to rate your experience":
      "Toca una estrella para calificar tu experiencia",
  "Enjoying AI Math Solver?": "¿Disfrutas del solucionador de matemáticas IA?",
  "Thank you for rating us": "Gracias por calificarnos",
  "Submit Rating": "Enviar calificación",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "¿Disfrutas del generador de historias IA?",
  AppKeys.arabic: "Árabe",
  AppKeys.chinese: "Chino",
  AppKeys.english: "Inglés",
  AppKeys.french: "Francés",
  AppKeys.german: "Alemán",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesio",
  AppKeys.japanese: "Japonés",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Portugués",
  AppKeys.russian: "Ruso",
  AppKeys.spanish: "Español",
  AppKeys.turkish: "Turco",
  'Download As': 'Descargar como',
  'Choose format to download': 'Elige el formato para descargar',
  'Text File': 'Archivo de texto',
  'PDF File': 'Archivo PDF',
  'Copy': 'Copiar',
  'Share': 'Compartir',
  'Text copied!': '¡Texto copiado!',
  'PDF saved successfully!': '¡PDF guardado exitosamente!',
  'Error creating PDF: Please try again':
      'Error al crear PDF: Por favor intenta de nuevo',
  'Character Story': 'Historia del personaje',
  'Character Details': 'Detalles del personaje',
  'Character Name': 'Nombre del personaje',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Edad (ej., 25, Joven adulto, Anciano)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalidad (ej., valiente, tímido, astuto)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (ej., Héroe, Villano, Mentor)',
  'Additional Details (optional)': 'Detalles adicionales (opcional)',
  'Output Style': 'Estilo de salida',
  'Generate Character': 'Generar personaje',
  'Please enter character name': 'Por favor ingresa el nombre del personaje',
  'Please enter character role': 'Por favor ingresa el rol del personaje',
  'Detailed': 'Detallado',
  'Brief': 'Breve',
  'Elaborate': 'Elaborado',
  'Create detailed character backstories':
      'Crea historias detalladas de personajes',
  'Create Character': 'Crear personaje',
  'Transform and improve your existing stories':
      'Transforma y mejora tus historias existentes',
  'Rewrite Now': 'Reescribir ahora',
  'Generate catchy titles for your stories':
      'Genera títulos atractivos para tus historias',
  'Generate Titles': 'Generar títulos',
  'Rewrite Story': 'Reescribir historia',
  'Paste Your Story': 'Pega tu historia',
  'Paste your story here to rewrite...':
      'Pega tu historia aquí para reescribir...',
  'Select Tone': 'Seleccionar tono',
  'Rewrite Style': 'Estilo de reescritura',
  'Output Length': 'Longitud de salida',
  'Please paste your story': 'Por favor pega tu historia',
  'Story is too short. Please provide more content.':
      'La historia es muy corta. Por favor proporciona más contenido.',
  'Same': 'Igual',
  'More Dramatic': 'Más dramático',
  'More Humorous': 'Más humorístico',
  'More Emotional': 'Más emocional',
  'More Suspenseful': 'Más suspense',
  'Lighter': 'Más ligero',
  'Improved': 'Mejorado',
  'Simplified': 'Simplificado',
  'More Descriptive': 'Más descriptivo',
  'More Dialogue': 'Más diálogo',
  'More Action': 'Más acción',
  'Literary': 'Literario',
  'Shorter': 'Más corto',
  'Longer': 'Más largo',
  'Much Longer': 'Mucho más largo',
  'Title Generator': 'Generador de títulos',
  'Story/Book Topic': 'Tema de historia/libro',
  'Keywords (Optional)': 'Palabras clave (opcional)',
  'Describe your story topic or theme...': 'Describe el tema de tu historia...',
  'e.g., magic, dragon, adventure': 'ej., magia, dragón, aventura',
  'Title For': 'Título para',
  'Title Style': 'Estilo de título',
  "Adventure": "Aventura",
  'Number of Titles': 'Número de títulos',
  'Book': 'Libro',
  'Short Story': 'Cuento corto',
  'Novel': 'Novela',
  'Chapter': 'Capítulo',
  'Series': 'Serie',
  'Simple': 'Simple',
  'Mysterious': 'Misterioso',
  'Dramatic': 'Dramático',
  'Catchy': 'Atractivo',
  'Poetic': 'Poético',
  'Kids': 'Niños',
  'Blog Writer': 'Escritor de blog',
  'Blog Topic': 'Tema del blog',
  'Target Keywords': 'Palabras clave objetivo',
  'Target Audience (Optional)': 'Audiencia objetivo (opcional)',
  'Enter your blog topic or title...': 'Ingresa el tema o título de tu blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'ej., escritura IA, marketing de contenido, consejos SEO',
  'e.g., small business owners, bloggers':
      'ej., dueños de pequeños negocios, blogueros',
  'Article Type': 'Tipo de artículo',
  'Writing Tone': 'Tono de escritura',
  'Article Length': 'Longitud del artículo',
  'SEO Options': 'Opciones SEO',
  'Include Meta Description': 'Incluir meta descripción',
  'Include Keyword Suggestions': 'Incluir sugerencias de palabras clave',
  'Include FAQs Section': 'Incluir sección de preguntas frecuentes',
  'Please enter a blog topic': 'Por favor ingresa un tema de blog',
  'Generate Blog': 'Generar blog',
  'SEO optimized articles with keywords':
      'Artículos optimizados para SEO con palabras clave',
  'Write Blog': 'Escribir blog',
  'SEO Article': 'Artículo SEO',
  'How-To Guide': 'Guía paso a paso',
  'Listicle': 'Listicle',
  'Product Review': 'Reseña de producto',
  'Opinion Piece': 'Artículo de opinión',
  'News Article': 'Artículo de noticias',
  'Professional': 'Profesional',
  'Casual': 'Casual',
  'Informative': 'Informativo',
  'Persuasive': 'Persuasivo',
  'Friendly': 'Amigable',
  'Authoritative': 'Autoritativo',
  'Short (500-800)': 'Corto (500-800)',
  'Medium (800-1500)': 'Medio (800-1500)',
  'Long (1500-2500)': 'Largo (1500-2500)',
  'Detailed (2500+)': 'Detallado (2500+)',
  'YouTube Script': 'Guión de YouTube',
  'Video Topic': 'Tema del video',
  'Key Points (Optional)': 'Puntos clave (opcional)',
  'What is your video about?': '¿De qué trata tu video?',
  'List key points to cover (optional)...':
      'Lista los puntos clave a cubrir (opcional)...',
  'Video Duration': 'Duración del video',
  'Script Options': 'Opciones de guión',
  'Include Hook/Intro': 'Incluir gancho/introducción',
  'Include Call-to-Action': 'Incluir llamada a la acción',
  'Include Timestamps': 'Incluir marcas de tiempo',
  'Please enter a video topic': 'Por favor ingresa un tema de video',
  'Generate Script': 'Generar guión',
  'Create scripts for videos & reels': 'Crea guiones para videos y reels',
  'Create Script': 'Crear guión',
  'Storytime': 'Hora del cuento',
  'Documentary': 'Documental',
  'Short Reel': 'Reel corto',
  'Educational': 'Educativo',
  'Review': 'Reseña',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Atractivo',
  'Energetic': 'Energético',
  'Calm': 'Tranquilo',
  'Funny': 'Divertido',
  'Inspired': 'Inspirado',
  'Film Script': 'Guión de película',
  'Stage Play': 'Obra de teatro',
  'Scene Breakdown': 'Desglose de escena',
  'Dialogue Only': 'Solo diálogo',
  'Ad loading please wait..': 'Cargando anuncio, por favor espera..',
  'Words:': 'Palabras:',
  'Reading:': 'Lectura:',
};
