import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> et = {
  AppKeys.lblChooseLanguage: "Vali keel",
  "All": "Kõik",
  "AI Story Generator": "AI loogeneraator",
  "Story Generator": "Loogeneraator",
  "Essay Writer": "Esseekirjutaja",
  "Essay length": "Essee pikkus",
  "Script Generator": "Skriptigeneraator",
  "Create original stories in seconds": "Loo originaalseid lugusid sekunditega",
  "Academic writing made simple": "Akadeemiline kirjutamine lihtsaks tehtud",
  "Generate powerful scripts for any medium":
      "Loo võimsaid skripte igale meediumile",
  "Start Writing": "Alusta kirjutamist",
  "Create Now": "Loo nüüd",
  "Start Generating": "Alusta genereerimist",
  "Your Stories": "Sinu lood",
  "No stories yet": "Lugusid veel pole",
  "Start creating your first story!": "Alusta oma esimese loo loomist!",
  "Your Story Space Awaits": "Sinu looderuum ootab",
  "Start your first story and see it appear here":
      "Alusta oma esimest lugu ja vaata, kuidas see siin ilmub",
  "Language": "Keel",
  "Rate us": "Hinda meid",
  "Share us": "Jaga meid",
  "Privacy Policy": "Privaatsuspoliitika",
  "Settings": "Seaded",
  "Select Language": "Vali keel",
  "Dashboard": "Töölaud",
  "BENEFITS": "EELISED",
  "Subscribe": "Telli",
  "Weekly": "Iganädalane",
  "Monthly": "Igakuine",
  "Yearly": "Aastane",
  "week": "nädal",
  "months": "kuud",
  "year": "aasta",
  "Terms & Condition": "Tingimused",
  "No Commitment. Cancel anytime": "Kohustuseta. Tühista igal ajal",
  "No Payment Now": "Praegu makset pole",
  "3 days free": "3 päeva tasuta",
  "Start your free trial": "Alusta tasuta prooviperioodi",
  "More detailed answers": "Detailsemad vastused",
  "Instant responds": "Kohesed vastused",
  "Text recognition": "Tekstituvastus",
  "Powered by AI": "AI-toega",
  "Storytelleing": "Jutustamine",
  ' Power': " Jõud",
  "Unlock your \nFill ": "Ava oma \nFill ",
  "Your History": "Sinu ajalugu",
  "Terms and Conditions": "Tingimused",
  "Short": "Lühike",
  "Medium": "Keskmine",
  "Long": "Pikk",
  "Length": "Pikkus",
  "Describe your topic...": "Kirjelda oma teemat...",
  "Set Creativity": "Seadista loovus",
  "Standard": "Standardne",
  "Creative": "Loov",
  "Complex": "Keeruline",
  "Select Genre": "Vali žanr",
  "Fantasy": "Fantaasia",
  "Mystery": "Müsteerium",
  "Thriller": "Põnevuslugu",
  "Script Tone": "Skripti toon",
  "Script Type": "Skripti tüüp",
  "Comedy": "Komöödia",
  "Drama": "Draama",
  "Horror": "Õudus",
  "Action": "Action",
  "Romance": "Romantika",
  "Go Premium": "Mine Premiumile",
  "Unlock Everything": "Ava kõik",
  "Unlimited Story Generation": "Piiramatu lugude genereerimine",
  "Write Longer & Detailed Essays": "Kirjuta pikemaid ja detailsemaid esseesid",
  "Advanced Script Writer": "Täiustatud skriptikirjutaja",
  "Unlock All Styles & Tones": "Ava kõik stiilid ja toonid",
  "No Word/Length Limit": "Sõnade/pikkuse piirangut pole",
  "Remove All Ads": "Eemalda kõik reklaamid",
  "Restore": "Taasta",
  "YouTube Video": "YouTube video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motiveeriv",
  "Advertisement": "Reklaam",
  "Fairy Tale": "Muinasjutt",
  "Sci-Fi": "Ulme",
  "Select Style": "Vali stiil",
  "Imaginative": "Kujutlusvõimeline",
  "Innovative": "Uuenduslik",
  "AI Story Writer": "AI lookirjutaja",
  "Generate": "Genereeri",
  "Please wait...": "Palun oota...",
  "Result": "Tulemus",
  "Regenerate": "Genereeri uuesti",
  "Download": "Laadi alla",
  "Text copied to clipboard!": "Tekst kopeeritud lõikelauale!",
  "Please enter a topic": "Palun sisesta teema",
  "Story Magic": "Loomaagia",
  "Let AI bring your thoughts to a full story":
      "Lase AI-l muuta oma mõtted täislooks",
  "Smart Scripts": "Nutikad skriptid",
  "From concept to script—fast, easy, and creative":
      "Kontseptsioonist skriptini—kiire, lihtne ja loov",
  "Perfect Essays": "Täiuslikud esseed",
  "You have reached your free limit": "Oled saavutanud oma tasuta piiri",
  "Donwload": "Laadi alla",
  "Press again to exit app": "Vajuta uuesti rakendusest väljumiseks",
  "Saved to files": "TXT-fail edukalt salvestatud!",
  "Error: Please try again": "Viga: Palun proovi uuesti",
  "Subscription expired": "Tellimus aegunud",
  "Purchase cancelled": "Ost tühistatud",
  "Purchase failed": "Ost ebaõnnestus",
  "Restore failed": "Taastamine ebaõnnestus",
  "Purchase Successful!": "Ost õnnestus!",
  "Short (200-500 words)": "Lühike (200-500 sõna)",
  "Medium (500-1000 words)": "Keskmine (500-1000 sõna)",
  "Large (1000+ words)": "Suur (1000+ sõna)",
  "Academic Level": "Akadeemiline tase",
  "Type of Paper": "Töö tüüp",
  "High School": "Keskkool",
  "College": "Kolledž",
  "Short Film": "Lühifilm",
  "University": "Ülikool",
  "Masters": "Magistriõpe",
  "Custom": "Kohandatud",
  "Tiktok Video": "TikToki video",
  "Movie": "Film",
  "Expository": "Selgitav",
  "Argumentative": "Argumenteeriv",
  "Narrative": "Jutustav",
  "Descriptive": "Kirjeldav",
  "We're sorry to hear that 😔": "Meil on kahju seda kuulda 😔",
  "We'll try to improve 🙁": "Proovime paremaks muuta 🙁",
  "Thanks for your feedback 🙂": "Täname tagasiside eest 🙂",
  "Great! We're glad you like it 😊": "Suurepärane! Rõõm, et meeldib 😊",
  "Awesome! Thank you so much! 🎉": "Suurepärane! Suur tänu! 🎉",
  "Maybe Later": "Võib-olla hiljem",
  "Tap a star to rate your experience":
      "Puuduta tähte, et hinnata oma kogemust",
  "Enjoying AI Math Solver?": "Naudid AI matemaatika lahendajat?",
  "Thank you for rating us": "Täname hindamise eest",
  "Submit Rating": "Esita hinnang",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Naudid AI loogeneraatorit?",
  AppKeys.arabic: "Araabia",
  AppKeys.chinese: "Hiina",
  AppKeys.english: "Inglise",
  AppKeys.french: "Prantsuse",
  AppKeys.german: "Saksa",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indoneesia",
  AppKeys.japanese: "Jaapani",
  AppKeys.korean: "Korea",
  AppKeys.portuguese: "Portugali",
  AppKeys.russian: "Vene",
  AppKeys.spanish: "Hispaania",
  AppKeys.turkish: "Türgi",
  'Download As': 'Laadi alla kui',
  'Choose format to download': 'Vali allalaadimise vorming',
  'Text File': 'Tekstifail',
  'PDF File': 'PDF-fail',
  'Copy': 'Kopeeri',
  'Share': 'Jaga',
  'Text copied!': 'Tekst kopeeritud!',
  'PDF saved successfully!': 'PDF edukalt salvestatud!',
  'Error creating PDF: Please try again':
      'Viga PDF loomisel: Palun proovi uuesti',
  'Character Story': 'Tegelase lugu',
  'Character Details': 'Tegelase üksikasjad',
  'Character Name': 'Tegelase nimi',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Vanus (nt 25, Noor täiskasvanu, Iidne)',
  'Personality (e.g., brave, shy, cunning)':
      'Isiksus (nt julge, häbelik, kaval)',
  'Role (e.g., Hero, Villain, Mentor)': 'Roll (nt Kangelane, Kurikael, Mentor)',
  'Additional Details (optional)': 'Lisainfo (valikuline)',
  'Output Style': 'Väljundi stiil',
  'Generate Character': 'Genereeri tegelane',
  'Please enter character name': 'Palun sisesta tegelase nimi',
  'Please enter character role': 'Palun sisesta tegelase roll',
  'Detailed': 'Detailne',
  'Brief': 'Lühike',
  'Elaborate': 'Üksikasjalik',
  'Create detailed character backstories':
      'Loo detailseid tegelaste taustaluusid',
  'Create Character': 'Loo tegelane',
  'Transform and improve your existing stories':
      'Muuda ja paranda oma olemasolevaid lugusid',
  'Rewrite Now': 'Kirjuta kohe ümber',
  'Generate catchy titles for your stories':
      'Genereeri meeldejäävaid pealkirju oma lugudele',
  'Generate Titles': 'Genereeri pealkirjad',
  'Rewrite Story': 'Kirjuta lugu ümber',
  'Paste Your Story': 'Kleebi oma lugu',
  'Paste your story here to rewrite...':
      'Kleebi oma lugu siia, et ümber kirjutada...',
  'Select Tone': 'Vali toon',
  'Rewrite Style': 'Ümberjutustamise stiil',
  'Output Length': 'Väljundi pikkus',
  'Please paste your story': 'Palun kleebi oma lugu',
  'Story is too short. Please provide more content.':
      'Lugu on liiga lühike. Palun anna rohkem sisu.',
  'Same': 'Sama',
  'More Dramatic': 'Dramaatilisem',
  'More Humorous': 'Humoristlikum',
  'More Emotional': 'Emotsionaalsem',
  'More Suspenseful': 'Põnevam',
  'Lighter': 'Kergem',
  'Improved': 'Parandatud',
  'Simplified': 'Lihtsustatud',
  'More Descriptive': 'Kirjeldavam',
  'More Dialogue': 'Rohkem dialoogi',
  'More Action': 'Rohkem tegevust',
  'Literary': 'Kirjanduslik',
  'Shorter': 'Lühem',
  'Longer': 'Pikem',
  'Much Longer': 'Palju pikem',
  'Title Generator': 'Pealkirjageneraator',
  'Story/Book Topic': 'Loo/raamatu teema',
  'Keywords (Optional)': 'Märksõnad (valikuline)',
  'Describe your story topic or theme...': 'Kirjelda oma loo teemat...',
  'e.g., magic, dragon, adventure': 'nt maagia, draakon, seiklus',
  'Title For': 'Pealkiri',
  'Title Style': 'Pealkirja stiil',
  "Adventure": "Seiklus",
  'Number of Titles': 'Pealkirjade arv',
  'Book': 'Raamat',
  'Short Story': 'Lühilugu',
  'Novel': 'Romaan',
  'Chapter': 'Peatükk',
  'Series': 'Sari',
  'Simple': 'Lihtne',
  'Mysterious': 'Müstiline',
  'Dramatic': 'Dramaatiline',
  'Catchy': 'Meeldejääv',
  'Poetic': 'Poeetiline',
  'Kids': 'Lastele',
  'Blog Writer': 'Blogikirjutaja',
  'Blog Topic': 'Blogi teema',
  'Target Keywords': 'Sihtmärksõnad',
  'Target Audience (Optional)': 'Sihtgrupp (valikuline)',
  'Enter your blog topic or title...':
      'Sisesta oma blogi teema või pealkiri...',
  'e.g., AI writing, content marketing, SEO tips':
      'nt AI kirjutamine, sisuturundus, SEO nõuanded',
  'e.g., small business owners, bloggers':
      'nt väikeettevõtete omanikud, blogijad',
  'Article Type': 'Artikli tüüp',
  'Writing Tone': 'Kirjutamise toon',
  'Article Length': 'Artikli pikkus',
  'SEO Options': 'SEO valikud',
  'Include Meta Description': 'Lisa metakirjeldus',
  'Include Keyword Suggestions': 'Lisa märksõna soovitused',
  'Include FAQs Section': 'Lisa KKK jaotis',
  'Please enter a blog topic': 'Palun sisesta blogi teema',
  'Generate Blog': 'Genereeri blogi',
  'SEO optimized articles with keywords':
      'SEO-optimeeritud artiklid märksõnadega',
  'Write Blog': 'Kirjuta blogi',
  'SEO Article': 'SEO artikkel',
  'How-To Guide': 'Juhend',
  'Listicle': 'Loendiartikkel',
  'Product Review': 'Tootearvustus',
  'Opinion Piece': 'Arvamusartikkel',
  'News Article': 'Uudisartikkel',
  'Professional': 'Professionaalne',
  'Casual': 'Vabam',
  'Informative': 'Informatiivne',
  'Persuasive': 'Veenev',
  'Friendly': 'Sõbralik',
  'Authoritative': 'Autoriteetne',
  'Short (500-800)': 'Lühike (500-800)',
  'Medium (800-1500)': 'Keskmine (800-1500)',
  'Long (1500-2500)': 'Pikk (1500-2500)',
  'Detailed (2500+)': 'Detailne (2500+)',
  'YouTube Script': 'YouTube skript',
  'Video Topic': 'Video teema',
  'Key Points (Optional)': 'Põhipunktid (valikuline)',
  'What is your video about?': 'Millest su video räägib?',
  'List key points to cover (optional)...':
      'Loetele põhipunktid (valikuline)...',
  'Video Duration': 'Video kestus',
  'Script Options': 'Skripti valikud',
  'Include Hook/Intro': 'Lisa sissejuhatus',
  'Include Call-to-Action': 'Lisa üleskutse tegevusele',
  'Include Timestamps': 'Lisa ajatemplid',
  'Please enter a video topic': 'Palun sisesta video teema',
  'Generate Script': 'Genereeri skript',
  'Create scripts for videos & reels': 'Loo skripte videotele ja reelidele',
  'Create Script': 'Loo skript',
  'Storytime': 'Jutustamisaeg',
  'Documentary': 'Dokumentaal',
  'Short Reel': 'Lühike reel',
  'Educational': 'Hariduslik',
  'Review': 'Arvustus',
  'Tutorial': 'Õpetus',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Kaasahaarav',
  'Energetic': 'Energiline',
  'Calm': 'Rahulik',
  'Funny': 'Naljakas',
  'Inspired': 'Inspireeritud',
  'Film Script': 'Filmiskript',
  'Stage Play': 'Lavanäidend',
  'Scene Breakdown': 'Stseeni analüüs',
  'Dialogue Only': 'Ainult dialoog',
  'Ad loading please wait..': 'Reklaam laadib, palun oota..',
  'Words:': 'Sõnad:',
  'Reading:': 'Lugemisaeg:',
};
