import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> eu = {
  AppKeys.lblChooseLanguage: "Aukeratu hizkuntza",
  "All": "Guztiak",
  "AI Story Generator": "AA istorio sortzailea",
  "Story Generator": "Istorio sortzailea",
  "Essay Writer": "Saiakera idazlea",
  "Essay length": "Saiakera luzera",
  "Script Generator": "Gidoi sortzailea",
  "Create original stories in seconds": "Sortu jatorrizko istorioak segundotan",
  "Academic writing made simple": "Idazketa akademikoa erraz eginda",
  "Generate powerful scripts for any medium":
      "Sortu gidoi indartsuak edozein bitartekorako",
  "Start Writing": "Hasi idazten",
  "Create Now": "Sortu orain",
  "Start Generating": "Hasi sortzen",
  "Your Stories": "Zure istorioak",
  "No stories yet": "Oraindik istoriorik ez",
  "Start creating your first story!": "Hasi zure lehen istorioa sortzen!",
  "Your Story Space Awaits": "Zure istorio espazioa zain dago",
  "Start your first story and see it appear here":
      "Hasi zure lehen istorioa eta ikusi hemen agertzen",
  "Language": "Hizkuntza",
  "Rate us": "Baloratu gaitzazu",
  "Share us": "Partekatu gaitzazu",
  "Privacy Policy": "Pribatutasun politika",
  "Settings": "Ezarpenak",
  "Select Language": "Aukeratu hizkuntza",
  "Dashboard": "Panela",
  "BENEFITS": "ONURAK",
  "Subscribe": "Harpidetu",
  "Weekly": "Astero",
  "Monthly": "Hilero",
  "Yearly": "Urtero",
  "week": "astea",
  "months": "hilabeteak",
  "year": "urtea",
  "Terms & Condition": "Baldintzak",
  "No Commitment. Cancel anytime":
      "Konpromisorik gabe. Ezeztatu edozein unetan",
  "No Payment Now": "Orain ordainketarik ez",
  "3 days free": "3 egun doako",
  "Start your free trial": "Hasi zure doako proba",
  "More detailed answers": "Erantzun zehatzagoak",
  "Instant responds": "Berehalako erantzunak",
  "Text recognition": "Testu ezagutza",
  "Powered by AI": "AAk bultzatuta",
  "Storytelleing": "Istorio kontaketa",
  ' Power': " Indarra",
  "Unlock your \nFill ": "Desblokeatu zure \nFill ",
  "Your History": "Zure historia",
  "Terms and Conditions": "Baldintzak",
  "Short": "Laburra",
  "Medium": "Ertaina",
  "Long": "Luzea",
  "Length": "Luzera",
  "Describe your topic...": "Deskribatu zure gaia...",
  "Set Creativity": "Ezarri sormena",
  "Standard": "Estandarra",
  "Creative": "Sortzailea",
  "Complex": "Konplexua",
  "Select Genre": "Aukeratu generoa",
  "Fantasy": "Fantasia",
  "Mystery": "Misterioa",
  "Thriller": "Thriller",
  "Script Tone": "Gidoi tonua",
  "Script Type": "Gidoi mota",
  "Comedy": "Komedia",
  "Drama": "Drama",
  "Horror": "Beldurra",
  "Action": "Ekintza",
  "Romance": "Erromantze",
  "Go Premium": "Premium-era joan",
  "Unlock Everything": "Desblokeatu guztia",
  "Unlimited Story Generation": "Mugagabeko istorio sorrera",
  "Write Longer & Detailed Essays": "Idatzi saiakera luzeagoak eta zehatzagoak",
  "Advanced Script Writer": "Gidoi idazle aurreratua",
  "Unlock All Styles & Tones": "Desblokeatu estilo eta tonu guztiak",
  "No Word/Length Limit": "Hitz/luzera mugarik ez",
  "Remove All Ads": "Kendu iragarki guztiak",
  "Restore": "Berrezarri",
  "YouTube Video": "YouTube bideoa",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motibatzailea",
  "Advertisement": "Iragarkia",
  "Fairy Tale": "Ipuina",
  "Sci-Fi": "Zientzia fikzioa",
  "Select Style": "Aukeratu estiloa",
  "Imaginative": "Irudimentsua",
  "Innovative": "Berritzailea",
  "AI Story Writer": "AA istorio idazlea",
  "Generate": "Sortu",
  "Please wait...": "Mesedez itxaron...",
  "Result": "Emaitza",
  "Regenerate": "Birsortu",
  "Download": "Deskargatu",
  "Text copied to clipboard!": "Testua arbelean kopiatuta!",
  "Please enter a topic": "Mesedez sartu gai bat",
  "Story Magic": "Istorio magia",
  "Let AI bring your thoughts to a full story":
      "Utzi AAri zure pentsamenduak istorio oso bihurtzen",
  "Smart Scripts": "Gidoi adimendunak",
  "From concept to script—fast, easy, and creative":
      "Kontzeptutik gidoira—azkar, erraz eta sortzailea",
  "Perfect Essays": "Saiakera perfektuak",
  "You have reached your free limit": "Zure doako mugara iritsi zara",
  "Donwload": "Deskargatu",
  "Press again to exit app": "Sakatu berriro aplikaziotik irteteko",
  "Saved to files": "TXT fitxategia ondo gordeta!",
  "Error: Please try again": "Errorea: Mesedez saiatu berriro",
  "Subscription expired": "Harpidetza iraungi da",
  "Purchase cancelled": "Erosketa bertan behera utzi da",
  "Purchase failed": "Erosketa huts egin du",
  "Restore failed": "Berrezarpenak huts egin du",
  "Purchase Successful!": "Erosketa arrakastatsua!",
  "Short (200-500 words)": "Laburra (200-500 hitz)",
  "Medium (500-1000 words)": "Ertaina (500-1000 hitz)",
  "Large (1000+ words)": "Handia (1000+ hitz)",
  "Academic Level": "Maila akademikoa",
  "Type of Paper": "Lan mota",
  "High School": "Batxilergoa",
  "College": "Unibertsitatea",
  "Short Film": "Film laburra",
  "University": "Unibertsitatea",
  "Masters": "Masterra",
  "Custom": "Pertsonalizatua",
  "Tiktok Video": "TikTok bideoa",
  "Movie": "Filma",
  "Expository": "Azaltzailea",
  "Argumentative": "Argumentatzailea",
  "Narrative": "Narratiboa",
  "Descriptive": "Deskribatzailea",
  "We're sorry to hear that 😔": "Sentitzen dugu hori entzutea 😔",
  "We'll try to improve 🙁": "Hobetzen saiatuko gara 🙁",
  "Thanks for your feedback 🙂": "Eskerrik asko zure iritziagaitik 🙂",
  "Great! We're glad you like it 😊": "Bikain! Pozten gara gustatu izana 😊",
  "Awesome! Thank you so much! 🎉": "Zoragarria! Mila esker! 🎉",
  "Maybe Later": "Agian geroago",
  "Tap a star to rate your experience":
      "Sakatu izar bat zure esperientzia baloratzeko",
  "Enjoying AI Math Solver?": "AA matematika ebaztailea gustatzen zaizu?",
  "Thank you for rating us": "Eskerrik asko baloratzea egin duzulako",
  "Submit Rating": "Bidali balorazioa",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "AA istorio sortzailea gustatzen zaizu?",
  AppKeys.arabic: "Arabiera",
  AppKeys.chinese: "Txinera",
  AppKeys.english: "Ingelesa",
  AppKeys.french: "Frantsesa",
  AppKeys.german: "Alemana",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesiera",
  AppKeys.japanese: "Japoniera",
  AppKeys.korean: "Koreera",
  AppKeys.portuguese: "Portugesa",
  AppKeys.russian: "Errusiera",
  AppKeys.spanish: "Gaztelania",
  AppKeys.turkish: "Turkiera",
  'Download As': 'Deskargatu honela',
  'Choose format to download': 'Aukeratu deskarga formatua',
  'Text File': 'Testu fitxategia',
  'PDF File': 'PDF fitxategia',
  'Copy': 'Kopiatu',
  'Share': 'Partekatu',
  'Text copied!': 'Testua kopiatuta!',
  'PDF saved successfully!': 'PDFa ondo gordeta!',
  'Error creating PDF: Please try again':
      'Errorea PDFa sortzerakoan: Mesedez saiatu berriro',
  'Character Story': 'Pertsonaiaren istorioa',
  'Character Details': 'Pertsonaiaren xehetasunak',
  'Character Name': 'Pertsonaiaren izena',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Adina (adib., 25, Gazte heldua, Antzinakoa)',
  'Personality (e.g., brave, shy, cunning)':
      'Pertsonalitatea (adib., ausarta, lotsatia, maltzurra)',
  'Role (e.g., Hero, Villain, Mentor)':
      'Rola (adib., Heroia, Gaiztoa, Mentorea)',
  'Additional Details (optional)': 'Xehetasun osagarriak (aukerakoa)',
  'Output Style': 'Irteera estiloa',
  'Generate Character': 'Sortu pertsonaia',
  'Please enter character name': 'Mesedez sartu pertsonaiaren izena',
  'Please enter character role': 'Mesedez sartu pertsonaiaren rola',
  'Detailed': 'Xehatua',
  'Brief': 'Laburra',
  'Elaborate': 'Sakona',
  'Create detailed character backstories':
      'Sortu pertsonaien aurrehistoria zehatzak',
  'Create Character': 'Sortu pertsonaia',
  'Transform and improve your existing stories':
      'Eraldatu eta hobetu zure dauden istorioak',
  'Rewrite Now': 'Berridatzi orain',
  'Generate catchy titles for your stories':
      'Sortu titulu erakargarriak zure istorioentzat',
  'Generate Titles': 'Sortu tituluak',
  'Rewrite Story': 'Berridatzi istorioa',
  'Paste Your Story': 'Itsatsi zure istorioa',
  'Paste your story here to rewrite...':
      'Itsatsi zure istorioa hemen berridazteko...',
  'Select Tone': 'Aukeratu tonua',
  'Rewrite Style': 'Berridazketa estiloa',
  'Output Length': 'Irteera luzera',
  'Please paste your story': 'Mesedez itsatsi zure istorioa',
  'Story is too short. Please provide more content.':
      'Istorioa laburregia da. Mesedez eman eduki gehiago.',
  'Same': 'Berdina',
  'More Dramatic': 'Dramatikoagoa',
  'More Humorous': 'Umorezkoa',
  'More Emotional': 'Emozionalagoa',
  'More Suspenseful': 'Suspensiboagoa',
  'Lighter': 'Arinagoa',
  'Improved': 'Hobetua',
  'Simplified': 'Sinplifikatua',
  'More Descriptive': 'Deskribatzaileagoa',
  'More Dialogue': 'Elkarrizketa gehiago',
  'More Action': 'Ekintza gehiago',
  'Literary': 'Literarioa',
  'Shorter': 'Laburragoa',
  'Longer': 'Luzeagoa',
  'Much Longer': 'Askoz luzeagoa',
  'Title Generator': 'Titulu sortzailea',
  'Story/Book Topic': 'Istorio/liburu gaia',
  'Keywords (Optional)': 'Gako-hitzak (aukerakoa)',
  'Describe your story topic or theme...': 'Deskribatu zure istorio gaia...',
  'e.g., magic, dragon, adventure': 'adib., magia, dragoia, abentura',
  'Title For': 'Tituluarentzat',
  'Title Style': 'Titulu estiloa',
  "Adventure": "Abentura",
  'Number of Titles': 'Titulu kopurua',
  'Book': 'Liburua',
  'Short Story': 'Istorio laburra',
  'Novel': 'Eleberria',
  'Chapter': 'Kapitulua',
  'Series': 'Seriea',
  'Simple': 'Sinplea',
  'Mysterious': 'Misteriotsua',
  'Dramatic': 'Dramatikoa',
  'Catchy': 'Erakargarria',
  'Poetic': 'Poetikoa',
  'Kids': 'Umeentzat',
  'Blog Writer': 'Blog idazlea',
  'Blog Topic': 'Blog gaia',
  'Target Keywords': 'Helburu gako-hitzak',
  'Target Audience (Optional)': 'Helburu publikoa (aukerakoa)',
  'Enter your blog topic or title...': 'Sartu zure blog gaia edo titulua...',
  'e.g., AI writing, content marketing, SEO tips':
      'adib., AA idazketa, eduki marketina, SEO aholkuak',
  'e.g., small business owners, bloggers':
      'adib., enpresa txikien jabeak, bloglariak',
  'Article Type': 'Artikulu mota',
  'Writing Tone': 'Idazketa tonua',
  'Article Length': 'Artikulu luzera',
  'SEO Options': 'SEO aukerak',
  'Include Meta Description': 'Meta deskripzioa sartu',
  'Include Keyword Suggestions': 'Gako-hitz iradokizunak sartu',
  'Include FAQs Section': 'Ohiko galderak sekzioa sartu',
  'Please enter a blog topic': 'Mesedez sartu blog gai bat',
  'Generate Blog': 'Sortu bloga',
  'SEO optimized articles with keywords':
      'SEOrako optimizatutako artikuluak gako-hitzekin',
  'Write Blog': 'Idatzi bloga',
  'SEO Article': 'SEO artikulua',
  'How-To Guide': 'Nola egin gida',
  'Listicle': 'Zerrenda artikulua',
  'Product Review': 'Produktu iritzia',
  'Opinion Piece': 'Iritzi artikulua',
  'News Article': 'Berri artikulua',
  'Professional': 'Profesionala',
  'Casual': 'Informala',
  'Informative': 'Informatiboa',
  'Persuasive': 'Konbentzitzailea',
  'Friendly': 'Adiskidetsua',
  'Authoritative': 'Autoritatiboa',
  'Short (500-800)': 'Laburra (500-800)',
  'Medium (800-1500)': 'Ertaina (800-1500)',
  'Long (1500-2500)': 'Luzea (1500-2500)',
  'Detailed (2500+)': 'Xehatua (2500+)',
  'YouTube Script': 'YouTube gidoia',
  'Video Topic': 'Bideo gaia',
  'Key Points (Optional)': 'Gako puntuak (aukerakoa)',
  'What is your video about?': 'Zertaz da zure bideoa?',
  'List key points to cover (optional)...':
      'Zerrendatu gako puntuak (aukerakoa)...',
  'Video Duration': 'Bideo iraupena',
  'Script Options': 'Gidoi aukerak',
  'Include Hook/Intro': 'Sartu harpidetzarako gakoa',
  'Include Call-to-Action': 'Ekintzarako deia sartu',
  'Include Timestamps': 'Denbora-markak sartu',
  'Please enter a video topic': 'Mesedez sartu bideo gai bat',
  'Generate Script': 'Sortu gidoia',
  'Create scripts for videos & reels':
      'Sortu gidoiak bideoetarako eta reelentzat',
  'Create Script': 'Sortu gidoia',
  'Storytime': 'Istorio denbora',
  'Documentary': 'Dokumentala',
  'Short Reel': 'Reel laburra',
  'Educational': 'Hezitzailea',
  'Review': 'Iritzia',
  'Tutorial': 'Tutoriala',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Erakargarria',
  'Energetic': 'Energikoa',
  'Calm': 'Lasaia',
  'Funny': 'Dibertigarria',
  'Inspired': 'Inspiratua',
  'Film Script': 'Film gidoia',
  'Stage Play': 'Antzerkia',
  'Scene Breakdown': 'Eszena analisia',
  'Dialogue Only': 'Elkarrizketa soilik',
  'Ad loading please wait..': 'Iragarkia kargatzen, mesedez itxaron..',
  'Words:': 'Hitzak:',
  'Reading:': 'Irakurketa:',
};
