import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> fa = {
  AppKeys.lblChooseLanguage: "زبان را انتخاب کنید",
  "All": "همه",
  "AI Story Generator": "تولیدکننده داستان هوش مصنوعی",
  "Story Generator": "تولیدکننده داستان",
  "Essay Writer": "نویسنده مقاله",
  "Essay length": "طول مقاله",
  "Script Generator": "تولیدکننده فیلمنامه",
  "Create original stories in seconds":
      "داستان‌های اصیل را در چند ثانیه بسازید",
  "Academic writing made simple": "نوشتن آکادمیک ساده شده",
  "Generate powerful scripts for any medium":
      "فیلمنامه‌های قدرتمند برای هر رسانه‌ای بسازید",
  "Start Writing": "شروع نوشتن",
  "Create Now": "اکنون بسازید",
  "Start Generating": "شروع تولید",
  "Your Stories": "داستان‌های شما",
  "No stories yet": "هنوز داستانی وجود ندارد",
  "Start creating your first story!": "اولین داستان خود را بسازید!",
  "Your Story Space Awaits": "فضای داستان شما منتظر است",
  "Start your first story and see it appear here":
      "اولین داستان خود را شروع کنید و آن را اینجا ببینید",
  "Language": "زبان",
  "Rate us": "به ما امتیاز دهید",
  "Share us": "ما را به اشتراک بگذارید",
  "Privacy Policy": "سیاست حفظ حریم خصوصی",
  "Settings": "تنظیمات",
  "Select Language": "زبان را انتخاب کنید",
  "Dashboard": "داشبورد",
  "BENEFITS": "مزایا",
  "Subscribe": "اشتراک",
  "Weekly": "هفتگی",
  "Monthly": "ماهانه",
  "Yearly": "سالانه",
  "week": "هفته",
  "months": "ماه",
  "year": "سال",
  "Terms & Condition": "شرایط و ضوابط",
  "No Commitment. Cancel anytime": "بدون تعهد. هر زمان لغو کنید",
  "No Payment Now": "اکنون پرداختی نیست",
  "3 days free": "۳ روز رایگان",
  "Start your free trial": "دوره آزمایشی رایگان خود را شروع کنید",
  "More detailed answers": "پاسخ‌های دقیق‌تر",
  "Instant responds": "پاسخ‌های فوری",
  "Text recognition": "تشخیص متن",
  "Powered by AI": "با قدرت هوش مصنوعی",
  "Storytelleing": "داستان‌سرایی",
  ' Power': " قدرت",
  "Unlock your \nFill ": "قفل خود را باز کنید \nFill ",
  "Your History": "تاریخچه شما",
  "Terms and Conditions": "شرایط و ضوابط",
  "Short": "کوتاه",
  "Medium": "متوسط",
  "Long": "بلند",
  "Length": "طول",
  "Describe your topic...": "موضوع خود را توصیف کنید...",
  "Set Creativity": "تنظیم خلاقیت",
  "Standard": "استاندارد",
  "Creative": "خلاقانه",
  "Complex": "پیچیده",
  "Select Genre": "ژانر را انتخاب کنید",
  "Fantasy": "فانتزی",
  "Mystery": "رمزی",
  "Thriller": "هیجان‌انگیز",
  "Script Tone": "لحن فیلمنامه",
  "Script Type": "نوع فیلمنامه",
  "Comedy": "کمدی",
  "Drama": "درام",
  "Horror": "ترسناک",
  "Action": "اکشن",
  "Romance": "عاشقانه",
  "Go Premium": "پریمیوم شوید",
  "Unlock Everything": "همه چیز را باز کنید",
  "Unlimited Story Generation": "تولید نامحدود داستان",
  "Write Longer & Detailed Essays": "مقالات طولانی‌تر و مفصل‌تر بنویسید",
  "Advanced Script Writer": "نویسنده فیلمنامه پیشرفته",
  "Unlock All Styles & Tones": "تمام سبک‌ها و لحن‌ها را باز کنید",
  "No Word/Length Limit": "بدون محدودیت کلمه/طول",
  "Remove All Ads": "حذف تمام تبلیغات",
  "Restore": "بازیابی",
  "YouTube Video": "ویدیوی یوتیوب",
  "Podcast": "پادکست",
  "Reel": "ریل",
  "Motivational": "انگیزشی",
  "Advertisement": "تبلیغات",
  "Fairy Tale": "قصه پریان",
  "Sci-Fi": "علمی تخیلی",
  "Select Style": "سبک را انتخاب کنید",
  "Imaginative": "تخیلی",
  "Innovative": "نوآورانه",
  "AI Story Writer": "نویسنده داستان هوش مصنوعی",
  "Generate": "تولید",
  "Please wait...": "لطفاً صبر کنید...",
  "Result": "نتیجه",
  "Regenerate": "تولید مجدد",
  "Download": "دانلود",
  "Text copied to clipboard!": "متن در کلیپ بورد کپی شد!",
  "Please enter a topic": "لطفاً یک موضوع وارد کنید",
  "Story Magic": "جادوی داستان",
  "Let AI bring your thoughts to a full story":
      "بگذارید هوش مصنوعی ا��کارتان را به داستانی کامل تبدیل کند",
  "Smart Scripts": "فیلمنامه‌های هوشمند",
  "From concept to script—fast, easy, and creative":
      "از مفهوم تا فیلمنامه—سریع، آسان و خلاقانه",
  "Perfect Essays": "مقالات عالی",
  "You have reached your free limit": "به حد رایگان خود رسیده‌اید",
  "Donwload": "دانلود",
  "Press again to exit app": "دوباره فشار دهید تا از برنامه خارج شوید",
  "Saved to files": "فایل TXT با موفقیت ذخیره شد!",
  "Error: Please try again": "خطا: لطفاً دوباره تلاش کنید",
  "Subscription expired": "اشتراک منقضی شده",
  "Purchase cancelled": "خرید لغو شد",
  "Purchase failed": "خرید ناموفق بود",
  "Restore failed": "بازیابی ناموفق بود",
  "Purchase Successful!": "خرید موفقیت‌آمیز بود!",
  "Short (200-500 words)": "کوتاه (۲۰۰-۵۰۰ کلمه)",
  "Medium (500-1000 words)": "متوسط (۵۰۰-۱۰۰۰ کلمه)",
  "Large (1000+ words)": "بزرگ (+۱۰۰۰ کلمه)",
  "Academic Level": "سطح آکادمیک",
  "Type of Paper": "نوع مقاله",
  "High School": "دبیرستان",
  "College": "کالج",
  "Short Film": "فیلم کوتاه",
  "University": "دانشگاه",
  "Masters": "کارشناسی ارشد",
  "Custom": "سفارشی",
  "Tiktok Video": "ویدیوی تیک‌تاک",
  "Movie": "فیلم",
  "Expository": "تشریحی",
  "Argumentative": "استدلالی",
  "Narrative": "روایتی",
  "Descriptive": "توصیفی",
  "We're sorry to hear that 😔": "متأسفیم که این را می‌شنویم 😔",
  "We'll try to improve 🙁": "سعی می‌کنیم بهتر شویم 🙁",
  "Thanks for your feedback 🙂": "ممنون از بازخورد شما 🙂",
  "Great! We're glad you like it 😊": "عالی! خوشحالیم که دوستش دارید 😊",
  "Awesome! Thank you so much! 🎉": "فوق‌العاده! بسیار ممنون! 🎉",
  "Maybe Later": "شاید بعداً",
  "Tap a star to rate your experience":
      "یک ستاره بزنید تا تجربه خود را امتیاز دهید",
  "Enjoying AI Math Solver?": "از حل‌کننده ریاضی هوش مصنوعی لذت می‌برید؟",
  "Thank you for rating us": "ممنون که به ما امتیاز دادید",
  "Submit Rating": "ارسال امتیاز",
  "Hindi": "هندی",
  "Enjoying AI Story Generator?":
      "از تول��دکننده داستان هوش مصنوعی لذت می‌برید؟",
  AppKeys.arabic: "عربی",
  AppKeys.chinese: "چینی",
  AppKeys.english: "انگلیسی",
  AppKeys.french: "فرانسوی",
  AppKeys.german: "آلمانی",
  AppKeys.hindi: "هندی",
  AppKeys.indonesian: "اندونزیایی",
  AppKeys.japanese: "ژاپنی",
  AppKeys.korean: "کره‌ای",
  AppKeys.portuguese: "پرتغالی",
  AppKeys.russian: "روسی",
  AppKeys.spanish: "اسپانیایی",
  AppKeys.turkish: "ترکی",
  'Download As': 'دانلود به عنوان',
  'Choose format to download': 'فرمت دانلود را انتخاب کنید',
  'Text File': 'فایل متنی',
  'PDF File': 'فایل PDF',
  'Copy': 'کپی',
  'Share': 'اشتراک‌گذاری',
  'Text copied!': 'متن کپی شد!',
  'PDF saved successfully!': 'PDF با موفقیت ذخیره شد!',
  'Error creating PDF: Please try again':
      'خطا در ایجاد PDF: لطفاً دوباره تلاش کنید',
  'Character Story': 'داستان شخصیت',
  'Character Details': 'جزئیات شخصیت',
  'Character Name': 'نام شخصیت',
  'Age (e.g., 25, Young Adult, Ancient)': 'سن (مثلاً ۲۵، جوان، باستانی)',
  'Personality (e.g., brave, shy, cunning)':
      'شخصیت (مثلاً شجاع، خجالتی، حیله‌گر)',
  'Role (e.g., Hero, Villain, Mentor)': 'نقش (مثلاً قهرمان، شرور، مرشد)',
  'Additional Details (optional)': 'جزئیات اضافی (اختیاری)',
  'Output Style': 'سبک خروجی',
  'Generate Character': 'تولید شخصیت',
  'Please enter character name': 'لطفاً نام شخصیت را وارد کنید',
  'Please enter character role': 'لطفاً نقش شخصیت را وارد کنید',
  'Detailed': 'مفصل',
  'Brief': 'مختصر',
  'Elaborate': 'گسترده',
  'Create detailed character backstories': 'پیشینه مفصل شخصیت‌ها بسازید',
  'Create Character': 'ایجاد شخصیت',
  'Transform and improve your existing stories':
      'داستان‌های موجود خود را تغییر دهید و بهبود ببخشید',
  'Rewrite Now': 'اکنون بازنویسی کنید',
  'Generate catchy titles for your stories':
      'عناوین جذاب برای داستان‌هایتان بسازید',
  'Generate Titles': 'تولید عناوین',
  'Rewrite Story': 'بازنویسی داستان',
  'Paste Your Story': 'داستان خود را بچسبانید',
  'Paste your story here to rewrite...':
      'داستان خود را برای بازنویسی اینجا بچسبانید...',
  'Select Tone': 'لحن را انتخاب کنید',
  'Rewrite Style': 'سبک بازنویسی',
  'Output Length': 'طول خروجی',
  'Please paste your story': 'لطفاً داستان خود را بچسبانید',
  'Story is too short. Please provide more content.':
      'داستان خیلی کوتاه است. لطفاً محتوای بیشتری ارائه دهید.',
  'Same': 'همان',
  'More Dramatic': 'دراماتیک‌تر',
  'More Humorous': 'طنزآمیزتر',
  'More Emotional': 'احساسی‌تر',
  'More Suspenseful': 'هیجان‌انگیزتر',
  'Lighter': 'سبک‌تر',
  'Improved': 'بهبود یافته',
  'Simplified': 'ساده‌شده',
  'More Descriptive': 'توصیفی‌تر',
  'More Dialogue': 'گفتگوی بیشتر',
  'More Action': 'اکشن بیشتر',
  'Literary': 'ادبی',
  'Shorter': 'کوتاه‌تر',
  'Longer': 'بلندتر',
  'Much Longer': 'بسیار بلندتر',
  'Title Generator': 'تولیدکننده عنوان',
  'Story/Book Topic': 'موضوع داستان/کتاب',
  'Keywords (Optional)': 'کلمات کلیدی (اختیاری)',
  'Describe your story topic or theme...':
      'موضوع یا تم داستان خود را توصیف کنید...',
  'e.g., magic, dragon, adventure': 'مثلاً جادو، اژدها، ماجراجویی',
  'Title For': 'عنوان برای',
  'Title Style': 'سبک عنوان',
  "Adventure": "ماجراجویی",
  'Number of Titles': 'تعداد عناوین',
  'Book': 'کتاب',
  'Short Story': 'داستان کوتاه',
  'Novel': 'رمان',
  'Chapter': 'فصل',
  'Series': 'مجموعه',
  'Simple': 'ساده',
  'Mysterious': 'رمزآلود',
  'Dramatic': 'دراماتیک',
  'Catchy': 'جذاب',
  'Poetic': 'شاعرانه',
  'Kids': 'کودکان',
  'Blog Writer': 'نویسنده بلاگ',
  'Blog Topic': 'موضوع بلاگ',
  'Target Keywords': 'کلمات کلیدی هدف',
  'Target Audience (Optional)': 'مخاطبان هدف (اختیاری)',
  'Enter your blog topic or title...':
      'موضوع یا عنوان بلاگ خود را وارد کنید...',
  'e.g., AI writing, content marketing, SEO tips':
      'مثلاً نوشتن با هوش مصنوعی، بازاریابی محتوا، نکات SEO',
  'e.g., small business owners, bloggers':
      'مثلاً صاحبان کسب‌وکار کوچک، بلاگرها',
  'Article Type': 'نوع مقاله',
  'Writing Tone': 'لحن نوشتن',
  'Article Length': 'طول مقاله',
  'SEO Options': 'گزینه‌های SEO',
  'Include Meta Description': 'شامل توضیحات متا',
  'Include Keyword Suggestions': 'شامل پیشنهادات کلمات کلیدی',
  'Include FAQs Section': 'شامل بخش سؤالات متداول',
  'Please enter a blog topic': 'لطفاً یک موضوع بلاگ وارد کنید',
  'Generate Blog': 'تولید بلاگ',
  'SEO optimized articles with keywords': 'مقالات بهینه‌شده SEO با کلمات کلیدی',
  'Write Blog': 'نوشتن بلاگ',
  'SEO Article': 'مقاله SEO',
  'How-To Guide': 'راهنمای آموزشی',
  'Listicle': 'مقاله فهرستی',
  'Product Review': 'بررسی محصول',
  'Opinion Piece': 'مقاله نظری',
  'News Article': 'مقاله خبری',
  'Professional': 'حرفه‌ای',
  'Casual': 'غیررسمی',
  'Informative': 'آموزنده',
  'Persuasive': 'متقاعدکننده',
  'Friendly': 'دوستانه',
  'Authoritative': 'معتبر',
  'Short (500-800)': 'کوتاه (۵۰۰-۸۰۰)',
  'Medium (800-1500)': 'متوسط (۸۰۰-۱۵۰۰)',
  'Long (1500-2500)': 'بلند (۱۵۰۰-۲۵۰۰)',
  'Detailed (2500+)': 'مفصل (+۲۵۰۰)',
  'YouTube Script': 'فیلمنامه یوتیوب',
  'Video Topic': 'موضوع ویدیو',
  'Key Points (Optional)': 'نکات کلیدی (اختیاری)',
  'What is your video about?': 'ویدیوی شما درباره چیست؟',
  'List key points to cover (optional)...':
      'نکات کلیدی را فهرست کنید (اختیاری)...',
  'Video Duration': 'مدت ویدیو',
  'Script Options': 'گزینه‌های فیلمنامه',
  'Include Hook/Intro': 'شامل قلاب/مقدمه',
  'Include Call-to-Action': 'شامل فراخوان اقدام',
  'Include Timestamps': 'شامل برچسب‌های زمانی',
  'Please enter a video topic': 'لطفاً یک موضوع ویدیو وارد کنید',
  'Generate Script': 'تولید فیلمنامه',
  'Create scripts for videos & reels': 'فیلمنامه برای ویدیوها و ریل‌ها بسازید',
  'Create Script': 'ایجاد فیلمنامه',
  'Storytime': 'وقت داستان',
  'Documentary': 'مستند',
  'Short Reel': 'ریل کوتاه',
  'Educational': 'آموزشی',
  'Review': 'بررسی',
  'Tutorial': 'آموزش',
  '< 1 min (Shorts)': '< ۱ دقیقه (شورتز)',
  '1-3 min': '۱-۳ دقیقه',
  '5-10 min': '۵-۱۰ دقیقه',
  '10-20 min': '۱۰-۲۰ دقیقه',
  '20+ min': '+۲۰ دقیقه',
  'Engaging': 'جذاب',
  'Energetic': 'پرانرژی',
  'Calm': 'آرام',
  'Funny': 'خنده‌دار',
  'Inspired': 'الهام‌بخش',
  'Film Script': 'فیلمنامه فیلم',
  'Stage Play': 'نمایشنامه صحنه‌ای',
  'Scene Breakdown': 'تحلیل صحنه',
  'Dialogue Only': 'فقط گفتگو',
  'Ad loading please wait..': 'تبلیغ در حال بارگذاری لطفاً صبر کنید..',
  'Words:': 'کلمات:',
  'Reading:': 'خواندن:',
};
