import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> fi = {
  AppKeys.lblChooseLanguage: "Valitse kieli",
  "All": "Kaikki",
  "AI Story Generator": "AI-tarinanluoja",
  "Story Generator": "Tarinanluoja",
  "Essay Writer": "Esseen kirjoittaja",
  "Essay length": "Esseen pituus",
  "Script Generator": "Käsikirjoitusluoja",
  "Create original stories in seconds":
      "Luo alkuperäisiä tarinoita sekunneissa",
  "Academic writing made simple":
      "Akateeminen kirjoittaminen yksinkertaistettuna",
  "Generate powerful scripts for any medium":
      "Luo tehokkaita käsikirjoituksia mihin tahansa mediaan",
  "Start Writing": "Aloita kirjoittaminen",
  "Create Now": "Luo nyt",
  "Start Generating": "Aloita luominen",
  "Your Stories": "Tarinasi",
  "No stories yet": "Ei vielä tarinoita",
  "Start creating your first story!": "Aloita ensimmäisen tarinasi luominen!",
  "Your Story Space Awaits": "Tarinatilasi odottaa",
  "Start your first story and see it appear here":
      "Aloita ensimmäinen tarinasi ja katso sen ilmestyvän tänne",
  "Language": "Kieli",
  "Rate us": "Arvioi meidät",
  "Share us": "Jaa meidät",
  "Privacy Policy": "Tietosuojakäytäntö",
  "Settings": "Asetukset",
  "Select Language": "Valitse kieli",
  "Dashboard": "Kojelauta",
  "BENEFITS": "EDUT",
  "Subscribe": "Tilaa",
  "Weekly": "Viikoittain",
  "Monthly": "Kuukausittain",
  "Yearly": "Vuosittain",
  "week": "viikko",
  "months": "kuukautta",
  "year": "vuosi",
  "Terms & Condition": "Ehdot",
  "No Commitment. Cancel anytime": "Ei sitoutumista. Peruuta milloin tahansa",
  "No Payment Now": "Ei maksua nyt",
  "3 days free": "3 päivää ilmaiseksi",
  "Start your free trial": "Aloita ilmainen kokeilu",
  "More detailed answers": "Yksityiskohtaisemmat vastaukset",
  "Instant responds": "Välittömät vastaukset",
  "Text recognition": "Tekstintunnistus",
  "Powered by AI": "AI:n voimalla",
  "Storytelleing": "Tarinankerronta",
  ' Power': " Voima",
  "Unlock your \nFill ": "Avaa \nFill ",
  "Your History": "Historiasi",
  "Terms and Conditions": "Ehdot",
  "Short": "Lyhyt",
  "Medium": "Keskipitkä",
  "Long": "Pitkä",
  "Length": "Pituus",
  "Describe your topic...": "Kuvaile aiheesi...",
  "Set Creativity": "Aseta luovuus",
  "Standard": "Vakio",
  "Creative": "Luova",
  "Complex": "Monimutkainen",
  "Select Genre": "Valitse genre",
  "Fantasy": "Fantasia",
  "Mystery": "Mysteeri",
  "Thriller": "Jännäri",
  "Script Tone": "Käsikirjoituksen sävy",
  "Script Type": "Käsikirjoituksen tyyppi",
  "Comedy": "Komedia",
  "Drama": "Draama",
  "Horror": "Kauhu",
  "Action": "Toiminta",
  "Romance": "Romanssi",
  "Go Premium": "Siirry Premiumiin",
  "Unlock Everything": "Avaa kaikki",
  "Unlimited Story Generation": "Rajoittamaton tarinoiden luominen",
  "Write Longer & Detailed Essays":
      "Kirjoita pidempiä ja yksityiskohtaisempia esseitä",
  "Advanced Script Writer": "Edistynyt käsikirjoittaja",
  "Unlock All Styles & Tones": "Avaa kaikki tyylit ja sävyt",
  "No Word/Length Limit": "Ei sana-/pituusrajoitusta",
  "Remove All Ads": "Poista kaikki mainokset",
  "Restore": "Palauta",
  "YouTube Video": "YouTube-video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivoiva",
  "Advertisement": "Mainos",
  "Fairy Tale": "Satu",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Valitse tyyli",
  "Imaginative": "Mielikuvituksellinen",
  "Innovative": "Innovatiivinen",
  "AI Story Writer": "AI-tarinakirjoittaja",
  "Generate": "Luo",
  "Please wait...": "Odota...",
  "Result": "Tulos",
  "Regenerate": "Luo uudelleen",
  "Download": "Lataa",
  "Text copied to clipboard!": "Teksti kopioitu leikepöydälle!",
  "Please enter a topic": "Syötä aihe",
  "Story Magic": "Tarinataikuutta",
  "Let AI bring your thoughts to a full story":
      "Anna AI:n muuttaa ajatuksesi kokonaiseksi tarinaksi",
  "Smart Scripts": "Älykkäät käsikirjoitukset",
  "From concept to script—fast, easy, and creative":
      "Konseptista käsikirjoitukseen—nopeasti, helposti ja luovasti",
  "Perfect Essays": "Täydelliset esseet",
  "You have reached your free limit": "Olet saavuttanut ilmaisen rajasi",
  "Donwload": "Lataa",
  "Press again to exit app": "Paina uudelleen poistuaksesi sovelluksesta",
  "Saved to files": "TXT-tiedosto tallennettu onnistuneesti!",
  "Error: Please try again": "Virhe: Yritä uudelleen",
  "Subscription expired": "Tilaus vanhentunut",
  "Purchase cancelled": "Osto peruutettu",
  "Purchase failed": "Osto epäonnistui",
  "Restore failed": "Palautus epäonnistui",
  "Purchase Successful!": "Osto onnistui!",
  "Short (200-500 words)": "Lyhyt (200-500 sanaa)",
  "Medium (500-1000 words)": "Keskipitkä (500-1000 sanaa)",
  "Large (1000+ words)": "Pitkä (1000+ sanaa)",
  "Academic Level": "Akateeminen taso",
  "Type of Paper": "Työn tyyppi",
  "High School": "Lukio",
  "College": "Korkeakoulu",
  "Short Film": "Lyhytelokuva",
  "University": "Yliopisto",
  "Masters": "Maisteriohjelma",
  "Custom": "Mukautettu",
  "Tiktok Video": "TikTok-video",
  "Movie": "Elokuva",
  "Expository": "Selittävä",
  "Argumentative": "Argumentoiva",
  "Narrative": "Kerronnallinen",
  "Descriptive": "Kuvaileva",
  "We're sorry to hear that 😔": "Olemme pahoillamme 😔",
  "We'll try to improve 🙁": "Yritämme parantaa 🙁",
  "Thanks for your feedback 🙂": "Kiitos palautteestasi 🙂",
  "Great! We're glad you like it 😊": "Hienoa! Iloitsemme, että pidät siitä 😊",
  "Awesome! Thank you so much! 🎉": "Mahtavaa! Paljon kiitoksia! 🎉",
  "Maybe Later": "Ehkä myöhemmin",
  "Tap a star to rate your experience":
      "Napauta tähteä arvioidaksesi kokemuksesi",
  "Enjoying AI Math Solver?": "Nautitko AI-matematiikan ratkaisijasta?",
  "Thank you for rating us": "Kiitos arvioinnista",
  "Submit Rating": "Lähetä arvio",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Nautitko AI-tarinanluojasta?",
  AppKeys.arabic: "Arabia",
  AppKeys.chinese: "Kiina",
  AppKeys.english: "Englanti",
  AppKeys.french: "Ranska",
  AppKeys.german: "Saksa",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesia",
  AppKeys.japanese: "Japani",
  AppKeys.korean: "Korea",
  AppKeys.portuguese: "Portugali",
  AppKeys.russian: "Venäjä",
  AppKeys.spanish: "Espanja",
  AppKeys.turkish: "Turkki",
  'Download As': 'Lataa muodossa',
  'Choose format to download': 'Valitse latausmuoto',
  'Text File': 'Tekstitiedosto',
  'PDF File': 'PDF-tiedosto',
  'Copy': 'Kopioi',
  'Share': 'Jaa',
  'Text copied!': 'Teksti kopioitu!',
  'PDF saved successfully!': 'PDF tallennettu onnistuneesti!',
  'Error creating PDF: Please try again':
      'Virhe PDF:n luomisessa: Yritä uudelleen',
  'Character Story': 'Hahmon tarina',
  'Character Details': 'Hahmon tiedot',
  'Character Name': 'Hahmon nimi',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Ikä (esim. 25, Nuori aikuinen, Muinainen)',
  'Personality (e.g., brave, shy, cunning)':
      'Persoonallisuus (esim. rohkea, ujo, ovela)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rooli (esim. Sankari, Konna, Mentori)',
  'Additional Details (optional)': 'Lisätiedot (valinnainen)',
  'Output Style': 'Tulostyyli',
  'Generate Character': 'Luo hahmo',
  'Please enter character name': 'Syötä hahmon nimi',
  'Please enter character role': 'Syötä hahmon rooli',
  'Detailed': 'Yksityiskohtainen',
  'Brief': 'Lyhyt',
  'Elaborate': 'Laaja',
  'Create detailed character backstories':
      'Luo yksityiskohtaisia hahmojen taustatarinoita',
  'Create Character': 'Luo hahmo',
  'Transform and improve your existing stories':
      'Muuta ja paranna olemassa olevia tarinoitasi',
  'Rewrite Now': 'Kirjoita uudelleen nyt',
  'Generate catchy titles for your stories':
      'Luo tarttuvia otsikoita tarinoillesi',
  'Generate Titles': 'Luo otsikoita',
  'Rewrite Story': 'Kirjoita tarina uudelleen',
  'Paste Your Story': 'Liitä tarinasi',
  'Paste your story here to rewrite...':
      'Liitä tarinasi tähän kirjoittaaksesi uudelleen...',
  'Select Tone': 'Valitse sävy',
  'Rewrite Style': 'Uudelleenkirjoitustyyli',
  'Output Length': 'Tuloksen pituus',
  'Please paste your story': 'Liitä tarinasi',
  'Story is too short. Please provide more content.':
      'Tarina on liian lyhyt. Anna enemmän sisältöä.',
  'Same': 'Sama',
  'More Dramatic': 'Dramaattisempi',
  'More Humorous': 'Humoristisempi',
  'More Emotional': 'Tunteellisempi',
  'More Suspenseful': 'Jännittävämpi',
  'Lighter': 'Kevyempi',
  'Improved': 'Parannettu',
  'Simplified': 'Yksinkertaistettu',
  'More Descriptive': 'Kuvailevampi',
  'More Dialogue': 'Enemmän dialogia',
  'More Action': 'Enemmän toimintaa',
  'Literary': 'Kirjallinen',
  'Shorter': 'Lyhyempi',
  'Longer': 'Pidempi',
  'Much Longer': 'Paljon pidempi',
  'Title Generator': 'Otsikkogenraattori',
  'Story/Book Topic': 'Tarinan/kirjan aihe',
  'Keywords (Optional)': 'Avainsanat (valinnainen)',
  'Describe your story topic or theme...':
      'Kuvaile tarinasi aihetta tai teemaa...',
  'e.g., magic, dragon, adventure': 'esim. taikuus, lohikäärme, seikkailu',
  'Title For': 'Otsikko',
  'Title Style': 'Otsikkotyyli',
  "Adventure": "Seikkailu",
  'Number of Titles': 'Otsikoiden määrä',
  'Book': 'Kirja',
  'Short Story': 'Novelli',
  'Novel': 'Romaani',
  'Chapter': 'Luku',
  'Series': 'Sarja',
  'Simple': 'Yksinkertainen',
  'Mysterious': 'Mysteerinen',
  'Dramatic': 'Dramaattinen',
  'Catchy': 'Tarttuva',
  'Poetic': 'Runollinen',
  'Kids': 'Lapsille',
  'Blog Writer': 'Blogikirjoittaja',
  'Blog Topic': 'Blogin aihe',
  'Target Keywords': 'Kohde-avainsanat',
  'Target Audience (Optional)': 'Kohdeyleisö (valinnainen)',
  'Enter your blog topic or title...': 'Syötä blogin aihe tai otsikko...',
  'e.g., AI writing, content marketing, SEO tips':
      'esim. AI-kirjoittaminen, sisältömarkkinointi, SEO-vinkit',
  'e.g., small business owners, bloggers':
      'esim. pienyrityksen omistajat, bloggaajat',
  'Article Type': 'Artikkelin tyyppi',
  'Writing Tone': 'Kirjoituksen sävy',
  'Article Length': 'Artikkelin pituus',
  'SEO Options': 'SEO-asetukset',
  'Include Meta Description': 'Sisällytä metakuvaus',
  'Include Keyword Suggestions': 'Sisällytä avainsanaehdotukset',
  'Include FAQs Section': 'Sisällytä UKK-osio',
  'Please enter a blog topic': 'Syötä blogin aihe',
  'Generate Blog': 'Luo blogi',
  'SEO optimized articles with keywords':
      'SEO-optimoidut artikkelit avainsanoilla',
  'Write Blog': 'Kirjoita blogi',
  'SEO Article': 'SEO-artikkeli',
  'How-To Guide': 'Opas',
  'Listicle': 'Listaartikkeli',
  'Product Review': 'Tuotearvostelu',
  'Opinion Piece': 'Mielipidekirjoitus',
  'News Article': 'Uutisartikkeli',
  'Professional': 'Ammattimainen',
  'Casual': 'Rento',
  'Informative': 'Informatiivinen',
  'Persuasive': 'Vakuuttava',
  'Friendly': 'Ystävällinen',
  'Authoritative': 'Arvovaltainen',
  'Short (500-800)': 'Lyhyt (500-800)',
  'Medium (800-1500)': 'Keskipitkä (800-1500)',
  'Long (1500-2500)': 'Pitkä (1500-2500)',
  'Detailed (2500+)': 'Yksityiskohtainen (2500+)',
  'YouTube Script': 'YouTube-käsikirjoitus',
  'Video Topic': 'Videon aihe',
  'Key Points (Optional)': 'Avainpisteet (valinnainen)',
  'What is your video about?': 'Mistä videosi kertoo?',
  'List key points to cover (optional)...':
      'Listaa käsiteltävät avainpisteet (valinnainen)...',
  'Video Duration': 'Videon kesto',
  'Script Options': 'Käsikirjoituksen asetukset',
  'Include Hook/Intro': 'Sisällytä koukku/intro',
  'Include Call-to-Action': 'Sisällytä toimintakehote',
  'Include Timestamps': 'Sisällytä aikaleimat',
  'Please enter a video topic': 'Syötä videon aihe',
  'Generate Script': 'Luo käsikirjoitus',
  'Create scripts for videos & reels':
      'Luo käsikirjoituksia videoille ja reeleille',
  'Create Script': 'Luo käsikirjoitus',
  'Storytime': 'Tarinatuokio',
  'Documentary': 'Dokumentti',
  'Short Reel': 'Lyhyt reel',
  'Educational': 'Opettavainen',
  'Review': 'Arvostelu',
  'Tutorial': 'Opastus',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Mukaansatempaava',
  'Energetic': 'Energinen',
  'Calm': 'Rauhallinen',
  'Funny': 'Hauska',
  'Inspired': 'Inspiroitunut',
  'Film Script': 'Elokuva­käsikirjoitus',
  'Stage Play': 'Näytelmä',
  'Scene Breakdown': 'Kohtausanalyysi',
  'Dialogue Only': 'Vain dialogi',
  'Ad loading please wait..': 'Mainos latautuu, odota..',
  'Words:': 'Sanat:',
  'Reading:': 'Lukuaika:',
};
