import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> fil = {
  AppKeys.lblChooseLanguage: "Pumili ng Wika",
  "All": "Lahat",
  "AI Story Generator": "AI Story Generator",
  "Story Generator": "Story Generator",
  "Essay Writer": "Manunulat ng Sanaysay",
  "Essay length": "Haba ng sanaysay",
  "Script Generator": "Script Generator",
  "Create original stories in seconds":
      "Lumikha ng orihinal na mga kwento sa ilang segundo",
  "Academic writing made simple": "Akademikong pagsulat na pinasimple",
  "Generate powerful scripts for any medium":
      "Gumawa ng makapangyarihang mga script para sa anumang medium",
  "Start Writing": "Magsimulang Sumulat",
  "Create Now": "Lumikha Ngayon",
  "Start Generating": "Magsimulang Gumawa",
  "Your Stories": "Mga Kwento Mo",
  "No stories yet": "Wala pang mga kwento",
  "Start creating your first story!":
      "Simulang likhain ang iyong unang kwento!",
  "Your Story Space Awaits": "Naghihintay ang Espasyo ng Kwento Mo",
  "Start your first story and see it appear here":
      "Simulan ang iyong unang kwento at makita itong lumitaw dito",
  "Language": "Wika",
  "Rate us": "I-rate kami",
  "Share us": "I-share kami",
  "Privacy Policy": "Patakaran sa Privacy",
  "Settings": "Mga Setting",
  "Select Language": "Pumili ng Wika",
  "Dashboard": "Dashboard",
  "BENEFITS": "MGA BENEPISYO",
  "Subscribe": "Mag-subscribe",
  "Weekly": "Lingguhan",
  "Monthly": "Buwanan",
  "Yearly": "Taunan",
  "week": "linggo",
  "months": "buwan",
  "year": "taon",
  "Terms & Condition": "Mga Tuntunin at Kundisyon",
  "No Commitment. Cancel anytime": "Walang Commitment. I-cancel anumang oras",
  "No Payment Now": "Walang Bayad Ngayon",
  "3 days free": "3 araw na libre",
  "Start your free trial": "Simulan ang iyong libreng trial",
  "More detailed answers": "Mas detalyadong mga sagot",
  "Instant responds": "Agarang mga sagot",
  "Text recognition": "Text recognition",
  "Powered by AI": "Pinapagana ng AI",
  "Storytelleing": "Pagkukwento",
  ' Power': " Kapangyarihan",
  "Unlock your \nFill ": "I-unlock ang iyong \nFill ",
  "Your History": "Iyong Kasaysayan",
  "Terms and Conditions": "Mga Tuntunin at Kundisyon",
  "Short": "Maikli",
  "Medium": "Katamtaman",
  "Long": "Mahaba",
  "Length": "Haba",
  "Describe your topic...": "Ilarawan ang iyong paksa...",
  "Set Creativity": "Itakda ang Pagkamalikhain",
  "Standard": "Standard",
  "Creative": "Malikhain",
  "Complex": "Komplikado",
  "Select Genre": "Pumili ng Genre",
  "Fantasy": "Pantasya",
  "Mystery": "Misteryo",
  "Thriller": "Thriller",
  "Script Tone": "Tono ng Script",
  "Script Type": "Uri ng Script",
  "Comedy": "Komedya",
  "Drama": "Drama",
  "Horror": "Horror",
  "Action": "Aksyon",
  "Romance": "Romansa",
  "Go Premium": "Mag-Premium",
  "Unlock Everything": "I-unlock Lahat",
  "Unlimited Story Generation": "Walang limitasyong paggawa ng kwento",
  "Write Longer & Detailed Essays":
      "Sumulat ng mas mahaba at detalyadong mga sanaysay",
  "Advanced Script Writer": "Advanced na Script Writer",
  "Unlock All Styles & Tones": "I-unlock lahat ng mga istilo at tono",
  "No Word/Length Limit": "Walang limitasyon sa salita/haba",
  "Remove All Ads": "Alisin lahat ng mga ads",
  "Restore": "I-restore",
  "YouTube Video": "YouTube Video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivational",
  "Advertisement": "Advertisement",
  "Fairy Tale": "Fairy Tale",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Pumili ng Istilo",
  "Imaginative": "Maimadyin",
  "Innovative": "Makabago",
  "AI Story Writer": "AI Story Writer",
  "Generate": "Gumawa",
  "Please wait...": "Mangyaring maghintay...",
  "Result": "Resulta",
  "Regenerate": "Gumawa Muli",
  "Download": "I-download",
  "Text copied to clipboard!": "Nakopya ang teksto sa clipboard!",
  "Please enter a topic": "Mangyaring maglagay ng paksa",
  "Story Magic": "Mahika ng Kwento",
  "Let AI bring your thoughts to a full story":
      "Hayaang dalhin ng AI ang iyong mga iniisip sa buong kwento",
  "Smart Scripts": "Matalinong mga Script",
  "From concept to script—fast, easy, and creative":
      "Mula konsepto hanggang script—mabilis, madali, at malikhain",
  "Perfect Essays": "Perpektong mga Sanaysay",
  "You have reached your free limit":
      "Naabot mo na ang iyong libreng limitasyon",
  "Donwload": "I-download",
  "Press again to exit app": "Pindutin muli para lumabas sa app",
  "Saved to files": "Matagumpay na na-save ang TXT file!",
  "Error: Please try again": "Error: Mangyaring subukan muli",
  "Subscription expired": "Nag-expire ang subscription",
  "Purchase cancelled": "Na-cancel ang pagbili",
  "Purchase failed": "Nabigo ang pagbili",
  "Restore failed": "Nabigo ang pag-restore",
  "Purchase Successful!": "Matagumpay ang Pagbili!",
  "Short (200-500 words)": "Maikli (200-500 salita)",
  "Medium (500-1000 words)": "Katamtaman (500-1000 salita)",
  "Large (1000+ words)": "Malaki (1000+ salita)",
  "Academic Level": "Antas Akademiko",
  "Type of Paper": "Uri ng Papel",
  "High School": "High School",
  "College": "Kolehiyo",
  "Short Film": "Short Film",
  "University": "Unibersidad",
  "Masters": "Masters",
  "Custom": "Custom",
  "Tiktok Video": "Tiktok Video",
  "Movie": "Pelikula",
  "Expository": "Expository",
  "Argumentative": "Argumentative",
  "Narrative": "Naratibo",
  "Descriptive": "Deskriptibo",
  "We're sorry to hear that 😔": "Ikinalulungkot namin iyan 😔",
  "We'll try to improve 🙁": "Susubukan naming mapabuti 🙁",
  "Thanks for your feedback 🙂": "Salamat sa iyong feedback 🙂",
  "Great! We're glad you like it 😊":
      "Magaling! Masaya kami na nagustuhan mo 😊",
  "Awesome! Thank you so much! 🎉": "Ang galing! Maraming salamat! 🎉",
  "Maybe Later": "Siguro Mamaya",
  "Tap a star to rate your experience":
      "Mag-tap ng bituin para i-rate ang iyong karanasan",
  "Enjoying AI Math Solver?": "Nae-enjoy mo ba ang AI Math Solver?",
  "Thank you for rating us": "Salamat sa pag-rate sa amin",
  "Submit Rating": "Isumite ang Rating",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Nae-enjoy mo ba ang AI Story Generator?",
  AppKeys.arabic: "Arabic",
  AppKeys.chinese: "Chinese",
  AppKeys.english: "English",
  AppKeys.french: "French",
  AppKeys.german: "German",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesian",
  AppKeys.japanese: "Japanese",
  AppKeys.korean: "Korean",
  AppKeys.portuguese: "Portuguese",
  AppKeys.russian: "Russian",
  AppKeys.spanish: "Spanish",
  AppKeys.turkish: "Turkish",
  'Download As': 'I-download Bilang',
  'Choose format to download': 'Pumili ng format para i-download',
  'Text File': 'Text File',
  'PDF File': 'PDF File',
  'Copy': 'Kopyahin',
  'Share': 'I-share',
  'Text copied!': 'Nakopya ang teksto!',
  'PDF saved successfully!': 'Matagumpay na na-save ang PDF!',
  'Error creating PDF: Please try again':
      'Error sa paggawa ng PDF: Mangyaring subukan muli',
  'Character Story': 'Kwento ng Karakter',
  'Character Details': 'Detalye ng Karakter',
  'Character Name': 'Pangalan ng Karakter',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Edad (hal., 25, Young Adult, Sinaunang)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalidad (hal., matapang, mahiyain, tuso)',
  'Role (e.g., Hero, Villain, Mentor)':
      'Papel (hal., Bayani, Kontrabida, Mentor)',
  'Additional Details (optional)': 'Karagdagang Detalye (opsyonal)',
  'Output Style': 'Istilo ng Output',
  'Generate Character': 'Gumawa ng Karakter',
  'Please enter character name': 'Mangyaring ilagay ang pangalan ng karakter',
  'Please enter character role': 'Mangyaring ilagay ang papel ng karakter',
  'Detailed': 'Detalyado',
  'Brief': 'Maikli',
  'Elaborate': 'Detalyado',
  'Create detailed character backstories':
      'Lumikha ng detalyadong backstory ng karakter',
  'Create Character': 'Lumikha ng Karakter',
  'Transform and improve your existing stories':
      'I-transform at pagbutihin ang iyong mga kwento',
  'Rewrite Now': 'Isulat Muli Ngayon',
  'Generate catchy titles for your stories':
      'Gumawa ng mga nakakaakit na pamagat para sa iyong mga kwento',
  'Generate Titles': 'Gumawa ng mga Pamagat',
  'Rewrite Story': 'Isulat Muli ang Kwento',
  'Paste Your Story': 'I-paste ang Iyong Kwento',
  'Paste your story here to rewrite...':
      'I-paste ang iyong kwento dito para isulat muli...',
  'Select Tone': 'Pumili ng Tono',
  'Rewrite Style': 'Istilo ng Pagsusulat Muli',
  'Output Length': 'Haba ng Output',
  'Please paste your story': 'Mangyaring i-paste ang iyong kwento',
  'Story is too short. Please provide more content.':
      'Masyado maikli ang kwento. Mangyaring magbigay ng mas maraming nilalaman.',
  'Same': 'Pareho',
  'More Dramatic': 'Mas Dramatiko',
  'More Humorous': 'Mas Nakakatawa',
  'More Emotional': 'Mas Emosyonal',
  'More Suspenseful': 'Mas Nakakaintriga',
  'Lighter': 'Mas Magaan',
  'Improved': 'Pinahusay',
  'Simplified': 'Pinasimple',
  'More Descriptive': 'Mas Deskriptibo',
  'More Dialogue': 'Mas Maraming Diyalogo',
  'More Action': 'Mas Maraming Aksyon',
  'Literary': 'Literaryo',
  'Shorter': 'Mas Maikli',
  'Longer': 'Mas Mahaba',
  'Much Longer': 'Mas Mahabang-mahaba',
  'Title Generator': 'Title Generator',
  'Story/Book Topic': 'Paksa ng Kwento/Aklat',
  'Keywords (Optional)': 'Mga Keyword (Opsyonal)',
  'Describe your story topic or theme...':
      'Ilarawan ang paksa o tema ng iyong kwento...',
  'e.g., magic, dragon, adventure': 'hal., mahika, dragon, pakikipagsapalaran',
  'Title For': 'Pamagat Para sa',
  'Title Style': 'Istilo ng Pamagat',
  "Adventure": "Pakikipagsapalaran",
  'Number of Titles': 'Bilang ng mga Pamagat',
  'Book': 'Aklat',
  'Short Story': 'Maikling Kwento',
  'Novel': 'Nobela',
  'Chapter': 'Kabanata',
  'Series': 'Serye',
  'Simple': 'Simple',
  'Mysterious': 'Misteryoso',
  'Dramatic': 'Dramatiko',
  'Catchy': 'Nakakaakit',
  'Poetic': 'Patula',
  'Kids': 'Mga Bata',
  'Blog Writer': 'Manunulat ng Blog',
  'Blog Topic': 'Paksa ng Blog',
  'Target Keywords': 'Target na mga Keyword',
  'Target Audience (Optional)': 'Target na Audience (Opsyonal)',
  'Enter your blog topic or title...':
      'Ilagay ang paksa o pamagat ng iyong blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'hal., AI writing, content marketing, SEO tips',
  'e.g., small business owners, bloggers':
      'hal., mga may-ari ng maliit na negosyo, mga blogger',
  'Article Type': 'Uri ng Artikulo',
  'Writing Tone': 'Tono ng Pagsulat',
  'Article Length': 'Haba ng Artikulo',
  'SEO Options': 'Mga Opsyon sa SEO',
  'Include Meta Description': 'Isama ang Meta Description',
  'Include Keyword Suggestions': 'Isama ang mga Keyword Suggestion',
  'Include FAQs Section': 'Isama ang FAQs Section',
  'Please enter a blog topic': 'Mangyaring maglagay ng paksa ng blog',
  'Generate Blog': 'Gumawa ng Blog',
  'SEO optimized articles with keywords':
      'SEO optimized na mga artikulo na may keyword',
  'Write Blog': 'Sumulat ng Blog',
  'SEO Article': 'SEO Artikulo',
  'How-To Guide': 'Gabay sa Paano',
  'Listicle': 'Listicle',
  'Product Review': 'Review ng Produkto',
  'Opinion Piece': 'Artikulong Opinyon',
  'News Article': 'Artikulong Balita',
  'Professional': 'Propesyonal',
  'Casual': 'Kaswal',
  'Informative': 'Impormatibo',
  'Persuasive': 'Mapanghikayat',
  'Friendly': 'Magiliw',
  'Authoritative': 'May Awtoridad',
  'Short (500-800)': 'Maikli (500-800)',
  'Medium (800-1500)': 'Katamtaman (800-1500)',
  'Long (1500-2500)': 'Mahaba (1500-2500)',
  'Detailed (2500+)': 'Detalyado (2500+)',
  'YouTube Script': 'YouTube Script',
  'Video Topic': 'Paksa ng Video',
  'Key Points (Optional)': 'Mga Pangunahing Punto (Opsyonal)',
  'What is your video about?': 'Ano ang tungkol sa iyong video?',
  'List key points to cover (optional)...':
      'Ilista ang mga pangunahing punto (opsyonal)...',
  'Video Duration': 'Tagal ng Video',
  'Script Options': 'Mga Opsyon ng Script',
  'Include Hook/Intro': 'Isama ang Hook/Intro',
  'Include Call-to-Action': 'Isama ang Call-to-Action',
  'Include Timestamps': 'Isama ang mga Timestamp',
  'Please enter a video topic': 'Mangyaring maglagay ng paksa ng video',
  'Generate Script': 'Gumawa ng Script',
  'Create scripts for videos & reels':
      'Gumawa ng mga script para sa mga video at reel',
  'Create Script': 'Gumawa ng Script',
  'Storytime': 'Oras ng Kwento',
  'Documentary': 'Dokumentaryo',
  'Short Reel': 'Maikling Reel',
  'Educational': 'Pang-edukasyon',
  'Review': 'Review',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Nakaka-engganyo',
  'Energetic': 'Masigla',
  'Calm': 'Mahinahon',
  'Funny': 'Nakakatawa',
  'Inspired': 'Inspirado',
  'Film Script': 'Film Script',
  'Stage Play': 'Stage Play',
  'Scene Breakdown': 'Paghahati ng Eksena',
  'Dialogue Only': 'Diyalogo Lamang',
  'Ad loading please wait..': 'Naglo-load ang ad mangyaring maghintay..',
  'Words:': 'Mga Salita:',
  'Reading:': 'Pagbasa:',
};
