import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> fr = {
  AppKeys.lblChooseLanguage: "Choisir la langue",
  "All": "Tout",
  "AI Story Generator": "Générateur d'histoires IA",
  "Story Generator": "Générateur d'histoires",
  "Essay Writer": "Rédacteur d'essais",
  "Essay length": "Longueur de l'essai",
  "Script Generator": "Générateur de scripts",
  "Create original stories in seconds":
      "Créez des histoires originales en quelques secondes",
  "Academic writing made simple": "Rédaction académique simplifiée",
  "Generate powerful scripts for any medium":
      "Générez des scripts puissants pour tout support",
  "Start Writing": "Commencer à écrire",
  "Create Now": "Créer maintenant",
  "Start Generating": "Commencer à générer",
  "Your Stories": "Vos histoires",
  "No stories yet": "Aucune histoire pour le moment",
  "Start creating your first story!":
      "Commencez à créer votre première histoire!",
  "Your Story Space Awaits": "Votre espace d'histoires vous attend",
  "Start your first story and see it appear here":
      "Commencez votre première histoire et regardez-la apparaître ici",
  "Language": "Langue",
  "Rate us": "Évaluez-nous",
  "Share us": "Partagez-nous",
  "Privacy Policy": "Politique de confidentialité",
  "Settings": "Paramètres",
  "Select Language": "Sélectionner la langue",
  "Dashboard": "Tableau de bord",
  "BENEFITS": "AVANTAGES",
  "Subscribe": "S'abonner",
  "Weekly": "Hebdomadaire",
  "Monthly": "Mensuel",
  "Yearly": "Annuel",
  "week": "semaine",
  "months": "mois",
  "year": "année",
  "Terms & Condition": "Termes et conditions",
  "No Commitment. Cancel anytime": "Aucun engagement. Annulez à tout moment",
  "No Payment Now": "Aucun paiement maintenant",
  "3 days free": "3 jours gratuits",
  "Start your free trial": "Commencez votre essai gratuit",
  "More detailed answers": "Réponses plus détaillées",
  "Instant responds": "Réponses instantanées",
  "Text recognition": "Reconnaissance de texte",
  "Powered by AI": "Propulsé par l'IA",
  "Storytelleing": "Narration",
  ' Power': "Puissance",
  "Unlock your \nFill ": "Débloquez votre \nFill",
  "Your History": "Votre historique",
  "Terms and Conditions": "Termes et conditions",
  "Short": "Court",
  "Medium": "Moyen",
  "Long": "Long",
  "Length": "Longueur",
  "Describe your topic...": "Décrivez votre sujet...",
  "Set Creativity": "Définir la créativité",
  "Standard": "Standard",
  "Creative": "Créatif",
  "Complex": "Complexe",
  "Select Genre": "Sélectionner le genre",
  "Fantasy": "Fantaisie",
  "Mystery": "Mystère",
  "Thriller": "Thriller",
  "Script Tone": "Ton du script",
  "Script Type": "Type de script",
  "Comedy": "Comédie",
  "Drama": "Drame",
  "Horror": "Horreur",
  "Action": "Action",
  "Romance": "Romance",
  "Go Premium": "Passer à Premium",
  "Unlock Everything": "Débloquer tout",
  "Unlimited Story Generation": "Génération d'histoires illimitée",
  "Write Longer & Detailed Essays":
      "Rédigez des essais plus longs et détaillés",
  "Advanced Script Writer": "Rédacteur de scripts avancé",
  "Unlock All Styles & Tones": "Débloquez tous les styles et tons",
  "No Word/Length Limit": "Sans limite de mots/longueur",
  "Remove All Ads": "Supprimer toutes les publicités",
  "3 days free": "3 jours gratuits",
  "Restore": "Restaurer",
  "YouTube Video": "Vidéo YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivationnel",
  "Advertisement": "Publicité",
  "Fairy Tale": "Conte de fées",
  "Sci-Fi": "Science-fiction",
  "Select Style": "Sélectionner le style",
  "Imaginative": "Imaginatif",
  "Innovative": "Innovant",
  "AI Story Writer": "Rédacteur d'histoires IA",
  "Generate": "Générer",
  "Please wait...": "Veuillez patienter...",
  "Result": "Résultat",
  "Regenerate": "Régénérer",
  "Download": "Télécharger",
  "Text copied to clipboard!": "Texte copié dans le presse-papiers!",
  "Please enter a topic": "Veuillez entrer un sujet",
  "Story Magic": "Magie des histoires",
  "Let AI bring your thoughts to a full story":
      "Laissez l'IA transformer vos pensées en une histoire complète",
  "Smart Scripts": "Scripts intelligents",
  "From concept to script—fast, easy, and creative":
      "Du concept au script—rapide, facile et créatif",
  "Perfect Essays": "Essais parfaits",
  "You have reached your free limit": "Vous avez atteint votre limite gratuite",
  "Donwload": "Téléchargements",
  "Press again to exit app": "Appuyez à nouveau pour quitter l'application",
  "Saved to files": "Fichier TXT enregistré avec succès!",
  "Error: Please try again": "Erreur: Veuillez réessayer",
  "Subscription expired": "Abonnement expiré",
  "Purchase cancelled": "Achat annulé",
  "Purchase failed": "Échec de l'achat",
  "Restore failed": "Échec de la restauration",
  "Purchase Successful!": "Achat réussi!",
  "Short (200-500 words)": "Court (200-500 mots)",
  "Medium (500-1000 words)": "Moyen (500-1000 mots)",
  "Large (1000+ words)": "Grand (1000+ mots)",
  "Academic Level": "Niveau académique",
  "Type of Paper": "Type de papier",
  "High School": "Lycée",
  "College": "Collège",
  "Short Film": "Court métrage",
  "University": "Université",
  "Masters": "Maîtrise",
  "Custom": "Personnalisé",
  "YouTube Video": "Vidéo YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Vidéo Tiktok",
  "Movie": "Film",
  "Expository": "Explicatif",
  "Argumentative": "Argumentatif",
  "Narrative": "Narratif",
  "Descriptive": "Descriptif",
  "We're sorry to hear that 😔": "Nous sommes désolés de l'entendre 😔",
  "We'll try to improve 🙁": "Nous essaierons de nous améliorer 🙁",
  "Thanks for your feedback 🙂": "Merci pour votre avis 🙂",
  "Great! We're glad you like it 😊":
      "Génial ! Nous sommes ravis que cela vous plaise 😊",
  "Awesome! Thank you so much! 🎉": "Super ! Merci beaucoup ! 🎉",
  "Maybe Later": "Peut-être plus tard",
  "Tap a star to rate your experience":
      "Appuyez sur une étoile pour évaluer votre expérience",
  "Enjoying AI Math Solver?": "Aimez-vous AI Math Solver ?",
  "Thank you for rating us": "Merci de nous avoir notés",
  "Submit Rating": "Soumettre l’évaluation",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Aimez-vous le Générateur d'Histoires IA ?",
  AppKeys.arabic: "Arabe",
  AppKeys.chinese: "Chinois",
  AppKeys.english: "Anglais",
  AppKeys.french: "Français",
  AppKeys.german: "Allemand",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonésien",
  AppKeys.japanese: "Japonais",
  AppKeys.korean: "Coréen",
  AppKeys.portuguese: "Portugais",
  AppKeys.russian: "Russe",
  AppKeys.spanish: "Espagnol",
  AppKeys.turkish: "Turc",
};
