import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> gl = {
  AppKeys.lblChooseLanguage: "Escoller idioma",
  "All": "Todos",
  "AI Story Generator": "Xerador de historias IA",
  "Story Generator": "Xerador de historias",
  "Essay Writer": "Escritor de ensaios",
  "Essay length": "Lonxitude do ensaio",
  "Script Generator": "Xerador de guións",
  "Create original stories in seconds": "Crea historias orixinais en segundos",
  "Academic writing made simple": "Escritura académica simplificada",
  "Generate powerful scripts for any medium":
      "Xera guións potentes para calquera medio",
  "Start Writing": "Comezar a escribir",
  "Create Now": "Crear agora",
  "Start Generating": "Comezar a xerar",
  "Your Stories": "As túas historias",
  "No stories yet": "Aínda non hai historias",
  "Start creating your first story!": "Comeza a crear a túa primeira historia!",
  "Your Story Space Awaits": "O teu espazo de historias agárdache",
  "Start your first story and see it appear here":
      "Comeza a túa primeira historia e míraa aparecer aquí",
  "Language": "Idioma",
  "Rate us": "Valóranos",
  "Share us": "Compártenos",
  "Privacy Policy": "Política de privacidade",
  "Settings": "Configuración",
  "Select Language": "Seleccionar idioma",
  "Dashboard": "Panel",
  "BENEFITS": "BENEFICIOS",
  "Subscribe": "Subscribirse",
  "Weekly": "Semanal",
  "Monthly": "Mensual",
  "Yearly": "Anual",
  "week": "semana",
  "months": "meses",
  "year": "ano",
  "Terms & Condition": "Termos e condicións",
  "No Commitment. Cancel anytime":
      "Sen compromiso. Cancela en calquera momento",
  "No Payment Now": "Sen pago agora",
  "3 days free": "3 días gratis",
  "Start your free trial": "Comeza a túa proba gratuíta",
  "More detailed answers": "Respostas máis detalladas",
  "Instant responds": "Respostas instantáneas",
  "Text recognition": "Recoñecemento de texto",
  "Powered by AI": "Impulsado por IA",
  "Storytelleing": "Narración",
  ' Power': " Poder",
  "Unlock your \nFill ": "Desbloquea o teu \nFill ",
  "Your History": "O teu historial",
  "Terms and Conditions": "Termos e condicións",
  "Short": "Curto",
  "Medium": "Medio",
  "Long": "Longo",
  "Length": "Lonxitude",
  "Describe your topic...": "Describe o teu tema...",
  "Set Creativity": "Axustar creatividade",
  "Standard": "Estándar",
  "Creative": "Creativo",
  "Complex": "Complexo",
  "Select Genre": "Seleccionar xénero",
  "Fantasy": "Fantasía",
  "Mystery": "Misterio",
  "Thriller": "Suspense",
  "Script Tone": "Ton do guión",
  "Script Type": "Tipo de guión",
  "Comedy": "Comedia",
  "Drama": "Drama",
  "Horror": "Terror",
  "Action": "Acción",
  "Romance": "Romance",
  "Go Premium": "Pasa a Premium",
  "Unlock Everything": "Desbloquea todo",
  "Unlimited Story Generation": "Xeración ilimitada de historias",
  "Write Longer & Detailed Essays": "Escribe ensaios máis longos e detallados",
  "Advanced Script Writer": "Escritor de guións avanzado",
  "Unlock All Styles & Tones": "Desbloquea todos os estilos e tons",
  "No Word/Length Limit": "Sen límite de palabras/lonxitude",
  "Remove All Ads": "Eliminar todos os anuncios",
  "Restore": "Restaurar",
  "YouTube Video": "Vídeo de YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivacional",
  "Advertisement": "Anuncio",
  "Fairy Tale": "Conto de fadas",
  "Sci-Fi": "Ciencia ficción",
  "Select Style": "Seleccionar estilo",
  "Imaginative": "Imaxinativo",
  "Innovative": "Innovador",
  "AI Story Writer": "Escritor de historias IA",
  "Generate": "Xerar",
  "Please wait...": "Por favor agarda...",
  "Result": "Resultado",
  "Regenerate": "Rexenerar",
  "Download": "Descargar",
  "Text copied to clipboard!": "Texto copiado ao portapapeis!",
  "Please enter a topic": "Por favor introduce un tema",
  "Story Magic": "Maxia de historias",
  "Let AI bring your thoughts to a full story":
      "Deixa que a IA converta os teus pensamentos nunha historia completa",
  "Smart Scripts": "Guións intelixentes",
  "From concept to script—fast, easy, and creative":
      "Do concepto ao guión—rápido, fácil e creativo",
  "Perfect Essays": "Ensaios perfectos",
  "You have reached your free limit": "Alcanzaches o teu límite gratuíto",
  "Donwload": "Descargar",
  "Press again to exit app": "Preme de novo para saír da app",
  "Saved to files": "Ficheiro TXT gardado con éxito!",
  "Error: Please try again": "Erro: Por favor tenta de novo",
  "Subscription expired": "Subscrición expirada",
  "Purchase cancelled": "Compra cancelada",
  "Purchase failed": "Compra fallida",
  "Restore failed": "Restauración fallida",
  "Purchase Successful!": "Compra exitosa!",
  "Short (200-500 words)": "Curto (200-500 palabras)",
  "Medium (500-1000 words)": "Medio (500-1000 palabras)",
  "Large (1000+ words)": "Grande (1000+ palabras)",
  "Academic Level": "Nivel académico",
  "Type of Paper": "Tipo de traballo",
  "High School": "Instituto",
  "College": "Universidade",
  "Short Film": "Curtametraxe",
  "University": "Universidade",
  "Masters": "Máster",
  "Custom": "Personalizado",
  "Tiktok Video": "Vídeo de TikTok",
  "Movie": "Película",
  "Expository": "Expositivo",
  "Argumentative": "Argumentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descritivo",
  "We're sorry to hear that 😔": "Sentímolo escoitar iso 😔",
  "We'll try to improve 🙁": "Tentaremos mellorar 🙁",
  "Thanks for your feedback 🙂": "Grazas pola túa opinión 🙂",
  "Great! We're glad you like it 😊": "Xenial! Alegramos de que che guste 😊",
  "Awesome! Thank you so much! 🎉": "Incríble! Moitas grazas! 🎉",
  "Maybe Later": "Quizais despois",
  "Tap a star to rate your experience":
      "Toca unha estrela para valorar a túa experiencia",
  "Enjoying AI Math Solver?": "Estás gozando do solucionador de mates IA?",
  "Thank you for rating us": "Grazas por valorarnos",
  "Submit Rating": "Enviar valoración",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Estás gozando do xerador de historias IA?",
  AppKeys.arabic: "Árabe",
  AppKeys.chinese: "Chinés",
  AppKeys.english: "Inglés",
  AppKeys.french: "Francés",
  AppKeys.german: "Alemán",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesio",
  AppKeys.japanese: "Xaponés",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Portugués",
  AppKeys.russian: "Ruso",
  AppKeys.spanish: "Español",
  AppKeys.turkish: "Turco",
  'Download As': 'Descargar como',
  'Choose format to download': 'Escolle o formato para descargar',
  'Text File': 'Ficheiro de texto',
  'PDF File': 'Ficheiro PDF',
  'Copy': 'Copiar',
  'Share': 'Compartir',
  'Text copied!': 'Texto copiado!',
  'PDF saved successfully!': 'PDF gardado con éxito!',
  'Error creating PDF: Please try again':
      'Erro ao crear PDF: Por favor tenta de novo',
  'Character Story': 'Historia do personaxe',
  'Character Details': 'Detalles do personaxe',
  'Character Name': 'Nome do personaxe',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Idade (ex., 25, Adulto novo, Antigo)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalidade (ex., valente, tímido, astuto)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (ex., Heroe, Vilán, Mentor)',
  'Additional Details (optional)': 'Detalles adicionais (opcional)',
  'Output Style': 'Estilo de saída',
  'Generate Character': 'Xerar personaxe',
  'Please enter character name': 'Por favor introduce o nome do personaxe',
  'Please enter character role': 'Por favor introduce o rol do personaxe',
  'Detailed': 'Detallado',
  'Brief': 'Breve',
  'Elaborate': 'Elaborado',
  'Create detailed character backstories':
      'Crea historias detalladas de personaxes',
  'Create Character': 'Crear personaxe',
  'Transform and improve your existing stories':
      'Transforma e mellora as túas historias existentes',
  'Rewrite Now': 'Reescribir agora',
  'Generate catchy titles for your stories':
      'Xera títulos atractivos para as túas historias',
  'Generate Titles': 'Xerar títulos',
  'Rewrite Story': 'Reescribir historia',
  'Paste Your Story': 'Pega a túa historia',
  'Paste your story here to rewrite...':
      'Pega a túa historia aquí para reescribir...',
  'Select Tone': 'Seleccionar ton',
  'Rewrite Style': 'Estilo de reescritura',
  'Output Length': 'Lonxitude de saída',
  'Please paste your story': 'Por favor pega a túa historia',
  'Story is too short. Please provide more content.':
      'A historia é moi curta. Por favor proporciona máis contido.',
  'Same': 'Igual',
  'More Dramatic': 'Máis dramático',
  'More Humorous': 'Máis humorístico',
  'More Emotional': 'Máis emocional',
  'More Suspenseful': 'Máis suspense',
  'Lighter': 'Máis lixeiro',
  'Improved': 'Mellorado',
  'Simplified': 'Simplificado',
  'More Descriptive': 'Máis descritivo',
  'More Dialogue': 'Máis diálogo',
  'More Action': 'Máis acción',
  'Literary': 'Literario',
  'Shorter': 'Máis curto',
  'Longer': 'Máis longo',
  'Much Longer': 'Moito máis longo',
  'Title Generator': 'Xerador de títulos',
  'Story/Book Topic': 'Tema de historia/libro',
  'Keywords (Optional)': 'Palabras clave (opcional)',
  'Describe your story topic or theme...': 'Describe o tema da túa historia...',
  'e.g., magic, dragon, adventure': 'ex., maxia, dragón, aventura',
  'Title For': 'Título para',
  'Title Style': 'Estilo de título',
  "Adventure": "Aventura",
  'Number of Titles': 'Número de títulos',
  'Book': 'Libro',
  'Short Story': 'Conto curto',
  'Novel': 'Novela',
  'Chapter': 'Capítulo',
  'Series': 'Serie',
  'Simple': 'Simple',
  'Mysterious': 'Misterioso',
  'Dramatic': 'Dramático',
  'Catchy': 'Atractivo',
  'Poetic': 'Poético',
  'Kids': 'Nenos',
  'Blog Writer': 'Escritor de blog',
  'Blog Topic': 'Tema do blog',
  'Target Keywords': 'Palabras clave obxectivo',
  'Target Audience (Optional)': 'Público obxectivo (opcional)',
  'Enter your blog topic or title...':
      'Introduce o tema ou título do teu blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'ex., escritura IA, marketing de contido, consellos SEO',
  'e.g., small business owners, bloggers':
      'ex., donos de pequenos negocios, blogueiros',
  'Article Type': 'Tipo de artigo',
  'Writing Tone': 'Ton de escritura',
  'Article Length': 'Lonxitude do artigo',
  'SEO Options': 'Opcións SEO',
  'Include Meta Description': 'Incluír meta descrición',
  'Include Keyword Suggestions': 'Incluír suxestións de palabras clave',
  'Include FAQs Section': 'Incluír sección de preguntas frecuentes',
  'Please enter a blog topic': 'Por favor introduce un tema de blog',
  'Generate Blog': 'Xerar blog',
  'SEO optimized articles with keywords':
      'Artigos optimizados para SEO con palabras clave',
  'Write Blog': 'Escribir blog',
  'SEO Article': 'Artigo SEO',
  'How-To Guide': 'Guía paso a paso',
  'Listicle': 'Listicle',
  'Product Review': 'Recensión de produto',
  'Opinion Piece': 'Artigo de opinión',
  'News Article': 'Artigo de noticias',
  'Professional': 'Profesional',
  'Casual': 'Casual',
  'Informative': 'Informativo',
  'Persuasive': 'Persuasivo',
  'Friendly': 'Amigable',
  'Authoritative': 'Autoritativo',
  'Short (500-800)': 'Curto (500-800)',
  'Medium (800-1500)': 'Medio (800-1500)',
  'Long (1500-2500)': 'Longo (1500-2500)',
  'Detailed (2500+)': 'Detallado (2500+)',
  'YouTube Script': 'Guión de YouTube',
  'Video Topic': 'Tema do vídeo',
  'Key Points (Optional)': 'Puntos clave (opcional)',
  'What is your video about?': 'De que trata o teu vídeo?',
  'List key points to cover (optional)...':
      'Lista os puntos clave a cubrir (opcional)...',
  'Video Duration': 'Duración do vídeo',
  'Script Options': 'Opcións do guión',
  'Include Hook/Intro': 'Incluír gancho/introdución',
  'Include Call-to-Action': 'Incluír chamada á acción',
  'Include Timestamps': 'Incluír marcas de tempo',
  'Please enter a video topic': 'Por favor introduce un tema de vídeo',
  'Generate Script': 'Xerar guión',
  'Create scripts for videos & reels': 'Crea guións para vídeos e reels',
  'Create Script': 'Crear guión',
  'Storytime': 'Hora do conto',
  'Documentary': 'Documental',
  'Short Reel': 'Reel curto',
  'Educational': 'Educativo',
  'Review': 'Recensión',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Atractivo',
  'Energetic': 'Enérxico',
  'Calm': 'Tranquilo',
  'Funny': 'Divertido',
  'Inspired': 'Inspirado',
  'Film Script': 'Guión de película',
  'Stage Play': 'Obra de teatro',
  'Scene Breakdown': 'Desglose de escena',
  'Dialogue Only': 'Só diálogo',
  'Ad loading please wait..': 'Cargando anuncio, por favor agarda..',
  'Words:': 'Palabras:',
  'Reading:': 'Lectura:',
};
