import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> gu = {
  AppKeys.lblChooseLanguage: "ભાષા પસંદ કરો",
  "All": "બધા",
  "AI Story Generator": "AI વાર્તા જનરેટર",
  "Story Generator": "વાર્તા જનરેટર",
  "Essay Writer": "નિબંધ લેખક",
  "Essay length": "નિબંધની લંબાઈ",
  "Script Generator": "સ્ક્રિપ્ટ જનરેટર",
  "Create original stories in seconds": "સેકન્ડોમાં મૂળ વાર્તાઓ બનાવો",
  "Academic writing made simple": "શૈક્ષણિક લેખન સરળ બનાવ્યું",
  "Generate powerful scripts for any medium":
      "કોઈપણ માધ્યમ માટે શક્તિશાળી સ્ક્રિપ્ટ બનાવો",
  "Start Writing": "લખવાનું શરૂ કરો",
  "Create Now": "હવે બનાવો",
  "Start Generating": "જનરેટ કરવાનું શરૂ કરો",
  "Your Stories": "તમારી વાર્તાઓ",
  "No stories yet": "હજુ કોઈ વાર્તા નથી",
  "Start creating your first story!": "તમારી પહેલી વાર્તા બનાવવાનું શરૂ કરો!",
  "Your Story Space Awaits": "તમારી વાર્તાની જગ્યા તમારી રાહ જોઈ રહી છે",
  "Start your first story and see it appear here":
      "તમારી પહેલી વાર્તા શરૂ કરો અને તેને અહીં દેખાતી જુઓ",
  "Language": "ભાષા",
  "Rate us": "અમને રેટ કરો",
  "Share us": "અમને શેર કરો",
  "Privacy Policy": "ગોપનીયતા નીતિ",
  "Settings": "સેટિંગ્સ",
  "Select Language": "ભાષા પસંદ કરો",
  "Dashboard": "ડેશબોર્ડ",
  "BENEFITS": "ફાયદા",
  "Subscribe": "સબ્સ્ક્રાઇબ કરો",
  "Weekly": "સાપ્તાહિક",
  "Monthly": "માસિક",
  "Yearly": "વાર્ષિક",
  "week": "અઠવાડિયું",
  "months": "મહિના",
  "year": "વર્ષ",
  "Terms & Condition": "શરતો અને નિયમો",
  "No Commitment. Cancel anytime": "કોઈ પ્રતિબદ્ધતા નહીં. કોઈપણ સમયે રદ કરો",
  "No Payment Now": "હવે કોઈ ચુકવણી નહીં",
  "3 days free": "3 દિવસ મફત",
  "Start your free trial": "તમારું મફત ટ્રાયલ શરૂ કરો",
  "More detailed answers": "વધુ વિગતવાર જવાબો",
  "Instant responds": "તાત્કાલિક પ્રતિસાદ",
  "Text recognition": "ટેક્સ્ટ ઓળખ",
  "Powered by AI": "AI દ્વારા સંચાલિત",
  "Storytelleing": "વાર્તા કહેવું",
  ' Power': " શક્તિ",
  "Unlock your \nFill ": "તમારું \nFill અનલૉક કરો ",
  "Your History": "તમારો ઇતિહાસ",
  "Terms and Conditions": "શરતો અને નિયમો",
  "Short": "ટૂંકું",
  "Medium": "મધ્યમ",
  "Long": "લાંબું",
  "Length": "લંબાઈ",
  "Describe your topic...": "તમારા વિષયનું વર્ણન કરો...",
  "Set Creativity": "સર્જનાત્મકતા સેટ કરો",
  "Standard": "સ્ટાન્ડર્ડ",
  "Creative": "સર્જનાત્મક",
  "Complex": "જટિલ",
  "Select Genre": "શૈલી પસંદ કરો",
  "Fantasy": "કલ્પના",
  "Mystery": "રહસ્ય",
  "Thriller": "થ્રિલર",
  "Script Tone": "સ્ક્રિપ્ટ ટોન",
  "Script Type": "સ્ક્રિપ્ટ પ્રકાર",
  "Comedy": "કોમેડી",
  "Drama": "નાટક",
  "Horror": "ભયાનક",
  "Action": "એક્શન",
  "Romance": "રોમાન્સ",
  "Go Premium": "પ્રીમિયમ જાઓ",
  "Unlock Everything": "બધું અનલૉક કરો",
  "Unlimited Story Generation": "અમર્યાદિત વાર્તા જનરેશન",
  "Write Longer & Detailed Essays": "લાંબા અને વિગતવાર નિબંધ લખો",
  "Advanced Script Writer": "અદ્યતન સ્ક્રિપ્ટ લેખક",
  "Unlock All Styles & Tones": "બધી શૈલીઓ અને ટોન અનલૉક કરો",
  "No Word/Length Limit": "કોઈ શબ્દ/લંબાઈ મર્યાદા નહીં",
  "Remove All Ads": "બધી જાહેરાતો દૂર કરો",
  "Restore": "પુનઃસ્થાપિત કરો",
  "YouTube Video": "યુટ્યુબ વીડિયો",
  "Podcast": "પોડકાસ્ટ",
  "Reel": "રીલ",
  "Motivational": "પ્રેરણાદાયક",
  "Advertisement": "જાહેરાત",
  "Fairy Tale": "પરીકથા",
  "Sci-Fi": "વિજ્ઞાન કથા",
  "Select Style": "શૈલી પસંદ કરો",
  "Imaginative": "કલ્��નાશીલ",
  "Innovative": "નવીન",
  "AI Story Writer": "AI વાર્તા લેખક",
  "Generate": "જનરેટ કરો",
  "Please wait...": "કૃપા કરીને રાહ જુઓ...",
  "Result": "પરિણામ",
  "Regenerate": "ફરીથી જનરેટ કરો",
  "Download": "ડાઉનલોડ",
  "Text copied to clipboard!": "ટેક્સ્ટ ક્લિપબોર્ડમાં કૉપી થયો!",
  "Please enter a topic": "કૃપા કરીને એક વિષય દાખલ કરો",
  "Story Magic": "વાર્તા જાદુ",
  "Let AI bring your thoughts to a full story":
      "AI ને તમારા વિચારોને પૂરી વાર્તામાં ફેરવવા દો",
  "Smart Scripts": "સ્માર્ટ સ્ક્રિપ્ટ",
  "From concept to script—fast, easy, and creative":
      "વિચારથી સ્ક્રિપ્ટ સુધી—ઝડપી, સરળ અને સર્જનાત્મક",
  "Perfect Essays": "સંપૂર્ણ નિબંધ",
  "You have reached your free limit":
      "તમે તમારી મફત મર્યાદા સુધી પહોંચી ગયા છો",
  "Donwload": "ડાઉનલોડ",
  "Press again to exit app": "એપમાંથી બહાર નીકળવા ફરીથી દબાવો",
  "Saved to files": "TXT ફાઇલ સફળતાપૂર્વક સાચવવામાં આવી!",
  "Error: Please try again": "ભૂલ: કૃપા કરીને ફરીથી પ્રયાસ કરો",
  "Subscription expired": "સબ્સ્ક્રિપ્શન સમાપ્ત થઈ ગયું",
  "Purchase cancelled": "ખરીદી રદ કરવામાં આવી",
  "Purchase failed": "ખરીદી નિષ્ફળ",
  "Restore failed": "પુનઃસ્થાપના નિષ્ફળ",
  "Purchase Successful!": "ખરીદી સફળ!",
  "Short (200-500 words)": "ટૂંકું (200-500 શબ્દો)",
  "Medium (500-1000 words)": "મધ્યમ (500-1000 શબ્દો)",
  "Large (1000+ words)": "મોટું (1000+ શબ્દો)",
  "Academic Level": "શૈક્ષણિક સ્તર",
  "Type of Paper": "પેપરનો પ્રકાર",
  "High School": "હાઈ સ્કૂલ",
  "College": "કૉલેજ",
  "Short Film": "શૉર્ટ ફિલ્મ",
  "University": "યુનિવર્સિટી",
  "Masters": "માસ્ટર્સ",
  "Custom": "કસ્ટમ",
  "Tiktok Video": "ટિકટૉક વીડિયો",
  "Movie": "મૂવી",
  "Expository": "વ્યાખ્યાત્મક",
  "Argumentative": "તર્કસંગત",
  "Narrative": "કથાત્મક",
  "Descriptive": "વર્ણનાત્મક",
  "We're sorry to hear that 😔": "આ સાંભળીને અમને દુઃખ થયું 😔",
  "We'll try to improve 🙁": "અમે સુધારવાનો પ્રયાસ કરીશું 🙁",
  "Thanks for your feedback 🙂": "તમારા પ્રતિસાદ માટે આભાર 🙂",
  "Great! We're glad you like it 😊": "શાનદાર! અમને ખુશી છે કે તમને ગમ્યું 😊",
  "Awesome! Thank you so much! 🎉": "અદ્ભુત! ખૂબ ખૂબ આભાર! 🎉",
  "Maybe Later": "કદાચ પછી",
  "Tap a star to rate your experience":
      "તમારા અનુભવને રેટ કરવા માટે એક સ્ટાર પર ટેપ કરો",
  "Enjoying AI Math Solver?": "શું તમે AI મેથ સૉલ્વરનો આનંદ માણી રહ્યા છો?",
  "Thank you for rating us": "અમને રેટ કરવા બદલ આભાર",
  "Submit Rating": "રેટિંગ સબમિટ કરો",
  "Hindi": "હિન્દી",
  "Enjoying AI Story Generator?":
      "શું તમે AI વાર્તા જનરેટરનો આનંદ માણી રહ્યા છો?",
  AppKeys.arabic: "અરબી",
  AppKeys.chinese: "ચાઇનીઝ",
  AppKeys.english: "અંગ્રેજી",
  AppKeys.french: "ફ્રેન્ચ",
  AppKeys.german: "જર્મન",
  AppKeys.hindi: "હિન્દી",
  AppKeys.indonesian: "ઇન્ડોનેશિયન",
  AppKeys.japanese: "જાપાનીઝ",
  AppKeys.korean: "કોરિયન",
  AppKeys.portuguese: "પોર્ટુગીઝ",
  AppKeys.russian: "રશિયન",
  AppKeys.spanish: "સ્પેનિશ",
  AppKeys.turkish: "ટર્કિશ",
  'Download As': 'આ રૂપે ડાઉનલોડ કરો',
  'Choose format to download': 'ડાઉનલોડ માટે ફોર્મેટ પસંદ કરો',
  'Text File': 'ટેક્સ્ટ ફાઇલ',
  'PDF File': 'PDF ફાઇલ',
  'Copy': 'કૉપી',
  'Share': 'શેર કરો',
  'Text copied!': 'ટેક્સ્ટ કૉપી થયો!',
  'PDF saved successfully!': 'PDF સફળતાપૂર્વક સાચવવામાં આવ્યું!',
  'Error creating PDF: Please try again':
      'PDF બનાવવામાં ભૂલ: કૃપા કરીને ફરીથી પ્રયાસ કરો',
  'Character Story': 'પાત્રની વાર્તા',
  'Character Details': 'પાત્ર વિગતો',
  'Character Name': 'પાત્રનું નામ',
  'Age (e.g., 25, Young Adult, Ancient)':
      'ઉંમર (દા.ત., 25, યુવા પુખ્ત, પ્રાચીન)',
  'Personality (e.g., brave, shy, cunning)':
      'વ્યક્તિત્વ (દા.ત., બહાદુર, શરમાળ, ચતુર)',
  'Role (e.g., Hero, Villain, Mentor)':
      'ભૂમિકા (દા.ત., નાયક, ખલનાયક, માર્ગદર્શક)',
  'Additional Details (optional)': 'વધારાની વિગતો (વૈકલ્પિક)',
  'Output Style': 'આઉટપુટ શૈલી',
  'Generate Character': 'પાત્ર જનરેટ કરો',
  'Please enter character name': 'કૃપા કરીને પાત્રનું નામ દાખલ કરો',
  'Please enter character role': 'કૃપા કરીને પાત્રની ભૂમિકા દાખલ કરો',
  'Detailed': 'વિગતવાર',
  'Brief': 'સંક્ષિપ્ત',
  'Elaborate': 'વિસ્તૃત',
  'Create detailed character backstories': 'પાત્રની વિગતવાર પૃષ્ઠભૂમિ બનાવો',
  'Create Character': 'પાત્ર બનાવો',
  'Transform and improve your existing stories':
      'તમારી હાલની વાર્તાઓને રૂપાંતરિત અને સુધારો',
  'Rewrite Now': 'હવે ફરીથી લખો',
  'Generate catchy titles for your stories':
      'તમારી વાર્તાઓ માટે આકર્ષક શીર્ષકો બનાવો',
  'Generate Titles': 'શીર્ષકો બનાવો',
  'Rewrite Story': 'વાર્તા ફરીથી લખો',
  'Paste Your Story': 'તમારી વાર્તા પેસ્ટ કરો',
  'Paste your story here to rewrite...':
      'ફરીથી લખવા માટે તમારી વાર્તા અહીં પેસ્ટ કરો...',
  'Select Tone': 'ટોન પસંદ કરો',
  'Rewrite Style': 'પુનર્લેખન શૈલી',
  'Output Length': 'આઉટપુટ લંબાઈ',
  'Please paste your story': 'કૃપા કરીને તમારી વાર્તા પેસ્ટ કરો',
  'Story is too short. Please provide more content.':
      'વાર્તા ખૂબ ટૂંકી છે. કૃપા કરીને વધુ સામગ્રી આપો.',
  'Same': 'સમાન',
  'More Dramatic': 'વધુ નાટકીય',
  'More Humorous': 'વધુ હાસ્ય',
  'More Emotional': 'વધુ ભાવનાત્મક',
  'More Suspenseful': 'વધુ રોમાંચક',
  'Lighter': 'હળવું',
  'Improved': 'સુધારેલું',
  'Simplified': 'સરળીકૃત',
  'More Descriptive': 'વધુ વર્ણનાત્મક',
  'More Dialogue': 'વધુ સંવાદ',
  'More Action': 'વધુ એક્શન',
  'Literary': 'સાહિત્યિક',
  'Shorter': 'ટૂંકું',
  'Longer': 'લાંબું',
  'Much Longer': 'ઘણું લાંબું',
  'Title Generator': 'શીર્ષક જનરેટર',
  'Story/Book Topic': 'વાર્તા/પુસ્તક વિષય',
  'Keywords (Optional)': 'કીવર્ડ (વૈકલ્પિક)',
  'Describe your story topic or theme...':
      'તમારી વાર્તાનો વિષય અથવા થીમ વર્ણન કરો...',
  'e.g., magic, dragon, adventure': 'દા.ત., જાદુ, ડ્રેગન, સાહસ',
  'Title For': 'શીર્ષક માટે',
  'Title Style': 'શીર્ષક શૈલી',
  "Adventure": "સાહસ",
  'Number of Titles': 'શીર્ષકોની સંખ્યા',
  'Book': 'પુસ્તક',
  'Short Story': 'ટૂંકી વાર્તા',
  'Novel': 'નવલકથા',
  'Chapter': 'અધ્યાય',
  'Series': 'શ્રેણી',
  'Simple': 'સરળ',
  'Mysterious': 'રહસ્યમય',
  'Dramatic': 'નાટકીય',
  'Catchy': 'આકર્ષક',
  'Poetic': 'કાવ્યાત્મક',
  'Kids': 'બાળકો માટે',
  'Blog Writer': 'બ્લોગ લેખક',
  'Blog Topic': 'બ્લોગ વિષય',
  'Target Keywords': 'લક્ષ્ય કીવર્ડ',
  'Target Audience (Optional)': 'લક્ષ્ય દર્શક (વૈકલ્પિક)',
  'Enter your blog topic or title...':
      'તમારા બ્લોગનો વિષય અથવા શીર્ષક દાખલ કરો...',
  'e.g., AI writing, content marketing, SEO tips':
      'દા.ત., AI લેખન, સામગ્રી માર્કેટિંગ, SEO ટિપ્સ',
  'e.g., small business owners, bloggers':
      'દા.ત., નાના વ્યવસાયના માલિકો, બ્લોગર્સ',
  'Article Type': 'લેખ પ્રકાર',
  'Writing Tone': 'લેખન ટોન',
  'Article Length': 'લેખ લંબાઈ',
  'SEO Options': 'SEO વિકલ્પો',
  'Include Meta Description': 'મેટા વર્ણન સમાવો',
  'Include Keyword Suggestions': 'કીવર્ડ સૂચનો સમાવો',
  'Include FAQs Section': 'FAQ વિભાગ સમાવો',
  'Please enter a blog topic': 'કૃપા કરીને બ્લોગ વિષય દાખલ કરો',
  'Generate Blog': 'બ્લોગ જનરેટ કરો',
  'SEO optimized articles with keywords': 'કીવર્ડ સાથે SEO ઑપ્ટિમાઇઝ્ડ લેખો',
  'Write Blog': 'બ્લોગ લખો',
  'SEO Article': 'SEO લેખ',
  'How-To Guide': 'કેવી રીતે કરવું ગાઇડ',
  'Listicle': 'સૂચિ લેખ',
  'Product Review': 'ઉત્પાદન સમીક્ષા',
  'Opinion Piece': 'અભિપ્રાય લેખ',
  'News Article': 'સમાચાર લેખ',
  'Professional': 'વ્યાવસાયિક',
  'Casual': 'અનૌપચારિક',
  'Informative': 'માહિતીપ્રદ',
  'Persuasive': 'સમજાવટભર્યું',
  'Friendly': 'મૈત્રીપૂર્ણ',
  'Authoritative': 'અધિકૃત',
  'Short (500-800)': 'ટૂંકું (500-800)',
  'Medium (800-1500)': 'મધ્યમ (800-1500)',
  'Long (1500-2500)': 'લાંબું (1500-2500)',
  'Detailed (2500+)': 'વિગતવાર (2500+)',
  'YouTube Script': 'યુટ્યુબ સ્ક્રિપ્ટ',
  'Video Topic': 'વીડિયો વિષય',
  'Key Points (Optional)': 'મુખ્ય મુદ્દાઓ (વૈકલ્પિક)',
  'What is your video about?': 'તમારો વીડિયો શેના વિશે છે?',
  'List key points to cover (optional)...':
      'આવરી લેવાના મુખ્ય મુદ્દાઓની સૂચિ બનાવો (વૈકલ્પિક)...',
  'Video Duration': 'વીડિયો અવધિ',
  'Script Options': 'સ્ક્રિપ્ટ વિકલ્પો',
  'Include Hook/Intro': 'હૂક/પરિચય સમાવો',
  'Include Call-to-Action': 'કૉલ-ટુ-એક્શન સમાવો',
  'Include Timestamps': 'ટાઇમસ્ટેમ્પ સમાવો',
  'Please enter a video topic': 'કૃપા કરીને વીડિયો વિષય દાખલ કરો',
  'Generate Script': 'સ્ક્રિપ્ટ જનરેટ કરો',
  'Create scripts for videos & reels': 'વીડિયો અને રીલ્સ માટે સ્ક્રિપ્ટ બનાવો',
  'Create Script': 'સ્ક્રિપ્ટ બનાવો',
  'Storytime': 'વાર્તાનો સમય',
  'Documentary': 'ડોક્યુમેન્ટરી',
  'Short Reel': 'ટૂંકી રીલ',
  'Educational': 'શૈક્ષણિક',
  'Review': 'સમીક્ષા',
  'Tutorial': 'ટ્યુટોરિયલ',
  '< 1 min (Shorts)': '< 1 મિનિટ (શૉર્ટ્સ)',
  '1-3 min': '1-3 મિનિટ',
  '5-10 min': '5-10 મિનિટ',
  '10-20 min': '10-20 મિનિટ',
  '20+ min': '20+ મિનિટ',
  'Engaging': 'આકર્ષક',
  'Energetic': 'ઊર્જાવાન',
  'Calm': 'શાંત',
  'Funny': 'મજેદાર',
  'Inspired': 'પ્રેરિત',
  'Film Script': 'ફિલ્મ સ્ક્રિપ્ટ',
  'Stage Play': 'સ્ટેજ નાટક',
  'Scene Breakdown': 'દ્રશ્ય વિશ્લેષણ',
  'Dialogue Only': 'ફક્ત સંવાદ',
  'Ad loading please wait..': 'જાહેરાત લોડ થઈ રહી છે કૃપા કરીને રાહ જુઓ..',
  'Words:': 'શબ્દો:',
  'Reading:': 'વાંચન:',
};
