import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> he = {
  AppKeys.lblChooseLanguage: "בחר שפה",
  "All": "הכל",
  "AI Story Generator": "מחולל סיפורים AI",
  "Story Generator": "מחולל סיפורים",
  "Essay Writer": "כותב חיבורים",
  "Essay length": "אורך החיבור",
  "Script Generator": "מחולל תסריטים",
  "Create original stories in seconds": "צור סיפורים מקוריים בשניות",
  "Academic writing made simple": "כתיבה אקדמית בפשטות",
  "Generate powerful scripts for any medium": "צור תסריטים עוצמתיים לכל מדיום",
  "Start Writing": "התחל לכתוב",
  "Create Now": "צור עכשיו",
  "Start Generating": "התחל ליצור",
  "Your Stories": "הסיפורים שלך",
  "No stories yet": "אין עדיין סיפורים",
  "Start creating your first story!": "התחל ליצור את הסיפור הראשון שלך!",
  "Your Story Space Awaits": "מרחב הסיפורים שלך מחכה",
  "Start your first story and see it appear here":
      "התחל את הסיפור הראשון שלך וראה אותו מופיע כאן",
  "Language": "שפה",
  "Rate us": "דרג אותנו",
  "Share us": "שתף אותנו",
  "Privacy Policy": "מדיניות פרטיות",
  "Settings": "הגדרות",
  "Select Language": "בחר שפה",
  "Dashboard": "לוח בקרה",
  "BENEFITS": "יתרונות",
  "Subscribe": "הירשם",
  "Weekly": "שבועי",
  "Monthly": "חודשי",
  "Yearly": "שנתי",
  "week": "שבוע",
  "months": "חודשים",
  "year": "שנה",
  "Terms & Condition": "תנאים והגבלות",
  "No Commitment. Cancel anytime": "ללא התחייבות. בטל בכל עת",
  "No Payment Now": "ללא תשלום עכשיו",
  "3 days free": "3 ימים חינם",
  "Start your free trial": "התחל את תקופת הניסיון החינמית",
  "More detailed answers": "תשובות מפורטות יותר",
  "Instant responds": "תגובות מיידיות",
  "Text recognition": "זיהוי טקסט",
  "Powered by AI": "מונע על ידי AI",
  "Storytelleing": "סיפור סיפורים",
  ' Power': " כוח",
  "Unlock your \nFill ": "שחרר את \nFill שלך ",
  "Your History": "ההיסטוריה שלך",
  "Terms and Conditions": "תנאים והגבלות",
  "Short": "קצר",
  "Medium": "בינוני",
  "Long": "ארוך",
  "Length": "אורך",
  "Describe your topic...": "תאר את הנושא שלך...",
  "Set Creativity": "הגדר יצירתיות",
  "Standard": "סטנדרטי",
  "Creative": "יצירתי",
  "Complex": "מורכב",
  "Select Genre": "בחר ז'אנר",
  "Fantasy": "פנטזיה",
  "Mystery": "מסתורין",
  "Thriller": "מותחן",
  "Script Tone": "טון התסריט",
  "Script Type": "סוג התסריט",
  "Comedy": "קומדיה",
  "Drama": "דרמה",
  "Horror": "אימה",
  "Action": "אקשן",
  "Romance": "רומנטיקה",
  "Go Premium": "עבור לפרימיום",
  "Unlock Everything": "שחרר הכל",
  "Unlimited Story Generation": "יצירת סיפורים ללא הגבלה",
  "Write Longer & Detailed Essays": "כתוב חיבורים ארוכים ומפורטים יותר",
  "Advanced Script Writer": "כותב תסריטים מתקדם",
  "Unlock All Styles & Tones": "שחרר את כל הסגנונות והטונים",
  "No Word/Length Limit": "ללא הגבלת מילים/אורך",
  "Remove All Ads": "הסר את כל הפרסומות",
  "Restore": "שחזר",
  "YouTube Video": "סרטון YouTube",
  "Podcast": "פודקאסט",
  "Reel": "ריל",
  "Motivational": "מוטיבציוני",
  "Advertisement": "פרסומת",
  "Fairy Tale": "אגדה",
  "Sci-Fi": "מדע בדיוני",
  "Select Style": "בחר סגנון",
  "Imaginative": "דמיוני",
  "Innovative": "חדשני",
  "AI Story Writer": "כותב סיפורים AI",
  "Generate": "צור",
  "Please wait...": "אנא המתן...",
  "Result": "תוצאה",
  "Regenerate": "צור מחדש",
  "Download": "הורד",
  "Text copied to clipboard!": "הטקסט הועתק ללוח!",
  "Please enter a topic": "אנא הזן נושא",
  "Story Magic": "קסם הסיפורים",
  "Let AI bring your thoughts to a full story":
      "תן ל-AI להפוך את המחשבות שלך לסיפור מלא",
  "Smart Scripts": "תסריטים חכמים",
  "From concept to script—fast, easy, and creative":
      "מרעיון לתסריט—מהיר, קל ויצירתי",
  "Perfect Essays": "חיבורים מושלמים",
  "You have reached your free limit": "הגעת למגבלת החינם שלך",
  "Donwload": "הורד",
  "Press again to exit app": "לחץ שוב כדי לצאת מהאפליקציה",
  "Saved to files": "קובץ TXT נשמר בהצלחה!",
  "Error: Please try again": "שגיאה: אנא נסה שוב",
  "Subscription expired": "המנוי פג תוקף",
  "Purchase cancelled": "הרכישה בוטלה",
  "Purchase failed": "הרכישה נכשלה",
  "Restore failed": "השחזור נכשל",
  "Purchase Successful!": "הרכישה הצליחה!",
  "Short (200-500 words)": "קצר (200-500 מילים)",
  "Medium (500-1000 words)": "בינוני (500-1000 מילים)",
  "Large (1000+ words)": "גדול (1000+ מילים)",
  "Academic Level": "רמה אקדמית",
  "Type of Paper": "סוג העבודה",
  "High School": "תיכון",
  "College": "מכללה",
  "Short Film": "סרט קצר",
  "University": "אוניברסיטה",
  "Masters": "תואר שני",
  "Custom": "מותאם אישית",
  "Tiktok Video": "סרטון TikTok",
  "Movie": "סרט",
  "Expository": "הסברתי",
  "Argumentative": "טיעוני",
  "Narrative": "סיפורי",
  "Descriptive": "תיאורי",
  "We're sorry to hear that 😔": "מצטערים לשמוע את זה 😔",
  "We'll try to improve 🙁": "ננסה להשתפר 🙁",
  "Thanks for your feedback 🙂": "תודה על המשוב שלך 🙂",
  "Great! We're glad you like it 😊": "מעולה! שמחים שאהבת 😊",
  "Awesome! Thank you so much! 🎉": "מדהים! תודה רבה! 🎉",
  "Maybe Later": "אולי אחר כך",
  "Tap a star to rate your experience": "הקש על כוכב כדי לדרג את החוויה שלך",
  "Enjoying AI Math Solver?": "נהנה מפותר המתמטיקה AI?",
  "Thank you for rating us": "תודה שדירגת אותנו",
  "Submit Rating": "שלח דירוג",
  "Hindi": "הינדי",
  "Enjoying AI Story Generator?": "נהנה ממחולל הסיפורים AI?",
  AppKeys.arabic: "ערבית",
  AppKeys.chinese: "סינית",
  AppKeys.english: "אנגלית",
  AppKeys.french: "צרפתית",
  AppKeys.german: "גרמנית",
  AppKeys.hindi: "הינדי",
  AppKeys.indonesian: "אינדונזית",
  AppKeys.japanese: "יפנית",
  AppKeys.korean: "קוריאנית",
  AppKeys.portuguese: "פורטוגזית",
  AppKeys.russian: "רוסית",
  AppKeys.spanish: "ספרדית",
  AppKeys.turkish: "טורקית",
  'Download As': 'הורד בתור',
  'Choose format to download': 'בחר פורמט להורדה',
  'Text File': 'קובץ טקסט',
  'PDF File': 'קובץ PDF',
  'Copy': 'העתק',
  'Share': 'שתף',
  'Text copied!': 'הטקסט הועתק!',
  'PDF saved successfully!': 'PDF נשמר בהצלחה!',
  'Error creating PDF: Please try again': 'שגיאה ביצירת PDF: אנא נסה שוב',
  'Character Story': 'סיפור הדמות',
  'Character Details': 'פרטי הדמות',
  'Character Name': 'שם הדמות',
  'Age (e.g., 25, Young Adult, Ancient)': 'גיל (לדוגמה, 25, מבוגר צעיר, עתיק)',
  'Personality (e.g., brave, shy, cunning)':
      'אישיות (לדוגמה, אמיץ, ביישן, ערמומי)',
  'Role (e.g., Hero, Villain, Mentor)': 'תפקיד (לדוגמה, גיבור, נבל, מנטור)',
  'Additional Details (optional)': 'פרטים נוספים (אופציונלי)',
  'Output Style': 'סגנון פלט',
  'Generate Character': 'צור דמות',
  'Please enter character name': 'אנא הזן שם דמות',
  'Please enter character role': 'אנא הזן תפקיד דמות',
  'Detailed': 'מפורט',
  'Brief': 'קצר',
  'Elaborate': 'מורחב',
  'Create detailed character backstories': 'צור סיפורי רקע מפורטים לדמויות',
  'Create Character': 'צור דמות',
  'Transform and improve your existing stories':
      'שנה ושפר את הסיפורים הקיימים שלך',
  'Rewrite Now': 'כתוב מחדש עכשיו',
  'Generate catchy titles for your stories': 'צור כותרות קליטות לסיפורים שלך',
  'Generate Titles': 'צור כותרות',
  'Rewrite Story': 'כתוב סיפור מחדש',
  'Paste Your Story': 'הדבק את הסיפור שלך',
  'Paste your story here to rewrite...':
      'הדבק את הסיפור שלך כאן כדי לכתוב מחדש...',
  'Select Tone': 'בחר טון',
  'Rewrite Style': 'סגנון כתיבה מחדש',
  'Output Length': 'אורך הפלט',
  'Please paste your story': 'אנא הדבק את הסיפור שלך',
  'Story is too short. Please provide more content.':
      'הסיפור קצר מדי. אנא ספק תוכן נוסף.',
  'Same': 'זהה',
  'More Dramatic': 'יותר דרמטי',
  'More Humorous': 'יותר הומוריסטי',
  'More Emotional': 'יותר רגשי',
  'More Suspenseful': 'יותר מתח',
  'Lighter': 'קליל יותר',
  'Improved': 'משופר',
  'Simplified': 'מפושט',
  'More Descriptive': 'יותר תיאורי',
  'More Dialogue': 'יותר דיאלוג',
  'More Action': 'יותר אקשן',
  'Literary': 'ספרותי',
  'Shorter': 'קצר יותר',
  'Longer': 'ארוך יותר',
  'Much Longer': 'ארוך הרבה יותר',
  'Title Generator': 'מחולל כותרות',
  'Story/Book Topic': 'נושא סיפור/ספר',
  'Keywords (Optional)': 'מילות מפתח (אופציונלי)',
  'Describe your story topic or theme...': 'תאר את נושא או ערכת הסיפור שלך...',
  'e.g., magic, dragon, adventure': 'לדוגמה, קסם, דרקון, הרפתקה',
  'Title For': 'כותרת עבור',
  'Title Style': 'סגנון כותרת',
  "Adventure": "הרפתקה",
  'Number of Titles': 'מספר כותרות',
  'Book': 'ספר',
  'Short Story': 'סיפור קצר',
  'Novel': 'רומן',
  'Chapter': 'פרק',
  'Series': 'סדרה',
  'Simple': 'פשוט',
  'Mysterious': 'מסתורי',
  'Dramatic': 'דרמטי',
  'Catchy': 'קליט',
  'Poetic': 'פואטי',
  'Kids': 'ילדים',
  'Blog Writer': 'כותב בלוג',
  'Blog Topic': 'נושא הבלוג',
  'Target Keywords': 'מילות מפתח יעד',
  'Target Audience (Optional)': 'קהל יעד (אופציונלי)',
  'Enter your blog topic or title...': 'הזן את נושא או כותרת הבלוג שלך...',
  'e.g., AI writing, content marketing, SEO tips':
      'לדוגמה, כתיבת AI, שיווק תוכן, טיפים לSEO',
  'e.g., small business owners, bloggers': 'לדוגמה, בעלי עסקים קטנים, בלוגרים',
  'Article Type': 'סוג מאמר',
  'Writing Tone': 'טון כתיבה',
  'Article Length': 'אורך מאמר',
  'SEO Options': 'אפשרויות SEO',
  'Include Meta Description': 'כלול תיאור מטא',
  'Include Keyword Suggestions': 'כלול הצעות מילות מפתח',
  'Include FAQs Section': 'כלול מדור שאלות נפוצות',
  'Please enter a blog topic': 'אנא הזן נושא בלוג',
  'Generate Blog': 'צור בלוג',
  'SEO optimized articles with keywords': 'מאמרים מותאמים לSEO עם מילות מפתח',
  'Write Blog': 'כתוב בלוג',
  'SEO Article': 'מאמר SEO',
  'How-To Guide': 'מדריך איך לעשות',
  'Listicle': 'רשימת מאמר',
  'Product Review': 'סקירת מוצר',
  'Opinion Piece': 'מאמר דעה',
  'News Article': 'מאמר חדשות',
  'Professional': 'מקצועי',
  'Casual': 'לא רשמי',
  'Informative': 'אינפורמטיבי',
  'Persuasive': 'משכנע',
  'Friendly': 'ידידותי',
  'Authoritative': 'סמכותי',
  'Short (500-800)': 'קצר (500-800)',
  'Medium (800-1500)': 'בינוני (800-1500)',
  'Long (1500-2500)': 'ארוך (1500-2500)',
  'Detailed (2500+)': 'מפורט (2500+)',
  'YouTube Script': 'תסריט YouTube',
  'Video Topic': 'נושא הסרטון',
  'Key Points (Optional)': 'נקודות מפתח (אופציונלי)',
  'What is your video about?': 'על מה הסרטון שלך?',
  'List key points to cover (optional)...':
      'רשום נקודות מפתח לכסות (אופציונלי)...',
  'Video Duration': 'משך הסרטון',
  'Script Options': 'אפשרויות תסריט',
  'Include Hook/Intro': 'כלול פתיח/הקדמה',
  'Include Call-to-Action': 'כלול קריאה לפעולה',
  'Include Timestamps': 'כלול חותמות זמן',
  'Please enter a video topic': 'אנא הזן נושא סרטון',
  'Generate Script': 'צור תסריט',
  'Create scripts for videos & reels': 'צור תסריטים לסרטונים ורילס',
  'Create Script': 'צור תסריט',
  'Storytime': 'זמן סיפור',
  'Documentary': 'דוקומנטרי',
  'Short Reel': 'ריל קצר',
  'Educational': 'חינוכי',
  'Review': 'סקירה',
  'Tutorial': 'מדריך',
  '< 1 min (Shorts)': '< 1 דקה (שורטס)',
  '1-3 min': '1-3 דקות',
  '5-10 min': '5-10 דקות',
  '10-20 min': '10-20 דקות',
  '20+ min': '20+ דקות',
  'Engaging': 'מרתק',
  'Energetic': 'אנרגטי',
  'Calm': 'רגוע',
  'Funny': 'מצחיק',
  'Inspired': 'מעורר השראה',
  'Film Script': 'תסריט סרט',
  'Stage Play': 'הצגת במה',
  'Scene Breakdown': 'פירוט סצנות',
  'Dialogue Only': 'דיאלוג בלבד',
  'Ad loading please wait..': 'הפרסומת נטענת אנא המתן..',
  'Words:': 'מילים:',
  'Reading:': 'קריאה:',
};
