import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> hi = {
  AppKeys.lblChooseLanguage: "भाषा चुनें",
  "All": "सभी",
  "AI Story Generator": "एआई कहानी जनरेटर",
  "Story Generator": "कहानी जनरेटर",
  "Essay Writer": "निबंध लेखक",
  "Essay length": "निबंध की लंबाई",
  "Script Generator": "स्क्रिप्ट जनरेटर",
  "Create original stories in seconds": "सेकंडों में मूल कहानियां बनाएं",
  "Academic writing made simple": "शैक्षणिक लेखन को सरल बनाया गया",
  "Generate powerful scripts for any medium":
      "किसी भी माध्यम के लिए शक्तिशाली स्क्रिप्ट बनाएं",
  "Start Writing": "लिखना शुरू करें",
  "Create Now": "अभी बनाएं",
  "Start Generating": "जनरेट करना शुरू करें",
  "Your Stories": "आपकी कहानियां",
  "No stories yet": "अभी कोई कहानी नहीं",
  "Start creating your first story!": "अपनी पहली कहानी बनाना शुरू करें!",
  "Your Story Space Awaits": "आपकी कहानी की जगह आपका इंतजार कर रही है",
  "Start your first story and see it appear here":
      "अपनी पहली कहानी शुरू करें और इसे यहां दिखते हुए देखें",
  "Language": "भाषा",
  "Rate us": "हमें रेट करें",
  "Share us": "हमें साझा करें",
  "Privacy Policy": "गोपनीयता नीति",
  "Settings": "सेटिंग्स",
  "Select Language": "भाषा चुनें",
  "Dashboard": "डैशबोर्ड",
  "BENEFITS": "लाभ",
  "Subscribe": "सदस्यता लें",
  "Weekly": "साप्ताहिक",
  "Monthly": "मासिक",
  "Yearly": "वार्षिक",
  "week": "सप्ताह",
  "months": "महीने",
  "year": "साल",
  "Terms & Condition": "शर्तें और शर्तें",
  "No Commitment. Cancel anytime":
      "कोई प्रतिबद्धता नहीं। किसी भी समय रद्द करें",
  "No Payment Now": "अभी कोई भुगतान नहीं",
  "3 days free": "3 दिन मुक्त",
  "Start your free trial": "अपना मुफ्त परीक्षण शुरू करें",
  "More detailed answers": "अधिक विस्तृत उत्तर",
  "Instant responds": "तत्काल प्रतिक्रिया",
  "Text recognition": "पाठ पहचान",
  "Powered by AI": "एआई द्वारा संचालित",
  "Storytelleing": "कहानी कहना",
  ' Power': "शक्ति",
  "Unlock your \nFill ": "अपनी \nFill को अनलॉक करें",
  "Your History": "आपका इतिहास",
  "Terms and Conditions": "शर्तें और शर्तें",
  "Short": "छोटा",
  "Medium": "मध्यम",
  "Long": "लंबा",
  "Length": "लंबाई",
  "Describe your topic...": "अपने विषय का वर्णन करें...",
  "Set Creativity": "रचनात्मकता सेट करें",
  "Standard": "मानक",
  "Creative": "रचनात्मक",
  "Complex": "जटिल",
  "Select Genre": "शैली चुनें",
  "Fantasy": "कल्पना",
  "Mystery": "रहस्य",
  "Thriller": "थ्रिलर",
  "Script Tone": "स्क्रिप्ट टोन",
  "Script Type": "स्क्रिप्ट प्रकार",
  "Comedy": "कॉमेडी",
  "Drama": "नाटक",
  "Horror": "डरावना",
  "Action": "कार्रवाई",
  "Romance": "रोमांस",
  "Go Premium": "प्रीमियम जाएं",
  "Unlock Everything": "सब कुछ अनलॉक करें",
  "Unlimited Story Generation": "असीमित कहानी जनरेशन",
  "Write Longer & Detailed Essays": "लंबे और विस्तृत निबंध लिखें",
  "Advanced Script Writer": "उन्नत स्क्रिप्ट लेखक",
  "Unlock All Styles & Tones": "सभी शैलियों और टोन को अनलॉक करें",
  "No Word/Length Limit": "कोई शब्द/लंबाई सीमा नहीं",
  "Remove All Ads": "सभी विज्ञापन हटाएं",
  "Restore": "पुनर्स्थापित करें",
  "YouTube Video": "यूट्यूब वीडियो",
  "Podcast": "पॉडकास्ट",
  "Reel": "रील",
  "Motivational": "प्रेरणादायक",
  "Advertisement": "विज्ञापन",
  "Fairy Tale": "परी कथा",
  "Sci-Fi": "विज्ञान कथा",
  "Select Style": "शैली चुनें",
  "Imaginative": "कल्पनाशील",
  "Innovative": "अभिनव",
  "AI Story Writer": "एआई कहानी लेखक",
  "Generate": "जनरेट करें",
  "Please wait...": "कृपया प्रतीक्षा करें...",
  "Result": "परिणाम",
  "Regenerate": "पुनः जनरेट करें",
  "Download": "डाउनलोड",
  "Text copied to clipboard!": "पाठ क्लिपबोर्ड में कॉपी किया गया!",
  "Please enter a topic": "कृपया एक विषय दर्ज करें",
  "Story Magic": "कहानी जादू",
  "Let AI bring your thoughts to a full story":
      "एआई को अपने विचारों को एक पूरी कहानी में लाने दें",
  "Smart Scripts": "स्मार्ट स्क्रिप्ट",
  "From concept to script—fast, easy, and creative":
      "अवधारणा से स्क्रिप्ट तक—तेज़, आसान और रचनात्मक",
  "Perfect Essays": "परिपूर्ण निबंध",
  "You have reached your free limit": "आप अपनी मुफ्त सीमा पर पहुंच गए हैं",
  "Donwload": "डाउनलोड",
  "Press again to exit app": "ऐप से बाहर निकलने के लिए फिर से दबाएं",
  "Saved to files": "टीएक्सटी फाइल सफलतापूर्वक सहेजी गई!",
  "Error: Please try again": "त्रुटि: कृपया फिर से कोशिश करें",
  "Subscription expired": "सदस्यता समाप्त हो गई",
  "Purchase cancelled": "खरीद रद्द कर दी गई",
  "Purchase failed": "खरीद विफल",
  "Restore failed": "पुनर्स्थापन विफल",
  "Purchase Successful!": "खरीद सफल!",
  "Short (200-500 words)": "छोटा (200-500 शब्द)",
  "Medium (500-1000 words)": "मध्यम (500-1000 शब्द)",
  "Large (1000+ words)": "बड़ा (1000+ शब्द)",
  "Academic Level": "शैक्षणिक स्तर",
  "Type of Paper": "कागज का प्रकार",
  "High School": "उच्च विद्यालय",
  "College": "कॉलेज",
  "Short Film": "शॉर्ट फिल्म",
  "University": "विश्वविद्यालय",
  "Masters": "मास्टर्स",
  "Custom": "कस्टम",
  "Tiktok Video": "टिकटॉक वीडियो",
  "Movie": "फिल्म",
  "Expository": "व्याख्यात्मक",
  "Argumentative": "तर्कसंगत",
  "Narrative": "आख्यान",
  "Descriptive": "वर्णनात्मक",
  "We're sorry to hear that 😔": "यह सुनकर हमें खेद है 😔",
  "We'll try to improve 🙁": "हम सुधार करने की कोशिश करेंगे 🙁",
  "Thanks for your feedback 🙂": "आपकी प्रतिक्रिया के लिए धन्यवाद 🙂",
  "Great! We're glad you like it 😊":
      "शानदार! हमें खुशी है कि आप इसे पसंद करते हैं 😊",
  "Awesome! Thank you so much! 🎉": "बहुत बढ़िया! बहुत-बहुत धन्यवाद! 🎉",
  "Maybe Later": "शायद बाद में",
  "Tap a star to rate your experience":
      "अपने अनुभव को रेट करने के लिए एक सितारे पर टैप करें",
  "Enjoying AI Math Solver?": "क्या आप एआई मैथ सॉल्वर का आनंद ले रहे हैं?",
  "Thank you for rating us": "हमें रेट करने के लिए धन्यवाद",
  "Submit Rating": "रेटिंग जमा करें",
  "Hindi": "हिंदी",
  "Enjoying AI Story Generator?":
      "क्या आप एआई कहानी जनरेटर का आनंद ले रहे हैं?",
  AppKeys.arabic: "अरबी",
  AppKeys.chinese: "चीनी",
  AppKeys.english: "अंग्रेज़ी",
  AppKeys.french: "फ्रेंच",
  AppKeys.german: "जर्मन",
  AppKeys.hindi: "हिंदी",
  AppKeys.indonesian: "इंडोनेशियाई",
  AppKeys.japanese: "जापानी",
  AppKeys.korean: "कोरियाई",
  AppKeys.portuguese: "पुर्तगाली",
  AppKeys.russian: "रूसी",
  AppKeys.spanish: "स्पेनिश",
  AppKeys.turkish: "तुर्की",

  // New strings for download & actions
  'Download As': 'इस रूप में डाउनलोड करें',
  'Choose format to download': 'डाउनलोड के लिए प्रारूप चुनें',
  'Text File': 'टेक्स्ट फाइल',
  'PDF File': 'पीडीएफ फाइल',
  'Copy': 'कॉपी',
  'Share': 'साझा करें',
  'Text copied!': 'पाठ कॉपी किया गया!',
  'PDF saved successfully!': 'पीडीएफ सफलतापूर्वक सहेजा गया!',
  'Error creating PDF: Please try again':
      'पीडीएफ बनाते समय त्रुटि: कृपया फिर से कोशिश करें',

  // Character Story Tool
  'Character Story': 'पात्र की कहानी',
  'Character Details': 'पात्र विवरण',
  'Character Name': 'पात्र का नाम',
  'Age (e.g., 25, Young Adult, Ancient)':
      'आयु (उदाहरण के लिए, 25, युवा वयस्क, प्राचीन)',
  'Personality (e.g., brave, shy, cunning)':
      'व्यक्तित्व (उदाहरण के लिए, साहसी, शर्मीला, चतुर)',
  'Role (e.g., Hero, Villain, Mentor)':
      'भूमिका (उदाहरण के लिए, नायक, खलनायक, सलाहकार)',
  'Additional Details (optional)': 'अतिरिक्त विवरण (वैकल्पिक)',
  'Output Style': 'आउटपुट शैली',
  'Generate Character': 'पात्र जनरेट करें',
  'Please enter character name': 'कृपया पात्र का नाम दर्ज करें',
  'Please enter character role': 'कृपया पात्र की भूमिका दर्ज करें',
  'Detailed': 'विस्तृत',
  'Brief': 'संक्षिप्त',
  'Elaborate': 'विस्तृत',

  // Home Screen Tool Cards
  'Create detailed character backstories': 'पात्र की विस्तृत पृष्ठभूमि बनाएं',
  'Create Character': 'पात्र बनाएं',
  'Transform and improve your existing stories':
      'अपनी मौजूदा कहानियों को रूपांतरित और सुधारें',
  'Rewrite Now': 'अभी फिर से लिखें',
  'Generate catchy titles for your stories':
      'अपनी कहानियों के लिए आकर्षक शीर्षक बनाएं',
  'Generate Titles': 'शीर्षक बनाएं',

  // Rewrite Story Tool
  'Rewrite Story': 'कहानी फिर से लिखें',
  'Paste Your Story': 'अपनी कहानी पेस्ट करें',
  'Paste your story here to rewrite...':
      'फिर से लिखने के लिए अपनी कहानी यहां पेस्ट करें...',
  'Select Tone': 'टोन चुनें',
  'Rewrite Style': 'पुनर्लेखन शैली',
  'Output Length': 'आउटपुट लंबाई',
  'Please paste your story': 'कृपया अपनी कहानी पेस्ट करें',
  'Story is too short. Please provide more content.':
      'कहानी बहुत छोटी है। कृपया अधिक सामग्री प्रदान करें।',
  // Tone options
  'Same': 'समान',
  'More Dramatic': 'अधिक नाटकीय',
  'More Humorous': 'अधिक हास्य',
  'More Emotional': 'अधिक भावनात्मक',
  'More Suspenseful': 'अधिक रोचक',
  'Lighter': 'हल्का',
  // Style options
  'Improved': 'सुधारा हुआ',
  'Simplified': 'सरलीकृत',
  'More Descriptive': 'अधिक वर्णनात्मक',
  'More Dialogue': 'अधिक संवाद',
  'More Action': 'अधिक कार्रवाई',
  'Literary': 'साहित्यिक',
  // Length options
  'Shorter': 'छोटा',
  'Longer': 'लंबा',
  'Much Longer': 'बहुत लंबा',

  // Title Generator Tool
  'Title Generator': 'शीर्षक जनरेटर',
  'Story/Book Topic': 'कहानी/पुस्तक विषय',
  'Keywords (Optional)': 'कीवर्ड (वैकल्पिक)',
  'Describe your story topic or theme...':
      'अपने कहानी के विषय या थीम का वर्णन करें...',
  'e.g., magic, dragon, adventure': 'उदाहरण के लिए, जादू, ड्रैगन, रोमांच',
  'Title For': 'शीर्षक के लिए',
  'Title Style': 'शीर्षक शैली',
  "Adventure": "रोमांच",
  'Number of Titles': 'शीर्षकों की संख्या',
  // Type options
  'Book': 'पुस्तक',
  'Short Story': 'लघु कहानी',
  'Novel': 'उपन्यास',
  'Chapter': 'अध्याय',
  'Series': 'श्रृंखला',
  // Title Style options
  'Simple': 'सरल',
  'Mysterious': 'रहस्यमय',
  'Dramatic': 'नाटकीय',
  'Catchy': 'आकर्षक',
  'Poetic': 'काव्यात्मक',
  // Genre options
  'Kids': 'बच्चों के लिए',

  // Blog Writer Tool
  'Blog Writer': 'ब्लॉग लेखक',
  'Blog Topic': 'ब्लॉग विषय',
  'Target Keywords': 'लक्ष्य कीवर्ड',
  'Target Audience (Optional)': 'लक्ष्य दर्शक (वैकल्पिक)',
  'Enter your blog topic or title...':
      'अपने ब्लॉग का विषय या शीर्षक दर्ज करें...',
  'e.g., AI writing, content marketing, SEO tips':
      'उदाहरण के लिए, एआई लेखन, सामग्री विपणन, एसईओ टिप्स',
  'e.g., small business owners, bloggers':
      'उदाहरण के लिए, छोटे व्यवसायों के मालिक, ब्लॉगर',
  'Article Type': 'लेख का प्रकार',
  'Writing Tone': 'लेखन टोन',
  'Article Length': 'लेख की लंबाई',
  'SEO Options': 'एसईओ विकल्प',
  'Include Meta Description': 'मेटा विवरण शामिल करें',
  'Include Keyword Suggestions': 'कीवर्ड सुझाव शामिल करें',
  'Include FAQs Section': 'अक्सर पूछे जाने वाले प्रश्न अनुभाग शामिल करें',
  'Please enter a blog topic': 'कृपया एक ब्लॉग विषय दर्ज करें',
  'Generate Blog': 'ब्लॉग जनरेट करें',
  'SEO optimized articles with keywords': 'कीवर्ड के साथ एसईओ अनुकूलित लेख',
  'Write Blog': 'ब्लॉग लिखें',
  // Article Types
  'SEO Article': 'एसईओ लेख',
  'How-To Guide': 'कैसे करें गाइड',
  'Listicle': 'सूची लेख',
  'Product Review': 'उत्पाद समीक्षा',
  'Opinion Piece': 'विचार टुकड़ा',
  'News Article': 'समाचार लेख',
  // Blog Tones
  'Professional': 'व्यावसायिक',
  'Casual': 'आकस्मिक',
  'Informative': 'सूचनात्मक',
  'Persuasive': 'प्रेरक',
  'Friendly': 'मैत्रीपूर्ण',
  'Authoritative': 'प्राधिकृत',
  // Blog Lengths
  'Short (500-800)': 'छोटा (500-800)',
  'Medium (800-1500)': 'मध्यम (800-1500)',
  'Long (1500-2500)': 'लंबा (1500-2500)',
  'Detailed (2500+)': 'विस्तृत (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'यूट्यूब स्क्रिप्ट',
  'Video Topic': 'वीडियो विषय',
  'Key Points (Optional)': 'मुख्य बिंदु (वैकल्पिक)',
  'What is your video about?': 'आपका वीडियो किस बारे में है?',
  'List key points to cover (optional)...':
      'कवर करने के लिए मुख्य बिंदु सूची बनाएं (वैकल्पिक)...',
  'Video Duration': 'वीडियो अवधि',
  'Script Options': 'स्क्रिप्ट विकल्प',
  'Include Hook/Intro': 'हुक/परिचय शामिल करें',
  'Include Call-to-Action': 'कार्रवाई के लिए आह्वान शामिल करें',
  'Include Timestamps': 'समय चिह्न शामिल करें',
  'Please enter a video topic': 'कृपया एक वीडियो विषय दर्ज करें',
  'Generate Script': 'स्क्रिप्ट जनरेट करें',
  'Create scripts for videos & reels': 'वीडियो और रील्स के लिए स्क्रिप्ट बनाएं',
  'Create Script': 'स्क्रिप्ट बनाएं',
  // Script Types
  'Storytime': 'कहानी सुनाने का समय',
  'Documentary': 'डॉक्यूमेंटरी',
  'Short Reel': 'छोटी रील',
  'Educational': 'शैक्षणिक',
  'Review': 'समीक्षा',
  'Tutorial': 'ट्यूटोरियल',
  // Durations
  '< 1 min (Shorts)': '< 1 मिनट (शॉर्ट्स)',
  '1-3 min': '1-3 मिनट',
  '5-10 min': '5-10 मिनट',
  '10-20 min': '10-20 मिनट',
  '20+ min': '20+ मिनट',
  // Script Tones
  'Engaging': 'आकर्षक',
  'Energetic': 'ऊर्जावान',
  'Calm': 'शांत',
  'Funny': 'मजेदार',

  // Story Generator - Styles
  'Inspired': 'प्रेरित',

  // Script Writer - Script Tones (formats)
  'Film Script': 'फिल्म स्क्रिप्ट',
  'Stage Play': 'मंच नाटक',
  'Scene Breakdown': 'दृश्य विश्लेषण',
  'Dialogue Only': 'केवल संवाद',

  // Ad & UI
  'Ad loading please wait..': 'विज्ञापन लोड हो रहा है कृपया प्रतीक्षा करें..',

  // Word Counter & Reading Time
  'Words:': 'शब्द:',
  'Reading:': 'पढ़ना:',
};
