import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> hr = {
  AppKeys.lblChooseLanguage: "Odaberi jezik",
  "All": "Sve",
  "AI Story Generator": "AI generator priča",
  "Story Generator": "Generator priča",
  "Essay Writer": "Pisac eseja",
  "Essay length": "Duljina eseja",
  "Script Generator": "Generator scenarija",
  "Create original stories in seconds": "Stvorite originalne priče u sekundama",
  "Academic writing made simple": "Akademsko pisanje pojednostavljeno",
  "Generate powerful scripts for any medium":
      "Generirajte moćne scenarije za bilo koji medij",
  "Start Writing": "Počnite pisati",
  "Create Now": "Stvori sada",
  "Start Generating": "Počni generirati",
  "Your Stories": "Vaše priče",
  "No stories yet": "Još nema priča",
  "Start creating your first story!": "Počnite stvarati svoju prvu priču!",
  "Your Story Space Awaits": "Vaš prostor za priče čeka",
  "Start your first story and see it appear here":
      "Započnite svoju prvu priču i pogledajte kako se pojavljuje ovdje",
  "Language": "Jezik",
  "Rate us": "Ocijenite nas",
  "Share us": "Podijelite nas",
  "Privacy Policy": "Pravila privatnosti",
  "Settings": "Postavke",
  "Select Language": "Odaberi jezik",
  "Dashboard": "Nadzorna ploča",
  "BENEFITS": "PREDNOSTI",
  "Subscribe": "Pretplatite se",
  "Weekly": "Tjedno",
  "Monthly": "Mjesečno",
  "Yearly": "Godišnje",
  "week": "tjedan",
  "months": "mjeseci",
  "year": "godina",
  "Terms & Condition": "Uvjeti i odredbe",
  "No Commitment. Cancel anytime": "Bez obveze. Otkažite u bilo kojem trenutku",
  "No Payment Now": "Bez plaćanja sada",
  "3 days free": "3 dana besplatno",
  "Start your free trial": "Započnite besplatno probno razdoblje",
  "More detailed answers": "Detaljniji odgovori",
  "Instant responds": "Trenutni odgovori",
  "Text recognition": "Prepoznavanje teksta",
  "Powered by AI": "Pokreće AI",
  "Storytelleing": "Pripovijedanje",
  ' Power': " Moć",
  "Unlock your \nFill ": "Otključajte svoj \nFill ",
  "Your History": "Vaša povijest",
  "Terms and Conditions": "Uvjeti i odredbe",
  "Short": "Kratko",
  "Medium": "Srednje",
  "Long": "Dugo",
  "Length": "Duljina",
  "Describe your topic...": "Opišite svoju temu...",
  "Set Creativity": "Postavi kreativnost",
  "Standard": "Standardno",
  "Creative": "Kreativno",
  "Complex": "Složeno",
  "Select Genre": "Odaberi žanr",
  "Fantasy": "Fantazija",
  "Mystery": "Misterija",
  "Thriller": "Triler",
  "Script Tone": "Ton scenarija",
  "Script Type": "Vrsta scenarija",
  "Comedy": "Komedija",
  "Drama": "Drama",
  "Horror": "Horor",
  "Action": "Akcija",
  "Romance": "Romansa",
  "Go Premium": "Postani Premium",
  "Unlock Everything": "Otključaj sve",
  "Unlimited Story Generation": "Neograničeno generiranje priča",
  "Write Longer & Detailed Essays": "Pišite duže i detaljnije eseje",
  "Advanced Script Writer": "Napredni pisac scenarija",
  "Unlock All Styles & Tones": "Otključajte sve stilove i tonove",
  "No Word/Length Limit": "Bez ograničenja riječi/duljine",
  "Remove All Ads": "Ukloni sve oglase",
  "Restore": "Vrati",
  "YouTube Video": "YouTube video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivacijski",
  "Advertisement": "Oglas",
  "Fairy Tale": "Bajka",
  "Sci-Fi": "Znanstvena fantastika",
  "Select Style": "Odaberi stil",
  "Imaginative": "Maštovit",
  "Innovative": "Inovativan",
  "AI Story Writer": "AI pisac priča",
  "Generate": "Generiraj",
  "Please wait...": "Molimo pričekajte...",
  "Result": "Rezultat",
  "Regenerate": "Regeneriraj",
  "Download": "Preuzmi",
  "Text copied to clipboard!": "Tekst kopiran u međuspremnik!",
  "Please enter a topic": "Molimo unesite temu",
  "Story Magic": "Magija priča",
  "Let AI bring your thoughts to a full story":
      "Pustite AI da vaše misli pretvori u punu priču",
  "Smart Scripts": "Pametni scenariji",
  "From concept to script—fast, easy, and creative":
      "Od koncepta do scenarija—brzo, lako i kreativno",
  "Perfect Essays": "Savršeni eseji",
  "You have reached your free limit": "Dosegli ste svoju besplatnu granicu",
  "Donwload": "Preuzmi",
  "Press again to exit app": "Pritisnite ponovo za izlaz iz aplikacije",
  "Saved to files": "TXT datoteka uspješno spremljena!",
  "Error: Please try again": "Greška: Molimo pokušajte ponovo",
  "Subscription expired": "Pretplata je istekla",
  "Purchase cancelled": "Kupnja otkazana",
  "Purchase failed": "Kupnja neuspješna",
  "Restore failed": "Vraćanje neuspješno",
  "Purchase Successful!": "Kupnja uspješna!",
  "Short (200-500 words)": "Kratko (200-500 riječi)",
  "Medium (500-1000 words)": "Srednje (500-1000 riječi)",
  "Large (1000+ words)": "Veliko (1000+ riječi)",
  "Academic Level": "Akademska razina",
  "Type of Paper": "Vrsta rada",
  "High School": "Srednja škola",
  "College": "Fakultet",
  "Short Film": "Kratki film",
  "University": "Sveučilište",
  "Masters": "Magisterij",
  "Custom": "Prilagođeno",
  "Tiktok Video": "TikTok video",
  "Movie": "Film",
  "Expository": "Eksplanatorni",
  "Argumentative": "Argumentacijski",
  "Narrative": "Narativni",
  "Descriptive": "Opisni",
  "We're sorry to hear that 😔": "Žao nam je to čuti 😔",
  "We'll try to improve 🙁": "Pokušat ćemo se poboljšati 🙁",
  "Thanks for your feedback 🙂": "Hvala na povratnim informacijama 🙂",
  "Great! We're glad you like it 😊": "Sjajno! Drago nam je da vam se sviđa 😊",
  "Awesome! Thank you so much! 🎉": "Izvrsno! Puno hvala! 🎉",
  "Maybe Later": "Možda kasnije",
  "Tap a star to rate your experience":
      "Dodirnite zvijezdu za ocjenu vašeg iskustva",
  "Enjoying AI Math Solver?": "Uživate li u AI rješavaču matematike?",
  "Thank you for rating us": "Hvala što ste nas ocijenili",
  "Submit Rating": "Pošalji ocjenu",
  "Hindi": "Hindski",
  "Enjoying AI Story Generator?": "Uživate li u AI generatoru priča?",
  AppKeys.arabic: "Arapski",
  AppKeys.chinese: "Kineski",
  AppKeys.english: "Engleski",
  AppKeys.french: "Francuski",
  AppKeys.german: "Njemački",
  AppKeys.hindi: "Hindski",
  AppKeys.indonesian: "Indonezijski",
  AppKeys.japanese: "Japanski",
  AppKeys.korean: "Korejski",
  AppKeys.portuguese: "Portugalski",
  AppKeys.russian: "Ruski",
  AppKeys.spanish: "Španjolski",
  AppKeys.turkish: "Turski",
  'Download As': 'Preuzmi kao',
  'Choose format to download': 'Odaberite format za preuzimanje',
  'Text File': 'Tekstualna datoteka',
  'PDF File': 'PDF datoteka',
  'Copy': 'Kopiraj',
  'Share': 'Podijeli',
  'Text copied!': 'Tekst kopiran!',
  'PDF saved successfully!': 'PDF uspješno spremljen!',
  'Error creating PDF: Please try again':
      'Greška pri stvaranju PDF-a: Molimo pokušajte ponovo',
  'Character Story': 'Priča lika',
  'Character Details': 'Detalji lika',
  'Character Name': 'Ime lika',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Dob (npr., 25, Mladi odrasli, Drevni)',
  'Personality (e.g., brave, shy, cunning)':
      'Osobnost (npr., hrabar, sramežljiv, lukav)',
  'Role (e.g., Hero, Villain, Mentor)': 'Uloga (npr., Heroj, Zlikovac, Mentor)',
  'Additional Details (optional)': 'Dodatni detalji (neobavezno)',
  'Output Style': 'Stil izlaza',
  'Generate Character': 'Generiraj lik',
  'Please enter character name': 'Molimo unesite ime lika',
  'Please enter character role': 'Molimo unesite ulogu lika',
  'Detailed': 'Detaljno',
  'Brief': 'Kratko',
  'Elaborate': 'Opširno',
  'Create detailed character backstories':
      'Stvorite detaljne pozadinske priče likova',
  'Create Character': 'Stvori lik',
  'Transform and improve your existing stories':
      'Transformirajte i poboljšajte svoje postojeće priče',
  'Rewrite Now': 'Prepiši sada',
  'Generate catchy titles for your stories':
      'Generirajte privlačne naslove za svoje priče',
  'Generate Titles': 'Generiraj naslove',
  'Rewrite Story': 'Prepiši priču',
  'Paste Your Story': 'Zalijepite svoju priču',
  'Paste your story here to rewrite...':
      'Zalijepite svoju priču ovdje za prepisivanje...',
  'Select Tone': 'Odaberi ton',
  'Rewrite Style': 'Stil prepisivanja',
  'Output Length': 'Duljina izlaza',
  'Please paste your story': 'Molimo zalijepite svoju priču',
  'Story is too short. Please provide more content.':
      'Priča je prekratka. Molimo pružite više sadržaja.',
  'Same': 'Isto',
  'More Dramatic': 'Dramatičnije',
  'More Humorous': 'Humorističnije',
  'More Emotional': 'Emotivnije',
  'More Suspenseful': 'Napetije',
  'Lighter': 'Lakše',
  'Improved': 'Poboljšano',
  'Simplified': 'Pojednostavljeno',
  'More Descriptive': 'Opisnije',
  'More Dialogue': 'Više dijaloga',
  'More Action': 'Više akcije',
  'Literary': 'Književno',
  'Shorter': 'Kraće',
  'Longer': 'Duže',
  'Much Longer': 'Mnogo duže',
  'Title Generator': 'Generator naslova',
  'Story/Book Topic': 'Tema priče/knjige',
  'Keywords (Optional)': 'Ključne riječi (neobavezno)',
  'Describe your story topic or theme...':
      'Opišite temu ili temu svoje priče...',
  'e.g., magic, dragon, adventure': 'npr., magija, zmaj, avantura',
  'Title For': 'Naslov za',
  'Title Style': 'Stil naslova',
  "Adventure": "Avantura",
  'Number of Titles': 'Broj naslova',
  'Book': 'Knjiga',
  'Short Story': 'Kratka priča',
  'Novel': 'Roman',
  'Chapter': 'Poglavlje',
  'Series': 'Serija',
  'Simple': 'Jednostavno',
  'Mysterious': 'Misteriozno',
  'Dramatic': 'Dramatično',
  'Catchy': 'Privlačno',
  'Poetic': 'Poetično',
  'Kids': 'Djeca',
  'Blog Writer': 'Pisac bloga',
  'Blog Topic': 'Tema bloga',
  'Target Keywords': 'Ciljane ključne riječi',
  'Target Audience (Optional)': 'Ciljna publika (neobavezno)',
  'Enter your blog topic or title...': 'Unesite temu ili naslov svog bloga...',
  'e.g., AI writing, content marketing, SEO tips':
      'npr., AI pisanje, marketing sadržaja, SEO savjeti',
  'e.g., small business owners, bloggers':
      'npr., vlasnici malih poduzeća, blogeri',
  'Article Type': 'Vrsta članka',
  'Writing Tone': 'Ton pisanja',
  'Article Length': 'Duljina članka',
  'SEO Options': 'SEO opcije',
  'Include Meta Description': 'Uključi meta opis',
  'Include Keyword Suggestions': 'Uključi prijedloge ključnih riječi',
  'Include FAQs Section': 'Uključi odjeljak čestih pitanja',
  'Please enter a blog topic': 'Molimo unesite temu bloga',
  'Generate Blog': 'Generiraj blog',
  'SEO optimized articles with keywords':
      'SEO optimizirani članci s ključnim riječima',
  'Write Blog': 'Piši blog',
  'SEO Article': 'SEO članak',
  'How-To Guide': 'Vodič kako',
  'Listicle': 'Članak s popisom',
  'Product Review': 'Recenzija proizvoda',
  'Opinion Piece': 'Članak mišljenja',
  'News Article': 'Novinski članak',
  'Professional': 'Profesionalno',
  'Casual': 'Ležerno',
  'Informative': 'Informativno',
  'Persuasive': 'Uvjerljivo',
  'Friendly': 'Prijateljski',
  'Authoritative': 'Autoritativno',
  'Short (500-800)': 'Kratko (500-800)',
  'Medium (800-1500)': 'Srednje (800-1500)',
  'Long (1500-2500)': 'Dugo (1500-2500)',
  'Detailed (2500+)': 'Detaljno (2500+)',
  'YouTube Script': 'YouTube scenarij',
  'Video Topic': 'Tema videa',
  'Key Points (Optional)': 'Ključne točke (neobavezno)',
  'What is your video about?': 'O čemu je vaš video?',
  'List key points to cover (optional)...':
      'Navedite ključne točke za pokriti (neobavezno)...',
  'Video Duration': 'Trajanje videa',
  'Script Options': 'Opcije scenarija',
  'Include Hook/Intro': 'Uključi uvod',
  'Include Call-to-Action': 'Uključi poziv na akciju',
  'Include Timestamps': 'Uključi vremenske oznake',
  'Please enter a video topic': 'Molimo unesite temu videa',
  'Generate Script': 'Generiraj scenarij',
  'Create scripts for videos & reels': 'Stvorite scenarije za videe i reelove',
  'Create Script': 'Stvori scenarij',
  'Storytime': 'Vrijeme za priču',
  'Documentary': 'Dokumentarni',
  'Short Reel': 'Kratki reel',
  'Educational': 'Obrazovni',
  'Review': 'Recenzija',
  'Tutorial': 'Vodič',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Privlačno',
  'Energetic': 'Energično',
  'Calm': 'Mirno',
  'Funny': 'Smiješno',
  'Inspired': 'Inspirirano',
  'Film Script': 'Filmski scenarij',
  'Stage Play': 'Kazališna predstava',
  'Scene Breakdown': 'Analiza scene',
  'Dialogue Only': 'Samo dijalog',
  'Ad loading please wait..': 'Oglas se učitava, molimo pričekajte..',
  'Words:': 'Riječi:',
  'Reading:': 'Čitanje:',
};
