import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> hu = {
  AppKeys.lblChooseLanguage: "Nyelv kiválasztása",
  "All": "Összes",
  "AI Story Generator": "AI történetgenerátor",
  "Story Generator": "Történetgenerátor",
  "Essay Writer": "Esszéíró",
  "Essay length": "Esszé hossza",
  "Script Generator": "Forgatókönyvgenerátor",
  "Create original stories in seconds":
      "Hozzon létre eredeti történeteket másodpercek alatt",
  "Academic writing made simple": "Az akadémiai írás egyszerűvé téve",
  "Generate powerful scripts for any medium":
      "Hozzon létre erőteljes forgatókönyveket bármilyen médiumhoz",
  "Start Writing": "Kezdjen el írni",
  "Create Now": "Létrehozás most",
  "Start Generating": "Generálás indítása",
  "Your Stories": "Történeteid",
  "No stories yet": "Még nincsenek történetek",
  "Start creating your first story!":
      "Kezdd el az első történeted létrehozását!",
  "Your Story Space Awaits": "A történettered vár",
  "Start your first story and see it appear here":
      "Kezdd el az első történeted és nézd meg, ahogy itt megjelenik",
  "Language": "Nyelv",
  "Rate us": "Értékelj minket",
  "Share us": "Oszd meg",
  "Privacy Policy": "Adatvédelmi irányelvek",
  "Settings": "Beállítások",
  "Select Language": "Nyelv kiválasztása",
  "Dashboard": "Irányítópult",
  "BENEFITS": "ELŐNYÖK",
  "Subscribe": "Feliratkozás",
  "Weekly": "Heti",
  "Monthly": "Havi",
  "Yearly": "Éves",
  "week": "hét",
  "months": "hónapok",
  "year": "év",
  "Terms & Condition": "Feltételek és kikötések",
  "No Commitment. Cancel anytime": "Nincs kötelezettség. Bármikor lemondható",
  "No Payment Now": "Most nincs fizetés",
  "3 days free": "3 nap ingyenes",
  "Start your free trial": "Indítsa el az ingyenes próbaverziót",
  "More detailed answers": "Részletesebb válaszok",
  "Instant responds": "Azonnali válaszok",
  "Text recognition": "Szövegfelismerés",
  "Powered by AI": "AI által hajtva",
  "Storytelleing": "Mesélés",
  ' Power': " Erő",
  "Unlock your \nFill ": "Oldd fel a \nFill ",
  "Your History": "Előzményeid",
  "Terms and Conditions": "Feltételek és kikötések",
  "Short": "Rövid",
  "Medium": "Közepes",
  "Long": "Hosszú",
  "Length": "Hossz",
  "Describe your topic...": "Írd le a témádat...",
  "Set Creativity": "Kreativitás beállítása",
  "Standard": "Standard",
  "Creative": "Kreatív",
  "Complex": "Összetett",
  "Select Genre": "Műfaj kiválasztása",
  "Fantasy": "Fantázia",
  "Mystery": "Rejtély",
  "Thriller": "Thriller",
  "Script Tone": "Forgatókönyv hangvétel",
  "Script Type": "Forgatókönyv típusa",
  "Comedy": "Vígjáték",
  "Drama": "Dráma",
  "Horror": "Horror",
  "Action": "Akció",
  "Romance": "Romantikus",
  "Go Premium": "Prémium",
  "Unlock Everything": "Mindent feloldani",
  "Unlimited Story Generation": "Korlátlan történetgenerálás",
  "Write Longer & Detailed Essays": "Írjon hosszabb és részletesebb esszéket",
  "Advanced Script Writer": "Fejlett forgatókönyvíró",
  "Unlock All Styles & Tones": "Minden stílus és hangvétel feloldása",
  "No Word/Length Limit": "Nincs szó/hossz korlát",
  "Remove All Ads": "Összes hirdetés eltávolítása",
  "Restore": "Visszaállítás",
  "YouTube Video": "YouTube videó",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivációs",
  "Advertisement": "Hirdetés",
  "Fairy Tale": "Mese",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Stílus kiválasztása",
  "Imaginative": "Képzeletgazdag",
  "Innovative": "Innovatív",
  "AI Story Writer": "AI történetíró",
  "Generate": "Generálás",
  "Please wait...": "Kérem várjon...",
  "Result": "Eredmény",
  "Regenerate": "Újragenerálás",
  "Download": "Letöltés",
  "Text copied to clipboard!": "Szöveg másolva a vágólapra!",
  "Please enter a topic": "Kérem adjon meg egy témát",
  "Story Magic": "Történetvarázslat",
  "Let AI bring your thoughts to a full story":
      "Hagyd, hogy az AI teljes történetté alakítsa gondolataid",
  "Smart Scripts": "Okos forgatókönyvek",
  "From concept to script—fast, easy, and creative":
      "Koncepciótól a forgatókönyvig—gyorsan, könnyen és kreatívan",
  "Perfect Essays": "Tökéletes esszék",
  "You have reached your free limit": "Elérted az ingyenes limitedet",
  "Donwload": "Letöltés",
  "Press again to exit app": "Nyomd meg újra az alkalmazásból való kilépéshez",
  "Saved to files": "TXT fájl sikeresen mentve!",
  "Error: Please try again": "Hiba: Kérem próbálja újra",
  "Subscription expired": "Az előfizetés lejárt",
  "Purchase cancelled": "Vásárlás törölve",
  "Purchase failed": "Vásárlás sikertelen",
  "Restore failed": "Visszaállítás sikertelen",
  "Purchase Successful!": "Vásárlás sikeres!",
  "Short (200-500 words)": "Rövid (200-500 szó)",
  "Medium (500-1000 words)": "Közepes (500-1000 szó)",
  "Large (1000+ words)": "Nagy (1000+ szó)",
  "Academic Level": "Akadémiai szint",
  "Type of Paper": "Dolgozat típusa",
  "High School": "Középiskola",
  "College": "Főiskola",
  "Short Film": "Rövidfilm",
  "University": "Egyetem",
  "Masters": "Mesterképzés",
  "Custom": "Egyéni",
  "Tiktok Video": "TikTok videó",
  "Movie": "Film",
  "Expository": "Magyarázó",
  "Argumentative": "Érvelő",
  "Narrative": "Elbeszélő",
  "Descriptive": "Leíró",
  "We're sorry to hear that 😔": "Sajnáljuk, hogy ezt halljuk 😔",
  "We'll try to improve 🙁": "Megpróbálunk javítani 🙁",
  "Thanks for your feedback 🙂": "K��szönjük a visszajelzésedet 🙂",
  "Great! We're glad you like it 😊": "Remek! Örülünk, hogy tetszik 😊",
  "Awesome! Thank you so much! 🎉": "Fantasztikus! Nagyon köszönjük! 🎉",
  "Maybe Later": "Talán később",
  "Tap a star to rate your experience":
      "Érintsd meg egy csillagot az élményed értékeléséhez",
  "Enjoying AI Math Solver?": "Élvezed az AI matematika megoldót?",
  "Thank you for rating us": "Köszönjük az értékelést",
  "Submit Rating": "Értékelés beküldése",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Élvezed az AI történetgenerátort?",
  AppKeys.arabic: "Arab",
  AppKeys.chinese: "Kínai",
  AppKeys.english: "Angol",
  AppKeys.french: "Francia",
  AppKeys.german: "Német",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonéz",
  AppKeys.japanese: "Japán",
  AppKeys.korean: "Koreai",
  AppKeys.portuguese: "Portugál",
  AppKeys.russian: "Orosz",
  AppKeys.spanish: "Spanyol",
  AppKeys.turkish: "Török",
  'Download As': 'Letöltés másként',
  'Choose format to download': 'Válasszon letöltési formátumot',
  'Text File': 'Szövegfájl',
  'PDF File': 'PDF fájl',
  'Copy': 'Másolás',
  'Share': 'Megosztás',
  'Text copied!': 'Szöveg másolva!',
  'PDF saved successfully!': 'PDF sikeresen mentve!',
  'Error creating PDF: Please try again':
      'Hiba a PDF létrehozásakor: Kérem próbálja újra',
  'Character Story': 'Karakter története',
  'Character Details': 'Karakter részletei',
  'Character Name': 'Karakter neve',
  'Age (e.g., 25, Young Adult, Ancient)': 'Kor (pl., 25, Fiatal felnőtt, Ős)',
  'Personality (e.g., brave, shy, cunning)':
      'Személyiség (pl., bátor, félénk, ravasz)',
  'Role (e.g., Hero, Villain, Mentor)': 'Szerep (pl., Hős, Gonosz, Mentor)',
  'Additional Details (optional)': 'További részletek (opcionális)',
  'Output Style': 'Kimeneti stílus',
  'Generate Character': 'Karakter generálása',
  'Please enter character name': 'Kérem adja meg a karakter nevét',
  'Please enter character role': 'Kérem adja meg a karakter szerepét',
  'Detailed': 'Részletes',
  'Brief': 'Rövid',
  'Elaborate': 'Részletezett',
  'Create detailed character backstories':
      'Hozzon létre részletes karakter háttértörténeteket',
  'Create Character': 'Karakter létrehozása',
  'Transform and improve your existing stories':
      'Alakítsd át és javítsd meglévő történeteidet',
  'Rewrite Now': 'Írd újra most',
  'Generate catchy titles for your stories':
      'Generálj fülbemászó címeket a történeteidhez',
  'Generate Titles': 'Címek generálása',
  'Rewrite Story': 'Történet újraírása',
  'Paste Your Story': 'Illeszd be a történeted',
  'Paste your story here to rewrite...':
      'Illeszd be a történeted ide az újraíráshoz...',
  'Select Tone': 'Hangvétel kiválasztása',
  'Rewrite Style': 'Újraírási stílus',
  'Output Length': 'Kimeneti hossz',
  'Please paste your story': 'Kérem illessze be a történetét',
  'Story is too short. Please provide more content.':
      'A történet túl rövid. Kérem adjon meg több tartalmat.',
  'Same': 'Ugyanaz',
  'More Dramatic': 'Drámaibb',
  'More Humorous': 'Humorosabb',
  'More Emotional': 'Érzelmibb',
  'More Suspenseful': 'Feszültebb',
  'Lighter': 'Könnyedebb',
  'Improved': 'Javított',
  'Simplified': 'Egyszerűsített',
  'More Descriptive': 'Leíróbb',
  'More Dialogue': 'Több párbeszéd',
  'More Action': 'Több akció',
  'Literary': 'Irodalmi',
  'Shorter': 'Rövidebb',
  'Longer': 'Hosszabb',
  'Much Longer': 'Sokkal hosszabb',
  'Title Generator': 'Címgenerátor',
  'Story/Book Topic': 'Történet/könyv téma',
  'Keywords (Optional)': 'Kulcsszavak (opcionális)',
  'Describe your story topic or theme...': 'Írd le a történeted témáját...',
  'e.g., magic, dragon, adventure': 'pl., mágia, sárkány, kaland',
  'Title For': 'Cím',
  'Title Style': 'Cím stílusa',
  "Adventure": "Kaland",
  'Number of Titles': 'Címek száma',
  'Book': 'Könyv',
  'Short Story': 'Novella',
  'Novel': 'Regény',
  'Chapter': 'Fejezet',
  'Series': 'Sorozat',
  'Simple': 'Egyszerű',
  'Mysterious': 'Rejtélyes',
  'Dramatic': 'Drámai',
  'Catchy': 'Fülbemászó',
  'Poetic': 'Költői',
  'Kids': 'Gyerekeknek',
  'Blog Writer': 'Blogíró',
  'Blog Topic': 'Blog téma',
  'Target Keywords': 'Cél kulcsszavak',
  'Target Audience (Optional)': 'Célközönség (opcionális)',
  'Enter your blog topic or title...': 'Add meg a blog témáját vagy címét...',
  'e.g., AI writing, content marketing, SEO tips':
      'pl., AI írás, tartalommarketing, SEO tippek',
  'e.g., small business owners, bloggers':
      'pl., kisvállalkozás tulajdonosok, bloggerek',
  'Article Type': 'Cikk típusa',
  'Writing Tone': 'Írás hangvétele',
  'Article Length': 'Cikk hossza',
  'SEO Options': 'SEO beállítások',
  'Include Meta Description': 'Meta leírás hozzáadása',
  'Include Keyword Suggestions': 'Kulcsszó javaslatok hozzáadása',
  'Include FAQs Section': 'GYIK rész hozzáadása',
  'Please enter a blog topic': 'Kérem adjon meg egy blog témát',
  'Generate Blog': 'Blog generálása',
  'SEO optimized articles with keywords':
      'SEO optimalizált cikkek kulcsszavakkal',
  'Write Blog': 'Blog írása',
  'SEO Article': 'SEO cikk',
  'How-To Guide': 'Útmutató',
  'Listicle': 'Listás cikk',
  'Product Review': 'Termékértékelés',
  'Opinion Piece': 'Véleménycikk',
  'News Article': 'Hír cikk',
  'Professional': 'Professzionális',
  'Casual': 'Laza',
  'Informative': 'Informatív',
  'Persuasive': 'Meggyőző',
  'Friendly': 'Barátságos',
  'Authoritative': 'Tekintélyes',
  'Short (500-800)': 'Rövid (500-800)',
  'Medium (800-1500)': 'Közepes (800-1500)',
  'Long (1500-2500)': 'Hosszú (1500-2500)',
  'Detailed (2500+)': 'Részletes (2500+)',
  'YouTube Script': 'YouTube forgatókönyv',
  'Video Topic': 'Videó téma',
  'Key Points (Optional)': 'Kulcspontok (opcionális)',
  'What is your video about?': 'Miről szól a videód?',
  'List key points to cover (optional)...':
      'Sorolja fel a tárgyalandó kulcspontokat (opcionális)...',
  'Video Duration': 'Videó időtartam',
  'Script Options': 'Forgatókönyv beállítások',
  'Include Hook/Intro': 'Bevezető hozzáadása',
  'Include Call-to-Action': 'Cselekvésre ösztönzés hozzáadása',
  'Include Timestamps': 'Időbélyegek hozzáadása',
  'Please enter a video topic': 'Kérem adjon meg egy videó témát',
  'Generate Script': 'Forgatókönyv generálása',
  'Create scripts for videos & reels':
      'Hozzon létre forgatókönyveket videókhoz és reelekhez',
  'Create Script': 'Forgatókönyv létrehozása',
  'Storytime': 'Meseóra',
  'Documentary': 'Dokumentum',
  'Short Reel': 'Rövid reel',
  'Educational': 'Oktatási',
  'Review': 'Értékelés',
  'Tutorial': 'Oktatóanyag',
  '< 1 min (Shorts)': '< 1 perc (Shorts)',
  '1-3 min': '1-3 perc',
  '5-10 min': '5-10 perc',
  '10-20 min': '10-20 perc',
  '20+ min': '20+ perc',
  'Engaging': 'Lebilincselő',
  'Energetic': 'Energikus',
  'Calm': 'Nyugodt',
  'Funny': 'Vicces',
  'Inspired': 'Inspirált',
  'Film Script': 'Filmforgatókönyv',
  'Stage Play': 'Színdarab',
  'Scene Breakdown': 'Jelenet elemzés',
  'Dialogue Only': 'Csak párbeszéd',
  'Ad loading please wait..': 'Hirdetés betöltődik, kérem várjon..',
  'Words:': 'Szavak:',
  'Reading:': 'Olvasás:',
};
