import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> hy = {
  AppKeys.lblChooseLanguage: "Ընտրել լեզusage",
  "All": "Բlolorege",
  "AI Story Generator": "AI Patmutyunneri generator",
  "Story Generator": "Patmutyunneri generator",
  "Essay Writer": "Essei grog",
  "Essay length": "Essei erkarutyan",
  "Script Generator": "Scenari generator",
  "Create original stories in seconds":
      "Steghtseq inknatip patmutyunner vayrkyannerts",
  "Academic writing made simple": "Akademiakan grutyan parzvetsatsva",
  "Generate powerful scripts for any medium":
      "Steghtseq hzor scenarner tsankatsats mijavayr hamar",
  "Start Writing": "Sksel grel",
  "Create Now": "Steghtsvel hima",
  "Start Generating": "Sksel generatsnel",
  "Your Stories": "Dzer patmutyunnerw",
  "No stories yet": "Derevs patmutyunner chkan",
  "Start creating your first story!":
      "Skseq steghtsvel dzer arajin patmutyunw!",
  "Your Story Space Awaits": "Dzer patmutyuneri taratsutyunw spasum e",
  "Start your first story and see it appear here":
      "Skseq dzer arajin patmutyunw yev teseq ayn aystegh",
  "Language": "Lezu",
  "Rate us": "Gnahateq mez",
  "Share us": "Kiseq mez",
  "Privacy Policy": "Gaghtniyutyan qaghaqakanutyan",
  "Settings": "Kargavorumner",
  "Select Language": "Entreg lezu",
  "Dashboard": "Karavaru varahu",
  "BENEFITS": "ARAGHUTYUNNER",
  "Subscribe": "Bajananordvel",
  "Weekly": "Shabatakan",
  "Monthly": "Amsakan",
  "Yearly": "Tarekan",
  "week": "shabat",
  "months": "amis",
  "year": "tari",
  "Terms & Condition": "Paymannerge yev paymannerge",
  "No Commitment. Cancel anytime":
      "Arants partavorutyan. Chegeyarkeq tsankatsats zhaman",
  "No Payment Now": "Hima vacharq chka",
  "3 days free": "3 or anvachar",
  "Start your free trial": "Skseq dzer anvachar poknaporddzwery",
  "More detailed answers": "Aveli manramashnak pataskhannerey",
  "Instant responds": "Akanakali pataskhannerey",
  "Text recognition": "Tekst chanagemaye",
  "Powered by AI": "AI-i kargavorutyuny",
  "Storytelleing": "Patmut patmelu",
  ' Power': " Uzh",
  "Unlock your \nFill ": "Batsakeq dzer \nFill ",
  "Your History": "Dzer patmutyun",
  "Terms and Conditions": "Paymannerge yev paymannerge",
  "Short": "Karch",
  "Medium": "Mijin",
  "Long": "Erkar",
  "Length": "Erkarutyun",
  "Describe your topic...": "Nkaragreq dzer temaw...",
  "Set Creativity": "Kargavoreg steghtsagortsutyan",
  "Standard": "Standart",
  "Creative": "Steghtsagortsakan",
  "Complex": "Barddz",
  "Select Genre": "Entreg zhanr",
  "Fantasy": "Fantazia",
  "Mystery": "Khodvatsayin",
  "Thriller": "Triler",
  "Script Tone": "Scenari tone",
  "Script Type": "Scenari tesak",
  "Comedy": "Katakergutyan",
  "Drama": "Drama",
  "Horror": "Sahuz",
  "Action": "Gortsoghutyun",
  "Romance": "Romantik",
  "Go Premium": "Premium dartzel",
  "Unlock Everything": "Batsakeq amena",
  "Unlimited Story Generation": "Ansahmanatel patmutyunner steghtselu",
  "Write Longer & Detailed Essays": "Greq aveli erkar yev manramashn essener",
  "Advanced Script Writer": "Arjanayanats scenari grog",
  "Unlock All Styles & Tones": "Batsakeq bolore vocher yev tonere",
  "No Word/Length Limit": "Ban/erkarutyan sahmanapakum chka",
  "Remove All Ads": "Heracreq bolore govazder",
  "Restore": "Verakangnel",
  "YouTube Video": "YouTube tesanuts",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivatsion",
  "Advertisement": "Govazd",
  "Fairy Tale": "Heqiatye",
  "Sci-Fi": "Gitakan fantastika",
  "Select Style": "Entreg voch",
  "Imaginative": "Yerevakayakani",
  "Innovative": "Norarakanakan",
  "AI Story Writer": "AI patmutyun grog",
  "Generate": "Generatsnel",
  "Please wait...": "Khndrume spasel...",
  "Result": "Ardyunq",
  "Regenerate": "Verageneratsnel",
  "Download": "Bernel",
  "Text copied to clipboard!": "Tekste patchemva klipborti mej!",
  "Please enter a topic": "Khndrume mttsreq tema",
  "Story Magic": "Patmutyunneri kakhardakanutyun",
  "Let AI bring your thoughts to a full story":
      "Tuq AI-in dzer mtqerw lits patmutyun dardzni",
  "Smart Scripts": "Khorhrdali scenarner",
  "From concept to script—fast, easy, and creative":
      "Hashetsoghutyunits scenar—arag, heshd yev steghtsagortsakan",
  "Perfect Essays": "Kataryal essener",
  "You have reached your free limit": "Dzeq hasel eq dzer anvachar sahmanin",
  "Donwload": "Bernel",
  "Press again to exit app": "Krknel noric havelvatsits durs galu hamar",
  "Saved to files": "TXT file hajoghutyamb pahpanvats e!",
  "Error: Please try again": "Skhal: Khndrume noric potsdeq",
  "Subscription expired": "Bajananordagrutyan zhamketn antsats e",
  "Purchase cancelled": "Gnume chegeyarkva",
  "Purchase failed": "Gnume dzakhogvel e",
  "Restore failed": "Verakangnume dzakhogvel e",
  "Purchase Successful!": "Gnume hajogha!",
  "Short (200-500 words)": "Karch (200-500 bar)",
  "Medium (500-1000 words)": "Mijin (500-1000 bar)",
  "Large (1000+ words)": "Mets (1000+ bar)",
  "Academic Level": "Akademiakan mart",
  "Type of Paper": "Tghti tesak",
  "High School": "Avag dprots",
  "College": "Kolej",
  "Short Film": "Karcharag film",
  "University": "Hamalsaran",
  "Masters": "Magistros",
  "Custom": "Hatkakan",
  "Tiktok Video": "TikTok tesanuts",
  "Movie": "Film",
  "Expository": "Batratsakani",
  "Argumentative": "Parbanakhakan",
  "Narrative": "Patmakhosakan",
  "Descriptive": "Nkaragrakan",
  "We're sorry to hear that 😔": "Tkhrum enq or ayd lsum enq 😔",
  "We'll try to improve 🙁": "Kpotsdenq lavatsnel 🙁",
  "Thanks for your feedback 🙂": "Shnorhakale dzer karts 🙂",
  "Great! We're glad you like it 😊":
      "Hrashalik! Urakhe enq, or dzer dur yekav 😊",
  "Awesome! Thank you so much! 🎉": "Hrashalik! Shat shnorhakale! 🎉",
  "Maybe Later": "Guts aveli ush",
  "Tap a star to rate your experience":
      "Sghmeq astvagh dzer portdzw gnahatelou hamar",
  "Enjoying AI Math Solver?": "Haytnum eq AI matemadikayi lusitsh?",
  "Thank you for rating us": "Shnorhakale mez gnahatelou hamar",
  "Submit Rating": "Gnahateq ughark",
  "Hindi": "Hindieren",
  "Enjoying AI Story Generator?": "Haytnum eq AI patmutyunneri generator?",
  AppKeys.arabic: "Araberen",
  AppKeys.chinese: "Chinaren",
  AppKeys.english: "Angleren",
  AppKeys.french: "Fransiaren",
  AppKeys.german: "Germaneren",
  AppKeys.hindi: "Hindieren",
  AppKeys.indonesian: "Indonezeren",
  AppKeys.japanese: "Yaponeren",
  AppKeys.korean: "Koreyeren",
  AppKeys.portuguese: "Portugaleren",
  AppKeys.russian: "Ruseren",
  AppKeys.spanish: "Ispaneren",
  AppKeys.turkish: "Turqeren",
  'Download As': 'Bernel vorpes',
  'Choose format to download': 'Entreg bernelow format',
  'Text File': 'Tekst file',
  'PDF File': 'PDF file',
  'Copy': 'Patchenel',
  'Share': 'Kisel',
  'Text copied!': 'Tekste patchenva!',
  'PDF saved successfully!': 'PDF-n hajoghakioren pahpanva!',
  'Error creating PDF: Please try again':
      'PDF steghtselu skhal: Khndrume noric potsdeq',
  'Character Story': 'Kerparw patmutyun',
  'Character Details': 'Kerpari manramasnutyunner',
  'Character Name': 'Kerpari anun',
  'Age (e.g., 25, Young Adult, Ancient)': 'Tariq (or., 25, Yeritasard, Hin)',
  'Personality (e.g., brave, shy, cunning)':
      'Andzanishteyr (or., qajer, amotkhah, khorda)',
  'Role (e.g., Hero, Villain, Mentor)': 'Derake (or., Heros, Char, Mentor)',
  'Additional Details (optional)': 'Havelyal manramasnutyunner (khmavore)',
  'Output Style': 'Ardyunqi voch',
  'Generate Character': 'Kerpar generatsnel',
  'Please enter character name': 'Khndrume mttsreq kerpari anun',
  'Please enter character role': 'Khndrume mttsreq kerpari derake',
  'Detailed': 'Manramashn',
  'Brief': 'Hamari',
  'Elaborate': 'Manramashni',
  'Create detailed character backstories':
      'Steghtseq manramashn kerpari patmutyunner',
  'Create Character': 'Steghtsvel kerpar',
  'Transform and improve your existing stories':
      'Pokhanakeq yev lavatseq dzer arddish patmutyunnerw',
  'Rewrite Now': 'Veragrel hima',
  'Generate catchy titles for your stories':
      'Steghtseq gragravich vernagrerner dzer patmutyunneri hamar',
  'Generate Titles': 'Steghtseq vernagrerner',
  'Rewrite Story': 'Veragrel patmutyun',
  'Paste Your Story': 'Teghadreq dzer patmutyunw',
  'Paste your story here to rewrite...':
      'Teghadreq dzer patmutyunw aystegh veragrelu hamar...',
  'Select Tone': 'Entreg tone',
  'Rewrite Style': 'Veragrelu voch',
  'Output Length': 'Ardyunqi erkarutyun',
  'Please paste your story': 'Khndrume teghadreq dzer patmutyunw',
  'Story is too short. Please provide more content.':
      'Patmutyunw shat karch e. Khndrume aveli shat bern tveq.',
  'Same': 'Nuyne',
  'More Dramatic': 'Aveli dramatik',
  'More Humorous': 'Aveli katakakan',
  'More Emotional': 'Aveli husakan',
  'More Suspenseful': 'Aveli larvayin',
  'Lighter': 'Aveli thetev',
  'Improved': 'Lavatsva',
  'Simplified': 'Parzvetsatsva',
  'More Descriptive': 'Aveli nkaragrakan',
  'More Dialogue': 'Aveli shat yerkhkhosutyan',
  'More Action': 'Aveli shat gortsoghutyun',
  'Literary': 'Grakanakan',
  'Shorter': 'Aveli karch',
  'Longer': 'Aveli erkar',
  'Much Longer': 'Shat aveli erkar',
  'Title Generator': 'Vernagrer generator',
  'Story/Book Topic': 'Patmutyun/girq tema',
  'Keywords (Optional)': 'Baner (khmavore)',
  'Describe your story topic or theme...': 'Nkaragreq dzer patmutyuni temaw...',
  'e.g., magic, dragon, adventure':
      'or., kakhardakanutyun, vishap, arargachutyan',
  'Title For': 'Vernagrer hamar',
  'Title Style': 'Vernagrer voch',
  "Adventure": "Araragachutyan",
  'Number of Titles': 'Vernagrerneri tiv',
  'Book': 'Girq',
  'Short Story': 'Karcharag patmutyun',
  'Novel': 'Vep',
  'Chapter': 'Glokh',
  'Series': 'Sharq',
  'Simple': 'Parze',
  'Mysterious': 'Khodvatsayin',
  'Dramatic': 'Dramatik',
  'Catchy': 'Gragravich',
  'Poetic': 'Banasteghnakan',
  'Kids': 'Yerekhaneri hamar',
  'Blog Writer': 'Blog grog',
  'Blog Topic': 'Blog tema',
  'Target Keywords': 'Npataki baner',
  'Target Audience (Optional)': 'Npataki lundsargh (khmavore)',
  'Enter your blog topic or title...': 'Mttsreq dzer blog tema...',
  'e.g., AI writing, content marketing, SEO tips':
      'or., AI grutyan, bern marketing, SEO khorurdner',
  'e.g., small business owners, bloggers': 'or., pokr biznes terer, blogerner',
  'Article Type': 'Hodvatsi tesak',
  'Writing Tone': 'Grutyan tone',
  'Article Length': 'Hodvatsi erkarutyun',
  'SEO Options': 'SEO yntrner',
  'Include Meta Description': 'Ners meta nkaragrutyun',
  'Include Keyword Suggestions': 'Ners bner aradzhutyunner',
  'Include FAQs Section': 'Ners hachakh trvats hartseri bazhin',
  'Please enter a blog topic': 'Khndrume mttsreq blog tema',
  'Generate Blog': 'Blog generatsnel',
  'SEO optimized articles with keywords':
      'SEO optimizatsatsva hodvatsner bnerov',
  'Write Blog': 'Blog grel',
  'SEO Article': 'SEO hodvats',
  'How-To Guide': 'Inchpes anel ughetsvats',
  'Listicle': 'Tsanki hodvats',
  'Product Review': 'Ardyunqi tesutyan',
  'Opinion Piece': 'Karts hodvats',
  'News Article': 'Lurer hodvats',
  'Professional': 'Masnagitakan',
  'Casual': 'Ogtayi',
  'Informative': 'Teghekatvakan',
  'Persuasive': 'Hamozich',
  'Friendly': 'Enkerasirakan',
  'Authoritative': 'Heghinavoakan',
  'Short (500-800)': 'Karch (500-800)',
  'Medium (800-1500)': 'Mijin (800-1500)',
  'Long (1500-2500)': 'Erkar (1500-2500)',
  'Detailed (2500+)': 'Manramashn (2500+)',
  'YouTube Script': 'YouTube scenar',
  'Video Topic': 'Tesanutsi tema',
  'Key Points (Optional)': 'Himnakan keter (khmavore)',
  'What is your video about?': 'Inchi masin e dzer tesanutse?',
  'List key points to cover (optional)...':
      'Tsankeq himnakan ketere (khmavore)...',
  'Video Duration': 'Tesanutsi tevoghutyun',
  'Script Options': 'Scenari yntrner',
  'Include Hook/Intro': 'Ners neratsutyan',
  'Include Call-to-Action': 'Ners gortsoghutyan koch',
  'Include Timestamps': 'Ners zhamanaki nishner',
  'Please enter a video topic': 'Khndrume mttsreq tesanutsi tema',
  'Generate Script': 'Scenar generatsnel',
  'Create scripts for videos & reels':
      'Steghtseq scenarner tesanutsneri yev reelneri hamar',
  'Create Script': 'Steghtsvel scenar',
  'Storytime': 'Patmutyunw zhamanak',
  'Documentary': 'Vaveragrakani',
  'Short Reel': 'Karch reel',
  'Educational': 'Krthakan',
  'Review': 'Tesutyan',
  'Tutorial': 'Ughetsvats',
  '< 1 min (Shorts)': '< 1 rope (Shorts)',
  '1-3 min': '1-3 rope',
  '5-10 min': '5-10 rope',
  '10-20 min': '10-20 rope',
  '20+ min': '20+ rope',
  'Engaging': 'Gragravich',
  'Energetic': 'Yerakhtakan',
  'Calm': 'Handart',
  'Funny': 'Tsishakan',
  'Inspired': 'Vocheshnorntsva',
  'Film Script': 'Filmi scenar',
  'Stage Play': 'Bddesakani nerakayatsutyan',
  'Scene Breakdown': 'Desarana verlutsutyan',
  'Dialogue Only': 'Miayakn yerkhkhosutyan',
  'Ad loading please wait..': 'Govazde bertsesvuma khndrume spasel..',
  'Words:': 'Baner:',
  'Reading:': 'Ardel:',
};
