import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> id = {
  AppKeys.lblChooseLanguage: "Pilih bahasa",
  "All": "Semua",
  "AI Story Generator": "Pembuat Cerita AI",
  "Story Generator": "Pembuat Cerita",
  "Essay Writer": "Penulis Esai",
  "Essay length": "Panjang esai",
  "Script Generator": "Pembuat Skrip",
  "Create original stories in seconds":
      "Buat cerita orisinal dalam hitungan detik",
  "Academic writing made simple": "Penulisan akademik menjadi sederhana",
  "Generate powerful scripts for any medium":
      "Hasilkan skrip yang kuat untuk media apa pun",
  "Start Writing": "Mulai Menulis",
  "Create Now": "Buat Sekarang",
  "Start Generating": "Mulai Menghasilkan",
  "Your Stories": "Cerita Anda",
  "No stories yet": "Belum ada cerita",
  "Start creating your first story!": "Mulai buat cerita pertama Anda!",
  "Your Story Space Awaits": "Ruang Cerita Anda Menanti",
  "Start your first story and see it appear here":
      "Mulai cerita pertama Anda dan lihat muncul di sini",
  "Language": "Bahasa",
  "Rate us": "Beri nilai kami",
  "Share us": "Bagikan kami",
  "Privacy Policy": "Kebijakan Privasi",
  "Settings": "Pengaturan",
  "Select Language": "Pilih Bahasa",
  "Dashboard": "Dasbor",
  "BENEFITS": "MANFAAT",
  "Subscribe": "Berlangganan",
  "Weekly": "Mingguan",
  "Monthly": "Bulanan",
  "Yearly": "Tahunan",
  "week": "minggu",
  "months": "bulan",
  "year": "tahun",
  "Terms & Condition": "Syarat dan Ketentuan",
  "No Commitment. Cancel anytime": "Tanpa Komitmen. Batalkan kapan saja",
  "No Payment Now": "Tidak Ada Pembayaran Sekarang",
  "3 days free": "3 hari gratis",
  "Start your free trial": "Mulai uji coba gratis Anda",
  "More detailed answers": "Jawaban lebih detail",
  "Instant responds": "Respons instan",
  "Text recognition": "Pengenalan teks",
  "Powered by AI": "Didukung oleh AI",
  "Storytelleing": "Bercerita",
  ' Power': "Kekuatan",
  "Unlock your \nFill ": "Buka kunci \nFill Anda",
  "Your History": "Riwayat Anda",
  "Terms and Conditions": "Syarat dan Ketentuan",
  "Short": "Pendek",
  "Medium": "Sedang",
  "Long": "Panjang",
  "Length": "Panjang",
  "Describe your topic...": "Jelaskan topik Anda...",
  "Set Creativity": "Atur Kreativitas",
  "Standard": "Standar",
  "Creative": "Kreatif",
  "Complex": "Kompleks",
  "Select Genre": "Pilih Genre",
  "Fantasy": "Fantasi",
  "Mystery": "Misteri",
  "Thriller": "Thriller",
  "Script Tone": "Nada Skrip",
  "Script Type": "Jenis Skrip",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Horor",
  "Action": "Aksi",
  "Romance": "Romantis",
  "Motivational": "Motivasi",
  "Advertisement": "Iklan",
  "Fairy Tale": "Dongeng",
  "Sci-Fi": "Fiksi Ilmiah",
  "Select Style": "Pilih Gaya",
  "Imaginative": "Imajinatif",
  "Innovative": "Inovatif",
  "Generate": "Hasilkan",
  "Please wait...": "Harap tunggu...",
  "Result": "Hasil",
  "Regenerate": "Hasilkan Ulang",
  "Download": "Unduh",
  "Text copied to clipboard!": "Teks disalin ke papan klip!",
  "Please enter a topic": "Silakan masukkan topik",
  "Story Magic": "Keajaiban Cerita",
  "Let AI bring your thoughts to a full story":
      "Biarkan AI mengubah pikiran Anda menjadi cerita lengkap",
  "Smart Scripts": "Skrip Pintar",
  "From concept to script—fast, easy, and creative":
      "Dari konsep ke skrip—cepat, mudah, dan kreatif",
  "Perfect Essays": "Esai Sempurna",

  "We're sorry to hear that 😔": "Kami turut menyesal mendengarnya 😔",
  "We'll try to improve 🙁": "Kami akan mencoba untuk meningkatkan 🙁",
  "Thanks for your feedback 🙂": "Terima kasih atas masukan Anda 🙂",
  "Great! We're glad you like it 😊": "Hebat! Kami senang Anda menyukainya 😊",
  "Awesome! Thank you so much! 🎉": "Luar biasa! Terima kasih banyak! 🎉",
  "Maybe Later": "Mungkin nanti",
  "Tap a star to rate your experience":
      "Ketuk bintang untuk menilai pengalaman Anda",
  "Enjoying AI Math Solver?": "Apakah Anda menikmati AI Math Solver?",
  "Thank you for rating us": "Terima kasih telah memberi penilaian",
  "Submit Rating": "Kirim Penilaian",
  "Enjoying AI Story Generator?": "Apakah Anda menikmati AI Story Generator?",
  "Hindi": "Hindi",
  "You have reached your free limit": "Anda telah mencapai batas gratis Anda",
  "Donwload": "Unduhan",
  "Press again to exit app": "Tekan lagi untuk keluar dari aplikasi",
  "Saved to files": "File TXT berhasil disimpan!",
  "Error: Please try again": "Kesalahan: Silakan coba lagi",
  "Subscription expired": "Langganan kedaluwarsa",
  "Purchase cancelled": "Pembelian dibatalkan",
  "Purchase failed": "Pembelian gagal",
  "Restore failed": "Pemulihan gagal",
  "Purchase Successful!": "Pembelian Berhasil!",
  "Short (200-500 words)": "Pendek (200-500 kata)",
  "Medium (500-1000 words)": "Sedang (500-1000 kata)",
  "Large (1000+ words)": "Besar (1000+ kata)",
  "Academic Level": "Tingkat Akademik",
  "Type of Paper": "Jenis Makalah",
  "High School": "Sekolah Menengah",
  "College": "Perguruan Tinggi",
  "Short Film": "Film Pendek",
  "University": "Universitas",
  "Masters": "Magister",
  "Custom": "Kustom",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Video Tiktok",
  "Movie": "Film",
  "Expository": "Ekspositori",
  "Argumentative": "Argumentatif",
  "Narrative": "Naratif",
  "Descriptive": "Deskriptif",

  AppKeys.arabic: "Arab",
  AppKeys.chinese: "Mandarin",
  AppKeys.english: "Inggris",
  AppKeys.french: "Prancis",
  AppKeys.german: "Jerman",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesia",
  AppKeys.japanese: "Jepang",
  "Go Premium": "Dapatkan Premium",
  "Unlock Everything": "Buka Semuanya",
  "Unlimited Story Generation": "Pembuatan Cerita Tidak Terbatas",
  "Write Longer & Detailed Essays": "Tulis Esai yang Lebih Panjang dan Detail",
  "Advanced Script Writer": "Penulis Skrip Lanjutan",
  "Unlock All Styles & Tones": "Buka Semua Gaya dan Nada",
  "No Word/Length Limit": "Tanpa Batas Kata/Panjang",
  "Remove All Ads": "Hapus Semua Iklan",
  "3 days free": "3 hari gratis",
  "Restore": "Pulihkan",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  AppKeys.korean: "Korea",
  AppKeys.portuguese: "Portugis",
  AppKeys.russian: "Rusia",
  AppKeys.spanish: "Spanyol",
  "AI Story Writer": "Penulis Cerita AI",
  AppKeys.turkish: "Turki",
};
