import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> id = {
  AppKeys.lblChooseLanguage: "Pilih bahasa",
  "All": "Semua",
  "AI Story Generator": "Pembuat Cerita AI",
  "Story Generator": "Pembuat Cerita",
  "Essay Writer": "Penulis Esai",
  "Essay length": "Panjang esai",
  "Script Generator": "Pembuat Skrip",
  "Create original stories in seconds":
      "Buat cerita orisinal dalam hitungan detik",
  "Academic writing made simple": "Penulisan akademik menjadi sederhana",
  "Generate powerful scripts for any medium":
      "Hasilkan skrip yang kuat untuk media apa pun",
  "Start Writing": "Mulai Menulis",
  "Create Now": "Buat Sekarang",
  "Start Generating": "Mulai Menghasilkan",
  "Your Stories": "Cerita Anda",
  "No stories yet": "Belum ada cerita",
  "Start creating your first story!": "Mulai buat cerita pertama Anda!",
  "Your Story Space Awaits": "Ruang Cerita Anda Menanti",
  "Start your first story and see it appear here":
      "Mulai cerita pertama Anda dan lihat muncul di sini",
  "Language": "Bahasa",
  "Rate us": "Beri nilai kami",
  "Share us": "Bagikan kami",
  "Privacy Policy": "Kebijakan Privasi",
  "Settings": "Pengaturan",
  "Select Language": "Pilih Bahasa",
  "Dashboard": "Dasbor",
  "BENEFITS": "MANFAAT",
  "Subscribe": "Berlangganan",
  "Weekly": "Mingguan",
  "Monthly": "Bulanan",
  "Yearly": "Tahunan",
  "week": "minggu",
  "months": "bulan",
  "year": "tahun",
  "Terms & Condition": "Syarat dan Ketentuan",
  "No Commitment. Cancel anytime": "Tanpa Komitmen. Batalkan kapan saja",
  "No Payment Now": "Tidak Ada Pembayaran Sekarang",
  "3 days free": "3 hari gratis",
  "Start your free trial": "Mulai uji coba gratis Anda",
  "More detailed answers": "Jawaban lebih detail",
  "Instant responds": "Respons instan",
  "Text recognition": "Pengenalan teks",
  "Powered by AI": "Didukung oleh AI",
  "Storytelleing": "Bercerita",
  ' Power': "Kekuatan",
  "Unlock your \nFill ": "Buka kunci \nFill Anda",
  "Your History": "Riwayat Anda",
  "Terms and Conditions": "Syarat dan Ketentuan",
  "Short": "Pendek",
  "Medium": "Sedang",
  "Long": "Panjang",
  "Length": "Panjang",
  "Describe your topic...": "Jelaskan topik Anda...",
  "Set Creativity": "Atur Kreativitas",
  "Standard": "Standar",
  "Creative": "Kreatif",
  "Complex": "Kompleks",
  "Select Genre": "Pilih Genre",
  "Fantasy": "Fantasi",
  "Mystery": "Misteri",
  "Thriller": "Thriller",
  "Script Tone": "Nada Skrip",
  "Script Type": "Jenis Skrip",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Horor",
  "Action": "Aksi",
  "Romance": "Romantis",
  "Motivational": "Motivasi",
  "Advertisement": "Iklan",
  "Fairy Tale": "Dongeng",
  "Sci-Fi": "Fiksi Ilmiah",
  "Select Style": "Pilih Gaya",
  "Imaginative": "Imajinatif",
  "Innovative": "Inovatif",
  "Generate": "Hasilkan",
  "Please wait...": "Harap tunggu...",
  "Result": "Hasil",
  "Regenerate": "Hasilkan Ulang",
  "Download": "Unduh",
  "Text copied to clipboard!": "Teks disalin ke papan klip!",
  "Please enter a topic": "Silakan masukkan topik",
  "Story Magic": "Keajaiban Cerita",
  "Let AI bring your thoughts to a full story":
      "Biarkan AI mengubah pikiran Anda menjadi cerita lengkap",
  "Smart Scripts": "Skrip Pintar",
  "From concept to script—fast, easy, and creative":
      "Dari konsep ke skrip—cepat, mudah, dan kreatif",
  "Perfect Essays": "Esai Sempurna",

  "We're sorry to hear that 😔": "Kami turut menyesal mendengarnya 😔",
  "We'll try to improve 🙁": "Kami akan mencoba untuk meningkatkan 🙁",
  "Thanks for your feedback 🙂": "Terima kasih atas masukan Anda 🙂",
  "Great! We're glad you like it 😊": "Hebat! Kami senang Anda menyukainya 😊",
  "Awesome! Thank you so much! 🎉": "Luar biasa! Terima kasih banyak! 🎉",
  "Maybe Later": "Mungkin nanti",
  "Tap a star to rate your experience":
      "Ketuk bintang untuk menilai pengalaman Anda",
  "Enjoying AI Math Solver?": "Apakah Anda menikmati AI Math Solver?",
  "Thank you for rating us": "Terima kasih telah memberi penilaian",
  "Submit Rating": "Kirim Penilaian",
  "Enjoying AI Story Generator?": "Apakah Anda menikmati AI Story Generator?",
  "Hindi": "Hindi",
  "You have reached your free limit": "Anda telah mencapai batas gratis Anda",
  "Donwload": "Unduhan",
  "Press again to exit app": "Tekan lagi untuk keluar dari aplikasi",
  "Saved to files": "File TXT berhasil disimpan!",
  "Error: Please try again": "Kesalahan: Silakan coba lagi",
  "Subscription expired": "Langganan kedaluwarsa",
  "Purchase cancelled": "Pembelian dibatalkan",
  "Purchase failed": "Pembelian gagal",
  "Restore failed": "Pemulihan gagal",
  "Purchase Successful!": "Pembelian Berhasil!",
  "Short (200-500 words)": "Pendek (200-500 kata)",
  "Medium (500-1000 words)": "Sedang (500-1000 kata)",
  "Large (1000+ words)": "Besar (1000+ kata)",
  "Academic Level": "Tingkat Akademik",
  "Type of Paper": "Jenis Makalah",
  "High School": "Sekolah Menengah",
  "College": "Perguruan Tinggi",
  "Short Film": "Film Pendek",
  "University": "Universitas",
  "Masters": "Magister",
  "Custom": "Kustom",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Video Tiktok",
  "Movie": "Film",
  "Expository": "Ekspositori",
  "Argumentative": "Argumentatif",
  "Narrative": "Naratif",
  "Descriptive": "Deskriptif",

  AppKeys.arabic: "Arab",
  AppKeys.chinese: "Mandarin",
  AppKeys.english: "Inggris",
  AppKeys.french: "Prancis",
  AppKeys.german: "Jerman",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesia",
  AppKeys.japanese: "Jepang",
  "Go Premium": "Dapatkan Premium",
  "Unlock Everything": "Buka Semuanya",
  "Unlimited Story Generation": "Pembuatan Cerita Tidak Terbatas",
  "Write Longer & Detailed Essays": "Tulis Esai yang Lebih Panjang dan Detail",
  "Advanced Script Writer": "Penulis Skrip Lanjutan",
  "Unlock All Styles & Tones": "Buka Semua Gaya dan Nada",
  "No Word/Length Limit": "Tanpa Batas Kata/Panjang",
  "Remove All Ads": "Hapus Semua Iklan",
  "Restore": "Pulihkan",
  AppKeys.korean: "Korea",
  AppKeys.portuguese: "Portugis",
  AppKeys.russian: "Rusia",
  AppKeys.spanish: "Spanyol",
  "AI Story Writer": "Penulis Cerita AI",
  AppKeys.turkish: "Turki",

  // New strings for download & actions
  'Download As': 'Unduh Sebagai',
  'Choose format to download': 'Pilih format untuk diunduh',
  'Text File': 'File Teks',
  'PDF File': 'File PDF',
  'Copy': 'Salin',
  'Share': 'Bagikan',
  'Text copied!': 'Teks disalin!',
  'PDF saved successfully!': 'PDF berhasil disimpan!',
  'Error creating PDF: Please try again':
      'Kesalahan membuat PDF: Silakan coba lagi',

  // Character Story Tool
  'Character Story': 'Cerita Karakter',
  'Character Details': 'Detail Karakter',
  'Character Name': 'Nama Karakter',
  'Age (e.g., 25, Young Adult, Ancient)': 'Usia (mis. 25, Dewasa Muda, Kuno)',
  'Personality (e.g., brave, shy, cunning)':
      'Kepribadian (mis. berani, pemalu, licik)',
  'Role (e.g., Hero, Villain, Mentor)':
      'Peran (mis. Pahlawan, Penjahat, Mentor)',
  'Additional Details (optional)': 'Detail Tambahan (opsional)',
  'Output Style': 'Gaya Keluaran',
  'Generate Character': 'Buat Karakter',
  'Please enter character name': 'Silakan masukkan nama karakter',
  'Please enter character role': 'Silakan masukkan peran karakter',
  'Detailed': 'Detail',
  'Brief': 'Singkat',
  'Elaborate': 'Terperinci',

  // Home Screen Tool Cards
  'Create detailed character backstories':
      'Buat cerita latar belakang karakter yang detail',
  'Create Character': 'Buat Karakter',
  'Transform and improve your existing stories':
      'Transformasi dan perbaiki cerita Anda',
  'Rewrite Now': 'Tulis Ulang Sekarang',
  'Generate catchy titles for your stories':
      'Buat judul menarik untuk cerita Anda',
  'Generate Titles': 'Buat Judul',

  // Rewrite Story Tool
  'Rewrite Story': 'Tulis Ulang Cerita',
  'Paste Your Story': 'Tempel Cerita Anda',
  'Paste your story here to rewrite...':
      'Tempel cerita Anda di sini untuk ditulis ulang...',
  'Select Tone': 'Pilih Nada',
  'Rewrite Style': 'Gaya Penulisan Ulang',
  'Output Length': 'Panjang Output',
  'Please paste your story': 'Silakan tempel cerita Anda',
  'Story is too short. Please provide more content.':
      'Cerita terlalu pendek. Berikan lebih banyak konten.',
  // Tone options
  'Same': 'Sama',
  'More Dramatic': 'Lebih Dramatis',
  'More Humorous': 'Lebih Lucu',
  'More Emotional': 'Lebih Emosional',
  'More Suspenseful': 'Lebih Menegangkan',
  'Lighter': 'Lebih Ringan',
  // Style options
  'Improved': 'Ditingkatkan',
  'Simplified': 'Disederhanakan',
  'More Descriptive': 'Lebih Deskriptif',
  'More Dialogue': 'Lebih Banyak Dialog',
  'More Action': 'Lebih Banyak Aksi',
  'Literary': 'Sastra',
  // Length options
  'Shorter': 'Lebih Pendek',
  'Longer': 'Lebih Panjang',
  'Much Longer': 'Jauh Lebih Panjang',

  // Title Generator Tool
  'Title Generator': 'Generator Judul',
  'Story/Book Topic': 'Topik Cerita/Buku',
  'Keywords (Optional)': 'Kata Kunci (Opsional)',
  'Describe your story topic or theme...':
      'Jelaskan topik atau tema cerita Anda...',
  'e.g., magic, dragon, adventure': 'mis., sihir, naga, petualangan',
  'Title For': 'Judul Untuk',
  'Title Style': 'Gaya Judul',
  'Number of Titles': 'Jumlah Judul',
  // Type options
  'Book': 'Buku',
  'Short Story': 'Cerita Pendek',
  'Novel': 'Novel',
  'Chapter': 'Bab',
  'Series': 'Seri',
  // Title Style options
  'Simple': 'Sederhana',
  'Mysterious': 'Misterius',
  'Dramatic': 'Dramatis',
  'Catchy': 'Menarik',
  'Poetic': 'Puitis',
  // Genre options
  'Kids': 'Anak-anak',

  // Blog Writer Tool
  'Blog Writer': 'Penulis Blog',
  'Blog Topic': 'Topik Blog',
  'Target Keywords': 'Kata Kunci Target',
  'Target Audience (Optional)': 'Target Audiens (Opsional)',
  'Enter your blog topic or title...': 'Masukkan topik atau judul blog Anda...',
  'e.g., AI writing, content marketing, SEO tips':
      'mis., penulisan AI, pemasaran konten, tips SEO',
  'e.g., small business owners, bloggers': 'mis., pemilik usaha kecil, blogger',
  'Article Type': 'Jenis Artikel',
  'Writing Tone': 'Nada Penulisan',
  'Article Length': 'Panjang Artikel',
  'SEO Options': 'Opsi SEO',
  'Include Meta Description': 'Sertakan Deskripsi Meta',
  'Include Keyword Suggestions': 'Sertakan Saran Kata Kunci',
  'Include FAQs Section': 'Sertakan Bagian FAQ',
  'Please enter a blog topic': 'Silakan masukkan topik blog',
  'Generate Blog': 'Buat Blog',
  'SEO optimized articles with keywords':
      'Artikel yang dioptimalkan SEO dengan kata kunci',
  'Write Blog': 'Tulis Blog',
  // Article Types
  'SEO Article': 'Artikel SEO',
  'How-To Guide': 'Panduan Cara',
  'Listicle': 'Artikel Daftar',
  'Product Review': 'Ulasan Produk',
  'Opinion Piece': 'Artikel Opini',
  'News Article': 'Artikel Berita',
  // Blog Tones
  'Professional': 'Profesional',
  'Casual': 'Santai',
  'Informative': 'Informatif',
  'Persuasive': 'Persuasif',
  'Friendly': 'Ramah',
  'Authoritative': 'Otoritatif',
  // Blog Lengths
  'Short (500-800)': 'Pendek (500-800)',
  'Medium (800-1500)': 'Sedang (800-1500)',
  'Long (1500-2500)': 'Panjang (1500-2500)',
  'Detailed (2500+)': 'Detail (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'Skrip YouTube',
  'Video Topic': 'Topik Video',
  'Key Points (Optional)': 'Poin Kunci (Opsional)',
  'What is your video about?': 'Tentang apa video Anda?',
  'List key points to cover (optional)...':
      'Daftar poin kunci yang akan dibahas (opsional)...',
  'Video Duration': 'Durasi Video',
  'Script Options': 'Opsi Skrip',
  'Include Hook/Intro': 'Sertakan Hook/Intro',
  'Include Call-to-Action': 'Sertakan Ajakan Bertindak',
  'Include Timestamps': 'Sertakan Stempel Waktu',
  'Please enter a video topic': 'Silakan masukkan topik video',
  'Generate Script': 'Buat Skrip',
  'Create scripts for videos & reels': 'Buat skrip untuk video & reel',
  'Create Script': 'Buat Skrip',
  // Script Types
  'Storytime': 'Waktu Cerita',
  'Documentary': 'Dokumenter',
  'Short Reel': 'Reel Pendek',
  'Educational': 'Edukatif',
  'Review': 'Ulasan',
  'Tutorial': 'Tutorial',
  // Durations
  '< 1 min (Shorts)': '< 1 menit (Shorts)',
  '1-3 min': '1-3 menit',
  '5-10 min': '5-10 menit',
  '10-20 min': '10-20 menit',
  '20+ min': '20+ menit',
  // Script Tones
  'Engaging': 'Menarik',
  'Energetic': 'Energik',
  'Calm': 'Tenang',
  'Funny': 'Lucu',

  // Story Generator - Styles
  'Inspired': 'Terinspirasi',

  // Script Writer - Script Tones (formats)
  'Film Script': 'Naskah Film',
  'Stage Play': 'Drama Panggung',
  'Scene Breakdown': 'Rincian Adegan',
  'Dialogue Only': 'Hanya Dialog',

  // Ad & UI
  'Ad loading please wait..': 'Iklan sedang dimuat, mohon tunggu..',

  // Word Counter & Reading Time
  'Words:': 'Kata:',
  'Reading:': 'Membaca:',

  // Missing strings from hi.dart
  'Adventure': 'Petualangan',
};
