import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> is_ = {
  AppKeys.lblChooseLanguage: "Veldu tungumál",
  "All": "Allt",
  "AI Story Generator": "AI sögugenerator",
  "Story Generator": "Sögugenerator",
  "Essay Writer": "Ritgerðarhöfundur",
  "Essay length": "Lengd ritgerðar",
  "Script Generator": "Handritsgenerator",
  "Create original stories in seconds":
      "Búðu til upprunalegar sögur á sekúndum",
  "Academic writing made simple": "Akademísk skrif einfölduð",
  "Generate powerful scripts for any medium":
      "Búðu til öflug handrit fyrir hvaða miðil sem er",
  "Start Writing": "Byrjaðu að skrifa",
  "Create Now": "Búa til núna",
  "Start Generating": "Byrja að búa til",
  "Your Stories": "Sögurnar þínar",
  "No stories yet": "Engar sögur ennþá",
  "Start creating your first story!": "Byrjaðu að búa til fyrstu söguna þína!",
  "Your Story Space Awaits": "Sögusvæðið þitt bíður",
  "Start your first story and see it appear here":
      "Byrjaðu fyrstu söguna þína og sjáðu hana birtast hér",
  "Language": "Tungumál",
  "Rate us": "Gefðu okkur einkunn",
  "Share us": "Deildu okkur",
  "Privacy Policy": "Persónuverndarstefna",
  "Settings": "Stillingar",
  "Select Language": "Veldu tungumál",
  "Dashboard": "Stjórnborð",
  "BENEFITS": "KOSTIR",
  "Subscribe": "Gerast áskrifandi",
  "Weekly": "Vikulega",
  "Monthly": "Mánaðarlega",
  "Yearly": "Árlega",
  "week": "vika",
  "months": "mánuðir",
  "year": "ár",
  "Terms & Condition": "Skilmálar og skilyrði",
  "No Commitment. Cancel anytime": "Engin skuldbinding. Hættu hvenær sem er",
  "No Payment Now": "Engin greiðsla núna",
  "3 days free": "3 dagar ókeypis",
  "Start your free trial": "Byrjaðu ókeypis prufunotkun",
  "More detailed answers": "Ítarlegri svör",
  "Instant responds": "Skyndisvör",
  "Text recognition": "Textagreining",
  "Powered by AI": "Knúið af gervigreind",
  "Storytelleing": "Sögusögn",
  ' Power': " Kraftur",
  "Unlock your \nFill ": "Opnaðu \nFill ",
  "Your History": "Sagan þín",
  "Terms and Conditions": "Skilmálar og skilyrði",
  "Short": "Stutt",
  "Medium": "Miðlungs",
  "Long": "Langt",
  "Length": "Lengd",
  "Describe your topic...": "Lýstu efninu þínu...",
  "Set Creativity": "Stilla sköpunargáfu",
  "Standard": "Staðlað",
  "Creative": "Skapandi",
  "Complex": "Flókið",
  "Select Genre": "Veldu tegund",
  "Fantasy": "Fantasía",
  "Mystery": "Dularfullur",
  "Thriller": "Spennumynd",
  "Script Tone": "Tónn handrits",
  "Script Type": "Tegund handrits",
  "Comedy": "Gamanleikur",
  "Drama": "Leikrit",
  "Horror": "Hryllingsmynd",
  "Action": "Hasarmynd",
  "Romance": "Rómantík",
  "Go Premium": "Fara í Premium",
  "Unlock Everything": "Opna allt",
  "Unlimited Story Generation": "Ótakmarkað sögusköpun",
  "Write Longer & Detailed Essays": "Skrifaðu lengri og ítarlegri ritgerðir",
  "Advanced Script Writer": "Háþróaður handritshöfundur",
  "Unlock All Styles & Tones": "Opnaðu alla stíla og tóna",
  "No Word/Length Limit": "Engin orða-/lengdartakmörk",
  "Remove All Ads": "Fjarlægja allar auglýsingar",
  "Restore": "Endurheimta",
  "YouTube Video": "YouTube myndband",
  "Podcast": "Hlaðvarp",
  "Reel": "Reel",
  "Motivational": "Hvetjandi",
  "Advertisement": "Auglýsing",
  "Fairy Tale": "Ævintýri",
  "Sci-Fi": "Vísindaskáldskap",
  "Select Style": "Veldu stíl",
  "Imaginative": "Ímyndunarríkur",
  "Innovative": "Nýstárlegur",
  "AI Story Writer": "AI söguhöfundur",
  "Generate": "Búa til",
  "Please wait...": "Vinsamlegast bíðið...",
  "Result": "Niðurstaða",
  "Regenerate": "Endurgera",
  "Download": "Hlaða niður",
  "Text copied to clipboard!": "Texti afritaður á klippiborð!",
  "Please enter a topic": "Vinsamlegast sláðu inn efni",
  "Story Magic": "Sögutöfrar",
  "Let AI bring your thoughts to a full story":
      "Leyfðu gervigreind að breyta hugsunum þínum í fulla sögu",
  "Smart Scripts": "Snjallt handrit",
  "From concept to script—fast, easy, and creative":
      "Frá hugmynd til handrits—hratt, auðvelt og skapandi",
  "Perfect Essays": "Fullkomnar ritgerðir",
  "You have reached your free limit": "Þú hefur náð ókeypis hámarkinu þínu",
  "Donwload": "Hlaða niður",
  "Press again to exit app": "Ýttu aftur til að hætta í appinu",
  "Saved to files": "TXT skrá vistuð!",
  "Error: Please try again": "Villa: Vinsamlegast reyndu aftur",
  "Subscription expired": "Áskrift útrunnin",
  "Purchase cancelled": "Kaupum hætt",
  "Purchase failed": "Kaup mistókust",
  "Restore failed": "Endurheimt mistókst",
  "Purchase Successful!": "Kaup tókust!",
  "Short (200-500 words)": "Stutt (200-500 orð)",
  "Medium (500-1000 words)": "Miðlungs (500-1000 orð)",
  "Large (1000+ words)": "Stórt (1000+ orð)",
  "Academic Level": "Akademískt stig",
  "Type of Paper": "Tegund ritgerðar",
  "High School": "Framhaldsskóli",
  "College": "Háskóli",
  "Short Film": "Stuttmynd",
  "University": "Háskóli",
  "Masters": "Meistaranám",
  "Custom": "Sérsniðið",
  "Tiktok Video": "TikTok myndband",
  "Movie": "Kvikmynd",
  "Expository": "Útskýrandi",
  "Argumentative": "Rökræður",
  "Narrative": "Frásagnir",
  "Descriptive": "Lýsandi",
  "We're sorry to hear that 😔": "Okkur þykir miður að heyra það 😔",
  "We'll try to improve 🙁": "Við munum reyna að bæta okkur 🙁",
  "Thanks for your feedback 🙂": "Takk fyrir álit þitt 🙂",
  "Great! We're glad you like it 😊": "Frábært! Við erum ánægð að þér líkar 😊",
  "Awesome! Thank you so much! 🎉": "Æðislegt! Þökkum kærlega! 🎉",
  "Maybe Later": "Kannski seinna",
  "Tap a star to rate your experience": "Pikkaðu á stjörnu til að gefa einkunn",
  "Enjoying AI Math Solver?": "Líkar þér AI stærðfræðileysirinn?",
  "Thank you for rating us": "Takk fyrir að gefa okkur einkunn",
  "Submit Rating": "Senda einkunn",
  "Hindi": "Hindí",
  "Enjoying AI Story Generator?": "Líkar þér AI sögugeneratorinn?",
  AppKeys.arabic: "Arabíska",
  AppKeys.chinese: "Kínverska",
  AppKeys.english: "Enska",
  AppKeys.french: "Franska",
  AppKeys.german: "Þýska",
  AppKeys.hindi: "Hindí",
  AppKeys.indonesian: "Indónesíska",
  AppKeys.japanese: "Japanska",
  AppKeys.korean: "Kóreska",
  AppKeys.portuguese: "Portúgalska",
  AppKeys.russian: "Rússneska",
  AppKeys.spanish: "Spænska",
  AppKeys.turkish: "Tyrkneska",
  'Download As': 'Hlaða niður sem',
  'Choose format to download': 'Veldu snið til niðurhals',
  'Text File': 'Textaskrá',
  'PDF File': 'PDF skrá',
  'Copy': 'Afrita',
  'Share': 'Deila',
  'Text copied!': 'Texti afritaður!',
  'PDF saved successfully!': 'PDF vistað!',
  'Error creating PDF: Please try again':
      'Villa við PDF: Vinsamlegast reyndu aftur',
  'Character Story': 'Persónusaga',
  'Character Details': 'Upplýsingar um persónu',
  'Character Name': 'Nafn persónu',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Aldur (t.d., 25, Ungur fullorðinn, Forn)',
  'Personality (e.g., brave, shy, cunning)':
      'Persónuleiki (t.d., hugaður, feiminn, slægur)',
  'Role (e.g., Hero, Villain, Mentor)':
      'Hlutverk (t.d., Hetja, Illmenni, Leiðbeinandi)',
  'Additional Details (optional)': 'Viðbótarupplýsingar (valfrjálst)',
  'Output Style': 'Úttaksstíll',
  'Generate Character': 'Búa til persónu',
  'Please enter character name': 'Vinsamlegast sláðu inn nafn persónu',
  'Please enter character role': 'Vinsamlegast sláðu inn hlutverk persónu',
  'Detailed': 'Ítarlegt',
  'Brief': 'Stutt',
  'Elaborate': 'Ítarlegt',
  'Create detailed character backstories': 'Búðu til ítarlegar persónusögur',
  'Create Character': 'Búa til persónu',
  'Transform and improve your existing stories':
      'Umbreyttu og bættu sögurnar þínar',
  'Rewrite Now': 'Endurskrifa núna',
  'Generate catchy titles for your stories':
      'Búðu til áberandi titla fyrir sögurnar þínar',
  'Generate Titles': 'Búa til titla',
  'Rewrite Story': 'Endurskrifa sögu',
  'Paste Your Story': 'Límdu söguna þína',
  'Paste your story here to rewrite...':
      'Límdu söguna þína hér til endurskrifa...',
  'Select Tone': 'Veldu tón',
  'Rewrite Style': 'Endurskrifunarstíll',
  'Output Length': 'Lengd úttaks',
  'Please paste your story': 'Vinsamlegast límdu söguna þína',
  'Story is too short. Please provide more content.':
      'Sagan er of stutt. Vinsamlegast gefðu meira efni.',
  'Same': 'Sama',
  'More Dramatic': 'Meira dramatískt',
  'More Humorous': 'Fyndnara',
  'More Emotional': 'Tilfinningalegra',
  'More Suspenseful': 'Meira spennt',
  'Lighter': 'Léttara',
  'Improved': 'Endurbætt',
  'Simplified': 'Einfaldað',
  'More Descriptive': 'Meira lýsandi',
  'More Dialogue': 'Fleiri samræður',
  'More Action': 'Meiri spenna',
  'Literary': 'Bókmenntalegt',
  'Shorter': 'Styttra',
  'Longer': 'Lengra',
  'Much Longer': 'Miklu lengra',
  'Title Generator': 'Titilgenerator',
  'Story/Book Topic': 'Efni sögu/bókar',
  'Keywords (Optional)': 'Lykilorð (valfrjálst)',
  'Describe your story topic or theme...': 'Lýstu efni eða þema sögunnar...',
  'e.g., magic, dragon, adventure': 't.d., galdrar, dreki, ævintýri',
  'Title For': 'Titill fyrir',
  'Title Style': 'Titilstíll',
  "Adventure": "Ævintýri",
  'Number of Titles': 'Fjöldi titla',
  'Book': 'Bók',
  'Short Story': 'Smásaga',
  'Novel': 'Skáldsaga',
  'Chapter': 'Kafli',
  'Series': 'Þáttaröð',
  'Simple': 'Einfalt',
  'Mysterious': 'Dularfullt',
  'Dramatic': 'Dramatískt',
  'Catchy': 'Áberandi',
  'Poetic': 'Ljóðrænt',
  'Kids': 'Börn',
  'Blog Writer': 'Blogghöfundur',
  'Blog Topic': 'Efni bloggs',
  'Target Keywords': 'Marklykilorð',
  'Target Audience (Optional)': 'Markhópur (valfrjálst)',
  'Enter your blog topic or title...': 'Sláðu inn efni eða titil bloggs...',
  'e.g., AI writing, content marketing, SEO tips':
      't.d., AI skrif, efnismarkaðssetning, SEO ráð',
  'e.g., small business owners, bloggers':
      't.d., eigendur lítilla fyrirtækja, bloggarar',
  'Article Type': 'Tegund greinar',
  'Writing Tone': 'Tónn skrifa',
  'Article Length': 'Lengd greinar',
  'SEO Options': 'SEO valkostir',
  'Include Meta Description': 'Hafa meta lýsingu',
  'Include Keyword Suggestions': 'Hafa lykilorðatillögur',
  'Include FAQs Section': 'Hafa algengar spurningar',
  'Please enter a blog topic': 'Vinsamlegast sláðu inn efni bloggs',
  'Generate Blog': 'Búa til blogg',
  'SEO optimized articles with keywords':
      'SEO fínstilltar greinar með lykilorðum',
  'Write Blog': 'Skrifa blogg',
  'SEO Article': 'SEO grein',
  'How-To Guide': 'Leiðbeiningar',
  'Listicle': 'Listagrein',
  'Product Review': 'Vörumat',
  'Opinion Piece': 'Skoðanagrein',
  'News Article': 'Fréttir',
  'Professional': 'Faglegur',
  'Casual': 'Óformlegur',
  'Informative': 'Fræðandi',
  'Persuasive': 'Sannfærandi',
  'Friendly': 'Vingjarnlegur',
  'Authoritative': 'Forystulegu',
  'Short (500-800)': 'Stutt (500-800)',
  'Medium (800-1500)': 'Miðlungs (800-1500)',
  'Long (1500-2500)': 'Langt (1500-2500)',
  'Detailed (2500+)': 'Ítarlegt (2500+)',
  'YouTube Script': 'YouTube handrit',
  'Video Topic': 'Efni myndbands',
  'Key Points (Optional)': 'Lykilatriði (valfrjálst)',
  'What is your video about?': 'Um hvað er myndbandið þitt?',
  'List key points to cover (optional)...':
      'Listi yfir lykilatriði (valfrjálst)...',
  'Video Duration': 'Lengd myndbands',
  'Script Options': 'Valkostir handrits',
  'Include Hook/Intro': 'Hafa krók/inngangur',
  'Include Call-to-Action': 'Hafa ákall til aðgerða',
  'Include Timestamps': 'Hafa tímamörk',
  'Please enter a video topic': 'Vinsamlegast sláðu inn efni myndbands',
  'Generate Script': 'Búa til handrit',
  'Create scripts for videos & reels':
      'Búðu til handrit fyrir myndbönd og reels',
  'Create Script': 'Búa til handrit',
  'Storytime': 'Sögutími',
  'Documentary': 'Heimildamynd',
  'Short Reel': 'Stutt reel',
  'Educational': 'Fræðslu',
  'Review': 'Umsögn',
  'Tutorial': 'Kennsla',
  '< 1 min (Shorts)': '< 1 mín (Shorts)',
  '1-3 min': '1-3 mín',
  '5-10 min': '5-10 mín',
  '10-20 min': '10-20 mín',
  '20+ min': '20+ mín',
  'Engaging': 'Grípandi',
  'Energetic': 'Orkumikill',
  'Calm': 'Rólegur',
  'Funny': 'Fyndinn',
  'Inspired': 'Innblásinn',
  'Film Script': 'Kvikmyndahandrit',
  'Stage Play': 'Sviðsverk',
  'Scene Breakdown': 'Senugreining',
  'Dialogue Only': 'Aðeins samræður',
  'Ad loading please wait..': 'Auglýsing hlaðast, vinsamlegast bíðið..',
  'Words:': 'Orð:',
  'Reading:': 'Lestur:',
};
