import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> it = {
  AppKeys.lblChooseLanguage: "Scegli lingua",
  "All": "Tutto",
  "AI Story Generator": "Generatore di storie AI",
  "Story Generator": "Generatore di storie",
  "Essay Writer": "Scrittore di saggi",
  "Essay length": "Lunghezza del saggio",
  "Script Generator": "Generatore di script",
  "Create original stories in seconds":
      "Crea storie originali in pochi secondi",
  "Academic writing made simple": "Scrittura accademica resa semplice",
  "Generate powerful scripts for any medium":
      "Genera script potenti per qualsiasi mezzo",
  "Start Writing": "Inizia a scrivere",
  "Create Now": "Crea ora",
  "Start Generating": "Inizia a generare",
  "Your Stories": "Le tue storie",
  "No stories yet": "Nessuna storia ancora",
  "Start creating your first story!": "Inizia a creare la tua prima storia!",
  "Your Story Space Awaits": "Il tuo spazio per le storie ti aspetta",
  "Start your first story and see it appear here":
      "Inizia la tua prima storia e vedila apparire qui",
  "Language": "Lingua",
  "Rate us": "Valutaci",
  "Share us": "Condividici",
  "Privacy Policy": "Informativa sulla privacy",
  "Settings": "Impostazioni",
  "Select Language": "Seleziona lingua",
  "Dashboard": "Pannello",
  "BENEFITS": "VANTAGGI",
  "Subscribe": "Abbonati",
  "Weekly": "Settimanale",
  "Monthly": "Mensile",
  "Yearly": "Annuale",
  "week": "settimana",
  "months": "mesi",
  "year": "anno",
  "Terms & Condition": "Termini e condizioni",
  "No Commitment. Cancel anytime":
      "Nessun impegno. Annulla in qualsiasi momento",
  "No Payment Now": "Nessun pagamento ora",
  "3 days free": "3 giorni gratis",
  "Start your free trial": "Inizia la tua prova gratuita",
  "More detailed answers": "Risposte più dettagliate",
  "Instant responds": "Risposte istantanee",
  "Text recognition": "Riconoscimento del testo",
  "Powered by AI": "Alimentato dall'AI",
  "Storytelleing": "Narrazione",
  ' Power': " Potenza",
  "Unlock your \nFill ": "Sblocca il tuo \nFill ",
  "Your History": "La tua cronologia",
  "Terms and Conditions": "Termini e condizioni",
  "Short": "Corto",
  "Medium": "Medio",
  "Long": "Lungo",
  "Length": "Lunghezza",
  "Describe your topic...": "Descrivi il tuo argomento...",
  "Set Creativity": "Imposta creatività",
  "Standard": "Standard",
  "Creative": "Creativo",
  "Complex": "Complesso",
  "Select Genre": "Seleziona genere",
  "Fantasy": "Fantasy",
  "Mystery": "Mistero",
  "Thriller": "Thriller",
  "Script Tone": "Tono dello script",
  "Script Type": "Tipo di script",
  "Comedy": "Commedia",
  "Drama": "Dramma",
  "Horror": "Horror",
  "Action": "Azione",
  "Romance": "Romantico",
  "Go Premium": "Diventa Premium",
  "Unlock Everything": "Sblocca tutto",
  "Unlimited Story Generation": "Generazione illimitata di storie",
  "Write Longer & Detailed Essays": "Scrivi saggi più lunghi e dettagliati",
  "Advanced Script Writer": "Scrittore di script avanzato",
  "Unlock All Styles & Tones": "Sblocca tutti gli stili e i toni",
  "No Word/Length Limit": "Nessun limite di parole/lunghezza",
  "Remove All Ads": "Rimuovi tutte le pubblicità",
  "Restore": "Ripristina",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivazionale",
  "Advertisement": "Pubblicità",
  "Fairy Tale": "Fiaba",
  "Sci-Fi": "Fantascienza",
  "Select Style": "Seleziona stile",
  "Imaginative": "Fantasioso",
  "Innovative": "Innovativo",
  "AI Story Writer": "Scrittore di storie AI",
  "Generate": "Genera",
  "Please wait...": "Attendere prego...",
  "Result": "Risultato",
  "Regenerate": "Rigenera",
  "Download": "Scarica",
  "Text copied to clipboard!": "Testo copiato negli appunti!",
  "Please enter a topic": "Inserisci un argomento",
  "Story Magic": "Magia delle storie",
  "Let AI bring your thoughts to a full story":
      "Lascia che l'AI trasformi i tuoi pensieri in una storia completa",
  "Smart Scripts": "Script intelligenti",
  "From concept to script—fast, easy, and creative":
      "Dal concetto allo script—veloce, facile e creativo",
  "Perfect Essays": "Saggi perfetti",
  "You have reached your free limit": "Hai raggiunto il tuo limite gratuito",
  "Donwload": "Scarica",
  "Press again to exit app": "Premi di nuovo per uscire dall'app",
  "Saved to files": "File TXT salvato con successo!",
  "Error: Please try again": "Errore: Riprova",
  "Subscription expired": "Abbonamento scaduto",
  "Purchase cancelled": "Acquisto annullato",
  "Purchase failed": "Acquisto fallito",
  "Restore failed": "Ripristino fallito",
  "Purchase Successful!": "Acquisto riuscito!",
  "Short (200-500 words)": "Corto (200-500 parole)",
  "Medium (500-1000 words)": "Medio (500-1000 parole)",
  "Large (1000+ words)": "Grande (1000+ parole)",
  "Academic Level": "Livello accademico",
  "Type of Paper": "Tipo di elaborato",
  "High School": "Liceo",
  "College": "Università",
  "Short Film": "Cortometraggio",
  "University": "Università",
  "Masters": "Master",
  "Custom": "Personalizzato",
  "Tiktok Video": "Video TikTok",
  "Movie": "Film",
  "Expository": "Espositivo",
  "Argumentative": "Argomentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descrittivo",
  "We're sorry to hear that 😔": "Ci dispiace sentirlo 😔",
  "We'll try to improve 🙁": "Cercheremo di migliorare 🙁",
  "Thanks for your feedback 🙂": "Grazie per il tuo feedback 🙂",
  "Great! We're glad you like it 😊": "Ottimo! Siamo felici che ti piaccia 😊",
  "Awesome! Thank you so much! 🎉": "Fantastico! Grazie mille! 🎉",
  "Maybe Later": "Forse dopo",
  "Tap a star to rate your experience":
      "Tocca una stella per valutare la tua esperienza",
  "Enjoying AI Math Solver?": "Ti piace il risolutore di matematica AI?",
  "Thank you for rating us": "Grazie per averci valutato",
  "Submit Rating": "Invia valutazione",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Ti piace il generatore di storie AI?",
  AppKeys.arabic: "Arabo",
  AppKeys.chinese: "Cinese",
  AppKeys.english: "Inglese",
  AppKeys.french: "Francese",
  AppKeys.german: "Tedesco",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesiano",
  AppKeys.japanese: "Giapponese",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Portoghese",
  AppKeys.russian: "Russo",
  AppKeys.spanish: "Spagnolo",
  AppKeys.turkish: "Turco",
  'Download As': 'Scarica come',
  'Choose format to download': 'Scegli il formato da scaricare',
  'Text File': 'File di testo',
  'PDF File': 'File PDF',
  'Copy': 'Copia',
  'Share': 'Condividi',
  'Text copied!': 'Testo copiato!',
  'PDF saved successfully!': 'PDF salvato con successo!',
  'Error creating PDF: Please try again':
      'Errore nella creazione del PDF: Riprova',
  'Character Story': 'Storia del personaggio',
  'Character Details': 'Dettagli del personaggio',
  'Character Name': 'Nome del personaggio',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Età (es., 25, Giovane adulto, Antico)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalità (es., coraggioso, timido, astuto)',
  'Role (e.g., Hero, Villain, Mentor)': 'Ruolo (es., Eroe, Cattivo, Mentore)',
  'Additional Details (optional)': 'Dettagli aggiuntivi (opzionale)',
  'Output Style': 'Stile di output',
  'Generate Character': 'Genera personaggio',
  'Please enter character name': 'Inserisci il nome del personaggio',
  'Please enter character role': 'Inserisci il ruolo del personaggio',
  'Detailed': 'Dettagliato',
  'Brief': 'Breve',
  'Elaborate': 'Elaborato',
  'Create detailed character backstories':
      'Crea storie dettagliate dei personaggi',
  'Create Character': 'Crea personaggio',
  'Transform and improve your existing stories':
      'Trasforma e migliora le tue storie esistenti',
  'Rewrite Now': 'Riscrivi ora',
  'Generate catchy titles for your stories':
      'Genera titoli accattivanti per le tue storie',
  'Generate Titles': 'Genera titoli',
  'Rewrite Story': 'Riscrivi storia',
  'Paste Your Story': 'Incolla la tua storia',
  'Paste your story here to rewrite...':
      'Incolla la tua storia qui per riscriverla...',
  'Select Tone': 'Seleziona tono',
  'Rewrite Style': 'Stile di riscrittura',
  'Output Length': 'Lunghezza output',
  'Please paste your story': 'Incolla la tua storia',
  'Story is too short. Please provide more content.':
      'La storia è troppo corta. Fornisci più contenuto.',
  'Same': 'Uguale',
  'More Dramatic': 'Più drammatico',
  'More Humorous': 'Più umoristico',
  'More Emotional': 'Più emotivo',
  'More Suspenseful': 'Più suspense',
  'Lighter': 'Più leggero',
  'Improved': 'Migliorato',
  'Simplified': 'Semplificato',
  'More Descriptive': 'Più descrittivo',
  'More Dialogue': 'Più dialogo',
  'More Action': 'Più azione',
  'Literary': 'Letterario',
  'Shorter': 'Più corto',
  'Longer': 'Più lungo',
  'Much Longer': 'Molto più lungo',
  'Title Generator': 'Generatore di titoli',
  'Story/Book Topic': 'Argomento storia/libro',
  'Keywords (Optional)': 'Parole chiave (opzionale)',
  'Describe your story topic or theme...':
      'Descrivi il tema della tua storia...',
  'e.g., magic, dragon, adventure': 'es., magia, drago, avventura',
  'Title For': 'Titolo per',
  'Title Style': 'Stile del titolo',
  "Adventure": "Avventura",
  'Number of Titles': 'Numero di titoli',
  'Book': 'Libro',
  'Short Story': 'Racconto',
  'Novel': 'Romanzo',
  'Chapter': 'Capitolo',
  'Series': 'Serie',
  'Simple': 'Semplice',
  'Mysterious': 'Misterioso',
  'Dramatic': 'Drammatico',
  'Catchy': 'Accattivante',
  'Poetic': 'Poetico',
  'Kids': 'Bambini',
  'Blog Writer': 'Scrittore di blog',
  'Blog Topic': 'Argomento del blog',
  'Target Keywords': 'Parole chiave target',
  'Target Audience (Optional)': 'Pubblico target (opzionale)',
  'Enter your blog topic or title...':
      'Inserisci l\'argomento o il titolo del tuo blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'es., scrittura AI, content marketing, consigli SEO',
  'e.g., small business owners, bloggers': 'es., piccoli imprenditori, blogger',
  'Article Type': 'Tipo di articolo',
  'Writing Tone': 'Tono di scrittura',
  'Article Length': 'Lunghezza articolo',
  'SEO Options': 'Opzioni SEO',
  'Include Meta Description': 'Includi meta descrizione',
  'Include Keyword Suggestions': 'Includi suggerimenti parole chiave',
  'Include FAQs Section': 'Includi sezione FAQ',
  'Please enter a blog topic': 'Inserisci un argomento del blog',
  'Generate Blog': 'Genera blog',
  'SEO optimized articles with keywords':
      'Articoli ottimizzati SEO con parole chiave',
  'Write Blog': 'Scrivi blog',
  'SEO Article': 'Articolo SEO',
  'How-To Guide': 'Guida pratica',
  'Listicle': 'Listicle',
  'Product Review': 'Recensione prodotto',
  'Opinion Piece': 'Articolo d\'opinione',
  'News Article': 'Articolo di notizie',
  'Professional': 'Professionale',
  'Casual': 'Casual',
  'Informative': 'Informativo',
  'Persuasive': 'Persuasivo',
  'Friendly': 'Amichevole',
  'Authoritative': 'Autorevole',
  'Short (500-800)': 'Corto (500-800)',
  'Medium (800-1500)': 'Medio (800-1500)',
  'Long (1500-2500)': 'Lungo (1500-2500)',
  'Detailed (2500+)': 'Dettagliato (2500+)',
  'YouTube Script': 'Script YouTube',
  'Video Topic': 'Argomento video',
  'Key Points (Optional)': 'Punti chiave (opzionale)',
  'What is your video about?': 'Di cosa parla il tuo video?',
  'List key points to cover (optional)...':
      'Elenca i punti chiave da trattare (opzionale)...',
  'Video Duration': 'Durata video',
  'Script Options': 'Opzioni script',
  'Include Hook/Intro': 'Includi gancio/intro',
  'Include Call-to-Action': 'Includi invito all\'azione',
  'Include Timestamps': 'Includi marcature temporali',
  'Please enter a video topic': 'Inserisci un argomento video',
  'Generate Script': 'Genera script',
  'Create scripts for videos & reels': 'Crea script per video e reel',
  'Create Script': 'Crea script',
  'Storytime': 'Ora della storia',
  'Documentary': 'Documentario',
  'Short Reel': 'Reel corto',
  'Educational': 'Educativo',
  'Review': 'Recensione',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Coinvolgente',
  'Energetic': 'Energico',
  'Calm': 'Calmo',
  'Funny': 'Divertente',
  'Inspired': 'Ispirato',
  'Film Script': 'Sceneggiatura',
  'Stage Play': 'Opera teatrale',
  'Scene Breakdown': 'Analisi della scena',
  'Dialogue Only': 'Solo dialogo',
  'Ad loading please wait..': 'Caricamento pubblicità, attendere..',
  'Words:': 'Parole:',
  'Reading:': 'Lettura:',
};
