import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ja = {
  AppKeys.lblChooseLanguage: "言語を選択",
  "All": "すべて",
  "AI Story Generator": "AIストーリージェネレーター",
  "Story Generator": "ストーリージェネレーター",
  "Essay Writer": "エッセイライター",
  "Essay length": "エッセイの長さ",
  "Script Generator": "スクリプトジェネレーター",
  "Create original stories in seconds": "数秒で元のストーリーを作成",
  "Academic writing made simple": "学術的な執筆を簡単に",
  "Generate powerful scripts for any medium": "あらゆるメディアのための強力なスクリプトを生成",
  "Start Writing": "書き始める",
  "Create Now": "今すぐ作成",
  "Start Generating": "生成を開始",
  "Your Stories": "あなたのストーリー",
  "No stories yet": "まだストーリーがありません",
  "Start creating your first story!": "最初のストーリーを作成してください！",
  "Your Story Space Awaits": "あなたのストーリースペースが待っています",
  "Start your first story and see it appear here":
      "最初のストーリーを開始して、ここに表示されるのを見てください",
  "Language": "言語",
  "Rate us": "私たちを評価してください",
  "Share us": "私たちを共有してください",
  "Privacy Policy": "プライバシーポリシー",
  "Settings": "設定",
  "Select Language": "言語を選択",
  "Dashboard": "ダッシュボード",
  "BENEFITS": "メリット",
  "Subscribe": "購読する",
  "Weekly": "週間",
  "Monthly": "月間",
  "Yearly": "年間",
  "week": "週",
  "months": "ヶ月",
  "year": "年",
  "Terms & Condition": "利用規約",
  "No Commitment. Cancel anytime": "コミットメントなし。いつでもキャンセル可能",
  "No Payment Now": "今は支払いなし",
  "3 days free": "3日間無料",
  "Start your free trial": "無料トライアルを開始",
  "More detailed answers": "より詳細な回答",
  "Instant responds": "即座の応答",
  "Text recognition": "テキスト認識",
  "Powered by AI": "AIが搭載",
  "Storytelleing": "ストーリーテリング",
  " Power": "パワー",
  "Unlock your \nFill ": "あなたの\nFillをロック解除",
  "Your History": "あなたの履歴",
  "Terms and Conditions": "利用規約",
  "Short": "短い",
  "Medium": "中",
  "Long": "長い",
  "Length": "長さ",
  "Describe your topic...": "トピックを説明してください...",
  "Set Creativity": "創造性を設定",
  "Standard": "標準",
  "Creative": "創造的",
  "Complex": "複雑",
  "Select Genre": "ジャンルを選択",
  "Fantasy": "ファンタジー",
  "Mystery": "ミステリー",
  "Thriller": "スリラー",
  "Script Tone": "スクリプトトーン",
  "Script Type": "スクリプトタイプ",
  "Comedy": "コメディ",
  "Drama": "ドラマ",
  "Horror": "ホラー",
  "Action": "アクション",
  "Romance": "ロマンス",
  "Go Premium": "プレミアムに移行",
  "Unlock Everything": "すべてをアンロック",
  "Unlimited Story Generation": "無制限のストーリー生成",
  "Write Longer & Detailed Essays": "より長く詳細なエッセイを書く",
  "Advanced Script Writer": "高度なスクリプトライター",
  "Unlock All Styles & Tones": "すべてのスタイルとトーンをアンロック",
  "No Word/Length Limit": "単語/長さの制限なし",
  "Remove All Ads": "すべての広告を削除",
  "3 days free": "3日間無料",
  "Restore": "復元",
  "YouTube Video": "YouTube動画",
  "Podcast": "ポッドキャスト",
  "Reel": "リール",
  "Motivational": "モチベーション",
  "Advertisement": "広告",
  "Fairy Tale": "童話",
  "Sci-Fi": "サイエンスフィクション",
  "Select Style": "スタイルを選択",
  "Imaginative": "想像力豊かな",
  "Innovative": "革新的",
  "AI Story Writer": "AIストーリーライター",
  "Generate": "生成",
  "Please wait...": "お待ちください...",
  "Result": "結果",
  "Regenerate": "再生成",
  "Download": "ダウンロード",
  "Text copied to clipboard!": "テキストがクリップボードにコピーされました！",
  "Please enter a topic": "トピックを入力してください",
  "Story Magic": "ストーリーマジック",
  "Let AI bring your thoughts to a full story": "AIがあなたの思いを完全なストーリーに変える",
  "Smart Scripts": "スマートスクリプト",
  "From concept to script—fast, easy, and creative": "コンセプトからスクリプトまで—速い、簡単、創造的",
  "Perfect Essays": "完璧なエッセイ",
  "You have reached your free limit": "無料制限に達しました",
  "Donwload": "ダウンロード",
  "Press again to exit app": "もう一度押してアプリを終了",
  "Saved to files": "TXTファイルが正常に保存されました！",
  "Error: Please try again": "エラー：もう一度試してください",
  "Subscription expired": "サブスクリプションの有効期限が切れています",
  "Purchase cancelled": "購入がキャンセルされました",
  "Purchase failed": "購入に失敗しました",
  "Restore failed": "復元に失敗しました",
  "Purchase Successful!": "購入成功！",
  "Short (200-500 words)": "短い（200-500語）",
  "Medium (500-1000 words)": "中（500-1000語）",
  "Large (1000+ words)": "大（1000語以上）",
  "Academic Level": "学位",
  "Type of Paper": "論文の種類",
  "High School": "高校",
  "College": "カレッジ",
  "Short Film": "短編映画",
  "University": "大学",
  "Masters": "修士号",
  "Custom": "カスタム",
  "YouTube Video": "YouTube動画",
  "Podcast": "ポッドキャスト",
  "Reel": "リール",
  "Tiktok Video": "TikTok動画",
  "Movie": "映画",
  "Expository": "説明的",
  "Argumentative": "論証的",
  "Narrative": "物語的",
  "Descriptive": "記述的",
  "We're sorry to hear that 😔": "それを聞いて申し訳ございません 😔",
  "We'll try to improve 🙁": "改善するよう努力します 🙁",
  "Thanks for your feedback 🙂": "フィードバックをありがとうございます 🙂",
  "Great! We're glad you like it 😊": "素晴らしい！気に入っていただき嬉しいです 😊",
  "Awesome! Thank you so much! 🎉": "素晴らしい！ありがとうございました！ 🎉",
  "Maybe Later": "多分後で",
  "Tap a star to rate your experience": "星をタップして体験を評価",
  "Enjoying AI Math Solver?": "AI Math Solverを楽しんでいますか？",
  "Thank you for rating us": "評価していただきありがとうございます",
  "Submit Rating": "評価を送信",
  "Hindi": "ヒンディー語",
  "Enjoying AI Story Generator?": "AIストーリージェネレーターを楽しんでいますか？",
  AppKeys.arabic: "アラビア語",
  AppKeys.chinese: "中国語",
  AppKeys.english: "英語",
  AppKeys.french: "フランス語",
  AppKeys.german: "ドイツ語",
  AppKeys.hindi: "ヒンディー語",
  AppKeys.indonesian: "インドネシア語",
  AppKeys.japanese: "日本語",
  AppKeys.korean: "韓国語",
  AppKeys.portuguese: "ポルトガル語",
  AppKeys.russian: "ロシア語",
  AppKeys.spanish: "スペイン語",
  AppKeys.turkish: "トルコ語",
  "Download As": "名前を付けてダウンロード",
  "Choose format to download": "ダウンロードする形式を選択",
  "Text File": "テキストファイル",
  "PDF File": "PDFファイル",
  "Copy": "コピー",
  "Share": "共有",
  "Text copied!": "テキストがコピーされました！",
  "PDF saved successfully!": "PDFが正常に保存されました！",
  "Error creating PDF: Please try again": "PDFの作成エラー：もう一度試してください",
  "Character Story": "キャラクターストーリー",
  "Character Details": "キャラクターの詳細",
  "Character Name": "キャラクター名",
  "Age (e.g., 25, Young Adult, Ancient)": "年齢（例：25、若い大人、古代）",
  "Personality (e.g., brave, shy, cunning)": "性格（例：勇敢、内気、狡猾）",
  "Role (e.g., Hero, Villain, Mentor)": "役割（例：ヒーロー、悪役、メンター）",
  "Additional Details (optional)": "追加詳細（オプション）",
  "Output Style": "出力スタイル",
  "Generate Character": "キャラクターを生成",
  "Please enter character name": "キャラクター名を入力してください",
  "Please enter character role": "キャラクターの役割を入力してください",
  "Detailed": "詳細",
  "Brief": "簡潔",
  "Elaborate": "精密",
  "Create detailed character backstories": "詳細なキャラクターの背景ストーリーを作成",
  "Create Character": "キャラクターを作成",
  "Transform and improve your existing stories": "既存のストーリーを変換して改善",
  "Rewrite Now": "今すぐ書き直す",
  "Generate catchy titles for your stories": "ストーリーの魅力的なタイトルを生成",
  "Generate Titles": "タイトルを生成",
  "Rewrite Story": "ストーリーを書き直す",
  "Paste Your Story": "ストーリーを貼り付ける",
  "Paste your story here to rewrite...": "書き直すためにストーリーをここに貼り付けてください...",
  "Select Tone": "トーンを選択",
  "Rewrite Style": "スタイルを書き直す",
  "Output Length": "出力長",
  "Please paste your story": "ストーリーを貼り付けてください",
  "Story is too short. Please provide more content.":
      "ストーリーが短すぎます。詳細なコンテンツを提供してください。",
  "Same": "同じ",
  "More Dramatic": "よりドラマチック",
  "More Humorous": "よりユーモア",
  "More Emotional": "より感情的",
  "More Suspenseful": "よりサスペンシフル",
  "Lighter": "より軽い",
  "Improved": "改善された",
  "Simplified": "簡略化された",
  "More Descriptive": "より記述的",
  "More Dialogue": "よりダイアログ",
  "More Action": "より多くのアクション",
  "Literary": "文学的",
  "Shorter": "短い",
  "Longer": "長い",
  "Much Longer": "はるかに長い",
  "Title Generator": "タイトルジェネレーター",
  "Story/Book Topic": "ストーリー/本のトピック",
  "Keywords (Optional)": "キーワード（オプション）",
  "Describe your story topic or theme...": "ストーリーのトピックまたはテーマを説明してください...",
  "e.g., magic, dragon, adventure": "例：魔法、ドラゴン、冒険",
  "Title For": "タイトル対象",
  "Title Style": "タイトルスタイル",
  "Number of Titles": "タイトル数",
  "Book": "本",
  "Short Story": "短編小説",
  "Novel": "小説",
  "Chapter": "章",
  "Series": "シリーズ",
  "Simple": "シンプル",
  "Mysterious": "神秘的",
  "Dramatic": "ドラマチック",
  "Catchy": "魅力的",
  "Poetic": "詩的",
  "Kids": "子供向け",
  "Blog Writer": "ブログライター",
  "Blog Topic": "ブログのトピック",
  "Target Keywords": "ターゲットキーワード",
  "Target Audience (Optional)": "ターゲットオーディエンス（オプション）",
  "Enter your blog topic or title...": "ブログのトピックまたはタイトルを入力してください...",
  "e.g., AI writing, content marketing, SEO tips":
      "例：AI執筆、コンテンツマーケティング、SEOのヒント",
  "e.g., small business owners, bloggers": "例：中小企業の所有者、ブロガー",
  "Article Type": "記事のタイプ",
  "Writing Tone": "執筆トーン",
  "Article Length": "記事の長さ",
  "SEO Options": "SEOオプション",
  "Include Meta Description": "メタ説明を含める",
  "Include Keyword Suggestions": "キーワード提案を含める",
  "Include FAQs Section": "FAQセクションを含める",
  "Please enter a blog topic": "ブログのトピックを入力してください",
  "Generate Blog": "ブログを生成",
  "SEO optimized articles with keywords": "キーワード付きのSEO最適化記事",
  "Write Blog": "ブログを書く",
  "SEO Article": "SEO記事",
  "How-To Guide": "方法ガイド",
  "Listicle": "リスト記事",
  "Product Review": "製品レビュー",
  "Opinion Piece": "意見記事",
  "News Article": "ニュース記事",
  "Professional": "プロフェッショナル",
  "Casual": "カジュアル",
  "Informative": "情報提供",
  "Persuasive": "説得力のある",
  "Friendly": "親切",
  "Authoritative": "権威ある",
  "Short (500-800)": "短い（500-800）",
  "Medium (800-1500)": "中（800-1500）",
  "Long (1500-2500)": "長い（1500-2500）",
  "Detailed (2500+)": "詳細（2500+）",
  "YouTube Script": "YouTubeスクリプト",
  "Video Topic": "ビデオトピック",
  "Key Points (Optional)": "キーポイント（オプション）",
  "What is your video about?": "ビデオは何についてですか？",
  "List key points to cover (optional)...": "カバーするキーポイントをリストアップ（オプション）...",
  "Video Duration": "ビデオの長さ",
  "Script Options": "スクリプトオプション",
  "Include Hook/Intro": "フック/イントロを含める",
  "Include Call-to-Action": "呼び出しアクションを含める",
  "Include Timestamps": "タイムスタンプを含める",
  "Please enter a video topic": "ビデオトピックを入力してください",
  "Generate Script": "スクリプトを生成",
  "Create scripts for videos & reels": "ビデオとリール用のスクリプトを作成",
  "Create Script": "スクリプトを作成",
  "Storytime": "ストーリータイム",
  "Documentary": "ドキュメンタリー",
  "Short Reel": "短いリール",
  "Educational": "教育的",
  "Review": "レビュー",
  "Tutorial": "チュートリアル",
  "< 1 min (Shorts)": "< 1分（ショート）",
  "1-3 min": "1-3分",
  "5-10 min": "5-10分",
  "10-20 min": "10-20分",
  "20+ min": "20+分",
  "Engaging": "魅力的",
  "Energetic": "エネルギッシュ",
  "Calm": "落ち着いた",
  "Funny": "面白い",
  "Inspired": "インスピレーション",
  "Film Script": "映画スクリプト",
  "Stage Play": "舞台劇",
  "Scene Breakdown": "シーンの分析",
  "Dialogue Only": "ダイアログのみ",
  "Ad loading please wait..": "広告を読み込み中、お待ちください...",
  "Words:": "単語：",
  "Reading:": "読み：",
};
