import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ka = {
  AppKeys.lblChooseLanguage: "აირჩიეთ ენა",
  "All": "ყველა",
  "AI Story Generator": "AI ისტორიის გენერატორი",
  "Story Generator": "ისტორიის გენერატორი",
  "Essay Writer": "ესეის მწერალი",
  "Essay length": "ესეის სიგრძე",
  "Script Generator": "სცენარის გენერატორი",
  "Create original stories in seconds":
      "შექმენით ორიგინალური ისტორიები წამებში",
  "Academic writing made simple": "აკადემიური წერა გამარტივებული",
  "Generate powerful scripts for any medium":
      "შექმენით ძლიერი სცენარები ნებისმიერი მედიისთვის",
  "Start Writing": "დაიწყეთ წერა",
  "Create Now": "შექმენით ახლა",
  "Start Generating": "დაიწყეთ გენერირება",
  "Your Stories": "თქვენი ისტორიები",
  "No stories yet": "ისტორიები ჯერ არ არის",
  "Start creating your first story!": "დაიწყეთ თქვენი პირველი ისტორიის შექმნა!",
  "Your Story Space Awaits": "თქვენი ისტორიის სივრცე გელოდებათ",
  "Start your first story and see it appear here":
      "დაიწყეთ თქვენი პირველი ისტორია და ნახეთ აქ",
  "Language": "ენა",
  "Rate us": "შეგვაფასეთ",
  "Share us": "გააზიარეთ",
  "Privacy Policy": "კონფიდენციალურობის პოლიტიკა",
  "Settings": "პარამეტრები",
  "Select Language": "აირჩიეთ ენა",
  "Dashboard": "მართვის პანელი",
  "BENEFITS": "უპირატესობები",
  "Subscribe": "გამოწერა",
  "Weekly": "ყოველკვირეული",
  "Monthly": "ყოველთვიური",
  "Yearly": "წლიური",
  "week": "კვირა",
  "months": "თვეები",
  "year": "წელი",
  "Terms & Condition": "წესები და პირობები",
  "No Commitment. Cancel anytime":
      "ვალდებულების გარეშე. გააუქმეთ ნებისმიერ დროს",
  "No Payment Now": "ახლა გადახდა არ არის",
  "3 days free": "3 დღე უფასო",
  "Start your free trial": "დაიწყეთ უფასო საცდელი პერიოდი",
  "More detailed answers": "უფრო დეტალური პასუხები",
  "Instant responds": "მყისიერი პასუხები",
  "Text recognition": "ტექსტის ამოცნობა",
  "Powered by AI": "AI-ით აღჭურვილი",
  "Storytelleing": "მოთხრობა",
  ' Power': " ძალა",
  "Unlock your \nFill ": "გახსენით თქვენი \nFill ",
  "Your History": "თქვენი ისტორია",
  "Terms and Conditions": "წესები და პირობები",
  "Short": "მოკლე",
  "Medium": "საშუალო",
  "Long": "გრძელი",
  "Length": "სიგრძე",
  "Describe your topic...": "აღწერეთ თქვენი თემა...",
  "Set Creativity": "შემოქმედების დაყენება",
  "Standard": "სტანდარტული",
  "Creative": "შემოქმედებითი",
  "Complex": "რთული",
  "Select Genre": "აირჩიეთ ჟანრი",
  "Fantasy": "ფანტაზია",
  "Mystery": "საიდუმლო",
  "Thriller": "თრილერი",
  "Script Tone": "სცენარის ტონი",
  "Script Type": "სცენარის ტიპი",
  "Comedy": "კომედია",
  "Drama": "დრამა",
  "Horror": "საშინელება",
  "Action": "მოქმედება",
  "Romance": "რომანტიკა",
  "Go Premium": "პრემიუმზე გადასვლა",
  "Unlock Everything": "ყველაფრის გახსნა",
  "Unlimited Story Generation": "შეუზღუდავი ისტორიების გენერირება",
  "Write Longer & Detailed Essays": "დაწერეთ გრძელი და დეტალური ესეები",
  "Advanced Script Writer": "გაფართოებული სცენარის მწერალი",
  "Unlock All Styles & Tones": "ყველა სტილისა და ტონის გახსნა",
  "No Word/Length Limit": "სიტყვების/სიგრძის ლიმიტი არ არის",
  "Remove All Ads": "ყველა რეკლამის წაშლა",
  "Restore": "აღდგენა",
  "YouTube Video": "YouTube ვიდეო",
  "Podcast": "პოდკასტი",
  "Reel": "რილი",
  "Motivational": "მოტივაციური",
  "Advertisement": "რეკლამა",
  "Fairy Tale": "ზღაპარი",
  "Sci-Fi": "სამეცნიერო ფანტასტიკა",
  "Select Style": "აირჩიეთ სტილი",
  "Imaginative": "წარმოსახვითი",
  "Innovative": "ინოვაციური",
  "AI Story Writer": "AI ისტორიის მწერალი",
  "Generate": "გენერირება",
  "Please wait...": "გთხოვთ დაელოდეთ...",
  "Result": "შედეგი",
  "Regenerate": "ხელახლა გენერირება",
  "Download": "ჩამოტვირთვა",
  "Text copied to clipboard!": "ტექსტი კოპირებულია!",
  "Please enter a topic": "გთხოვთ შეიყვან��თ თემა",
  "Story Magic": "ისტორიის მაგია",
  "Let AI bring your thoughts to a full story":
      "მიეცით AI-ს თქვენი აზრები სრულ ისტორიად აქციოს",
  "Smart Scripts": "ჭკვიანი სცენარები",
  "From concept to script—fast, easy, and creative":
      "კონცეფციიდან სცენარამდე—სწრაფი, მარტივი და შემოქმედებითი",
  "Perfect Essays": "სრულყოფილი ესეები",
  "You have reached your free limit": "თქვენ მიაღწიეთ უფასო ლიმიტს",
  "Donwload": "ჩამოტვირთვა",
  "Press again to exit app": "კვლავ დააჭირეთ აპიდან გასასვლელად",
  "Saved to files": "TXT ფაილი წარმატებით შეინახა!",
  "Error: Please try again": "შეცდომა: გთხოვთ სცადეთ ხელახლა",
  "Subscription expired": "გამოწერა ვადაგასულია",
  "Purchase cancelled": "შენახვა გაუქმებულია",
  "Purchase failed": "შენახ��ა ვერ მოხერხდა",
  "Restore failed": "აღდგენა ვერ მოხერხდა",
  "Purchase Successful!": "შენახვა წარმატებულია!",
  "Short (200-500 words)": "მოკლე (200-500 სიტყვა)",
  "Medium (500-1000 words)": "საშუალო (500-1000 სიტყვა)",
  "Large (1000+ words)": "დიდი (1000+ სიტყვა)",
  "Academic Level": "აკადემიური დონე",
  "Type of Paper": "ნაშრომის ტიპი",
  "High School": "საშუალო სკოლა",
  "College": "კოლეჯი",
  "Short Film": "მოკლემეტრაჟიანი ფილმი",
  "University": "უნივერსიტეტი",
  "Masters": "მაგისტრატურა",
  "Custom": "მორგებული",
  "Tiktok Video": "TikTok ვიდეო",
  "Movie": "ფილმი",
  "Expository": "განმარტებითი",
  "Argumentative": "არგუმენტირებული",
  "Narrative": "ნარატიული",
  "Descriptive": "აღწერითი",
  "We're sorry to hear that 😔": "სამწუხაროა ამის გაგება 😔",
  "We'll try to improve 🙁": "შევეცდებით გავაუმჯობესოთ 🙁",
  "Thanks for your feedback 🙂": "მადლობა გამოხმაურებისთვის 🙂",
  "Great! We're glad you like it 😊":
      "შესანიშნავი! მოხარული ვართ რომ მოგეწონათ 😊",
  "Awesome! Thank you so much! 🎉": "საოცარი! დიდი მადლობა! 🎉",
  "Maybe Later": "იქნებ მოგვიანებით",
  "Tap a star to rate your experience":
      "შეეხეთ ვარსკვლავს თქვენი გამოცდილების შესაფასებლად",
  "Enjoying AI Math Solver?": "მოგწონთ AI მათემატიკის ამომხსნელი?",
  "Thank you for rating us": "მადლობა შეფასებისთვის",
  "Submit Rating": "შეფასების გაგზავნა",
  "Hindi": "ჰინდი",
  "Enjoying AI Story Generator?": "მოგწონთ AI ისტორიის გენერატორი?",
  AppKeys.arabic: "არაბული",
  AppKeys.chinese: "ჩინური",
  AppKeys.english: "ინგლისური",
  AppKeys.french: "ფრანგული",
  AppKeys.german: "გერმანული",
  AppKeys.hindi: "ჰინდი",
  AppKeys.indonesian: "ინდონეზიური",
  AppKeys.japanese: "იაპონური",
  AppKeys.korean: "კორეული",
  AppKeys.portuguese: "პორტუგალიური",
  AppKeys.russian: "რუსული",
  AppKeys.spanish: "ესპანური",
  AppKeys.turkish: "თურქული",
  'Download As': 'ჩამოტვირთვა როგორც',
  'Choose format to download': 'აირჩიეთ ფორმატი ჩამოსატვირთად',
  'Text File': 'ტექსტური ფაილი',
  'PDF File': 'PDF ფაილი',
  'Copy': 'კოპირება',
  'Share': 'გაზიარება',
  'Text copied!': 'ტექსტი კოპირებულია!',
  'PDF saved successfully!': 'PDF წარმატებით შეინახა!',
  'Error creating PDF: Please try again':
      'შეცდომა PDF-ის შექმნისას: გთხოვთ სცადეთ ხელახლა',
  'Character Story': 'პერსონაჟის ისტორია',
  'Character Details': 'პერსონაჟის დეტალები',
  'Character Name': 'პერსონაჟის სახელი',
  'Age (e.g., 25, Young Adult, Ancient)':
      'ასაკი (მაგ., 25, ახალგაზრდა, უძველესი)',
  'Personality (e.g., brave, shy, cunning)':
      'პიროვნება (მაგ., მამაცი, მორცხვი, ეშმაკი)',
  'Role (e.g., Hero, Villain, Mentor)':
      'როლი (მაგ., გმირი, ბოროტმოქმედი, მენტორი)',
  'Additional Details (optional)': 'დამატებითი დეტალები (არასავალდებულო)',
  'Output Style': 'გამოსავლის სტილი',
  'Generate Character': 'პერსონაჟის გენერირება',
  'Please enter character name': 'გთხოვთ შეიყვანოთ პერსონაჟის სახელი',
  'Please enter character role': 'გთხოვთ შეიყვანოთ პერსონაჟის როლი',
  'Detailed': 'დეტალური',
  'Brief': 'მოკლე',
  'Elaborate': 'ვრცელი',
  'Create detailed character backstories':
      'შექმენით დეტალური პერსონაჟების წინაისტორიები',
  'Create Character': 'პერსონაჟის შექმნა',
  'Transform and improve your existing stories':
      'გარდაქმენით და გააუმჯობესეთ თქვენი არსებული ისტორიები',
  'Rewrite Now': 'ახლა გადაწერეთ',
  'Generate catchy titles for your stories':
      'შექმენით მიმზიდველი სათაურები თქვენი ისტორიებისთვის',
  'Generate Titles': 'სათაურების გენერირება',
  'Rewrite Story': 'ისტორიის გადაწერა',
  'Paste Your Story': 'ჩასვით თქვენი ისტორია',
  'Paste your story here to rewrite...': 'ჩასვით ისტორია აქ გადასაწერად...',
  'Select Tone': 'აირჩიეთ ტონი',
  'Rewrite Style': 'გადაწერის სტილი',
  'Output Length': 'გამოსავლის სიგრძე',
  'Please paste your story': 'გთხოვთ ჩასვათ თქვენი ისტორია',
  'Story is too short. Please provide more content.':
      'ისტორია ძალიან მოკლეა. გთხოვთ მეტი შინაარსი მოგვაწოდოთ.',
  'Same': 'იგივე',
  'More Dramatic': 'უფრო დრამატული',
  'More Humorous': 'უფრო იუმორისტული',
  'More Emotional': 'უფრო ემოციური',
  'More Suspenseful': 'უფრო დაძაბული',
  'Lighter': 'უფრო მსუბუქი',
  'Improved': 'გაუმჯობესებული',
  'Simplified': 'გამარტივებული',
  'More Descriptive': 'უფრო აღწერითი',
  'More Dialogue': 'მეტი დიალოგი',
  'More Action': 'მეტი მოქმედება',
  'Literary': 'ლიტერატურული',
  'Shorter': 'უფრო მოკლე',
  'Longer': 'უფრო გრძელი',
  'Much Longer': 'ბევრად გრძელი',
  'Title Generator': 'სათაურის გენერატორი',
  'Story/Book Topic': 'ისტორიის/წიგნის თემა',
  'Keywords (Optional)': 'საკვანძო სიტყვები (არასავალდებულო)',
  'Describe your story topic or theme...': 'აღწერეთ ისტორიის თემა...',
  'e.g., magic, dragon, adventure': 'მაგ., მაგია, დრაკონი, თავგადასავალი',
  'Title For': 'სათაური',
  'Title Style': 'სათაურის სტილი',
  "Adventure": "თავგადასავალი",
  'Number of Titles': 'სათაურების რაოდენობა',
  'Book': 'წიგნი',
  'Short Story': 'მოთხრობა',
  'Novel': 'რომანი',
  'Chapter': 'თავი',
  'Series': 'სერია',
  'Simple': 'მარტივი',
  'Mysterious': 'საიდუმლოებით მოცული',
  'Dramatic': 'დრამატული',
  'Catchy': 'მიმზიდველი',
  'Poetic': 'პოეტური',
  'Kids': 'ბავშვებისთვის',
  'Blog Writer': 'ბლოგის მწერალი',
  'Blog Topic': 'ბლოგის თემა',
  'Target Keywords': 'სამიზნე საკვანძო სიტყვები',
  'Target Audience (Optional)': 'სამიზნე აუდიტორია (არასავალდებულო)',
  'Enter your blog topic or title...': 'შეიყვანეთ ბლოგის თემა ან სათაური...',
  'e.g., AI writing, content marketing, SEO tips':
      'მაგ., AI წერა, კონტენტ მარკეტინგი, SEO რჩევები',
  'e.g., small business owners, bloggers':
      'მაგ., მცირე ბიზნესის მფლობელები, ბლოგერები',
  'Article Type': 'სტატიის ტიპი',
  'Writing Tone': 'წერის ტონი',
  'Article Length': 'სტატიის სიგრძე',
  'SEO Options': 'SEO პარამეტრები',
  'Include Meta Description': 'მეტა აღწერის ჩართვა',
  'Include Keyword Suggestions': 'საკვანძო სიტყვების შეთავაზებების ჩართვა',
  'Include FAQs Section': 'ხშირად დასმული კითხვების ჩართვა',
  'Please enter a blog topic': 'გთხოვთ შეიყვანოთ ბლოგის თემა',
  'Generate Blog': 'ბლოგის გენერირება',
  'SEO optimized articles with keywords':
      'SEO ოპტიმიზირებული სტატიები საკვანძო სიტყვებით',
  'Write Blog': 'ბლოგის წერა',
  'SEO Article': 'SEO სტატია',
  'How-To Guide': 'სახელმძღვანელო',
  'Listicle': 'სიის სტატია',
  'Product Review': 'პროდუქტის მიმოხილვა',
  'Opinion Piece': 'მოსაზრების სტატია',
  'News Article': 'ახალი ამბების სტატია',
  'Professional': 'პროფესიონალური',
  'Casual': 'არაფორმალური',
  'Informative': 'ინფორმაციული',
  'Persuasive': 'დამაჯერებელი',
  'Friendly': 'მეგობრული',
  'Authoritative': 'ავტორიტეტული',
  'Short (500-800)': 'მოკლე (500-800)',
  'Medium (800-1500)': 'საშუალო (800-1500)',
  'Long (1500-2500)': 'გრძელი (1500-2500)',
  'Detailed (2500+)': 'დეტალური (2500+)',
  'YouTube Script': 'YouTube სცენარი',
  'Video Topic': 'ვიდეოს თემა',
  'Key Points (Optional)': 'ძირითადი პუნქტები (არასავალდებულო)',
  'What is your video about?': 'რის შესახებ არის თქვენი ვიდეო?',
  'List key points to cover (optional)...':
      'ჩამოთვალეთ ძირითადი პუნქტები (არასავალდებულო)...',
  'Video Duration': 'ვიდეოს ხანგრძლივობა',
  'Script Options': 'სცენარის პარამეტრები',
  'Include Hook/Intro': 'შესავალის ჩართვა',
  'Include Call-to-Action': 'მოქმედებისკენ მოწოდების ჩართვა',
  'Include Timestamps': 'დროის ნიშნულების ჩართვა',
  'Please enter a video topic': 'გთხოვთ შეიყვანოთ ვიდეოს თემა',
  'Generate Script': 'სცენარის გენერირება',
  'Create scripts for videos & reels':
      'შექმენით სცენარები ვიდეოებისა და რილებისთვის',
  'Create Script': 'სცენარის შექმნა',
  'Storytime': 'ისტორიის დრო',
  'Documentary': 'დოკუმენტური',
  'Short Reel': 'მოკლე რილი',
  'Educational': 'საგანმანათლებლო',
  'Review': 'მიმოხილვა',
  'Tutorial': 'სახელმძღვანელო',
  '< 1 min (Shorts)': '< 1 წთ (Shorts)',
  '1-3 min': '1-3 წთ',
  '5-10 min': '5-10 წთ',
  '10-20 min': '10-20 წთ',
  '20+ min': '20+ წთ',
  'Engaging': 'მიმზიდველი',
  'Energetic': 'ენერგიული',
  'Calm': 'მშვიდი',
  'Funny': 'სასაცილო',
  'Inspired': 'შთაგონებული',
  'Film Script': 'ფილმის სცენარი',
  'Stage Play': 'სასცენო პიესა',
  'Scene Breakdown': 'სცენის ანალიზი',
  'Dialogue Only': 'მხოლოდ დიალოგი',
  'Ad loading please wait..': 'რეკლამა იტვირთება გთხოვთ დაელოდეთ..',
  'Words:': 'სიტყვები:',
  'Reading:': 'კითხვა:',
};
