import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> kk = {
  AppKeys.lblChooseLanguage: "Тілді таңдаңыз",
  "All": "Барлығы",
  "AI Story Generator": "AI әңгіме генераторы",
  "Story Generator": "Әңгіме генераторы",
  "Essay Writer": "Эссе жазушы",
  "Essay length": "Эссе ұзындығы",
  "Script Generator": "Сценарий генераторы",
  "Create original stories in seconds":
      "Секундтарда түпнұсқа әңгімелер жасаңыз",
  "Academic writing made simple": "Академиялық жазу оңайлатылған",
  "Generate powerful scripts for any medium":
      "Кез келген орта үшін қуатты сценарийлер жасаңыз",
  "Start Writing": "Жазуды бастаңыз",
  "Create Now": "Қазір жасаңыз",
  "Start Generating": "Генерацияны бастаңыз",
  "Your Stories": "Сіздің әңгімелеріңіз",
  "No stories yet": "Әзірге әңгімелер жоқ",
  "Start creating your first story!": "Бірінші әңгімеңізді жасай бастаңыз!",
  "Your Story Space Awaits": "Сіздің әңгіме кеңістігіңіз күтуде",
  "Start your first story and see it appear here":
      "Бірінші әңгімеңізді бастаңыз және оны мұнда көріңіз",
  "Language": "Тіл",
  "Rate us": "Бізді бағалаңыз",
  "Share us": "Бізбен бөлісіңіз",
  "Privacy Policy": "Құпиялық саясаты",
  "Settings": "Параметрлер",
  "Select Language": "Тілді таңдаңыз",
  "Dashboard": "Басқару тақтасы",
  "BENEFITS": "АРТЫҚШЫЛЫҚТАР",
  "Subscribe": "Жазылу",
  "Weekly": "Апталық",
  "Monthly": "Айлық",
  "Yearly": "Жылдық",
  "week": "апта",
  "months": "айлар",
  "year": "жыл",
  "Terms & Condition": "Шарттар мен ережелер",
  "No Commitment. Cancel anytime":
      "Міндеттемесіз. Кез келген уақытта болдырмаңыз",
  "No Payment Now": "Қазір төлем жоқ",
  "3 days free": "3 күн тегін",
  "Start your free trial": "Тегін сынақ кезеңін бастаңыз",
  "More detailed answers": "Толығырақ жауаптар",
  "Instant responds": "Лезде жауаптар",
  "Text recognition": "Мәтінді тану",
  "Powered by AI": "AI қуатымен",
  "Storytelleing": "Әңгіме айту",
  ' Power': " Қуат",
  "Unlock your \nFill ": "Ашыңыз \nFill ",
  "Your History": "Сіздің тарихыңыз",
  "Terms and Conditions": "Шарттар мен ережелер",
  "Short": "Қысқа",
  "Medium": "Орташа",
  "Long": "Ұзын",
  "Length": "Ұзындық",
  "Describe your topic...": "Тақырыбыңызды сипаттаңыз...",
  "Set Creativity": "Шығармашылықты орнатыңыз",
  "Standard": "Стандартты",
  "Creative": "Шығармашылық",
  "Complex": "Күрделі",
  "Select Genre": "Жанрды таңдаңыз",
  "Fantasy": "Фан��азия",
  "Mystery": "Құпия",
  "Thriller": "Триллер",
  "Script Tone": "Сценарий үні",
  "Script Type": "Сценарий түрі",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Horror": "Қорқынышты",
  "Action": "Экшн",
  "Romance": "Романтика",
  "Go Premium": "Премиумға өту",
  "Unlock Everything": "Бәрін ашу",
  "Unlimited Story Generation": "Шексіз әңгіме генерациясы",
  "Write Longer & Detailed Essays": "Ұзын және егжей-тегжейлі эсселер жазыңыз",
  "Advanced Script Writer": "Кеңейтілген сценарий жазушы",
  "Unlock All Styles & Tones": "Барлық стильдер мен үндерді ашу",
  "No Word/Length Limit": "Сөз/ұзындық шегі жоқ",
  "Remove All Ads": "Барлық жарнамаларды алып тастау",
  "Restore": "Қалпына келтіру",
  "YouTube Video": "YouTube видео",
  "Podcast": "Подкаст",
  "Reel": "Рил",
  "Motivational": "Мотивациялық",
  "Advertisement": "Жарнама",
  "Fairy Tale": "Ертегі",
  "Sci-Fi": "Ғылыми фантастика",
  "Select Style": "Стильді таңдаңыз",
  "Imaginative": "Қиялшыл",
  "Innovative": "Инновациялық",
  "AI Story Writer": "AI әңгіме жазушы",
  "Generate": "Генерациялау",
  "Please wait...": "Күте тұрыңыз...",
  "Result": "Нәтиже",
  "Regenerate": "Қайта генерациялау",
  "Download": "Жүктеу",
  "Text copied to clipboard!": "Мәтін буферге көшірілді!",
  "Please enter a topic": "Тақырып енгізіңіз",
  "Story Magic": "Әңгіме сиқыры",
  "Let AI bring your thoughts to a full story":
      "AI сіздің ойларыңызды толық әңгімеге айналдырсын",
  "Smart Scripts": "Ақылды сценарийлер",
  "From concept to script—fast, easy, and creative":
      "Концепциядан сценарийге—жылдам, оңай және шығармашыл",
  "Perfect Essays": "Мінсіз эсселер",
  "You have reached your free limit": "Сіз тегін шегіне жеттіңіз",
  "Donwload": "Жүктеу",
  "Press again to exit app": "Қолданбадан шығу үшін қайта басыңыз",
  "Saved to files": "TXT файл сәтті сақталды!",
  "Error: Please try again": "Қате: Қайта көріңіз",
  "Subscription expired": "Жазылым мерзімі аяқталды",
  "Purchase cancelled": "Сатып алу болдырылмады",
  "Purchase failed": "Сатып алу сәтсіз аяқталды",
  "Restore failed": "Қалпына келтіру сәтсіз",
  "Purchase Successful!": "Сатып алу сәтті!",
  "Short (200-500 words)": "Қысқа (200-500 сөз)",
  "Medium (500-1000 words)": "Орташа (500-1000 сөз)",
  "Large (1000+ words)": "Үлкен (1000+ сөз)",
  "Academic Level": "Академиялық деңгей",
  "Type of Paper": "Жұмыс түрі",
  "High School": "Орта мектеп",
  "College": "Колледж",
  "Short Film": "Қысқа фильм",
  "University": "Университет",
  "Masters": "Магистратура",
  "Custom": "Реттелетін",
  "Tiktok Video": "TikTok видео",
  "Movie": "Фильм",
  "Expository": "Түсіндірмелі",
  "Argumentative": "Дәлелді",
  "Narrative": "Баяндау",
  "Descriptive": "Сипаттама",
  "We're sorry to hear that 😔": "Мұны естігенімізге өкінеміз 😔",
  "We'll try to improve 🙁": "Жақсартуға тырысамыз 🙁",
  "Thanks for your feedback 🙂": "Пікіріңіз үшін рахмет 🙂",
  "Great! We're glad you like it 😊": "Тамаша! Ұнағанына қуаныштымыз 😊",
  "Awesome! Thank you so much! 🎉": "Керемет! Көп рахмет! 🎉",
  "Maybe Later": "Мүмкін кейін",
  "Tap a star to rate your experience":
      "Тәжірибеңізді бағалау үшін жұлдызға басыңыз",
  "Enjoying AI Math Solver?": "AI математика шешушісі ұнады ма?",
  "Thank you for rating us": "Бағалағаныңыз үшін рахмет",
  "Submit Rating": "Бағалауды жіберу",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "AI әңгіме генераторы ұнады ма?",
  AppKeys.arabic: "Арабша",
  AppKeys.chinese: "Қытайша",
  AppKeys.english: "Ағылшынша",
  AppKeys.french: "Французша",
  AppKeys.german: "Немісше",
  AppKeys.hindi: "Хинди",
  AppKeys.indonesian: "Индонезияша",
  AppKeys.japanese: "Жапонша",
  AppKeys.korean: "Корейше",
  AppKeys.portuguese: "Португалша",
  AppKeys.russian: "Орысша",
  AppKeys.spanish: "Испанша",
  AppKeys.turkish: "Түрікше",
  'Download As': 'Жүктеу форматы',
  'Choose format to download': 'Жүктеу форматын таңдаңыз',
  'Text File': 'Мәтіндік файл',
  'PDF File': 'PDF файл',
  'Copy': 'Көшіру',
  'Share': 'Бөлісу',
  'Text copied!': 'Мәтін көшірілді!',
  'PDF saved successfully!': 'PDF сәтті сақталды!',
  'Error creating PDF: Please try again': 'PDF жасау қатесі: Қайта көріңіз',
  'Character Story': 'Кейіпкер әңгімесі',
  'Character Details': 'Кейіпкер мәліметтері',
  'Character Name': 'Кейіпкер аты',
  'Age (e.g., 25, Young Adult, Ancient)': 'Жас (мыс., 25, Жас ересек, Ежелгі)',
  'Personality (e.g., brave, shy, cunning)':
      'Мінез (мыс., батыл, ұялшақ, айлакер)',
  'Role (e.g., Hero, Villain, Mentor)': 'Рөл (мыс., Батыр, Зұлым, Тәлімгер)',
  'Additional Details (optional)': 'Қосымша мәліметтер (міндетті емес)',
  'Output Style': 'Шығу стилі',
  'Generate Character': 'Кейіпкер генерациялау',
  'Please enter character name': 'Кейіпкер атын енгізіңіз',
  'Please enter character role': 'Кейіпкер рөлін енгізіңіз',
  'Detailed': 'Егжей-тегжейлі',
  'Brief': 'Қысқаша',
  'Elaborate': 'Кеңейтілген',
  'Create detailed character backstories':
      'Егжей-тегжейлі кейіпкер тарихтарын жасаңыз',
  'Create Character': 'Кейіпкер жасау',
  'Transform and improve your existing stories':
      'Бар әңгімелеріңізді өзгертіңіз және жақсартыңыз',
  'Rewrite Now': 'Қазір қайта жазыңыз',
  'Generate catchy titles for your stories':
      'Әңгімелеріңізге тартымды тақырыптар жасаңыз',
  'Generate Titles': 'Тақырыптар генерациялау',
  'Rewrite Story': 'Әңгімені қайта жазу',
  'Paste Your Story': 'Әңгімеңізді қойыңыз',
  'Paste your story here to rewrite...':
      'Қайта жазу үшін әңгімеңізді осында қойыңыз...',
  'Select Tone': 'Үнді таңдаңыз',
  'Rewrite Style': 'Қайта жазу стилі',
  'Output Length': 'Шығу ұзындығы',
  'Please paste your story': 'Әңгімеңізді қойыңыз',
  'Story is too short. Please provide more content.':
      'Әңгіме тым қысқа. Көбірек мазмұн беріңіз.',
  'Same': 'Бірдей',
  'More Dramatic': 'Драмалырақ',
  'More Humorous': 'Әзілдірек',
  'More Emotional': 'Эмоционалдырақ',
  'More Suspenseful': 'Шиеленістірек',
  'Lighter': 'Жеңілірек',
  'Improved': 'Жақсартылған',
  'Simplified': 'Оңайлатылған',
  'More Descriptive': 'Сипаттамалырақ',
  'More Dialogue': 'Көбірек диалог',
  'More Action': 'Көбірек экшн',
  'Literary': 'Әдеби',
  'Shorter': 'Қысқарақ',
  'Longer': 'Ұзынырақ',
  'Much Longer': 'Әлдеқайда ұзынырақ',
  'Title Generator': 'Тақырып генераторы',
  'Story/Book Topic': 'Әңгіме/кітап тақырыбы',
  'Keywords (Optional)': 'Кілт сөздер (міндетті емес)',
  'Describe your story topic or theme...': 'Әңгіме тақырыбын сипаттаңыз...',
  'e.g., magic, dragon, adventure': 'мыс., сиқыр, айдаһар, шытырман оқиға',
  'Title For': 'Тақырып',
  'Title Style': 'Тақырып стилі',
  "Adventure": "Шытырман оқиға",
  'Number of Titles': 'Тақырыптар саны',
  'Book': 'Кітап',
  'Short Story': 'Қысқа әңгіме',
  'Novel': 'Роман',
  'Chapter': 'Тарау',
  'Series': 'Серия',
  'Simple': 'Қарапайым',
  'Mysterious': 'Құпиялы',
  'Dramatic': 'Драмалық',
  'Catchy': 'Тартымды',
  'Poetic': 'Поэтикалық',
  'Kids': 'Балаларға',
  'Blog Writer': 'Блог жазушы',
  'Blog Topic': 'Блог тақырыбы',
  'Target Keywords': 'Мақсатты кілт сөздер',
  'Target Audience (Optional)': 'Мақсатты аудитория (міндетті емес)',
  'Enter your blog topic or title...':
      'Блог тақырыбын немесе атауын енгізіңіз...',
  'e.g., AI writing, content marketing, SEO tips':
      'мыс., AI жазу, контент маркетинг, SEO кеңестер',
  'e.g., small business owners, bloggers':
      'мыс., шағын бизнес иелері, блогерлер',
  'Article Type': 'Мақала түрі',
  'Writing Tone': 'Жазу үні',
  'Article Length': 'Мақала ұзындығы',
  'SEO Options': 'SEO параметрлері',
  'Include Meta Description': 'Мета сипаттаманы қосу',
  'Include Keyword Suggestions': 'Кілт сөз ұсыныстарын қосу',
  'Include FAQs Section': 'Жиі қойылатын сұрақтар бөлімін қосу',
  'Please enter a blog topic': 'Блог тақырыбын енгізіңіз',
  'Generate Blog': 'Блог генерациялау',
  'SEO optimized articles with keywords':
      'Кілт сөздерімен SEO оңтайландырылған мақалалар',
  'Write Blog': 'Блог жазу',
  'SEO Article': 'SEO мақала',
  'How-To Guide': 'Нұсқаулық',
  'Listicle': 'Тізім мақала',
  'Product Review': 'Өнім шолуы',
  'Opinion Piece': 'Пікір мақаласы',
  'News Article': 'Жаңалықтар мақаласы',
  'Professional': 'Кәсіби',
  'Casual': 'Бейресми',
  'Informative': 'Ақпараттық',
  'Persuasive': 'Сендіретін',
  'Friendly': 'Достық',
  'Authoritative': 'Беделді',
  'Short (500-800)': 'Қысқа (500-800)',
  'Medium (800-1500)': 'Орташа (800-1500)',
  'Long (1500-2500)': 'Ұзын (1500-2500)',
  'Detailed (2500+)': 'Егжей-тегжейлі (2500+)',
  'YouTube Script': 'YouTube сценарийі',
  'Video Topic': 'Видео тақырыбы',
  'Key Points (Optional)': 'Негізгі пункттер (міндетті емес)',
  'What is your video about?': 'Видеоңыз не туралы?',
  'List key points to cover (optional)...':
      'Негізгі пункттерді тізімдеңіз (міндетті емес)...',
  'Video Duration': 'Видео ұзақтығы',
  'Script Options': 'Сценарий параметрлері',
  'Include Hook/Intro': 'Кіріспені қосу',
  'Include Call-to-Action': 'Әрекетке шақыруды қосу',
  'Include Timestamps': 'Уақыт белгілерін қосу',
  'Please enter a video topic': 'Видео тақырыбын енгізіңіз',
  'Generate Script': 'Сценарий генерациялау',
  'Create scripts for videos & reels':
      'Видеолар мен рилдерге сценарийлер жасаңыз',
  'Create Script': 'Сценарий жасау',
  'Storytime': 'Әңгіме уақыты',
  'Documentary': 'Деректі фильм',
  'Short Reel': 'Қысқа рил',
  'Educational': 'Білім беретін',
  'Review': 'Шолу',
  'Tutorial': 'Оқулық',
  '< 1 min (Shorts)': '< 1 мин (Shorts)',
  '1-3 min': '1-3 мин',
  '5-10 min': '5-10 мин',
  '10-20 min': '10-20 мин',
  '20+ min': '20+ мин',
  'Engaging': 'Тартымды',
  'Energetic': 'Қуатты',
  'Calm': 'Тыныш',
  'Funny': 'Күлкілі',
  'Inspired': 'Шабыттандырылған',
  'Film Script': 'Фильм сценарийі',
  'Stage Play': 'Сахна пьесасы',
  'Scene Breakdown': 'Сахна талдауы',
  'Dialogue Only': 'Тек диалог',
  'Ad loading please wait..': 'Жарнама жүктелуде күте тұрыңыз..',
  'Words:': 'Сөздер:',
  'Reading:': 'Оқу:',
};
