import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> km = {
  AppKeys.lblChooseLanguage: "ជ្រើសរើសភាសា",
  "All": "ទាំងអស់",
  "AI Story Generator": "កម្មវិធីបង្កើតរឿង AI",
  "Story Generator": "កម្មវិធីបង្កើតរឿង",
  "Essay Writer": "អ្នកសរសេរសំណេរ",
  "Essay length": "ប្រវែងសំណេរ",
  "Script Generator": "កម្មវិធីបង្កើតស្គ្រីប",
  "Create original stories in seconds": "បង្កើតរឿងដើមក្នុងរយៈពេលប៉ុន្មានវិនាទី",
  "Academic writing made simple": "ការសរសេរបែបសិក្សាធ្វើឱ្យសាមញ្ញ",
  "Generate powerful scripts for any medium":
      "បង្កើតស្គ្រីបដ៏មានអានុភាពសម្រាប់មធ្យោបាយណាមួយ",
  "Start Writing": "ចាប់ផ្តើមសរសេរ",
  "Create Now": "បង្កើតឥឡូវនេះ",
  "Start Generating": "ចាប់ផ្តើមបង្កើត",
  "Your Stories": "រឿងរបស់អ្នក",
  "No stories yet": "មិនទាន់មានរឿងទេ",
  "Start creating your first story!": "ចាប់ផ្តើមបង្កើតរឿងដំបូងរបស់អ្នក!",
  "Your Story Space Awaits": "កន្លែងរឿងរបស់អ្នកកំពុងរង់ចាំ",
  "Start your first story and see it appear here":
      "ចាប់ផ្តើមរឿងដំបូងរបស់អ្នក ហើយមើលវាបង្ហាញនៅទីនេះ",
  "Language": "ភាសា",
  "Rate us": "វាយតម្លៃយើង",
  "Share us": "ចែករំលែកយើង",
  "Privacy Policy": "គោលការណ៍ភាពឯកជន",
  "Settings": "ការកំណត់",
  "Select Language": "ជ្រើសរើសភាសា",
  "Dashboard": "ផ្ទាំងគ្រប់គ្រង",
  "BENEFITS": "អត្ថប្រយោជន៍",
  "Subscribe": "ជាវ",
  "Weekly": "ប្រចាំសប្តាហ៍",
  "Monthly": "ប្រចាំខែ",
  "Yearly": "ប្រចាំឆ្នាំ",
  "week": "សប្តាហ៍",
  "months": "ខែ",
  "year": "ឆ្នាំ",
  "Terms & Condition": "លក្ខខណ្ឌ",
  "No Commitment. Cancel anytime": "គ្មានការប្តេជ្ញាចិត្ត។ បោះបង់បានគ្រប់ពេល",
  "No Payment Now": "មិនចាំបាច់បង់ប្រាក់ឥឡូវទេ",
  "3 days free": "ឥតគិតថ្លៃ 3 ថ្ងៃ",
  "Start your free trial": "ចាប់ផ្តើមការសាកល្បងឥតគិតថ្លៃ",
  "More detailed answers": "ចម្លើយលម្អិតបន្ថែម",
  "Instant responds": "ឆ្លើយតបភ្លាមៗ",
  "Text recognition": "ការសម្គាល់អត្ថបទ",
  "Powered by AI": "ដំណើរការដោយ AI",
  "Storytelleing": "ការនិទានរឿង",
  ' Power': "ថាមពល",
  "Unlock your \nFill ": "ដោះសោរបស់អ្នក \nបំពេញ",
  "Your History": "ប្រវត្តិរបស់អ្នក",
  "Terms and Conditions": "លក្ខខណ្ឌ",
  "Short": "ខ្លី",
  "Medium": "មធ្យម",
  "Long": "វែង",
  "Length": "ប្រវែង",
  "Describe your topic...": "ពិពណ៌នាប្រធានបទរបស់អ្នក...",
  "Set Creativity": "កំណត់ភាពច្នៃប្រឌិត",
  "Standard": "ស្តង់ដារ",
  "Creative": "ច្នៃប្រឌិត",
  "Complex": "ស្មុគស្មាញ",
  "Select Genre": "ជ្រើសរើសប្រភេទ",
  "Fantasy": "រឿងប្រឌិត",
  "Mystery": "អាថ៌កំបាំង",
  "Thriller": "រន្ធត់",
  "Script Tone": "សម្លេងស្គ្រីប",
  "Script Type": "ប្រភេទស្គ្រីប",
  "Comedy": "កំប្លែង",
  "Drama": "រឿងភាគ",
  "Horror": "រន្ធត់ភ័យ",
  "Action": "សកម្មភាព",
  "Romance": "មនោសញ្ចេតនា",
  "Go Premium": "ទៅ Premium",
  "Unlock Everything": "ដោះសោរទាំងអស់",
  "Unlimited Story Generation": "បង្កើតរឿងគ្មានដែនកំណត់",
  "Write Longer & Detailed Essays": "សរសេរសំណេរវែង និងលម្អិត",
  "Advanced Script Writer": "អ្នកសរសេរស្គ្រីបកម្រិតខ្ពស់",
  "Unlock All Styles & Tones": "ដោះសោរស្ទាល និងសម្លេងទាំងអស់",
  "No Word/Length Limit": "គ្មានដែនកំណត់ពាក្យ/ប្រវែង",
  "Remove All Ads": "លុបការផ្សាយពាណិជ្ជកម្មទាំងអស់",
  "Restore": "ស្តារឡើងវិញ",
  "YouTube Video": "វីដេអូ YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "លើកទឹកចិត្ត",
  "Advertisement": "ការផ្សាយពាណិជ្ជកម្ម",
  "Fairy Tale": "រឿងនិទាន",
  "Sci-Fi": "វិទ្យាសាស្ត្រប្រឌិត",
  "Select Style": "ជ្រើសរើសស្ទាល",
  "Imaginative": "ពោរពេញដោយការស្រមើស្រមៃ",
  "Innovative": "ច្នៃប្រឌិត",
  "AI Story Writer": "អ្នកសរសេររឿង AI",
  "Generate": "បង្កើត",
  "Please wait...": "សូមរង់ចាំ...",
  "Result": "លទ្ធផល",
  "Regenerate": "បង្កើតឡើងវិញ",
  "Download": "ទាញយក",
  "Text copied to clipboard!": "អត្ថបទត្រូវបានចម្លងទៅក្ដារតម្បៀតខ្ទាស់!",
  "Please enter a topic": "សូមបញ្ចូលប្រធានបទ",
  "Story Magic": "វេទមន្តរឿង",
  "Let AI bring your thoughts to a full story":
      "អនុញ្ញាតឱ្យ AI នាំយកគំនិតរបស់អ្នកទៅជារឿងពេញលេញ",
  "Smart Scripts": "ស្គ្រីបឆ្លាតវៃ",
  "From concept to script—fast, easy, and creative":
      "ពីគំនិតទៅស្គ្រីប—រហ័ស ងាយស្រួល និងច្នៃប្រឌិត",
  "Perfect Essays": "សំណេរល្អឥតខ្ចោះ",
  "You have reached your free limit": "អ្នកបានឈានដល់ដែនកំណត់ឥតគិតថ្លៃរបស់អ្នក",
  "Donwload": "ទាញយក",
  "Press again to exit app": "ចុចម្តងទៀតដើម្បីចេញពីកម្មវិធី",
  "Saved to files": "ឯកសារ TXT បានរក្សាទុកដោយជោគជ័យ!",
  "Error: Please try again": "កំហុស៖ សូមព្យាយាមម្តងទៀត",
  "Subscription expired": "ការជាវបានផុតកំណត់",
  "Purchase cancelled": "ការទិញត្រូវបានលុបចោល",
  "Purchase failed": "ការទិញបានបរាជ័យ",
  "Restore failed": "ការស្តារឡើងវិញបានបរាជ័យ",
  "Purchase Successful!": "ការទិញបានជោគជ័យ!",
  "Short (200-500 words)": "ខ្លី (200-500 ពាក្យ)",
  "Medium (500-1000 words)": "មធ្យម (500-1000 ពាក្យ)",
  "Large (1000+ words)": "ធំ (1000+ ពាក្យ)",
  "Academic Level": "កម្រិតសិក្សា",
  "Type of Paper": "ប្រភេទក្រដាស",
  "High School": "វិទ្យាល័យ",
  "College": "មហាវិទ្យាល័យ",
  "Short Film": "រឿងខ្លី",
  "University": "សាកលវិទ្យាល័យ",
  "Masters": "អនុបណ្ឌិត",
  "Custom": "ផ្ទាល់ខ្លួន",
  "Tiktok Video": "វីដេអូ Tiktok",
  "Movie": "ភាពយន្ត",
  "Expository": "ពន្យល់",
  "Argumentative": "វែកញែក",
  "Narrative": "និទាន",
  "Descriptive": "ពិពណ៌នា",
  "We're sorry to hear that 😔": "យើងសោកស្តាយដែលបានឮដូច្នេះ 😔",
  "We'll try to improve 🙁": "យើងនឹងព្យាយាមកែលម្អ 🙁",
  "Thanks for your feedback 🙂": "សូមអរគុណសម្រាប់មតិកែលម្អរបស់អ្នក 🙂",
  "Great! We're glad you like it 😊": "អស្ចារ្យ! យើងរីករាយដែលអ្នកចូលចិត្ត 😊",
  "Awesome! Thank you so much! 🎉": "អស្ចារ្យ! សូមអរគុណច្រើន! 🎉",
  "Maybe Later": "ប្រហែលជាពេលក្រោយ",
  "Tap a star to rate your experience":
      "ចុចផ្កាយដើម្បីវាយតម្លៃបទពិសោធន៍របស់អ្នក",
  "Enjoying AI Math Solver?": "រីករាយជាមួយ AI Math Solver មែនទេ?",
  "Thank you for rating us": "សូមអរគុណសម្រាប់ការវាយតម្លៃយើង",
  "Submit Rating": "ដាក់ស្នើការវាយតម្លៃ",
  "Hindi": "ហិណ្ឌី",
  "Enjoying AI Story Generator?": "រីករាយជាមួយ AI Story Generator មែនទេ?",
  "Adventure": "ផ្សងព្រេង",
  "Inspired": "បានបំផុសគំនិត",
  "Film Script": "ស្គ្រីបភាពយន្ត",
  "Stage Play": "ល្ខោនឆាក",
  "Scene Breakdown": "ការបែងចែកឈុត",
  "Dialogue Only": "ការសន្ទនាតែប៉ុណ្ណោះ",
  "Ad loading please wait..": "កំពុងផ្ទុកការផ្សាយពាណិជ្ជកម្ម សូមរង់ចាំ...",
  "Words:": "ពាក្យ:",
  "Reading:": "ការអាន:",

  AppKeys.arabic: "អារ៉ាប់",
  AppKeys.chinese: "ចិន",
  AppKeys.english: "អង់គ្លេស",
  AppKeys.french: "បារាំង",
  AppKeys.german: "អាល្លឺម៉ង់",
  AppKeys.hindi: "ហិណ្ឌី",
  AppKeys.indonesian: "ឥណ្ឌូនេស៊ី",
  AppKeys.japanese: "ជប៉ុន",
  AppKeys.korean: "កូរ៉េ",
  AppKeys.portuguese: "ព័រទុយហ្គាល់",
  AppKeys.russian: "រុស្ស៊ី",
  AppKeys.spanish: "អេស្ប៉ាញ",
  AppKeys.turkish: "តួកគី",

  // New strings for download & actions
  'Download As': 'ទាញយកជា',
  'Choose format to download': 'ជ្រើសរើសទម្រង់ដើម្បីទាញយក',
  'Text File': 'ឯកសារអត្ថបទ',
  'PDF File': 'ឯកសារ PDF',
  'Copy': 'ចម្លង',
  'Share': 'ចែករំលែក',
  'Text copied!': 'អត្ថបទត្រូវបានចម្លង!',
  'Copied to clipboard': 'បានចម្លងទៅក្ដារតម្បៀតខ្ទាស់',
  'File saved successfully': 'ឯកសារត្រូវបានរក្សាទុកដោយជោគជ័យ',
  'Error saving file': 'កំហុសក្នុងការរក្សាទុកឯកសារ',
  'Share Story': 'ចែករំលែករឿង',
  'Export': 'នាំចេញ',
};
