import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> kn = {
  AppKeys.lblChooseLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
  "All": "ಎಲ್ಲಾ",
  "AI Story Generator": "AI ಕಥೆ ಜನರೇಟರ್",
  "Story Generator": "ಕಥೆ ಜನರೇಟರ್",
  "Essay Writer": "ಪ್ರಬಂಧ ಬರಹಗಾರ",
  "Essay length": "ಪ್ರಬಂಧದ ಉದ್ದ",
  "Script Generator": "ಸ್ಕ್ರಿಪ್ಟ್ ಜನರೇಟರ್",
  "Create original stories in seconds": "ಕ್ಷಣಗಳಲ್ಲಿ ಮೂಲ ಕಥೆಗಳನ್ನು ರಚಿಸಿ",
  "Academic writing made simple": "ಶೈಕ್ಷಣಿಕ ಬರವಣಿಗೆಯನ್ನು ಸರಳಗೊಳಿಸಲಾಗಿದೆ",
  "Generate powerful scripts for any medium":
      "ಯಾವುದೇ ಮಾಧ್ಯಮಕ್ಕಾಗಿ ಶಕ್ತಿಶಾಲಿ ಸ್ಕ್ರಿಪ್ಟ್‌ಗಳನ್ನು ರಚಿಸಿ",
  "Start Writing": "ಬರೆಯಲು ಪ್ರಾರಂಭಿಸಿ",
  "Create Now": "ಈಗ ರಚಿಸಿ",
  "Start Generating": "ಜನರೇಟ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ",
  "Your Stories": "ನಿಮ್ಮ ಕಥೆಗಳು",
  "No stories yet": "ಇನ್ನೂ ಯಾವುದೇ ಕಥೆಗಳಿಲ್ಲ",
  "Start creating your first story!": "ನಿಮ್ಮ ಮೊದಲ ಕಥೆಯನ್ನು ರಚಿಸಲು ಪ್ರಾರಂಭಿಸಿ!",
  "Your Story Space Awaits": "ನಿಮ್ಮ ಕಥೆಯ ಜಾಗ ನಿಮ್ಮನ್ನು ಕಾಯುತ್ತಿದೆ",
  "Start your first story and see it appear here":
      "ನಿಮ್ಮ ಮೊದಲ ಕಥೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ಅದು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುವುದನ್ನು ನೋಡಿ",
  "Language": "ಭಾಷೆ",
  "Rate us": "ನಮ್ಮನ್ನು ರೇಟ್ ಮಾಡಿ",
  "Share us": "ನಮ್ಮನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
  "Privacy Policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
  "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  "Select Language": "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
  "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "BENEFITS": "ಪ್ರಯೋಜನಗಳು",
  "Subscribe": "ಚಂದಾ ಮಾಡಿ",
  "Weekly": "ವಾರಕ್ಕೊಮ್ಮೆ",
  "Monthly": "ಮಾಸಿಕ",
  "Yearly": "ವಾರ್ಷಿಕ",
  "week": "ವಾರ",
  "months": "ತಿಂಗಳುಗಳು",
  "year": "ವರ್ಷ",
  "Terms & Condition": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
  "No Commitment. Cancel anytime":
      "ಯಾವುದೇ ಬದ್ಧತೆ ಇಲ್ಲ. ಯಾವಾಗ ಬೇಕಾದರೂ ರದ್ದು ಮಾಡಿ",
  "No Payment Now": "ಈಗ ಯಾವುದೇ ಪಾವತಿ ಇಲ್ಲ",
  "3 days free": "3 ದಿನ ಉಚಿತ",
  "Start your free trial": "ನಿಮ್ಮ ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
  "More detailed answers": "ಹೆಚ್ಚು ವಿವರವಾದ ಉತ್ತರಗಳು",
  "Instant responds": "ತಕ್ಷಣದ ಪ್ರತಿಕ್ರಿಯೆ",
  "Text recognition": "ಪಠ್ಯ ಗುರುತಿಸುವಿಕೆ",
  "Powered by AI": "AI ಯಿಂದ ಚಾಲಿತ",
  "Storytelleing": "ಕಥೆ ಹೇಳುವಿಕೆ",
  ' Power': "ಶಕ್ತಿ",
  "Unlock your \nFill ": "ನಿಮ್ಮ \nFill ಅನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
  "Your History": "ನಿಮ್ಮ ಇತಿಹಾಸ",
  "Terms and Conditions": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
  "Short": "ಚಿಕ್ಕದು",
  "Medium": "ಮಧ್ಯಮ",
  "Long": "ದೀರ್ಘ",
  "Length": "ಉದ್ದ",
  "Describe your topic...": "ನಿಮ್ಮ ವಿಷಯವನ್ನು ವಿವರಿಸಿ...",
  "Set Creativity": "ಸೃಜನಶೀಲತೆ ಹೊಂದಿಸಿ",
  "Standard": "ಪ್ರಮಾಣಿತ",
  "Creative": "ಸೃಜನಶೀಲ",
  "Complex": "ಸಂಕೀರ್ಣ",
  "Select Genre": "ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "Fantasy": "ಕಲ್ಪನೆ",
  "Mystery": "ರಹಸ್ಯ",
  "Thriller": "ಥ್ರಿಲ್ಲರ್",
  "Script Tone": "ಸ್ಕ್ರಿಪ್ಟ್ ಧ್ವನಿ",
  "Script Type": "ಸ್ಕ್ರಿಪ್ಟ್ ಪ್ರಕಾರ",
  "Comedy": "ಕಾಮೆಡಿ",
  "Drama": "ನಾಟಕ",
  "Horror": "ಭಯಾನಕ",
  "Action": "ಆಕ್ಷನ್",
  "Romance": "ರೋಮಾನ್ಸ್",
  "Go Premium": "ಪ್ರೀಮಿಯಂಗೆ ಹೋಗಿ",
  "Unlock Everything": "ಎಲ್ಲವನ್ನೂ ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
  "Unlimited Story Generation": "ಅಪರಿಮಿತ ಕಥೆ ಜನರೇಷನ್",
  "Write Longer & Detailed Essays": "ದೀರ್ಘ ಮತ್ತು ವಿವರವಾದ ಪ್ರಬಂಧಗಳನ್ನು ಬರೆಯಿರಿ",
  "Advanced Script Writer": "ಸುಧಾರಿತ ಸ್ಕ್ರಿಪ್ಟ್ ಬರಹಗಾರ",
  "Unlock All Styles & Tones": "ಎಲ್ಲಾ ಶೈಲಿಗಳು ಮತ್ತು ಧ್ವನಿಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
  "No Word/Length Limit": "ಯಾವುದೇ ಪದ/ಉದ್ದದ ಮಿತಿ ಇಲ್ಲ",
  "Remove All Ads": "ಎಲ್ಲಾ ಜಾಹೀರಾತುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
  "Restore": "ಮರುಸ್ಥಾಪಿಸಿ",
  "YouTube Video": "ಯೂಟ್ಯೂಬ್ ವಿಡಿಯೋ",
  "Podcast": "ಪಾಡ್‌ಕಾಸ್ಟ್",
  "Reel": "ರೀಲ್",
  "Motivational": "ಪ್ರೇರಣಾದಾಯಕ",
  "Advertisement": "ಜಾಹೀರಾತು",
  "Fairy Tale": "ಪರಿ ಕಥೆ",
  "Sci-Fi": "ವೈಜ್ಞಾನಿಕ ಕಾಲ್ಪನಿಕ",
  "Select Style": "ಶೈಲಿ ಆಯ್ಕೆಮಾಡಿ",
  "Imaginative": "ಕಲ್ಪನಾಶೀಲ",
  "Innovative": "ನವೀನ",
  "AI Story Writer": "AI ಕಥೆ ಬರಹಗಾರ",
  "Generate": "ಜನರೇಟ್ ಮಾಡಿ",
  "Please wait...": "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
  "Result": "ಫಲಿತಾಂಶ",
  "Regenerate": "ಮರು-ಜನರೇಟ್ ಮಾಡಿ",
  "Download": "ಡೌನ್‌ಲೋಡ್",
  "Text copied to clipboard!": "ಪಠ್ಯ ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ!",
  "Please enter a topic": "ದಯವಿಟ್ಟು ಒಂದು ವಿಷಯ ನಮೂದಿಸಿ",
  "Story Magic": "ಕಥೆ ಮಾಯಾ",
  "Let AI bring your thoughts to a full story":
      "AI ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಸಂಪೂರ್ಣ ಕಥೆಯಾಗಿ ಮಾಡಲಿ",
  "Smart Scripts": "ಸ್ಮಾರ್ಟ್ ಸ್ಕ್ರಿಪ್ಟ್‌ಗಳು",
  "From concept to script—fast, easy, and creative":
      "ಪರಿಕಲ್ಪನೆಯಿಂದ ಸ್ಕ್ರಿಪ್ಟ್‌ವರೆಗೆ—ವೇಗವಾಗಿ, ಸುಲಭವಾಗಿ ಮತ್ತು ಸೃಜನಶೀಲವಾಗಿ",
  "Perfect Essays": "ಪರಿಪೂರ್ಣ ಪ್ರಬಂಧಗಳು",
  "You have reached your free limit": "ನೀವು ನಿಮ್ಮ ಉಚಿತ ಮಿತಿಯನ್ನು ತಲುಪಿದ್ದೀರಿ",
  "Donwload": "ಡೌನ್‌ಲೋಡ್",
  "Press again to exit app": "ಅಪ್ಲಿಕೇಶನ್ ತೊರೆಯಲು ಮತ್ತೆ ಒತ್ತಿ",
  "Saved to files": "TXT ಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!",
  "Error: Please try again": "ದೋಷ: ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  "Subscription expired": "ಚಂದಾದಾರಿಕೆ ಮುಕ್ತಾಯವಾಗಿದೆ",
  "Purchase cancelled": "ಖರೀದಿ ರದ್ದು ಮಾಡಲಾಗಿದೆ",
  "Purchase failed": "ಖರೀದಿ ವಿಫಲವಾಗಿದೆ",
  "Restore failed": "ಮರುಸ್ಥಾಪನೆ ವಿಫಲವಾಗಿದೆ",
  "Purchase Successful!": "ಖರೀದಿ ಯಶಸ್ವಿ!",
  "Short (200-500 words)": "ಚಿಕ್ಕದು (200-500 ಪದಗಳು)",
  "Medium (500-1000 words)": "ಮಧ್ಯಮ (500-1000 ಪದಗಳು)",
  "Large (1000+ words)": "ದೊಡ್ಡದು (1000+ ಪದಗಳು)",
  "Academic Level": "ಶೈಕ್ಷಣಿಕ ಮಟ್ಟ",
  "Type of Paper": "ಪೇಪರ್ ಪ್ರಕಾರ",
  "High School": "ಪ್ರೌಢಶಾಲೆ",
  "College": "ಕಾಲೇಜು",
  "Short Film": "ಶಾರ್ಟ್ ಫಿಲ್ಮ್",
  "University": "ವಿಶ್ವವಿದ್ಯಾಲಯ",
  "Masters": "ಮಾಸ್ಟರ್ಸ್",
  "Custom": "ಕಸ್ಟಮ್",
  "Tiktok Video": "ಟಿಕ್‌ಟಾಕ್ ವಿಡಿಯೋ",
  "Movie": "ಚಲನಚಿತ್ರ",
  "Expository": "ವಿವರಣಾತ್ಮಕ",
  "Argumentative": "ವಾದಾತ್ಮಕ",
  "Narrative": "ನಿರೂಪಣಾತ್ಮಕ",
  "Descriptive": "ವರ್ಣನಾತ್ಮಕ",
  "We're sorry to hear that 😔": "ಅದನ್ನು ಕೇಳಿ ನಮಗೆ ವಿಷಾದವಿದೆ 😔",
  "We'll try to improve 🙁": "ನಾವು ಸುಧಾರಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತೇವೆ 🙁",
  "Thanks for your feedback 🙂": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು 🙂",
  "Great! We're glad you like it 😊":
      "ಅದ್ಭುತ! ನಿಮಗೆ ಇದು ಇಷ್ಟವಾಯಿತು ಎಂದು ನಮಗೆ ಸಂತೋಷ 😊",
  "Awesome! Thank you so much! 🎉": "ಅದ್ಭುತ! ತುಂಬಾ ಧನ್ಯವಾದಗಳು! 🎉",
  "Maybe Later": "ಬಹುಶಃ ನಂತರ",
  "Tap a star to rate your experience":
      "ನಿಮ್ಮ ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಲು ನಕ್ಷತ್ರವನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ",
  "Enjoying AI Math Solver?": "AI ಮ್ಯಾಥ್ ಸಾಲ್ವರ್ ಆನಂದಿಸುತ್ತಿದ್ದೀರಾ?",
  "Thank you for rating us": "ನಮ್ಮನ್ನು ರೇಟ್ ಮಾಡಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದಗಳು",
  "Submit Rating": "ರೇಟಿಂಗ್ ಸಲ್ಲಿಸಿ",
  "Hindi": "ಹಿಂದಿ",
  "Enjoying AI Story Generator?": "AI ಕಥೆ ಜನರೇಟರ್ ಆನಂದಿಸುತ್ತಿದ್ದೀರಾ?",
  AppKeys.arabic: "ಅರೇಬಿಕ್",
  AppKeys.chinese: "ಚೀನೀ",
  AppKeys.english: "ಇಂಗ್ಲಿಷ್",
  AppKeys.french: "ಫ್ರೆಂಚ್",
  AppKeys.german: "ಜರ್ಮನ್",
  AppKeys.hindi: "ಹಿಂದಿ",
  AppKeys.indonesian: "ಇಂಡೋನೇಷಿಯನ್",
  AppKeys.japanese: "ಜಪಾನೀಸ್",
  AppKeys.korean: "ಕೊರಿಯನ್",
  AppKeys.portuguese: "ಪೋರ್ಚುಗೀಸ್",
  AppKeys.russian: "ರಷ್ಯನ್",
  AppKeys.spanish: "ಸ್ಪ್ಯಾನಿಷ್",
  AppKeys.turkish: "ಟರ್ಕಿಷ್",

  // New strings for download & actions
  'Download As': 'ಇಂತಹ ರೂಪದಲ್ಲಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  'Choose format to download': 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಫಾರ್ಮ್ಯಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
  'Text File': 'ಟೆಕ್ಸ್ಟ್ ಫೈಲ್',
  'PDF File': 'PDF ಫೈಲ್',
  'Copy': 'ನಕಲಿಸಿ',
  'Share': 'ಹಂಚಿಕೊಳ್ಳಿ',
  'Text copied!': 'ಪಠ್ಯ ನಕಲಿಸಲಾಗಿದೆ!',
  'PDF saved successfully!': 'PDF ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
  'Error creating PDF: Please try again':
      'PDF ರಚಿಸುವಲ್ಲಿ ದೋಷ: ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',

  // Character Story Tool
  'Character Story': 'ಪಾತ್ರದ ಕಥೆ',
  'Character Details': 'ಪಾತ್ರದ ವಿವರಗಳು',
  'Character Name': 'ಪಾತ್ರದ ಹೆಸರು',
  'Age (e.g., 25, Young Adult, Ancient)':
      'ವಯಸ್ಸು (ಉದಾ., 25, ಯುವ ವಯಸ್ಕ, ಪ್ರಾಚೀನ)',
  'Personality (e.g., brave, shy, cunning)':
      'ವ್ಯಕ್ತಿತ್ವ (ಉದಾ., ಧೈರ್ಯಶಾಲಿ, ನಾಚಿಕೆ, ಚಾಣಾಕ್ಷ)',
  'Role (e.g., Hero, Villain, Mentor)': 'ಪಾತ್ರ (ಉದಾ., ನಾಯಕ, ವಿಲನ್, ಮಾರ್ಗದರ್ಶಕ)',
  'Additional Details (optional)': 'ಹೆಚ್ಚುವರಿ ವಿವರಗಳು (ಐಚ್ಛಿಕ)',
  'Output Style': 'ಔಟ್‌ಪುಟ್ ಶೈಲಿ',
  'Generate Character': 'ಪಾತ್ರ ಜನರೇಟ್ ಮಾಡಿ',
  'Please enter character name': 'ದಯವಿಟ್ಟು ಪಾತ್ರದ ಹೆಸರು ನಮೂದಿಸಿ',
  'Please enter character role': 'ದಯವಿಟ್ಟು ಪಾತ್ರದ ಭೂಮಿಕೆ ನಮೂದಿಸಿ',
  'Detailed': 'ವಿಸ್ತೃತ',
  'Brief': 'ಸಂಕ್ಷಿಪ್ತ',
  'Elaborate': 'ವಿಸ್ತಾರವಾದ',

  // Home Screen Tool Cards
  'Create detailed character backstories': 'ವಿಸ್ತೃತ ಪಾತ್ರದ ಹಿನ್ನೆಲೆ ರಚಿಸಿ',
  'Create Character': 'ಪಾತ್ರ ರಚಿಸಿ',
  'Transform and improve your existing stories':
      'ನಿಮ್ಮ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಕಥೆಗಳನ್ನು ರೂಪಾಂತರಿಸಿ ಮತ್ತು ಸುಧಾರಿಸಿ',
  'Rewrite Now': 'ಈಗ ಮರು-ಬರೆಯಿರಿ',
  'Generate catchy titles for your stories':
      'ನಿಮ್ಮ ಕಥೆಗಳಿಗೆ ಆಕರ್ಷಕ ಶೀರ್ಷಿಕೆಗಳನ್ನು ರಚಿಸಿ',
  'Generate Titles': 'ಶೀರ್ಷಿಕೆಗಳನ್ನು ರಚಿಸಿ',

  // Rewrite Story Tool
  'Rewrite Story': 'ಕಥೆಯನ್ನು ಮರು-ಬರೆಯಿರಿ',
  'Paste Your Story': 'ನಿಮ್ಮ ಕಥೆಯನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ',
  'Paste your story here to rewrite...':
      'ಮರು-ಬರೆಯಲು ನಿಮ್ಮ ಕಥೆಯನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...',
  'Select Tone': 'ಧ್ವನಿ ಆಯ್ಕೆಮಾಡಿ',
  'Rewrite Style': 'ಮರು-ಬರೆಯುವ ಶೈಲಿ',
  'Output Length': 'ಔಟ್‌ಪುಟ್ ಉದ್ದ',
  'Please paste your story': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕಥೆಯನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ',
  'Story is too short. Please provide more content.':
      'ಕಥೆ ತುಂಬಾ ಚಿಕ್ಕದಾಗಿದೆ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ವಿಷಯ ಒದಗಿಸಿ.',
  // Tone options
  'Same': 'ಅದೇ',
  'More Dramatic': 'ಹೆಚ್ಚು ನಾಟಕೀಯ',
  'More Humorous': 'ಹೆಚ್ಚು ಹಾಸ್ಯಮಯ',
  'More Emotional': 'ಹೆಚ್ಚು ಭಾವನಾತ್ಮಕ',
  'More Suspenseful': 'ಹೆಚ್ಚು ಉದ್ವೇಗಮಯ',
  'Lighter': 'ಹಗುರ',
  // Style options
  'Improved': 'ಸುಧಾರಿತ',
  'Simplified': 'ಸರಳೀಕೃತ',
  'More Descriptive': 'ಹೆಚ್ಚು ವರ್ಣನಾತ್ಮಕ',
  'More Dialogue': 'ಹೆಚ್ಚು ಸಂಭಾಷಣೆ',
  'More Action': 'ಹೆಚ್ಚು ಆಕ್ಷನ್',
  'Literary': 'ಸಾಹಿತ್ಯಿಕ',
  // Length options
  'Shorter': 'ಚಿಕ್ಕದು',
  'Longer': 'ದೀರ್ಘ',
  'Much Longer': 'ಹೆಚ್ಚು ದೀರ್ಘ',

  // Title Generator Tool
  'Title Generator': 'ಶೀರ್ಷಿಕೆ ಜನರೇಟರ್',
  'Story/Book Topic': 'ಕಥೆ/ಪುಸ್ತಕ ವಿಷಯ',
  'Keywords (Optional)': 'ಕೀವರ್ಡ್‌ಗಳು (ಐಚ್ಛಿಕ)',
  'Describe your story topic or theme...':
      'ನಿಮ್ಮ ಕಥೆಯ ವಿಷಯ ಅಥವಾ ಥೀಮ್ ವಿವರಿಸಿ...',
  'e.g., magic, dragon, adventure': 'ಉದಾ., ಮಾಯಾ, ಡ್ರ್ಯಾಗನ್, ಸಾಹಸ',
  'Title For': 'ಶೀರ್ಷಿಕೆ ಇಂದ',
  'Title Style': 'ಶೀರ್ಷಿಕೆ ಶೈಲಿ',
  "Adventure": "ಸಾಹಸ",
  'Number of Titles': 'ಶೀರ್ಷಿಕೆಗಳ ಸಂಖ್ಯೆ',
  // Type options
  'Book': 'ಪುಸ್ತಕ',
  'Short Story': 'ಸಣ್ಣ ಕಥೆ',
  'Novel': 'ಕಾದಂಬರಿ',
  'Chapter': 'ಅಧ್ಯಾಯ',
  'Series': 'ಸರಣಿ',
  // Title Style options
  'Simple': 'ಸರಳ',
  'Mysterious': 'ರಹಸ್ಯಮಯ',
  'Dramatic': 'ನಾಟಕೀಯ',
  'Catchy': 'ಆಕರ್ಷಕ',
  'Poetic': 'ಕಾವ್ಯಾತ್ಮಕ',
  // Genre options
  'Kids': 'ಮಕ್ಕಳಿಗಾಗಿ',

  // Blog Writer Tool
  'Blog Writer': 'ಬ್ಲಾಗ್ ಬರಹಗಾರ',
  'Blog Topic': 'ಬ್ಲಾಗ್ ವಿಷಯ',
  'Target Keywords': 'ಗುರಿ ಕೀವರ್ಡ್‌ಗಳು',
  'Target Audience (Optional)': 'ಗುರಿ ಪ್ರೇಕ್ಷಕರು (ಐಚ್ಛಿಕ)',
  'Enter your blog topic or title...':
      'ನಿಮ್ಮ ಬ್ಲಾಗ್ ವಿಷಯ ಅಥವಾ ಶೀರ್ಷಿಕೆ ನಮೂದಿಸಿ...',
  'e.g., AI writing, content marketing, SEO tips':
      'ಉದಾ., AI ಬರವಣಿಗೆ, ವಿಷಯ ಮಾರ್ಕೆಟಿಂಗ್, SEO ಸಲಹೆಗಳು',
  'e.g., small business owners, bloggers':
      'ಉದಾ., ಸಣ್ಣ ವ್ಯಾಪಾರ ಮಾಲೀಕರು, ಬ್ಲಾಗರ್‌ಗಳು',
  'Article Type': 'ಲೇಖನ ಪ್ರಕಾರ',
  'Writing Tone': 'ಬರವಣಿಗೆ ಧ್ವನಿ',
  'Article Length': 'ಲೇಖನದ ಉದ್ದ',
  'SEO Options': 'SEO ಆಯ್ಕೆಗಳು',
  'Include Meta Description': 'ಮೆಟಾ ವಿವರಣೆ ಸೇರಿಸಿ',
  'Include Keyword Suggestions': 'ಕೀವರ್ಡ್ ಸಲಹೆಗಳನ್ನು ಸೇರಿಸಿ',
  'Include FAQs Section': 'FAQ ವಿಭಾಗ ಸೇರಿಸಿ',
  'Please enter a blog topic': 'ದಯವಿಟ್ಟು ಒಂದು ಬ್ಲಾಗ್ ವಿಷಯ ನಮೂದಿಸಿ',
  'Generate Blog': 'ಬ್ಲಾಗ್ ಜನರೇಟ್ ಮಾಡಿ',
  'SEO optimized articles with keywords':
      'ಕೀವರ್ಡ್‌ಗಳೊಂದಿಗೆ SEO ಆಪ್ಟಿಮೈಜ್ ಮಾಡಿದ ಲೇಖನಗಳು',
  'Write Blog': 'ಬ್ಲಾಗ್ ಬರೆಯಿರಿ',
  // Article Types
  'SEO Article': 'SEO ಲೇಖನ',
  'How-To Guide': 'ಹೇಗೆ ಮಾಡಬೇಕು ಮಾರ್ಗದರ್ಶಿ',
  'Listicle': 'ಪಟ್ಟಿ ಲೇಖನ',
  'Product Review': 'ಉತ್ಪನ್ನ ವಿಮರ್ಶೆ',
  'Opinion Piece': 'ಅಭಿಪ್ರಾಯ ತುಣುಕು',
  'News Article': 'ಸುದ್ದಿ ಲೇಖನ',
  // Blog Tones
  'Professional': 'ವೃತ್ತಿಪರ',
  'Casual': 'ಆಕಸ್ಮಿಕ',
  'Informative': 'ಮಾಹಿತಿಪ್ರದ',
  'Persuasive': 'ಮನವೊಲಿಸುವ',
  'Friendly': 'ಸ್ನೇಹಪರ',
  'Authoritative': 'ಅಧಿಕೃತ',
  // Blog Lengths
  'Short (500-800)': 'ಚಿಕ್ಕದು (500-800)',
  'Medium (800-1500)': 'ಮಧ್ಯಮ (800-1500)',
  'Long (1500-2500)': 'ದೀರ್ಘ (1500-2500)',
  'Detailed (2500+)': 'ವಿಸ್ತೃತ (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'ಯೂಟ್ಯೂಬ್ ಸ್ಕ್ರಿಪ್ಟ್',
  'Video Topic': 'ವಿಡಿಯೋ ವಿಷಯ',
  'Key Points (Optional)': 'ಮುಖ್ಯ ಅಂಶಗಳು (ಐಚ್ಛಿಕ)',
  'What is your video about?': 'ನಿಮ್ಮ ವಿಡಿಯೋ ಯಾವ ಬಗ್ಗೆ?',
  'List key points to cover (optional)...':
      'ಕವರ್ ಮಾಡಬೇಕಾದ ಮುಖ್ಯ ಅಂಶಗಳ ಪಟ್ಟಿ (ಐಚ್ಛಿಕ)...',
  'Video Duration': 'ವಿಡಿಯೋ ಅವಧಿ',
  'Script Options': 'ಸ್ಕ್ರಿಪ್ಟ್ ಆಯ್ಕೆಗಳು',
  'Include Hook/Intro': 'ಹುಕ್/ಪರಿಚಯ ಸೇರಿಸಿ',
  'Include Call-to-Action': 'ಕ್ರಿಯೆಗೆ ಆಹ್ವಾನ ಸೇರಿಸಿ',
  'Include Timestamps': 'ಸಮಯ ಗುರುತುಗಳನ್ನು ಸೇರಿಸಿ',
  'Please enter a video topic': 'ದಯವಿಟ್ಟು ಒಂದು ವಿಡಿಯೋ ವಿಷಯ ನಮೂದಿಸಿ',
  'Generate Script': 'ಸ್ಕ್ರಿಪ್ಟ್ ಜನರೇಟ್ ಮಾಡಿ',
  'Create scripts for videos & reels':
      'ವಿಡಿಯೋ ಮತ್ತು ರೀಲ್‌ಗಳಿಗಾಗಿ ಸ್ಕ್ರಿಪ್ಟ್ ರಚಿಸಿ',
  'Create Script': 'ಸ್ಕ್ರಿಪ್ಟ್ ರಚಿಸಿ',
  // Script Types
  'Storytime': 'ಕಥೆ ಹೇಳುವ ಸಮಯ',
  'Documentary': 'ಸಾಕ್ಷ್ಯಚಿತ್ರ',
  'Short Reel': 'ಶಾರ್ಟ್ ರೀಲ್',
  'Educational': 'ಶೈಕ್ಷಣಿಕ',
  'Review': 'ವಿಮರ್ಶೆ',
  'Tutorial': 'ಟ್ಯುಟೋರಿಯಲ್',
  // Durations
  '< 1 min (Shorts)': '< 1 ನಿಮಿಷ (ಶಾರ್ಟ್ಸ್)',
  '1-3 min': '1-3 ನಿಮಿಷ',
  '5-10 min': '5-10 ನಿಮಿಷ',
  '10-20 min': '10-20 ನಿಮಿಷ',
  '20+ min': '20+ ನಿಮಿಷ',
  // Script Tones
  'Engaging': 'ಆಕರ್ಷಕ',
  'Energetic': 'ಶಕ್ತಿಶಾಲಿ',
  'Calm': 'ಶಾಂತ',
  'Funny': 'ತಮಾಷೆ',

  // Story Generator - Styles
  'Inspired': 'ಪ್ರೇರಿತ',

  // Script Writer - Script Tones (formats)
  'Film Script': 'ಫಿಲ್ಮ್ ಸ್ಕ್ರಿಪ್ಟ್',
  'Stage Play': 'ರಂಗ ನಾಟಕ',
  'Scene Breakdown': 'ದೃಶ್ಯ ವಿಶ್ಲೇಷಣೆ',
  'Dialogue Only': 'ಸಂಭಾಷಣೆ ಮಾತ್ರ',

  // Ad & UI
  'Ad loading please wait..': 'ಜಾಹೀರಾತು ಲೋಡ್ ಆಗುತ್ತಿದೆ ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ..',

  // Word Counter & Reading Time
  'Words:': 'ಪದಗಳು:',
  'Reading:': 'ಓದುವಿಕೆ:',
};
