import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ko = {
  AppKeys.lblChooseLanguage: "언어 선택",
  "All": "전체",
  "AI Story Generator": "AI 스토리 생성기",
  "Story Generator": "스토리 생성기",
  "Essay Writer": "에세이 작성기",
  "Essay length": "에세이 길이",
  "Script Generator": "스크립트 생성기",
  "Create original stories in seconds": "몇 초 만에 오리지널 스토리 만들기",
  "Academic writing made simple": "학술 글쓰기를 간단하게",
  "Generate powerful scripts for any medium": "모든 매체를 위한 강력한 스크립트 생성",
  "Start Writing": "글쓰기 시작",
  "Create Now": "지금 만들기",
  "Start Generating": "생성 시작",
  "Your Stories": "내 스토리",
  "No stories yet": "아직 스토리가 없습니다",
  "Start creating your first story!": "첫 번째 스토리를 만들어보세요!",
  "Your Story Space Awaits": "스토리 공간이 기다리고 있습니다",
  "Start your first story and see it appear here":
      "첫 번째 스토리를 시작하고 여기에 표시되는 것을 확인하세요",
  "Language": "언어",
  "Rate us": "평가하기",
  "Share us": "공유하기",
  "Privacy Policy": "개인정보 처리방침",
  "Settings": "설정",
  "Select Language": "언어 선택",
  "Dashboard": "대시보드",
  "BENEFITS": "혜택",
  "Subscribe": "구독",
  "Weekly": "주간",
  "Monthly": "월간",
  "Yearly": "연간",
  "week": "주",
  "months": "개월",
  "year": "년",
  "Terms & Condition": "이용약관",
  "No Commitment. Cancel anytime": "약정 없음. 언제든지 취소 가능",
  "No Payment Now": "지금 결제 없음",
  "3 days free": "3일 무료",
  "Start your free trial": "무료 체험 시작",
  "More detailed answers": "더 자세한 답변",
  "Instant responds": "즉각적인 응답",
  "Text recognition": "텍스트 인식",
  "Powered by AI": "AI 기반",
  "Storytelleing": "스토리텔링",
  ' Power': "파워",
  "Unlock your \nFill ": "잠금 해제\n채우기",
  "Your History": "내 기록",
  "Terms and Conditions": "이용약관",
  "Short": "짧음",
  "Medium": "중간",
  "Long": "긴",
  "Length": "길이",
  "Describe your topic...": "주제를 설명하세요...",
  "Set Creativity": "창의성 설정",
  "Standard": "표준",
  "Creative": "창의적",
  "Complex": "복잡한",
  "Select Genre": "장르 선택",
  "Fantasy": "판타지",
  "Mystery": "미스터리",
  "Thriller": "스릴러",
  "Script Tone": "스크립트 톤",
  "Script Type": "스크립트 유형",
  "Comedy": "코미디",
  "Drama": "드라마",
  "Horror": "호러",
  "Action": "액션",
  "Romance": "로맨스",
  "Go Premium": "프리미엄 이용",
  "Unlock Everything": "모두 잠금 해제",
  "Unlimited Story Generation": "무제한 스토리 생성",
  "Write Longer & Detailed Essays": "더 길고 상세한 에세이 작성",
  "Advanced Script Writer": "고급 스크립트 작성기",
  "Unlock All Styles & Tones": "모든 스타일 및 톤 잠금 해제",
  "No Word/Length Limit": "단어/길이 제한 없음",
  "Remove All Ads": "모든 광고 제거",
  "Restore": "복원",
  "YouTube Video": "YouTube 동영상",
  "Podcast": "팟캐스트",
  "Reel": "릴",
  "Motivational": "동기부여",
  "Advertisement": "광고",
  "Fairy Tale": "동화",
  "Sci-Fi": "SF",
  "Select Style": "스타일 선택",
  "Imaginative": "상상력 풍부한",
  "Innovative": "혁신적인",
  "AI Story Writer": "AI 스토리 작가",
  "Generate": "생성",
  "Please wait...": "잠시만 기다려주세요...",
  "Result": "결과",
  "Regenerate": "다시 생성",
  "Download": "다운로드",
  "Text copied to clipboard!": "텍스트가 클립보드에 복사되었습니다!",
  "Please enter a topic": "주제를 입력하세요",
  "Story Magic": "스토리 매직",
  "Let AI bring your thoughts to a full story": "AI가 당신의 생각을 완전한 스토리로 만들어드립니다",
  "Smart Scripts": "스마트 스크립트",
  "From concept to script—fast, easy, and creative":
      "컨셉에서 스크립트까지—빠르고, 쉽고, 창의적으로",
  "Perfect Essays": "완벽한 에세이",
  "You have reached your free limit": "무료 한도에 도달했습니다",
  "Donwload": "다운로드",
  "Press again to exit app": "앱을 종료하려면 다시 누르세요",
  "Saved to files": "TXT 파일이 성공적으로 저장되었습니다!",
  "Error: Please try again": "오류: 다시 시도해주세요",
  "Subscription expired": "구독이 만료되었습니다",
  "Purchase cancelled": "구매가 취소되었습니다",
  "Purchase failed": "구매 실패",
  "Restore failed": "복원 실패",
  "Purchase Successful!": "구매 성공!",
  "Short (200-500 words)": "짧음 (200-500 단어)",
  "Medium (500-1000 words)": "중간 (500-1000 단어)",
  "Large (1000+ words)": "긴 (1000+ 단어)",
  "Academic Level": "학술 수준",
  "Type of Paper": "논문 유형",
  "High School": "고등학교",
  "College": "대학",
  "Short Film": "단편 영화",
  "University": "대학교",
  "Masters": "석사",
  "Custom": "사용자 정의",
  "Tiktok Video": "틱톡 동영상",
  "Movie": "영화",
  "Expository": "설명문",
  "Argumentative": "논증문",
  "Narrative": "서술문",
  "Descriptive": "묘사문",
  "We're sorry to hear that 😔": "그렇게 들어서 유감입니다 😔",
  "We'll try to improve 🙁": "개선하도록 노력하겠습니다 🙁",
  "Thanks for your feedback 🙂": "피드백 감사합니다 🙂",
  "Great! We're glad you like it 😊": "좋아요! 마음에 드셔서 기쁩니다 😊",
  "Awesome! Thank you so much! 🎉": "멋져요! 정말 감사합니다! 🎉",
  "Maybe Later": "나중에",
  "Tap a star to rate your experience": "별을 탭하여 경험을 평가하세요",
  "Enjoying AI Math Solver?": "AI Math Solver를 즐기고 계신가요?",
  "Thank you for rating us": "평가해 주셔서 감사합니다",
  "Submit Rating": "평가 제출",
  "Hindi": "힌디어",
  "Enjoying AI Story Generator?": "AI Story Generator를 즐기고 계신가요?",
  "Adventure": "모험",
  "Inspired": "영감을 받은",
  "Film Script": "영화 시나리오",
  "Stage Play": "무대 연극",
  "Scene Breakdown": "장면 분석",
  "Dialogue Only": "대화만",
  "Ad loading please wait..": "광고 로딩 중 잠시만 기다려주세요...",
  "Words:": "단어:",
  "Reading:": "읽기:",

  AppKeys.arabic: "아랍어",
  AppKeys.chinese: "중국어",
  AppKeys.english: "영어",
  AppKeys.french: "프랑스어",
  AppKeys.german: "독일어",
  AppKeys.hindi: "힌디어",
  AppKeys.indonesian: "인도네시아어",
  AppKeys.japanese: "일본어",
  AppKeys.korean: "한국어",
  AppKeys.portuguese: "포르투갈어",
  AppKeys.russian: "러시아어",
  AppKeys.spanish: "스페인어",
  AppKeys.turkish: "터키어",

  // New strings for download & actions
  'Download As': '다운로드 형식',
  'Choose format to download': '다운로드할 형식을 선택하세요',
  'Text File': '텍스트 파일',
  'PDF File': 'PDF 파일',
  'Copy': '복사',
  'Share': '공유',
  'Text copied!': '텍스트가 복사되었습니다!',
  'Copied to clipboard': '클립보드에 복사됨',
  'File saved successfully': '파일이 성공적으로 저장되었습니다',
  'Error saving file': '파일 저장 오류',
  'Share Story': '스토리 공유',
  'Export': '내보내기',

  "Character Story": "캐릭터 스토리",
  "Create detailed character backstories": "캐릭터의 자세한 배경 이야기를 만드세요",
  "Create Character": "캐릭터 만들기",
  "Rewrite Story": "스토리 다시 작성",
  "Paste Your Story": "스토리를 붙여넣기",
  "Paste your story here to rewrite...": "다시 작성하려면 여기에 스토리를 붙여넣으세요...",
  "Transform and improve your existing stories": "기존 스토리를 변형하고 개선하세요",
  "Title Generator": "제목 생성기",
  "Generate catchy titles for your stories": "스토리를 위한 매력적인 제목 생성",
  "Generate Titles": "제목 생성",
  "Blog Writer": "블로그 작성기",
  "Blog Topic": "블로그 주제",
  "Target Keywords": "대상 키워드",
  "Target Audience (Optional)": "대상 독자 (선택 사항)",
  "Enter your blog topic or title...": "블로그 주제 또는 제목을 입력하세요...",
  "e.g., AI writing, content marketing, SEO tips": "예: AI 글쓰기, 콘텐츠 마케팅, SEO 팁",
  "e.g., small business owners, bloggers": "예: 소규모 사업자, 블로거",
  "Article Type": "기사 유형",
  "Writing Tone": "작성 톤",
  "Article Length": "기사 길이",
  "SEO Options": "SEO 옵션",
  "Include Meta Description": "메타 설명 포함",
  "Include Keyword Suggestions": "키워드 제안 포함",
  "Include FAQs Section": "FAQ 섹션 포함",
  "Please enter a blog topic": "블로그 주제를 입력하세요",
  "Generate Blog": "블로그 생성",
  "SEO optimized articles with keywords": "키워드가 포함된 SEO 최적화 기사",
  "Write Blog": "블로그 작성",
  "YouTube Script": "유튜브 스크립트",
  "Video Topic": "영상 주제",
  "Key Points (Optional)": "핵심 포인트 (선택 사항)",
  "What is your video about?": "영상은 무엇에 관한 것인가요?",
  "List key points to cover (optional)...": "다룰 핵심 포인트를 나열하세요 (선택 사항)...",
  "Video Duration": "영상 길이",
  "Script Options": "스크립트 옵션",
  "Include Hook/Intro": "후크/인트로 포함",
  "Include Call-to-Action": "행동 유도 문구 포함",
  "Include Timestamps": "타임스탬프 포함",
  "Please enter a video topic": "영상 주제를 입력하세요",
  "Generate Script": "스크립트 생성",
  "Create scripts for videos & reels": "영상 및 릴을 위한 스크립트 생성",
  "Create Script": "스크립트 만들기",
  "Character Details": "캐릭터 세부 정보",
  "Character Name": "캐릭터 이름",
  "Age (e.g., 25, Young Adult, Ancient)": "나이 (예: 25, 청년, 고대)",
  "Personality (e.g., brave, shy, cunning)": "성격 (예: 용감한, 수줍은, 교활한)",
  "Role (e.g., Hero, Villain, Mentor)": "역할 (예: 영웅, 악당, 멘토)",
  "Additional Details (optional)": "추가 세부 정보 (선택 사항)",
  "Output Style": "출력 스타일",
  "Generate Character": "캐릭터 생성",
  "Please enter character name": "캐릭터 이름을 입력하세요",
  "Please enter character role": "캐릭터 역할을 입력하세요",
  "Detailed": "상세",
  "Brief": "간단",
  "Elaborate": "정교한",
  "Select Tone": "톤 선택",
  "Rewrite Style": "재작성 스타일",
  "Output Length": "출력 길이",
  "Please paste your story": "스토리를 붙여넣어 주세요",
  "Story is too short. Please provide more content.":
      "스토리가 너무 짧습니다. 더 많은 내용을 제공해 주세요.",
  "Same": "동일",
  "More Dramatic": "더 극적인",
  "More Humorous": "더 유머러스한",
  "More Emotional": "더 감정적인",
  "More Suspenseful": "더 긴장감 있는",
  "Lighter": "더 가벼운",
  "Improved": "개선된",
  "Simplified": "단순화된",
  "More Descriptive": "더 묘사적인",
  "More Dialogue": "더 많은 대화",
  "More Action": "더 많은 액션",
  "Literary": "문학적인",
  "Shorter": "더 짧게",
  "Longer": "더 길게",
  "Much Longer": "훨씬 더 길게",
  "Rewrite Now": "지금 다시 작성",
  "Story/Book Topic": "이야기/책 주제",
  "Keywords (Optional)": "키워드 (선택 사항)",
  "Describe your story topic or theme...": "이야기 주제나 테마를 설명하세요...",
  "e.g., magic, dragon, adventure": "예: 마법, 드래곤, 모험",
  "Title For": "제목 대상",
  "Title Style": "제목 스타일",
  "Number of Titles": "제목 개수",
  "Book": "책",
  "Short Story": "단편 소설",
  "Novel": "소설",
  "Chapter": "챕터",
  "Series": "시리즈",
  "Simple": "단순",
  "Mysterious": "신비로운",
  "Dramatic": "극적인",
  "Catchy": "눈에 띄는",
  "Poetic": "시적인",
  "Kids": "어린이용",
  "SEO Article": "SEO 기사",
  "How-To Guide": "사용법 가이드",
  "Listicle": "리스트형 기사",
  "Product Review": "제품 리뷰",
  "Opinion Piece": "의견 글",
  "News Article": "뉴스 기사",
  "Professional": "전문적인",
  "Casual": "캐주얼",
  "Informative": "정보 제공",
  "Persuasive": "설득력 있는",
  "Friendly": "친근한",
  "Authoritative": "권위 있는",
  "Short (500-800)": "짧음 (500-800)",
  "Medium (800-1500)": "중간 (800-1500)",
  "Long (1500-2500)": "김 (1500-2500)",
  "Detailed (2500+)": "상세 (2500+)",

  "Storytime": "스토리타임",
  "Documentary": "다큐멘터리",
  "Short Reel": "짧은 릴",
  "Educational": "교육용",
  "Review": "리뷰",
  "Tutorial": "튜토리얼",
  "< 1 min (Shorts)": "< 1분 (쇼츠)",
  "1-3 min": "1-3분",
  "5-10 min": "5-10분",
  "10-20 min": "10-20분",
  "20+ min": "20분 이상",
  "Engaging": "흥미로운",
  "Energetic": "활기찬",
  "Calm": "차분한",
  "Funny": "재미있는",
  "Next": "다음",
  "Get Started": "시작하기",
  "Your tool for quick, high-quality essay writing": "빠르고 질 높은 에세이 작성을 위한 도구",
};
