import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ky = {
  AppKeys.lblChooseLanguage: "Тил тандоо",
  "All": "Баары",
  "AI Story Generator": "AI окуя генератору",
  "Story Generator": "Окуя генератору",
  "Essay Writer": "Эссе жазуучу",
  "Essay length": "Эссе узундугу",
  "Script Generator": "Сценарий генератору",
  "Create original stories in seconds":
      "Бир нече секундда оригиналдуу окуялар түзүңүз",
  "Academic writing made simple": "Академиялык жазуу жөнөкөйлөштүрүлдү",
  "Generate powerful scripts for any medium":
      "Каалаган медиа үчүн күчтүү сценарийлерди түзүңүз",
  "Start Writing": "Жазууну баштоо",
  "Create Now": "Азыр түзүү",
  "Start Generating": "Генерацияны баштоо",
  "Your Stories": "Сиздин окуяларыңыз",
  "No stories yet": "Окуялар жок",
  "Start creating your first story!": "Биринчи окуяңызды түзүүнү баштаңыз!",
  "Your Story Space Awaits": "Сиздин окуя мейкиндигиңиз күтүүдө",
  "Start your first story and see it appear here":
      "Биринчи окуяңызды баштаңыз жана анын бул жерде пайда болушун көрүңүз",
  "Language": "Тил",
  "Rate us": "Бизди баалаңыз",
  "Share us": "Бизди бөлүшүңүз",
  "Privacy Policy": "Купуялык саясаты",
  "Settings": "Орнотуулар",
  "Select Language": "Тил тандоо",
  "Dashboard": "Башкаруу панели",
  "BENEFITS": "АРТЫКЧЫЛЫКТАР",
  "Subscribe": "Жазылуу",
  "Weekly": "Апталык",
  "Monthly": "Айлык",
  "Yearly": "Жылдык",
  "week": "апта",
  "months": "ай",
  "year": "жыл",
  "Terms & Condition": "Шарттар жана эрежелер",
  "No Commitment. Cancel anytime":
      "Милдеттенме жок. Каалаган убакта жокко чыгарыңыз",
  "No Payment Now": "Азыр төлөм жок",
  "3 days free": "3 күн бекер",
  "Start your free trial": "Бекер сыноону баштаңыз",
  "More detailed answers": "Кененирээк жооптор",
  "Instant responds": "Дароо жооптор",
  "Text recognition": "Текстти таануу",
  "Powered by AI": "AI менен иштейт",
  "Storytelleing": "Окуя айтуу",
  ' Power': "Күч",
  "Unlock your \nFill ": "Толтурууңузду \nачыңыз",
  "Your History": "Сиздин тарыхыңыз",
  "Terms and Conditions": "Шарттар жана эрежелер",
  "Short": "Кыска",
  "Medium": "Орточо",
  "Long": "Узун",
  "Length": "Узундук",
  "Describe your topic...": "Темаңызды сүрөттөңүз...",
  "Set Creativity": "Чыгармачылыкты орнотуу",
  "Standard": "Стандарт",
  "Creative": "Чыгармачыл",
  "Complex": "Татаал",
  "Select Genre": "Жанр тандоо",
  "Fantasy": "Фантазия",
  "Mystery": "Сыр",
  "Thriller": "Триллер",
  "Script Tone": "Сценарий обону",
  "Script Type": "Сценарий түрү",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Horror": "Коркунуч",
  "Action": "Экшн",
  "Romance": "Романтика",
  "Go Premium": "Премиум алуу",
  "Unlock Everything": "Баарын ачуу",
  "Unlimited Story Generation": "Чексиз окуя генерациясы",
  "Write Longer & Detailed Essays": "Узунураак жана деталдуу эсселер жазыңыз",
  "Advanced Script Writer": "Өнүккөн сценарий жазуучу",
  "Unlock All Styles & Tones": "Бардык стилдерди жана обондорду ачуу",
  "No Word/Length Limit": "Сөз/узундук чеги жок",
  "Remove All Ads": "Бардык жарнамаларды алып салуу",
  "Restore": "Калыбына келтирүү",
  "YouTube Video": "YouTube видеосу",
  "Podcast": "Подкаст",
  "Reel": "Рил",
  "Motivational": "Мотивациялык",
  "Advertisement": "Жарнама",
  "Fairy Tale": "Жомок",
  "Sci-Fi": "Илимий фантастика",
  "Select Style": "Стиль тандоо",
  "Imaginative": "Элестетүүчү",
  "Innovative": "Инновациялык",
  "AI Story Writer": "AI окуя жазуучу",
  "Generate": "Генерациялоо",
  "Please wait...": "Күтө туруңуз...",
  "Result": "Натыйжа",
  "Regenerate": "Кайра генерациялоо",
  "Download": "Жүктөп алуу",
  "Text copied to clipboard!": "Текст алмашуу буферине көчүрүлдү!",
  "Please enter a topic": "Теманы киргизиңиз",
  "Story Magic": "Окуя сыйкыры",
  "Let AI bring your thoughts to a full story":
      "AI'га ойлоруңузду толук окуяга айландырууга уруксат бериңиз",
  "Smart Scripts": "Акылдуу сценарийлер",
  "From concept to script—fast, easy, and creative":
      "Концепциядан сценарийге—тез, оңой жана чыгармачыл",
  "Perfect Essays": "Мыкты эсселер",
  "You have reached your free limit": "Сиз бекер чегиңизге жеттиңиз",
  "Donwload": "Жүктөп алуу",
  "Press again to exit app": "Колдонмодон чыгуу үчүн кайра басыңыз",
  "Saved to files": "TXT файлы ийгиликтүү сакталды!",
  "Error: Please try again": "Ката: кайра аракет кылыңыз",
  "Subscription expired": "Жазылуу мөөнөтү аяктады",
  "Purchase cancelled": "Сатып алуу токтотулду",
  "Purchase failed": "Сатып алуу ишке ашкан жок",
  "Restore failed": "Калыбына келтирүү ишке ашкан жок",
  "Purchase Successful!": "Сатып алуу ийгиликтүү!",
  "Short (200-500 words)": "Кыска (200-500 сөз)",
  "Medium (500-1000 words)": "Орточо (500-1000 сөз)",
  "Large (1000+ words)": "Чоң (1000+ сөз)",
  "Academic Level": "Академиялык деңгээл",
  "Type of Paper": "Кагаз түрү",
  "High School": "Орто мектеп",
  "College": "Колледж",
  "Short Film": "Кыска фильм",
  "University": "Университет",
  "Masters": "Магистратура",
  "Custom": "Жеке",
  "Tiktok Video": "Tiktok видеосу",
  "Movie": "Кино",
  "Expository": "Түшүндүрмө",
  "Argumentative": "Аргументтик",
  "Narrative": "Баян",
  "Descriptive": "Сүрөттөмө",
  "We're sorry to hear that 😔": "Муну уккандыгыбыз үчүн кечирим сурайбыз 😔",
  "We'll try to improve 🙁": "Биз жакшыртууга аракет кылабыз 🙁",
  "Thanks for your feedback 🙂": "Пикириңиз үчүн рахмат 🙂",
  "Great! We're glad you like it 😊": "Сонун! Сизге жакканына кубанычтабыз 😊",
  "Awesome! Thank you so much! 🎉": "Укмуш! Көп рахмат! 🎉",
  "Maybe Later": "Балким кийинчерээк",
  "Tap a star to rate your experience":
      "Тажрыйбаңызды баалоо үчүн жылдызды басыңыз",
  "Enjoying AI Math Solver?": "AI Math Solver жакты беле?",
  "Thank you for rating us": "Бизди баалаганыңыз үчүн рахмат",
  "Submit Rating": "Баа берүү",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "AI Story Generator жакты беле?",
  "Adventure": "Укмуштуу окуя",
  "Inspired": "Шыктандырылган",
  "Film Script": "Кино сценарийи",
  "Stage Play": "Сахна оюну",
  "Scene Breakdown": "Сахна бөлүштүрүлүшү",
  "Dialogue Only": "Диалог гана",
  "Ad loading please wait..": "Жарнама жүктөлүүдө, күтө туруңуз...",
  "Words:": "Сөздөр:",
  "Reading:": "Окуу:",

  AppKeys.arabic: "Арабча",
  AppKeys.chinese: "Кытайча",
  AppKeys.english: "Англисче",
  AppKeys.french: "Французча",
  AppKeys.german: "Немисче",
  AppKeys.hindi: "Хиндиче",
  AppKeys.indonesian: "Индонезияча",
  AppKeys.japanese: "Жапончо",
  AppKeys.korean: "Корейче",
  AppKeys.portuguese: "Португалча",
  AppKeys.russian: "Орусча",
  AppKeys.spanish: "Испанча",
  AppKeys.turkish: "Түркчө",

  // New strings for download & actions
  'Download As': 'Жүктөп алуу',
  'Choose format to download': 'Жүктөп алуу форматын тандаңыз',
  'Text File': 'Текст файлы',
  'PDF File': 'PDF файлы',
  'Copy': 'Көчүрүү',
  'Share': 'Бөлүшүү',
  'Text copied!': 'Текст көчүрүлдү!',
  'Copied to clipboard': 'Алмашуу буферине көчүрүлдү',
  'File saved successfully': 'Файл ийгиликтүү сакталды',
  'Error saving file': 'Файлды сактоо катасы',
  'Share Story': 'Окуяны бөлүшүү',
  'Export': 'Экспорттоо',
  "Character Story": "Каарман окуясы",
  "Create detailed character backstories":
      "Каармандын деталдуу тарых окуясын түзүңүз",
  "Create Character": "Каарман түзүү",
  "Rewrite Story": "Окуяны кайра жазуу",
  "Paste Your Story": "Окуяңызды чаптаңыз",
  "Paste your story here to rewrite...":
      "Кайра жазуу үчүн окуяңызды бул жерге чаптаңыз...",
  "Transform and improve your existing stories":
      "Учурдагы окуяларыңызды өзгөртүп, жакшыртыңыз",
  "Title Generator": "Аталыш генератору",
  "Generate catchy titles for your stories":
      "Окуяларыңыз үчүн кызыктуу аталыштар түзүңүз",
  "Generate Titles": "Аталыштарды түзүү",
  "Blog Writer": "Блог жазуучу",
  "Blog Topic": "Блог темасы",
  "Target Keywords": "Максаттуу ачкыч сөздөр",
  "Target Audience (Optional)": "Максаттуу аудитория (Милдеттүү эмес)",
  "Enter your blog topic or title...":
      "Блогуңуздун темасын же аталышын киргизиңиз...",
  "e.g., AI writing, content marketing, SEO tips":
      "Мис., AI жазуу, мазмун маркетинги, SEO кеңештери",
  "e.g., small business owners, bloggers":
      "Мис., кичи бизнес ээлери, блогерлер",
  "Article Type": "Макала түрү",
  "Writing Tone": "Жазуу тону",
  "Article Length": "Макаланын узундугу",
  "SEO Options": "SEO параметрлери",
  "Include Meta Description": "Мета сүрөттөмөнү кошуу",
  "Include Keyword Suggestions": "Ачкыч сөз сунуштарын кошуу",
  "Include FAQs Section": "КБС бөлүмүн кошуу",
  "Please enter a blog topic": "Блог темасын киргизиңиз",
  "Generate Blog": "Блог түзүү",
  "SEO optimized articles with keywords":
      "Ачкыч сөздөр менен SEO оптималдаштырылган макалалар",
  "Write Blog": "Блог жазуу",
  "YouTube Script": "YouTube сценарийи",
  "Video Topic": "Видео темасы",
  "Key Points (Optional)": "Негизги пункттар (Милдеттүү эмес)",
  "What is your video about?": "Видеоңуз эмне жөнүндө?",
  "List key points to cover (optional)...":
      "Камтыла турган негизги пункттарды тизмелеңиз (милдеттүү эмес)...",
  "Video Duration": "Видео узактыгы",
  "Script Options": "Сценарий параметрлери",
  "Include Hook/Intro": "Кириш/Тааныштырууну кошуу",
  "Include Call-to-Action": "Иш-аракетке чакырыкты кошуу",
  "Include Timestamps": "Убакыт белгилерин кошуу",
  "Please enter a video topic": "Видео темасын киргизиңиз",
  "Generate Script": "Сценарий түзүү",
  "Create scripts for videos & reels":
      "Видеолор жана рилдер үчүн сценарийлерди түзүңүз",
  "Create Script": "Сценарий түзүү",
  "Character Details": "Каарман деталдары",
  "Character Name": "Каармандын аты",
  "Age (e.g., 25, Young Adult, Ancient)": "Жашы (мис., 25, Жаш, Байыркы)",
  "Personality (e.g., brave, shy, cunning)":
      "Мүнөзү (мис., эр жүрөк, уялчаак, айлакер)",
  "Role (e.g., Hero, Villain, Mentor)": "Ролу (мис., Баатыр, Залим, Насаатчы)",
  "Additional Details (optional)": "Кошумча маалымат (милдеттүү эмес)",
  "Output Style": "Чыгаруу стили",
  "Generate Character": "Каарман түзүү",
  "Please enter character name": "Каармандын атын киргизиңиз",
  "Please enter character role": "Каармандын ролун киргизиңиз",
  "Detailed": "Деталдуу",
  "Brief": "Кыскача",
  "Elaborate": "Кеңири",
  "Select Tone": "Тонду тандаңыз",
  "Rewrite Style": "Кайра жазуу стили",
  "Output Length": "Чыгаруунун узундугу",
  "Please paste your story": "Окуяңызды чаптаңыз",
  "Story is too short. Please provide more content.":
      "Окуя өтө кыска. Көбүрөөк мазмун бериңиз.",
  "Same": "Бирдей",
  "More Dramatic": "Дагы драмалуу",
  "More Humorous": "Дагы юморлуу",
  "More Emotional": "Дагы эмоционалдуу",
  "More Suspenseful": "Дагы чыңалуулуу",
  "Lighter": "Жеңилирээк",
  "Improved": "Жакшыртылган",
  "Simplified": "Жөнөкөйлөштүрүлгөн",
  "More Descriptive": "Дагы сүрөттөмөлүү",
  "More Dialogue": "Дагы диалог",
  "More Action": "Дагы аракет",
  "Literary": "Адабий",
  "Shorter": "Кыскараак",
  "Longer": "Узунураак",
  "Much Longer": "Алда канча узунураак",
  "Rewrite Now": "Азыр кайра жазуу",
  "Story/Book Topic": "Окуя/Китеп темасы",
  "Keywords (Optional)": "Ачкыч сөздөр (Милдеттүү эмес)",
  "Describe your story topic or theme...":
      "Окуяңыздын темасын же багытын сүрөттөңүз...",
  "e.g., magic, dragon, adventure": "Мис., сыйкыр, айдаhар, укмуштуу саякат",
  "Title For": "Аталышы",
  "Title Style": "Аталыш стили",
  "Number of Titles": "Аталыштардын саны",
  "Book": "Китеп",
  "Short Story": "Аңгеме",
  "Novel": "Роман",
  "Chapter": "Бөлүм",
  "Series": "Сериал",
  "Simple": "Жөнөкөй",
  "Mysterious": "Сырдуу",
  "Dramatic": "Драмалуу",
  "Catchy": "Тарткыч",
  "Poetic": "Поэтикалык",
  "Kids": "Балдар үчүн",
  "SEO Article": "SEO макаласы",
  "How-To Guide": "Колдонмо",
  "Listicle": "Тизме макала",
  "Product Review": "Продукт сын-пикири",
  "Opinion Piece": "Пикир жазуу",
  "News Article": "Жаңылык макаласы",
  "Professional": "Кесипкөй",
  "Casual": "Кадимки",
  "Informative": "Маалыматтуу",
  "Persuasive": "Ынандыруучу",
  "Friendly": "Достук",
  "Authoritative": "Авторитеттүү",
  "Short (500-800)": "Кыска (500-800)",
  "Medium (800-1500)": "Орто (800-1500)",
  "Long (1500-2500)": "Узун (1500-2500)",
  "Detailed (2500+)": "Деталдуу (2500+)",
  "Storytime": "Окуя убактысы",
  "Documentary": "Документалдык",
  "Short Reel": "Кыска рил",
  "Educational": "Билим берүүчү",
  "Review": "Сын-пикир",
  "Tutorial": "Окутуу",
  "< 1 min (Shorts)": "< 1 мүн (Кыска)",
  "1-3 min": "1-3 мүн",
  "5-10 min": "5-10 мүн",
  "10-20 min": "10-20 мүн",
  "20+ min": "20+ мүн",
  "Engaging": "Кызыктуу",
  "Energetic": "Энергиялуу",
  "Calm": "Тынч",
  "Funny": "Күлкүлүү",
  "Next": "Кийинки",
  "Get Started": "Баштоо",
  "Your tool for quick, high-quality essay writing":
      "Тез жана сапаттуу эссе жазуу куралы",
};
