import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> lo = {
  AppKeys.lblChooseLanguage: "ເລືອກພາສາ",
  "All": "ທັງໝົດ",
  "AI Story Generator": "ເຄື່ອງສ້າງເລື່ອງ AI",
  "Story Generator": "ເຄື່ອງສ້າງເລື່ອງ",
  "Essay Writer": "ນັກຂຽນບົດຄວາມ",
  "Essay length": "ຄວາມຍາວບົດຄວາມ",
  "Script Generator": "ເຄື່ອງສ້າງສະຄຣິບ",
  "Create original stories in seconds": "ສ້າງເລື່ອງຕົ້ນສະບັບໃນບໍ່ເທົ່າໃດວິນາທີ",
  "Academic writing made simple": "ການຂຽນທາງວິຊາການເຮັດໃຫ້ງ່າຍ",
  "Generate powerful scripts for any medium": "ສ້າງສະຄຣິບທີ່ມີພະລັງສຳລັບທຸກສື່",
  "Start Writing": "ເລີ່ມຂຽນ",
  "Create Now": "ສ້າງດຽວນີ້",
  "Start Generating": "ເລີ່ມການສ້າງ",
  "Your Stories": "ເລື່ອງຂອງເຈົ້າ",
  "No stories yet": "ຍັງບໍ່ມີເລື່ອງ",
  "Start creating your first story!": "ເລີ່ມສ້າງເລື່ອງທຳອິດຂອງເຈົ້າ!",
  "Your Story Space Awaits": "ພື້ນທີ່ເລື່ອງຂອງເຈົ້າກຳລັງລໍຖ້າ",
  "Start your first story and see it appear here":
      "ເລີ່ມເລື່ອງທຳອິດຂອງເຈົ້າ ແລະ ເບິ່ງມັນປາກົດຢູ່ນີ້",
  "Language": "ພາສາ",
  "Rate us": "ໃຫ້ຄະແນນພວກເຮົາ",
  "Share us": "ແບ່ງປັນພວກເຮົາ",
  "Privacy Policy": "ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ",
  "Settings": "ການຕັ້ງຄ່າ",
  "Select Language": "ເລືອກພາສາ",
  "Dashboard": "ແຜງຄວບຄຸມ",
  "BENEFITS": "ຜົນປະໂຫຍດ",
  "Subscribe": "ສະໝັກ",
  "Weekly": "ລາຍອາທິດ",
  "Monthly": "ລາຍເດືອນ",
  "Yearly": "ລາຍປີ",
  "week": "ອາທິດ",
  "months": "ເດືອນ",
  "year": "ປີ",
  "Terms & Condition": "ຂໍ້ກຳນົດ ແລະ ເງື່ອນໄຂ",
  "No Commitment. Cancel anytime": "ບໍ່ມີພັນທະ. ຍົກເລີກໄດ້ທຸກເວລາ",
  "No Payment Now": "ບໍ່ຕ້ອງຈ່າຍຕອນນີ້",
  "3 days free": "ຟຣີ 3 ມື້",
  "Start your free trial": "ເລີ່ມການທົດລອງຟຣີ",
  "More detailed answers": "ຄຳຕອບລະອຽດກວ່າ",
  "Instant responds": "ຕອບກັບທັນທີ",
  "Text recognition": "ການຮັບຮູ້ຂໍ້ຄວາມ",
  "Powered by AI": "ຂັບເຄື່ອນດ້ວຍ AI",
  "Storytelleing": "ການເລົ່າເລື່ອງ",
  ' Power': "ພະລັງ",
  "Unlock your \nFill ": "ປົດລ໋ອກ\nການຕື່ມຂອງເຈົ້າ",
  "Your History": "ປະຫວັດຂອງເຈົ້າ",
  "Terms and Conditions": "ຂໍ້ກຳນົດ ແລະ ເງື່ອນໄຂ",
  "Short": "ສັ້ນ",
  "Medium": "ກາງ",
  "Long": "ຍາວ",
  "Length": "ຄວາມຍາວ",
  "Describe your topic...": "ອະທິບາຍຫົວຂໍ້ຂອງເຈົ້າ...",
  "Set Creativity": "ຕັ້ງຄ່າຄວາມຄິດສ້າງສັນ",
  "Standard": "ມາດຕະຖານ",
  "Creative": "ສ້າງສັນ",
  "Complex": "ຊັບຊ້ອນ",
  "Select Genre": "ເລືອກປະເພດ",
  "Fantasy": "ແຟນຕາຊີ",
  "Mystery": "ລຶກລັບ",
  "Thriller": "ລະຄອນ",
  "Script Tone": "ສຽງສະຄຣິບ",
  "Script Type": "ປະເພດສະຄຣິບ",
  "Comedy": "ຕະຫຼົກ",
  "Drama": "ລະຄອນ",
  "Horror": "ສະຍອງຂວັນ",
  "Action": "ແອັກຊັນ",
  "Romance": "ຮັກໂລແມນຕິກ",
  "Go Premium": "ໄປ Premium",
  "Unlock Everything": "ປົດລ໋ອກທຸກຢ່າງ",
  "Unlimited Story Generation": "ການສ້າງເລື່ອງບໍ່ຈຳກັດ",
  "Write Longer & Detailed Essays": "ຂຽນບົດຄວາມຍາວ ແລະ ລະອຽດກວ່າ",
  "Advanced Script Writer": "ນັກຂຽນສະຄຣິບຂັ້ນສູງ",
  "Unlock All Styles & Tones": "ປົດລ໋ອກທຸກແບບ ແລະ ສຽງ",
  "No Word/Length Limit": "ບໍ່ມີຂໍ້ຈຳກັດຄຳ/ຄວາມຍາວ",
  "Remove All Ads": "ລົບໂຄສະນາທັງໝົດ",
  "Restore": "ຟື້ນຟູ",
  "YouTube Video": "ວິດີໂອ YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "ສ້າງແຮງບັນດານໃຈ",
  "Advertisement": "ໂຄສະນາ",
  "Fairy Tale": "ເທບນິຍາຍ",
  "Sci-Fi": "ວິທະຍາສາດ",
  "Select Style": "ເລືອກແບບ",
  "Imaginative": "ຈິນຕະນາການ",
  "Innovative": "ນະວັດຕະກຳ",
  "AI Story Writer": "ນັກຂຽນເລື່ອງ AI",
  "Generate": "ສ້າງ",
  "Please wait...": "ກະລຸນາລໍຖ້າ...",
  "Result": "ຜົນໄດ້ຮັບ",
  "Regenerate": "ສ້າງໃໝ່",
  "Download": "ດາວໂຫລດ",
  "Text copied to clipboard!": "ຄັດລອກຂໍ້ຄວາມໄປຄລິບບອດແລ້ວ!",
  "Please enter a topic": "ກະລຸນາໃສ່ຫົວຂໍ້",
  "Story Magic": "ມະຫັດສະຈັນເລື່ອງ",
  "Let AI bring your thoughts to a full story":
      "ໃຫ້ AI ນຳຄວາມຄິດຂອງເຈົ້າໄປສູ່ເລື່ອງເຕັມ",
  "Smart Scripts": "ສະຄຣິບສະຫຼາດ",
  "From concept to script—fast, easy, and creative":
      "ຈາກແນວຄິດຫາສະຄຣິບ—ໄວ, ງ່າຍ, ແລະ ສ້າງສັນ",
  "Perfect Essays": "ບົດຄວາມສົມບູນແບບ",
  "You have reached your free limit": "ເຈົ້າຮອດຂີດຈຳກັດຟຣີຂອງເຈົ້າແລ້ວ",
  "Donwload": "ດາວໂຫລດ",
  "Press again to exit app": "ກົດອີກຄັ້ງເພື່ອອອກຈາກແອັບ",
  "Saved to files": "ບັນທຶກໄຟລ໌ TXT ສຳເລັດແລ້ວ!",
  "Error: Please try again": "ຂໍ້ຜິດພາດ: ກະລຸນາລອງໃໝ່",
  "Subscription expired": "ການສະໝັກໝົດອາຍຸ",
  "Purchase cancelled": "ຍົກເລີກການຊື້ແລ້ວ",
  "Purchase failed": "ການຊື້ລົ້ມເຫລວ",
  "Restore failed": "ການຟື້ນຟູລົ້ມເຫລວ",
  "Purchase Successful!": "ການຊື້ສຳເລັດ!",
  "Short (200-500 words)": "ສັ້ນ (200-500 ຄຳ)",
  "Medium (500-1000 words)": "ກາງ (500-1000 ຄຳ)",
  "Large (1000+ words)": "ໃຫຍ່ (1000+ ຄຳ)",
  "Academic Level": "ລະດັບວິຊາການ",
  "Type of Paper": "ປະເພດເຈ້ຍ",
  "High School": "ໂຮງຮຽນມັດທະຍົມ",
  "College": "ວິທະຍາໄລ",
  "Short Film": "ຮູບເງົາສັ້ນ",
  "University": "ມະຫາວິທະຍາໄລ",
  "Masters": "ປະລິນຍາໂທ",
  "Custom": "ກຳນົດເອງ",
  "Tiktok Video": "ວິດີໂອ Tiktok",
  "Movie": "ຮູບເງົາ",
  "Expository": "ອະທິບາຍ",
  "Argumentative": "ໂຕ້ແຍ້ງ",
  "Narrative": "ເລື່ອງເລົ່າ",
  "Descriptive": "ພັນລະນາ",
  "We're sorry to hear that 😔": "ພວກເຮົາເສຍໃຈທີ່ໄດ້ຍິນແນວນັ້ນ 😔",
  "We'll try to improve 🙁": "ພວກເຮົາຈະພະຍາຍາມປັບປຸງ 🙁",
  "Thanks for your feedback 🙂": "ຂອບໃຈສຳລັບຄຳຕິຊົມຂອງທ່ານ 🙂",
  "Great! We're glad you like it 😊": "ດີຫຼາຍ! ພວກເຮົາດີໃຈທີ່ທ່ານມັກ 😊",
  "Awesome! Thank you so much! 🎉": "ສຸດຍອດ! ຂອບໃຈຫຼາຍໆ! 🎉",
  "Maybe Later": "ບາງທີທີຫຼັງ",
  "Tap a star to rate your experience": "ແຕະດາວເພື່ອໃຫ້ຄະແນນປະສົບການຂອງທ່ານ",
  "Enjoying AI Math Solver?": "ມັກ AI Math Solver ບໍ່?",
  "Thank you for rating us": "ຂອບໃຈທີ່ໃຫ້ຄະແນນພວກເຮົາ",
  "Submit Rating": "ສົ່ງຄະແນນ",
  "Hindi": "ຮິນດີ",
  "Enjoying AI Story Generator?": "ມັກ AI Story Generator ບໍ່?",
  "Adventure": "ການຜະຈົນໄພ",
  "Inspired": "ໄດ້ຮັບແຮງບັນດານໃຈ",
  "Film Script": "ສະຄຣິບຮູບເງົາ",
  "Stage Play": "ການສະແດງເວທີ",
  "Scene Breakdown": "ການແບ່ງສາກ",
  "Dialogue Only": "ບົດສົນທະນາເທົ່ານັ້ນ",
  "Ad loading please wait..": "ກຳລັງໂຫລດໂຄສະນາ ກະລຸນາລໍຖ້າ...",
  "Words:": "ຄຳ:",
  "Reading:": "ການອ່ານ:",

  AppKeys.arabic: "ອາຣັບ",
  AppKeys.chinese: "ຈີນ",
  AppKeys.english: "ອັງກິດ",
  AppKeys.french: "ຝຣັ່ງ",
  AppKeys.german: "ເຢຍລະມັນ",
  AppKeys.hindi: "ຮິນດີ",
  AppKeys.indonesian: "ອິນໂດເນເຊຍ",
  AppKeys.japanese: "ຍີ່ປຸ່ນ",
  AppKeys.korean: "ເກົາຫຼີ",
  AppKeys.portuguese: "ໂປຕຸເກດ",
  AppKeys.russian: "ຣັດເຊຍ",
  AppKeys.spanish: "ສະເປນ",
  AppKeys.turkish: "ຕວກກີ",

  // New strings for download & actions
  'Download As': 'ດາວໂຫລດເປັນ',
  'Choose format to download': 'ເລືອກຮູບແບບເພື່ອດາວໂຫລດ',
  'Text File': 'ໄຟລ໌ຂໍ້ຄວາມ',
  'PDF File': 'ໄຟລ໌ PDF',
  'Copy': 'ຄັດລອກ',
  'Share': 'ແບ່ງປັນ',
  'Text copied!': 'ຄັດລອກຂໍ້ຄວາມແລ້ວ!',
  'Copied to clipboard': 'ຄັດລອກໄປຄລິບບອດແລ້ວ',
  'File saved successfully': 'ບັນທຶກໄຟລ໌ສຳເລັດ',
  'Error saving file': 'ຂໍ້ຜິດພາດໃນການບັນທຶກໄຟລ໌',
  'Share Story': 'ແບ່ງປັນເລື່ອງ',
  'Export': 'ສົ່ງອອກ',

  "Character Story": "ເລື່ອງຕົວລະຄອນ",
  "Create detailed character backstories":
      "ສ້າງປະຫວັດຄວາມເປັນມາຂອງຕົວລະຄອນຢ່າງລະອຽດ",
  "Create Character": "ສ້າງຕົວລະຄອນ",
  "Rewrite Story": "ຂຽນເລື່ອງໃໝ່",
  "Paste Your Story": "ວາງເລື່ອງຂອງທ່ານ",
  "Paste your story here to rewrite...": "ວາງເລື່ອງຂອງທ່ານທີ່ນີ້ເພື່ອຂຽນໃໝ່...",
  "Transform and improve your existing stories":
      "ປ່ຽນແປງ ແລະ ປັບປຸງເລື່ອງທີ່ມີຢູ່ຂອງທ່ານ",
  "Title Generator": "ເຄື່ອງສ້າງຫົວຂໍ້",
  "Generate catchy titles for your stories":
      "ສ້າງຫົວຂໍ້ທີ່ໜ້າດຶງດູດສໍາລັບເລື່ອງຂອງທ່ານ",
  "Generate Titles": "ສ້າງຫົວຂໍ້",
  "Blog Writer": "ນັກຂຽນບລັອກ",
  "Blog Topic": "ຫົວຂໍ້ບລັອກ",
  "Target Keywords": "ຄໍາຄົ້ນຫາເປົ້າໝາຍ",
  "Target Audience (Optional)": "ກຸ່ມເປົ້າໝາຍ (ທາງເລືອກ)",
  "Enter your blog topic or title...": "ໃສ່ຫົວຂໍ້ ຫຼື ຊື່ບລັອກຂອງທ່ານ...",
  "e.g., AI writing, content marketing, SEO tips":
      "ເຊັ່ນ: ການຂຽນ AI, ການຕະຫຼາດເນື້ອຫາ, ຄໍາແນະນໍາ SEO",
  "e.g., small business owners, bloggers":
      "ເຊັ່ນ: ເຈົ້າຂອງທຸລະກິດຂະໜາດນ້ອຍ, ນັກຂຽນບລັອກ",
  "Article Type": "ປະເພດບົດຄວາມ",
  "Writing Tone": "ນໍ້າສຽງການຂຽນ",
  "Article Length": "ຄວາມຍາວບົດຄວາມ",
  "SEO Options": "ທາງເລືອກ SEO",
  "Include Meta Description": "ລວມຄໍາອະທິບາຍ Meta",
  "Include Keyword Suggestions": "ລວມຄໍາແນະນໍາຄໍາຄົ້ນຫາ",
  "Include FAQs Section": "ລວມສ່ວນ FAQ",
  "Please enter a blog topic": "ກະລຸນາໃສ່ຫົວຂໍ້ບລັອກ",
  "Generate Blog": "ສ້າງບລັອກ",
  "SEO optimized articles with keywords": "ບົດຄວາມທີ່ປັບປຸງ SEO ດ້ວຍຄໍາຄົ້ນຫາ",
  "Write Blog": "ຂຽນບລັອກ",
  "YouTube Script": "ສະຄຣິບ YouTube",
  "Video Topic": "ຫົວຂໍ້ວິດີໂອ",
  "Key Points (Optional)": "ຈຸດສໍາຄັນ (ທາງເລືອກ)",
  "What is your video about?": "ວິດີໂອຂອງທ່ານກ່ຽວກັບຫຍັງ?",
  "List key points to cover (optional)...":
      "ລາຍຊື່ຈຸດສໍາຄັນທີ່ຕ້ອງກວມເອົາ (ທາງເລືອກ)...",
  "Video Duration": "ໄລຍະເວລາວິດີໂອ",
  "Script Options": "ທາງເລືອກສະຄຣິບ",
  "Include Hook/Intro": "ລວມການແນະນໍາ/ບົດນໍາ",
  "Include Call-to-Action": "ລວມການກະຕຸ້ນໃຫ້ດໍາເນີນການ",
  "Include Timestamps": "ລວມເວລາ",
  "Please enter a video topic": "ກະລຸນາໃສ່ຫົວຂໍ້ວິດີໂອ",
  "Generate Script": "ສ້າງສະຄຣິບ",
  "Create scripts for videos & reels": "ສ້າງສະຄຣິບສໍາລັບວິດີໂອ ແລະ ຣີລ",
  "Create Script": "ສ້າງສະຄຣິບ",
  "Character Details": "ລາຍລະອຽດຕົວລະຄອນ",
  "Character Name": "ຊື່ຕົວລະຄອນ",
  "Age (e.g., 25, Young Adult, Ancient)": "ອາຍຸ (ເຊັ່ນ: 25, ໜຸ່ມ, ບູຮານ)",
  "Personality (e.g., brave, shy, cunning)":
      "ບຸກຄະລິກ (ເຊັ່ນ: ກ້າຫານ, ອາຍ, ສະຫຼາດ)",
  "Role (e.g., Hero, Villain, Mentor)":
      "ບົດບາດ (ເຊັ່ນ: ວີລະບຸລຸດ, ຜູ້ຮ້າຍ, ຜູ້ແນະນໍາ)",
  "Additional Details (optional)": "ລາຍລະອຽດເພີ່ມເຕີມ (ທາງເລືອກ)",
  "Output Style": "ຮູບແບບຜົນລັບ",
  "Generate Character": "ສ້າງຕົວລະຄອນ",
  "Please enter character name": "ກະລຸນາໃສ່ຊື່ຕົວລະຄອນ",
  "Please enter character role": "ກະລຸນາໃສ່ບົດບາດຕົວລະຄອນ",
  "Detailed": "ລະອຽດ",
  "Brief": "ຫຍໍ້",
  "Elaborate": "ລາຍລະອຽດ",
  "Select Tone": "ເລືອກນໍ້າສຽງ",
  "Rewrite Style": "ຮູບແບບຂຽນໃໝ່",
  "Output Length": "ຄວາມຍາວຜົນລັບ",
  "Please paste your story": "ກະລຸນາວາງເລື່ອງຂອງທ່ານ",
  "Story is too short. Please provide more content.":
      "ເລື່ອງສັ້ນເກີນໄປ. ກະລຸນາໃສ່ເນື້ອຫາເພີ່ມເຕີມ.",
  "Same": "ຄືກັນ",
  "More Dramatic": "ດຣາມາຫຼາຍຂຶ້ນ",
  "More Humorous": "ຕະຫຼົກຫຼາຍຂຶ້ນ",
  "More Emotional": "ອ່ອນໄຫວຫຼາຍຂຶ້ນ",
  "More Suspenseful": "ໜ້າລຸ້ນລ້ຽວຫຼາຍຂຶ້ນ",
  "Lighter": "ເບົາກວ່າ",
  "Improved": "ປັບປຸງແລ້ວ",
  "Simplified": "ງ່າຍຂຶ້ນ",
  "More Descriptive": "ອະທິບາຍຫຼາຍຂຶ້ນ",
  "More Dialogue": "ບົດສົນທະນາຫຼາຍຂຶ້ນ",
  "More Action": "ການກະທໍາຫຼາຍຂຶ້ນ",
  "Literary": "ວັນນະກໍາ",
  "Shorter": "ສັ້ນກວ່າ",
  "Longer": "ຍາວກວ່າ",
  "Much Longer": "ຍາວກວ່າຫຼາຍ",
  "Rewrite Now": "ຂຽນໃໝ່ດຽວນີ້",
  "Story/Book Topic": "ຫົວຂໍ້ເລື່ອງ/ໜັງສື",
  "Keywords (Optional)": "ຄໍາຄົ້ນຫາ (ທາງເລືອກ)",
  "Describe your story topic or theme...":
      "ອະທິບາຍຫົວຂໍ້ ຫຼື ຫົວຂໍ້ເລື່ອງຂອງທ່ານ...",
  "e.g., magic, dragon, adventure": "ເຊັ່ນ: ມະນົດ, ມັງກອນ, ການຜະຈົນໄພ",
  "Title For": "ຫົວຂໍ້ສໍາລັບ",
  "Title Style": "ຮູບແບບຫົວຂໍ້",
  "Number of Titles": "ຈໍານວນຫົວຂໍ້",
  "Book": "ໜັງສື",
  "Short Story": "ເລື່ອງສັ້ນ",
  "Novel": "ນິຍາຍ",
  "Chapter": "ບົດ",
  "Series": "ຊຸດ",
  "Simple": "ງ່າຍດາຍ",
  "Mysterious": "ລຶກລັບ",
  "Dramatic": "ດຣາມາ",
  "Catchy": "ດຶງດູດ",
  "Poetic": "ກະວີ",
  "Kids": "ເດັກນ້ອຍ",
  "SEO Article": "ບົດຄວາມ SEO",
  "How-To Guide": "ຄູ່ມືການນໍາໃຊ້",
  "Listicle": "ບົດຄວາມລາຍການ",
  "Product Review": "ການທົບທວນຜະລິດຕະພັນ",
  "Opinion Piece": "ບົດຄວາມຄໍາເຫັນ",
  "News Article": "ບົດຄວາມຂ່າວ",
  "Professional": "ເປັນມືອາຊີບ",
  "Casual": "ທໍາມະດາ",
  "Informative": "ໃຫ້ຂໍ້ມູນ",
  "Persuasive": "ໂນ້ມໜ້າວ",
  "Friendly": "ເປັນກັນເອງ",
  "Authoritative": "ມີສິດທິ",
  "Short (500-800)": "ສັ້ນ (500-800)",
  "Medium (800-1500)": "ກາງ (800-1500)",
  "Long (1500-2500)": "ຍາວ (1500-2500)",
  "Detailed (2500+)": "ລະອຽດ (2500+)",
  "Storytime": "ເວລາເລື່ອງ",
  "Documentary": "ສາລະຄະດີ",
  "Short Reel": "ຣີລສັ້ນ",
  "Educational": "ການສຶກສາ",
  "Review": "ການທົບທວນ",
  "Tutorial": "ການສອນ",
  "< 1 min (Shorts)": "< 1 ນາທີ (ສັ້ນ)",
  "1-3 min": "1-3 ນາທີ",
  "5-10 min": "5-10 ນາທີ",
  "10-20 min": "10-20 ນາທີ",
  "20+ min": "20+ ນາທີ",
  "Engaging": "ໜ້າສົນໃຈ",
  "Energetic": "ກະຕືລືລົ້ນ",
  "Calm": "ສະຫງົບ",
  "Funny": "ຕະຫຼົກ",
  "Next": "ຕໍ່ໄປ",
  "Get Started": "ເລີ່ມຕົ້ນ",
  "Your tool for quick, high-quality essay writing":
      "ເຄື່ອງມືຂຽນບົດຄວາມໄວ ແລະ ມີຄຸນນະພາບສູງ",
};
