import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> lt = {
  AppKeys.lblChooseLanguage: "Pasirinkite kalbą",
  "All": "Visi",
  "AI Story Generator": "AI istorijų generatorius",
  "Story Generator": "Istorijų generatorius",
  "Essay Writer": "Esė rašytojas",
  "Essay length": "Esė ilgis",
  "Script Generator": "Scenarijų generatorius",
  "Create original stories in seconds":
      "Sukurkite originalias istorijas per kelias sekundes",
  "Academic writing made simple": "Akademinis rašymas supaprastintas",
  "Generate powerful scripts for any medium":
      "Sukurkite galingus scenarijus bet kuriai terpei",
  "Start Writing": "Pradėti rašyti",
  "Create Now": "Sukurti dabar",
  "Start Generating": "Pradėti generuoti",
  "Your Stories": "Jūsų istorijos",
  "No stories yet": "Istorijų dar nėra",
  "Start creating your first story!": "Pradėkite kurti savo pirmąją istoriją!",
  "Your Story Space Awaits": "Jūsų istorijų erdvė laukia",
  "Start your first story and see it appear here":
      "Pradėkite savo pirmąją istoriją ir pamatykite ją čia",
  "Language": "Kalba",
  "Rate us": "Įvertinkite mus",
  "Share us": "Pasidalinkite mumis",
  "Privacy Policy": "Privatumo politika",
  "Settings": "Nustatymai",
  "Select Language": "Pasirinkite kalbą",
  "Dashboard": "Valdymo skydas",
  "BENEFITS": "NAUDA",
  "Subscribe": "Prenumeruoti",
  "Weekly": "Savaitinis",
  "Monthly": "Mėnesinis",
  "Yearly": "Metinis",
  "week": "savaitė",
  "months": "mėnesiai",
  "year": "metai",
  "Terms & Condition": "Sąlygos ir taisyklės",
  "No Commitment. Cancel anytime": "Jokių įsipareigojimų. Atšaukite bet kada",
  "No Payment Now": "Dabar mokėti nereikia",
  "3 days free": "3 dienos nemokamai",
  "Start your free trial": "Pradėkite nemokamą bandomąjį laikotarpį",
  "More detailed answers": "Išsamesni atsakymai",
  "Instant responds": "Momentiniai atsakymai",
  "Text recognition": "Teksto atpažinimas",
  "Powered by AI": "Veikia su AI",
  "Storytelleing": "Pasakojimas",
  ' Power': "Galia",
  "Unlock your \nFill ": "Atrakinkite savo \nužpildymą",
  "Your History": "Jūsų istorija",
  "Terms and Conditions": "Sąlygos ir taisyklės",
  "Short": "Trumpas",
  "Medium": "Vidutinis",
  "Long": "Ilgas",
  "Length": "Ilgis",
  "Describe your topic...": "Apibūdinkite savo temą...",
  "Set Creativity": "Nustatyti kūrybiškumą",
  "Standard": "Standartinis",
  "Creative": "Kūrybiškas",
  "Complex": "Sudėtingas",
  "Select Genre": "Pasirinkite žanrą",
  "Fantasy": "Fantazija",
  "Mystery": "Paslaptis",
  "Thriller": "Trileris",
  "Script Tone": "Scenarijaus tonas",
  "Script Type": "Scenarijaus tipas",
  "Comedy": "Komedija",
  "Drama": "Drama",
  "Horror": "Siaubas",
  "Action": "Veiksmas",
  "Romance": "Romantika",
  "Go Premium": "Tapti Premium",
  "Unlock Everything": "Atrakinti viską",
  "Unlimited Story Generation": "Neribota istorijų generacija",
  "Write Longer & Detailed Essays": "Rašykite ilgesnes ir detalesnes esė",
  "Advanced Script Writer": "Pažangus scenarijų rašytojas",
  "Unlock All Styles & Tones": "Atrakinti visus stilius ir tonus",
  "No Word/Length Limit": "Be žodžių/ilgio limito",
  "Remove All Ads": "Pašalinti visas reklamas",
  "Restore": "Atkurti",
  "YouTube Video": "YouTube vaizdo įrašas",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motyvacinis",
  "Advertisement": "Reklama",
  "Fairy Tale": "Pasaka",
  "Sci-Fi": "Mokslinė fantastika",
  "Select Style": "Pasirinkite stilių",
  "Imaginative": "Vaizdingas",
  "Innovative": "Inovatyvus",
  "AI Story Writer": "AI istorijų rašytojas",
  "Generate": "Generuoti",
  "Please wait...": "Prašome palaukti...",
  "Result": "Rezultatas",
  "Regenerate": "Regeneruoti",
  "Download": "Atsisiųsti",
  "Text copied to clipboard!": "Tekstas nukopijuotas į iškarpinę!",
  "Please enter a topic": "Įveskite temą",
  "Story Magic": "Istorijos magija",
  "Let AI bring your thoughts to a full story":
      "Leiskite AI paversti jūsų mintis pilna istorija",
  "Smart Scripts": "Išmanieji scenarijai",
  "From concept to script—fast, easy, and creative":
      "Nuo koncepcijos iki scenarijaus — greitai, lengvai ir kūrybiškai",
  "Perfect Essays": "Tobulos esė",
  "You have reached your free limit": "Pasiekėte savo nemokamą limitą",
  "Donwload": "Atsisiųsti",
  "Press again to exit app":
      "Paspauskite dar kartą, kad išeitumėte iš programos",
  "Saved to files": "TXT failas sėkmingai išsaugotas!",
  "Error: Please try again": "Klaida: bandykite dar kartą",
  "Subscription expired": "Prenumerata baigėsi",
  "Purchase cancelled": "Pirkimas atšauktas",
  "Purchase failed": "Pirkimas nepavyko",
  "Restore failed": "Atkūrimas nepavyko",
  "Purchase Successful!": "Pirkimas sėkmingas!",
  "Short (200-500 words)": "Trumpas (200-500 žodžių)",
  "Medium (500-1000 words)": "Vidutinis (500-1000 žodžių)",
  "Large (1000+ words)": "Didelis (1000+ žodžių)",
  "Academic Level": "Akademinis lygis",
  "Type of Paper": "Darbo tipas",
  "High School": "Vidurinė mokykla",
  "College": "Kolegija",
  "Short Film": "Trumpametražis filmas",
  "University": "Universitetas",
  "Masters": "Magistrantūra",
  "Custom": "Pasirinktinis",
  "Tiktok Video": "Tiktok vaizdo įrašas",
  "Movie": "Filmas",
  "Expository": "Aiškinamasis",
  "Argumentative": "Argumentuojantis",
  "Narrative": "Pasakojamasis",
  "Descriptive": "Aprašomasis",
  "We're sorry to hear that 😔": "Apgailestaujame tai išgirdę 😔",
  "We'll try to improve 🙁": "Stengsimės tobulėti 🙁",
  "Thanks for your feedback 🙂": "Dėkojame už atsiliepimą 🙂",
  "Great! We're glad you like it 😊": "Puiku! Džiaugiamės, kad patiko 😊",
  "Awesome! Thank you so much! 🎉": "Nuostabu! Labai ačiū! 🎉",
  "Maybe Later": "Galbūt vėliau",
  "Tap a star to rate your experience":
      "Bakstelėkite žvaigždutę, kad įvertintumėte savo patirtį",
  "Enjoying AI Math Solver?": "Patinka AI Math Solver?",
  "Thank you for rating us": "Dėkojame, kad mus įvertinote",
  "Submit Rating": "Pateikti įvertinimą",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Patinka AI Story Generator?",
  "Adventure": "Nuotykis",
  "Inspired": "Įkvėptas",
  "Film Script": "Filmo scenarijus",
  "Stage Play": "Scenos spektaklis",
  "Scene Breakdown": "Scenos analizė",
  "Dialogue Only": "Tik dialogas",
  "Ad loading please wait..": "Reklama kraunasi, palaukite...",
  "Words:": "Žodžiai:",
  "Reading:": "Skaitymas:",

  AppKeys.arabic: "Arabų",
  AppKeys.chinese: "Kinų",
  AppKeys.english: "Anglų",
  AppKeys.french: "Prancūzų",
  AppKeys.german: "Vokiečių",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indoneziečių",
  AppKeys.japanese: "Japonų",
  AppKeys.korean: "Korėjiečių",
  AppKeys.portuguese: "Portugalų",
  AppKeys.russian: "Rusų",
  AppKeys.spanish: "Ispanų",
  AppKeys.turkish: "Turkų",

  // New strings for download & actions
  'Download As': 'Atsisiųsti kaip',
  'Choose format to download': 'Pasirinkite formatą atsisiuntimui',
  'Text File': 'Teksto failas',
  'PDF File': 'PDF failas',
  'Copy': 'Kopijuoti',
  'Share': 'Dalintis',
  'Text copied!': 'Tekstas nukopijuotas!',
  'Copied to clipboard': 'Nukopijuota į iškarpinę',
  'File saved successfully': 'Failas sėkmingai išsaugotas',
  'Error saving file': 'Klaida išsaugant failą',
  'Share Story': 'Dalintis istorija',
  'Export': 'Eksportuoti',
};
