import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> lv = {
  AppKeys.lblChooseLanguage: "Izvēlieties valodu",
  "All": "Visi",
  "AI Story Generator": "AI stāstu ģenerators",
  "Story Generator": "Stāstu ģenerators",
  "Essay Writer": "Eseju rakstītājs",
  "Essay length": "Esejas garums",
  "Script Generator": "Scenāriju ģenerators",
  "Create original stories in seconds":
      "Izveidojiet oriģinālus stāstus dažās sekundēs",
  "Academic writing made simple": "Akadēmiskā rakstīšana vienkāršota",
  "Generate powerful scripts for any medium":
      "Ģenerējiet spēcīgus scenārijus jebkurai videi",
  "Start Writing": "Sākt rakstīt",
  "Create Now": "Izveidot tagad",
  "Start Generating": "Sākt ģenerēšanu",
  "Your Stories": "Jūsu stāsti",
  "No stories yet": "Stāstu vēl nav",
  "Start creating your first story!": "Sāciet veidot savu pirmo stāstu!",
  "Your Story Space Awaits": "Jūsu stāstu telpa gaida",
  "Start your first story and see it appear here":
      "Sāciet savu pirmo stāstu un redziet, kā tas parādās šeit",
  "Language": "Valoda",
  "Rate us": "Novērtējiet mūs",
  "Share us": "Dalieties ar mums",
  "Privacy Policy": "Privātuma politika",
  "Settings": "Iestatījumi",
  "Select Language": "Izvēlieties valodu",
  "Dashboard": "Vadības panelis",
  "BENEFITS": "PRIEKŠROCĪBAS",
  "Subscribe": "Abonēt",
  "Weekly": "Iknedēļas",
  "Monthly": "Ikmēneša",
  "Yearly": "Ikgadējs",
  "week": "nedēļa",
  "months": "mēneši",
  "year": "gads",
  "Terms & Condition": "Noteikumi un nosacījumi",
  "No Commitment. Cancel anytime": "Bez saistībām. Atceliet jebkurā laikā",
  "No Payment Now": "Tagad maksāt nav nepieciešams",
  "3 days free": "3 dienas bez maksas",
  "Start your free trial": "Sāciet bezmaksas izmēģinājumu",
  "More detailed answers": "Detalizētākas atbildes",
  "Instant responds": "Tūlītējas atbildes",
  "Text recognition": "Teksta atpazīšana",
  "Powered by AI": "Darbina AI",
  "Storytelleing": "Stāstīšana",
  ' Power': "Jauda",
  "Unlock your \nFill ": "Atbloķējiet savu \naizpildījumu",
  "Your History": "Jūsu vēsture",
  "Terms and Conditions": "Noteikumi un nosacījumi",
  "Short": "Īss",
  "Medium": "Vidējs",
  "Long": "Garš",
  "Length": "Garums",
  "Describe your topic...": "Aprakstiet savu tēmu...",
  "Set Creativity": "Iestatīt radošumu",
  "Standard": "Standarta",
  "Creative": "Radošs",
  "Complex": "Sarežģīts",
  "Select Genre": "Izvēlieties žanru",
  "Fantasy": "Fantāzija",
  "Mystery": "Noslēpums",
  "Thriller": "Trilleris",
  "Script Tone": "Scenārija tonis",
  "Script Type": "Scenārija veids",
  "Comedy": "Komēdija",
  "Drama": "Drāma",
  "Horror": "Šausmas",
  "Action": "Darbība",
  "Romance": "Romantika",
  "Go Premium": "Iegūt Premium",
  "Unlock Everything": "Atbloķēt visu",
  "Unlimited Story Generation": "Neierobežota stāstu ģenerēšana",
  "Write Longer & Detailed Essays": "Rakstiet garākas un detalizētākas esejas",
  "Advanced Script Writer": "Uzlabots scenāriju rakstītājs",
  "Unlock All Styles & Tones": "Atbloķēt visus stilus un toņus",
  "No Word/Length Limit": "Bez vārdu/garuma ierobežojumiem",
  "Remove All Ads": "Noņemt visas reklāmas",
  "Restore": "Atjaunot",
  "YouTube Video": "YouTube video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivējošs",
  "Advertisement": "Reklāma",
  "Fairy Tale": "Pasaka",
  "Sci-Fi": "Zinātniskā fantastika",
  "Select Style": "Izvēlieties stilu",
  "Imaginative": "Iztēles bagāts",
  "Innovative": "Inovatīvs",
  "AI Story Writer": "AI stāstu rakstītājs",
  "Generate": "Ģenerēt",
  "Please wait...": "Lūdzu, uzgaidiet...",
  "Result": "Rezultāts",
  "Regenerate": "Reģenerēt",
  "Download": "Lejupielādēt",
  "Text copied to clipboard!": "Teksts nokopēts starpliktuvē!",
  "Please enter a topic": "Ievadiet tēmu",
  "Story Magic": "Stāstu maģija",
  "Let AI bring your thoughts to a full story":
      "Ļaujiet AI pārvērst jūsu domas pilnā stāstā",
  "Smart Scripts": "Viedie scenāriji",
  "From concept to script—fast, easy, and creative":
      "No koncepcijas līdz scenārijam — ātri, viegli un radoši",
  "Perfect Essays": "Perfektas esejas",
  "You have reached your free limit": "Esat sasniedzis savu bezmaksas limitu",
  "Donwload": "Lejupielādēt",
  "Press again to exit app": "Nospiediet vēlreiz, lai izietu no lietotnes",
  "Saved to files": "TXT fails veiksmīgi saglabāts!",
  "Error: Please try again": "Kļūda: lūdzu, mēģiniet vēlreiz",
  "Subscription expired": "Abonements beidzies",
  "Purchase cancelled": "Pirkums atcelts",
  "Purchase failed": "Pirkums neizdevās",
  "Restore failed": "Atjaunošana neizdevās",
  "Purchase Successful!": "Pirkums veiksmīgs!",
  "Short (200-500 words)": "Īss (200-500 vārdi)",
  "Medium (500-1000 words)": "Vidējs (500-1000 vārdi)",
  "Large (1000+ words)": "Liels (1000+ vārdi)",
  "Academic Level": "Akadēmiskais līmenis",
  "Type of Paper": "Darba veids",
  "High School": "Vidusskola",
  "College": "Koledža",
  "Short Film": "Īsfilma",
  "University": "Universitāte",
  "Masters": "Maģistrantūra",
  "Custom": "Pielāgots",
  "Tiktok Video": "Tiktok video",
  "Movie": "Filma",
  "Expository": "Izskaidrojošs",
  "Argumentative": "Argumentējošs",
  "Narrative": "Stāstījuma",
  "Descriptive": "Aprakstošs",
  "We're sorry to hear that 😔": "Mums žēl to dzirdēt 😔",
  "We'll try to improve 🙁": "Mēs centīsimies uzlabot 🙁",
  "Thanks for your feedback 🙂": "Paldies par atsauksmēm 🙂",
  "Great! We're glad you like it 😊": "Lieliski! Priecājamies, ka patīk 😊",
  "Awesome! Thank you so much! 🎉": "Brīnišķīgi! Liels paldies! 🎉",
  "Maybe Later": "Varbūt vēlāk",
  "Tap a star to rate your experience":
      "Pieskarieties zvaigznei, lai novērtētu savu pieredzi",
  "Enjoying AI Math Solver?": "Patīk AI Math Solver?",
  "Thank you for rating us": "Paldies, ka novērtējāt mūs",
  "Submit Rating": "Iesniegt vērtējumu",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Patīk AI Story Generator?",
  "Adventure": "Piedzīvojums",
  "Inspired": "Iedvesmots",
  "Film Script": "Filmas scenārijs",
  "Stage Play": "Skatuves izrāde",
  "Scene Breakdown": "Ainas analīze",
  "Dialogue Only": "Tikai dialogs",
  "Ad loading please wait..": "Reklāma tiek ielādēta, lūdzu uzgaidiet...",
  "Words:": "Vārdi:",
  "Reading:": "Lasīšana:",

  AppKeys.arabic: "Arābu",
  AppKeys.chinese: "Ķīniešu",
  AppKeys.english: "Angļu",
  AppKeys.french: "Franču",
  AppKeys.german: "Vācu",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonēziešu",
  AppKeys.japanese: "Japāņu",
  AppKeys.korean: "Korejiešu",
  AppKeys.portuguese: "Portugāļu",
  AppKeys.russian: "Krievu",
  AppKeys.spanish: "Spāņu",
  AppKeys.turkish: "Turku",

  // New strings for download & actions
  'Download As': 'Lejupielādēt kā',
  'Choose format to download': 'Izvēlieties formātu lejupielādei',
  'Text File': 'Teksta fails',
  'PDF File': 'PDF fails',
  'Copy': 'Kopēt',
  'Share': 'Dalīties',
  'Text copied!': 'Teksts nokopēts!',
  'Copied to clipboard': 'Nokopēts starpliktuvē',
  'File saved successfully': 'Fails veiksmīgi saglabāts',
  'Error saving file': 'Kļūda saglabājot failu',
  'Share Story': 'Dalīties ar stāstu',
  'Export': 'Eksportēt',

  "Character Story": "Varoņa stāsts",
  "Create detailed character backstories":
      "Izveidojiet detalizētu varoņa priekšvēsturi",
  "Create Character": "Izveidot varoni",
  "Rewrite Story": "Pārrakstīt stāstu",
  "Paste Your Story": "Ielīmējiet savu stāstu",
  "Paste your story here to rewrite...":
      "Ielīmējiet savu stāstu šeit, lai pārrakstītu...",
  "Transform and improve your existing stories":
      "Pārveidojiet un uzlabojiet esošos stāstus",
  "Title Generator": "Nosaukumu ģenerators",
  "Generate catchy titles for your stories":
      "Ģenerējiet pievilcīgus nosaukumus saviem stāstiem",
  "Generate Titles": "Ģenerēt nosaukumus",
  "Blog Writer": "Bloga rakstītājs",
  "Blog Topic": "Bloga tēma",
  "Target Keywords": "Mērķa atslēgvārdi",
  "Target Audience (Optional)": "Mērķauditorija (neobligāti)",
  "Enter your blog topic or title...": "Ievadiet bloga tēmu vai nosaukumu...",
  "e.g., AI writing, content marketing, SEO tips":
      "piem., AI rakstīšana, satura mārketings, SEO padomi",
  "e.g., small business owners, bloggers":
      "piem., mazo uzņēmumu īpašnieki, blogeri",
  "Article Type": "Raksta veids",
  "Writing Tone": "Rakstīšanas tonis",
  "Article Length": "Raksta garums",
  "SEO Options": "SEO opcijas",
  "Include Meta Description": "Iekļaut meta aprakstu",
  "Include Keyword Suggestions": "Iekļaut atslēgvārdu ieteikumus",
  "Include FAQs Section": "Iekļaut BUJ sadaļu",
  "Please enter a blog topic": "Lūdzu, ievadiet bloga tēmu",
  "Generate Blog": "Ģenerēt blogu",
  "SEO optimized articles with keywords":
      "SEO optimizēti raksti ar atslēgvārdiem",
  "Write Blog": "Rakstīt blogu",
  "YouTube Script": "YouTube scenārijs",
  "Video Topic": "Video tēma",
  "Key Points (Optional)": "Galvenie punkti (neobligāti)",
  "What is your video about?": "Par ko ir jūsu video?",
  "List key points to cover (optional)...":
      "Uzskaitiet galvenos punktus (neobligāti)...",
  "Video Duration": "Video ilgums",
  "Script Options": "Scenārija opcijas",
  "Include Hook/Intro": "Iekļaut āķi/ievadu",
  "Include Call-to-Action": "Iekļaut aicinājumu rīkoties",
  "Include Timestamps": "Iekļaut laika zīmogus",
  "Please enter a video topic": "Lūdzu, ievadiet video tēmu",
  "Generate Script": "Ģenerēt scenāriju",
  "Create scripts for videos & reels": "Izveidojiet scenārijus video un rīliem",
  "Create Script": "Izveidot scenāriju",
  "Character Details": "Varoņa detaļas",
  "Character Name": "Varoņa vārds",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Vecums (piem., 25, Jauns pieaugušais, Sens)",
  "Personality (e.g., brave, shy, cunning)":
      "Personība (piem., drosmīgs, kautrīgs, viltīgs)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Loma (piem., Varonis, Ļaundaris, Mentors)",
  "Additional Details (optional)": "Papildu detaļas (neobligāti)",
  "Output Style": "Izvades stils",
  "Generate Character": "Ģenerēt varoni",
  "Please enter character name": "Lūdzu, ievadiet varoņa vārdu",
  "Please enter character role": "Lūdzu, ievadiet varoņa lomu",
  "Detailed": "Detalizēts",
  "Brief": "Īss",
  "Elaborate": "Izvērsts",
  "Select Tone": "Izvēlieties toni",
  "Rewrite Style": "Pārrakstīšanas stils",
  "Output Length": "Izvades garums",
  "Please paste your story": "Lūdzu, ielīmējiet savu stāstu",
  "Story is too short. Please provide more content.":
      "Stāsts ir pārāk īss. Lūdzu, sniedziet vairāk satura.",
  "Same": "Vienāds",
  "More Dramatic": "Dramatiskāks",
  "More Humorous": "Humorīgāks",
  "More Emotional": "Emocionālāks",
  "More Suspenseful": "Spriegāks",
  "Lighter": "Vieglāks",
  "Improved": "Uzlabots",
  "Simplified": "Vienkāršots",
  "More Descriptive": "Aprakstošāks",
  "More Dialogue": "Vairāk dialogu",
  "More Action": "Vairāk darbības",
  "Literary": "Literārs",
  "Shorter": "Īsāks",
  "Longer": "Garāks",
  "Much Longer": "Daudz garāks",
  "Rewrite Now": "Pārrakstīt tagad",
  "Story/Book Topic": "Stāsta/grāmatas tēma",
  "Keywords (Optional)": "Atslēgvārdi (neobligāti)",
  "Describe your story topic or theme...":
      "Aprakstiet stāsta tēmu vai motīvu...",
  "e.g., magic, dragon, adventure": "piem., maģija, pūķis, piedzīvojums",
  "Title For": "Nosaukums priekš",
  "Title Style": "Nosaukuma stils",
  "Number of Titles": "Nosaukumu skaits",
  "Book": "Grāmata",
  "Short Story": "Īsstāsts",
  "Novel": "Romans",
  "Chapter": "Nodaļa",
  "Series": "Sērija",
  "Simple": "Vienkāršs",
  "Mysterious": "Noslēpumains",
  "Dramatic": "Dramatisks",
  "Catchy": "Iedarbīgs",
  "Poetic": "Poētisks",
  "Kids": "Bērniem",
  "SEO Article": "SEO raksts",
  "How-To Guide": "Rokasgrāmata",
  "Listicle": "Saraksta raksts",
  "Product Review": "Produkta atsauksme",
  "Opinion Piece": "Viedokļa raksts",
  "News Article": "Ziņu raksts",
  "Professional": "Profesionāls",
  "Casual": "Neformāls",
  "Informative": "Informatīvs",
  "Persuasive": "Pārliecinošs",
  "Friendly": "Draudzīgs",
  "Authoritative": "Autoritatīvs",
  "Short (500-800)": "Īss (500-800)",
  "Medium (800-1500)": "Vidējs (800-1500)",
  "Long (1500-2500)": "Garš (1500-2500)",
  "Detailed (2500+)": "Detalizēts (2500+)",
  "Storytime": "Stāstu laiks",
  "Documentary": "Dokumentāls",
  "Short Reel": "Īss rīls",
  "Educational": "Izglītojošs",
  "Review": "Atsauksme",
  "Tutorial": "Pamācība",
  "< 1 min (Shorts)": "< 1 min (Īsie)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Aizraujošs",
  "Energetic": "Enerģisks",
  "Calm": "Mierīgs",
  "Funny": "Smieklīgs",
  "Next": "Tālāk",
  "Get Started": "Sākt",
  "Your tool for quick, high-quality essay writing":
      "Jūsu rīks ātriem un kvalitatīviem esejiem",
};
