import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> mk = {
  AppKeys.lblChooseLanguage: "Изберете јазик",
  "All": "Сите",
  "AI Story Generator": "AI генератор на приказни",
  "Story Generator": "Генератор на приказни",
  "Essay Writer": "Писател на есеи",
  "Essay length": "Должина на есеј",
  "Script Generator": "Генератор на сценарија",
  "Create original stories in seconds":
      "Создавајте оригинални приказни за секунди",
  "Academic writing made simple": "Академското пишување поедноставено",
  "Generate powerful scripts for any medium":
      "Генерирајте моќни сценарија за секој медиум",
  "Start Writing": "Започнете да пишувате",
  "Create Now": "Создајте сега",
  "Start Generating": "Започнете генерирање",
  "Your Stories": "Вашите приказни",
  "No stories yet": "Сè уште нема приказни",
  "Start creating your first story!":
      "Започнете да ја создавате вашата прва приказна!",
  "Your Story Space Awaits": "Вашиот простор за приказни ве чека",
  "Start your first story and see it appear here":
      "Започнете ја вашата прва приказна и видете ја тука",
  "Language": "Јазик",
  "Rate us": "Оценете нè",
  "Share us": "Споделете нè",
  "Privacy Policy": "Политика за приватност",
  "Settings": "Поставки",
  "Select Language": "Изберете јазик",
  "Dashboard": "Контролна табла",
  "BENEFITS": "ПРИДОБИВКИ",
  "Subscribe": "Претплатете се",
  "Weekly": "Неделно",
  "Monthly": "Месечно",
  "Yearly": "Годишно",
  "week": "недела",
  "months": "месеци",
  "year": "година",
  "Terms & Condition": "Услови и правила",
  "No Commitment. Cancel anytime": "Без обврски. Откажете во секое време",
  "No Payment Now": "Без плаќање сега",
  "3 days free": "3 дена бесплатно",
  "Start your free trial": "Започнете го вашиот бесплатен пробен период",
  "More detailed answers": "Подетални одговори",
  "Instant responds": "Моментални одговори",
  "Text recognition": "Препознавање текст",
  "Powered by AI": "Напојувано од AI",
  "Storytelleing": "Раскажување",
  ' Power': "Моќ",
  "Unlock your \nFill ": "Отклучете го вашиот \nполнење",
  "Your History": "Вашата историја",
  "Terms and Conditions": "Услови и правила",
  "Short": "Кратко",
  "Medium": "Средно",
  "Long": "Долго",
  "Length": "Должина",
  "Describe your topic...": "Опишете ја вашата тема...",
  "Set Creativity": "Поставете креативност",
  "Standard": "Стандардно",
  "Creative": "Креативно",
  "Complex": "Комплексно",
  "Select Genre": "Изберете жанр",
  "Fantasy": "Фантазија",
  "Mystery": "Мистерија",
  "Thriller": "Трилер",
  "Script Tone": "Тон на сценарио",
  "Script Type": "Тип на сценарио",
  "Comedy": "Комедија",
  "Drama": "Драма",
  "Horror": "Хорор",
  "Action": "Акција",
  "Romance": "Романтика",
  "Go Premium": "Земете Premium",
  "Unlock Everything": "Отклучете сè",
  "Unlimited Story Generation": "Неограничено генерирање приказни",
  "Write Longer & Detailed Essays": "Пишувајте подолги и детални есеи",
  "Advanced Script Writer": "Напреден писател на сценарија",
  "Unlock All Styles & Tones": "Отклучете ги сите стилови и тонови",
  "No Word/Length Limit": "Без ограничување на зборови/должина",
  "Remove All Ads": "Отстранете ги сите реклами",
  "Restore": "Обнови",
  "YouTube Video": "YouTube видео",
  "Podcast": "Подкаст",
  "Reel": "Рил",
  "Motivational": "Мотивациски",
  "Advertisement": "Реклама",
  "Fairy Tale": "Бајка",
  "Sci-Fi": "Научна фантастика",
  "Select Style": "Изберете стил",
  "Imaginative": "Имагинативен",
  "Innovative": "Иновативен",
  "AI Story Writer": "AI писател на приказни",
  "Generate": "Генерирај",
  "Please wait...": "Ве молиме почекајте...",
  "Result": "Резултат",
  "Regenerate": "Регенерирај",
  "Download": "Преземи",
  "Text copied to clipboard!": "Текстот е копиран во клипборд!",
  "Please enter a topic": "Внесете тема",
  "Story Magic": "Магија на приказни",
  "Let AI bring your thoughts to a full story":
      "Дозволете AI да ги претвори вашите мисли во целосна приказна",
  "Smart Scripts": "Паметни сценарија",
  "From concept to script—fast, easy, and creative":
      "Од концепт до сценарио — брзо, лесно и креативно",
  "Perfect Essays": "Совршени есеи",
  "You have reached your free limit": "Го достигнавте вашиот бесплатен лимит",
  "Donwload": "Преземи",
  "Press again to exit app":
      "Притиснете повторно за да излезете од апликацијата",
  "Saved to files": "TXT датотеката е успешно зачувана!",
  "Error: Please try again": "Грешка: обидете се повторно",
  "Subscription expired": "Претплатата истече",
  "Purchase cancelled": "Купувањето е откажано",
  "Purchase failed": "Купувањето не успеа",
  "Restore failed": "Обновувањето не успеа",
  "Purchase Successful!": "Купувањето е успешно!",
  "Short (200-500 words)": "Кратко (200-500 зборови)",
  "Medium (500-1000 words)": "Средно (500-1000 зборови)",
  "Large (1000+ words)": "Големо (1000+ зборови)",
  "Academic Level": "Академско ниво",
  "Type of Paper": "Тип на труд",
  "High School": "Средно училиште",
  "College": "Колеџ",
  "Short Film": "Краток филм",
  "University": "Универзитет",
  "Masters": "Магистратура",
  "Custom": "Прилагодено",
  "Tiktok Video": "Tiktok видео",
  "Movie": "Филм",
  "Expository": "Објаснувачки",
  "Argumentative": "Аргументативен",
  "Narrative": "Нарација",
  "Descriptive": "Описен",
  "We're sorry to hear that 😔": "Ни е жал да го слушнеме тоа 😔",
  "We'll try to improve 🙁": "Ќе се обидеме да се подобриме 🙁",
  "Thanks for your feedback 🙂": "Ви благодариме за повратните информации 🙂",
  "Great! We're glad you like it 😊": "Одлично! Ни е драго што ви се допаѓа 😊",
  "Awesome! Thank you so much! 🎉": "Неверојатно! Ви благодариме многу! 🎉",
  "Maybe Later": "Можеби подоцна",
  "Tap a star to rate your experience":
      "Допрете ѕвезда за да го оцените вашето искуство",
  "Enjoying AI Math Solver?": "Ви се допаѓа AI Math Solver?",
  "Thank you for rating us": "Ви благодариме што нè оценивте",
  "Submit Rating": "Поднесете оцена",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "Ви се допаѓа AI Story Generator?",
  "Adventure": "Авантура",
  "Inspired": "Инспириран",
  "Film Script": "Филмско сценарио",
  "Stage Play": "Сценска претстава",
  "Scene Breakdown": "Анализа на сцена",
  "Dialogue Only": "Само дијалог",
  "Ad loading please wait..": "Рекламата се вчитува, почекајте...",
  "Words:": "Зборови:",
  "Reading:": "Читање:",

  AppKeys.arabic: "Арапски",
  AppKeys.chinese: "Кинески",
  AppKeys.english: "Англиски",
  AppKeys.french: "Француски",
  AppKeys.german: "Германски",
  AppKeys.hindi: "Хинди",
  AppKeys.indonesian: "Индонезиски",
  AppKeys.japanese: "Јапонски",
  AppKeys.korean: "Корејски",
  AppKeys.portuguese: "Португалски",
  AppKeys.russian: "Руски",
  AppKeys.spanish: "Шпански",
  AppKeys.turkish: "Турски",

  // New strings for download & actions
  'Download As': 'Преземи како',
  'Choose format to download': 'Изберете формат за преземање',
  'Text File': 'Текстуална датотека',
  'PDF File': 'PDF датотека',
  'Copy': 'Копирај',
  'Share': 'Сподели',
  'Text copied!': 'Текстот е копиран!',
  'Copied to clipboard': 'Копирано во клипборд',
  'File saved successfully': 'Датотеката е успешно зачувана',
  'Error saving file': 'Грешка при зачувување на датотеката',
  'Share Story': 'Сподели приказна',
  'Export': 'Извези',

  "Character Story": "Приказна за ликот",
  "Create detailed character backstories": "Создајте детална историја за ликот",
  "Create Character": "Создај лик",
  "Rewrite Story": "Препиши приказна",
  "Paste Your Story": "Залепи ја приказната",
  "Paste your story here to rewrite...":
      "Залепете ја вашата приказна овде за препишување...",
  "Transform and improve your existing stories":
      "Трансформирајте и подобрете ги постојните приказни",
  "Title Generator": "Генератор на наслови",
  "Generate catchy titles for your stories":
      "Генерирајте привлечни наслови за вашите приказни",
  "Generate Titles": "Генерирај наслови",
  "Blog Writer": "Писател на блог",
  "Blog Topic": "Тема на блог",
  "Target Keywords": "Целни клучни зборови",
  "Target Audience (Optional)": "Целна публика (Опционално)",
  "Enter your blog topic or title...": "Внесете тема или наслов на блогот...",
  "e.g., AI writing, content marketing, SEO tips":
      "пр., AI пишување, маркетинг на содржини, совети за SEO",
  "e.g., small business owners, bloggers":
      "пр., сопственици на мали бизниси, блогери",
  "Article Type": "Тип на статија",
  "Writing Tone": "Тон на пишување",
  "Article Length": "Должина на статијата",
  "SEO Options": "SEO опции",
  "Include Meta Description": "Вклучи мета опис",
  "Include Keyword Suggestions": "Вклучи предлози за клучни зборови",
  "Include FAQs Section": "Вклучи секција за ЧПП",
  "Please enter a blog topic": "Внесете тема на блог",
  "Generate Blog": "Генерирај блог",
  "SEO optimized articles with keywords":
      "SEO оптимизирани статии со клучни зборови",
  "Write Blog": "Пишувај блог",
  "YouTube Script": "YouTube сценарио",
  "Video Topic": "Тема на видео",
  "Key Points (Optional)": "Клучни точки (Опционално)",
  "What is your video about?": "За што е вашето видео?",
  "List key points to cover (optional)...":
      "Наведете клучни точки (опционално)...",
  "Video Duration": "Траење на видеото",
  "Script Options": "Опции за сценарио",
  "Include Hook/Intro": "Вклучи вовед/интро",
  "Include Call-to-Action": "Вклучи повик за акција",
  "Include Timestamps": "Вклучи временски ознаки",
  "Please enter a video topic": "Внесете тема на видеото",
  "Generate Script": "Генерирај сценарио",
  "Create scripts for videos & reels": "Создадете сценарија за видеа и рилови",
  "Create Script": "Создај сценарио",
  "Character Details": "Детали за ликот",
  "Character Name": "Име на ликот",
  "Age (e.g., 25, Young Adult, Ancient)": "Возраст (пр., 25, Млад, Античкиот)",
  "Personality (e.g., brave, shy, cunning)":
      "Личност (пр., храбар, срамежлив, лукав)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Улога (пр., Херој, Злосторник, Ментор)",
  "Additional Details (optional)": "Дополнителни детали (опционално)",
  "Output Style": "Стил на излез",
  "Generate Character": "Генерирај лик",
  "Please enter character name": "Внесете го името на ликот",
  "Please enter character role": "Внесете ја улогата на ликот",
  "Detailed": "Детален",
  "Brief": "Краток",
  "Elaborate": "Разработен",
  "Select Tone": "Избери тон",
  "Rewrite Style": "Стил на препишување",
  "Output Length": "Должина на излезот",
  "Please paste your story": "Залепете ја вашата приказна",
  "Story is too short. Please provide more content.":
      "Приказната е премногу кратка. Дајте повеќе содржина.",
  "Same": "Исто",
  "More Dramatic": "Подраматично",
  "More Humorous": "Похумористично",
  "More Emotional": "Поемотивно",
  "More Suspenseful": "Понапнато",
  "Lighter": "Полесно",
  "Improved": "Подобрено",
  "Simplified": "Поедноставено",
  "More Descriptive": "Поописно",
  "More Dialogue": "Повеќе дијалог",
  "More Action": "Повеќе акција",
  "Literary": "Литературно",
  "Shorter": "Пократко",
  "Longer": "Подолго",
  "Much Longer": "Многу подолго",
  "Rewrite Now": "Препиши сега",
  "Story/Book Topic": "Тема на приказна/книга",
  "Keywords (Optional)": "Клучни зборови (Опционално)",
  "Describe your story topic or theme...":
      "Опишете ја темата или мотивот на приказната...",
  "e.g., magic, dragon, adventure": "пр., магија, змеј, авантура",
  "Title For": "Наслов за",
  "Title Style": "Стил на наслов",
  "Number of Titles": "Број на наслови",
  "Book": "Книга",
  "Short Story": "Кратка приказна",
  "Novel": "Роман",
  "Chapter": "Поглавје",
  "Series": "Серија",
  "Simple": "Едноставен",
  "Mysterious": "Мистериозен",
  "Dramatic": "Драматичен",
  "Catchy": "Привлечен",
  "Poetic": "Поетски",
  "Kids": "За деца",
  "SEO Article": "SEO статија",
  "How-To Guide": "Упатство",
  "Listicle": "Листа статија",
  "Product Review": "Рецензија на производ",
  "Opinion Piece": "Мислење",
  "News Article": "Новинска статија",
  "Professional": "Професионален",
  "Casual": "Неформален",
  "Informative": "Информативен",
  "Persuasive": "Убедлив",
  "Friendly": "Пријателски",
  "Authoritative": "Авторитативен",
  "Short (500-800)": "Краток (500-800)",
  "Medium (800-1500)": "Среден (800-1500)",
  "Long (1500-2500)": "Долг (1500-2500)",
  "Detailed (2500+)": "Детален (2500+)",
  "Storytime": "Расказување",
  "Documentary": "Документарен",
  "Short Reel": "Краток рил",
  "Educational": "Образовен",
  "Review": "Рецензија",
  "Tutorial": "Упатство",
  "< 1 min (Shorts)": "< 1 мин (Кратки)",
  "1-3 min": "1-3 мин",
  "5-10 min": "5-10 мин",
  "10-20 min": "10-20 мин",
  "20+ min": "20+ мин",
  "Engaging": "Интересно",
  "Energetic": "Енергично",
  "Calm": "Смирено",
  "Funny": "Смешно",
  "Next": "Следно",
  "Get Started": "Започни",
  "Your tool for quick, high-quality essay writing":
      "Вашата алатка за брзо и квалитетно пишување есеи",
};
