import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> mn = {
  AppKeys.lblChooseLanguage: "Хэл сонгох",
  "All": "Бүгд",
  "AI Story Generator": "AI түүх үүсгэгч",
  "Story Generator": "Түүх үүсгэгч",
  "Essay Writer": "Эссэ бичигч",
  "Essay length": "Эссэний урт",
  "Script Generator": "Скрипт үүсгэгч",
  "Create original stories in seconds":
      "Хэдхэн секундын дотор анхны түүхүүдийг үүсгэ",
  "Academic writing made simple": "Академик бичвэрийг хялбар болгосон",
  "Generate powerful scripts for any medium":
      "Ямар ч хэвлэл мэдээллийн хэрэгсэлд хүчирхэг скриптүүд үүсгэ",
  "Start Writing": "Бичиж эхлэх",
  "Create Now": "Одоо үүсгэх",
  "Start Generating": "Үүсгэж эхлэх",
  "Your Stories": "Таны түүхүүд",
  "No stories yet": "Түүх байхгүй байна",
  "Start creating your first story!": "Эхний түүхээ бичиж эхлээрэй!",
  "Your Story Space Awaits": "Таны түүхийн орон зай хүлээж байна",
  "Start your first story and see it appear here":
      "Эхний түүхээ эхлүүлээд энд харагдаж байгааг хараарай",
  "Language": "Хэл",
  "Rate us": "Биднийг үнэлээрэй",
  "Share us": "Хуваалцаарай",
  "Privacy Policy": "Нууцлалын бодлого",
  "Settings": "Тохиргоо",
  "Select Language": "Хэл сонгох",
  "Dashboard": "Хяналтын самбар",
  "BENEFITS": "ДАВУУ ТАЛУУД",
  "Subscribe": "Бүртгүүлэх",
  "Weekly": "Долоо хоног бүр",
  "Monthly": "Сар бүр",
  "Yearly": "Жил бүр",
  "week": "долоо хоног",
  "months": "сар",
  "year": "жил",
  "Terms & Condition": "Нөхцөл ба шаардлага",
  "No Commitment. Cancel anytime":
      "Үүрэг хариуцлага байхгүй. Хэзээ ч цуцлах боломжтой",
  "No Payment Now": "Одоо төлбөр байхгүй",
  "3 days free": "3 өдөр үнэгүй",
  "Start your free trial": "Үнэгүй туршилтаа эхлүүлээрэй",
  "More detailed answers": "Илүү дэлгэрэнгүй хариултууд",
  "Instant responds": "Шуурхай хариу",
  "Text recognition": "Текст таних",
  "Powered by AI": "AI-аар ажилладаг",
  "Storytelleing": "Түүх яриа",
  ' Power': "Хүч",
  "Unlock your \nFill ": "Бөглөхөө \nнээгээрэй",
  "Your History": "Таны түүх",
  "Terms and Conditions": "Нөхцөл ба шаардлага",
  "Short": "Богино",
  "Medium": "Дунд",
  "Long": "Урт",
  "Length": "Урт",
  "Describe your topic...": "Сэдвээ тайлбарлаарай...",
  "Set Creativity": "Бүтээлч байдлыг тохируулах",
  "Standard": "Стандарт",
  "Creative": "Бүтээлч",
  "Complex": "Нарийн төвөгтэй",
  "Select Genre": "Жанр сонгох",
  "Fantasy": "Уран зөгнөлт",
  "Mystery": "Нууцлаг",
  "Thriller": "Триллер",
  "Script Tone": "Скриптийн өнгө аяс",
  "Script Type": "Скриптийн төрөл",
  "Comedy": "Инээдмийн",
  "Drama": "Драм",
  "Horror": "Аймшгийн",
  "Action": "Экшн",
  "Romance": "Романтик",
  "Go Premium": "Premium авах",
  "Unlock Everything": "Бүгдийг нээх",
  "Unlimited Story Generation": "Хязгааргүй түүх үүсгэх",
  "Write Longer & Detailed Essays": "Урт бөгөөд дэлгэрэнгүй эссэ бичих",
  "Advanced Script Writer": "Дэвшилтэт скрипт бичигч",
  "Unlock All Styles & Tones": "Бүх загвар ба өнгө аясыг нээх",
  "No Word/Length Limit": "Үг/уртын хязгаарлалт байхгүй",
  "Remove All Ads": "Бүх зар хасах",
  "Restore": "Сэргээх",
  "YouTube Video": "YouTube видео",
  "Podcast": "Подкаст",
  "Reel": "Рийл",
  "Motivational": "Урам зоригийн",
  "Advertisement": "Сурталчилгаа",
  "Fairy Tale": "Үлгэр",
  "Sci-Fi": "Шинжлэх ухааны уран зөгнөл",
  "Select Style": "Загвар сонгох",
  "Imaginative": "Төсөөллийн",
  "Innovative": "Шинэлэг",
  "AI Story Writer": "AI түүх бичигч",
  "Generate": "Үүсгэх",
  "Please wait...": "Түр хүлээнэ үү...",
  "Result": "Үр дүн",
  "Regenerate": "Дахин үүсгэх",
  "Download": "Татах",
  "Text copied to clipboard!": "Текст хуулах санд хуулагдлаа!",
  "Please enter a topic": "Сэдэв оруулна уу",
  "Story Magic": "Түүхийн ид шид",
  "Let AI bring your thoughts to a full story":
      "AI-д таны бодлыг бүрэн түүх болгон хувиргахыг зөвшөөрнө үү",
  "Smart Scripts": "Ухаалаг скриптүүд",
  "From concept to script—fast, easy, and creative":
      "Үзэл баримтлалаас скрипт хүртэл—хурдан, хялбар, бүтээлч",
  "Perfect Essays": "Төгс эссэнүүд",
  "You have reached your free limit": "Та үнэгүй хязгаартаа хүрсэн байна",
  "Donwload": "Татах",
  "Press again to exit app": "Апп-аас гарахын тулд дахин дарна уу",
  "Saved to files": "TXT файл амжилттай хадгалагдлаа!",
  "Error: Please try again": "Алдаа: Дахин оролдоно уу",
  "Subscription expired": "Захиалга дууссан",
  "Purchase cancelled": "Худалдан авалт цуцлагдсан",
  "Purchase failed": "Худалдан авалт амжилтгүй болсон",
  "Restore failed": "Сэргээлт амжилтгүй болсон",
  "Purchase Successful!": "Худалдан авалт амжилттай!",
  "Short (200-500 words)": "Богино (200-500 үг)",
  "Medium (500-1000 words)": "Дунд (500-1000 үг)",
  "Large (1000+ words)": "Том (1000+ үг)",
  "Academic Level": "Академик түвшин",
  "Type of Paper": "Цаасны төрөл",
  "High School": "Ахлах сургууль",
  "College": "Коллеж",
  "Short Film": "Богино кино",
  "University": "Их сургууль",
  "Masters": "Магистрын",
  "Custom": "Өөрийн",
  "Tiktok Video": "Tiktok видео",
  "Movie": "Кино",
  "Expository": "Тайлбарлах",
  "Argumentative": "Маргаантай",
  "Narrative": "Өгүүлэх",
  "Descriptive": "Тодорхойлох",
  "We're sorry to hear that 😔": "Үүнийг сонсоход харамсалтай байна 😔",
  "We'll try to improve 🙁": "Бид сайжруулахыг хичээх болно 🙁",
  "Thanks for your feedback 🙂": "Санал хүсэлт илгээсэнд баярлалаа 🙂",
  "Great! We're glad you like it 😊":
      "Гайхалтай! Танд таалагдсанд баяртай байна 😊",
  "Awesome! Thank you so much! 🎉": "Гайхалтай! Маш их баярлалаа! 🎉",
  "Maybe Later": "Магадгүй дараа",
  "Tap a star to rate your experience":
      "Туршлагаа үнэлэхийн тулд одон дээр дарна уу",
  "Enjoying AI Math Solver?": "AI Math Solver таалагдаж байна уу?",
  "Thank you for rating us": "Биднийг үнэлсэнд баярлалаа",
  "Submit Rating": "Үнэлгээ илгээх",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "AI Story Generator таалагдаж байна уу?",
  "Adventure": "Адал явдал",
  "Inspired": "Урам авсан",
  "Film Script": "Киноны скрипт",
  "Stage Play": "Тайзны жүжиг",
  "Scene Breakdown": "Үзэгдлийн задаргаа",
  "Dialogue Only": "Зөвхөн харилцан яриа",
  "Ad loading please wait..": "Зар ачаалж байна, хүлээнэ үү...",
  "Words:": "Үг:",
  "Reading:": "Унших:",

  AppKeys.arabic: "Араб",
  AppKeys.chinese: "Хятад",
  AppKeys.english: "Англи",
  AppKeys.french: "Франц",
  AppKeys.german: "Герман",
  AppKeys.hindi: "Хинди",
  AppKeys.indonesian: "Индонез",
  AppKeys.japanese: "Япон",
  AppKeys.korean: "Солонгос",
  AppKeys.portuguese: "Португал",
  AppKeys.russian: "Орос",
  AppKeys.spanish: "Испани",
  AppKeys.turkish: "Турк",

  // New strings for download & actions
  'Download As': 'Татаж авах',
  'Choose format to download': 'Татах форматыг сонгоно уу',
  'Text File': 'Текст файл',
  'PDF File': 'PDF файл',
  'Copy': 'Хуулах',
  'Share': 'Хуваалцах',
  'Text copied!': 'Текст хуулагдлаа!',
  'Copied to clipboard': 'Хуулах санд хуулагдлаа',
  'File saved successfully': 'Файл амжилттай хадгалагдлаа',
  'Error saving file': 'Файл хадгалахад алдаа гарлаа',
  'Share Story': 'Түүх хуваалцах',
  'Export': 'Экспорт',
  "Character Story": "Дүрийн түүх",
  "Create detailed character backstories":
      "Дүрийн дэлгэрэнгүй урьдчилсан түүх үүсгэх",
  "Create Character": "Дүр үүсгэх",
  "Rewrite Story": "Түүхийг дахин бичих",
  "Paste Your Story": "Түүхээ буулгах",
  "Paste your story here to rewrite...":
      "Дахин бичихийн тулд түүхээ энд буулгана уу...",
  "Transform and improve your existing stories":
      "Одоо байгаа түүхүүдийг өөрчлөн сайжруулах",
  "Title Generator": "Гарчиг үүсгэгч",
  "Generate catchy titles for your stories":
      "Түүхүүддээ сонирхолтой гарчиг үүсгэх",
  "Generate Titles": "Гарчиг үүсгэх",
  "Blog Writer": "Блог бичигч",
  "Blog Topic": "Блогийн сэдэв",
  "Target Keywords": "Зорилтот түлхүүр үгс",
  "Target Audience (Optional)": "Зорилтот үзэгчид (Нэмэлт)",
  "Enter your blog topic or title...":
      "Блогийнхоо сэдэв эсвэл гарчгийг оруулна уу...",
  "e.g., AI writing, content marketing, SEO tips":
      "жш., AI бичих, контент маркетинг, SEO зөвлөмж",
  "e.g., small business owners, bloggers":
      "жш., жижиг бизнес эрхлэгчид, блогчид",
  "Article Type": "Нийтлэлийн төрөл",
  "Writing Tone": "Бичлэгийн өнгө аяс",
  "Article Length": "Нийтлэлийн урт",
  "SEO Options": "SEO сонголтууд",
  "Include Meta Description": "Мета тайлбар оруулах",
  "Include Keyword Suggestions": "Түлхүүр үгийн санал оруулах",
  "Include FAQs Section": "ТАА хэсэг оруулах",
  "Please enter a blog topic": "Блогийн сэдэв оруулна уу",
  "Generate Blog": "Блог үүсгэх",
  "SEO optimized articles with keywords":
      "Түлхүүр үгтэй SEO оновчлосон нийтлэлүүд",
  "Write Blog": "Блог бичих",
  "YouTube Script": "YouTube скрипт",
  "Video Topic": "Видеоны сэдэв",
  "Key Points (Optional)": "Гол цэгүүд (Нэмэлт)",
  "What is your video about?": "Таны видео юуны тухай вэ?",
  "List key points to cover (optional)...":
      "Хамрах гол цэгүүдийг жагсаана уу (нэмэлт)...",
  "Video Duration": "Видеоны үргэлжлэх хугацаа",
  "Script Options": "Скриптийн сонголтууд",
  "Include Hook/Intro": "Танилцуулга/удиртгал оруулах",
  "Include Call-to-Action": "Үйлдэлд уриалах дуудлага оруулах",
  "Include Timestamps": "Цагийн тэмдэглэгээ оруулах",
  "Please enter a video topic": "Видеоны сэдэв оруулна уу",
  "Generate Script": "Скрипт үүсгэх",
  "Create scripts for videos & reels":
      "Видео болон рилүүдэд зориулсан скрипт үүсгэх",
  "Create Script": "Скрипт үүсгэх",
  "Character Details": "Дүрийн дэлгэрэнгүй мэдээлэл",
  "Character Name": "Дүрийн нэр",
  "Age (e.g., 25, Young Adult, Ancient)": "Нас (жш., 25, Залуу, Эртний)",
  "Personality (e.g., brave, shy, cunning)":
      "Зан чанар (жш., зоригтой, ичимхий, хуурамч)",
  "Role (e.g., Hero, Villain, Mentor)": "Үүрэг (жш., Баатар, Муу хүн, Ментор)",
  "Additional Details (optional)": "Нэмэлт дэлгэрэнгүй мэдээлэл (нэмэлт)",
  "Output Style": "Гаралтын хэв маяг",
  "Generate Character": "Дүр үүсгэх",
  "Please enter character name": "Дүрийн нэрийг оруулна уу",
  "Please enter character role": "Дүрийн үүргийг оруулна уу",
  "Detailed": "Дэлгэрэнгүй",
  "Brief": "Товч",
  "Elaborate": "Нарийвчилсан",
  "Select Tone": "Өнгө аяс сонгох",
  "Rewrite Style": "Дахин бичих хэв маяг",
  "Output Length": "Гаралтын урт",
  "Please paste your story": "Түүхээ буулгана уу",
  "Story is too short. Please provide more content.":
      "Түүх хэтэрхий богино байна. Илүү их агуулга оруулна уу.",
  "Same": "Адилхан",
  "More Dramatic": "Илүү жүжгийн",
  "More Humorous": "Илүү хошин",
  "More Emotional": "Илүү сэтгэл хөдлөлтэй",
  "More Suspenseful": "Илүү хурцадмал",
  "Lighter": "Хөнгөн",
  "Improved": "Сайжруулсан",
  "Simplified": "Хялбаршуулсан",
  "More Descriptive": "Илүү тайлбарлагдсан",
  "More Dialogue": "Илүү их яриа",
  "More Action": "Илүү их үйлдэл",
  "Literary": "Уран зохиолын",
  "Shorter": "Богиносгосон",
  "Longer": "Уртасгасан",
  "Much Longer": "Илүү урт",
  "Rewrite Now": "Одоо дахин бичих",
  "Story/Book Topic": "Түүх/Номын сэдэв",
  "Keywords (Optional)": "Түлхүүр үгс (Нэмэлт)",
  "Describe your story topic or theme...":
      "Түүхийнхээ сэдэв эсвэл уриа тайлбарлана уу...",
  "e.g., magic, dragon, adventure": "жш., ид шид, луу, адал явдал",
  "Title For": "Гарчиг",
  "Title Style": "Гарчгийн хэв маяг",
  "Number of Titles": "Гарчгийн тоо",
  "Book": "Ном",
  "Short Story": "Богино өгүүллэг",
  "Novel": "Роман",
  "Chapter": "Бүлэг",
  "Series": "Цуврал",
  "Simple": "Энгийн",
  "Mysterious": "Нууцлаг",
  "Dramatic": "Жүжгийн",
  "Catchy": "Татах",
  "Poetic": "Шүлгийн",
  "Kids": "Хүүхдийн",
  "SEO Article": "SEO нийтлэл",
  "How-To Guide": "Гарын авлага",
  "Listicle": "Жагсаалт нийтлэл",
  "Product Review": "Бүтээгдэхүүний тойм",
  "Opinion Piece": "Санал бодол",
  "News Article": "Мэдээний нийтлэл",
  "Professional": "Мэргэжлийн",
  "Casual": "Энгийн",
  "Informative": "Мэдээлэл өгөх",
  "Persuasive": "Итгүүлэх",
  "Friendly": "Найрсаг",
  "Authoritative": "Эрх мэдэлтэй",
  "Short (500-800)": "Богино (500-800)",
  "Medium (800-1500)": "Дунд (800-1500)",
  "Long (1500-2500)": "Урт (1500-2500)",
  "Detailed (2500+)": "Дэлгэрэнгүй (2500+)",
  "Storytime": "Түүх цаг",
  "Documentary": "Баримтат",
  "Short Reel": "Богино рил",
  "Educational": "Боловсролын",
  "Review": "Тойм",
  "Tutorial": "Заавар",
  "< 1 min (Shorts)": "< 1 мин (Богино)",
  "1-3 min": "1-3 мин",
  "5-10 min": "5-10 мин",
  "10-20 min": "10-20 мин",
  "20+ min": "20+ мин",
  "Engaging": "Сонирхолтой",
  "Energetic": "Эрч хүчтэй",
  "Calm": "Тайван",
  "Funny": "Хошин",
  "Next": "Дараах",
  "Get Started": "Эхлэх",
  "Your tool for quick, high-quality essay writing":
      "Хурдан, өндөр чанартай эссе бичих хэрэгсэл",
};
