import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ms = {
  AppKeys.lblChooseLanguage: "Pilih Bahasa",
  "All": "Semua",
  "AI Story Generator": "Penjana Cerita AI",
  "Story Generator": "Penjana Cerita",
  "Essay Writer": "Penulis Esei",
  "Essay length": "Panjang esei",
  "Script Generator": "Penjana Skrip",
  "Create original stories in seconds": "Cipta cerita asal dalam beberapa saat",
  "Academic writing made simple": "Penulisan akademik dipermudahkan",
  "Generate powerful scripts for any medium":
      "Jana skrip berkuasa untuk sebarang medium",
  "Start Writing": "Mula Menulis",
  "Create Now": "Cipta Sekarang",
  "Start Generating": "Mula Menjana",
  "Your Stories": "Cerita Anda",
  "No stories yet": "Belum ada cerita",
  "Start creating your first story!": "Mula mencipta cerita pertama anda!",
  "Your Story Space Awaits": "Ruang Cerita Anda Menanti",
  "Start your first story and see it appear here":
      "Mulakan cerita pertama anda dan lihat ia muncul di sini",
  "Language": "Bahasa",
  "Rate us": "Nilai kami",
  "Share us": "Kongsi kami",
  "Privacy Policy": "Dasar Privasi",
  "Settings": "Tetapan",
  "Select Language": "Pilih Bahasa",
  "Dashboard": "Papan Pemuka",
  "BENEFITS": "MANFAAT",
  "Subscribe": "Langgan",
  "Weekly": "Mingguan",
  "Monthly": "Bulanan",
  "Yearly": "Tahunan",
  "week": "minggu",
  "months": "bulan",
  "year": "tahun",
  "Terms & Condition": "Terma & Syarat",
  "No Commitment. Cancel anytime": "Tiada Komitmen. Batal bila-bila masa",
  "No Payment Now": "Tiada Pembayaran Sekarang",
  "3 days free": "3 hari percuma",
  "Start your free trial": "Mulakan percubaan percuma anda",
  "More detailed answers": "Jawapan lebih terperinci",
  "Instant responds": "Respons segera",
  "Text recognition": "Pengecaman teks",
  "Powered by AI": "Dikuasai oleh AI",
  "Storytelleing": "Penceritaan",
  ' Power': "Kuasa",
  "Unlock your \nFill ": "Buka kunci \nIsi anda",
  "Your History": "Sejarah Anda",
  "Terms and Conditions": "Terma dan Syarat",
  "Short": "Pendek",
  "Medium": "Sederhana",
  "Long": "Panjang",
  "Length": "Panjang",
  "Describe your topic...": "Terangkan topik anda...",
  "Set Creativity": "Tetapkan Kreativiti",
  "Standard": "Standard",
  "Creative": "Kreatif",
  "Complex": "Kompleks",
  "Select Genre": "Pilih Genre",
  "Fantasy": "Fantasi",
  "Mystery": "Misteri",
  "Thriller": "Thriller",
  "Script Tone": "Nada Skrip",
  "Script Type": "Jenis Skrip",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Seram",
  "Action": "Aksi",
  "Romance": "Romantis",
  "Go Premium": "Dapatkan Premium",
  "Unlock Everything": "Buka Kunci Semua",
  "Unlimited Story Generation": "Penjanaan Cerita Tanpa Had",
  "Write Longer & Detailed Essays": "Tulis Esei Lebih Panjang & Terperinci",
  "Advanced Script Writer": "Penulis Skrip Lanjutan",
  "Unlock All Styles & Tones": "Buka Kunci Semua Gaya & Nada",
  "No Word/Length Limit": "Tiada Had Perkataan/Panjang",
  "Remove All Ads": "Buang Semua Iklan",
  "Restore": "Pulihkan",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivasi",
  "Advertisement": "Iklan",
  "Fairy Tale": "Kisah Dongeng",
  "Sci-Fi": "Sains Fiksyen",
  "Select Style": "Pilih Gaya",
  "Imaginative": "Imaginatif",
  "Innovative": "Inovatif",
  "AI Story Writer": "Penulis Cerita AI",
  "Generate": "Jana",
  "Please wait...": "Sila tunggu...",
  "Result": "Keputusan",
  "Regenerate": "Jana Semula",
  "Download": "Muat Turun",
  "Text copied to clipboard!": "Teks disalin ke papan keratan!",
  "Please enter a topic": "Sila masukkan topik",
  "Story Magic": "Keajaiban Cerita",
  "Let AI bring your thoughts to a full story":
      "Biarkan AI membawa fikiran anda menjadi cerita penuh",
  "Smart Scripts": "Skrip Pintar",
  "From concept to script—fast, easy, and creative":
      "Dari konsep ke skrip—cepat, mudah, dan kreatif",
  "Perfect Essays": "Esei Sempurna",
  "You have reached your free limit": "Anda telah mencapai had percuma anda",
  "Donwload": "Muat Turun",
  "Press again to exit app": "Tekan sekali lagi untuk keluar dari aplikasi",
  "Saved to files": "Fail TXT berjaya disimpan!",
  "Error: Please try again": "Ralat: Sila cuba lagi",
  "Subscription expired": "Langganan tamat tempoh",
  "Purchase cancelled": "Pembelian dibatalkan",
  "Purchase failed": "Pembelian gagal",
  "Restore failed": "Pemulihan gagal",
  "Purchase Successful!": "Pembelian Berjaya!",
  "Short (200-500 words)": "Pendek (200-500 perkataan)",
  "Medium (500-1000 words)": "Sederhana (500-1000 perkataan)",
  "Large (1000+ words)": "Besar (1000+ perkataan)",
  "Academic Level": "Tahap Akademik",
  "Type of Paper": "Jenis Kertas",
  "High School": "Sekolah Menengah",
  "College": "Kolej",
  "Short Film": "Filem Pendek",
  "University": "Universiti",
  "Masters": "Sarjana",
  "Custom": "Tersuai",
  "Tiktok Video": "Video Tiktok",
  "Movie": "Filem",
  "Expository": "Ekspositori",
  "Argumentative": "Argumentatif",
  "Narrative": "Naratif",
  "Descriptive": "Deskriptif",
  "We're sorry to hear that 😔": "Kami kesal mendengarnya 😔",
  "We'll try to improve 🙁": "Kami akan cuba memperbaiki 🙁",
  "Thanks for your feedback 🙂": "Terima kasih atas maklum balas anda 🙂",
  "Great! We're glad you like it 😊": "Hebat! Kami gembira anda menyukainya 😊",
  "Awesome! Thank you so much! 🎉": "Hebat! Terima kasih banyak! 🎉",
  "Maybe Later": "Mungkin Nanti",
  "Tap a star to rate your experience":
      "Ketik bintang untuk menilai pengalaman anda",
  "Enjoying AI Math Solver?": "Menikmati AI Math Solver?",
  "Thank you for rating us": "Terima kasih kerana menilai kami",
  "Submit Rating": "Hantar Penilaian",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Menikmati AI Story Generator?",
  "Adventure": "Pengembaraan",
  "Inspired": "Terinspirasi",
  "Film Script": "Skrip Filem",
  "Stage Play": "Drama Pentas",
  "Scene Breakdown": "Pecahan Adegan",
  "Dialogue Only": "Dialog Sahaja",
  "Ad loading please wait..": "Iklan sedang dimuatkan, sila tunggu...",
  "Words:": "Perkataan:",
  "Reading:": "Bacaan:",

  AppKeys.arabic: "Arab",
  AppKeys.chinese: "Cina",
  AppKeys.english: "Inggeris",
  AppKeys.french: "Perancis",
  AppKeys.german: "Jerman",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesia",
  AppKeys.japanese: "Jepun",
  AppKeys.korean: "Korea",
  AppKeys.portuguese: "Portugis",
  AppKeys.russian: "Rusia",
  AppKeys.spanish: "Sepanyol",
  AppKeys.turkish: "Turki",

  // New strings for download & actions
  'Download As': 'Muat Turun Sebagai',
  'Choose format to download': 'Pilih format untuk muat turun',
  'Text File': 'Fail Teks',
  'PDF File': 'Fail PDF',
  'Copy': 'Salin',
  'Share': 'Kongsi',
  'Text copied!': 'Teks disalin!',
  'Copied to clipboard': 'Disalin ke papan keratan',
  'File saved successfully': 'Fail berjaya disimpan',
  'Error saving file': 'Ralat menyimpan fail',
  'Share Story': 'Kongsi Cerita',
  'Export': 'Eksport',

  "Character Story": "Kisah Watak",
  "Create detailed character backstories":
      "Cipta latar belakang watak yang terperinci",
  "Create Character": "Cipta Watak",
  "Rewrite Story": "Tulis Semula Cerita",
  "Paste Your Story": "Tampal Cerita Anda",
  "Paste your story here to rewrite...":
      "Tampal cerita anda di sini untuk ditulis semula...",
  "Transform and improve your existing stories":
      "Ubah dan perbaiki cerita anda yang sedia ada",
  "Title Generator": "Penjana Tajuk",
  "Generate catchy titles for your stories":
      "Jana tajuk menarik untuk cerita anda",
  "Generate Titles": "Jana Tajuk",
  "Blog Writer": "Penulis Blog",
  "Blog Topic": "Topik Blog",
  "Target Keywords": "Kata Kunci Sasaran",
  "Target Audience (Optional)": "Audiens Sasaran (Pilihan)",
  "Enter your blog topic or title...": "Masukkan topik atau tajuk blog anda...",
  "e.g., AI writing, content marketing, SEO tips":
      "cth., penulisan AI, pemasaran kandungan, tips SEO",
  "e.g., small business owners, bloggers":
      "cth., pemilik perniagaan kecil, blogger",
  "Article Type": "Jenis Artikel",
  "Writing Tone": "Nada Penulisan",
  "Article Length": "Panjang Artikel",
  "SEO Options": "Pilihan SEO",
  "Include Meta Description": "Sertakan Deskripsi Meta",
  "Include Keyword Suggestions": "Sertakan Cadangan Kata Kunci",
  "Include FAQs Section": "Sertakan Bahagian Soalan Lazim",
  "Please enter a blog topic": "Sila masukkan topik blog",
  "Generate Blog": "Jana Blog",
  "SEO optimized articles with keywords":
      "Artikel yang dioptimumkan SEO dengan kata kunci",
  "Write Blog": "Tulis Blog",
  "YouTube Script": "Skrip YouTube",
  "Video Topic": "Topik Video",
  "Key Points (Optional)": "Poin Utama (Pilihan)",
  "What is your video about?": "Apakah video anda tentang?",
  "List key points to cover (optional)...":
      "Senaraikan poin utama (pilihan)...",
  "Video Duration": "Tempoh Video",
  "Script Options": "Pilihan Skrip",
  "Include Hook/Intro": "Sertakan Pemikat/Intro",
  "Include Call-to-Action": "Sertakan Ajakan Bertindak",
  "Include Timestamps": "Sertakan Cap Masa",
  "Please enter a video topic": "Sila masukkan topik video",
  "Generate Script": "Jana Skrip",
  "Create scripts for videos & reels": "Cipta skrip untuk video dan reel",
  "Create Script": "Cipta Skrip",
  "Character Details": "Butiran Watak",
  "Character Name": "Nama Watak",
  "Age (e.g., 25, Young Adult, Ancient)": "Umur (cth., 25, Dewasa Muda, Purba)",
  "Personality (e.g., brave, shy, cunning)":
      "Personaliti (cth., berani, pemalu, licik)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Peranan (cth., Wira, Penjahat, Mentor)",
  "Additional Details (optional)": "Butiran Tambahan (pilihan)",
  "Output Style": "Gaya Output",
  "Generate Character": "Jana Watak",
  "Please enter character name": "Sila masukkan nama watak",
  "Please enter character role": "Sila masukkan peranan watak",
  "Detailed": "Terperinci",
  "Brief": "Ringkas",
  "Elaborate": "Huraian",
  "Select Tone": "Pilih Nada",
  "Rewrite Style": "Gaya Tulis Semula",
  "Output Length": "Panjang Output",
  "Please paste your story": "Sila tampal cerita anda",
  "Story is too short. Please provide more content.":
      "Cerita terlalu pendek. Sila berikan lebih banyak kandungan.",
  "Same": "Sama",
  "More Dramatic": "Lebih Dramatik",
  "More Humorous": "Lebih Humor",
  "More Emotional": "Lebih Emosional",
  "More Suspenseful": "Lebih Menegangkan",
  "Lighter": "Lebih Ringan",
  "Improved": "Dipertingkatkan",
  "Simplified": "Dipermudahkan",
  "More Descriptive": "Lebih Deskriptif",
  "More Dialogue": "Lebih Dialog",
  "More Action": "Lebih Aksi",
  "Literary": "Sastera",
  "Shorter": "Lebih Pendek",
  "Longer": "Lebih Panjang",
  "Much Longer": "Jauh Lebih Panjang",
  "Rewrite Now": "Tulis Semula Sekarang",
  "Story/Book Topic": "Topik Cerita/Buku",
  "Keywords (Optional)": "Kata Kunci (Pilihan)",
  "Describe your story topic or theme...":
      "Huraikan topik atau tema cerita anda...",
  "e.g., magic, dragon, adventure": "cth., sihir, naga, pengembaraan",
  "Title For": "Tajuk Untuk",
  "Title Style": "Gaya Tajuk",
  "Number of Titles": "Bilangan Tajuk",
  "Book": "Buku",
  "Short Story": "Cerpen",
  "Novel": "Novel",
  "Chapter": "Bab",
  "Series": "Siri",
  "Simple": "Mudah",
  "Mysterious": "Misteri",
  "Dramatic": "Dramatik",
  "Catchy": "Menarik",
  "Poetic": "Puitis",
  "Kids": "Kanak-kanak",
  "SEO Article": "Artikel SEO",
  "How-To Guide": "Panduan Cara",
  "Listicle": "Artikel Senarai",
  "Product Review": "Ulasan Produk",
  "Opinion Piece": "Rencana Pendapat",
  "News Article": "Artikel Berita",
  "Professional": "Profesional",
  "Casual": "Santai",
  "Informative": "Informatif",
  "Persuasive": "Persuasif",
  "Friendly": "Mesra",
  "Authoritative": "Berwibawa",
  "Short (500-800)": "Pendek (500-800)",
  "Medium (800-1500)": "Sederhana (800-1500)",
  "Long (1500-2500)": "Panjang (1500-2500)",
  "Detailed (2500+)": "Terperinci (2500+)",
  "Storytime": "Masa Bercerita",
  "Documentary": "Dokumentari",
  "Short Reel": "Reel Pendek",
  "Educational": "Pendidikan",
  "Review": "Ulasan",
  "Tutorial": "Tutorial",
  "< 1 min (Shorts)": "< 1 min (Pendek)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Menarik",
  "Energetic": "Bertenaga",
  "Calm": "Tenang",
  "Funny": "Lucu",
  "Next": "Seterusnya",
  "Get Started": "Mulakan",
  "Your tool for quick, high-quality essay writing":
      "Alat anda untuk penulisan esei yang cepat dan berkualiti tinggi",
};
