import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> my = {
  AppKeys.lblChooseLanguage: "ဘာသာစကားရွေးချယ်ပါ",

  AppKeys.arabic: "အာရဗီ",
  AppKeys.chinese: "တရုတ်",
  AppKeys.english: "အင်္ဂလိပ်",
  AppKeys.french: "ပြင်သစ်",
  AppKeys.german: "ဂျာမန်",
  AppKeys.hindi: "ဟိန္ဒီ",
  AppKeys.indonesian: "အင်ဒိုနီးရှား",
  AppKeys.japanese: "ဂျပန်",
  AppKeys.korean: "ကိုရီးယား",
  AppKeys.portuguese: "ပေါ်တူဂီ",
  AppKeys.russian: "ရုရှား",
  AppKeys.spanish: "စပိန်",
  AppKeys.turkish: "တူရကီ",
  AppKeys.btnNext: "ရှေ့သို့",
  AppKeys.dahsboard: "ဒက်ရှ်ဘုတ်",
  AppKeys.yourStories: "သင့်ဇာတ်လမ်းများ",
  AppKeys.setting: "ဆက်တင်များ",
  AppKeys.btngetStarted: "စတင်ပါ",
  '': "စတင်ပါ",

  // New strings for download & actions
  'Download As': 'အဖြစ် ဒေါင်းလုတ်',
  'Choose format to download': 'ဒေါင်းလုတ်ရန် ဖော်မက်ရွေးပါ',
  'Text File': 'စာသားဖိုင်',
  'PDF File': 'PDF ဖိုင်',
  'Copy': 'ကူးယူ',
  'Share': 'မျှဝေ',
  'Download': 'ဒေါင်းလုတ်',
  'Text copied!': 'စာသားကူးယူပြီး!',
  'PDF saved successfully!': 'PDF အောင်မြင်စွာ သိမ်းပြီး!',
  'Saved to files': 'ဖိုင်များသို့ သိမ်းပြီး',
  'Error: Please try again': 'အမှား: ကျေးဇူးပြု၍ ထပ်ကြိုးစားပါ',
  'Error creating PDF: Please try again':
      'PDF ဖန်တီးရာတွင် အမှား: ကျေးဇူးပြု၍ ထပ်ကြိုးစားပါ',

  // Character Story Tool
  'Character Story': 'ဇာတ်ကောင်ဇာတ်လမ်း',
  'Character Details': 'ဇာတ်ကောင်အသေးစိတ်',
  'Character Name': 'ဇာတ်ကောင်အမည်',
  'Age (e.g., 25, Young Adult, Ancient)': 'အသက် (ဥပမာ ၂၅၊ လူငယ်၊ ရှေးဟောင်း)',
  'Personality (e.g., brave, shy, cunning)':
      'စရိုက် (ဥပမာ ရဲရင့်၊ ရှက်ကြောက်၊ လိမ္မာ)',
  'Role (e.g., Hero, Villain, Mentor)':
      'အခန်းကဏ္ဍ (ဥပမာ သူရဲကောင်း၊ လူဆိုး၊ ဆရာ)',
  'Additional Details (optional)': 'အပို အသေးစိတ် (ရွေးချယ်ခွင့်)',
  'Select Genre': 'အမျိုးအစားရွေး',
  'Output Style': 'ထုတ်ပေးမှုပုံစံ',
  'Generate Character': 'ဇာတ်ကောင်ဖန်တီး',
  'Please enter character name': 'ကျေးဇူးပြု၍ ဇာတ်ကောင်အမည်ထည့်ပါ',
  'Please enter character role': 'ကျေးဇူးပြု၍ ဇာတ်ကောင်အခန်းထည့်ပါ',
  // Genres
  'Fantasy': 'စိတ်ကူးယဉ်',
  'Sci-Fi': 'သိပ္ပံစိတ်ကူး',
  'Romance': 'အချစ်',
  'Horror': 'ထိတ်လန့်',
  'Comedy': 'ဟာသ',
  'Drama': 'ဒရာမာ',
  'Adventure': 'စွန့်စားခန်း',
  // Output Styles
  'Detailed': 'အသေးစိတ်',
  'Brief': 'အကျဉ်း',
  'Elaborate': 'ကျယ်ပြန့်',

  // Home Screen Tool Cards
  'Create detailed character backstories':
      'အသေးစိတ် ဇာတ်ကောင်နောက်ခံဇာတ်လမ်းများ ဖန်တီးပါ',
  'Create Character': 'ဇာတ်ကောင်ဖန်တီး',
  'Transform and improve your existing stories':
      'သင့်ဇာတ်လမ်းများကို ပြောင်းလဲတိုးတက်အောင်လုပ်ပါ',
  'Rewrite Now': 'ယခု ပြန်ရေး',
  'Generate catchy titles for your stories':
      'ဆွဲဆောင်မှုရှိသော ခေါင်းစဉ်များ ဖန်တီးပါ',
  'Generate Titles': 'ခေါင်းစဉ်များဖန်တီး',

  // Rewrite Story Tool
  'Rewrite Story': 'ဇာတ်လမ်းပြန်ရေး',
  'Paste Your Story': 'သင့်ဇာတ်လမ်းကူးထည့်ပါ',
  'Paste your story here to rewrite...':
      'ပြန်ရေးရန် ဇာတ်လမ်းကိုဤနေရာကူးထည့်ပါ...',
  'Select Tone': 'လေသံရွေး',
  'Rewrite Style': 'ပြန်ရေးပုံစံ',
  'Output Length': 'ထုတ်ပေးမှုအရှည်',
  'Please paste your story': 'ကျေးဇူးပြု၍ သင့်ဇာတ်လမ်းကူးထည့်ပါ',
  'Story is too short. Please provide more content.':
      'ဇာတ်လမ်းတိုလွန်းသည်။ ကျေးဇူးပြု၍ အကြောင်းအရာပိုထည့်ပါ။',
  // Tone options
  'Same': 'အတူတူ',
  'More Dramatic': 'ပိုဒရာမာ',
  'More Humorous': 'ပိုရယ်စရာ',
  'More Emotional': 'ပိုခံစားချက်',
  'More Suspenseful': 'ပိုစိတ်လှုပ်ရှား',
  'Lighter': 'ပိုပေါ့',
  // Style options
  'Improved': 'တိုးတက်',
  'Simplified': 'ရိုးရှင်း',
  'More Descriptive': 'ပိုဖော်ပြ',
  'More Dialogue': 'စကားပြောပို',
  'More Action': 'လှုပ်ရှားမှုပို',
  'Literary': 'စာပေ',
  // Length options
  'Shorter': 'ပိုတို',
  'Longer': 'ပိုရှည်',
  'Much Longer': 'အများကြီးရှည်',

  // Title Generator Tool
  'Title Generator': 'ခေါင်းစဉ်ဖန်တီးစက်',
  'Story/Book Topic': 'ဇာတ်လမ်း/စာအုပ်အကြောင်းအရာ',
  'Keywords (Optional)': 'သော့ချက်စာလုံးများ (ရွေးချယ်ခွင့်)',
  'Describe your story topic or theme...': 'သင့်ဇာတ်လမ်းအကြောင်းအရာဖော်ပြပါ...',
  'e.g., magic, dragon, adventure': 'ဥပမာ မှော်၊ နဂါး၊ စွန့်စားခန်း',
  'Title For': 'ခေါင်းစဉ်အတွက်',
  'Title Style': 'ခေါင်းစဉ်ပုံစံ',
  'Number of Titles': 'ခေါင်းစဉ်အရေအတွက်',
  'Please enter a topic': 'ကျေးဇူးပြု၍ အကြောင်းအရာထည့်ပါ',
  // Type options
  'Book': 'စာအုပ်',
  'Short Story': 'ဝတ္ထုတို',
  'Novel': 'ဝတ္ထုရှည်',
  'Chapter': 'အခန်း',
  'Series': 'စီးရီး',
  // Style options
  'Creative': 'ဖန်တီးမှု',
  'Simple': 'ရိုးရှင်း',
  'Mysterious': 'လျှို့ဝှက်',
  'Dramatic': 'ဒရာမာ',
  'Catchy': 'ဆွဲဆောင်မှု',
  'Poetic': 'ကဗျာဆန်',
  // Genre options
  'Mystery': 'လျှို့ဝှက်',
  'Thriller': 'ထိတ်လန့်',
  'Kids': 'ကလေး',

  // Blog Writer Tool
  'Blog Writer': 'ဘလော့ရေးသူ',
  'Blog Topic': 'ဘလော့အကြောင်းအရာ',
  'Target Keywords': 'ပစ်မှတ်သော့ချက်စာလုံးများ',
  'Target Audience (Optional)': 'ပစ်မှတ်ပရိသတ် (ရွေးချယ်ခွင့်)',
  'Enter your blog topic or title...': 'သင့်ဘလော့အကြောင်းအရာထည့်ပါ...',
  'e.g., AI writing, content marketing, SEO tips':
      'ဥပမာ AI ရေးသားမှု၊ ကွန်တန့်မားကတ်တင်း၊ SEO အကြံပြု',
  'e.g., small business owners, bloggers':
      'ဥပမာ စီးပွားရေးငယ်ပိုင်ရှင်များ၊ ဘလော့ဂါများ',
  'Article Type': 'ဆောင်းပါးအမျိုးအစား',
  'Writing Tone': 'ရေးသားမှုလေသံ',
  'Article Length': 'ဆောင်းပါးအရှည်',
  'SEO Options': 'SEO ရွေးချယ်မှုများ',
  'Include Meta Description': 'Meta ဖော်ပြချက်ထည့်',
  'Include Keyword Suggestions': 'သော့ချက်စာလုံးအကြံပြုချက်ထည့်',
  'Include FAQs Section': 'FAQ အပိုင်းထည့်',
  'Please enter a blog topic': 'ကျေးဇူးပြု၍ ဘလော့အကြောင်းအရာထည့်ပါ',
  'Generate Blog': 'ဘလော့ဖန်တီး',
  'SEO optimized articles with keywords':
      'သော့ချက်စာလုံးများဖြင့် SEO အကောင်းဆုံးဆောင်းပါးများ',
  'Write Blog': 'ဘလော့ရေး',
  // Article Types
  'SEO Article': 'SEO ဆောင်းပါး',
  'How-To Guide': 'လမ်းညွှန်',
  'Listicle': 'စာရင်းဆောင်းပါး',
  'Product Review': 'ထုတ်ကုန်သုံးသပ်ချက်',
  'Opinion Piece': 'အမြင်ဆောင်းပါး',
  'News Article': 'သတင်းဆောင်းပါး',
  // Blog Tones
  'Professional': 'ပရော်ဖက်ရှင်နယ်',
  'Casual': 'သာမန်',
  'Informative': 'သတင်းအချက်အလက်',
  'Persuasive': 'ဆွဲဆောင်မှု',
  'Friendly': 'ရင်းနှီး',
  'Authoritative': 'အာဏာပိုင်',
  // Blog Lengths
  'Short (500-800)': 'တို (၅၀၀-၈၀၀)',
  'Medium (800-1500)': 'အလယ်အလတ် (၈၀၀-၁၅၀၀)',
  'Long (1500-2500)': 'ရှည် (၁၅၀၀-၂၅၀၀)',
  'Detailed (2500+)': 'အသေးစိတ် (၂၅၀၀+)',

  // YouTube Script Tool
  'YouTube Script': 'YouTube ဇာတ်ညွှန်း',
  'Script Type': 'ဇာတ်ညွှန်းအမျိုးအစား',
  'Video Topic': 'ဗီဒီယိုအကြောင်းအရာ',
  'Key Points (Optional)': 'အဓိကအချက်များ (ရွေးချယ်ခွင့်)',
  'What is your video about?': 'သင့်ဗီဒီယိုက ဘာအကြောင်းလဲ?',
  'List key points to cover (optional)...':
      'ဖုံးလွှမ်းရန် အဓိကအချက်များစာရင်း (ရွေးချယ်ခွင့်)...',
  'Video Duration': 'ဗီဒီယိုကြာချိန်',
  'Script Tone': 'ဇာတ်ညွှန်းလေသံ',
  'Script Options': 'ဇာတ်ညွှန်းရွေးချယ်မှုများ',
  'Include Hook/Intro': 'Hook/နိဒါန်းထည့်',
  'Include Call-to-Action': 'လုပ်ဆောင်မှုတောင်းဆိုချက်ထည့်',
  'Include Timestamps': 'အချိန်တံဆိပ်များထည့်',
  'Please enter a video topic': 'ကျေးဇူးပြု၍ ဗီဒီယိုအကြောင်းအရာထည့်ပါ',
  'Generate Script': 'ဇာတ်ညွှန်းဖန်တီး',
  'Create scripts for videos & reels':
      'ဗီဒီယိုများနှင့် reels အတွက် ဇာတ်ညွှန်းများဖန်တီး',
  'Create Script': 'ဇာတ်ညွှန်းဖန်တီး',
  // Script Types
  'Storytime': 'ဇာတ်လမ်းအချိန်',
  'Documentary': 'မှတ်တမ်းရုပ်ရှင်',
  'Short Reel': 'Reel တို',
  'Motivational': 'လှုံ့ဆော်မှု',
  'Educational': 'ပညာရေး',
  'Review': 'သုံးသပ်ချက်',
  'Tutorial': 'သင်ခန်းစာ',
  // Durations
  '< 1 min (Shorts)': '< ၁ မိနစ် (Shorts)',
  '1-3 min': '၁-၃ မိနစ်',
  '5-10 min': '၅-၁၀ မိနစ်',
  '10-20 min': '၁၀-၂၀ မိနစ်',
  '20+ min': '၂၀+ မိနစ်',
  // Script Tones
  'Engaging': 'ဆွဲဆောင်မှု',
  'Energetic': 'စွမ်းအင်',
  'Calm': 'တည်ငြိမ်',
  'Funny': 'ရယ်စရာ',

  // Story Generator - Styles
  'Inspired': 'လှုံ့ဆော်',
  'Standard': 'စံ',
  'Imaginative': 'စိတ်ကူး',
  'Innovative': 'ဆန်းသစ်',

  // Script Writer - Script Tones (formats)
  'Short Film': 'ရုပ်ရှင်တို',
  'Film Script': 'ရုပ်ရှင်ဇာတ်ညွှန်း',
  'Stage Play': 'ဇာတ်စင်',
  'Advertisement': 'ကြော်ငြာ',
  'Tiktok Video': 'Tiktok ဗီဒီယို',
  'Movie': 'ရုပ်ရှင်',
  'Scene Breakdown': 'မြင်ကွင်းခွဲခြမ်း',
  'Dialogue Only': 'စကားပြောသာ',

  // Script Writer - Script Types
  'Action': 'အက်ရှင်',
  'Fairy Tale': 'ပုံပြင်',

  // Ad & UI
  'Ad loading please wait..': 'ကြော်ငြာတင်နေသည် ကျေးဇူးပြု၍ စောင့်ပါ..',

  // Word Counter & Reading Time
  'Words:': 'စာလုံး:',
  'Reading:': 'ဖတ်ရှုခြင်း:',

  "Character Story": "ဇာတ်ကောင်ပုံပြင်",
  "Create detailed character backstories":
      "ဇာတ်ကောင်၏ အသေးစိတ်နောက်ခံပုံပြင်များ ဖန်တီးပါ",
  "Create Character": "ဇာတ်ကောင်ဖန်တီးရန်",
  "Rewrite Story": "ပုံပြင်ပြန်ရေးရန်",
  "Paste Your Story": "သင်၏ပုံပြင်ကူးထည့်ပါ",
  "Paste your story here to rewrite...":
      "ပြန်ရေးရန် သင်၏ပုံပြင်ကို ဤနေရာတွင် ကူးထည့်ပါ...",
  "Transform and improve your existing stories":
      "သင်၏ရှိပြီးသားပုံပြင်များကို ပြောင်းလဲ ပိုမိုကောင်းမွန်အောင်ပြုလုပ်ပါ",
  "Title Generator": "ခေါင်းစဉ်ထုတ်လုပ်သူ",
  "Generate catchy titles for your stories":
      "သင်၏ပုံပြင်များအတွက် ဆွဲဆောင်မှုရှိသောခေါင်းစဉ်များ ထုတ်လုပ်ပါ",
  "Generate Titles": "ခေါင်းစဉ်များထုတ်လုပ်ရန်",
  "Blog Writer": "ဘလော့ဂ်ရေးသူ",
  "Blog Topic": "ဘလော့ဂ်ခေါင်းစဉ်",
  "Target Keywords": "ပစ်မှတ်သော့ချက်စကားလုံးများ",
  "Target Audience (Optional)": "ပစ်မှတ်ပရိသတ် (ရွေးချယ်နိုင်)",
  "Enter your blog topic or title...":
      "သင်၏ဘလော့ဂ်ခေါင်းစဉ် သို့မဟုတ် ခေါင်းစဉ်ကို ထည့်သွင်းပါ...",
  "e.g., AI writing, content marketing, SEO tips":
      "ဥပမာ - AI ရေးသားခြင်း၊ အကြောင်းအရာ မားကတ်တင်၊ SEO အကြံပြုချက်များ",
  "e.g., small business owners, bloggers":
      "ဥပမာ - လုပ်ငန်းငယ်ပိုင်ရှင်များ၊ ဘလော့ဂ်ရေးသားသူများ",
  "Article Type": "ဆောင်းပါးအမျိုးအစား",
  "Writing Tone": "ရေးသားမှုသံချပ်",
  "Article Length": "ဆောင်းပါးအရှည်",
  "SEO Options": "SEO ရွေးချယ်မှုများ",
  "Include Meta Description": "Meta ဖော်ပြချက်ထည့်သွင်းရန်",
  "Include Keyword Suggestions": "သော့ချက်စကားလုံးအကြံပြုချက်များ ထည့်သွင်းရန်",
  "Include FAQs Section": "FAQ အပိုင်းထည့်သွင်းရန်",
  "Please enter a blog topic": "ဘလော့ဂ်ခေါင်းစဉ်ထည့်သွင်းပါ",
  "Generate Blog": "ဘလော့ဂ်ထုတ်လုပ်ရန်",
  "SEO optimized articles with keywords":
      "သော့ချက်စကားလုံးများပါသော SEO အကောင်းဆုံးဆောင်းပါးများ",
  "Write Blog": "ဘလော့ဂ်ရေးရန်",
  "YouTube Script": "YouTube 台本",
  "Video Topic": "ဗီဒီယိုခေါင်းစဉ်",
  "Key Points (Optional)": "အဓိကအချက်များ (ရွေးချယ်နိုင်)",
  "What is your video about?": "သင်၏ဗီဒီယိုသည် ဘာနှင့်ပတ်သက်သနည်း?",
  "List key points to cover (optional)...":
      "ဖော်ပြရမည့် အဓိကအချက်များ စာရင်းပြုစုပါ (ရွေးချယ်နိုင်)...",
  "Video Duration": "ဗီဒီယိုကြာချိန်",
  "Script Options": "Script ရွေးချယ်မှုများ",
  "Include Hook/Intro": "Hook/နိဒါန်းထည့်သွင်းရန်",
  "Include Call-to-Action": "လုပ်ဆောင်ရန်တိုက်တွန်းချက်ထည့်သွင်းရန်",
  "Include Timestamps": "အချိန်အမှတ်အသားများထည့်သွင်းရန်",
  "Please enter a video topic": "ဗီဒီယိုခေါင်းစဉ်ထည့်သွင်းပါ",
  "Generate Script": "Script ထုတ်လုပ်ရန်",
  "Create scripts for videos & reels":
      "ဗီဒီယိုနှင့် ရီးလ်များအတွက် script များဖန်တီးပါ",
  "Create Script": "Script ဖန်တီးရန်",
  "Character Details": "ဇာတ်ကောင်အသေးစိတ်",
  "Character Name": "ဇာတ်ကောင်အမည်",
  "Age (e.g., 25, Young Adult, Ancient)": "အသက် (ဥပမာ - ၂၅၊ လူငယ်၊ ရှေးဟောင်း)",
  "Personality (e.g., brave, shy, cunning)":
      "ကိုယ်ရည်ကိုယ်သွေး (ဥပမာ - ရဲရင့်သော၊ ရှက်တတ်သော၊ လိမ္မာသော)",
  "Role (e.g., Hero, Villain, Mentor)":
      "အခန်းကဏ္ဍ (ဥပမာ - သူရဲကောင်း၊ သူဆိုး၊ လမ်းပြ)",
  "Additional Details (optional)": "နောက်ထပ်အသေးစိတ် (ရွေးချယ်နိုင်)",
  "Output Style": "ရလဒ်ပုံစံ",
  "Generate Character": "ဇာတ်ကောင်ထုတ်လုပ်ရန်",
  "Please enter character name": "ဇာတ်ကောင်အမည်ထည့်သွင်းပါ",
  "Please enter character role": "ဇာတ်ကောင်အခန်းကဏ္ဍထည့်သွင်းပါ",
  "Detailed": "အသေးစိတ်",
  "Brief": "အကျဉ်းချုပ်",
  "Elaborate": "ရှင်းလင်းပြည့်စုံသော",
  "Select Tone": "သံချပ်ရွေးချယ်ပါ",
  "Rewrite Style": "ပြန်ရေးမည့်ပုံစံ",
  "Output Length": "ရလဒ်အရှည်",
  "Please paste your story": "သင်၏ပုံပြင်ကူးထည့်ပါ",
  "Story is too short. Please provide more content.":
      "ပုံပြင်တိုလွန်းသည်။ ပိုမိုများသောအကြောင်းအရာ ထည့်သွင်းပါ။",
  "Same": "အတူတူ",
  "More Dramatic": "ပိုမိုဒရာမာကြီးသော",
  "More Humorous": "ပိုမိုရွှင်မြူးသော",
  "More Emotional": "ပိုမိုခံစားမှုရှိသော",
  "More Suspenseful": "ပိုမိုစိုးရိမ်ဖွယ်ကောင်းသော",
  "Lighter": "ပိုမိုပေါ့ပါးသော",
  "Improved": "ပိုမိုကောင်းမွန်သော",
  "Simplified": "ပိုမိုရိုးရှင်းသော",
  "More Descriptive": "ပိုမိုဖော်ပြသော",
  "More Dialogue": "ပိုမိုစကားပြောဆိုမှု",
  "More Action": "ပိုမိုလုပ်ဆောင်မှု",
  "Literary": "စာပေဆိုင်ရာ",
  "Shorter": "ပိုတိုသော",
  "Longer": "ပိုရှည်သော",
  "Much Longer": "များစွာပိုရှည်သော",
  "Rewrite Now": "ယခုပြန်ရေးပါ",
  "Story/Book Topic": "ပုံပြင်/စာအုပ်ခေါင်းစဉ်",
  "Keywords (Optional)": "သော့ချက်စကားလုံးများ (ရွေးချယ်နိုင်)",
  "Describe your story topic or theme...":
      "သင်၏ပုံပြင်ခေါင်းစဉ် သို့မဟုတ် အကြောင်းအရာ ဖော်ပြပါ...",
  "e.g., magic, dragon, adventure": "ဥပမာ - မှော်၊ နဂါး၊ စွန့်စားမှု",
  "Title For": "ခေါင်းစဉ်",
  "Title Style": "ခေါင်းစဉ်ပုံစံ",
  "Number of Titles": "ခေါင်းစဉ်အရေအတွက်",
  "Book": "စာအုပ်",
  "Short Story": "တိုတောင်းသောပုံပြင်",
  "Novel": "ဝတ္ထု",
  "Chapter": "အခန်း",
  "Series": "စီးရီး",
  "Simple": "ရိုးရှင်းသော",
  "Mysterious": "နက်နဲသော",
  "Dramatic": "ဒရာမာကြီးသော",
  "Catchy": "ဆွဲဆောင်မှုရှိသော",
  "Poetic": "ကဗျာဆန်သော",
  "Kids": "ကလေးများအတွက်",
  "SEO Article": "SEO ဆောင်းပါး",
  "How-To Guide": "လမ်းညွှန်ချက်",
  "Listicle": "စာရင်းဆောင်းပါး",
  "Product Review": "ကုန်ပစ္စည်းသုံးသပ်ချက်",
  "Opinion Piece": "သဘောထားဆောင်းပါး",
  "News Article": "သတင်းဆောင်းပါး",
  "Professional": "ပရော်ဖက်ရှင်နယ်",
  "Casual": "သာမာန်",
  "Informative": "သတင်းအချက်အလက်ပေးသော",
  "Persuasive": "ယုံကြည်စေသော",
  "Friendly": "ဖော်ရွေသော",
  "Authoritative": "အာဏာပိုင်ဆန်သော",
  "Short (500-800)": "တို (500-800)",
  "Medium (800-1500)": "အလတ်စား (800-1500)",
  "Long (1500-2500)": "ရှည် (1500-2500)",
  "Detailed (2500+)": "အသေးစိတ် (2500+)",
  "Storytime": "ပုံပြင်ချိန်",
  "Documentary": "မှတ်တမ်းရုပ်ရှင်",
  "Short Reel": "တိုတောင်းသောရီးလ်",
  "Educational": "ပညာရေးဆိုင်ရာ",
  "Review": "သုံးသပ်ချက်",
  "Tutorial": "သင်ခန်းစာ",
  "< 1 min (Shorts)": "< ၁ မိနစ် (တိုတောင်း)",
  "1-3 min": "၁-၃ မိနစ်",
  "5-10 min": "၅-၁၀ မိနစ်",
  "10-20 min": "၁၀-၂၀ မိနစ်",
  "20+ min": "၂၀+ မိနစ်",
  "Engaging": "ဆွဲဆောင်မှုရှိသော",
  "Energetic": "စွမ်းအင်ပြည့်သော",
  "Calm": "တည်ငြိမ်သော",
  "Funny": "မျက်နှာပျက်စရာကောင်းသော",
  "Next": "နောက်တစ်ဆင့်",
  "Get Started": "စတင်ရန်",
  "Your tool for quick, high-quality essay writing":
      "မြန်ဆန်၍ အရည်အသွေးမြင့်သော စာရေးခြင်းအတွက် သင်၏ကိရိယာ",
};
