import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ne = {
  AppKeys.lblChooseLanguage: "भाषा छान्नुहोस्",
  "All": "सबै",
  "AI Story Generator": "AI कथा जेनेरेटर",
  "Story Generator": "कथा जेनेरेटर",
  "Essay Writer": "निबन्ध लेखक",
  "Essay length": "निबन्ध लम्बाइ",
  "Script Generator": "स्क्रिप्ट जेनेरेटर",
  "Create original stories in seconds":
      "सेकेन्डमा मौलिक कथाहरू सिर्जना गर्नुहोस्",
  "Academic writing made simple": "शैक्षिक लेखन सरल बनाइएको",
  "Generate powerful scripts for any medium":
      "कुनै पनि माध्यमको लागि शक्तिशाली स्क्रिप्टहरू उत्पन्न गर्नुहोस्",
  "Start Writing": "लेख्न सुरु गर्नुहोस्",
  "Create Now": "अहिले सिर्जना गर्नुहोस्",
  "Start Generating": "उत्पन्न गर्न सुरु गर्नुहोस्",
  "Your Stories": "तपाईंका कथाहरू",
  "No stories yet": "अहिलेसम्म कुनै कथा छैन",
  "Start creating your first story!":
      "आफ्नो पहिलो कथा सिर्जना गर्न सुरु गर्नुहोस्!",
  "Your Story Space Awaits": "तपाईंको कथा स्थान पर्खिरहेको छ",
  "Start your first story and see it appear here":
      "आफ्नो पहिलो कथा सुरु गर्नुहोस् र यहाँ देखिनुहोस्",
  "Language": "भाषा",
  "Rate us": "हामीलाई मूल्याङ्कन गर्नुहोस्",
  "Share us": "हामीलाई साझा गर्नुहोस्",
  "Privacy Policy": "गोपनीयता नीति",
  "Settings": "सेटिङहरू",
  "Select Language": "भाषा छान्नुहोस्",
  "Dashboard": "ड्यासबोर्ड",
  "BENEFITS": "लाभहरू",
  "Subscribe": "सदस्यता लिनुहोस्",
  "Weekly": "साप्ताहिक",
  "Monthly": "मासिक",
  "Yearly": "वार्षिक",
  "week": "हप्ता",
  "months": "महिना",
  "year": "वर्ष",
  "Terms & Condition": "सर्तहरू र शर्तहरू",
  "No Commitment. Cancel anytime":
      "कुनै प्रतिबद्धता छैन। जुनसुकै बेला रद्द गर्नुहोस्",
  "No Payment Now": "अहिले कुनै भुक्तानी छैन",
  "3 days free": "३ दिन निःशुल्क",
  "Start your free trial": "आफ्नो निःशुल्क परीक्षण सुरु गर्नुहोस्",
  "More detailed answers": "थप विस्तृत जवाफहरू",
  "Instant responds": "तात्कालिक जवाफहरू",
  "Text recognition": "पाठ पहिचान",
  "Powered by AI": "AI द्वारा संचालित",
  "Storytelleing": "कथा भनाइ",
  ' Power': "शक्ति",
  "Unlock your \nFill ": "तपाईंको \nभर्नुहोस् अनलक गर्नुहोस्",
  "Your History": "तपाईंको इतिहास",
  "Terms and Conditions": "सर्तहरू र शर्तहरू",
  "Short": "छोटो",
  "Medium": "मध्यम",
  "Long": "लामो",
  "Length": "लम्बाइ",
  "Describe your topic...": "आफ्नो विषय वर्णन गर्नुहोस्...",
  "Set Creativity": "सिर्जनात्मकता सेट गर्नुहोस्",
  "Standard": "मानक",
  "Creative": "सिर्जनात्मक",
  "Complex": "जटिल",
  "Select Genre": "शैली छान्नुहोस्",
  "Fantasy": "कल्पना",
  "Mystery": "रहस्य",
  "Thriller": "थ्रिलर",
  "Script Tone": "स्क्रिप्ट टोन",
  "Script Type": "स्क्रिप्ट प्रकार",
  "Comedy": "हास्य",
  "Drama": "नाटक",
  "Horror": "डरलाग्दो",
  "Action": "एक्सन",
  "Romance": "रोमान्स",
  "Go Premium": "प्रिमियम लिनुहोस्",
  "Unlock Everything": "सबै अनलक गर्नुहोस्",
  "Unlimited Story Generation": "असीमित कथा उत्पादन",
  "Write Longer & Detailed Essays": "लामो र विस्तृत निबन्धहरू लेख्नुहोस्",
  "Advanced Script Writer": "उन्नत स्क्रिप्ट लेखक",
  "Unlock All Styles & Tones": "सबै शैली र टोनहरू अनलक गर्नुहोस्",
  "No Word/Length Limit": "शब्द/लम्बाइ सीमा छैन",
  "Remove All Ads": "सबै विज्ञापनहरू हटाउनुहोस्",
  "Restore": "पुनर्स्थापित गर्नुहोस्",
  "YouTube Video": "YouTube भिडियो",
  "Podcast": "पोडकास्ट",
  "Reel": "रिल",
  "Motivational": "प्रेरणादायी",
  "Advertisement": "विज्ञापन",
  "Fairy Tale": "परी कथा",
  "Sci-Fi": "विज्ञान कथा",
  "Select Style": "शैली छान्नुहोस्",
  "Imaginative": "कल्पनाशील",
  "Innovative": "नवीन",
  "AI Story Writer": "AI कथा लेखक",
  "Generate": "उत्पन्न गर्नुहोस्",
  "Please wait...": "कृपया पर्खनुहोस्...",
  "Result": "परिणाम",
  "Regenerate": "पुन: उत्पन्न गर्नुहोस्",
  "Download": "डाउनलोड गर्नुहोस्",
  "Text copied to clipboard!": "पाठ क्लिपबोर्डमा प्रतिलिपि गरियो!",
  "Please enter a topic": "कृपया विषय प्रविष्ट गर्नुहोस्",
  "Story Magic": "कथा जादू",
  "Let AI bring your thoughts to a full story":
      "AI लाई तपाईंको विचारहरू पूर्ण कथामा ल्याउन दिनुहोस्",
  "Smart Scripts": "स्मार्ट स्क्रिप्टहरू",
  "From concept to script—fast, easy, and creative":
      "अवधारणादेखि स्क्रिप्टसम्म—छिटो, सजिलो, र सिर्जनात्मक",
  "Perfect Essays": "उत्तम निबन्धहरू",
  "You have reached your free limit": "तपाईंले आफ्नो निःशुल्क सीमामा पुगेको छ",
  "Donwload": "डाउनलोड गर्नुहोस्",
  "Press again to exit app": "एप बाट बाहिर निस्कन फेरि थिच्नुहोस्",
  "Saved to files": "TXT फाइल सफलतापूर्वक बचत गरियो!",
  "Error: Please try again": "त्रुटि: कृपया फेरि प्रयास गर्नुहोस्",
  "Subscription expired": "सदस्यता समाप्त भयो",
  "Purchase cancelled": "खरिद रद्द गरियो",
  "Purchase failed": "खरिद असफल भयो",
  "Restore failed": "पुनर्स्थापना असफल भयो",
  "Purchase Successful!": "खरिद सफल!",
  "Short (200-500 words)": "छोटो (२००-५०० शब्द)",
  "Medium (500-1000 words)": "मध्यम (५००-१००० शब्द)",
  "Large (1000+ words)": "ठूलो (१०००+ शब्द)",
  "Academic Level": "शैक्षिक स्तर",
  "Type of Paper": "कागजको प्रकार",
  "High School": "उच्च माध्यमिक विद्यालय",
  "College": "कलेज",
  "Short Film": "छोटो फिल्म",
  "University": "विश्वविद्यालय",
  "Masters": "स्नातकोत्तर",
  "Custom": "अनुकूलित",
  "Tiktok Video": "Tiktok भिडियो",
  "Movie": "फिल्म",
  "Expository": "व्याख्यात्मक",
  "Argumentative": "तर्कसंगत",
  "Narrative": "कथात्मक",
  "Descriptive": "वर्णनात्मक",
  "We're sorry to hear that 😔": "यो सुनेर हामीलाई दुःख लाग्यो 😔",
  "We'll try to improve 🙁": "हामी सुधार गर्न प्रयास गर्नेछौं 🙁",
  "Thanks for your feedback 🙂": "तपाईंको प्रतिक्रियाको लागि धन्यवाद 🙂",
  "Great! We're glad you like it 😊":
      "उत्कृष्ट! तपाईंलाई मन परेकोमा खुशी लाग्यो 😊",
  "Awesome! Thank you so much! 🎉": "अद्भुत! धेरै धन्यवाद! 🎉",
  "Maybe Later": "शायद पछि",
  "Tap a star to rate your experience":
      "आफ्नो अनुभव मूल्याङ्कन गर्न ताराबाट थिच्नुहोस्",
  "Enjoying AI Math Solver?": "AI Math Solver रमाइलो लाग्यो?",
  "Thank you for rating us": "हामीलाई मूल्याङ्कन गरेकोमा धन्यवाद",
  "Submit Rating": "मूल्याङ्कन पेश गर्नुहोस्",
  "Hindi": "हिन्दी",
  "Enjoying AI Story Generator?": "AI Story Generator रमाइलो लाग्यो?",
  "Adventure": "साहसिक",
  "Inspired": "प्रेरित",
  "Film Script": "फिल्म स्क्रिप्ट",
  "Stage Play": "मञ्च नाटक",
  "Scene Breakdown": "दृश्य विश्लेषण",
  "Dialogue Only": "संवाद मात्र",
  "Ad loading please wait..": "विज्ञापन लोड हुँदैछ, कृपया पर्खनुहोस्...",
  "Words:": "शब्दहरू:",
  "Reading:": "पढाइ:",

  AppKeys.arabic: "अरबी",
  AppKeys.chinese: "चिनियाँ",
  AppKeys.english: "अंग्रेजी",
  AppKeys.french: "फ्रेन्च",
  AppKeys.german: "जर्मन",
  AppKeys.hindi: "हिन्दी",
  AppKeys.indonesian: "इन्डोनेसियाली",
  AppKeys.japanese: "जापानी",
  AppKeys.korean: "कोरियाली",
  AppKeys.portuguese: "पोर्तुगाली",
  AppKeys.russian: "रूसी",
  AppKeys.spanish: "स्पेनिश",
  AppKeys.turkish: "टर्किश",

  // New strings for download & actions
  'Download As': 'डाउनलोड गर्नुहोस्',
  'Choose format to download': 'डाउनलोडको लागि ढाँचा छान्नुहोस्',
  'Text File': 'पाठ फाइल',
  'PDF File': 'PDF फाइल',
  'Copy': 'प्रतिलिपि गर्नुहोस्',
  'Share': 'साझा गर्नुहोस्',
  'Text copied!': 'पाठ प्रतिलिपि गरियो!',
  'Copied to clipboard': 'क्लिपबोर्डमा प्रतिलिपि गरियो',
  'File saved successfully': 'फाइल सफलतापूर्वक बचत गरियो',
  'Error saving file': 'फाइल बचत गर्दा त्रुटि',
  'Share Story': 'कथा साझा गर्नुहोस्',
  'Export': 'निर्यात गर्नुहोस्',

  "Character Story": "पात्रको कथा",
  "Create detailed character backstories":
      "पात्रको विस्तृत पृष्ठभूमि कथा बनाउनुहोस्",
  "Create Character": "पात्र बनाउनुहोस्",
  "Rewrite Story": "कथा पुनर्लेखन गर्नुहोस्",
  "Paste Your Story": "आफ्नो कथा टाँस्नुहोस्",
  "Paste your story here to rewrite...":
      "पुनर्लेखनका लागि आफ्नो कथा यहाँ टाँस्नुहोस्...",
  "Transform and improve your existing stories":
      "आफ्ना अवस्थित कथाहरू रूपान्तरण र सुधार गर्नुहोस्",
  "Title Generator": "शीर्षक जनरेटर",
  "Generate catchy titles for your stories":
      "आफ्ना कथाहरूका लागि आकर्षक शीर्षकहरू उत्पन्न गर्नुहोस्",
  "Generate Titles": "शीर्षकहरू उत्पन्न गर्नुहोस्",
  "Blog Writer": "ब्लग लेखक",
  "Blog Topic": "ब्लग विषय",
  "Target Keywords": "लक्षित किवर्डहरू",
  "Target Audience (Optional)": "लक्षित दर्शक (वैकल्पिक)",
  "Enter your blog topic or title...":
      "आफ्नो ब्लग विषय वा शीर्षक प्रविष्ट गर्नुहोस्...",
  "e.g., AI writing, content marketing, SEO tips":
      "जस्तै, AI लेखन, सामग्री मार्केटिङ, SEO सुझावहरू",
  "e.g., small business owners, bloggers":
      "जस्तै, साना व्यवसाय मालिकहरू, ब्लगरहरू",
  "Article Type": "लेखको प्रकार",
  "Writing Tone": "लेखन स्वर",
  "Article Length": "लेखको लम्बाइ",
  "SEO Options": "SEO विकल्पहरू",
  "Include Meta Description": "मेटा विवरण समावेश गर्नुहोस्",
  "Include Keyword Suggestions": "किवर्ड सुझावहरू समावेश गर्नुहोस्",
  "Include FAQs Section": "FAQ खण्ड समावेश गर्नुहोस्",
  "Please enter a blog topic": "कृपया ब्लग विषय प्रविष्ट गर्नुहोस्",
  "Generate Blog": "ब्लग उत्पन्न गर्नुहोस्",
  "SEO optimized articles with keywords": "किवर्डहरू सहित SEO अनुकूलित लेखहरू",
  "Write Blog": "ब्लग लेख्नुहोस्",
  "YouTube Script": "YouTube स्क्रिप्ट",
  "Video Topic": "भिडियो विषय",
  "Key Points (Optional)": "मुख्य बुँदाहरू (वैकल्पिक)",
  "What is your video about?": "तपाईंको भिडियो के बारेमा हो?",
  "List key points to cover (optional)...":
      "समेट्नुपर्ने मुख्य बुँदाहरू सूचीबद्ध गर्नुहोस् (वैकल्पिक)...",
  "Video Duration": "भिडियो अवधि",
  "Script Options": "स्क्रिप्ट विकल्पहरू",
  "Include Hook/Intro": "हुक/परिचय समावेश गर्नुहोस्",
  "Include Call-to-Action": "कार्यका लागि आह्वान समावेश गर्नुहोस्",
  "Include Timestamps": "टाइमस्ट्याम्पहरू समावेश गर्नुहोस्",
  "Please enter a video topic": "कृपया भिडियो विषय प्रविष्ट गर्नुहोस्",
  "Generate Script": "स्क्रिप्ट उत्पन्न गर्नुहोस्",
  "Create scripts for videos & reels":
      "भिडियो र रिलहरूका लागि स्क्रिप्टहरू बनाउनुहोस्",
  "Create Script": "स्क्रिप्ट बनाउनुहोस्",
  "Character Details": "पात्रको विवरण",
  "Character Name": "पात्रको नाम",
  "Age (e.g., 25, Young Adult, Ancient)": "उमेर (जस्तै, २५, युवा, प्राचीन)",
  "Personality (e.g., brave, shy, cunning)":
      "व्यक्तित्व (जस्तै, साहसी, लजालु, चालाक)",
  "Role (e.g., Hero, Villain, Mentor)":
      "भूमिका (जस्तै, नायक, खलनायक, मार्गदर्शक)",
  "Additional Details (optional)": "थप विवरण (वैकल्पिक)",
  "Output Style": "आउटपुट शैली",
  "Generate Character": "पात्र उत्पन्न गर्नुहोस्",
  "Please enter character name": "कृपया पात्रको नाम प्रविष्ट गर्नुहोस्",
  "Please enter character role": "कृपया पात्रको भूमिका प्रविष्ट गर्नुहोस्",
  "Detailed": "विस्तृत",
  "Brief": "संक्षिप्त",
  "Elaborate": "विस्तारित",
  "Select Tone": "स्वर चयन गर्नुहोस्",
  "Rewrite Style": "पुनर्लेखन शैली",
  "Output Length": "आउटपुट लम्बाइ",
  "Please paste your story": "कृपया आफ्नो कथा टाँस्नुहोस्",
  "Story is too short. Please provide more content.":
      "कथा धेरै छोटो छ। कृपया थप सामग्री प्रदान गर्नुहोस्।",
  "Same": "उही",
  "More Dramatic": "थप नाटकीय",
  "More Humorous": "थप हास्यपूर्ण",
  "More Emotional": "थप भावनात्मक",
  "More Suspenseful": "थप रोमाञ्चकारी",
  "Lighter": "हल्का",
  "Improved": "सुधारिएको",
  "Simplified": "सरलीकृत",
  "More Descriptive": "थप वर्णनात्मक",
  "More Dialogue": "थप संवाद",
  "More Action": "थप कार्य",
  "Literary": "साहित्यिक",
  "Shorter": "छोटो",
  "Longer": "लामो",
  "Much Longer": "धेरै लामो",
  "Rewrite Now": "अहिले पुनर्लेखन गर्नुहोस्",
  "Story/Book Topic": "कथा/पुस्तक विषय",
  "Keywords (Optional)": "किवर्डहरू (वैकल्पिक)",
  "Describe your story topic or theme...":
      "आफ्नो कथाको विषय वा थिम वर्णन गर्नुहोस्...",
  "e.g., magic, dragon, adventure": "जस्तै, जादू, ड्र्यागन, साहसिक यात्रा",
  "Title For": "शीर्षक",
  "Title Style": "शीर्षक शैली",
  "Number of Titles": "शीर्षकहरूको संख्या",
  "Book": "पुस्तक",
  "Short Story": "छोटो कथा",
  "Novel": "उपन्यास",
  "Chapter": "अध्याय",
  "Series": "श्रृंखला",
  "Simple": "सरल",
  "Mysterious": "रहस्यमय",
  "Dramatic": "नाटकीय",
  "Catchy": "आकर्षक",
  "Poetic": "काव्यात्मक",
  "Kids": "बालबालिका",
  "SEO Article": "SEO लेख",
  "How-To Guide": "कसरी गाइड",
  "Listicle": "सूची लेख",
  "Product Review": "उत्पाद समीक्षा",
  "Opinion Piece": "मत लेख",
  "News Article": "समाचार लेख",
  "Professional": "व्यावसायिक",
  "Casual": "अनौपचारिक",
  "Informative": "सूचनात्मक",
  "Persuasive": "प्रेरक",
  "Friendly": "मैत्रीपूर्ण",
  "Authoritative": "आधिकारिक",
  "Short (500-800)": "छोटो (500-800)",
  "Medium (800-1500)": "मध्यम (800-1500)",
  "Long (1500-2500)": "लामो (1500-2500)",
  "Detailed (2500+)": "विस्तृत (2500+)",
  "Storytime": "कथा समय",
  "Documentary": "वृत्तचित्र",
  "Short Reel": "छोटो रिल",
  "Educational": "शैक्षिक",
  "Review": "समीक्षा",
  "Tutorial": "ट्युटोरियल",
  "< 1 min (Shorts)": "< १ मिनेट (छोटो)",
  "1-3 min": "१-३ मिनेट",
  "5-10 min": "५-१० मिनेट",
  "10-20 min": "१०-२० मिनेट",
  "20+ min": "२०+ मिनेट",
  "Engaging": "आकर्षक",
  "Energetic": "उत्साहित",
  "Calm": "शान्त",
  "Funny": "मजाकिया",
  "Next": "अर्को",
  "Get Started": "सुरु गर्नुहोस्",
  "Your tool for quick, high-quality essay writing":
      "द्रुत र उच्च गुणस्तरको निबन्ध लेखनका लागि तपाईंको उपकरण",
};
