import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> nl = {
  AppKeys.lblChooseLanguage: "Kies Taal",
  AppKeys.arabic: "Arabisch",
  AppKeys.chinese: "Chinees",
  AppKeys.english: "Engels",
  AppKeys.french: "Frans",
  AppKeys.german: "Duits",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesisch",
  AppKeys.japanese: "Japans",
  AppKeys.korean: "Koreaans",
  AppKeys.portuguese: "Portugees",
  AppKeys.russian: "Russisch",
  AppKeys.spanish: "Spaans",
  AppKeys.turkish: "Turks",
  AppKeys.btnNext: "Volgende",
  AppKeys.dahsboard: "Dashboard",
  AppKeys.yourStories: "Jouw Verhalen",
  AppKeys.setting: "Instellingen",
  AppKeys.btngetStarted: "Aan de Slag",
  '': "Aan de Slag",

  'Download As': 'Downloaden Als',
  'Choose format to download': 'Kies formaat om te downloaden',
  'Text File': 'Tekstbestand',
  'PDF File': 'PDF-bestand',
  'Copy': 'Kopiëren',
  'Share': 'Delen',
  'Download': 'Downloaden',
  'Text copied!': 'Tekst gekopieerd!',
  'PDF saved successfully!': 'PDF succesvol opgeslagen!',
  'Saved to files': 'Opgeslagen in bestanden',
  'Error: Please try again': 'Fout: Probeer het opnieuw',
  'Error creating PDF: Please try again':
      'Fout bij maken PDF: Probeer het opnieuw',

  'Character Story': 'Karakterverhaal',
  'Character Details': 'Karakterdetails',
  'Character Name': 'Karakternaam',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Leeftijd (bijv., 25, Jong Volwassen, Oud)',
  'Personality (e.g., brave, shy, cunning)':
      'Persoonlijkheid (bijv., dapper, verlegen, sluw)',
  'Role (e.g., Hero, Villain, Mentor)': 'Rol (bijv., Held, Schurk, Mentor)',
  'Additional Details (optional)': 'Aanvullende Details (optioneel)',
  'Select Genre': 'Selecteer Genre',
  'Output Style': 'Uitvoerstijl',
  'Generate Character': 'Genereer Karakter',
  'Please enter character name': 'Voer alstublieft karakternaam in',
  'Please enter character role': 'Voer alstublieft karakterrol in',
  'Fantasy': 'Fantasie',
  'Sci-Fi': 'Sci-Fi',
  'Romance': 'Romantiek',
  'Horror': 'Horror',
  'Comedy': 'Komedie',
  'Drama': 'Drama',
  'Adventure': 'Avontuur',
  'Detailed': 'Gedetailleerd',
  'Brief': 'Kort',
  'Elaborate': 'Uitgebreid',

  'Create detailed character backstories':
      'Maak gedetailleerde karakterachtergronden',
  'Create Character': 'Maak Karakter',
  'Transform and improve your existing stories':
      'Transformeer en verbeter je bestaande verhalen',
  'Rewrite Now': 'Nu Herschrijven',
  'Generate catchy titles for your stories':
      'Genereer pakkende titels voor je verhalen',
  'Generate Titles': 'Genereer Titels',

  'Rewrite Story': 'Verhaal Herschrijven',
  'Paste Your Story': 'Plak Je Verhaal',
  'Paste your story here to rewrite...':
      'Plak je verhaal hier om te herschrijven...',
  'Select Tone': 'Selecteer Toon',
  'Rewrite Style': 'Herschrijfstijl',
  'Output Length': 'Uitvoerlengte',
  'Please paste your story': 'Plak alstublieft je verhaal',
  'Story is too short. Please provide more content.':
      'Verhaal is te kort. Geef alstublieft meer inhoud.',
  'Same': 'Hetzelfde',
  'More Dramatic': 'Dramatischer',
  'More Humorous': 'Humoristischer',
  'More Emotional': 'Emotioneler',
  'More Suspenseful': 'Spannender',
  'Lighter': 'Lichter',
  'Improved': 'Verbeterd',
  'Simplified': 'Vereenvoudigd',
  'More Descriptive': 'Meer Beschrijvend',
  'More Dialogue': 'Meer Dialoog',
  'More Action': 'Meer Actie',
  'Literary': 'Literair',
  'Shorter': 'Korter',
  'Longer': 'Langer',
  'Much Longer': 'Veel Langer',

  'Title Generator': 'Titelgenerator',
  'Story/Book Topic': 'Verhaal/Boek Onderwerp',
  'Keywords (Optional)': 'Trefwoorden (Optioneel)',
  'Describe your story topic or theme...':
      'Beschrijf je verhaalonderwerp of thema...',
  'e.g., magic, dragon, adventure': 'bijv., magie, draak, avontuur',
  'Title For': 'Titel Voor',
  'Title Style': 'Titelstijl',
  'Number of Titles': 'Aantal Titels',
  'Please enter a topic': 'Voer alstublieft een onderwerp in',
  'Book': 'Boek',
  'Short Story': 'Kort Verhaal',
  'Novel': 'Roman',
  'Chapter': 'Hoofdstuk',
  'Series': 'Serie',
  'Creative': 'Creatief',
  'Simple': 'Eenvoudig',
  'Mysterious': 'Mysterieus',
  'Dramatic': 'Dramatisch',
  'Catchy': 'Pakkend',
  'Poetic': 'Poëtisch',
  'Mystery': 'Mysterie',
  'Thriller': 'Thriller',
  'Kids': 'Kinderen',

  'Blog Writer': 'Blogschrijver',
  'Blog Topic': 'Blogonderwerp',
  'Target Keywords': 'Doeltrefwoorden',
  'Target Audience (Optional)': 'Doelgroep (Optioneel)',
  'Enter your blog topic or title...': 'Voer je blogonderwerp of titel in...',
  'e.g., AI writing, content marketing, SEO tips':
      'bijv., AI schrijven, contentmarketing, SEO tips',
  'e.g., small business owners, bloggers':
      'bijv., kleine ondernemers, bloggers',
  'Article Type': 'Artikeltype',
  'Writing Tone': 'Schrijftoon',
  'Article Length': 'Artikellengte',
  'SEO Options': 'SEO Opties',
  'Include Meta Description': 'Inclusief Metabeschrijving',
  'Include Keyword Suggestions': 'Inclusief Trefwoordsuggesties',
  'Include FAQs Section': 'Inclusief FAQ Sectie',
  'Please enter a blog topic': 'Voer alstublieft een blogonderwerp in',
  'Generate Blog': 'Genereer Blog',
  'SEO optimized articles with keywords':
      'SEO-geoptimaliseerde artikelen met trefwoorden',
  'Write Blog': 'Schrijf Blog',
  'SEO Article': 'SEO Artikel',
  'How-To Guide': 'Handleiding',
  'Listicle': 'Lijstartikel',
  'Product Review': 'Productrecensie',
  'Opinion Piece': 'Opiniestuk',
  'News Article': 'Nieuwsartikel',
  'Professional': 'Professioneel',
  'Casual': 'Informeel',
  'Informative': 'Informatief',
  'Persuasive': 'Overtuigend',
  'Friendly': 'Vriendelijk',
  'Authoritative': 'Gezaghebbend',
  'Short (500-800)': 'Kort (500-800)',
  'Medium (800-1500)': 'Medium (800-1500)',
  'Long (1500-2500)': 'Lang (1500-2500)',
  'Detailed (2500+)': 'Gedetailleerd (2500+)',

  'YouTube Script': 'YouTube Script',
  'Script Type': 'Scripttype',
  'Video Topic': 'Video-onderwerp',
  'Key Points (Optional)': 'Kernpunten (Optioneel)',
  'What is your video about?': 'Waar gaat je video over?',
  'List key points to cover (optional)...':
      'Lijst kernpunten om te behandelen (optioneel)...',
  'Video Duration': 'Videoduur',
  'Script Tone': 'Scripttoon',
  'Script Options': 'Scriptopties',
  'Include Hook/Intro': 'Inclusief Hook/Intro',
  'Include Call-to-Action': 'Inclusief Call-to-Action',
  'Include Timestamps': 'Inclusief Tijdstempels',
  'Please enter a video topic': 'Voer alstublieft een video-onderwerp in',
  'Generate Script': 'Genereer Script',
  'Create scripts for videos & reels': 'Maak scripts voor videos en reels',
  'Create Script': 'Maak Script',
  'Storytime': 'Verhaaltijd',
  'Documentary': 'Documentaire',
  'Short Reel': 'Korte Reel',
  'Motivational': 'Motiverend',
  'Educational': 'Educatief',
  'Review': 'Recensie',
  'Tutorial': 'Tutorial',
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  'Engaging': 'Boeiend',
  'Energetic': 'Energiek',
  'Calm': 'Kalm',
  'Funny': 'Grappig',

  'Inspired': 'Geïnspireerd',
  'Standard': 'Standaard',
  'Imaginative': 'Fantasierijk',
  'Innovative': 'Innovatief',

  'Short Film': 'Korte Film',
  'Film Script': 'Filmscript',
  'Stage Play': 'Toneelstuk',
  'Advertisement': 'Advertentie',
  'Tiktok Video': 'Tiktok Video',
  'Movie': 'Film',
  'Scene Breakdown': 'Scène-uitsplitsing',
  'Dialogue Only': 'Alleen Dialoog',

  'Action': 'Actie',
  'Fairy Tale': 'Sprookje',

  'Ad loading please wait..': 'Advertentie wordt geladen, even geduld..',
  'Words:': 'Woorden:',
  'Reading:': 'Lezen:',
  "Character Story": "Karakterverhaal",
  "Create detailed character backstories":
      "Maak gedetailleerde achtergrondverhalen voor je personages",
  "Create Character": "Personage aanmaken",
  "Rewrite Story": "Verhaal herschrijven",
  "Paste Your Story": "Plak uw verhaal",
  "Paste your story here to rewrite...":
      "Plak hier uw verhaal om het te herschrijven...",
  "Transform and improve your existing stories":
      "Transformeer en verbeter uw bestaande verhalen",
  "Title Generator": "Titelgenerator",
  "Generate catchy titles for your stories":
      "Genereer pakkende titels voor uw verhalen",
  "Generate Titles": "Titels genereren",
  "Blog Writer": "Blogschrijver",
  "Blog Topic": "Blogonderwerp",
  "Target Keywords": "Doelzoekwoorden",
  "Target Audience (Optional)": "Doelgroep (Optioneel)",
  "Enter your blog topic or title...": "Voer uw blogonderwerp of titel in...",
  "e.g., AI writing, content marketing, SEO tips":
      "bijv. AI schrijven, contentmarketing, SEO-tips",
  "e.g., small business owners, bloggers":
      "bijv. eigenaren van kleine bedrijven, bloggers",
  "Article Type": "Artikeltype",
  "Writing Tone": "Schrijftoon",
  "Article Length": "Artikellengte",
  "SEO Options": "SEO-opties",
  "Include Meta Description": "Meta-beschrijving opnemen",
  "Include Keyword Suggestions": "Zoekwoordsuggesties opnemen",
  "Include FAQs Section": "FAQ-sectie opnemen",
  "Please enter a blog topic": "Voer een blogonderwerp in",
  "Generate Blog": "Blog genereren",
  "SEO optimized articles with keywords":
      "SEO-geoptimaliseerde artikelen met zoekwoorden",
  "Write Blog": "Blog schrijven",
  "YouTube Script": "YouTube-script",
  "Video Topic": "Video-onderwerp",
  "Key Points (Optional)": "Kernpunten (Optioneel)",
  "What is your video about?": "Waar gaat uw video over?",
  "List key points to cover (optional)...":
      "Geef de te behandelen kernpunten op (optioneel)...",
  "Video Duration": "Videoduur",
  "Script Options": "Scriptopties",
  "Include Hook/Intro": "Hook/intro opnemen",
  "Include Call-to-Action": "Oproep tot actie opnemen",
  "Include Timestamps": "Tijdstempels opnemen",
  "Please enter a video topic": "Voer een video-onderwerp in",
  "Generate Script": "Script genereren",
  "Create scripts for videos & reels": "Maak scripts voor video's en reels",
  "Create Script": "Script aanmaken",
  "Character Details": "Personagedetails",
  "Character Name": "Personagenaam",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Leeftijd (bijv. 25, Jongvolwassene, Oud)",
  "Personality (e.g., brave, shy, cunning)":
      "Persoonlijkheid (bijv. dapper, verlegen, slim)",
  "Role (e.g., Hero, Villain, Mentor)": "Rol (bijv. Held, Schurk, Mentor)",
  "Additional Details (optional)": "Extra details (optioneel)",
  "Output Style": "Uitvoerstijl",
  "Generate Character": "Personage genereren",
  "Please enter character name": "Voer de naam van het personage in",
  "Please enter character role": "Voer de rol van het personage in",
  "Detailed": "Gedetailleerd",
  "Brief": "Beknopt",
  "Elaborate": "Uitgebreid",
  "Select Tone": "Toon selecteren",
  "Rewrite Style": "Herschrijfstijl",
  "Output Length": "Uitvoerlengte",
  "Please paste your story": "Plak uw verhaal",
  "Story is too short. Please provide more content.":
      "Het verhaal is te kort. Geef meer inhoud.",
  "Same": "Hetzelfde",
  "More Dramatic": "Dramatischer",
  "More Humorous": "Humorvoller",
  "More Emotional": "Emotioneler",
  "More Suspenseful": "Spannender",
  "Lighter": "Lichter",
  "Improved": "Verbeterd",
  "Simplified": "Vereenvoudigd",
  "More Descriptive": "Beschrijvender",
  "More Dialogue": "Meer dialoog",
  "More Action": "Meer actie",
  "Literary": "Literair",
  "Shorter": "Korter",
  "Longer": "Langer",
  "Much Longer": "Veel langer",
  "Rewrite Now": "Nu herschrijven",
  "Story/Book Topic": "Verhaal-/boekonderwerp",
  "Keywords (Optional)": "Zoekwoorden (Optioneel)",
  "Describe your story topic or theme...":
      "Beschrijf uw verhaalonderwerp of thema...",
  "e.g., magic, dragon, adventure": "bijv. magie, draak, avontuur",
  "Title For": "Titel voor",
  "Title Style": "Titelstijl",
  "Number of Titles": "Aantal titels",
  "Book": "Boek",
  "Short Story": "Kort verhaal",
  "Novel": "Roman",
  "Chapter": "Hoofdstuk",
  "Series": "Reeks",
  "Simple": "Eenvoudig",
  "Mysterious": "Mysterieus",
  "Dramatic": "Dramatisch",
  "Catchy": "Pakkend",
  "Poetic": "Poëtisch",
  "Kids": "Kinderen",
  "SEO Article": "SEO-artikel",
  "How-To Guide": "Handleiding",
  "Listicle": "Lijstartikel",
  "Product Review": "Productrecensie",
  "Opinion Piece": "Opiniestuk",
  "News Article": "Nieuwsartikel",
  "Professional": "Professioneel",
  "Casual": "Informeel",
  "Informative": "Informatief",
  "Persuasive": "Overtuigend",
  "Friendly": "Vriendelijk",
  "Authoritative": "Gezaghebbend",
  "Short (500-800)": "Kort (500-800)",
  "Medium (800-1500)": "Gemiddeld (800-1500)",
  "Long (1500-2500)": "Lang (1500-2500)",
  "Detailed (2500+)": "Gedetailleerd (2500+)",
  "Storytime": "Verhaaltijd",
  "Documentary": "Documentaire",
  "Short Reel": "Korte reel",
  "Educational": "Educatief",
  "Review": "Recensie",
  "Tutorial": "Tutorial",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Boeiend",
  "Energetic": "Energiek",
  "Calm": "Kalm",
  "Funny": "Grappig",
  "Next": "Volgende",
  "Get Started": "Aan de slag",
  "Your tool for quick, high-quality essay writing":
      "Uw hulpmiddel voor snel en kwalitatief hoogwaardig schrijven",
};
