import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> no = {
  AppKeys.lblChooseLanguage: "Velg språk",
  "All": "Alle",
  "AI Story Generator": "AI-historiegenerator",
  "Story Generator": "Historiegenerator",
  "Essay Writer": "Essay-forfatter",
  "Essay length": "Essay-lengde",
  "Script Generator": "Manusgenerator",
  "Create original stories in seconds": "Lag originale historier på sekunder",
  "Academic writing made simple": "Akademisk skriving gjort enkelt",
  "Generate powerful scripts for any medium":
      "Generer kraftige manus for ethvert medium",
  "Start Writing": "Begynn å skrive",
  "Create Now": "Opprett nå",
  "Start Generating": "Start generering",
  "Your Stories": "Dine historier",
  "No stories yet": "Ingen historier ennå",
  "Start creating your first story!": "Begynn å lage din første historie!",
  "Your Story Space Awaits": "Ditt historie-rom venter",
  "Start your first story and see it appear here":
      "Start din første historie og se den vises her",
  "Language": "Språk",
  "Rate us": "Vurder oss",
  "Share us": "Del oss",
  "Privacy Policy": "Personvernregler",
  "Settings": "Innstillinger",
  "Select Language": "Velg språk",
  "Dashboard": "Kontrollpanel",
  "BENEFITS": "FORDELER",
  "Subscribe": "Abonner",
  "Weekly": "Ukentlig",
  "Monthly": "Månedlig",
  "Yearly": "Årlig",
  "week": "uke",
  "months": "måneder",
  "year": "år",
  "Terms & Condition": "Vilkår og betingelser",
  "No Commitment. Cancel anytime": "Ingen forpliktelse. Avbryt når som helst",
  "No Payment Now": "Ingen betaling nå",
  "3 days free": "3 dager gratis",
  "Start your free trial": "Start din gratis prøveperiode",
  "More detailed answers": "Mer detaljerte svar",
  "Instant responds": "Umiddelbare svar",
  "Text recognition": "Tekstgjenkjenning",
  "Powered by AI": "Drevet av AI",
  "Storytelleing": "Historiefortelling",
  ' Power': "Kraft",
  "Unlock your \nFill ": "Lås opp din \nFyll",
  "Your History": "Din historie",
  "Terms and Conditions": "Vilkår og betingelser",
  "Short": "Kort",
  "Medium": "Medium",
  "Long": "Lang",
  "Length": "Lengde",
  "Describe your topic...": "Beskriv emnet ditt...",
  "Set Creativity": "Sett kreativitet",
  "Standard": "Standard",
  "Creative": "Kreativ",
  "Complex": "Kompleks",
  "Select Genre": "Velg sjanger",
  "Fantasy": "Fantasy",
  "Mystery": "Mysterium",
  "Thriller": "Thriller",
  "Script Tone": "Manustone",
  "Script Type": "Manustype",
  "Comedy": "Komedie",
  "Drama": "Drama",
  "Horror": "Skrekk",
  "Action": "Action",
  "Romance": "Romantikk",
  "Go Premium": "Få Premium",
  "Unlock Everything": "Lås opp alt",
  "Unlimited Story Generation": "Ubegrenset historiegenerering",
  "Write Longer & Detailed Essays": "Skriv lengre og detaljerte essays",
  "Advanced Script Writer": "Avansert manusforfatter",
  "Unlock All Styles & Tones": "Lås opp alle stiler og toner",
  "No Word/Length Limit": "Ingen ord-/lengdegrense",
  "Remove All Ads": "Fjern alle annonser",
  "Restore": "Gjenopprett",
  "YouTube Video": "YouTube-video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motiverende",
  "Advertisement": "Reklame",
  "Fairy Tale": "Eventyr",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Velg stil",
  "Imaginative": "Fantasifull",
  "Innovative": "Innovativ",
  "AI Story Writer": "AI-historieforfatter",
  "Generate": "Generer",
  "Please wait...": "Vennligst vent...",
  "Result": "Resultat",
  "Regenerate": "Regenerer",
  "Download": "Last ned",
  "Text copied to clipboard!": "Tekst kopiert til utklippstavlen!",
  "Please enter a topic": "Vennligst skriv inn et emne",
  "Story Magic": "Historiemagi",
  "Let AI bring your thoughts to a full story":
      "La AI bringe tankene dine til en fullstendig historie",
  "Smart Scripts": "Smarte manus",
  "From concept to script—fast, easy, and creative":
      "Fra konsept til manus—raskt, enkelt og kreativt",
  "Perfect Essays": "Perfekte essays",
  "You have reached your free limit": "Du har nådd din gratis grense",
  "Donwload": "Last ned",
  "Press again to exit app": "Trykk igjen for å avslutte appen",
  "Saved to files": "TXT-fil lagret!",
  "Error: Please try again": "Feil: Vennligst prøv igjen",
  "Subscription expired": "Abonnement utløpt",
  "Purchase cancelled": "Kjøp kansellert",
  "Purchase failed": "Kjøp mislyktes",
  "Restore failed": "Gjenoppretting mislyktes",
  "Purchase Successful!": "Kjøp vellykket!",
  "Short (200-500 words)": "Kort (200-500 ord)",
  "Medium (500-1000 words)": "Medium (500-1000 ord)",
  "Large (1000+ words)": "Lang (1000+ ord)",
  "Academic Level": "Akademisk nivå",
  "Type of Paper": "Type papir",
  "High School": "Videregående skole",
  "College": "Høyskole",
  "Short Film": "Kortfilm",
  "University": "Universitet",
  "Masters": "Master",
  "Custom": "Tilpasset",
  "Tiktok Video": "Tiktok-video",
  "Movie": "Film",
  "Expository": "Forklarende",
  "Argumentative": "Argumenterende",
  "Narrative": "Fortellende",
  "Descriptive": "Beskrivende",
  "We're sorry to hear that 😔": "Vi beklager å høre det 😔",
  "We'll try to improve 🙁": "Vi skal prøve å forbedre oss 🙁",
  "Thanks for your feedback 🙂": "Takk for tilbakemeldingen 🙂",
  "Great! We're glad you like it 😊":
      "Flott! Vi er glade for at du liker det 😊",
  "Awesome! Thank you so much! 🎉": "Fantastisk! Tusen takk! 🎉",
  "Maybe Later": "Kanskje senere",
  "Tap a star to rate your experience":
      "Trykk på en stjerne for å vurdere opplevelsen din",
  "Enjoying AI Math Solver?": "Liker du AI Math Solver?",
  "Thank you for rating us": "Takk for at du vurderte oss",
  "Submit Rating": "Send inn vurdering",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Liker du AI Story Generator?",
  "Adventure": "Eventyr",
  "Inspired": "Inspirert",
  "Film Script": "Filmmanus",
  "Stage Play": "Scenestykke",
  "Scene Breakdown": "Sceneanalyse",
  "Dialogue Only": "Kun dialog",
  "Ad loading please wait..": "Annonse laster, vennligst vent...",
  "Words:": "Ord:",
  "Reading:": "Lesing:",

  AppKeys.arabic: "Arabisk",
  AppKeys.chinese: "Kinesisk",
  AppKeys.english: "Engelsk",
  AppKeys.french: "Fransk",
  AppKeys.german: "Tysk",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesisk",
  AppKeys.japanese: "Japansk",
  AppKeys.korean: "Koreansk",
  AppKeys.portuguese: "Portugisisk",
  AppKeys.russian: "Russisk",
  AppKeys.spanish: "Spansk",
  AppKeys.turkish: "Tyrkisk",

  // New strings for download & actions
  'Download As': 'Last ned som',
  'Choose format to download': 'Velg format for nedlasting',
  'Text File': 'Tekstfil',
  'PDF File': 'PDF-fil',
  'Copy': 'Kopier',
  'Share': 'Del',
  'Text copied!': 'Tekst kopiert!',
  'Copied to clipboard': 'Kopiert til utklippstavlen',
  'File saved successfully': 'Fil lagret',
  'Error saving file': 'Feil ved lagring av fil',
  'Share Story': 'Del historie',
  'Export': 'Eksporter',
  "Character Story": "Karakterhistorie",
  "Create detailed character backstories":
      "Lag detaljerte bakgrunnshistorier for karakterene dine",
  "Create Character": "Opprett karakter",
  "Rewrite Story": "Skriv om historien",
  "Paste Your Story": "Lim inn historien din",
  "Paste your story here to rewrite...":
      "Lim inn historien din her for å skrive den om...",
  "Transform and improve your existing stories":
      "Transformer og forbedre dine eksisterende historier",
  "Title Generator": "Titelgenerator",
  "Generate catchy titles for your stories":
      "Generer fengende titler til historiene dine",
  "Generate Titles": "Generer titler",
  "Blog Writer": "Bloggskribent",
  "Blog Topic": "Bloggemne",
  "Target Keywords": "Målnøkkelord",
  "Target Audience (Optional)": "Målgruppe (Valgfritt)",
  "Enter your blog topic or title...": "Skriv inn bloggemne eller tittel...",
  "e.g., AI writing, content marketing, SEO tips":
      "f.eks. AI-skriving, innholdsmarkedsføring, SEO-tips",
  "e.g., small business owners, bloggers": "f.eks. småbedriftseiere, bloggere",
  "Article Type": "Artikkeltype",
  "Writing Tone": "Skrivetone",
  "Article Length": "Artikkellengde",
  "SEO Options": "SEO-alternativer",
  "Include Meta Description": "Inkluder metabeskrivelse",
  "Include Keyword Suggestions": "Inkluder nøkkelordforslag",
  "Include FAQs Section": "Inkluder FAQ-seksjon",
  "Please enter a blog topic": "Skriv inn et bloggemne",
  "Generate Blog": "Generer blogg",
  "SEO optimized articles with keywords":
      "SEO-optimaliserte artikler med nøkkelord",
  "Write Blog": "Skriv blogg",
  "YouTube Script": "YouTube-manus",
  "Video Topic": "Videoemne",
  "Key Points (Optional)": "Nøkkelpunkter (Valgfritt)",
  "What is your video about?": "Hva handler videoen din om?",
  "List key points to cover (optional)...":
      "List opp nøkkelpunkter (valgfritt)...",
  "Video Duration": "Videovarighet",
  "Script Options": "Manusalternativer",
  "Include Hook/Intro": "Inkluder krok/intro",
  "Include Call-to-Action": "Inkluder oppfordring til handling",
  "Include Timestamps": "Inkluder tidsstempler",
  "Please enter a video topic": "Skriv inn et videoemne",
  "Generate Script": "Generer manus",
  "Create scripts for videos & reels": "Lag manus til videoer og reels",
  "Create Script": "Opprett manus",
  "Character Details": "Karakterdetaljer",
  "Character Name": "Karakternavn",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Alder (f.eks. 25, Ung voksen, Gammel)",
  "Personality (e.g., brave, shy, cunning)":
      "Personlighet (f.eks. modig, sjenert, listig)",
  "Role (e.g., Hero, Villain, Mentor)": "Rolle (f.eks. Helt, Skurk, Mentor)",
  "Additional Details (optional)": "Tilleggsdetaljer (valgfritt)",
  "Output Style": "Utdatastil",
  "Generate Character": "Generer karakter",
  "Please enter character name": "Skriv inn karakternavn",
  "Please enter character role": "Skriv inn karakterens rolle",
  "Detailed": "Detaljert",
  "Brief": "Kortfattet",
  "Elaborate": "Utdypet",
  "Select Tone": "Velg tone",
  "Rewrite Style": "Omskrivingsstil",
  "Output Length": "Utdatalengde",
  "Please paste your story": "Lim inn historien din",
  "Story is too short. Please provide more content.":
      "Historien er for kort. Gi mer innhold.",
  "Same": "Samme",
  "More Dramatic": "Mer dramatisk",
  "More Humorous": "Mer humoristisk",
  "More Emotional": "Mer emosjonell",
  "More Suspenseful": "Mer spent",
  "Lighter": "Lettere",
  "Improved": "Forbedret",
  "Simplified": "Forenklet",
  "More Descriptive": "Mer beskrivende",
  "More Dialogue": "Mer dialog",
  "More Action": "Mer handling",
  "Literary": "Litterær",
  "Shorter": "Kortere",
  "Longer": "Lengre",
  "Much Longer": "Mye lengre",
  "Rewrite Now": "Skriv om nå",
  "Story/Book Topic": "Historie-/boktema",
  "Keywords (Optional)": "Nøkkelord (Valgfritt)",
  "Describe your story topic or theme...":
      "Beskriv historiens tema eller motiv...",
  "e.g., magic, dragon, adventure": "f.eks. magi, drage, eventyr",
  "Title For": "Tittel for",
  "Title Style": "Titelstil",
  "Number of Titles": "Antall titler",
  "Book": "Bok",
  "Short Story": "Novelle",
  "Novel": "Roman",
  "Chapter": "Kapittel",
  "Series": "Serie",
  "Simple": "Enkel",
  "Mysterious": "Mystisk",
  "Dramatic": "Dramatisk",
  "Catchy": "Fengende",
  "Poetic": "Poetisk",
  "Kids": "Barn",
  "SEO Article": "SEO-artikkel",
  "How-To Guide": "Veiledning",
  "Listicle": "Listeartikkel",
  "Product Review": "Produktanmeldelse",
  "Opinion Piece": "Meningsartikkel",
  "News Article": "Nyhetsartikkel",
  "Professional": "Profesjonell",
  "Casual": "Uformell",
  "Informative": "Informativ",
  "Persuasive": "Overbevisende",
  "Friendly": "Vennlig",
  "Authoritative": "Autoritativ",
  "Short (500-800)": "Kort (500-800)",
  "Medium (800-1500)": "Middels (800-1500)",
  "Long (1500-2500)": "Lang (1500-2500)",
  "Detailed (2500+)": "Detaljert (2500+)",
  "Storytime": "Historiefortelling",
  "Documentary": "Dokumentar",
  "Short Reel": "Kort reel",
  "Educational": "Pedagogisk",
  "Review": "Anmeldelse",
  "Tutorial": "Veiledning",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Engasjerende",
  "Energetic": "Energisk",
  "Calm": "Rolig",
  "Funny": "Morsom",
  "Next": "Neste",
  "Get Started": "Kom i gang",
  "Your tool for quick, high-quality essay writing":
      "Verktøyet ditt for rask og høykvalitets essayskriving",
};
