import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> pa = {
  AppKeys.lblChooseLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
  "All": "ਸਾਰੇ",
  "AI Story Generator": "AI ਕਹਾਣੀ ਜਨਰੇਟਰ",
  "Story Generator": "ਕਹਾਣੀ ਜਨਰੇਟਰ",
  "Essay Writer": "ਲੇਖ ਲੇਖਕ",
  "Essay length": "ਲੇਖ ਦੀ ਲੰਬਾਈ",
  "Script Generator": "ਸਕ੍ਰਿਪਟ ਜਨਰੇਟਰ",
  "Create original stories in seconds": "ਸਕਿੰਟਾਂ ਵਿੱਚ ਅਸਲੀ ਕਹਾਣੀਆਂ ਬਣਾਓ",
  "Academic writing made simple": "ਅਕਾਦਮਿਕ ਲਿਖਤ ਸਰਲ ਬਣਾਈ",
  "Generate powerful scripts for any medium":
      "ਕਿਸੇ ਵੀ ਮੀਡੀਅਮ ਲਈ ਸ਼ਕਤੀਸ਼ਾਲੀ ਸਕ੍ਰਿਪਟਾਂ ਬਣਾਓ",
  "Start Writing": "ਲਿਖਣਾ ਸ਼ੁਰੂ ਕਰੋ",
  "Create Now": "ਹੁਣੇ ਬਣਾਓ",
  "Start Generating": "ਬਣਾਉਣਾ ਸ਼ੁਰੂ ਕਰੋ",
  "Your Stories": "ਤੁਹਾਡੀਆਂ ਕਹਾਣੀਆਂ",
  "No stories yet": "ਅਜੇ ਕੋਈ ਕਹਾਣੀਆਂ ਨਹੀਂ",
  "Start creating your first story!": "ਆਪਣੀ ਪਹਿਲੀ ਕਹਾਣੀ ਬਣਾਉਣਾ ਸ਼ੁਰੂ ਕਰੋ!",
  "Your Story Space Awaits": "ਤੁਹਾਡਾ ਕਹਾਣੀ ਸਪੇਸ ਉਡੀਕ ਰਿਹਾ ਹੈ",
  "Start your first story and see it appear here":
      "ਆਪਣੀ ਪਹਿਲੀ ਕਹਾਣੀ ਸ਼ੁਰੂ ਕਰੋ ਅਤੇ ਇਸਨੂੰ ਇੱਥੇ ਦੇਖੋ",
  "Language": "ਭਾਸ਼ਾ",
  "Rate us": "ਸਾਨੂੰ ਰੇਟ ਕਰੋ",
  "Share us": "ਸਾਨੂੰ ਸਾਂਝਾ ਕਰੋ",
  "Privacy Policy": "ਪ੍ਰਾਈਵੇਸੀ ਨੀਤੀ",
  "Settings": "ਸੈਟਿੰਗਜ਼",
  "Select Language": "ਭਾਸ਼ਾ ਚੁਣੋ",
  "Dashboard": "ਡੈਸ਼ਬੋਰਡ",
  "BENEFITS": "ਫਾਇਦੇ",
  "Subscribe": "ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ",
  "Weekly": "ਹਫ਼ਤਾਵਾਰੀ",
  "Monthly": "ਮਹੀਨਾਵਾਰ",
  "Yearly": "ਸਾਲਾਨਾ",
  "week": "ਹਫ਼ਤਾ",
  "months": "ਮਹੀਨੇ",
  "year": "ਸਾਲ",
  "Terms & Condition": "ਸ਼ਰਤਾਂ ਅਤੇ ਨਿਯਮ",
  "No Commitment. Cancel anytime": "ਕੋਈ ਵਚਨਬੱਧਤਾ ਨਹੀਂ। ਕਿਸੇ ਵੀ ਸਮੇਂ ਰੱਦ ਕਰੋ",
  "No Payment Now": "ਹੁਣ ਕੋਈ ਭੁਗਤਾਨ ਨਹੀਂ",
  "3 days free": "3 ਦਿਨ ਮੁਫ਼ਤ",
  "Start your free trial": "ਆਪਣਾ ਮੁਫ਼ਤ ਟ੍ਰਾਇਲ ਸ਼ੁਰੂ ਕਰੋ",
  "More detailed answers": "ਵਧੇਰੇ ਵਿਸਤ੍ਰਿਤ ਜਵਾਬ",
  "Instant responds": "ਤੁਰੰਤ ਜਵਾਬ",
  "Text recognition": "ਟੈਕਸਟ ਪਛਾਣ",
  "Powered by AI": "AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ",
  "Storytelleing": "ਕਹਾਣੀ ਸੁਣਾਉਣਾ",
  ' Power': "ਸ਼ਕਤੀ",
  "Unlock your \nFill ": "ਆਪਣਾ \nਭਰੋ ਅਨਲੌਕ ਕਰੋ",
  "Your History": "ਤੁਹਾਡਾ ਇਤਿਹਾਸ",
  "Terms and Conditions": "ਸ਼ਰਤਾਂ ਅਤੇ ਨਿਯਮ",
  "Short": "ਛੋਟਾ",
  "Medium": "ਮੱਧਮ",
  "Long": "ਲੰਬਾ",
  "Length": "ਲੰਬਾਈ",
  "Describe your topic...": "ਆਪਣੇ ਵਿਸ਼ੇ ਦਾ ਵਰਣਨ ਕਰੋ...",
  "Set Creativity": "ਸਿਰਜਣਾਤਮਕਤਾ ਸੈੱਟ ਕਰੋ",
  "Standard": "ਸਟੈਂਡਰਡ",
  "Creative": "ਸਿਰਜਣਾਤਮਕ",
  "Complex": "ਜਟਿਲ",
  "Select Genre": "ਸ਼ੈਲੀ ਚੁਣੋ",
  "Fantasy": "ਕਲਪਨਾ",
  "Mystery": "ਰਹੱਸ",
  "Thriller": "ਥ੍ਰਿਲਰ",
  "Script Tone": "ਸਕ੍ਰਿਪਟ ਟੋਨ",
  "Script Type": "ਸਕ੍ਰਿਪਟ ਕਿਸਮ",
  "Comedy": "ਕਾਮੇਡੀ",
  "Drama": "ਡਰਾਮਾ",
  "Horror": "ਡਰਾਉਣਾ",
  "Action": "ਐਕਸ਼ਨ",
  "Romance": "ਰੋਮਾਂਸ",
  "Go Premium": "ਪ੍ਰੀਮੀਅਮ ਲਵੋ",
  "Unlock Everything": "ਸਭ ਕੁਝ ਅਨਲੌਕ ਕਰੋ",
  "Unlimited Story Generation": "ਅਸੀਮਿਤ ਕਹਾਣੀ ਬਣਾਉਣਾ",
  "Write Longer & Detailed Essays": "ਲੰਬੇ ਅਤੇ ਵਿਸਤ੍ਰਿਤ ਲੇਖ ਲਿਖੋ",
  "Advanced Script Writer": "ਉੱਨਤ ਸਕ੍ਰਿਪਟ ਲੇਖਕ",
  "Unlock All Styles & Tones": "ਸਾਰੀਆਂ ਸ਼ੈਲੀਆਂ ਅਤੇ ਟੋਨ ਅਨਲੌਕ ਕਰੋ",
  "No Word/Length Limit": "ਕੋਈ ਸ਼ਬਦ/ਲੰਬਾਈ ਸੀਮਾ ਨਹੀਂ",
  "Remove All Ads": "ਸਾਰੇ ਇਸ਼ਤਿਹਾਰ ਹਟਾਓ",
  "Restore": "ਰੀਸਟੋਰ ਕਰੋ",
  "YouTube Video": "YouTube ਵੀਡੀਓ",
  "Podcast": "ਪੋਡਕਾਸਟ",
  "Reel": "ਰੀਲ",
  "Motivational": "ਪ੍ਰੇਰਣਾਦਾਇਕ",
  "Advertisement": "ਇਸ਼ਤਿਹਾਰ",
  "Fairy Tale": "ਪਰੀ ਕਹਾਣੀ",
  "Sci-Fi": "ਵਿਗਿਆਨ ਗਲਪ",
  "Select Style": "ਸ਼ੈਲੀ ਚੁਣੋ",
  "Imaginative": "ਕਲਪਨਾਸ਼ੀਲ",
  "Innovative": "ਨਵੀਨਤਾਕਾਰੀ",
  "AI Story Writer": "AI ਕਹਾਣੀ ਲੇਖਕ",
  "Generate": "ਬਣਾਓ",
  "Please wait...": "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
  "Result": "ਨਤੀਜਾ",
  "Regenerate": "ਦੁਬਾਰਾ ਬਣਾਓ",
  "Download": "ਡਾਊਨਲੋਡ ਕਰੋ",
  "Text copied to clipboard!": "ਟੈਕਸਟ ਕਲਿੱਪਬੋਰਡ 'ਤੇ ਕਾਪੀ ਹੋਇਆ!",
  "Please enter a topic": "ਕਿਰਪਾ ਕਰਕੇ ਵਿਸ਼ਾ ਦਰਜ ਕਰੋ",
  "Story Magic": "ਕਹਾਣੀ ਜਾਦੂ",
  "Let AI bring your thoughts to a full story":
      "AI ਨੂੰ ਆਪਣੇ ਵਿਚਾਰਾਂ ਨੂੰ ਪੂਰੀ ਕਹਾਣੀ ਵਿੱਚ ਲਿਆਉਣ ਦਿਓ",
  "Smart Scripts": "ਸਮਾਰਟ ਸਕ੍ਰਿਪਟਾਂ",
  "From concept to script—fast, easy, and creative":
      "ਧਾਰਨਾ ਤੋਂ ਸਕ੍ਰਿਪਟ ਤੱਕ—ਤੇਜ਼, ਆਸਾਨ, ਅਤੇ ਸਿਰਜਣਾਤਮਕ",
  "Perfect Essays": "ਸੰਪੂਰਨ ਲੇਖ",
  "You have reached your free limit": "ਤੁਸੀਂ ਆਪਣੀ ਮੁਫ਼ਤ ਸੀਮਾ 'ਤੇ ਪਹੁੰਚ ਗਏ ਹੋ",
  "Donwload": "ਡਾਊਨਲੋਡ ਕਰੋ",
  "Press again to exit app": "ਐਪ ਤੋਂ ਬਾਹਰ ਆਉਣ ਲਈ ਦੁਬਾਰਾ ਦਬਾਓ",
  "Saved to files": "TXT ਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਹੋਈ!",
  "Error: Please try again": "ਗਲਤੀ: ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
  "Subscription expired": "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਖਤਮ ਹੋ ਗਈ",
  "Purchase cancelled": "ਖਰੀਦ ਰੱਦ ਕੀਤੀ ਗਈ",
  "Purchase failed": "ਖਰੀਦ ਅਸਫਲ ਰਹੀ",
  "Restore failed": "ਰੀਸਟੋਰ ਅਸਫਲ ਰਿਹਾ",
  "Purchase Successful!": "ਖਰੀਦ ਸਫਲ!",
  "Short (200-500 words)": "ਛੋਟਾ (200-500 ਸ਼ਬਦ)",
  "Medium (500-1000 words)": "ਮੱਧਮ (500-1000 ਸ਼ਬਦ)",
  "Large (1000+ words)": "ਵੱਡਾ (1000+ ਸ਼ਬਦ)",
  "Academic Level": "ਅਕਾਦਮਿਕ ਪੱਧਰ",
  "Type of Paper": "ਪੇਪਰ ਦੀ ਕਿਸਮ",
  "High School": "ਹਾਈ ਸਕੂਲ",
  "College": "ਕਾਲਜ",
  "Short Film": "ਛੋਟੀ ਫਿਲਮ",
  "University": "ਯੂਨੀਵਰਸਿਟੀ",
  "Masters": "ਮਾਸਟਰਜ਼",
  "Custom": "ਕਸਟਮ",
  "Tiktok Video": "Tiktok ਵੀਡੀਓ",
  "Movie": "ਫਿਲਮ",
  "Expository": "ਵਿਆਖਿਆਤਮਕ",
  "Argumentative": "ਦਲੀਲਬਾਜ਼",
  "Narrative": "ਬਿਰਤਾਂਤਕ",
  "Descriptive": "ਵਰਣਨਾਤਮਕ",
  "We're sorry to hear that 😔": "ਸਾਨੂੰ ਇਹ ਸੁਣ ਕੇ ਅਫ਼ਸੋਸ ਹੈ 😔",
  "We'll try to improve 🙁": "ਅਸੀਂ ਸੁਧਾਰ ਕਰਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰਾਂਗੇ 🙁",
  "Thanks for your feedback 🙂": "ਤੁਹਾਡੀ ਫੀਡਬੈਕ ਲਈ ਧੰਨਵਾਦ 🙂",
  "Great! We're glad you like it 😊":
      "ਵਧੀਆ! ਸਾਨੂੰ ਖੁਸ਼ੀ ਹੈ ਕਿ ਤੁਹਾਨੂੰ ਪਸੰਦ ਆਈ 😊",
  "Awesome! Thank you so much! 🎉": "ਸ਼ਾਨਦਾਰ! ਬਹੁਤ ਧੰਨਵਾਦ! 🎉",
  "Maybe Later": "ਸ਼ਾਇਦ ਬਾਅਦ ਵਿੱਚ",
  "Tap a star to rate your experience":
      "ਆਪਣੇ ਤਜ਼ਰਬੇ ਨੂੰ ਰੇਟ ਕਰਨ ਲਈ ਸਟਾਰ 'ਤੇ ਟੈਪ ਕਰੋ",
  "Enjoying AI Math Solver?": "AI Math Solver ਪਸੰਦ ਆ ਰਿਹਾ ਹੈ?",
  "Thank you for rating us": "ਸਾਨੂੰ ਰੇਟ ਕਰਨ ਲਈ ਧੰਨਵਾਦ",
  "Submit Rating": "ਰੇਟਿੰਗ ਜਮ੍ਹਾਂ ਕਰੋ",
  "Hindi": "ਹਿੰਦੀ",
  "Enjoying AI Story Generator?": "AI Story Generator ਪਸੰਦ ਆ ਰਿਹਾ ਹੈ?",
  "Adventure": "ਸਾਹਸ",
  "Inspired": "ਪ੍ਰੇਰਿਤ",
  "Film Script": "ਫਿਲਮ ਸਕ੍ਰਿਪਟ",
  "Stage Play": "ਸਟੇਜ ਪਲੇ",
  "Scene Breakdown": "ਸੀਨ ਵਿਸ਼ਲੇਸ਼ਣ",
  "Dialogue Only": "ਸਿਰਫ਼ ਸੰਵਾਦ",
  "Ad loading please wait..": "ਇਸ਼ਤਿਹਾਰ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ, ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
  "Words:": "ਸ਼ਬਦ:",
  "Reading:": "ਪੜ੍ਹਨਾ:",

  AppKeys.arabic: "ਅਰਬੀ",
  AppKeys.chinese: "ਚੀਨੀ",
  AppKeys.english: "ਅੰਗਰੇਜ਼ੀ",
  AppKeys.french: "ਫ੍ਰੈਂਚ",
  AppKeys.german: "ਜਰਮਨ",
  AppKeys.hindi: "ਹਿੰਦੀ",
  AppKeys.indonesian: "ਇੰਡੋਨੇਸ਼ੀਆਈ",
  AppKeys.japanese: "ਜਾਪਾਨੀ",
  AppKeys.korean: "ਕੋਰੀਆਈ",
  AppKeys.portuguese: "ਪੁਰਤਗਾਲੀ",
  AppKeys.russian: "ਰੂਸੀ",
  AppKeys.spanish: "ਸਪੈਨਿਸ਼",
  AppKeys.turkish: "ਤੁਰਕੀ",

  // New strings for download & actions
  'Download As': 'ਡਾਊਨਲੋਡ ਕਰੋ',
  'Choose format to download': 'ਡਾਊਨਲੋਡ ਲਈ ਫਾਰਮੈਟ ਚੁਣੋ',
  'Text File': 'ਟੈਕਸਟ ਫਾਈਲ',
  'PDF File': 'PDF ਫਾਈਲ',
  'Copy': 'ਕਾਪੀ ਕਰੋ',
  'Share': 'ਸਾਂਝਾ ਕਰੋ',
  'Text copied!': 'ਟੈਕਸਟ ਕਾਪੀ ਹੋਇਆ!',
  'Copied to clipboard': 'ਕਲਿੱਪਬੋਰਡ ਤੇ ਕਾਪੀ ਹੋਇਆ',
  'File saved successfully': 'ਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਹੋਈ',
  'Error saving file': 'ਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰਨ ਵਿੱਚ ਗਲਤੀ',
  'Share Story': 'ਕਹਾਣੀ ਸਾਂਝਾ ਕਰੋ',
  'Export': 'ਨਿਰਯਾਤ ਕਰੋ',

  "Character Story": "ਪਾਤਰ ਦੀ ਕਹਾਣੀ",
  "Create detailed character backstories": "ਪਾਤਰ ਦੀ ਵਿਸਤ੍ਰਿਤ ਪਿਛੋਕੜ ਕਹਾਣੀ ਬਣਾਓ",
  "Create Character": "ਪਾਤਰ ਬਣਾਓ",
  "Rewrite Story": "ਕਹਾਣੀ ਦੁਬਾਰਾ ਲਿਖੋ",
  "Paste Your Story": "ਆਪਣੀ ਕਹਾਣੀ ਪੇਸਟ ਕਰੋ",
  "Paste your story here to rewrite...":
      "ਦੁਬਾਰਾ ਲਿਖਣ ਲਈ ਆਪਣੀ ਕਹਾਣੀ ਇੱਥੇ ਪੇਸਟ ਕਰੋ...",
  "Transform and improve your existing stories":
      "ਆਪਣੀਆਂ ਮੌਜੂਦਾ ਕਹਾਣੀਆਂ ਨੂੰ ਬਦਲੋ ਅਤੇ ਸੁਧਾਰੋ",
  "Title Generator": "ਸਿਰਲੇਖ ਜਨਰੇਟਰ",
  "Generate catchy titles for your stories":
      "ਆਪਣੀਆਂ ਕਹਾਣੀਆਂ ਲਈ ਆਕਰਸ਼ਕ ਸਿਰਲੇਖ ਬਣਾਓ",
  "Generate Titles": "ਸਿਰਲੇਖ ਬਣਾਓ",
  "Blog Writer": "ਬਲੌਗ ਲੇਖਕ",
  "Blog Topic": "ਬਲੌਗ ਵਿਸ਼ਾ",
  "Target Keywords": "ਟੀਚਾ ਕੀਵਰਡ",
  "Target Audience (Optional)": "ਟੀਚਾ ਦਰਸ਼ਕ (ਵਿਕਲਪਿਕ)",
  "Enter your blog topic or title...": "ਆਪਣਾ ਬਲੌਗ ਵਿਸ਼ਾ ਜਾਂ ਸਿਰਲੇਖ ਦਰਜ ਕਰੋ...",
  "e.g., AI writing, content marketing, SEO tips":
      "ਉਦਾ., AI ਲਿਖਾਈ, ਸਮੱਗਰੀ ਮਾਰਕੀਟਿੰਗ, SEO ਸੁਝਾਅ",
  "e.g., small business owners, bloggers": "ਉਦਾ., ਛੋਟੇ ਕਾਰੋਬਾਰ ਮਾਲਕ, ਬਲੌਗਰ",
  "Article Type": "ਲੇਖ ਦੀ ਕਿਸਮ",
  "Writing Tone": "ਲਿਖਾਈ ਦਾ ਟੋਨ",
  "Article Length": "ਲੇਖ ਦੀ ਲੰਬਾਈ",
  "SEO Options": "SEO ਵਿਕਲਪ",
  "Include Meta Description": "ਮੇਟਾ ਵੇਰਵਾ ਸ਼ਾਮਲ ਕਰੋ",
  "Include Keyword Suggestions": "ਕੀਵਰਡ ਸੁਝਾਅ ਸ਼ਾਮਲ ਕਰੋ",
  "Include FAQs Section": "FAQ ਭਾਗ ਸ਼ਾਮਲ ਕਰੋ",
  "Please enter a blog topic": "ਕਿਰਪਾ ਕਰਕੇ ਬਲੌਗ ਵਿਸ਼ਾ ਦਰਜ ਕਰੋ",
  "Generate Blog": "ਬਲੌਗ ਬਣਾਓ",
  "SEO optimized articles with keywords": "ਕੀਵਰਡਾਂ ਨਾਲ SEO ਅਨੁਕੂਲਿਤ ਲੇਖ",
  "Write Blog": "ਬਲੌਗ ਲਿਖੋ",
  "YouTube Script": "YouTube ਸਕ੍ਰਿਪਟ",
  "Video Topic": "ਵੀਡੀਓ ਵਿਸ਼ਾ",
  "Key Points (Optional)": "ਮੁੱਖ ਨੁਕਤੇ (ਵਿਕਲਪਿਕ)",
  "What is your video about?": "ਤੁਹਾਡੀ ਵੀਡੀਓ ਕਿਸ ਬਾਰੇ ਹੈ?",
  "List key points to cover (optional)...":
      "ਸ਼ਾਮਲ ਕਰਨ ਦੇ ਮੁੱਖ ਨੁਕਤੇ ਸੂਚੀਬੱਧ ਕਰੋ (ਵਿਕਲਪਿਕ)...",
  "Video Duration": "ਵੀਡੀਓ ਦੀ ਮਿਆਦ",
  "Script Options": "ਸਕ੍ਰਿਪਟ ਵਿਕਲਪ",
  "Include Hook/Intro": "ਹੁੱਕ/ਜਾਣ-ਪਛਾਣ ਸ਼ਾਮਲ ਕਰੋ",
  "Include Call-to-Action": "ਕਾਰਵਾਈ ਲਈ ਸੱਦਾ ਸ਼ਾਮਲ ਕਰੋ",
  "Include Timestamps": "ਟਾਈਮਸਟੈਂਪ ਸ਼ਾਮਲ ਕਰੋ",
  "Please enter a video topic": "ਕਿਰਪਾ ਕਰਕੇ ਵੀਡੀਓ ਵਿਸ਼ਾ ਦਰਜ ਕਰੋ",
  "Generate Script": "ਸਕ੍ਰਿਪਟ ਬਣਾਓ",
  "Create scripts for videos & reels": "ਵੀਡੀਓ ਅਤੇ ਰੀਲਾਂ ਲਈ ਸਕ੍ਰਿਪਟ ਬਣਾਓ",
  "Create Script": "ਸਕ੍ਰਿਪਟ ਬਣਾਓ",
  "Character Details": "ਪਾਤਰ ਦੇ ਵੇਰਵੇ",
  "Character Name": "ਪਾਤਰ ਦਾ ਨਾਮ",
  "Age (e.g., 25, Young Adult, Ancient)": "ਉਮਰ (ਉਦਾ., 25, ਜਵਾਨ, ਪੁਰਾਣਾ)",
  "Personality (e.g., brave, shy, cunning)":
      "ਸ਼ਖਸੀਅਤ (ਉਦਾ., ਬਹਾਦਰ, ਸ਼ਰਮੀਲਾ, ਚਾਲਾਕ)",
  "Role (e.g., Hero, Villain, Mentor)":
      "ਭੂਮਿਕਾ (ਉਦਾ., ਨਾਇਕ, ਖਲਨਾਇਕ, ਮਾਰਗਦਰਸ਼ਕ)",
  "Additional Details (optional)": "ਵਾਧੂ ਵੇਰਵੇ (ਵਿਕਲਪਿਕ)",
  "Output Style": "ਆਉਟਪੁੱਟ ਸ਼ੈਲੀ",
  "Generate Character": "ਪਾਤਰ ਬਣਾਓ",
  "Please enter character name": "ਕਿਰਪਾ ਕਰਕੇ ਪਾਤਰ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ",
  "Please enter character role": "ਕਿਰਪਾ ਕਰਕੇ ਪਾਤਰ ਦੀ ਭੂਮਿਕਾ ਦਰਜ ਕਰੋ",
  "Detailed": "ਵਿਸਤ੍ਰਿਤ",
  "Brief": "ਸੰਖੇਪ",
  "Elaborate": "ਵਿਸਤ੍ਰਿਤ",
  "Select Tone": "ਟੋਨ ਚੁਣੋ",
  "Rewrite Style": "ਦੁਬਾਰਾ ਲਿਖਣ ਦੀ ਸ਼ੈਲੀ",
  "Output Length": "ਆਉਟਪੁੱਟ ਦੀ ਲੰਬਾਈ",
  "Please paste your story": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਕਹਾਣੀ ਪੇਸਟ ਕਰੋ",
  "Story is too short. Please provide more content.":
      "ਕਹਾਣੀ ਬਹੁਤ ਛੋਟੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਸਮੱਗਰੀ ਦਿਓ।",
  "Same": "ਉਹੀ",
  "More Dramatic": "ਵਧੇਰੇ ਨਾਟਕੀ",
  "More Humorous": "ਵਧੇਰੇ ਹਾਸਰਸ",
  "More Emotional": "ਵਧੇਰੇ ਭਾਵਨਾਤਮਕ",
  "More Suspenseful": "ਵਧੇਰੇ ਰੋਮਾਂਚਕ",
  "Lighter": "ਹਲਕਾ",
  "Improved": "ਸੁਧਰਿਆ",
  "Simplified": "ਸਰਲੀਕ੍ਰਿਤ",
  "More Descriptive": "ਵਧੇਰੇ ਵਰਣਨਾਤਮਕ",
  "More Dialogue": "ਵਧੇਰੇ ਸੰਵਾਦ",
  "More Action": "ਵਧੇਰੇ ਕਿਰਿਆ",
  "Literary": "ਸਾਹਿਤਕ",
  "Shorter": "ਛੋਟਾ",
  "Longer": "ਲੰਬਾ",
  "Much Longer": "ਬਹੁਤ ਲੰਬਾ",
  "Rewrite Now": "ਹੁਣੇ ਦੁਬਾਰਾ ਲਿਖੋ",
  "Story/Book Topic": "ਕਹਾਣੀ/ਕਿਤਾਬ ਵਿਸ਼ਾ",
  "Keywords (Optional)": "ਕੀਵਰਡ (ਵਿਕਲਪਿਕ)",
  "Describe your story topic or theme...":
      "ਆਪਣੀ ਕਹਾਣੀ ਦਾ ਵਿਸ਼ਾ ਜਾਂ ਥੀਮ ਦੱਸੋ...",
  "e.g., magic, dragon, adventure": "ਉਦਾ., ਜਾਦੂ, ਅਜਗਰ, ਸਾਹਸ",
  "Title For": "ਸਿਰਲੇਖ",
  "Title Style": "ਸਿਰਲੇਖ ਸ਼ੈਲੀ",
  "Number of Titles": "ਸਿਰਲੇਖਾਂ ਦੀ ਗਿਣਤੀ",
  "Book": "ਕਿਤਾਬ",
  "Short Story": "ਛੋਟੀ ਕਹਾਣੀ",
  "Novel": "ਨਾਵਲ",
  "Chapter": "ਅਧਿਆਇ",
  "Series": "ਲੜੀ",
  "Simple": "ਸਰਲ",
  "Mysterious": "ਰਹੱਸਮਈ",
  "Dramatic": "ਨਾਟਕੀ",
  "Catchy": "ਆਕਰਸ਼ਕ",
  "Poetic": "ਕਾਵਿਕ",
  "Kids": "ਬੱਚੇ",
  "SEO Article": "SEO ਲੇਖ",
  "How-To Guide": "ਕਿਵੇਂ ਕਰਨਾ ਗਾਈਡ",
  "Listicle": "ਸੂਚੀ ਲੇਖ",
  "Product Review": "ਉਤਪਾਦ ਸਮੀਖਿਆ",
  "Opinion Piece": "ਰਾਏ ਲੇਖ",
  "News Article": "ਖਬਰ ਲੇਖ",
  "Professional": "ਪੇਸ਼ੇਵਰ",
  "Casual": "ਅਨੌਪਚਾਰਿਕ",
  "Informative": "ਜਾਣਕਾਰੀਪੂਰਨ",
  "Persuasive": "ਮਨਾਉਣ ਵਾਲਾ",
  "Friendly": "ਦੋਸਤਾਨਾ",
  "Authoritative": "ਅਧਿਕਾਰਕ",
  "Short (500-800)": "ਛੋਟਾ (500-800)",
  "Medium (800-1500)": "ਦਰਮਿਆਨਾ (800-1500)",
  "Long (1500-2500)": "ਲੰਬਾ (1500-2500)",
  "Detailed (2500+)": "ਵਿਸਤ੍ਰਿਤ (2500+)",
  "Storytime": "ਕਹਾਣੀ ਸਮਾਂ",
  "Documentary": "ਦਸਤਾਵੇਜ਼ੀ",
  "Short Reel": "ਛੋਟੀ ਰੀਲ",
  "Educational": "ਵਿੱਦਿਅਕ",
  "Review": "ਸਮੀਖਿਆ",
  "Tutorial": "ਟਿਊਟੋਰਿਅਲ",
  "< 1 min (Shorts)": "< 1 ਮਿੰਟ (ਛੋਟੇ)",
  "1-3 min": "1-3 ਮਿੰਟ",
  "5-10 min": "5-10 ਮਿੰਟ",
  "10-20 min": "10-20 ਮਿੰਟ",
  "20+ min": "20+ ਮਿੰਟ",
  "Engaging": "ਦਿਲਚਸਪ",
  "Energetic": "ਊਰਜਾਵਾਨ",
  "Calm": "ਸ਼ਾਂਤ",
  "Funny": "ਮਜ਼ੇਦਾਰ",
  "Next": "ਅਗਲਾ",
  "Get Started": "ਸ਼ੁਰੂ ਕਰੋ",
  "Your tool for quick, high-quality essay writing":
      "ਤੇਜ਼ ਅਤੇ ਉੱਚ-ਗੁਣਵੱਤਾ ਵਾਲੀ ਲੇਖ ਲਿਖਾਈ ਲਈ ਤੁਹਾਡਾ ਸਾਧਨ",
};
