import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> pl = {
  AppKeys.lblChooseLanguage: "Wybierz język",
  "All": "Wszystko",
  "AI Story Generator": "Generator opowieści AI",
  "Story Generator": "Generator opowieści",
  "Essay Writer": "Pisarz esejów",
  "Essay length": "Długość eseju",
  "Script Generator": "Generator scenariuszy",
  "Create original stories in seconds":
      "Twórz oryginalne historie w kilka sekund",
  "Academic writing made simple": "Pisanie akademickie uproszczone",
  "Generate powerful scripts for any medium":
      "Generuj potężne scenariusze dla dowolnego medium",
  "Start Writing": "Zacznij pisać",
  "Create Now": "Stwórz teraz",
  "Start Generating": "Zacznij generować",
  "Your Stories": "Twoje historie",
  "No stories yet": "Brak historii",
  "Start creating your first story!":
      "Zacznij tworzyć swoją pierwszą historię!",
  "Your Story Space Awaits": "Twoja przestrzeń na historie czeka",
  "Start your first story and see it appear here":
      "Rozpocznij swoją pierwszą historię i zobacz ją tutaj",
  "Language": "Język",
  "Rate us": "Oceń nas",
  "Share us": "Udostępnij nas",
  "Privacy Policy": "Polityka prywatności",
  "Settings": "Ustawienia",
  "Select Language": "Wybierz język",
  "Dashboard": "Panel",
  "BENEFITS": "KORZYŚCI",
  "Subscribe": "Subskrybuj",
  "Weekly": "Tygodniowo",
  "Monthly": "Miesięcznie",
  "Yearly": "Rocznie",
  "week": "tydzień",
  "months": "miesiące",
  "year": "rok",
  "Terms & Condition": "Warunki i zasady",
  "No Commitment. Cancel anytime": "Bez zobowiązań. Anuluj w dowolnym momencie",
  "No Payment Now": "Bez płatności teraz",
  "3 days free": "3 dni za darmo",
  "Start your free trial": "Rozpocznij bezpłatny okres próbny",
  "More detailed answers": "Bardziej szczegółowe odpowiedzi",
  "Instant responds": "Natychmiastowe odpowiedzi",
  "Text recognition": "Rozpoznawanie tekstu",
  "Powered by AI": "Napędzane przez AI",
  "Storytelleing": "Opowiadanie historii",
  ' Power': "Moc",
  "Unlock your \nFill ": "Odblokuj swoją \nWypełnij",
  "Your History": "Twoja historia",
  "Terms and Conditions": "Warunki i zasady",
  "Short": "Krótki",
  "Medium": "Średni",
  "Long": "Długi",
  "Length": "Długość",
  "Describe your topic...": "Opisz swój temat...",
  "Set Creativity": "Ustaw kreatywność",
  "Standard": "Standardowy",
  "Creative": "Kreatywny",
  "Complex": "Złożony",
  "Select Genre": "Wybierz gatunek",
  "Fantasy": "Fantasy",
  "Mystery": "Tajemnica",
  "Thriller": "Thriller",
  "Script Tone": "Ton scenariusza",
  "Script Type": "Typ scenariusza",
  "Comedy": "Komedia",
  "Drama": "Dramat",
  "Horror": "Horror",
  "Action": "Akcja",
  "Romance": "Romans",
  "Go Premium": "Przejdź na Premium",
  "Unlock Everything": "Odblokuj wszystko",
  "Unlimited Story Generation": "Nieograniczone generowanie historii",
  "Write Longer & Detailed Essays": "Pisz dłuższe i bardziej szczegółowe eseje",
  "Advanced Script Writer": "Zaawansowany pisarz scenariuszy",
  "Unlock All Styles & Tones": "Odblokuj wszystkie style i tony",
  "No Word/Length Limit": "Bez limitu słów/długości",
  "Remove All Ads": "Usuń wszystkie reklamy",
  "Restore": "Przywróć",
  "YouTube Video": "Wideo YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motywacyjny",
  "Advertisement": "Reklama",
  "Fairy Tale": "Bajka",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Wybierz styl",
  "Imaginative": "Wyobraźniowy",
  "Innovative": "Innowacyjny",
  "AI Story Writer": "Pisarz historii AI",
  "Generate": "Generuj",
  "Please wait...": "Proszę czekać...",
  "Result": "Wynik",
  "Regenerate": "Regeneruj",
  "Download": "Pobierz",
  "Text copied to clipboard!": "Tekst skopiowany do schowka!",
  "Please enter a topic": "Proszę wprowadzić temat",
  "Story Magic": "Magia historii",
  "Let AI bring your thoughts to a full story":
      "Pozwól AI przekształcić twoje myśli w pełną historię",
  "Smart Scripts": "Inteligentne scenariusze",
  "From concept to script—fast, easy, and creative":
      "Od koncepcji do scenariusza—szybko, łatwo i kreatywnie",
  "Perfect Essays": "Doskonałe eseje",
  "You have reached your free limit": "Osiągnąłeś swój bezpłatny limit",
  "Donwload": "Pobierz",
  "Press again to exit app": "Naciśnij ponownie, aby wyjść z aplikacji",
  "Saved to files": "Plik TXT zapisany pomyślnie!",
  "Error: Please try again": "Błąd: Spróbuj ponownie",
  "Subscription expired": "Subskrypcja wygasła",
  "Purchase cancelled": "Zakup anulowany",
  "Purchase failed": "Zakup nieudany",
  "Restore failed": "Przywracanie nieudane",
  "Purchase Successful!": "Zakup udany!",
  "Short (200-500 words)": "Krótki (200-500 słów)",
  "Medium (500-1000 words)": "Średni (500-1000 słów)",
  "Large (1000+ words)": "Duży (1000+ słów)",
  "Academic Level": "Poziom akademicki",
  "Type of Paper": "Typ pracy",
  "High School": "Liceum",
  "College": "Uczelnia",
  "Short Film": "Film krótkometrażowy",
  "University": "Uniwersytet",
  "Masters": "Magisterskie",
  "Custom": "Niestandardowy",
  "Tiktok Video": "Wideo Tiktok",
  "Movie": "Film",
  "Expository": "Wyjaśniający",
  "Argumentative": "Argumentacyjny",
  "Narrative": "Narracyjny",
  "Descriptive": "Opisowy",
  "We're sorry to hear that 😔": "Przykro nam to słyszeć 😔",
  "We'll try to improve 🙁": "Postaramy się poprawić 🙁",
  "Thanks for your feedback 🙂": "Dziękujemy za opinię 🙂",
  "Great! We're glad you like it 😊":
      "Świetnie! Cieszymy się, że ci się podoba 😊",
  "Awesome! Thank you so much! 🎉": "Niesamowite! Bardzo dziękujemy! 🎉",
  "Maybe Later": "Może później",
  "Tap a star to rate your experience":
      "Dotknij gwiazdkę, aby ocenić swoje doświadczenie",
  "Enjoying AI Math Solver?": "Podoba ci się AI Math Solver?",
  "Thank you for rating us": "Dziękujemy za ocenę",
  "Submit Rating": "Prześlij ocenę",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Podoba ci się AI Story Generator?",
  "Adventure": "Przygoda",
  "Inspired": "Zainspirowany",
  "Film Script": "Scenariusz filmowy",
  "Stage Play": "Sztuka sceniczna",
  "Scene Breakdown": "Analiza sceny",
  "Dialogue Only": "Tylko dialog",
  "Ad loading please wait..": "Reklama się ładuje, proszę czekać...",
  "Words:": "Słowa:",
  "Reading:": "Czytanie:",

  AppKeys.arabic: "Arabski",
  AppKeys.chinese: "Chiński",
  AppKeys.english: "Angielski",
  AppKeys.french: "Francuski",
  AppKeys.german: "Niemiecki",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonezyjski",
  AppKeys.japanese: "Japoński",
  AppKeys.korean: "Koreański",
  AppKeys.portuguese: "Portugalski",
  AppKeys.russian: "Rosyjski",
  AppKeys.spanish: "Hiszpański",
  AppKeys.turkish: "Turecki",

  // New strings for download & actions
  'Download As': 'Pobierz jako',
  'Choose format to download': 'Wybierz format do pobrania',
  'Text File': 'Plik tekstowy',
  'PDF File': 'Plik PDF',
  'Copy': 'Kopiuj',
  'Share': 'Udostępnij',
  'Text copied!': 'Tekst skopiowany!',
  'Copied to clipboard': 'Skopiowano do schowka',
  'File saved successfully': 'Plik zapisany pomyślnie',
  'Error saving file': 'Błąd zapisu pliku',
  'Share Story': 'Udostępnij historię',
  'Export': 'Eksportuj',
  "Character Story": "Historia postaci",
  "Create detailed character backstories":
      "Twórz szczegółowe tło fabularne postaci",
  "Create Character": "Utwórz postać",
  "Rewrite Story": "Przepisz historię",
  "Paste Your Story": "Wklej swoją historię",
  "Paste your story here to rewrite...":
      "Wklej swoją historię tutaj, aby ją przepisać...",
  "Transform and improve your existing stories":
      "Przekształć i popraw swoje istniejące historie",
  "Title Generator": "Generator tytułów",
  "Generate catchy titles for your stories":
      "Generuj chwytliwe tytuły dla swoich historii",
  "Generate Titles": "Generuj tytuły",
  "Blog Writer": "Pisarz blogów",
  "Blog Topic": "Temat bloga",
  "Target Keywords": "Docelowe słowa kluczowe",
  "Target Audience (Optional)": "Docelowi odbiorcy (Opcjonalnie)",
  "Enter your blog topic or title...": "Wpisz temat lub tytuł swojego bloga...",
  "e.g., AI writing, content marketing, SEO tips":
      "np. pisanie AI, marketing treści, wskazówki SEO",
  "e.g., small business owners, bloggers":
      "np. właściciele małych firm, blogerzy",
  "Article Type": "Typ artykułu",
  "Writing Tone": "Ton pisania",
  "Article Length": "Długość artykułu",
  "SEO Options": "Opcje SEO",
  "Include Meta Description": "Uwzględnij metaopis",
  "Include Keyword Suggestions": "Uwzględnij sugestie słów kluczowych",
  "Include FAQs Section": "Uwzględnij sekcję FAQ",
  "Please enter a blog topic": "Proszę wpisz temat bloga",
  "Generate Blog": "Generuj bloga",
  "SEO optimized articles with keywords":
      "Artykuły zoptymalizowane pod SEO ze słowami kluczowymi",
  "Write Blog": "Napisz blog",
  "YouTube Script": "Skrypt YouTube",
  "Video Topic": "Temat wideo",
  "Key Points (Optional)": "Kluczowe punkty (Opcjonalnie)",
  "What is your video about?": "O czym jest Twoje wideo?",
  "List key points to cover (optional)...":
      "Wylistuj kluczowe punkty do omówienia (opcjonalnie)...",
  "Video Duration": "Czas trwania wideo",
  "Script Options": "Opcje skryptu",
  "Include Hook/Intro": "Uwzględnij haczyk/intro",
  "Include Call-to-Action": "Uwzględnij wezwanie do działania",
  "Include Timestamps": "Uwzględnij znaczniki czasu",
  "Please enter a video topic": "Proszę wpisz temat wideo",
  "Generate Script": "Generuj skrypt",
  "Create scripts for videos & reels": "Twórz skrypty do filmów i reelsów",
  "Create Script": "Utwórz skrypt",
  "Character Details": "Szczegóły postaci",
  "Character Name": "Imię postaci",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Wiek (np. 25, Młody dorosły, Starożytny)",
  "Personality (e.g., brave, shy, cunning)":
      "Osobowość (np. odważny, nieśmiały, przebiegły)",
  "Role (e.g., Hero, Villain, Mentor)": "Rola (np. Bohater, Złoczyńca, Mentor)",
  "Additional Details (optional)": "Dodatkowe szczegóły (opcjonalnie)",
  "Output Style": "Styl wyjściowy",
  "Generate Character": "Generuj postać",
  "Please enter character name": "Proszę wpisz imię postaci",
  "Please enter character role": "Proszę wpisz rolę postaci",
  "Detailed": "Szczegółowy",
  "Brief": "Zwięzły",
  "Elaborate": "Rozbudowany",
  "Select Tone": "Wybierz ton",
  "Rewrite Style": "Styl przepisywania",
  "Output Length": "Długość wyjściowa",
  "Please paste your story": "Proszę wklej swoją historię",
  "Story is too short. Please provide more content.":
      "Historia jest za krótka. Proszę podaj więcej treści.",
  "Same": "Taki sam",
  "More Dramatic": "Bardziej dramatyczny",
  "More Humorous": "Bardziej humorystyczny",
  "More Emotional": "Bardziej emocjonalny",
  "More Suspenseful": "Bardziej napięty",
  "Lighter": "Lżejszy",
  "Improved": "Ulepszony",
  "Simplified": "Uproszczony",
  "More Descriptive": "Bardziej opisowy",
  "More Dialogue": "Więcej dialogów",
  "More Action": "Więcej akcji",
  "Literary": "Literacki",
  "Shorter": "Krótszy",
  "Longer": "Dłuższy",
  "Much Longer": "Znacznie dłuższy",
  "Rewrite Now": "Przepisz teraz",
  "Story/Book Topic": "Temat historii/książki",
  "Keywords (Optional)": "Słowa kluczowe (Opcjonalnie)",
  "Describe your story topic or theme...":
      "Opisz temat lub motyw swojej historii...",
  "e.g., magic, dragon, adventure": "np. magia, smok, przygoda",
  "Title For": "Tytuł dla",
  "Title Style": "Styl tytułu",
  "Number of Titles": "Liczba tytułów",
  "Book": "Książka",
  "Short Story": "Opowiadanie",
  "Novel": "Powieść",
  "Chapter": "Rozdział",
  "Series": "Seria",
  "Simple": "Prosty",
  "Mysterious": "Tajemniczy",
  "Dramatic": "Dramatyczny",
  "Catchy": "Chwytliwy",
  "Poetic": "Poetycki",
  "Kids": "Dla dzieci",
  "SEO Article": "Artykuł SEO",
  "How-To Guide": "Poradnik",
  "Listicle": "Artykuł w formie listy",
  "Product Review": "Recenzja produktu",
  "Opinion Piece": "Artykuł opinii",
  "News Article": "Artykuł informacyjny",
  "Professional": "Profesjonalny",
  "Casual": "Nieformalny",
  "Informative": "Informacyjny",
  "Persuasive": "Przekonujący",
  "Friendly": "Przyjazny",
  "Authoritative": "Autorytatywny",
  "Short (500-800)": "Krótki (500-800)",
  "Medium (800-1500)": "Średni (800-1500)",
  "Long (1500-2500)": "Długi (1500-2500)",
  "Detailed (2500+)": "Szczegółowy (2500+)",
  "Storytime": "Czas na historię",
  "Documentary": "Dokumentalny",
  "Short Reel": "Krótki reel",
  "Educational": "Edukacyjny",
  "Review": "Recenzja",
  "Tutorial": "Samouczek",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Angażujący",
  "Energetic": "Energiczny",
  "Calm": "Spokojny",
  "Funny": "Zabawny",
  "Next": "Dalej",
  "Get Started": "Zacznij",
  "Your tool for quick, high-quality essay writing":
      "Twoje narzędzie do szybkiego pisania wysokiej jakości esejów",
};
