import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> pt = {
  AppKeys.lblChooseLanguage: "Escolher idioma",
  "All": "Todos",
  "AI Story Generator": "Gerador de Histórias com IA",
  "Story Generator": "Gerador de Histórias",
  "Essay Writer": "Escritor de Ensaios",
  "Essay length": "Comprimento do ensaio",
  "Script Generator": "Gerador de Roteiros",
  "Create original stories in seconds": "Crie histórias originais em segundos",
  "Academic writing made simple": "Escrita acadêmica simplificada",
  "Generate powerful scripts for any medium":
      "Gere roteiros poderosos para qualquer meio",
  "Start Writing": "Começar a Escrever",
  "Create Now": "Criar Agora",
  "Start Generating": "Começar a Gerar",
  "Go Premium": "Obter Premium",
  "Unlock Everything": "Desbloquear Tudo",
  "Unlimited Story Generation": "Geração de Histórias Ilimitada",
  "Write Longer & Detailed Essays": "Escrever Ensaios Mais Longos e Detalhados",
  "Advanced Script Writer": "Escritor de Scripts Avançado",
  "Unlock All Styles & Tones": "Desbloquear Todos os Estilos e Tons",
  "No Word/Length Limit": "Sem Limite de Palavras/Comprimento",
  "Remove All Ads": "Remover Todos os Anúncios",
  "3 days free": "3 dias grátis",
  "Restore": "Restaurar",
  "Your Stories": "Suas Histórias",
  "AI Story Writer": "Escritor de Histórias com IA",
  "No stories yet": "Ainda sem histórias",
  "Start creating your first story!": "Comece a criar sua primeira história!",
  "Your Story Space Awaits": "Seu Espaço de Histórias Aguarda",
  "Start your first story and see it appear here":
      "Comece sua primeira história e veja-a aparecer aqui",
  "Language": "Idioma",
  "Rate us": "Avalie-nos",
  "Share us": "Compartilhe-nos",
  "Privacy Policy": "Política de Privacidade",
  "Settings": "Configurações",
  "Select Language": "Selecionar Idioma",
  "Dashboard": "Painel",
  "BENEFITS": "BENEFÍCIOS",
  "Subscribe": "Assinar",
  "Weekly": "Semanal",
  "Monthly": "Mensal",
  "Yearly": "Anual",
  "week": "semana",
  "months": "meses",
  "We're sorry to hear that 😔": "Lamentamos ouvir isso 😔",
  "We'll try to improve 🙁": "Vamos tentar melhorar 🙁",
  "Thanks for your feedback 🙂": "Obrigado pelo seu feedback 🙂",
  "Great! We're glad you like it 😊":
      "Ótimo! Ficamos felizes que você goste 😊",
  "Awesome! Thank you so much! 🎉": "Incrível! Muito obrigado! 🎉",
  "Maybe Later": "Talvez depois",
  "Tap a star to rate your experience":
      "Toque em uma estrela para avaliar sua experiência",
  "Enjoying AI Math Solver?": "Está gostando do AI Math Solver?",
  "Thank you for rating us": "Obrigado por nos avaliar",
  "Submit Rating": "Enviar avaliação",
  "Hindi": "Hindi",
  "year": "ano",
  "Enjoying AI Story Generator?":
      "Está gostando do Gerador de Histórias com IA?",
  "Terms & Condition": "Termos e Condições",
  "No Commitment. Cancel anytime":
      "Sem Compromisso. Cancele a qualquer momento",
  "No Payment Now": "Sem Pagamento Agora",
  "Start your free trial": "Comece seu teste gratuito",
  "More detailed answers": "Respostas mais detalhadas",
  "Instant responds": "Respostas instantâneas",
  "Text recognition": "Reconhecimento de texto",
  "Powered by AI": "Alimentado por IA",
  "Storytelleing": "Contação de histórias",
  ' Power': "Poder",
  "Unlock your \nFill ": "Desbloqueie seu \nFill",
  "Your History": "Seu Histórico",
  "Terms and Conditions": "Termos e Condições",
  "Short": "Curto",
  "Medium": "Médio",
  "Long": "Longo",
  "Length": "Comprimento",
  "Describe your topic...": "Descreva seu tópico...",
  "Set Creativity": "Definir Criatividade",
  "Standard": "Padrão",
  "Creative": "Criativo",
  "Complex": "Complexo",
  "Select Genre": "Selecionar Gênero",
  "Fantasy": "Fantasia",
  "Mystery": "Mistério",
  "Thriller": "Suspense",
  "Script Tone": "Tom do Roteiro",
  "Script Type": "Tipo de Roteiro",
  "Comedy": "Comédia",
  "Drama": "Drama",
  "Horror": "Terror",
  "Action": "Ação",
  "Romance": "Romance",
  "Motivational": "Motivacional",
  "Advertisement": "Publicidade",
  "Fairy Tale": "Conto de Fadas",
  "Sci-Fi": "Ficção Científica",
  "Select Style": "Selecionar Estilo",
  "Imaginative": "Imaginativo",
  "Innovative": "Inovador",
  "Generate": "Gerar",
  "Please wait...": "Por favor, aguarde...",
  "Result": "Resultado",
  "Regenerate": "Regenerar",
  "Download": "Baixar",
  "Text copied to clipboard!": "Texto copiado para a área de transferência!",
  "Please enter a topic": "Por favor, insira um tópico",
  "Story Magic": "Magia de Histórias",
  "Let AI bring your thoughts to a full story":
      "Deixe a IA transformar seus pensamentos em uma história completa",
  "Smart Scripts": "Roteiros Inteligentes",
  "From concept to script—fast, easy, and creative":
      "Do conceito ao roteiro—rápido, fácil e criativo",
  "Perfect Essays": "Ensaios Perfeitos",
  "You have reached your free limit": "Você atingiu seu limite gratuito",
  "Donwload": "Downloads",
  "Press again to exit app": "Pressione novamente para sair do aplicativo",
  "Saved to files": "Arquivo TXT salvo com sucesso!",
  "Error: Please try again": "Erro: Por favor, tente novamente",
  "Subscription expired": "Assinatura expirada",
  "Purchase cancelled": "Compra cancelada",
  "Purchase failed": "Compra falhou",
  "Restore failed": "Restauração falhou",
  "Purchase Successful!": "Compra Bem-sucedida!",
  "Short (200-500 words)": "Curto (200-500 palavras)",
  "Medium (500-1000 words)": "Médio (500-1000 palavras)",
  "Large (1000+ words)": "Grande (1000+ palavras)",
  "Academic Level": "Nível Acadêmico",
  "Type of Paper": "Tipo de Documento",
  "High School": "Ensino Médio",
  "College": "Faculdade",
  "Short Film": "Curta-metragem",
  "University": "Universidade",
  "Masters": "Mestrado",
  "Custom": "Personalizado",
  "YouTube Video": "Vídeo do YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Vídeo do Tiktok",
  "Movie": "Filme",
  "Expository": "Expositivo",
  "Argumentative": "Argumentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descritivo",

  AppKeys.arabic: "Árabe",
  AppKeys.chinese: "Chinês",
  AppKeys.english: "Inglês",
  AppKeys.french: "Francês",
  AppKeys.german: "Alemão",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonésio",
  AppKeys.japanese: "Japonês",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Português",
  AppKeys.russian: "Russo",
  AppKeys.spanish: "Espanhol",
  AppKeys.turkish: "Turco",

  // New strings for download & actions
  'Download As': 'Baixar Como',
  'Choose format to download': 'Escolha o formato para baixar',
  'Text File': 'Arquivo de Texto',
  'PDF File': 'Arquivo PDF',
  'Copy': 'Copiar',
  'Share': 'Compartilhar',
  'Text copied!': 'Texto copiado!',
  'PDF saved successfully!': 'PDF salvo com sucesso!',
  'Error creating PDF: Please try again':
      'Erro ao criar PDF: Por favor, tente novamente',

  // Character Story Tool
  'Character Story': 'História do Personagem',
  'Character Details': 'Detalhes do Personagem',
  'Character Name': 'Nome do Personagem',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Idade (ex. 25, Jovem Adulto, Ancião)',
  'Personality (e.g., brave, shy, cunning)':
      'Personalidade (ex. corajoso, tímido, astuto)',
  'Role (e.g., Hero, Villain, Mentor)': 'Papel (ex. Herói, Vilão, Mentor)',
  'Additional Details (optional)': 'Detalhes Adicionais (opcional)',
  'Output Style': 'Estilo de Saída',
  'Generate Character': 'Gerar Personagem',
  'Please enter character name': 'Por favor, insira o nome do personagem',
  'Please enter character role': 'Por favor, insira o papel do personagem',
  'Detailed': 'Detalhado',
  'Brief': 'Breve',
  'Elaborate': 'Elaborado',

  // Home Screen Tool Cards
  'Create detailed character backstories':
      'Crie histórias de fundo detalhadas de personagens',
  'Create Character': 'Criar Personagem',
  'Transform and improve your existing stories':
      'Transforme e melhore suas histórias existentes',
  'Rewrite Now': 'Reescrever Agora',
  'Generate catchy titles for your stories':
      'Gere títulos atraentes para suas histórias',
  'Generate Titles': 'Gerar Títulos',

  // Rewrite Story Tool
  'Rewrite Story': 'Reescrever História',
  'Paste Your Story': 'Cole Sua História',
  'Paste your story here to rewrite...':
      'Cole sua história aqui para reescrever...',
  'Select Tone': 'Selecionar Tom',
  'Rewrite Style': 'Estilo de Reescrita',
  'Output Length': 'Comprimento da Saída',
  'Please paste your story': 'Por favor, cole sua história',
  'Story is too short. Please provide more content.':
      'A história é muito curta. Por favor, forneça mais conteúdo.',
  // Tone options
  'Same': 'Mesmo',
  'More Dramatic': 'Mais Dramático',
  'More Humorous': 'Mais Humorístico',
  'More Emotional': 'Mais Emocional',
  'More Suspenseful': 'Mais Suspense',
  'Lighter': 'Mais Leve',
  // Style options
  'Improved': 'Melhorado',
  'Simplified': 'Simplificado',
  'More Descriptive': 'Mais Descritivo',
  'More Dialogue': 'Mais Diálogo',
  'More Action': 'Mais Ação',
  'Literary': 'Literário',
  // Length options
  'Shorter': 'Mais Curto',
  'Longer': 'Mais Longo',
  'Much Longer': 'Muito Mais Longo',

  // Title Generator Tool
  'Title Generator': 'Gerador de Títulos',
  'Story/Book Topic': 'Tópico de História/Livro',
  'Keywords (Optional)': 'Palavras-chave (Opcional)',
  'Describe your story topic or theme...':
      'Descreva o tópico ou tema da sua história...',
  'e.g., magic, dragon, adventure': 'ex., magia, dragão, aventura',
  'Title For': 'Título Para',
  'Title Style': 'Estilo do Título',
  'Number of Titles': 'Número de Títulos',
  // Type options
  'Book': 'Livro',
  'Short Story': 'Conto',
  'Novel': 'Romance',
  'Chapter': 'Capítulo',
  'Series': 'Série',
  // Title Style options
  'Simple': 'Simples',
  'Mysterious': 'Misterioso',
  'Dramatic': 'Dramático',
  'Catchy': 'Cativante',
  'Poetic': 'Poético',
  // Genre options
  'Kids': 'Crianças',

  // Blog Writer Tool
  'Blog Writer': 'Escritor de Blog',
  'Blog Topic': 'Tópico do Blog',
  'Target Keywords': 'Palavras-chave Alvo',
  'Target Audience (Optional)': 'Público Alvo (Opcional)',
  'Enter your blog topic or title...':
      'Digite o tópico ou título do seu blog...',
  'e.g., AI writing, content marketing, SEO tips':
      'ex., escrita com IA, marketing de conteúdo, dicas de SEO',
  'e.g., small business owners, bloggers':
      'ex., proprietários de pequenas empresas, blogueiros',
  'Article Type': 'Tipo de Artigo',
  'Writing Tone': 'Tom de Escrita',
  'Article Length': 'Comprimento do Artigo',
  'SEO Options': 'Opções de SEO',
  'Include Meta Description': 'Incluir Meta Descrição',
  'Include Keyword Suggestions': 'Incluir Sugestões de Palavras-chave',
  'Include FAQs Section': 'Incluir Seção de Perguntas Frequentes',
  'Please enter a blog topic': 'Por favor, insira um tópico de blog',
  'Generate Blog': 'Gerar Blog',
  'SEO optimized articles with keywords':
      'Artigos otimizados para SEO com palavras-chave',
  'Write Blog': 'Escrever Blog',
  // Article Types
  'SEO Article': 'Artigo SEO',
  'How-To Guide': 'Guia Prático',
  'Listicle': 'Artigo de Lista',
  'Product Review': 'Avaliação de Produto',
  'Opinion Piece': 'Artigo de Opinião',
  'News Article': 'Artigo de Notícias',
  // Blog Tones
  'Professional': 'Profissional',
  'Casual': 'Casual',
  'Informative': 'Informativo',
  'Persuasive': 'Persuasivo',
  'Friendly': 'Amigável',
  'Authoritative': 'Autoritativo',
  // Blog Lengths
  'Short (500-800)': 'Curto (500-800)',
  'Medium (800-1500)': 'Médio (800-1500)',
  'Long (1500-2500)': 'Longo (1500-2500)',
  'Detailed (2500+)': 'Detalhado (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'Script do YouTube',
  'Video Topic': 'Tópico do Vídeo',
  'Key Points (Optional)': 'Pontos-chave (Opcional)',
  'What is your video about?': 'Sobre o que é o seu vídeo?',
  'List key points to cover (optional)...':
      'Liste os pontos-chave a abordar (opcional)...',
  'Video Duration': 'Duração do Vídeo',
  'Script Options': 'Opções do Script',
  'Include Hook/Intro': 'Incluir Gancho/Intro',
  'Include Call-to-Action': 'Incluir Chamada para Ação',
  'Include Timestamps': 'Incluir Marcações de Tempo',
  'Please enter a video topic': 'Por favor, insira um tópico de vídeo',
  'Generate Script': 'Gerar Script',
  'Create scripts for videos & reels': 'Crie scripts para vídeos e reels',
  'Create Script': 'Criar Script',
  // Script Types
  'Storytime': 'Hora da História',
  'Documentary': 'Documentário',
  'Short Reel': 'Reel Curto',
  'Educational': 'Educacional',
  'Review': 'Avaliação',
  'Tutorial': 'Tutorial',
  // Durations
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  // Script Tones
  'Engaging': 'Envolvente',
  'Energetic': 'Energético',
  'Calm': 'Calmo',
  'Funny': 'Engraçado',

  // Story Generator - Styles
  'Inspired': 'Inspirado',

  // Script Writer - Script Tones (formats)
  'Film Script': 'Roteiro de Filme',
  'Stage Play': 'Peça de Teatro',
  'Scene Breakdown': 'Análise de Cena',
  'Dialogue Only': 'Apenas Diálogo',

  // Ad & UI
  'Ad loading please wait..': 'Carregando anúncio, por favor aguarde..',

  // Word Counter & Reading Time
  'Words:': 'Palavras:',
  'Reading:': 'Leitura:',

  // Missing strings from hi.dart
  'Adventure': 'Aventura',
};
