import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> pt = {
  AppKeys.lblChooseLanguage: "Escolher idioma",
  "All": "Todos",
  "AI Story Generator": "Gerador de Histórias com IA",
  "Story Generator": "Gerador de Histórias",
  "Essay Writer": "Escritor de Ensaios",
  "Essay length": "Comprimento do ensaio",
  "Script Generator": "Gerador de Roteiros",
  "Create original stories in seconds": "Crie histórias originais em segundos",
  "Academic writing made simple": "Escrita acadêmica simplificada",
  "Generate powerful scripts for any medium":
      "Gere roteiros poderosos para qualquer meio",
  "Start Writing": "Começar a Escrever",
  "Create Now": "Criar Agora",
  "Start Generating": "Começar a Gerar",
  "Go Premium": "Obter Premium",
  "Unlock Everything": "Desbloquear Tudo",
  "Unlimited Story Generation": "Geração de Histórias Ilimitada",
  "Write Longer & Detailed Essays": "Escrever Ensaios Mais Longos e Detalhados",
  "Advanced Script Writer": "Escritor de Scripts Avançado",
  "Unlock All Styles & Tones": "Desbloquear Todos os Estilos e Tons",
  "No Word/Length Limit": "Sem Limite de Palavras/Comprimento",
  "Remove All Ads": "Remover Todos os Anúncios",
  "3 days free": "3 dias grátis",
  "Restore": "Restaurar",
  "YouTube Video": "Vídeo do YouTube",
  "Podcast": "Podcast",
  "AI Story Writer": "Escritor de Histórias com IA",
  "Reel": "Reel",
  "Your Stories": "Suas Histórias",
  "AI Story Writer": "Escritor de Histórias com IA",
  "No stories yet": "Ainda sem histórias",
  "Start creating your first story!": "Comece a criar sua primeira história!",
  "Your Story Space Awaits": "Seu Espaço de Histórias Aguarda",
  "Start your first story and see it appear here":
      "Comece sua primeira história e veja-a aparecer aqui",
  "Language": "Idioma",
  "Rate us": "Avalie-nos",
  "Share us": "Compartilhe-nos",
  "Privacy Policy": "Política de Privacidade",
  "Settings": "Configurações",
  "Select Language": "Selecionar Idioma",
  "Dashboard": "Painel",
  "BENEFITS": "BENEFÍCIOS",
  "Subscribe": "Assinar",
  "Weekly": "Semanal",
  "Monthly": "Mensal",
  "Yearly": "Anual",
  "week": "semana",
  "months": "meses",
  "We're sorry to hear that 😔": "Lamentamos ouvir isso 😔",
  "We'll try to improve 🙁": "Vamos tentar melhorar 🙁",
  "Thanks for your feedback 🙂": "Obrigado pelo seu feedback 🙂",
  "Great! We're glad you like it 😊":
      "Ótimo! Ficamos felizes que você goste 😊",
  "Awesome! Thank you so much! 🎉": "Incrível! Muito obrigado! 🎉",
  "Maybe Later": "Talvez depois",
  "Tap a star to rate your experience":
      "Toque em uma estrela para avaliar sua experiência",
  "Enjoying AI Math Solver?": "Está gostando do AI Math Solver?",
  "Thank you for rating us": "Obrigado por nos avaliar",
  "Submit Rating": "Enviar avaliação",
  "Hindi": "Hindi",
  "year": "ano",
  "Enjoying AI Story Generator?":
      "Está gostando do Gerador de Histórias com IA?",
  "Terms & Condition": "Termos e Condições",
  "No Commitment. Cancel anytime":
      "Sem Compromisso. Cancele a qualquer momento",
  "No Payment Now": "Sem Pagamento Agora",
  "3 days free": "3 dias grátis",
  "Start your free trial": "Comece seu teste gratuito",
  "More detailed answers": "Respostas mais detalhadas",
  "Instant responds": "Respostas instantâneas",
  "Text recognition": "Reconhecimento de texto",
  "Powered by AI": "Alimentado por IA",
  "Storytelleing": "Contação de histórias",
  ' Power': "Poder",
  "Unlock your \nFill ": "Desbloqueie seu \nFill",
  "Your History": "Seu Histórico",
  "Terms and Conditions": "Termos e Condições",
  "Short": "Curto",
  "Medium": "Médio",
  "Long": "Longo",
  "Length": "Comprimento",
  "Describe your topic...": "Descreva seu tópico...",
  "Set Creativity": "Definir Criatividade",
  "Standard": "Padrão",
  "Creative": "Criativo",
  "Complex": "Complexo",
  "Select Genre": "Selecionar Gênero",
  "Fantasy": "Fantasia",
  "Mystery": "Mistério",
  "Thriller": "Suspense",
  "Script Tone": "Tom do Roteiro",
  "Script Type": "Tipo de Roteiro",
  "Comedy": "Comédia",
  "Drama": "Drama",
  "Horror": "Terror",
  "Action": "Ação",
  "Romance": "Romance",
  "Motivational": "Motivacional",
  "Advertisement": "Publicidade",
  "Fairy Tale": "Conto de Fadas",
  "Sci-Fi": "Ficção Científica",
  "Select Style": "Selecionar Estilo",
  "Imaginative": "Imaginativo",
  "Innovative": "Inovador",
  "Generate": "Gerar",
  "Please wait...": "Por favor, aguarde...",
  "Result": "Resultado",
  "Regenerate": "Regenerar",
  "Download": "Baixar",
  "Text copied to clipboard!": "Texto copiado para a área de transferência!",
  "Please enter a topic": "Por favor, insira um tópico",
  "Story Magic": "Magia de Histórias",
  "Let AI bring your thoughts to a full story":
      "Deixe a IA transformar seus pensamentos em uma história completa",
  "Smart Scripts": "Roteiros Inteligentes",
  "From concept to script—fast, easy, and creative":
      "Do conceito ao roteiro—rápido, fácil e criativo",
  "Perfect Essays": "Ensaios Perfeitos",
  "You have reached your free limit": "Você atingiu seu limite gratuito",
  "Donwload": "Downloads",
  "Press again to exit app": "Pressione novamente para sair do aplicativo",
  "Saved to files": "Arquivo TXT salvo com sucesso!",
  "Error: Please try again": "Erro: Por favor, tente novamente",
  "Subscription expired": "Assinatura expirada",
  "Purchase cancelled": "Compra cancelada",
  "Purchase failed": "Compra falhou",
  "Restore failed": "Restauração falhou",
  "Purchase Successful!": "Compra Bem-sucedida!",
  "Short (200-500 words)": "Curto (200-500 palavras)",
  "Medium (500-1000 words)": "Médio (500-1000 palavras)",
  "Large (1000+ words)": "Grande (1000+ palavras)",
  "Academic Level": "Nível Acadêmico",
  "Type of Paper": "Tipo de Documento",
  "High School": "Ensino Médio",
  "College": "Faculdade",
  "Short Film": "Curta-metragem",
  "University": "Universidade",
  "Masters": "Mestrado",
  "Custom": "Personalizado",
  "YouTube Video": "Vídeo do YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Tiktok Video": "Vídeo do Tiktok",
  "Movie": "Filme",
  "Expository": "Expositivo",
  "Argumentative": "Argumentativo",
  "Narrative": "Narrativo",
  "Descriptive": "Descritivo",

  AppKeys.arabic: "Árabe",
  AppKeys.chinese: "Chinês",
  AppKeys.english: "Inglês",
  AppKeys.french: "Francês",
  AppKeys.german: "Alemão",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonésio",
  AppKeys.japanese: "Japonês",
  AppKeys.korean: "Coreano",
  AppKeys.portuguese: "Português",
  AppKeys.russian: "Russo",
  AppKeys.spanish: "Espanhol",
  AppKeys.turkish: "Turco",
};
