import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ro = {
  AppKeys.lblChooseLanguage: "Alegeți limba",
  "All": "Toate",
  "AI Story Generator": "Generator de povești AI",
  "Story Generator": "Generator de povești",
  "Essay Writer": "Scriitor de eseuri",
  "Essay length": "Lungimea eseului",
  "Script Generator": "Generator de scenarii",
  "Create original stories in seconds":
      "Creați povești originale în câteva secunde",
  "Academic writing made simple": "Scrierea academică simplificată",
  "Generate powerful scripts for any medium":
      "Generați scenarii puternice pentru orice mediu",
  "Start Writing": "Începeți să scrieți",
  "Create Now": "Creați acum",
  "Start Generating": "Începeți generarea",
  "Your Stories": "Poveștile tale",
  "No stories yet": "Nicio poveste încă",
  "Start creating your first story!":
      "Începeți să creați prima voastră poveste!",
  "Your Story Space Awaits": "Spațiul tău pentru povești te așteaptă",
  "Start your first story and see it appear here":
      "Începeți prima poveste și vedeți-o apărând aici",
  "Language": "Limbă",
  "Rate us": "Evaluați-ne",
  "Share us": "Distribuiți-ne",
  "Privacy Policy": "Politica de confidențialitate",
  "Settings": "Setări",
  "Select Language": "Selectați limba",
  "Dashboard": "Panou de control",
  "BENEFITS": "BENEFICII",
  "Subscribe": "Abonați-vă",
  "Weekly": "Săptămânal",
  "Monthly": "Lunar",
  "Yearly": "Anual",
  "week": "săptămână",
  "months": "luni",
  "year": "an",
  "Terms & Condition": "Termeni și condiții",
  "No Commitment. Cancel anytime": "Fără angajament. Anulați oricând",
  "No Payment Now": "Fără plată acum",
  "3 days free": "3 zile gratuit",
  "Start your free trial": "Începeți perioada de probă gratuită",
  "More detailed answers": "Răspunsuri mai detaliate",
  "Instant responds": "Răspunsuri instantanee",
  "Text recognition": "Recunoașterea textului",
  "Powered by AI": "Alimentat de AI",
  "Storytelleing": "Povestire",
  ' Power': "Putere",
  "Unlock your \nFill ": "Deblocați-vă \nCompletați",
  "Your History": "Istoricul tău",
  "Terms and Conditions": "Termeni și condiții",
  "Short": "Scurt",
  "Medium": "Mediu",
  "Long": "Lung",
  "Length": "Lungime",
  "Describe your topic...": "Descrieți subiectul...",
  "Set Creativity": "Setați creativitatea",
  "Standard": "Standard",
  "Creative": "Creativ",
  "Complex": "Complex",
  "Select Genre": "Selectați genul",
  "Fantasy": "Fantezie",
  "Mystery": "Mister",
  "Thriller": "Thriller",
  "Script Tone": "Tonul scenariului",
  "Script Type": "Tipul scenariului",
  "Comedy": "Comedie",
  "Drama": "Dramă",
  "Horror": "Horror",
  "Action": "Acțiune",
  "Romance": "Romantic",
  "Go Premium": "Treceți la Premium",
  "Unlock Everything": "Deblocați totul",
  "Unlimited Story Generation": "Generare nelimitată de povești",
  "Write Longer & Detailed Essays": "Scrieți eseuri mai lungi și detaliate",
  "Advanced Script Writer": "Scriitor avansat de scenarii",
  "Unlock All Styles & Tones": "Deblocați toate stilurile și tonurile",
  "No Word/Length Limit": "Fără limită de cuvinte/lungime",
  "Remove All Ads": "Eliminați toate reclamele",
  "Restore": "Restaurați",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivațional",
  "Advertisement": "Reclamă",
  "Fairy Tale": "Basm",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Selectați stilul",
  "Imaginative": "Imaginativ",
  "Innovative": "Inovator",
  "AI Story Writer": "Scriitor de povești AI",
  "Generate": "Generați",
  "Please wait...": "Vă rugăm așteptați...",
  "Result": "Rezultat",
  "Regenerate": "Regenerați",
  "Download": "Descărcați",
  "Text copied to clipboard!": "Text copiat în clipboard!",
  "Please enter a topic": "Vă rugăm introduceți un subiect",
  "Story Magic": "Magia poveștilor",
  "Let AI bring your thoughts to a full story":
      "Lăsați AI să vă transforme gândurile într-o poveste completă",
  "Smart Scripts": "Scenarii inteligente",
  "From concept to script—fast, easy, and creative":
      "De la concept la scenariu—rapid, ușor și creativ",
  "Perfect Essays": "Eseuri perfecte",
  "You have reached your free limit": "Ați atins limita gratuită",
  "Donwload": "Descărcați",
  "Press again to exit app": "Apăsați din nou pentru a ieși din aplicație",
  "Saved to files": "Fișier TXT salvat cu succes!",
  "Error: Please try again": "Eroare: Vă rugăm încercați din nou",
  "Subscription expired": "Abonament expirat",
  "Purchase cancelled": "Achiziție anulată",
  "Purchase failed": "Achiziție eșuată",
  "Restore failed": "Restaurare eșuată",
  "Purchase Successful!": "Achiziție reușită!",
  "Short (200-500 words)": "Scurt (200-500 cuvinte)",
  "Medium (500-1000 words)": "Mediu (500-1000 cuvinte)",
  "Large (1000+ words)": "Lung (1000+ cuvinte)",
  "Academic Level": "Nivel academic",
  "Type of Paper": "Tipul lucrării",
  "High School": "Liceu",
  "College": "Colegiu",
  "Short Film": "Scurtmetraj",
  "University": "Universitate",
  "Masters": "Masterat",
  "Custom": "Personalizat",
  "Tiktok Video": "Video Tiktok",
  "Movie": "Film",
  "Expository": "Expozitiv",
  "Argumentative": "Argumentativ",
  "Narrative": "Narativ",
  "Descriptive": "Descriptiv",
  "We're sorry to hear that 😔": "Ne pare rău să auzim asta 😔",
  "We'll try to improve 🙁": "Vom încerca să ne îmbunătățim 🙁",
  "Thanks for your feedback 🙂": "Mulțumim pentru feedback 🙂",
  "Great! We're glad you like it 😊": "Grozav! Ne bucurăm că vă place 😊",
  "Awesome! Thank you so much! 🎉": "Minunat! Vă mulțumim mult! 🎉",
  "Maybe Later": "Poate mai târziu",
  "Tap a star to rate your experience":
      "Atingeți o stea pentru a evalua experiența",
  "Enjoying AI Math Solver?": "Vă place AI Math Solver?",
  "Thank you for rating us": "Vă mulțumim pentru evaluare",
  "Submit Rating": "Trimiteți evaluarea",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Vă place AI Story Generator?",
  "Adventure": "Aventură",
  "Inspired": "Inspirat",
  "Film Script": "Scenariu de film",
  "Stage Play": "Piesă de teatru",
  "Scene Breakdown": "Analiza scenei",
  "Dialogue Only": "Doar dialog",
  "Ad loading please wait..": "Reclama se încarcă, vă rugăm așteptați...",
  "Words:": "Cuvinte:",
  "Reading:": "Lectură:",

  AppKeys.arabic: "Arabă",
  AppKeys.chinese: "Chineză",
  AppKeys.english: "Engleză",
  AppKeys.french: "Franceză",
  AppKeys.german: "Germană",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indoneziană",
  AppKeys.japanese: "Japoneză",
  AppKeys.korean: "Coreeană",
  AppKeys.portuguese: "Portugheză",
  AppKeys.russian: "Rusă",
  AppKeys.spanish: "Spaniolă",
  AppKeys.turkish: "Turcă",

  'Download As': 'Descărcați ca',
  'Choose format to download': 'Alegeți formatul de descărcare',
  'Text File': 'Fișier text',
  'PDF File': 'Fișier PDF',
  'Copy': 'Copiați',
  'Share': 'Distribuiți',
  'Text copied!': 'Text copiat!',
  'Copied to clipboard': 'Copiat în clipboard',
  'File saved successfully': 'Fișier salvat cu succes',
  'Error saving file': 'Eroare la salvarea fișierului',
  'Share Story': 'Distribuiți povestea',
  'Export': 'Exportați',
  "Character Story": "Povestea personajului",
  "Create detailed character backstories":
      "Creați povești detaliate de fundal pentru personaje",
  "Create Character": "Creează personaj",
  "Rewrite Story": "Rescrie povestea",
  "Paste Your Story": "Lipește povestea ta",
  "Paste your story here to rewrite...":
      "Lipește povestea ta aici pentru a o rescrie...",
  "Transform and improve your existing stories":
      "Transformă și îmbunătățește poveștile existente",
  "Title Generator": "Generator de titluri",
  "Generate catchy titles for your stories":
      "Generați titluri atrăgătoare pentru poveștile dvs.",
  "Generate Titles": "Generează titluri",
  "Blog Writer": "Scriitor de blog",
  "Blog Topic": "Subiect blog",
  "Target Keywords": "Cuvinte cheie țintă",
  "Target Audience (Optional)": "Public țintă (Opțional)",
  "Enter your blog topic or title...":
      "Introduceți subiectul sau titlul blogului...",
  "e.g., AI writing, content marketing, SEO tips":
      "ex., scriere AI, marketing de conținut, sfaturi SEO",
  "e.g., small business owners, bloggers":
      "ex., proprietari de afaceri mici, bloggeri",
  "Article Type": "Tipul articolului",
  "Writing Tone": "Tonul scrierii",
  "Article Length": "Lungimea articolului",
  "SEO Options": "Opțiuni SEO",
  "Include Meta Description": "Includeți meta descriere",
  "Include Keyword Suggestions": "Includeți sugestii de cuvinte cheie",
  "Include FAQs Section": "Includeți secțiunea FAQ",
  "Please enter a blog topic": "Vă rugăm să introduceți un subiect de blog",
  "Generate Blog": "Generează blog",
  "SEO optimized articles with keywords":
      "Articole optimizate SEO cu cuvinte cheie",
  "Write Blog": "Scrie blog",
  "YouTube Script": "Scenariu YouTube",
  "Video Topic": "Subiect video",
  "Key Points (Optional)": "Puncte cheie (Opțional)",
  "What is your video about?": "Despre ce este videoul tău?",
  "List key points to cover (optional)...":
      "Listați punctele cheie de acoperit (opțional)...",
  "Video Duration": "Durata videoclipului",
  "Script Options": "Opțiuni scenariu",
  "Include Hook/Intro": "Includeți cârlig/intro",
  "Include Call-to-Action": "Includeți îndemn la acțiune",
  "Include Timestamps": "Includeți marcaje de timp",
  "Please enter a video topic": "Vă rugăm să introduceți un subiect video",
  "Generate Script": "Generează scenariu",
  "Create scripts for videos & reels":
      "Creați scenarii pentru videoclipuri și reels",
  "Create Script": "Creează scenariu",
  "Character Details": "Detalii personaj",
  "Character Name": "Numele personajului",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Vârstă (ex., 25, Tânăr adult, Antic)",
  "Personality (e.g., brave, shy, cunning)":
      "Personalitate (ex., curajos, timid, viclean)",
  "Role (e.g., Hero, Villain, Mentor)": "Rol (ex., Erou, Villain, Mentor)",
  "Additional Details (optional)": "Detalii suplimentare (opțional)",
  "Output Style": "Stil de ieșire",
  "Generate Character": "Generează personaj",
  "Please enter character name": "Vă rugăm să introduceți numele personajului",
  "Please enter character role": "Vă rugăm să introduceți rolul personajului",
  "Detailed": "Detaliat",
  "Brief": "Scurt",
  "Elaborate": "Elaborat",
  "Select Tone": "Selectați tonul",
  "Rewrite Style": "Stil de rescriere",
  "Output Length": "Lungimea ieșirii",
  "Please paste your story": "Vă rugăm să lipiți povestea dvs.",
  "Story is too short. Please provide more content.":
      "Povestea este prea scurtă. Vă rugăm să furnizați mai mult conținut.",
  "Same": "Același",
  "More Dramatic": "Mai dramatic",
  "More Humorous": "Mai umoristic",
  "More Emotional": "Mai emoțional",
  "More Suspenseful": "Mai suspansiv",
  "Lighter": "Mai ușor",
  "Improved": "Îmbunătățit",
  "Simplified": "Simplificat",
  "More Descriptive": "Mai descriptiv",
  "More Dialogue": "Mai mult dialog",
  "More Action": "Mai multă acțiune",
  "Literary": "Literar",
  "Shorter": "Mai scurt",
  "Longer": "Mai lung",
  "Much Longer": "Mult mai lung",
  "Rewrite Now": "Rescrie acum",
  "Story/Book Topic": "Subiect poveste/carte",
  "Keywords (Optional)": "Cuvinte cheie (Opțional)",
  "Describe your story topic or theme...":
      "Descrieți subiectul sau tema poveștii...",
  "e.g., magic, dragon, adventure": "ex., magie, dragon, aventură",
  "Title For": "Titlu pentru",
  "Title Style": "Stilul titlului",
  "Number of Titles": "Numărul de titluri",
  "Book": "Carte",
  "Short Story": "Poveste scurtă",
  "Novel": "Roman",
  "Chapter": "Capitol",
  "Series": "Serie",
  "Simple": "Simplu",
  "Mysterious": "Misterios",
  "Dramatic": "Dramatic",
  "Catchy": "Atrăgător",
  "Poetic": "Poetic",
  "Kids": "Copii",
  "SEO Article": "Articol SEO",
  "How-To Guide": "Ghid pas cu pas",
  "Listicle": "Articol tip listă",
  "Product Review": "Recenzie produs",
  "Opinion Piece": "Articol de opinie",
  "News Article": "Articol de știri",
  "Professional": "Profesional",
  "Casual": "Casual",
  "Informative": "Informativ",
  "Persuasive": "Persuasiv",
  "Friendly": "Prietenos",
  "Authoritative": "Autoritar",
  "Short (500-800)": "Scurt (500-800)",
  "Medium (800-1500)": "Mediu (800-1500)",
  "Long (1500-2500)": "Lung (1500-2500)",
  "Detailed (2500+)": "Detaliat (2500+)",
  "Storytime": "Ora poveștilor",
  "Documentary": "Documentar",
  "Short Reel": "Reel scurt",
  "Educational": "Educațional",
  "Review": "Recenzie",
  "Tutorial": "Tutorial",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Captivant",
  "Energetic": "Energic",
  "Calm": "Calm",
  "Funny": "Amuzant",
  "Next": "Următor",
  "Get Started": "Începe",
  "Your tool for quick, high-quality essay writing":
      "Instrumentul tău pentru scriere rapidă și de înaltă calitate",
};
