import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ru = {
  AppKeys.lblChooseLanguage: "Выберите язык",
  "All": "Все",
  "AI Story Generator": "Генератор историй с ИИ",
  "Story Generator": "Генератор историй",
  "Essay Writer": "Писатель эссе",
  "Essay length": "Длина эссе",
  "Script Generator": "Генератор сценариев",
  "Create original stories in seconds":
      "Создавайте оригинальные истории за секунды",
  "Academic writing made simple": "Академическое письмо стало простым",
  "Generate powerful scripts for any medium":
      "Создавайте мощные сценарии для любого носителя",
  "Start Writing": "Начать писать",
  "Create Now": "Создать сейчас",
  "Start Generating": "Начать генерацию",
  "Your Stories": "Ваши истории",
  "No stories yet": "Пока нет историй",
  "Start creating your first story!": "Начните создавать свою первую историю!",
  "Your Story Space Awaits": "Ваше пространство историй ждет вас",
  "Start your first story and see it appear here":
      "Начните свою первую историю и увидите её здесь",
  "Language": "Язык",
  "Rate us": "Оцените нас",
  "Share us": "Поделитесь нами",
  "Privacy Policy": "Политика конфиденциальности",
  "Settings": "Настройки",
  "Select Language": "Выберите язык",
  "Dashboard": "Панель управления",
  "BENEFITS": "ПРЕИМУЩЕСТВА",
  "Subscribe": "Подписаться",
  "Weekly": "Еженедельно",
  "Monthly": "Ежемесячно",
  "Yearly": "Ежегодно",
  "week": "неделя",
  "months": "месяцы",
  "year": "год",
  "Terms & Condition": "Условия и положения",
  "No Commitment. Cancel anytime":
      "Никаких обязательств. Отменить в любое время",
  "No Payment Now": "Сейчас без оплаты",
  "We're sorry to hear that 😔": "Нам жаль это слышать 😔",
  "We'll try to improve 🙁": "Мы постараемся стать лучше 🙁",
  "Thanks for your feedback 🙂": "Спасибо за ваш отзыв 🙂",
  "Great! We're glad you like it 😊": "Отлично! Мы рады, что вам нравится 😊",
  "Awesome! Thank you so much! 🎉": "Потрясающе! Большое спасибо! 🎉",
  "Maybe Later": "Возможно позже",
  "Tap a star to rate your experience":
      "Нажмите на звезду, чтобы оценить ваш опыт",
  "Enjoying AI Math Solver?": "Вам нравится AI Math Solver?",
  "Thank you for rating us": "Спасибо за вашу оценку",
  "Submit Rating": "Отправить оценку",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "Вам нравится Генератор Историй с ИИ?",
  "3 days free": "3 дня бесплатно",
  "Start your free trial": "Начните бесплатную пробную версию",
  "More detailed answers": "Более подробные ответы",
  "Instant responds": "Мгновенные ответы",
  "Text recognition": "Распознавание текста",
  "Powered by AI": "Работает на ИИ",
  "Storytelleing": "Рассказывание историй",
  ' Power': "Мощь",
  "Unlock your \nFill ": "Разблокируйте свой \nFill",
  "Your History": "Ваша история",
  "Terms and Conditions": "Условия и положения",
  "Short": "Короткий",
  "Medium": "Средний",
  "Long": "Длинный",
  "Length": "Длина",
  "Describe your topic...": "Опишите вашу тему...",
  "Set Creativity": "Установить креативность",
  "Standard": "Стандартный",
  "Creative": "Креативный",
  "Complex": "Сложный",
  "Select Genre": "Выберите жанр",
  "Fantasy": "Фэнтези",
  "Mystery": "Тайна",
  "Thriller": "Триллер",
  "Script Tone": "Тон сценария",
  "Script Type": "Тип сценария",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Horror": "Ужасы",
  "Action": "Боевик",
  "Romance": "Романтика",
  "Motivational": "Мотивационный",
  "Advertisement": "Реклама",
  "Fairy Tale": "Сказка",
  "Sci-Fi": "Научная фантастика",
  "Select Style": "Выберите стиль",
  "Imaginative": "Творческий",
  "Innovative": "Инновационный",
  "Generate": "Генерировать",
  "Please wait...": "Пожалуйста, подождите...",
  "Result": "Результат",
  "Regenerate": "Перегенерировать",
  "Download": "Скачать",
  "Text copied to clipboard!": "Текст скопирован в буфер обмена!",
  "Please enter a topic": "Пожалуйста, введите тему",
  "Story Magic": "Магия историй",
  "Let AI bring your thoughts to a full story":
      "Позвольте ИИ превратить ваши мысли в полноценную историю",
  "Smart Scripts": "Умные сценарии",
  "From concept to script—fast, easy, and creative":
      "От концепции до сценария—быстро, легко и креативно",
  "Perfect Essays": "Идеальные эссе",
  "You have reached your free limit": "Вы достигли бесплатного лимита",
  "Donwload": "Загрузки",
  "Press again to exit app": "Нажмите еще раз, чтобы выйти из приложения",
  "Saved to files": "TXT файл успешно сохранен!",
  "Error: Please try again": "Ошибка: Пожалуйста, попробуйте снова",
  "Subscription expired": "Подписка истекла",
  "Purchase cancelled": "Покупка отменена",
  "Purchase failed": "Покупка не удалась",
  "Restore failed": "Восстановление не удалось",
  "Purchase Successful!": "Покупка успешна!",
  "Short (200-500 words)": "Короткий (200-500 слов)",
  "Medium (500-1000 words)": "Средний (500-1000 слов)",
  "Large (1000+ words)": "Большой (1000+ слов)",
  "Academic Level": "Академический уровень",
  "Type of Paper": "Тип работы",
  "High School": "Средняя школа",
  "College": "Колледж",
  "Short Film": "Короткометражный фильм",
  "University": "Университет",
  "Masters": "Магистратура",
  "Custom": "Пользовательский",
  "YouTube Video": "Видео YouTube",
  "Podcast": "Подкаст",
  "Reel": "Рилс",
  "Tiktok Video": "Видео Tiktok",
  "Movie": "Фильм",
  "Expository": "Разъяснительный",
  "Argumentative": "Аргументированный",
  "Narrative": "Повествовательный",
  "Descriptive": "Описательный",

  AppKeys.arabic: "Арабский",
  AppKeys.chinese: "Китайский",
  AppKeys.english: "Английский",
  AppKeys.french: "Французский",
  AppKeys.german: "Немецкий",
  AppKeys.hindi: "Хинди",
  "Go Premium": "Получить Premium",
  "Unlock Everything": "Разблокировать всё",
  "Unlimited Story Generation": "Неограниченное создание историй",
  "Write Longer & Detailed Essays": "Пишите более длинные и подробные эссе",
  "Advanced Script Writer": "Продвинутый редактор скриптов",
  "Unlock All Styles & Tones": "Разблокировать все стили и тоны",
  "No Word/Length Limit": "Без ограничений по словам/длине",
  "Remove All Ads": "Удалить все объявления",
  "3 days free": "3 дня бесплатно",
  "Restore": "Восстановить",
  "YouTube Video": "Видео YouTube",
  "Podcast": "Подкаст",
  "Reel": "Рил",
  AppKeys.indonesian: "Индонезийский",
  AppKeys.japanese: "Японский",
  AppKeys.korean: "Корейский",
  AppKeys.portuguese: "Португальский",
  "AI Story Writer": "Писатель историй с ИИ",
  AppKeys.russian: "Русский",
  AppKeys.spanish: "Испанский",
  AppKeys.turkish: "Турецкий",
};
