import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ru = {
  AppKeys.lblChooseLanguage: "Выберите язык",
  "All": "Все",
  "AI Story Generator": "Генератор историй с ИИ",
  "Story Generator": "Генератор историй",
  "Essay Writer": "Писатель эссе",
  "Essay length": "Длина эссе",
  "Script Generator": "Генератор сценариев",
  "Create original stories in seconds":
      "Создавайте оригинальные истории за секунды",
  "Academic writing made simple": "Академическое письмо стало простым",
  "Generate powerful scripts for any medium":
      "Создавайте мощные сценарии для любого носителя",
  "Start Writing": "Начать писать",
  "Create Now": "Создать сейчас",
  "Start Generating": "Начать генерацию",
  "Your Stories": "Ваши истории",
  "No stories yet": "Пока нет историй",
  "Start creating your first story!": "Начните создавать свою первую историю!",
  "Your Story Space Awaits": "Ваше пространство историй ждет вас",
  "Start your first story and see it appear here":
      "Начните свою первую историю и увидите её здесь",
  "Language": "Язык",
  "Rate us": "Оцените нас",
  "Share us": "Поделитесь нами",
  "Privacy Policy": "Политика конфиденциальности",
  "Settings": "Настройки",
  "Select Language": "Выберите язык",
  "Dashboard": "Панель управления",
  "BENEFITS": "ПРЕИМУЩЕСТВА",
  "Subscribe": "Подписаться",
  "Weekly": "Еженедельно",
  "Monthly": "Ежемесячно",
  "Yearly": "Ежегодно",
  "week": "неделя",
  "months": "месяцы",
  "year": "год",
  "Terms & Condition": "Условия и положения",
  "No Commitment. Cancel anytime":
      "Никаких обязательств. Отменить в любое время",
  "No Payment Now": "Сейчас без оплаты",
  "We're sorry to hear that 😔": "Нам жаль это слышать 😔",
  "We'll try to improve 🙁": "Мы постараемся стать лучше 🙁",
  "Thanks for your feedback 🙂": "Спасибо за ваш отзыв 🙂",
  "Great! We're glad you like it 😊": "Отлично! Мы рады, что вам нравится 😊",
  "Awesome! Thank you so much! 🎉": "Потрясающе! Большое спасибо! 🎉",
  "Maybe Later": "Возможно позже",
  "Tap a star to rate your experience":
      "Нажмите на звезду, чтобы оценить ваш опыт",
  "Enjoying AI Math Solver?": "Вам нравится AI Math Solver?",
  "Thank you for rating us": "Спасибо за вашу оценку",
  "Submit Rating": "Отправить оценку",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "Вам нравится Генератор Историй с ИИ?",
  "3 days free": "3 дня бесплатно",
  "Start your free trial": "Начните бесплатную пробную версию",
  "More detailed answers": "Более подробные ответы",
  "Instant responds": "Мгновенные ответы",
  "Text recognition": "Распознавание текста",
  "Powered by AI": "Работает на ИИ",
  "Storytelleing": "Рассказывание историй",
  ' Power': "Мощь",
  "Unlock your \nFill ": "Разблокируйте свой \nFill",
  "Your History": "Ваша история",
  "Terms and Conditions": "Условия и положения",
  "Short": "Короткий",
  "Medium": "Средний",
  "Long": "Длинный",
  "Length": "Длина",
  "Describe your topic...": "Опишите вашу тему...",
  "Set Creativity": "Установить креативность",
  "Standard": "Стандартный",
  "Creative": "Креативный",
  "Complex": "Сложный",
  "Select Genre": "Выберите жанр",
  "Fantasy": "Фэнтези",
  "Mystery": "Тайна",
  "Thriller": "Триллер",
  "Script Tone": "Тон сценария",
  "Script Type": "Тип сценария",
  "Comedy": "Комедия",
  "Drama": "Драма",
  "Horror": "Ужасы",
  "Action": "Боевик",
  "Romance": "Романтика",
  "Motivational": "Мотивационный",
  "Advertisement": "Реклама",
  "Fairy Tale": "Сказка",
  "Sci-Fi": "Научная фантастика",
  "Select Style": "Выберите стиль",
  "Imaginative": "Творческий",
  "Innovative": "Инновационный",
  "Generate": "Генерировать",
  "Please wait...": "Пожалуйста, подождите...",
  "Result": "Результат",
  "Regenerate": "Перегенерировать",
  "Download": "Скачать",
  "Text copied to clipboard!": "Текст скопирован в буфер обмена!",
  "Please enter a topic": "Пожалуйста, введите тему",
  "Story Magic": "Магия историй",
  "Let AI bring your thoughts to a full story":
      "Позвольте ИИ превратить ваши мысли в полноценную историю",
  "Smart Scripts": "Умные сценарии",
  "From concept to script—fast, easy, and creative":
      "От концепции до сценария—быстро, легко и креативно",
  "Perfect Essays": "Идеальные эссе",
  "You have reached your free limit": "Вы достигли бесплатного лимита",
  "Donwload": "Загрузки",
  "Press again to exit app": "Нажмите еще раз, чтобы выйти из приложения",
  "Saved to files": "TXT файл успешно сохранен!",
  "Error: Please try again": "Ошибка: Пожалуйста, попробуйте снова",
  "Subscription expired": "Подписка истекла",
  "Purchase cancelled": "Покупка отменена",
  "Purchase failed": "Покупка не удалась",
  "Restore failed": "Восстановление не удалось",
  "Purchase Successful!": "Покупка успешна!",
  "Short (200-500 words)": "Короткий (200-500 слов)",
  "Medium (500-1000 words)": "Средний (500-1000 слов)",
  "Large (1000+ words)": "Большой (1000+ слов)",
  "Academic Level": "Академический уровень",
  "Type of Paper": "Тип работы",
  "High School": "Средняя школа",
  "College": "Колледж",
  "Short Film": "Короткометражный фильм",
  "University": "Университет",
  "Masters": "Магистратура",
  "Custom": "Пользовательский",
  "YouTube Video": "Видео YouTube",
  "Podcast": "Подкаст",
  "Reel": "Рилс",
  "Tiktok Video": "Видео Tiktok",
  "Movie": "Фильм",
  "Expository": "Разъяснительный",
  "Argumentative": "Аргументированный",
  "Narrative": "Повествовательный",
  "Descriptive": "Описательный",

  AppKeys.arabic: "Арабский",
  AppKeys.chinese: "Китайский",
  AppKeys.english: "Английский",
  AppKeys.french: "Французский",
  AppKeys.german: "Немецкий",
  AppKeys.hindi: "Хинди",
  "Go Premium": "Получить Premium",
  "Unlock Everything": "Разблокировать всё",
  "Unlimited Story Generation": "Неограниченное создание историй",
  "Write Longer & Detailed Essays": "Пишите более длинные и подробные эссе",
  "Advanced Script Writer": "Продвинутый редактор скриптов",
  "Unlock All Styles & Tones": "Разблокировать все стили и тоны",
  "No Word/Length Limit": "Без ограничений по словам/длине",
  "Remove All Ads": "Удалить все объявления",
  "Restore": "Восстановить",
  AppKeys.indonesian: "Индонезийский",
  AppKeys.japanese: "Японский",
  AppKeys.korean: "Корейский",
  AppKeys.portuguese: "Португальский",
  "AI Story Writer": "Писатель историй с ИИ",
  AppKeys.russian: "Русский",
  AppKeys.spanish: "Испанский",
  AppKeys.turkish: "Турецкий",

  // New strings for download & actions
  'Download As': 'Скачать как',
  'Choose format to download': 'Выберите формат для скачивания',
  'Text File': 'Текстовый файл',
  'PDF File': 'PDF файл',
  'Copy': 'Копировать',
  'Share': 'Поделиться',
  'Text copied!': 'Текст скопирован!',
  'PDF saved successfully!': 'PDF успешно сохранен!',
  'Error creating PDF: Please try again':
      'Ошибка создания PDF: Пожалуйста, попробуйте еще раз',

  // Character Story Tool
  'Character Story': 'История Персонажа',
  'Character Details': 'Детали Персонажа',
  'Character Name': 'Имя Персонажа',
  'Age (e.g., 25, Young Adult, Ancient)':
      'Возраст (напр. 25, Молодой взрослый, Древний)',
  'Personality (e.g., brave, shy, cunning)':
      'Личность (напр. храбрый, застенчивый, хитрый)',
  'Role (e.g., Hero, Villain, Mentor)': 'Роль (напр. Герой, Злодей, Наставник)',
  'Additional Details (optional)': 'Дополнительные Детали (необязательно)',
  'Output Style': 'Стиль Вывода',
  'Generate Character': 'Создать Персонажа',
  'Please enter character name': 'Пожалуйста, введите имя персонажа',
  'Please enter character role': 'Пожалуйста, введите роль персонажа',
  'Detailed': 'Подробный',
  'Brief': 'Краткий',
  'Elaborate': 'Развернутый',

  // Home Screen Tool Cards
  'Create detailed character backstories':
      'Создайте детальные предыстории персонажей',
  'Create Character': 'Создать Персонажа',
  'Transform and improve your existing stories':
      'Преобразуйте и улучшите ваши истории',
  'Rewrite Now': 'Переписать Сейчас',
  'Generate catchy titles for your stories':
      'Создайте привлекательные заголовки для ваших историй',
  'Generate Titles': 'Создать Заголовки',

  // Rewrite Story Tool
  'Rewrite Story': 'Переписать Историю',
  'Paste Your Story': 'Вставьте Вашу Историю',
  'Paste your story here to rewrite...':
      'Вставьте вашу историю сюда для переписывания...',
  'Select Tone': 'Выберите Тон',
  'Rewrite Style': 'Стиль Переписывания',
  'Output Length': 'Длина Вывода',
  'Please paste your story': 'Пожалуйста, вставьте вашу историю',
  'Story is too short. Please provide more content.':
      'История слишком короткая. Пожалуйста, добавьте больше контента.',
  // Tone options
  'Same': 'Тот же',
  'More Dramatic': 'Более Драматичный',
  'More Humorous': 'Более Юмористический',
  'More Emotional': 'Более Эмоциональный',
  'More Suspenseful': 'Более Напряженный',
  'Lighter': 'Легче',
  // Style options
  'Improved': 'Улучшенный',
  'Simplified': 'Упрощенный',
  'More Descriptive': 'Более Описательный',
  'More Dialogue': 'Больше Диалога',
  'More Action': 'Больше Действия',
  'Literary': 'Литературный',
  // Length options
  'Shorter': 'Короче',
  'Longer': 'Длиннее',
  'Much Longer': 'Намного Длиннее',

  // Title Generator Tool
  'Title Generator': 'Генератор Заголовков',
  'Story/Book Topic': 'Тема Истории/Книги',
  'Keywords (Optional)': 'Ключевые Слова (Необязательно)',
  'Describe your story topic or theme...': 'Опишите тему вашей истории...',
  'e.g., magic, dragon, adventure': 'напр., магия, дракон, приключение',
  'Title For': 'Заголовок Для',
  'Title Style': 'Стиль Заголовка',
  'Number of Titles': 'Количество Заголовков',
  // Type options
  'Book': 'Книга',
  'Short Story': 'Рассказ',
  'Novel': 'Роман',
  'Chapter': 'Глава',
  'Series': 'Серия',
  // Title Style options
  'Simple': 'Простой',
  'Mysterious': 'Таинственный',
  'Dramatic': 'Драматичный',
  'Catchy': 'Запоминающийся',
  'Poetic': 'Поэтичный',
  // Genre options
  'Kids': 'Детские',

  // Blog Writer Tool
  'Blog Writer': 'Автор Блога',
  'Blog Topic': 'Тема Блога',
  'Target Keywords': 'Целевые Ключевые Слова',
  'Target Audience (Optional)': 'Целевая Аудитория (Необязательно)',
  'Enter your blog topic or title...': 'Введите тему или заголовок блога...',
  'e.g., AI writing, content marketing, SEO tips':
      'напр., ИИ-письмо, контент-маркетинг, SEO-советы',
  'e.g., small business owners, bloggers':
      'напр., владельцы малого бизнеса, блогеры',
  'Article Type': 'Тип Статьи',
  'Writing Tone': 'Тон Письма',
  'Article Length': 'Длина Статьи',
  'SEO Options': 'SEO Опции',
  'Include Meta Description': 'Включить Мета Описание',
  'Include Keyword Suggestions': 'Включить Предложения Ключевых Слов',
  'Include FAQs Section': 'Включить Раздел Вопросов',
  'Please enter a blog topic': 'Пожалуйста, введите тему блога',
  'Generate Blog': 'Создать Блог',
  'SEO optimized articles with keywords':
      'SEO-оптимизированные статьи с ключевыми словами',
  'Write Blog': 'Написать Блог',
  // Article Types
  'SEO Article': 'SEO Статья',
  'How-To Guide': 'Руководство',
  'Listicle': 'Статья-список',
  'Product Review': 'Обзор Продукта',
  'Opinion Piece': 'Мнение',
  'News Article': 'Новостная Статья',
  // Blog Tones
  'Professional': 'Профессиональный',
  'Casual': 'Непринужденный',
  'Informative': 'Информативный',
  'Persuasive': 'Убедительный',
  'Friendly': 'Дружелюбный',
  'Authoritative': 'Авторитетный',
  // Blog Lengths
  'Short (500-800)': 'Короткий (500-800)',
  'Medium (800-1500)': 'Средний (800-1500)',
  'Long (1500-2500)': 'Длинный (1500-2500)',
  'Detailed (2500+)': 'Подробный (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'YouTube Скрипт',
  'Video Topic': 'Тема Видео',
  'Key Points (Optional)': 'Ключевые Моменты (Необязательно)',
  'What is your video about?': 'О чем ваше видео?',
  'List key points to cover (optional)...':
      'Перечислите ключевые моменты (необязательно)...',
  'Video Duration': 'Продолжительность Видео',
  'Script Options': 'Опции Скрипта',
  'Include Hook/Intro': 'Включить Хук/Вступление',
  'Include Call-to-Action': 'Включить Призыв к Действию',
  'Include Timestamps': 'Включить Временные Метки',
  'Please enter a video topic': 'Пожалуйста, введите тему видео',
  'Generate Script': 'Создать Скрипт',
  'Create scripts for videos & reels': 'Создавайте скрипты для видео и рилсов',
  'Create Script': 'Создать Скрипт',
  // Script Types
  'Storytime': 'Время Историй',
  'Documentary': 'Документальный',
  'Short Reel': 'Короткий Рилс',
  'Educational': 'Образовательный',
  'Review': 'Обзор',
  'Tutorial': 'Урок',
  // Durations
  '< 1 min (Shorts)': '< 1 мин (Шортс)',
  '1-3 min': '1-3 мин',
  '5-10 min': '5-10 мин',
  '10-20 min': '10-20 мин',
  '20+ min': '20+ мин',
  // Script Tones
  'Engaging': 'Увлекательный',
  'Energetic': 'Энергичный',
  'Calm': 'Спокойный',
  'Funny': 'Смешной',

  // Story Generator - Styles
  'Inspired': 'Вдохновлённый',

  // Script Writer - Script Tones (formats)
  'Film Script': 'Сценарий Фильма',
  'Stage Play': 'Театральная Пьеса',
  'Scene Breakdown': 'Разбор Сцены',
  'Dialogue Only': 'Только Диалог',

  // Ad & UI
  'Ad loading please wait..': 'Загрузка рекламы, пожалуйста подождите..',

  // Word Counter & Reading Time
  'Words:': 'Слова:',
  'Reading:': 'Чтение:',

  // Missing strings from hi.dart
  'Adventure': 'Приключение',
};
