import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> si = {
  AppKeys.lblChooseLanguage: "භාෂාව තෝරන්න",
  "All": "සියල්ල",
  "AI Story Generator": "AI කතා උත්පාදකය",
  "Story Generator": "කතා උත්පාදකය",
  "Essay Writer": "රචනා ලේඛකයා",
  "Essay length": "රචනා දිග",
  "Script Generator": "පිටපත් උත්පාදකය",
  "Create original stories in seconds":
      "තත්පර කිහිපයකින් මුල් කතා නිර්මාණය කරන්න",
  "Academic writing made simple": "අධ්‍යයන ලිවීම සරල කරන ලදී",
  "Generate powerful scripts for any medium":
      "ඕනෑම මාධ්‍යයක් සඳහා ප්‍රබල පිටපත් උත්පාදනය කරන්න",
  "Start Writing": "ලිවීම ආරම්භ කරන්න",
  "Create Now": "දැන් නිර්මාණය කරන්න",
  "Start Generating": "උත්පාදනය ආරම්භ කරන්න",
  "Your Stories": "ඔබේ කතා",
  "No stories yet": "තවම කතා නැත",
  "Start creating your first story!":
      "ඔබේ පළමු කතාව නිර්මාණය කිරීම ආරම්භ කරන්න!",
  "Your Story Space Awaits": "ඔබේ කතා අවකාශය බලා සිටී",
  "Start your first story and see it appear here":
      "ඔබේ පළමු කතාව ආරම්භ කර එය මෙහි දිස්වන බව බලන්න",
  "Language": "භාෂාව",
  "Rate us": "අපට ශ්‍රේණිගත කරන්න",
  "Share us": "අප බෙදා ගන්න",
  "Privacy Policy": "පෞද්ගලිකත්ව ප්‍රතිපත්තිය",
  "Settings": "සැකසුම්",
  "Select Language": "භාෂාව තෝරන්න",
  "Dashboard": "උපකරණ පුවරුව",
  "BENEFITS": "ප්‍රතිලාභ",
  "Subscribe": "දායක වන්න",
  "Weekly": "සතිපතා",
  "Monthly": "මාසික",
  "Yearly": "වාර්ෂික",
  "week": "සතිය",
  "months": "මාස",
  "year": "වසර",
  "Terms & Condition": "නියම සහ කොන්දේසි",
  "No Commitment. Cancel anytime":
      "කිසිදු බැඳීමක් නැත. ඕනෑම වේලාවක අවලංගු කරන්න",
  "No Payment Now": "දැන් ගෙවීම් නැත",
  "3 days free": "දින 3ක් නොමිලේ",
  "Start your free trial": "ඔබේ නොමිලේ අත්හදා බැලීම ආරම්භ කරන්න",
  "More detailed answers": "වඩාත් විස්තරාත්මක පිළිතුරු",
  "Instant responds": "ක්ෂණික ප්‍රතිචාර",
  "Text recognition": "පෙළ හඳුනාගැනීම",
  "Powered by AI": "AI මගින් බල ගැන්වේ",
  "Storytelleing": "කතා කීම",
  ' Power': "බලය",
  "Unlock your \nFill ": "ඔබේ \nපුරවන්න අගුළු ඇරීම",
  "Your History": "ඔබේ ඉතිහාසය",
  "Terms and Conditions": "නියම සහ කොන්දේසි",
  "Short": "කෙටි",
  "Medium": "මධ්‍යම",
  "Long": "දිග",
  "Length": "දිග",
  "Describe your topic...": "ඔබේ මාතෘකාව විස්තර කරන්න...",
  "Set Creativity": "නිර්මාණශීලිත්වය සකසන්න",
  "Standard": "සම්මත",
  "Creative": "නිර්මාණශීලී",
  "Complex": "සංකීර්ණ",
  "Select Genre": "ප්‍රභේදය තෝරන්න",
  "Fantasy": "මනඃකල්පිත",
  "Mystery": "අභිරහස",
  "Thriller": "ත්‍රිලර්",
  "Script Tone": "පිටපත් ස්වරය",
  "Script Type": "පිටපත් වර්ගය",
  "Comedy": "විකට",
  "Drama": "නාට්‍ය",
  "Horror": "භයානක",
  "Action": "ක්‍රියාදාම",
  "Romance": "ආදර",
  "Go Premium": "Premium ලබාගන්න",
  "Unlock Everything": "සියල්ල අගුළු ඇරීම",
  "Unlimited Story Generation": "අසීමිත කතා උත්පාදනය",
  "Write Longer & Detailed Essays": "දිගු සහ විස්තරාත්මක රචනා ලියන්න",
  "Advanced Script Writer": "උසස් පිටපත් ලේඛකයා",
  "Unlock All Styles & Tones": "සියලු මෝස්තර සහ ස්වර අගුළු ඇරීම",
  "No Word/Length Limit": "වචන/දිග සීමාවක් නැත",
  "Remove All Ads": "සියලු දැන්වීම් ඉවත් කරන්න",
  "Restore": "ප්‍රතිස්ථාපනය කරන්න",
  "YouTube Video": "YouTube වීඩියෝ",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "අභිප්‍රේරණාත්මක",
  "Advertisement": "දැන්වීම",
  "Fairy Tale": "පරිකථා",
  "Sci-Fi": "විද්‍යා ප්‍රබන්ධ",
  "Select Style": "මෝස්තරය තෝරන්න",
  "Imaginative": "කල්පනාශීලී",
  "Innovative": "නවෝත්පාදන",
  "AI Story Writer": "AI කතා ලේඛකයා",
  "Generate": "උත්පාදනය කරන්න",
  "Please wait...": "කරුණාකර රැඳී සිටින්න...",
  "Result": "ප්‍රතිඵලය",
  "Regenerate": "නැවත උත්පාදනය කරන්න",
  "Download": "බාගන්න",
  "Text copied to clipboard!": "පෙළ පසුරු පුවරුවට පිටපත් කරන ලදී!",
  "Please enter a topic": "කරුණාකර මාතෘකාවක් ඇතුළත් කරන්න",
  "Story Magic": "කතා මැජික්",
  "Let AI bring your thoughts to a full story":
      "AI ට ඔබේ සිතුවිලි සම්පූර්ණ කතාවක් බවට පත් කිරීමට ඉඩ දෙන්න",
  "Smart Scripts": "ස්මාර්ට් පිටපත්",
  "From concept to script—fast, easy, and creative":
      "සංකල්පයේ සිට පිටපතට—වේගවත්, පහසු, සහ නිර්මාණශීලී",
  "Perfect Essays": "පරිපූර්ණ රචනා",
  "You have reached your free limit": "ඔබ ඔබේ නොමිලේ සීමාවට පැමිණ ඇත",
  "Donwload": "බාගන්න",
  "Press again to exit app": "යෙදුමෙන් ඉවත් වීමට නැවත ඔබන්න",
  "Saved to files": "TXT ගොනුව සාර්ථකව සුරකින ලදී!",
  "Error: Please try again": "දෝෂයකි: කරුණාකර නැවත උත්සාහ කරන්න",
  "Subscription expired": "දායකත්වය කල් ඉකුත් විය",
  "Purchase cancelled": "මිලදී ගැනීම අවලංගු කරන ලදී",
  "Purchase failed": "මිලදී ගැනීම අසාර්ථක විය",
  "Restore failed": "ප්‍රතිස්ථාපනය අසාර්ථක විය",
  "Purchase Successful!": "මිලදී ගැනීම සාර්ථකයි!",
  "Short (200-500 words)": "කෙටි (වචන 200-500)",
  "Medium (500-1000 words)": "මධ්‍යම (වචන 500-1000)",
  "Large (1000+ words)": "විශාල (වචන 1000+)",
  "Academic Level": "අධ්‍යයන මට්ටම",
  "Type of Paper": "කඩදාසි වර්ගය",
  "High School": "උසස් පාසල",
  "College": "විද්‍යාලය",
  "Short Film": "කෙටි චිත්‍රපටය",
  "University": "විශ්ව විද්‍යාලය",
  "Masters": "ශාස්ත්‍රපති",
  "Custom": "අභිරුචි",
  "Tiktok Video": "Tiktok වීඩියෝ",
  "Movie": "චිත්‍රපටය",
  "Expository": "විවරණාත්මක",
  "Argumentative": "තර්කාත්මක",
  "Narrative": "ආඛ්‍යානාත්මක",
  "Descriptive": "විස්තරාත්මක",
  "We're sorry to hear that 😔": "එය අසන්නට අපට කණගාටුයි 😔",
  "We'll try to improve 🙁": "අපි වැඩිදියුණු කිරීමට උත්සාහ කරන්නෙමු 🙁",
  "Thanks for your feedback 🙂": "ඔබේ ප්‍රතිපෝෂණයට ස්තූතියි 🙂",
  "Great! We're glad you like it 😊": "නියමයි! ඔබට එය කැමති වීම ගැන සතුටුයි 😊",
  "Awesome! Thank you so much! 🎉": "අපූරුයි! ඉතා ස්තූතියි! 🎉",
  "Maybe Later": "සමහර විට පසුව",
  "Tap a star to rate your experience":
      "ඔබේ අත්දැකීම ශ්‍රේණිගත කිරීමට තරුවක් තට්ටු කරන්න",
  "Enjoying AI Math Solver?": "AI Math Solver ප්‍රිය කරනවාද?",
  "Thank you for rating us": "අපට ශ්‍රේණිගත කිරීම ගැන ස්තූතියි",
  "Submit Rating": "ශ්‍රේණිගත කිරීම ඉදිරිපත් කරන්න",
  "Hindi": "හින්දි",
  "Enjoying AI Story Generator?": "AI Story Generator ප්‍රිය කරනවාද?",
  "Adventure": "වික්‍රමාන්විත",
  "Inspired": "ආභාෂයෙන්",
  "Film Script": "චිත්‍රපට පිටපත",
  "Stage Play": "වේදිකා නාට්‍ය",
  "Scene Breakdown": "දර්ශන විශ්ලේෂණය",
  "Dialogue Only": "සංවාදය පමණි",
  "Ad loading please wait..": "දැන්වීම පූරණය වෙමින්, කරුණාකර රැඳී සිටින්න...",
  "Words:": "වචන:",
  "Reading:": "කියවීම:",

  AppKeys.arabic: "අරාබි",
  AppKeys.chinese: "චීන",
  AppKeys.english: "ඉංග්‍රීසි",
  AppKeys.french: "ප්‍රංශ",
  AppKeys.german: "ජර්මන්",
  AppKeys.hindi: "හින්දි",
  AppKeys.indonesian: "ඉන්දුනීසියානු",
  AppKeys.japanese: "ජපන්",
  AppKeys.korean: "කොරියානු",
  AppKeys.portuguese: "පෘතුගීසි",
  AppKeys.russian: "රුසියානු",
  AppKeys.spanish: "ස්පාඤ්ඤ",
  AppKeys.turkish: "තුර්කි",

  'Download As': 'ලෙස බාගන්න',
  'Choose format to download': 'බාගැනීමට ආකෘතිය තෝරන්න',
  'Text File': 'පෙළ ගොනුව',
  'PDF File': 'PDF ගොනුව',
  'Copy': 'පිටපත් කරන්න',
  'Share': 'බෙදා ගන්න',
  'Text copied!': 'පෙළ පිටපත් කරන ලදී!',
  'Copied to clipboard': 'පසුරු පුවරුවට පිටපත් කරන ලදී',
  'File saved successfully': 'ගොනුව සාර්ථකව සුරකින ලදී',
  'Error saving file': 'ගොනුව සුරැකීමේ දෝෂයකි',
  'Share Story': 'කතාව බෙදා ගන්න',
  'Export': 'අපනයනය කරන්න',

  "Character Story": "චරිත කතාව",
  "Create detailed character backstories":
      "චරිතයේ සවිස්තරාත්මක පසුබිම් කතා සාදන්න",
  "Create Character": "චරිතය සාදන්න",
  "Rewrite Story": "කතාව නැවත ලියන්න",
  "Paste Your Story": "ඔබේ කතාව අලවන්න",
  "Paste your story here to rewrite...":
      "නැවත ලිවීම සඳහා ඔබේ කතාව මෙහි අලවන්න...",
  "Transform and improve your existing stories":
      "ඔබේ පවතින කතා වෙනස් කර වැඩිදියුණු කරන්න",
  "Title Generator": "මාතෘකා උත්පාදකය",
  "Generate catchy titles for your stories":
      "ඔබේ කතා සඳහා ආකර්ෂණීය මාතෘකා සාදන්න",
  "Generate Titles": "මාතෘකා සාදන්න",
  "Blog Writer": "බ්ලොග් ලේඛකයා",
  "Blog Topic": "බ්ලොග් මාතෘකාව",
  "Target Keywords": "ඉලක්ක මූල පද",
  "Target Audience (Optional)": "ඉලක්ක පේක්ෂකයින් (විකල්ප)",
  "Enter your blog topic or title...":
      "ඔබේ බ්ලොග් මාතෘකාව හෝ නම ඇතුළු කරන්න...",
  "e.g., AI writing, content marketing, SEO tips":
      "උදා., AI ලිවීම, අන්තර්ගත අලෙවිකරණය, SEO ඉඟි",
  "e.g., small business owners, bloggers":
      "උදා., කුඩා ව්‍යාපාර හිමිකරුවන්, බ්ලොගකරුවන්",
  "Article Type": "ලිපි වර්ගය",
  "Writing Tone": "ලිවීමේ ස්වරය",
  "Article Length": "ලිපියේ දිග",
  "SEO Options": "SEO විකල්ප",
  "Include Meta Description": "මෙටා විස්තරය ඇතුළත් කරන්න",
  "Include Keyword Suggestions": "මූල පද යෝජනා ඇතුළත් කරන්න",
  "Include FAQs Section": "නිතර අසන ප්‍රශ්න කොටස ඇතුළත් කරන්න",
  "Please enter a blog topic": "කරුණාකර බ්ලොග් මාතෘකාවක් ඇතුළු කරන්න",
  "Generate Blog": "බ්ලොග් සාදන්න",
  "SEO optimized articles with keywords": "මූල පද සහිත SEO-ප්‍රශස්ත ලිපි",
  "Write Blog": "බ්ලොග් ලියන්න",
  "YouTube Script": "YouTube පිටපත",
  "Video Topic": "වීඩියෝ මාතෘකාව",
  "Key Points (Optional)": "ප්‍රධාන කරුණු (විකල්ප)",
  "What is your video about?": "ඔබේ වීඩියෝව ගැන කුමක්ද?",
  "List key points to cover (optional)...":
      "ආවරණය කළ යුතු ප්‍රධාන කරුණු ලැයිස්තු කරන්න (විකල්ප)...",
  "Video Duration": "වීඩියෝ කාලය",
  "Script Options": "පිටපත් විකල්ප",
  "Include Hook/Intro": "හූක්/හැඳින්වීම ඇතුළත් කරන්න",
  "Include Call-to-Action": "ක්‍රියාවට කැඳවීම ඇතුළත් කරන්න",
  "Include Timestamps": "කාල මුද්‍රා ඇතුළත් කරන්න",
  "Please enter a video topic": "කරුණාකර වීඩියෝ මාතෘකාවක් ඇතුළු කරන්න",
  "Generate Script": "පිටපත සාදන්න",
  "Create scripts for videos & reels": "වීඩියෝ සහ රීල් සඳහා පිටපත් සාදන්න",
  "Create Script": "පිටපත සාදන්න",
  "Character Details": "චරිත විස්තර",
  "Character Name": "චරිත නාමය",
  "Age (e.g., 25, Young Adult, Ancient)":
      "වයස (උදා., 25, තරුණ වැඩිහිටි, පුරාණ)",
  "Personality (e.g., brave, shy, cunning)":
      "පෞරුෂය (උදා., නිර්භීත, ලජ්ජාශීලී, දක්ෂ)",
  "Role (e.g., Hero, Villain, Mentor)":
      "භූමිකාව (උදා., වීරයා, දුෂ්ටයා, මගපෙන්වන්නා)",
  "Additional Details (optional)": "අතිරේක විස්තර (විකල්ප)",
  "Output Style": "ප්‍රතිදාන ශෛලිය",
  "Generate Character": "චරිතය සාදන්න",
  "Please enter character name": "කරුණාකර චරිත නාමය ඇතුළු කරන්න",
  "Please enter character role": "කරුණාකර චරිත භූමිකාව ඇතුළු කරන්න",
  "Detailed": "සවිස්තරාත්මක",
  "Brief": "කෙටි",
  "Elaborate": "විස්තරාත්මක",
  "Select Tone": "ස්වරය තෝරන්න",
  "Rewrite Style": "නැවත ලිවීමේ ශෛලිය",
  "Output Length": "ප්‍රතිදාන දිග",
  "Please paste your story": "කරුණාකර ඔබේ කතාව අලවන්න",
  "Story is too short. Please provide more content.":
      "කතාව ඉතා කෙටිය. කරුණාකර තවත් අන්තර්ගතයක් ලබා දෙන්න.",
  "Same": "සමාන",
  "More Dramatic": "වැඩි නාට්‍යාත්මකව",
  "More Humorous": "වැඩි හාස්‍යයෙන්",
  "More Emotional": "වැඩි හැඟීම්බරව",
  "More Suspenseful": "වැඩි තතු ශෝකයෙන්",
  "Lighter": "සැහැල්ලු",
  "Improved": "වැඩිදියුණු කළ",
  "Simplified": "සරල කළ",
  "More Descriptive": "වැඩි විස්තරාත්මකව",
  "More Dialogue": "වැඩි සංවාද",
  "More Action": "වැඩි ක්‍රියා",
  "Literary": "සාහිත්‍යමය",
  "Shorter": "කෙටි",
  "Longer": "දිග",
  "Much Longer": "ඉතා දිග",
  "Rewrite Now": "දැන් නැවත ලියන්න",
  "Story/Book Topic": "කතා/පොත් මාතෘකාව",
  "Keywords (Optional)": "මූල පද (විකල්ප)",
  "Describe your story topic or theme...":
      "ඔබේ කතාවේ මාතෘකාව හෝ තේමාව විස්තර කරන්න...",
  "e.g., magic, dragon, adventure": "උදා., මායාව, මකරා, සාහසිකත්වය",
  "Title For": "සඳහා මාතෘකාව",
  "Title Style": "මාතෘකා ශෛලිය",
  "Number of Titles": "මාතෘකා ගණන",
  "Book": "පොත",
  "Short Story": "කෙටිකතාව",
  "Novel": "නවකතාව",
  "Chapter": "පරිච්ඡේදය",
  "Series": "ශ්‍රේණිය",
  "Simple": "සරල",
  "Mysterious": "රහස්‍යමය",
  "Dramatic": "නාට්‍යාත්මක",
  "Catchy": "ආකර්ෂණීය",
  "Poetic": "කාව්‍යමය",
  "Kids": "දරුවන්",
  "SEO Article": "SEO ලිපිය",
  "How-To Guide": "මාර්ගෝපදේශය",
  "Listicle": "ලැයිස්තු ලිපිය",
  "Product Review": "නිෂ්පාදන සමාලෝචනය",
  "Opinion Piece": "මතය ලිපිය",
  "News Article": "ප්‍රවෘත්ති ලිපිය",
  "Professional": "වෘත්තීය",
  "Casual": "සාමාන්‍ය",
  "Informative": "තොරතුරු සපයන",
  "Persuasive": "ඒත්තු ගන්වන",
  "Friendly": "මිත්‍රශීලී",
  "Authoritative": "ප්‍රාමාණික",
  "Short (500-800)": "කෙටි (500-800)",
  "Medium (800-1500)": "මධ්‍යම (800-1500)",
  "Long (1500-2500)": "දිග (1500-2500)",
  "Detailed (2500+)": "සවිස්තරාත්මක (2500+)",
  "Storytime": "කතා වේලාව",
  "Documentary": "වාර්තාමය",
  "Short Reel": "කෙටි රීල්",
  "Educational": "අධ්‍යාපනික",
  "Review": "සමාලෝචනය",
  "Tutorial": "ඉගෙනුම",
  "< 1 min (Shorts)": "< 1 මිනිත්තු (කෙටි)",
  "1-3 min": "1-3 මිනිත්තු",
  "5-10 min": "5-10 මිනිත්තු",
  "10-20 min": "10-20 මිනිත්තු",
  "20+ min": "20+ මිනිත්තු",
  "Engaging": "ආකර්ෂණීය",
  "Energetic": "ශක්තිමත්",
  "Calm": "සන්සුන්",
  "Funny": "විහිළු",
  "Next": "ඊළඟ",
  "Get Started": "ආරම්භ කරන්න",
  "Your tool for quick, high-quality essay writing":
      "ඉක්මන් සහ උසස් ගුණාත්මක රචනා ලිවීම සඳහා ඔබේ මෙවලම",
};
