import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sk = {
  AppKeys.lblChooseLanguage: "Vyberte jazyk",
  "All": "Všetko",
  "AI Story Generator": "AI generátor príbehov",
  "Story Generator": "Generátor príbehov",
  "Essay Writer": "Pisateľ esejí",
  "Essay length": "Dĺžka eseje",
  "Script Generator": "Generátor scenárov",
  "Create original stories in seconds":
      "Vytvorte originálne príbehy za pár sekúnd",
  "Academic writing made simple": "Akademické písanie zjednodušené",
  "Generate powerful scripts for any medium":
      "Generujte silné scenáre pre akékoľvek médium",
  "Start Writing": "Začať písať",
  "Create Now": "Vytvoriť teraz",
  "Start Generating": "Začať generovať",
  "Your Stories": "Vaše príbehy",
  "No stories yet": "Zatiaľ žiadne príbehy",
  "Start creating your first story!": "Začnite vytvárať svoj prvý príbeh!",
  "Your Story Space Awaits": "Váš priestor na príbehy čaká",
  "Start your first story and see it appear here":
      "Začnite svoj prvý príbeh a uvidíte ho tu",
  "Language": "Jazyk",
  "Rate us": "Ohodnoťte nás",
  "Share us": "Zdieľajte nás",
  "Privacy Policy": "Zásady ochrany osobných údajov",
  "Settings": "Nastavenia",
  "Select Language": "Vyberte jazyk",
  "Dashboard": "Ovládací panel",
  "BENEFITS": "VÝHODY",
  "Subscribe": "Predplatiť",
  "Weekly": "Týždenne",
  "Monthly": "Mesačne",
  "Yearly": "Ročne",
  "week": "týždeň",
  "months": "mesiace",
  "year": "rok",
  "Terms & Condition": "Podmienky a pravidlá",
  "No Commitment. Cancel anytime": "Bez záväzku. Zrušte kedykoľvek",
  "No Payment Now": "Teraz bez platby",
  "3 days free": "3 dni zadarmo",
  "Start your free trial": "Začnite bezplatnú skúšobnú verziu",
  "More detailed answers": "Podrobnejšie odpovede",
  "Instant responds": "Okamžité odpovede",
  "Text recognition": "Rozpoznávanie textu",
  "Powered by AI": "Poháňané AI",
  "Storytelleing": "Rozprávanie",
  ' Power': "Sila",
  "Unlock your \nFill ": "Odomknite svoje \nVyplňte",
  "Your History": "Vaša história",
  "Terms and Conditions": "Podmienky a pravidlá",
  "Short": "Krátky",
  "Medium": "Stredný",
  "Long": "Dlhý",
  "Length": "Dĺžka",
  "Describe your topic...": "Opíšte svoju tému...",
  "Set Creativity": "Nastaviť kreativitu",
  "Standard": "Štandardný",
  "Creative": "Kreatívny",
  "Complex": "Komplexný",
  "Select Genre": "Vyberte žáner",
  "Fantasy": "Fantasy",
  "Mystery": "Záhada",
  "Thriller": "Thriller",
  "Script Tone": "Tón scenára",
  "Script Type": "Typ scenára",
  "Comedy": "Komédia",
  "Drama": "Dráma",
  "Horror": "Horor",
  "Action": "Akcia",
  "Romance": "Romantika",
  "Go Premium": "Získať Premium",
  "Unlock Everything": "Odomknúť všetko",
  "Unlimited Story Generation": "Neobmedzené generovanie príbehov",
  "Write Longer & Detailed Essays": "Píšte dlhšie a podrobnejšie eseje",
  "Advanced Script Writer": "Pokročilý pisateľ scenárov",
  "Unlock All Styles & Tones": "Odomknúť všetky štýly a tóny",
  "No Word/Length Limit": "Bez limitu slov/dĺžky",
  "Remove All Ads": "Odstrániť všetky reklamy",
  "Restore": "Obnoviť",
  "YouTube Video": "YouTube video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivačný",
  "Advertisement": "Reklama",
  "Fairy Tale": "Rozprávka",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Vyberte štýl",
  "Imaginative": "Nápaditý",
  "Innovative": "Inovatívny",
  "AI Story Writer": "AI pisateľ príbehov",
  "Generate": "Generovať",
  "Please wait...": "Prosím čakajte...",
  "Result": "Výsledok",
  "Regenerate": "Regenerovať",
  "Download": "Stiahnuť",
  "Text copied to clipboard!": "Text skopírovaný do schránky!",
  "Please enter a topic": "Prosím zadajte tému",
  "Story Magic": "Mágia príbehov",
  "Let AI bring your thoughts to a full story":
      "Nechajte AI premeniť vaše myšlienky na celý príbeh",
  "Smart Scripts": "Inteligentné scenáre",
  "From concept to script—fast, easy, and creative":
      "Od konceptu k scenáru—rýchlo, ľahko a kreatívne",
  "Perfect Essays": "Dokonalé eseje",
  "You have reached your free limit": "Dosiahli ste bezplatný limit",
  "Donwload": "Stiahnuť",
  "Press again to exit app": "Stlačte znova pre ukončenie aplikácie",
  "Saved to files": "TXT súbor úspešne uložený!",
  "Error: Please try again": "Chyba: Skúste prosím znova",
  "Subscription expired": "Predplatné vypršalo",
  "Purchase cancelled": "Nákup zrušený",
  "Purchase failed": "Nákup zlyhal",
  "Restore failed": "Obnovenie zlyhalo",
  "Purchase Successful!": "Nákup úspešný!",
  "Short (200-500 words)": "Krátky (200-500 slov)",
  "Medium (500-1000 words)": "Stredný (500-1000 slov)",
  "Large (1000+ words)": "Dlhý (1000+ slov)",
  "Academic Level": "Akademická úroveň",
  "Type of Paper": "Typ práce",
  "High School": "Stredná škola",
  "College": "Vysoká škola",
  "Short Film": "Krátky film",
  "University": "Univerzita",
  "Masters": "Magisterské",
  "Custom": "Vlastné",
  "Tiktok Video": "Tiktok video",
  "Movie": "Film",
  "Expository": "Výkladový",
  "Argumentative": "Argumentačný",
  "Narrative": "Naratívny",
  "Descriptive": "Opisný",
  "We're sorry to hear that 😔": "Je nám ľúto, že to počujeme 😔",
  "We'll try to improve 🙁": "Budeme sa snažiť zlepšiť 🙁",
  "Thanks for your feedback 🙂": "Ďakujeme za spätnú väzbu 🙂",
  "Great! We're glad you like it 😊": "Skvelé! Sme radi, že sa vám páči 😊",
  "Awesome! Thank you so much! 🎉": "Úžasné! Ďakujeme veľmi pekne! 🎉",
  "Maybe Later": "Možno neskôr",
  "Tap a star to rate your experience":
      "Ťuknite na hviezdu pre ohodnotenie skúsenosti",
  "Enjoying AI Math Solver?": "Páči sa vám AI Math Solver?",
  "Thank you for rating us": "Ďakujeme za hodnotenie",
  "Submit Rating": "Odoslať hodnotenie",
  "Hindi": "Hindčina",
  "Enjoying AI Story Generator?": "Páči sa vám AI Story Generator?",
  "Adventure": "Dobrodružstvo",
  "Inspired": "Inšpirovaný",
  "Film Script": "Filmový scenár",
  "Stage Play": "Divadelná hra",
  "Scene Breakdown": "Analýza scény",
  "Dialogue Only": "Len dialóg",
  "Ad loading please wait..": "Reklama sa načítava, prosím čakajte...",
  "Words:": "Slová:",
  "Reading:": "Čítanie:",

  AppKeys.arabic: "Arabčina",
  AppKeys.chinese: "Čínština",
  AppKeys.english: "Angličtina",
  AppKeys.french: "Francúzština",
  AppKeys.german: "Nemčina",
  AppKeys.hindi: "Hindčina",
  AppKeys.indonesian: "Indonézština",
  AppKeys.japanese: "Japončina",
  AppKeys.korean: "Kórejčina",
  AppKeys.portuguese: "Portugalčina",
  AppKeys.russian: "Ruština",
  AppKeys.spanish: "Španielčina",
  AppKeys.turkish: "Turečtina",

  'Download As': 'Stiahnuť ako',
  'Choose format to download': 'Vyberte formát na stiahnutie',
  'Text File': 'Textový súbor',
  'PDF File': 'PDF súbor',
  'Copy': 'Kopírovať',
  'Share': 'Zdieľať',
  'Text copied!': 'Text skopírovaný!',
  'Copied to clipboard': 'Skopírované do schránky',
  'File saved successfully': 'Súbor úspešne uložený',
  'Error saving file': 'Chyba pri ukladaní súboru',
  'Share Story': 'Zdieľať príbeh',
  'Export': 'Exportovať',

  "Character Story": "Príbeh postavy",
  "Create detailed character backstories": "Vytvorte podrobné zázemie postáv",
  "Create Character": "Vytvoriť postavu",
  "Rewrite Story": "Prepísať príbeh",
  "Paste Your Story": "Vložte váš príbeh",
  "Paste your story here to rewrite...":
      "Vložte váš príbeh sem na prepísanie...",
  "Transform and improve your existing stories":
      "Transformujte a vylepšite svoje existujúce príbehy",
  "Title Generator": "Generátor názvov",
  "Generate catchy titles for your stories":
      "Generujte chytľavé názvy pre vaše príbehy",
  "Generate Titles": "Generovať názvy",
  "Blog Writer": "Autor blogu",
  "Blog Topic": "Téma blogu",
  "Target Keywords": "Cieľové kľúčové slová",
  "Target Audience (Optional)": "Cieľové publikum (Voliteľné)",
  "Enter your blog topic or title...":
      "Zadajte tému alebo názov vášho blogu...",
  "e.g., AI writing, content marketing, SEO tips":
      "napr. písanie s AI, obsahový marketing, tipy na SEO",
  "e.g., small business owners, bloggers":
      "napr. majitelia malých firiem, blogeri",
  "Article Type": "Typ článku",
  "Writing Tone": "Tón písania",
  "Article Length": "Dĺžka článku",
  "SEO Options": "Možnosti SEO",
  "Include Meta Description": "Zahrnúť meta popis",
  "Include Keyword Suggestions": "Zahrnúť návrhy kľúčových slov",
  "Include FAQs Section": "Zahrnúť sekciu FAQ",
  "Please enter a blog topic": "Zadajte tému blogu",
  "Generate Blog": "Generovať blog",
  "SEO optimized articles with keywords":
      "Články optimalizované pre SEO s kľúčovými slovami",
  "Write Blog": "Napísať blog",
  "YouTube Script": "YouTube scenár",
  "Video Topic": "Téma videa",
  "Key Points (Optional)": "Kľúčové body (Voliteľné)",
  "What is your video about?": "O čom je vaše video?",
  "List key points to cover (optional)...":
      "Vypíšte kľúčové body (voliteľné)...",
  "Video Duration": "Trvanie videa",
  "Script Options": "Možnosti scenára",
  "Include Hook/Intro": "Zahrnúť háčik/intro",
  "Include Call-to-Action": "Zahrnúť výzvu na akciu",
  "Include Timestamps": "Zahrnúť časové pečiatky",
  "Please enter a video topic": "Zadajte tému videa",
  "Generate Script": "Generovať scenár",
  "Create scripts for videos & reels": "Vytvorte scenáre pre videá a reels",
  "Create Script": "Vytvoriť scenár",
  "Character Details": "Detaily postavy",
  "Character Name": "Meno postavy",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Vek (napr. 25, Mladý dospelý, Staroveký)",
  "Personality (e.g., brave, shy, cunning)":
      "Osobnosť (napr. odvážny, hanblivý, prefíkaný)",
  "Role (e.g., Hero, Villain, Mentor)": "Rola (napr. Hrdina, Záporák, Mentor)",
  "Additional Details (optional)": "Ďalšie podrobnosti (voliteľné)",
  "Output Style": "Štýl výstupu",
  "Generate Character": "Generovať postavu",
  "Please enter character name": "Zadajte meno postavy",
  "Please enter character role": "Zadajte rolu postavy",
  "Detailed": "Podrobný",
  "Brief": "Stručný",
  "Elaborate": "Rozvinutý",
  "Select Tone": "Vybrať tón",
  "Rewrite Style": "Štýl prepísania",
  "Output Length": "Dĺžka výstupu",
  "Please paste your story": "Vložte váš príbeh",
  "Story is too short. Please provide more content.":
      "Príbeh je príliš krátky. Poskytnite viac obsahu.",
  "Same": "Rovnaký",
  "More Dramatic": "Dramatickejší",
  "More Humorous": "Humoristickejší",
  "More Emotional": "Emocionálnejší",
  "More Suspenseful": "Napínavejší",
  "Lighter": "Ľahší",
  "Improved": "Vylepšený",
  "Simplified": "Zjednodušený",
  "More Descriptive": "Opisnejší",
  "More Dialogue": "Viac dialógov",
  "More Action": "Viac akcie",
  "Literary": "Literárny",
  "Shorter": "Kratší",
  "Longer": "Dlhší",
  "Much Longer": "Oveľa dlhší",
  "Rewrite Now": "Prepísať teraz",
  "Story/Book Topic": "Téma príbehu/knihy",
  "Keywords (Optional)": "Kľúčové slová (Voliteľné)",
  "Describe your story topic or theme...":
      "Opíšte tému alebo motív vášho príbehu...",
  "e.g., magic, dragon, adventure": "napr. mágia, drak, dobrodružstvo",
  "Title For": "Názov pre",
  "Title Style": "Štýl názvu",
  "Number of Titles": "Počet názvov",
  "Book": "Kniha",
  "Short Story": "Poviedka",
  "Novel": "Román",
  "Chapter": "Kapitola",
  "Series": "Séria",
  "Simple": "Jednoduchý",
  "Mysterious": "Tajomný",
  "Dramatic": "Dramatický",
  "Catchy": "Chytľavý",
  "Poetic": "Poetický",
  "Kids": "Pre deti",
  "SEO Article": "SEO článok",
  "How-To Guide": "Návod",
  "Listicle": "Zoznamový článok",
  "Product Review": "Recenzia produktu",
  "Opinion Piece": "Názorový článok",
  "News Article": "Spravodajský článok",
  "Professional": "Profesionálny",
  "Casual": "Neformálny",
  "Informative": "Informatívny",
  "Persuasive": "Presvedčivý",
  "Friendly": "Priateľský",
  "Authoritative": "Autoritatívny",
  "Short (500-800)": "Krátky (500-800)",
  "Medium (800-1500)": "Stredný (800-1500)",
  "Long (1500-2500)": "Dlhý (1500-2500)",
  "Detailed (2500+)": "Podrobný (2500+)",
  "Storytime": "Čas na príbehy",
  "Documentary": "Dokumentárny",
  "Short Reel": "Krátky reel",
  "Educational": "Vzdelávací",
  "Review": "Recenzia",
  "Tutorial": "Návod",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Pútavý",
  "Energetic": "Energický",
  "Calm": "Pokojný",
  "Funny": "Vtipný",
  "Next": "Ďalej",
  "Get Started": "Začať",
  "Your tool for quick, high-quality essay writing":
      "Váš nástroj na rýchle a kvalitné písanie esejí",
};
