import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sl = {
  AppKeys.lblChooseLanguage: "Izberite jezik",
  "All": "Vse",
  "AI Story Generator": "AI generator zgodb",
  "Story Generator": "Generator zgodb",
  "Essay Writer": "Pisec esejev",
  "Essay length": "Dolžina eseja",
  "Script Generator": "Generator scenarijev",
  "Create original stories in seconds":
      "Ustvarite izvirne zgodbe v nekaj sekundah",
  "Academic writing made simple": "Akademsko pisanje poenostavljeno",
  "Generate powerful scripts for any medium":
      "Generirajte močne scenarije za kateri koli medij",
  "Start Writing": "Začni pisati",
  "Create Now": "Ustvari zdaj",
  "Start Generating": "Začni generirati",
  "Your Stories": "Vaše zgodbe",
  "No stories yet": "Še ni zgodb",
  "Start creating your first story!": "Začnite ustvarjati svojo prvo zgodbo!",
  "Your Story Space Awaits": "Vaš prostor za zgodbe čaka",
  "Start your first story and see it appear here":
      "Začnite svojo prvo zgodbo in jo vidite tukaj",
  "Language": "Jezik",
  "Rate us": "Ocenite nas",
  "Share us": "Delite nas",
  "Privacy Policy": "Politika zasebnosti",
  "Settings": "Nastavitve",
  "Select Language": "Izberite jezik",
  "Dashboard": "Nadzorna plošča",
  "BENEFITS": "PREDNOSTI",
  "Subscribe": "Naročite se",
  "Weekly": "Tedensko",
  "Monthly": "Mesečno",
  "Yearly": "Letno",
  "week": "teden",
  "months": "meseci",
  "year": "leto",
  "Terms & Condition": "Pogoji in pravila",
  "No Commitment. Cancel anytime": "Brez obveznosti. Prekličite kadarkoli",
  "No Payment Now": "Zdaj brez plačila",
  "3 days free": "3 dni brezplačno",
  "Start your free trial": "Začnite brezplačno preizkusno obdobje",
  "More detailed answers": "Podrobnejši odgovori",
  "Instant responds": "Takojšnji odgovori",
  "Text recognition": "Prepoznavanje besedila",
  "Powered by AI": "Poganja AI",
  "Storytelleing": "Pripovedovanje",
  ' Power': "Moč",
  "Unlock your \nFill ": "Odklenite svoje \nIzpolnite",
  "Your History": "Vaša zgodovina",
  "Terms and Conditions": "Pogoji in pravila",
  "Short": "Kratko",
  "Medium": "Srednje",
  "Long": "Dolgo",
  "Length": "Dolžina",
  "Describe your topic...": "Opišite svojo temo...",
  "Set Creativity": "Nastavite kreativnost",
  "Standard": "Standardno",
  "Creative": "Kreativno",
  "Complex": "Kompleksno",
  "Select Genre": "Izberite zvrst",
  "Fantasy": "Fantazija",
  "Mystery": "Skrivnost",
  "Thriller": "Triler",
  "Script Tone": "Ton scenarija",
  "Script Type": "Tip scenarija",
  "Comedy": "Komedija",
  "Drama": "Drama",
  "Horror": "Grozljivka",
  "Action": "Akcija",
  "Romance": "Romantika",
  "Go Premium": "Pridobite Premium",
  "Unlock Everything": "Odklenite vse",
  "Unlimited Story Generation": "Neomejeno generiranje zgodb",
  "Write Longer & Detailed Essays": "Pišite daljše in podrobnejše eseje",
  "Advanced Script Writer": "Napredni pisec scenarijev",
  "Unlock All Styles & Tones": "Odklenite vse sloge in tone",
  "No Word/Length Limit": "Brez omejitve besed/dolžine",
  "Remove All Ads": "Odstranite vse oglase",
  "Restore": "Obnovi",
  "YouTube Video": "YouTube video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivacijski",
  "Advertisement": "Oglas",
  "Fairy Tale": "Pravljica",
  "Sci-Fi": "Znanstvena fantastika",
  "Select Style": "Izberite slog",
  "Imaginative": "Domišljijski",
  "Innovative": "Inovativen",
  "AI Story Writer": "AI pisec zgodb",
  "Generate": "Generiraj",
  "Please wait...": "Prosimo počakajte...",
  "Result": "Rezultat",
  "Regenerate": "Regeneriraj",
  "Download": "Prenesi",
  "Text copied to clipboard!": "Besedilo kopirano v odložišče!",
  "Please enter a topic": "Prosimo vnesite temo",
  "Story Magic": "Čarovnija zgodb",
  "Let AI bring your thoughts to a full story":
      "Naj AI pretvori vaše misli v celotno zgodbo",
  "Smart Scripts": "Pametni scenariji",
  "From concept to script—fast, easy, and creative":
      "Od koncepta do scenarija—hitro, enostavno in kreativno",
  "Perfect Essays": "Popolni eseji",
  "You have reached your free limit": "Dosegli ste brezplačno omejitev",
  "Donwload": "Prenesi",
  "Press again to exit app": "Pritisnite znova za izhod iz aplikacije",
  "Saved to files": "TXT datoteka uspešno shranjena!",
  "Error: Please try again": "Napaka: Prosimo poskusite znova",
  "Subscription expired": "Naročnina je potekla",
  "Purchase cancelled": "Nakup preklican",
  "Purchase failed": "Nakup ni uspel",
  "Restore failed": "Obnovitev ni uspela",
  "Purchase Successful!": "Nakup uspešen!",
  "Short (200-500 words)": "Kratko (200-500 besed)",
  "Medium (500-1000 words)": "Srednje (500-1000 besed)",
  "Large (1000+ words)": "Dolgo (1000+ besed)",
  "Academic Level": "Akademska raven",
  "Type of Paper": "Vrsta dela",
  "High School": "Srednja šola",
  "College": "Fakulteta",
  "Short Film": "Kratki film",
  "University": "Univerza",
  "Masters": "Magisterij",
  "Custom": "Po meri",
  "Tiktok Video": "Tiktok video",
  "Movie": "Film",
  "Expository": "Razlagalni",
  "Argumentative": "Argumentacijski",
  "Narrative": "Pripovedni",
  "Descriptive": "Opisni",
  "We're sorry to hear that 😔": "Žal nam je to slišati 😔",
  "We'll try to improve 🙁": "Trudili se bomo izboljšati 🙁",
  "Thanks for your feedback 🙂": "Hvala za povratne informacije 🙂",
  "Great! We're glad you like it 😊": "Odlično! Veseli smo, da vam je všeč 😊",
  "Awesome! Thank you so much! 🎉": "Super! Najlepša hvala! 🎉",
  "Maybe Later": "Morda kasneje",
  "Tap a star to rate your experience": "Tapnite zvezdico za oceno izkušnje",
  "Enjoying AI Math Solver?": "Vam je všeč AI Math Solver?",
  "Thank you for rating us": "Hvala za oceno",
  "Submit Rating": "Pošlji oceno",
  "Hindi": "Hindujščina",
  "Enjoying AI Story Generator?": "Vam je všeč AI Story Generator?",
  "Adventure": "Pustolovščina",
  "Inspired": "Navdihnjen",
  "Film Script": "Filmski scenarij",
  "Stage Play": "Gledališka igra",
  "Scene Breakdown": "Analiza scene",
  "Dialogue Only": "Samo dialog",
  "Ad loading please wait..": "Oglas se nalaga, prosimo počakajte...",
  "Words:": "Besede:",
  "Reading:": "Branje:",

  AppKeys.arabic: "Arabščina",
  AppKeys.chinese: "Kitajščina",
  AppKeys.english: "Angleščina",
  AppKeys.french: "Francoščina",
  AppKeys.german: "Nemščina",
  AppKeys.hindi: "Hindujščina",
  AppKeys.indonesian: "Indonezijščina",
  AppKeys.japanese: "Japonščina",
  AppKeys.korean: "Korejščina",
  AppKeys.portuguese: "Portugalščina",
  AppKeys.russian: "Ruščina",
  AppKeys.spanish: "Španščina",
  AppKeys.turkish: "Turščina",

  'Download As': 'Prenesi kot',
  'Choose format to download': 'Izberite format za prenos',
  'Text File': 'Besedilna datoteka',
  'PDF File': 'PDF datoteka',
  'Copy': 'Kopiraj',
  'Share': 'Deli',
  'Text copied!': 'Besedilo kopirano!',
  'Copied to clipboard': 'Kopirano v odložišče',
  'File saved successfully': 'Datoteka uspešno shranjena',
  'Error saving file': 'Napaka pri shranjevanju datoteke',
  'Share Story': 'Deli zgodbo',
  'Export': 'Izvozi',

  "Character Story": "Zgodba lika",
  "Create detailed character backstories":
      "Ustvarite podrobne ozadnje zgodbe likov",
  "Create Character": "Ustvari lik",
  "Rewrite Story": "Prepiši zgodbo",
  "Paste Your Story": "Prilepite svojo zgodbo",
  "Paste your story here to rewrite...":
      "Prilepite svojo zgodbo sem za prepisovanje...",
  "Transform and improve your existing stories":
      "Preoblikujte in izboljšajte obstoječe zgodbe",
  "Title Generator": "Generator naslovov",
  "Generate catchy titles for your stories":
      "Ustvarite privlačne naslove za svoje zgodbe",
  "Generate Titles": "Ustvari naslove",
  "Blog Writer": "Pisec blogov",
  "Blog Topic": "Tema bloga",
  "Target Keywords": "Ciljne ključne besede",
  "Target Audience (Optional)": "Ciljna publika (Neobvezno)",
  "Enter your blog topic or title...":
      "Vnesite temo ali naslov svojega bloga...",
  "e.g., AI writing, content marketing, SEO tips":
      "npr. pisanje z AI, vsebinski marketing, nasveti za SEO",
  "e.g., small business owners, bloggers":
      "npr. lastniki malih podjetij, blogerji",
  "Article Type": "Vrsta članka",
  "Writing Tone": "Ton pisanja",
  "Article Length": "Dolžina članka",
  "SEO Options": "Možnosti SEO",
  "Include Meta Description": "Vključi meta opis",
  "Include Keyword Suggestions": "Vključi predloge ključnih besed",
  "Include FAQs Section": "Vključi razdelek FAQ",
  "Please enter a blog topic": "Prosimo, vnesite temo bloga",
  "Generate Blog": "Ustvari blog",
  "SEO optimized articles with keywords":
      "SEO optimizirani članki s ključnimi besedami",
  "Write Blog": "Napiši blog",
  "YouTube Script": "YouTube scenarij",
  "Video Topic": "Tema videa",
  "Key Points (Optional)": "Ključne točke (Neobvezno)",
  "What is your video about?": "O čem je vaš video?",
  "List key points to cover (optional)...":
      "Navedite ključne točke (neobvezno)...",
  "Video Duration": "Trajanje videa",
  "Script Options": "Možnosti scenarija",
  "Include Hook/Intro": "Vključi kavelj/uvod",
  "Include Call-to-Action": "Vključi poziv k dejanju",
  "Include Timestamps": "Vključi časovne žige",
  "Please enter a video topic": "Prosimo, vnesite temo videa",
  "Generate Script": "Ustvari scenarij",
  "Create scripts for videos & reels":
      "Ustvarite scenarije za videoposnetke in reele",
  "Create Script": "Ustvari scenarij",
  "Character Details": "Podrobnosti lika",
  "Character Name": "Ime lika",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Starost (npr. 25, Mlad odrasel, Antični)",
  "Personality (e.g., brave, shy, cunning)":
      "Osebnost (npr. pogumen, sramežljiv, zvit)",
  "Role (e.g., Hero, Villain, Mentor)": "Vloga (npr. Junak, Zlobnež, Mentor)",
  "Additional Details (optional)": "Dodatne podrobnosti (neobvezno)",
  "Output Style": "Slog izhoda",
  "Generate Character": "Ustvari lik",
  "Please enter character name": "Prosimo, vnesite ime lika",
  "Please enter character role": "Prosimo, vnesite vlogo lika",
  "Detailed": "Podroben",
  "Brief": "Kratek",
  "Elaborate": "Razdelan",
  "Select Tone": "Izberi ton",
  "Rewrite Style": "Slog prepisovanja",
  "Output Length": "Dolžina izhoda",
  "Please paste your story": "Prosimo, prilepite svojo zgodbo",
  "Story is too short. Please provide more content.":
      "Zgodba je prekratka. Prosimo, dodajte več vsebine.",
  "Same": "Enako",
  "More Dramatic": "Bolj dramatično",
  "More Humorous": "Bolj humoristično",
  "More Emotional": "Bolj čustveno",
  "More Suspenseful": "Bolj napeto",
  "Lighter": "Lažje",
  "Improved": "Izboljšano",
  "Simplified": "Poenostavljeno",
  "More Descriptive": "Bolj opisno",
  "More Dialogue": "Več dialogov",
  "More Action": "Več akcije",
  "Literary": "Literarno",
  "Shorter": "Krajše",
  "Longer": "Daljše",
  "Much Longer": "Veliko daljše",
  "Rewrite Now": "Prepiši zdaj",
  "Story/Book Topic": "Tema zgodbe/knjige",
  "Keywords (Optional)": "Ključne besede (Neobvezno)",
  "Describe your story topic or theme...":
      "Opišite temo ali motiv svoje zgodbe...",
  "e.g., magic, dragon, adventure": "npr. magija, zmaj, pustolovščina",
  "Title For": "Naslov za",
  "Title Style": "Slog naslova",
  "Number of Titles": "Število naslovov",
  "Book": "Knjiga",
  "Short Story": "Kratka zgodba",
  "Novel": "Roman",
  "Chapter": "Poglavje",
  "Series": "Serija",
  "Simple": "Preprost",
  "Mysterious": "Skrivnosten",
  "Dramatic": "Dramatičen",
  "Catchy": "Privlačen",
  "Poetic": "Poetičen",
  "Kids": "Za otroke",
  "SEO Article": "SEO članek",
  "How-To Guide": "Navodila",
  "Listicle": "Členek s seznamom",
  "Product Review": "Ocena izdelka",
  "Opinion Piece": "Mnenjski prispevek",
  "News Article": "Novičarski članek",
  "Professional": "Profesionalen",
  "Casual": "Neformalen",
  "Informative": "Informativen",
  "Persuasive": "Prepričljiv",
  "Friendly": "Prijazen",
  "Authoritative": "Avtoritativen",
  "Short (500-800)": "Kratek (500-800)",
  "Medium (800-1500)": "Srednji (800-1500)",
  "Long (1500-2500)": "Dolg (1500-2500)",
  "Detailed (2500+)": "Podroben (2500+)",
  "Storytime": "Čas za zgodbe",
  "Documentary": "Dokumentarec",
  "Short Reel": "Kratek reel",
  "Educational": "Izobraževalen",
  "Review": "Ocena",
  "Tutorial": "Vadnica",
  "< 1 min (Shorts)": "< 1 min (Kratki)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Privlačno",
  "Energetic": "Energično",
  "Calm": "Mirno",
  "Funny": "Smešno",
  "Next": "Naprej",
  "Get Started": "Začni",
  "Your tool for quick, high-quality essay writing":
      "Vaše orodje za hitro in kakovostno pisanje esejev",
};
