import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sq = {
  AppKeys.lblChooseLanguage: "Zgjidhni Gjuhën",

  AppKeys.arabic: "Arabisht",
  AppKeys.chinese: "Kinezisht",
  AppKeys.english: "Anglisht",
  AppKeys.french: "Frëngjisht",
  AppKeys.german: "Gjermanisht",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonezisht",
  AppKeys.japanese: "Japonisht",
  AppKeys.korean: "Koreanisht",
  AppKeys.portuguese: "Portugalisht",
  AppKeys.russian: "Rusisht",
  AppKeys.spanish: "Spanjisht",
  AppKeys.turkish: "Turqisht",
  AppKeys.btnNext: "Tjetër",
  AppKeys.dahsboard: "Paneli",
  AppKeys.yourStories: "Historitë Tuaja",
  AppKeys.setting: "Cilësimet",
  AppKeys.btngetStarted: "Fillo",
  '': "Fillo",

  // New strings for download & actions
  'Download As': 'Shkarko Si',
  'Choose format to download': 'Zgjidhni formatin për shkarkim',
  'Text File': 'Skedar Teksti',
  'PDF File': 'Skedar PDF',
  'Copy': 'Kopjo',
  'Share': 'Ndaj',
  'Download': 'Shkarko',
  'Text copied!': 'Teksti u kopjua!',
  'PDF saved successfully!': 'PDF u ruajt me sukses!',
  'Saved to files': 'U ruajt në skedarë',
  'Error: Please try again': 'Gabim: Ju lutem provoni përsëri',
  'Error creating PDF: Please try again':
      'Gabim në krijimin e PDF: Ju lutem provoni përsëri',

  // Character Story Tool
  'Character Story': 'Historia e Personazhit',
  'Character Details': 'Detajet e Personazhit',
  'Character Name': 'Emri i Personazhit',
  'Age (e.g., 25, Young Adult, Ancient)': 'Mosha (p.sh., 25, I Ri, I Lashtë)',
  'Personality (e.g., brave, shy, cunning)':
      'Personaliteti (p.sh., trim, i turpshëm, dinak)',
  'Role (e.g., Hero, Villain, Mentor)': 'Roli (p.sh., Hero, Zuzar, Mentor)',
  'Additional Details (optional)': 'Detaje Shtesë (opsionale)',
  'Select Genre': 'Zgjidhni Zhanrin',
  'Output Style': 'Stili i Daljes',
  'Generate Character': 'Gjenero Personazhin',
  'Please enter character name': 'Ju lutem vendosni emrin e personazhit',
  'Please enter character role': 'Ju lutem vendosni rolin e personazhit',
  // Genres
  'Fantasy': 'Fantazi',
  'Sci-Fi': 'Shkencë-Fantastike',
  'Romance': 'Romancë',
  'Horror': 'Horror',
  'Comedy': 'Komedi',
  'Drama': 'Dramë',
  'Adventure': 'Aventurë',
  // Output Styles
  'Detailed': 'I Detajuar',
  'Brief': 'I Shkurtër',
  'Elaborate': 'I Hollësishëm',

  // Home Screen Tool Cards
  'Create detailed character backstories':
      'Krijo histori të hollësishme të personazheve',
  'Create Character': 'Krijo Personazh',
  'Transform and improve your existing stories':
      'Transformo dhe përmirëso historitë ekzistuese',
  'Rewrite Now': 'Rishkruaj Tani',
  'Generate catchy titles for your stories':
      'Gjenero tituj tërheqës për historitë tuaja',
  'Generate Titles': 'Gjenero Tituj',

  // Rewrite Story Tool
  'Rewrite Story': 'Rishkruaj Historinë',
  'Paste Your Story': 'Ngjit Historinë Tënde',
  'Paste your story here to rewrite...':
      'Ngjit historinë këtu për ta rishkruar...',
  'Select Tone': 'Zgjidhni Tonin',
  'Rewrite Style': 'Stili i Rishkrimit',
  'Output Length': 'Gjatësia e Daljes',
  'Please paste your story': 'Ju lutem ngjitni historinë tuaj',
  'Story is too short. Please provide more content.':
      'Historia është shumë e shkurtër. Ju lutem jepni më shumë përmbajtje.',
  // Tone options
  'Same': 'I Njëjtë',
  'More Dramatic': 'Më Dramatik',
  'More Humorous': 'Më Humoristik',
  'More Emotional': 'Më Emocional',
  'More Suspenseful': 'Më Suspensiv',
  'Lighter': 'Më i Lehtë',
  // Style options
  'Improved': 'I Përmirësuar',
  'Simplified': 'I Thjeshtuar',
  'More Descriptive': 'Më Përshkrues',
  'More Dialogue': 'Më Shumë Dialog',
  'More Action': 'Më Shumë Aksion',
  'Literary': 'Letrar',
  // Length options
  'Shorter': 'Më i Shkurtër',
  'Longer': 'Më i Gjatë',
  'Much Longer': 'Shumë Më i Gjatë',

  // Title Generator Tool
  'Title Generator': 'Gjenerues Titujsh',
  'Story/Book Topic': 'Tema e Historisë/Librit',
  'Keywords (Optional)': 'Fjalë Kyçe (Opsionale)',
  'Describe your story topic or theme...':
      'Përshkruani temën e historisë suaj...',
  'e.g., magic, dragon, adventure': 'p.sh., magji, dragua, aventurë',
  'Title For': 'Titulli Për',
  'Title Style': 'Stili i Titullit',
  'Number of Titles': 'Numri i Titujve',
  'Please enter a topic': 'Ju lutem vendosni një temë',
  // Type options
  'Book': 'Libër',
  'Short Story': 'Tregim i Shkurtër',
  'Novel': 'Roman',
  'Chapter': 'Kapitull',
  'Series': 'Seri',
  // Style options
  'Creative': 'Kreativ',
  'Simple': 'I Thjeshtë',
  'Mysterious': 'Misterioz',
  'Dramatic': 'Dramatik',
  'Catchy': 'Tërheqës',
  'Poetic': 'Poetik',
  // Genre options
  'Mystery': 'Mister',
  'Thriller': 'Thriller',
  'Kids': 'Fëmijë',

  // Blog Writer Tool
  'Blog Writer': 'Shkrimtar Blogu',
  'Blog Topic': 'Tema e Blogut',
  'Target Keywords': 'Fjalë Kyçe Synuese',
  'Target Audience (Optional)': 'Audienca e Synuar (Opsionale)',
  'Enter your blog topic or title...':
      'Vendosni temën ose titullin e blogut...',
  'e.g., AI writing, content marketing, SEO tips':
      'p.sh., shkrim me IA, marketing përmbajtje, këshilla SEO',
  'e.g., small business owners, bloggers':
      'p.sh., pronarë biznesi të vogla, blogjerë',
  'Article Type': 'Lloji i Artikullit',
  'Writing Tone': 'Toni i Shkrimit',
  'Article Length': 'Gjatësia e Artikullit',
  'SEO Options': 'Opsionet SEO',
  'Include Meta Description': 'Përfshi Meta Përshkrimin',
  'Include Keyword Suggestions': 'Përfshi Sugjerime Fjalësh Kyçe',
  'Include FAQs Section': 'Përfshi Seksionin FAQ',
  'Please enter a blog topic': 'Ju lutem vendosni një temë blogu',
  'Generate Blog': 'Gjenero Blogun',
  'SEO optimized articles with keywords':
      'Artikuj të optimizuar për SEO me fjalë kyçe',
  'Write Blog': 'Shkruaj Blog',
  // Article Types
  'SEO Article': 'Artikull SEO',
  'How-To Guide': 'Udhëzues Si-Të',
  'Listicle': 'Listikulli',
  'Product Review': 'Recensim Produkti',
  'Opinion Piece': 'Artikull Opinioni',
  'News Article': 'Artikull Lajmesh',
  // Blog Tones
  'Professional': 'Profesional',
  'Casual': 'Rastësor',
  'Informative': 'Informativ',
  'Persuasive': 'Bindës',
  'Friendly': 'Miqësor',
  'Authoritative': 'Autoritar',
  // Blog Lengths
  'Short (500-800)': 'I Shkurtër (500-800)',
  'Medium (800-1500)': 'Mesatar (800-1500)',
  'Long (1500-2500)': 'I Gjatë (1500-2500)',
  'Detailed (2500+)': 'I Detajuar (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'Skenari YouTube',
  'Script Type': 'Lloji i Skenarit',
  'Video Topic': 'Tema e Videos',
  'Key Points (Optional)': 'Pikat Kyçe (Opsionale)',
  'What is your video about?': 'Për çfarë është videoja juaj?',
  'List key points to cover (optional)...':
      'Listoni pikat kyçe për të mbuluar (opsionale)...',
  'Video Duration': 'Kohëzgjatja e Videos',
  'Script Tone': 'Toni i Skenarit',
  'Script Options': 'Opsionet e Skenarit',
  'Include Hook/Intro': 'Përfshi Grepin/Hyrjen',
  'Include Call-to-Action': 'Përfshi Thirrjen për Veprim',
  'Include Timestamps': 'Përfshi Vulat Kohore',
  'Please enter a video topic': 'Ju lutem vendosni një temë videoje',
  'Generate Script': 'Gjenero Skenarin',
  'Create scripts for videos & reels': 'Krijo skenarë për video dhe reels',
  'Create Script': 'Krijo Skenar',
  // Script Types
  'Storytime': 'Koha e Historisë',
  'Documentary': 'Dokumentar',
  'Short Reel': 'Reel i Shkurtër',
  'Motivational': 'Motivues',
  'Educational': 'Edukativ',
  'Review': 'Recensim',
  'Tutorial': 'Tutorial',
  // Durations
  '< 1 min (Shorts)': '< 1 min (Shorts)',
  '1-3 min': '1-3 min',
  '5-10 min': '5-10 min',
  '10-20 min': '10-20 min',
  '20+ min': '20+ min',
  // Script Tones
  'Engaging': 'Angazhues',
  'Energetic': 'Energjik',
  'Calm': 'I Qetë',
  'Funny': 'Qesharak',

  // Story Generator - Styles
  'Inspired': 'I Frymëzuar',
  'Standard': 'Standard',
  'Imaginative': 'Imagjinativ',
  'Innovative': 'Inovativ',

  // Script Writer - Script Tones (formats)
  'Short Film': 'Film i Shkurtër',
  'Film Script': 'Skenar Filmi',
  'Stage Play': 'Dramë Skenike',
  'Advertisement': 'Reklamë',
  'Tiktok Video': 'Video Tiktok',
  'Movie': 'Film',
  'Scene Breakdown': 'Zbërthim Skene',
  'Dialogue Only': 'Vetëm Dialog',

  // Script Writer - Script Types
  'Action': 'Aksion',
  'Fairy Tale': 'Përrallë',

  // Ad & UI
  'Ad loading please wait..': 'Reklama po ngarkohet, ju lutem prisni..',

  // Word Counter & Reading Time
  'Words:': 'Fjalë:',
  'Reading:': 'Lexim:',

  "Character Story": "Historia e personazhit",
  "Create detailed character backstories":
      "Krijoni histori të detajuara të sfondit të personazhit",
  "Create Character": "Krijo personazh",
  "Rewrite Story": "Rishkruaj historinë",
  "Paste Your Story": "Ngjit historinë tuaj",
  "Paste your story here to rewrite...":
      "Ngjit historinë tuaj këtu për ta rishkruar...",
  "Transform and improve your existing stories":
      "Transformoni dhe përmirësoni historitë tuaja ekzistuese",
  "Title Generator": "Gjenerues titujsh",
  "Generate catchy titles for your stories":
      "Gjeneroni tituj tërheqës për historitë tuaja",
  "Generate Titles": "Gjenero tituj",
  "Blog Writer": "Shkrues blogu",
  "Blog Topic": "Tema e blogut",
  "Target Keywords": "Fjalë kyçe të synuara",
  "Target Audience (Optional)": "Audienca e synuar (Opsionale)",
  "Enter your blog topic or title...":
      "Shkruani temën ose titullin e blogut tuaj...",
  "e.g., AI writing, content marketing, SEO tips":
      "p.sh., shkrimi me AI, marketing i përmbajtjes, këshilla SEO",
  "e.g., small business owners, bloggers":
      "p.sh., pronarë të bizneseve të vogla, blogerë",
  "Article Type": "Lloji i artikullit",
  "Writing Tone": "Toni i shkrimit",
  "Article Length": "Gjatësia e artikullit",
  "SEO Options": "Opsionet SEO",
  "Include Meta Description": "Përfshi meta përshkrimin",
  "Include Keyword Suggestions": "Përfshi sugjerime fjalësh kyçe",
  "Include FAQs Section": "Përfshi seksionin FAQ",
  "Please enter a blog topic": "Ju lutemi shkruani temën e blogut",
  "Generate Blog": "Gjenero blog",
  "SEO optimized articles with keywords":
      "Artikuj të optimizuar SEO me fjalë kyçe",
  "Write Blog": "Shkruaj blog",
  "YouTube Script": "Skenar YouTube",
  "Video Topic": "Tema e videos",
  "Key Points (Optional)": "Pikat kryesore (Opsionale)",
  "What is your video about?": "Për çfarë është videoja juaj?",
  "List key points to cover (optional)...":
      "Listoni pikat kryesore për të mbuluar (opsionale)...",
  "Video Duration": "Kohëzgjatja e videos",
  "Script Options": "Opsionet e skenarit",
  "Include Hook/Intro": "Përfshi grepin/intro",
  "Include Call-to-Action": "Përfshi thirrjen për veprim",
  "Include Timestamps": "Përfshi vulat kohore",
  "Please enter a video topic": "Ju lutemi shkruani temën e videos",
  "Generate Script": "Gjenero skenar",
  "Create scripts for videos & reels": "Krijoni skenarë për video dhe reels",
  "Create Script": "Krijo skenar",
  "Character Details": "Detajet e personazhit",
  "Character Name": "Emri i personazhit",
  "Age (e.g., 25, Young Adult, Ancient)": "Mosha (p.sh., 25, I ri, Antik)",
  "Personality (e.g., brave, shy, cunning)":
      "Personaliteti (p.sh., guximtar, i turpshëm, dinak)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Roli (p.sh., Hero, Antagonist, Mentor)",
  "Additional Details (optional)": "Detaje shtesë (opsionale)",
  "Output Style": "Stili i daljes",
  "Generate Character": "Gjenero personazh",
  "Please enter character name": "Ju lutemi shkruani emrin e personazhit",
  "Please enter character role": "Ju lutemi shkruani rolin e personazhit",
  "Detailed": "I detajuar",
  "Brief": "I shkurtër",
  "Elaborate": "I elaboruar",
  "Select Tone": "Zgjidhni tonin",
  "Rewrite Style": "Stili i rishkrimit",
  "Output Length": "Gjatësia e daljes",
  "Please paste your story": "Ju lutemi ngjitni historinë tuaj",
  "Story is too short. Please provide more content.":
      "Historia është shumë e shkurtër. Ju lutemi jepni më shumë përmbajtje.",
  "Same": "E njëjtë",
  "More Dramatic": "Më dramatike",
  "More Humorous": "Më humoristike",
  "More Emotional": "Më emocionale",
  "More Suspenseful": "Më e tensionuar",
  "Lighter": "Më e lehtë",
  "Improved": "E përmirësuar",
  "Simplified": "E thjeshtësuar",
  "More Descriptive": "Më përshkruese",
  "More Dialogue": "Më shumë dialog",
  "More Action": "Më shumë veprim",
  "Literary": "Letrare",
  "Shorter": "Më e shkurtër",
  "Longer": "Më e gjatë",
  "Much Longer": "Shumë më e gjatë",
  "Rewrite Now": "Rishkruaj tani",
  "Story/Book Topic": "Tema e historisë/librit",
  "Keywords (Optional)": "Fjalë kyçe (Opsionale)",
  "Describe your story topic or theme...":
      "Përshkruani temën ose motivin e historisë tuaj...",
  "e.g., magic, dragon, adventure": "p.sh., magji, dragua, aventurë",
  "Title For": "Titull për",
  "Title Style": "Stili i titullit",
  "Number of Titles": "Numri i titujve",
  "Book": "Libër",
  "Short Story": "Tregim i shkurtër",
  "Novel": "Roman",
  "Chapter": "Kapitull",
  "Series": "Seri",
  "Simple": "I thjeshtë",
  "Mysterious": "Misterioz",
  "Dramatic": "Dramatik",
  "Catchy": "Tërheqës",
  "Poetic": "Poetik",
  "Kids": "Fëmijë",
  "SEO Article": "Artikull SEO",
  "How-To Guide": "Udhëzues",
  "Listicle": "Artikull listë",
  "Product Review": "Rishikim produkti",
  "Opinion Piece": "Shkrim mendimi",
  "News Article": "Artikull lajmesh",
  "Professional": "Profesional",
  "Casual": "Joformal",
  "Informative": "Informues",
  "Persuasive": "Bindës",
  "Friendly": "Miqësor",
  "Authoritative": "Autoritar",
  "Short (500-800)": "I shkurtër (500-800)",
  "Medium (800-1500)": "Mesatar (800-1500)",
  "Long (1500-2500)": "I gjatë (1500-2500)",
  "Detailed (2500+)": "I detajuar (2500+)",
  "Storytime": "Koha e historive",
  "Documentary": "Dokumentar",
  "Short Reel": "Reel i shkurtër",
  "Educational": "Edukativ",
  "Review": "Rishikim",
  "Tutorial": "Tutorial",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Tërheqës",
  "Energetic": "Energjik",
  "Calm": "I qetë",
  "Funny": "Qesharak",
  "Next": "Tjetër",
  "Get Started": "Fillo",
  "Your tool for quick, high-quality essay writing":
      "Mjeti juaj për shkrim të shpejtë dhe me cilësi të lartë",
};
