import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sr = {
  AppKeys.lblChooseLanguage: "Изаберите језик",
  "All": "Све",
  "AI Story Generator": "AI генератор прича",
  "Story Generator": "Генератор прича",
  "Essay Writer": "Писац есеја",
  "Essay length": "Дужина есеја",
  "Script Generator": "Генератор сценарија",
  "Create original stories in seconds":
      "Креирајте оригиналне приче за неколико секунди",
  "Academic writing made simple": "Академско писање поједностављено",
  "Generate powerful scripts for any medium":
      "Генеришите моћне сценарије за било који медиј",
  "Start Writing": "Почните да пишете",
  "Create Now": "Креирајте сада",
  "Start Generating": "Почните генерисање",
  "Your Stories": "Ваше приче",
  "No stories yet": "Још нема прича",
  "Start creating your first story!": "Почните да креирате своју прву причу!",
  "Your Story Space Awaits": "Ваш простор за приче чека",
  "Start your first story and see it appear here":
      "Започните своју прву причу и видите је овде",
  "Language": "Језик",
  "Rate us": "Оцените нас",
  "Share us": "Поделите нас",
  "Privacy Policy": "Политика приватности",
  "Settings": "Подешавања",
  "Select Language": "Изаберите језик",
  "Dashboard": "Контролна табла",
  "BENEFITS": "ПРЕДНОСТИ",
  "Subscribe": "Претплатите се",
  "Weekly": "Недељно",
  "Monthly": "Месечно",
  "Yearly": "Годишње",
  "week": "недеља",
  "months": "месеци",
  "year": "година",
  "Terms & Condition": "Услови и правила",
  "No Commitment. Cancel anytime": "Без обавеза. Откажите било када",
  "No Payment Now": "Без плаћања сада",
  "3 days free": "3 дана бесплатно",
  "Start your free trial": "Започните бесплатни пробни период",
  "More detailed answers": "Детаљнији одговори",
  "Instant responds": "Тренутни одговори",
  "Text recognition": "Препознавање текста",
  "Powered by AI": "Покреће AI",
  "Storytelleing": "Причање",
  ' Power': "Снага",
  "Unlock your \nFill ": "Откључајте своје \nпопуњавање",
  "Your History": "Ваша историја",
  "Terms and Conditions": "Услови и правила",
  "Short": "Кратко",
  "Medium": "Средње",
  "Long": "Дуго",
  "Length": "Дужина",
  "Describe your topic...": "Опишите своју тему...",
  "Set Creativity": "Подесите креативност",
  "Standard": "Стандардно",
  "Creative": "Креативно",
  "Complex": "Сложено",
  "Select Genre": "Изаберите жанр",
  "Fantasy": "Фантазија",
  "Mystery": "Мистерија",
  "Thriller": "Трилер",
  "Script Tone": "Тон сценарија",
  "Script Type": "Тип сценарија",
  "Comedy": "Комедија",
  "Drama": "Драма",
  "Horror": "Хорор",
  "Action": "Акција",
  "Romance": "Романтика",
  "Go Premium": "Пређите на Premium",
  "Unlock Everything": "Откључајте све",
  "Unlimited Story Generation": "Неограничено генерисање прича",
  "Write Longer & Detailed Essays": "Пишите дуже и детаљније есеје",
  "Advanced Script Writer": "Напредни писац сценарија",
  "Unlock All Styles & Tones": "Откључајте све стилове и тонове",
  "No Word/Length Limit": "Без ограничења речи/дужине",
  "Remove All Ads": "Уклоните све огласе",
  "Restore": "Обновите",
  "YouTube Video": "YouTube видео",
  "Podcast": "Подкаст",
  "Reel": "Рил",
  "Motivational": "Мотивациони",
  "Advertisement": "Оглас",
  "Fairy Tale": "Бајка",
  "Sci-Fi": "Научна фантастика",
  "Select Style": "Изаберите стил",
  "Imaginative": "Имагинативан",
  "Innovative": "Иновативан",
  "AI Story Writer": "AI писац прича",
  "Generate": "Генеришите",
  "Please wait...": "Молимо сачекајте...",
  "Result": "Резултат",
  "Regenerate": "Регенеришите",
  "Download": "Преузмите",
  "Text copied to clipboard!": "Текст копиран у клипборд!",
  "Please enter a topic": "Молимо унесите тему",
  "Story Magic": "Магија прича",
  "Let AI bring your thoughts to a full story":
      "Пустите AI да претвори ваше мисли у целу причу",
  "Smart Scripts": "Паметни сценарији",
  "From concept to script—fast, easy, and creative":
      "Од концепта до сценарија—брзо, лако и креативно",
  "Perfect Essays": "Савршени есеји",
  "You have reached your free limit": "Достигли сте бесплатни лимит",
  "Donwload": "Преузмите",
  "Press again to exit app": "Притисните поново да изађете из апликације",
  "Saved to files": "TXT датотека успешно сачувана!",
  "Error: Please try again": "Грешка: Покушајте поново",
  "Subscription expired": "Претплата истекла",
  "Purchase cancelled": "Куповина отказана",
  "Purchase failed": "Куповина неуспешна",
  "Restore failed": "Обнављање неуспешно",
  "Purchase Successful!": "Куповина успешна!",
  "Short (200-500 words)": "Кратко (200-500 речи)",
  "Medium (500-1000 words)": "Средње (500-1000 речи)",
  "Large (1000+ words)": "Дуго (1000+ речи)",
  "Academic Level": "Академски ниво",
  "Type of Paper": "Тип рада",
  "High School": "Средња школа",
  "College": "Факултет",
  "Short Film": "Кратки филм",
  "University": "Универзитет",
  "Masters": "Мастер",
  "Custom": "Прилагођено",
  "Tiktok Video": "Tiktok видео",
  "Movie": "Филм",
  "Expository": "Експозиторни",
  "Argumentative": "Аргументативни",
  "Narrative": "Наративни",
  "Descriptive": "Дескриптивни",
  "We're sorry to hear that 😔": "Жао нам је што то чујемо 😔",
  "We'll try to improve 🙁": "Покушаћемо да се побољшамо 🙁",
  "Thanks for your feedback 🙂": "Хвала на повратним информацијама 🙂",
  "Great! We're glad you like it 😊":
      "Одлично! Драго нам је да вам се свиђа 😊",
  "Awesome! Thank you so much! 🎉": "Невероватно! Хвала вам пуно! 🎉",
  "Maybe Later": "Можда касније",
  "Tap a star to rate your experience": "Додирните звезду да оцените искуство",
  "Enjoying AI Math Solver?": "Уживате у AI Math Solver?",
  "Thank you for rating us": "Хвала што сте нас оценили",
  "Submit Rating": "Пошаљите оцену",
  "Hindi": "Хинди",
  "Enjoying AI Story Generator?": "Уживате у AI Story Generator?",
  "Adventure": "Авантура",
  "Inspired": "Инспирисан",
  "Film Script": "Филмски сценарио",
  "Stage Play": "Позоришна представа",
  "Scene Breakdown": "Анализа сцене",
  "Dialogue Only": "Само дијалог",
  "Ad loading please wait..": "Оглас се учитава, сачекајте...",
  "Words:": "Речи:",
  "Reading:": "Читање:",

  AppKeys.arabic: "Арапски",
  AppKeys.chinese: "Кинески",
  AppKeys.english: "Енглески",
  AppKeys.french: "Француски",
  AppKeys.german: "Немачки",
  AppKeys.hindi: "Хинди",
  AppKeys.indonesian: "Индонежански",
  AppKeys.japanese: "Јапански",
  AppKeys.korean: "Корејски",
  AppKeys.portuguese: "Португалски",
  AppKeys.russian: "Руски",
  AppKeys.spanish: "Шпански",
  AppKeys.turkish: "Турски",

  'Download As': 'Преузмите као',
  'Choose format to download': 'Изаберите формат за преузимање',
  'Text File': 'Текстуална датотека',
  'PDF File': 'PDF датотека',
  'Copy': 'Копирајте',
  'Share': 'Поделите',
  'Text copied!': 'Текст копиран!',
  'Copied to clipboard': 'Копирано у клипборд',
  'File saved successfully': 'Датотека успешно сачувана',
  'Error saving file': 'Грешка при чувању датотеке',
  'Share Story': 'Поделите причу',
  'Export': 'Извезите',
  "Character Story": "Прича лика",
  "Create detailed character backstories":
      "Направите детаљне позадинске приче ликова",
  "Create Character": "Направи лик",
  "Rewrite Story": "Препиши причу",
  "Paste Your Story": "Налепи своју причу",
  "Paste your story here to rewrite...":
      "Налепите своју причу овде за препис...",
  "Transform and improve your existing stories":
      "Трансформишите и побољшајте постојеће приче",
  "Title Generator": "Генератор наслова",
  "Generate catchy titles for your stories":
      "Генеришите привлачне наслове за своје приче",
  "Generate Titles": "Генериши наслове",
  "Blog Writer": "Писац блога",
  "Blog Topic": "Тема блога",
  "Target Keywords": "Циљне кључне речи",
  "Target Audience (Optional)": "Циљна публика (Опционо)",
  "Enter your blog topic or title...": "Унесите тему или наслов свог блога...",
  "e.g., AI writing, content marketing, SEO tips":
      "нпр. писање са АИ, маркетинг садржаја, савети за SEO",
  "e.g., small business owners, bloggers":
      "нпр. власници малих предузећа, блогери",
  "Article Type": "Врста чланка",
  "Writing Tone": "Тон писања",
  "Article Length": "Дужина чланка",
  "SEO Options": "SEO опције",
  "Include Meta Description": "Укључи мета опис",
  "Include Keyword Suggestions": "Укључи предлоге кључних речи",
  "Include FAQs Section": "Укључи ЧПП одељак",
  "Please enter a blog topic": "Унесите тему блога",
  "Generate Blog": "Генериши блог",
  "SEO optimized articles with keywords":
      "SEO оптимизовани чланци са кључним речима",
  "Write Blog": "Напиши блог",
  "YouTube Script": "YouTube сценарио",
  "Video Topic": "Тема видеа",
  "Key Points (Optional)": "Кључне тачке (Опционо)",
  "What is your video about?": "О чему је ваш видео?",
  "List key points to cover (optional)...":
      "Наведите кључне тачке (опционо)...",
  "Video Duration": "Трајање видеа",
  "Script Options": "Опције сценарија",
  "Include Hook/Intro": "Укључи увод/хук",
  "Include Call-to-Action": "Укључи позив на акцију",
  "Include Timestamps": "Укључи временске ознаке",
  "Please enter a video topic": "Унесите тему видеа",
  "Generate Script": "Генериши сценарио",
  "Create scripts for videos & reels": "Направите сценарије за видеа и рилове",
  "Create Script": "Направи сценарио",
  "Character Details": "Детаљи лика",
  "Character Name": "Ime лика",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Старост (нпр. 25, Млади одрасли, Антички)",
  "Personality (e.g., brave, shy, cunning)":
      "Личност (нпр. храбар, стидљив, лукав)",
  "Role (e.g., Hero, Villain, Mentor)": "Улога (нпр. Јунак, Негативац, Ментор)",
  "Additional Details (optional)": "Додатне детаљи (опционо)",
  "Output Style": "Стил излаза",
  "Generate Character": "Генериши лик",
  "Please enter character name": "Унесите ime лика",
  "Please enter character role": "Унесите улогу лика",
  "Detailed": "Детаљан",
  "Brief": "Кратак",
  "Elaborate": "Разрађен",
  "Select Tone": "Изабери тон",
  "Rewrite Style": "Стил преписа",
  "Output Length": "Дужина излаза",
  "Please paste your story": "Налепите своју причу",
  "Story is too short. Please provide more content.":
      "Прича је прекратка. Молимо унесите више садржаја.",
  "Same": "Исто",
  "More Dramatic": "Драматичније",
  "More Humorous": "Хумористичније",
  "More Emotional": "Емоционалније",
  "More Suspenseful": "Напетије",
  "Lighter": "Лакше",
  "Improved": "Побољшано",
  "Simplified": "Поједностављено",
  "More Descriptive": "Описније",
  "More Dialogue": "Више дијалога",
  "More Action": "Више акције",
  "Literary": "Књижевно",
  "Shorter": "Краће",
  "Longer": "Дуже",
  "Much Longer": "Много дуже",
  "Rewrite Now": "Препиши сада",
  "Story/Book Topic": "Тема приче/књиге",
  "Keywords (Optional)": "Кључне речи (Опционо)",
  "Describe your story topic or theme...":
      "Опишите тему или мотив своје приче...",
  "e.g., magic, dragon, adventure": "нпр. магија, змај, авантура",
  "Title For": "Наслов за",
  "Title Style": "Стил наслова",
  "Number of Titles": "Број наслова",
  "Book": "Књига",
  "Short Story": "Кратка прича",
  "Novel": "Роман",
  "Chapter": "Поглавље",
  "Series": "Серија",
  "Simple": "Jedноставан",
  "Mysterious": "Мистериозан",
  "Dramatic": "Драматичан",
  "Catchy": "Привлачан",
  "Poetic": "Поетски",
  "Kids": "За децу",
  "SEO Article": "SEO чланак",
  "How-To Guide": "Водич",
  "Listicle": "Листа чланак",
  "Product Review": "Рецензија производа",
  "Opinion Piece": "Мишљење",
  "News Article": "Новински чланак",
  "Professional": "Професионалан",
  "Casual": "Неформалан",
  "Informative": "Информативан",
  "Persuasive": "Убедљив",
  "Friendly": "Пријатељски",
  "Authoritative": "Ауторитативан",
  "Short (500-800)": "Кратак (500-800)",
  "Medium (800-1500)": "Средњи (800-1500)",
  "Long (1500-2500)": "Дугачак (1500-2500)",
  "Detailed (2500+)": "Детаљан (2500+)",
  "Storytime": "Причање прича",
  "Documentary": "Документарац",
  "Short Reel": "Кратак рил",
  "Educational": "Образовни",
  "Review": "Рецензија",
  "Tutorial": "Упутство",
  "< 1 min (Shorts)": "< 1 мин (Кратки)",
  "1-3 min": "1-3 мин",
  "5-10 min": "5-10 мин",
  "10-20 min": "10-20 мин",
  "20+ min": "20+ мин",
  "Engaging": "Занимљиво",
  "Energetic": "Енергично",
  "Calm": "Смирено",
  "Funny": "Смешно",
  "Next": "Следеће",
  "Get Started": "Почни",
  "Your tool for quick, high-quality essay writing":
      "Ваш алат за брзо и квалитетно писање есеја",
};
