import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sv = {
  AppKeys.lblChooseLanguage: "Välj språk",
  "All": "Alla",
  "AI Story Generator": "AI-berättelsegenerator",
  "Story Generator": "Berättelsegenerator",
  "Essay Writer": "Uppsatsförfattare",
  "Essay length": "Uppsatslängd",
  "Script Generator": "Manusgenerator",
  "Create original stories in seconds":
      "Skapa originella berättelser på några sekunder",
  "Academic writing made simple": "Akademiskt skrivande förenklat",
  "Generate powerful scripts for any medium":
      "Generera kraftfulla manus för alla medier",
  "Start Writing": "Börja skriva",
  "Create Now": "Skapa nu",
  "Start Generating": "Börja generera",
  "Your Stories": "Dina berättelser",
  "No stories yet": "Inga berättelser ännu",
  "Start creating your first story!": "Börja skapa din första berättelse!",
  "Your Story Space Awaits": "Ditt berättelseutrymme väntar",
  "Start your first story and see it appear here":
      "Börja din första berättelse och se den visas här",
  "Language": "Språk",
  "Rate us": "Betygsätt oss",
  "Share us": "Dela oss",
  "Privacy Policy": "Integritetspolicy",
  "Settings": "Inställningar",
  "Select Language": "Välj språk",
  "Dashboard": "Instrumentpanel",
  "BENEFITS": "FÖRDELAR",
  "Subscribe": "Prenumerera",
  "Weekly": "Veckovis",
  "Monthly": "Månadsvis",
  "Yearly": "Årligen",
  "week": "vecka",
  "months": "månader",
  "year": "år",
  "Terms & Condition": "Villkor och regler",
  "No Commitment. Cancel anytime": "Ingen bindningstid. Avbryt när som helst",
  "No Payment Now": "Ingen betalning nu",
  "3 days free": "3 dagar gratis",
  "Start your free trial": "Starta din kostnadsfria provperiod",
  "More detailed answers": "Mer detaljerade svar",
  "Instant responds": "Omedelbara svar",
  "Text recognition": "Textigenkänning",
  "Powered by AI": "Drivs av AI",
  "Storytelleing": "Berättande",
  ' Power': "Kraft",
  "Unlock your \nFill ": "Lås upp din \nFyll i",
  "Your History": "Din historik",
  "Terms and Conditions": "Villkor och regler",
  "Short": "Kort",
  "Medium": "Mellan",
  "Long": "Lång",
  "Length": "Längd",
  "Describe your topic...": "Beskriv ditt ämne...",
  "Set Creativity": "Ställ in kreativitet",
  "Standard": "Standard",
  "Creative": "Kreativ",
  "Complex": "Komplex",
  "Select Genre": "Välj genre",
  "Fantasy": "Fantasy",
  "Mystery": "Mysterium",
  "Thriller": "Thriller",
  "Script Tone": "Manustonalitet",
  "Script Type": "Manustyp",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Skräck",
  "Action": "Action",
  "Romance": "Romantik",
  "Go Premium": "Bli Premium",
  "Unlock Everything": "Lås upp allt",
  "Unlimited Story Generation": "Obegränsad berättelsegenerering",
  "Write Longer & Detailed Essays":
      "Skriv längre och mer detaljerade uppsatser",
  "Advanced Script Writer": "Avancerad manusförfattare",
  "Unlock All Styles & Tones": "Lås upp alla stilar och toner",
  "No Word/Length Limit": "Ingen ord-/längdbegränsning",
  "Remove All Ads": "Ta bort alla annonser",
  "Restore": "Återställ",
  "YouTube Video": "YouTube-video",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motiverande",
  "Advertisement": "Annons",
  "Fairy Tale": "Saga",
  "Sci-Fi": "Sci-Fi",
  "Select Style": "Välj stil",
  "Imaginative": "Fantasifull",
  "Innovative": "Innovativ",
  "AI Story Writer": "AI-berättelseförfattare",
  "Generate": "Generera",
  "Please wait...": "Vänligen vänta...",
  "Result": "Resultat",
  "Regenerate": "Regenerera",
  "Download": "Ladda ner",
  "Text copied to clipboard!": "Text kopierad till urklipp!",
  "Please enter a topic": "Vänligen ange ett ämne",
  "Story Magic": "Berättelsemagi",
  "Let AI bring your thoughts to a full story":
      "Låt AI förvandla dina tankar till en fullständig berättelse",
  "Smart Scripts": "Smarta manus",
  "From concept to script—fast, easy, and creative":
      "Från koncept till manus—snabbt, enkelt och kreativt",
  "Perfect Essays": "Perfekta uppsatser",
  "You have reached your free limit": "Du har nått din gratisgrens",
  "Donwload": "Ladda ner",
  "Press again to exit app": "Tryck igen för att avsluta appen",
  "Saved to files": "TXT-fil sparad!",
  "Error: Please try again": "Fel: Försök igen",
  "Subscription expired": "Prenumeration utgången",
  "Purchase cancelled": "Köp avbrutet",
  "Purchase failed": "Köp misslyckades",
  "Restore failed": "Återställning misslyckades",
  "Purchase Successful!": "Köp lyckat!",
  "Short (200-500 words)": "Kort (200-500 ord)",
  "Medium (500-1000 words)": "Mellan (500-1000 ord)",
  "Large (1000+ words)": "Lång (1000+ ord)",
  "Academic Level": "Akademisk nivå",
  "Type of Paper": "Typ av arbete",
  "High School": "Gymnasium",
  "College": "Högskola",
  "Short Film": "Kortfilm",
  "University": "Universitet",
  "Masters": "Master",
  "Custom": "Anpassad",
  "Tiktok Video": "Tiktok-video",
  "Movie": "Film",
  "Expository": "Förklarande",
  "Argumentative": "Argumenterande",
  "Narrative": "Berättande",
  "Descriptive": "Beskrivande",
  "We're sorry to hear that 😔": "Vi beklagar att höra det 😔",
  "We'll try to improve 🙁": "Vi ska försöka förbättra oss 🙁",
  "Thanks for your feedback 🙂": "Tack för din feedback 🙂",
  "Great! We're glad you like it 😊": "Bra! Vi är glada att du gillar det 😊",
  "Awesome! Thank you so much! 🎉": "Fantastiskt! Tack så mycket! 🎉",
  "Maybe Later": "Kanske senare",
  "Tap a star to rate your experience":
      "Tryck på en stjärna för att betygsätta din upplevelse",
  "Enjoying AI Math Solver?": "Gillar du AI Math Solver?",
  "Thank you for rating us": "Tack för ditt betyg",
  "Submit Rating": "Skicka betyg",
  "Hindi": "Hindi",
  "Enjoying AI Story Generator?": "Gillar du AI Story Generator?",
  "Adventure": "Äventyr",
  "Inspired": "Inspirerad",
  "Film Script": "Filmmanus",
  "Stage Play": "Scenspel",
  "Scene Breakdown": "Scenanalys",
  "Dialogue Only": "Endast dialog",
  "Ad loading please wait..": "Annons laddas, vänligen vänta...",
  "Words:": "Ord:",
  "Reading:": "Läsning:",

  AppKeys.arabic: "Arabiska",
  AppKeys.chinese: "Kinesiska",
  AppKeys.english: "Engelska",
  AppKeys.french: "Franska",
  AppKeys.german: "Tyska",
  AppKeys.hindi: "Hindi",
  AppKeys.indonesian: "Indonesiska",
  AppKeys.japanese: "Japanska",
  AppKeys.korean: "Koreanska",
  AppKeys.portuguese: "Portugisiska",
  AppKeys.russian: "Ryska",
  AppKeys.spanish: "Spanska",
  AppKeys.turkish: "Turkiska",

  'Download As': 'Ladda ner som',
  'Choose format to download': 'Välj format att ladda ner',
  'Text File': 'Textfil',
  'PDF File': 'PDF-fil',
  'Copy': 'Kopiera',
  'Share': 'Dela',
  'Text copied!': 'Text kopierad!',
  'Copied to clipboard': 'Kopierad till urklipp',
  'File saved successfully': 'Fil sparad',
  'Error saving file': 'Fel vid sparande av fil',
  'Share Story': 'Dela berättelse',
  'Export': 'Exportera',

  "Character Story": "Karaktärsberättelse",
  "Create detailed character backstories":
      "Skapa detaljerade bakgrundsberättelser för karaktärerna",
  "Create Character": "Skapa karaktär",
  "Rewrite Story": "Skriv om berättelsen",
  "Paste Your Story": "Klistra in din berättelse",
  "Paste your story here to rewrite...":
      "Klistra in din berättelse här för att skriva om den...",
  "Transform and improve your existing stories":
      "Transformera och förbättra dina befintliga berättelser",
  "Title Generator": "Titelgenerator",
  "Generate catchy titles for your stories":
      "Generera fängslande titlar till dina berättelser",
  "Generate Titles": "Generera titlar",
  "Blog Writer": "Bloggskribent",
  "Blog Topic": "Bloggtema",
  "Target Keywords": "Målsökord",
  "Target Audience (Optional)": "Målgrupp (Valfritt)",
  "Enter your blog topic or title...": "Ange ditt bloggtema eller titel...",
  "e.g., AI writing, content marketing, SEO tips":
      "t.ex. AI-skrivande, innehållsmarknadsföring, SEO-tips",
  "e.g., small business owners, bloggers": "t.ex. småföretagare, bloggare",
  "Article Type": "Artikeltyp",
  "Writing Tone": "Skrivton",
  "Article Length": "Artikellängd",
  "SEO Options": "SEO-alternativ",
  "Include Meta Description": "Inkludera metabeskrivning",
  "Include Keyword Suggestions": "Inkludera sökordförslag",
  "Include FAQs Section": "Inkludera FAQ-avsnitt",
  "Please enter a blog topic": "Ange ett bloggtema",
  "Generate Blog": "Generera blogg",
  "SEO optimized articles with keywords": "SEO-optimerade artiklar med sökord",
  "Write Blog": "Skriv blogg",
  "YouTube Script": "YouTube-manus",
  "Video Topic": "Videotema",
  "Key Points (Optional)": "Nyckelpunkter (Valfritt)",
  "What is your video about?": "Vad handlar din video om?",
  "List key points to cover (optional)...":
      "Lista nyckelpunkter att täcka (valfritt)...",
  "Video Duration": "Videolängd",
  "Script Options": "Manusalternativ",
  "Include Hook/Intro": "Inkludera krok/intro",
  "Include Call-to-Action": "Inkludera uppmaning till handling",
  "Include Timestamps": "Inkludera tidsstämplar",
  "Please enter a video topic": "Ange ett videotema",
  "Generate Script": "Generera manus",
  "Create scripts for videos & reels": "Skapa manus för videor och reels",
  "Create Script": "Skapa manus",
  "Character Details": "Karaktärsdetaljer",
  "Character Name": "Karaktärsnamn",
  "Age (e.g., 25, Young Adult, Ancient)": "Ålder (t.ex. 25, Ung vuxen, Antik)",
  "Personality (e.g., brave, shy, cunning)":
      "Personlighet (t.ex. modig, blyg, listig)",
  "Role (e.g., Hero, Villain, Mentor)": "Roll (t.ex. Hjälte, Skurk, Mentor)",
  "Additional Details (optional)": "Ytterligare detaljer (valfritt)",
  "Output Style": "Utdatastil",
  "Generate Character": "Generera karaktär",
  "Please enter character name": "Ange karaktärens namn",
  "Please enter character role": "Ange karaktärens roll",
  "Detailed": "Detaljerad",
  "Brief": "Kortfattad",
  "Elaborate": "Utarbetad",
  "Select Tone": "Välj ton",
  "Rewrite Style": "Omskrivningsstil",
  "Output Length": "Utdatalängd",
  "Please paste your story": "Klistra in din berättelse",
  "Story is too short. Please provide more content.":
      "Berättelsen är för kort. Ange mer innehåll.",
  "Same": "Samma",
  "More Dramatic": "Mer dramatisk",
  "More Humorous": "Mer humoristisk",
  "More Emotional": "Mer emotionell",
  "More Suspenseful": "Mer spännande",
  "Lighter": "Lättare",
  "Improved": "Förbättrad",
  "Simplified": "Förenklad",
  "More Descriptive": "Mer beskrivande",
  "More Dialogue": "Mer dialog",
  "More Action": "Mer handling",
  "Literary": "Litterär",
  "Shorter": "Kortare",
  "Longer": "Längre",
  "Much Longer": "Mycket längre",
  "Rewrite Now": "Skriv om nu",
  "Story/Book Topic": "Berättelse-/boktema",
  "Keywords (Optional)": "Sökord (Valfritt)",
  "Describe your story topic or theme...":
      "Beskriv berättelsens tema eller motiv...",
  "e.g., magic, dragon, adventure": "t.ex. magi, drake, äventyr",
  "Title For": "Titel för",
  "Title Style": "Titelstil",
  "Number of Titles": "Antal titlar",
  "Book": "Bok",
  "Short Story": "Novell",
  "Novel": "Roman",
  "Chapter": "Kapitel",
  "Series": "Serie",
  "Simple": "Enkel",
  "Mysterious": "Mystisk",
  "Dramatic": "Dramatisk",
  "Catchy": "Catchy",
  "Poetic": "Poetisk",
  "Kids": "Barn",
  "SEO Article": "SEO-artikel",
  "How-To Guide": "Handledning",
  "Listicle": "Listartikel",
  "Product Review": "Produktrecension",
  "Opinion Piece": "Debattartikel",
  "News Article": "Nyhetsartikel",
  "Professional": "Professionell",
  "Casual": "Informell",
  "Informative": "Informativ",
  "Persuasive": "Övertygande",
  "Friendly": "Vänlig",
  "Authoritative": "Auktoritativ",
  "Short (500-800)": "Kort (500-800)",
  "Medium (800-1500)": "Medel (800-1500)",
  "Long (1500-2500)": "Lång (1500-2500)",
  "Detailed (2500+)": "Detaljerad (2500+)",
  "Storytime": "Berättarstund",
  "Documentary": "Dokumentär",
  "Short Reel": "Kort reel",
  "Educational": "Utbildande",
  "Review": "Recension",
  "Tutorial": "Handledning",
  "< 1 min (Shorts)": "< 1 min (Shorts)",
  "1-3 min": "1-3 min",
  "5-10 min": "5-10 min",
  "10-20 min": "10-20 min",
  "20+ min": "20+ min",
  "Engaging": "Engagerande",
  "Energetic": "Energisk",
  "Calm": "Lugn",
  "Funny": "Rolig",
  "Next": "Nästa",
  "Get Started": "Kom igång",
  "Your tool for quick, high-quality essay writing":
      "Ditt verktyg för snabbt och högkvalitativt essäskrivande",
};
