import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> sw = {
  AppKeys.lblChooseLanguage: "Chagua Lugha",
  "All": "Zote",
  "AI Story Generator": "Kizazi cha Hadithi cha AI",
  "Story Generator": "Kizazi cha Hadithi",
  "Essay Writer": "Mwandishi wa Insha",
  "Essay length": "Urefu wa insha",
  "Script Generator": "Kizazi cha Skripti",
  "Create original stories in seconds": "Unda hadithi za asili kwa sekunde",
  "Academic writing made simple": "Uandishi wa kitaaluma umefanywa rahisi",
  "Generate powerful scripts for any medium":
      "Zalisha skripti zenye nguvu kwa chombo chochote",
  "Start Writing": "Anza Kuandika",
  "Create Now": "Unda Sasa",
  "Start Generating": "Anza Kuzalisha",
  "Your Stories": "Hadithi Zako",
  "No stories yet": "Hakuna hadithi bado",
  "Start creating your first story!": "Anza kuunda hadithi yako ya kwanza!",
  "Your Story Space Awaits": "Nafasi Yako ya Hadithi Inakungoja",
  "Start your first story and see it appear here":
      "Anza hadithi yako ya kwanza na uione hapa",
  "Language": "Lugha",
  "Rate us": "Tupeni alama",
  "Share us": "Tushiriki",
  "Privacy Policy": "Sera ya Faragha",
  "Settings": "Mipangilio",
  "Select Language": "Chagua Lugha",
  "Dashboard": "Dashibodi",
  "BENEFITS": "FAIDA",
  "Subscribe": "Jisajili",
  "Weekly": "Kila Wiki",
  "Monthly": "Kila Mwezi",
  "Yearly": "Kila Mwaka",
  "week": "wiki",
  "months": "miezi",
  "year": "mwaka",
  "Terms & Condition": "Masharti na Vigezo",
  "No Commitment. Cancel anytime": "Hakuna Ahadi. Ghairi wakati wowote",
  "No Payment Now": "Hakuna Malipo Sasa",
  "3 days free": "Siku 3 bure",
  "Start your free trial": "Anza jaribio lako la bure",
  "More detailed answers": "Majibu ya kina zaidi",
  "Instant responds": "Majibu ya papo hapo",
  "Text recognition": "Utambuzi wa maandishi",
  "Powered by AI": "Inayoendeshwa na AI",
  "Storytelleing": "Kusimulia Hadithi",
  ' Power': "Nguvu",
  "Unlock your \nFill ": "Fungua yako \nJaza",
  "Your History": "Historia Yako",
  "Terms and Conditions": "Masharti na Vigezo",
  "Short": "Fupi",
  "Medium": "Wastani",
  "Long": "Ndefu",
  "Length": "Urefu",
  "Describe your topic...": "Eleza mada yako...",
  "Set Creativity": "Weka Ubunifu",
  "Standard": "Kawaida",
  "Creative": "Mbunifu",
  "Complex": "Ngumu",
  "Select Genre": "Chagua Aina",
  "Fantasy": "Ndoto",
  "Mystery": "Siri",
  "Thriller": "Thriller",
  "Script Tone": "Toni ya Skripti",
  "Script Type": "Aina ya Skripti",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Hofu",
  "Action": "Hatua",
  "Romance": "Mapenzi",
  "Go Premium": "Pata Premium",
  "Unlock Everything": "Fungua Kila Kitu",
  "Unlimited Story Generation": "Uzalishaji wa Hadithi Usio na Kikomo",
  "Write Longer & Detailed Essays": "Andika Insha Ndefu na za Kina",
  "Advanced Script Writer": "Mwandishi wa Skripti wa Juu",
  "Unlock All Styles & Tones": "Fungua Mitindo na Toni Zote",
  "No Word/Length Limit": "Hakuna Kikomo cha Maneno/Urefu",
  "Remove All Ads": "Ondoa Matangazo Yote",
  "Restore": "Rejesha",
  "YouTube Video": "Video ya YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Ya Motisha",
  "Advertisement": "Tangazo",
  "Fairy Tale": "Hadithi ya Kichawi",
  "Sci-Fi": "Sayansi ya Kubuni",
  "Select Style": "Chagua Mtindo",
  "Imaginative": "Ya Kubuni",
  "Innovative": "Ya Ubunifu",
  "AI Story Writer": "Mwandishi wa Hadithi wa AI",
  "Generate": "Zalisha",
  "Please wait...": "Tafadhali subiri...",
  "Result": "Matokeo",
  "Regenerate": "Zalisha tena",
  "Download": "Pakua",
  "Text copied to clipboard!": "Maandishi yamenakiliwa kwenye clipboard!",
  "Please enter a topic": "Tafadhali weka mada",
  "Story Magic": "Uchawi wa Hadithi",
  "Let AI bring your thoughts to a full story":
      "Wacha AI igeuze mawazo yako kuwa hadithi kamili",
  "Smart Scripts": "Skripti za Busara",
  "From concept to script—fast, easy, and creative":
      "Kutoka wazo hadi skripti—haraka, rahisi, na mbunifu",
  "Perfect Essays": "Insha Kamili",
  "You have reached your free limit": "Umefika kikomo chako cha bure",
  "Donwload": "Pakua",
  "Press again to exit app": "Bonyeza tena kutoka kwenye programu",
  "Saved to files": "Faili ya TXT imehifadhiwa!",
  "Error: Please try again": "Hitilafu: Tafadhali jaribu tena",
  "Subscription expired": "Usajili umeisha",
  "Purchase cancelled": "Ununuzi umeghairiwa",
  "Purchase failed": "Ununuzi umeshindwa",
  "Restore failed": "Urejeshaji umeshindwa",
  "Purchase Successful!": "Ununuzi Umefanikiwa!",
  "Short (200-500 words)": "Fupi (maneno 200-500)",
  "Medium (500-1000 words)": "Wastani (maneno 500-1000)",
  "Large (1000+ words)": "Ndefu (maneno 1000+)",
  "Academic Level": "Kiwango cha Kitaaluma",
  "Type of Paper": "Aina ya Karatasi",
  "High School": "Shule ya Upili",
  "College": "Chuo",
  "Short Film": "Filamu Fupi",
  "University": "Chuo Kikuu",
  "Masters": "Shahada ya Uzamili",
  "Custom": "Maalum",
  "Tiktok Video": "Video ya Tiktok",
  "Movie": "Filamu",
  "Expository": "Ya Maelezo",
  "Argumentative": "Ya Hoja",
  "Narrative": "Ya Hadithi",
  "Descriptive": "Ya Maelezo",
  "We're sorry to hear that 😔": "Tunasikitika kusikia hivyo 😔",
  "We'll try to improve 🙁": "Tutajaribu kuboresha 🙁",
  "Thanks for your feedback 🙂": "Asante kwa maoni yako 🙂",
  "Great! We're glad you like it 😊": "Nzuri! Tunafurahi unakipenda 😊",
  "Awesome! Thank you so much! 🎉": "Bora! Asante sana! 🎉",
  "Maybe Later": "Labda Baadaye",
  "Tap a star to rate your experience": "Gusa nyota ili kukadiria uzoefu wako",
  "Enjoying AI Math Solver?": "Unafurahia AI Math Solver?",
  "Thank you for rating us": "Asante kwa kutukadiria",
  "Submit Rating": "Tuma Kadirio",
  "Hindi": "Kihindi",
  "Enjoying AI Story Generator?": "Unafurahia AI Story Generator?",
  "Adventure": "Matukio ya Kusisimua",
  "Inspired": "Iliyochochewa",
  "Film Script": "Skripti ya Filamu",
  "Stage Play": "Mchezo wa Jukwaani",
  "Scene Breakdown": "Uchambuzi wa Eneo",
  "Dialogue Only": "Mazungumzo tu",
  "Ad loading please wait..": "Tangazo linabeba, tafadhali subiri...",
  "Words:": "Maneno:",
  "Reading:": "Kusoma:",

  AppKeys.arabic: "Kiarabu",
  AppKeys.chinese: "Kichina",
  AppKeys.english: "Kiingereza",
  AppKeys.french: "Kifaransa",
  AppKeys.german: "Kijerumani",
  AppKeys.hindi: "Kihindi",
  AppKeys.indonesian: "Kiindonesia",
  AppKeys.japanese: "Kijapani",
  AppKeys.korean: "Kikorea",
  AppKeys.portuguese: "Kireno",
  AppKeys.russian: "Kirusi",
  AppKeys.spanish: "Kihispania",
  AppKeys.turkish: "Kituruki",

  'Download As': 'Pakua Kama',
  'Choose format to download': 'Chagua umbizo la kupakua',
  'Text File': 'Faili ya Maandishi',
  'PDF File': 'Faili ya PDF',
  'Copy': 'Nakili',
  'Share': 'Shiriki',
  'Text copied!': 'Maandishi yamenakiliwa!',
  'Copied to clipboard': 'Imenakiliwa kwenye clipboard',
  'File saved successfully': 'Faili imehifadhiwa',
  'Error saving file': 'Hitilafu ya kuhifadhi faili',
  'Share Story': 'Shiriki Hadithi',
  'Export': 'Hamisha',
  "Character Story": "Hadithi ya Mhusika",
  "Create detailed character backstories":
      "Unda historia ya kina ya nyuma ya mhusika",
  "Create Character": "Unda Mhusika",
  "Rewrite Story": "Andika Upya Hadithi",
  "Paste Your Story": "Bandika Hadithi Yako",
  "Paste your story here to rewrite...":
      "Bandika hadithi yako hapa ili kuandika upya...",
  "Transform and improve your existing stories":
      "Badilisha na uboresha hadithi zako zilizopo",
  "Title Generator": "Kizalishi cha Kichwa",
  "Generate catchy titles for your stories":
      "Zalisha vichwa vya kuvutia kwa hadithi zako",
  "Generate Titles": "Zalisha Vichwa",
  "Blog Writer": "Mwandishi wa Blogu",
  "Blog Topic": "Mada ya Blogu",
  "Target Keywords": "Maneno Muhimu ya Lengo",
  "Target Audience (Optional)": "Hadhira Inayolengwa (Hiari)",
  "Enter your blog topic or title...":
      "Ingiza mada au kichwa cha blogu yako...",
  "e.g., AI writing, content marketing, SEO tips":
      "mf., uandishi wa AI, uuzaji wa maudhui, vidokezo vya SEO",
  "e.g., small business owners, bloggers":
      "mf., wamiliki wa biashara ndogo, waandishi wa blogu",
  "Article Type": "Aina ya Makala",
  "Writing Tone": "Sauti ya Uandishi",
  "Article Length": "Urefu wa Makala",
  "SEO Options": "Chaguo za SEO",
  "Include Meta Description": "Jumuisha Maelezo ya Meta",
  "Include Keyword Suggestions": "Jumuisha Mapendekezo ya Maneno Muhimu",
  "Include FAQs Section":
      "Jumuisha Sehemu ya Maswali Yanayoulizwa Mara kwa Mara",
  "Please enter a blog topic": "Tafadhali ingiza mada ya blogu",
  "Generate Blog": "Zalisha Blogu",
  "SEO optimized articles with keywords":
      "Makala yaliyoboreshwa kwa SEO na maneno muhimu",
  "Write Blog": "Andika Blogu",
  "YouTube Script": "Hati ya YouTube",
  "Video Topic": "Mada ya Video",
  "Key Points (Optional)": "Pointi Muhimu (Hiari)",
  "What is your video about?": "Video yako inahusu nini?",
  "List key points to cover (optional)...":
      "Orodhesha pointi muhimu za kufunika (hiari)...",
  "Video Duration": "Muda wa Video",
  "Script Options": "Chaguo za Hati",
  "Include Hook/Intro": "Jumuisha Msukumo/Utangulizi",
  "Include Call-to-Action": "Jumuisha Wito wa Kutenda",
  "Include Timestamps": "Jumuisha Alama za Wakati",
  "Please enter a video topic": "Tafadhali ingiza mada ya video",
  "Generate Script": "Zalisha Hati",
  "Create scripts for videos & reels": "Unda hati kwa video na reels",
  "Create Script": "Unda Hati",
  "Character Details": "Maelezo ya Mhusika",
  "Character Name": "Jina la Mhusika",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Umri (mf., 25, Kijana Mzima, wa Kale)",
  "Personality (e.g., brave, shy, cunning)": "Utu (mf., jasiri, aibu, mjanja)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Jukumu (mf., Shujaa, Mhalifu, Mshauri)",
  "Additional Details (optional)": "Maelezo ya Ziada (hiari)",
  "Output Style": "Mtindo wa Matokeo",
  "Generate Character": "Zalisha Mhusika",
  "Please enter character name": "Tafadhali ingiza jina la mhusika",
  "Please enter character role": "Tafadhali ingiza jukumu la mhusika",
  "Detailed": "Kwa Kina",
  "Brief": "Kwa Ufupi",
  "Elaborate": "Kwa Undani",
  "Select Tone": "Chagua Sauti",
  "Rewrite Style": "Mtindo wa Kuandika Upya",
  "Output Length": "Urefu wa Matokeo",
  "Please paste your story": "Tafadhali bandika hadithi yako",
  "Story is too short. Please provide more content.":
      "Hadithi ni fupi sana. Tafadhali toa maudhui zaidi.",
  "Same": "Sawa",
  "More Dramatic": "Zaidi ya Kudramia",
  "More Humorous": "Zaidi ya Kuchekesha",
  "More Emotional": "Zaidi ya Kihisia",
  "More Suspenseful": "Zaidi ya Kusisimua",
  "Lighter": "Nyepesi Zaidi",
  "Improved": "Iliyoboreshwa",
  "Simplified": "Iliyorahisishwa",
  "More Descriptive": "Zaidi ya Kuelezea",
  "More Dialogue": "Mazungumzo Zaidi",
  "More Action": "Vitendo Zaidi",
  "Literary": "Kisanaa",
  "Shorter": "Fupi Zaidi",
  "Longer": "Ndefu Zaidi",
  "Much Longer": "Ndefu Sana Zaidi",
  "Rewrite Now": "Andika Upya Sasa",
  "Story/Book Topic": "Mada ya Hadithi/Kitabu",
  "Keywords (Optional)": "Maneno Muhimu (Hiari)",
  "Describe your story topic or theme...":
      "Elezea mada au dhamira ya hadithi yako...",
  "e.g., magic, dragon, adventure": "mf., uchawi, joka, msafara wa kusisimua",
  "Title For": "Kichwa kwa",
  "Title Style": "Mtindo wa Kichwa",
  "Number of Titles": "Idadi ya Vichwa",
  "Book": "Kitabu",
  "Short Story": "Hadithi Fupi",
  "Novel": "Riwaya",
  "Chapter": "Sura",
  "Series": "Mfululizo",
  "Simple": "Rahisi",
  "Mysterious": "ya Kushangaza",
  "Dramatic": "ya Kudramia",
  "Catchy": "ya Kuvutia",
  "Poetic": "ya Kishairi",
  "Kids": "Watoto",
  "SEO Article": "Makala ya SEO",
  "How-To Guide": "Mwongozo wa Jinsi ya",
  "Listicle": "Makala ya Orodha",
  "Product Review": "Mapitio ya Bidhaa",
  "Opinion Piece": "Makala ya Maoni",
  "News Article": "Makala ya Habari",
  "Professional": "Kitaalamu",
  "Casual": "Kawaida",
  "Informative": "ya Kutoa Habari",
  "Persuasive": "ya Kushawishi",
  "Friendly": "ya Kirafiki",
  "Authoritative": "ya Mamlaka",
  "Short (500-800)": "Fupi (500-800)",
  "Medium (800-1500)": "Wastani (800-1500)",
  "Long (1500-2500)": "Ndefu (1500-2500)",
  "Detailed (2500+)": "Kwa Kina (2500+)",
  "Storytime": "Wakati wa Hadithi",
  "Documentary": "Filamu ya Kumbukumbu",
  "Short Reel": "Reel Fupi",
  "Educational": "ya Kielimu",
  "Review": "Mapitio",
  "Tutorial": "Mafunzo",
  "< 1 min (Shorts)": "< dakika 1 (Fupi)",
  "1-3 min": "dakika 1-3",
  "5-10 min": "dakika 5-10",
  "10-20 min": "dakika 10-20",
  "20+ min": "dakika 20+",
  "Engaging": "Inayovutia",
  "Energetic": "Yenye Nguvu",
  "Calm": "Tulivu",
  "Funny": "ya Kuchekesha",
  "Next": "Ifuatayo",
  "Get Started": "Anza",
  "Your tool for quick, high-quality essay writing":
      "Chombo chako cha uandishi wa haraka na wenye ubora wa juu",
};
