import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ta = {
  AppKeys.lblChooseLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
  "All": "அனைத்தும்",
  "AI Story Generator": "AI கதை உருவாக்கி",
  "Story Generator": "கதை உருவாக்கி",
  "Essay Writer": "கட்டுரை எழுத்தாளர்",
  "Essay length": "கட்டுரை நீளம்",
  "Script Generator": "ஸ்கிரிப்ட் உருவாக்கி",
  "Create original stories in seconds": "நொடிகளில் அசல் கதைகளை உருவாக்கவும்",
  "Academic writing made simple": "கல்வி எழுத்து எளிமையாக்கப்பட்டது",
  "Generate powerful scripts for any medium":
      "எந்த ஊடகத்திற்கும் சக்திவாய்ந்த ஸ்கிரிப்ட்களை உருவாக்கவும்",
  "Start Writing": "எழுதத் தொடங்கு",
  "Create Now": "இப்போது உருவாக்கு",
  "Start Generating": "உருவாக்கத் தொடங்கு",
  "Your Stories": "உங்கள் கதைகள்",
  "No stories yet": "இன்னும் கதைகள் இல்லை",
  "Start creating your first story!":
      "உங்கள் முதல் கதையை உருவாக்கத் தொடங்குங்கள்!",
  "Your Story Space Awaits": "உங்கள் கதை இடம் காத்திருக்கிறது",
  "Start your first story and see it appear here":
      "உங்கள் முதல் கதையைத் தொடங்கி இங்கே தோன்றுவதைப் பாருங்கள்",
  "Language": "மொழி",
  "Rate us": "எங்களை மதிப்பிடுங்கள்",
  "Share us": "எங்களைப் பகிருங்கள்",
  "Privacy Policy": "தனியுரிமைக் கொள்கை",
  "Settings": "அமைப்புகள்",
  "Select Language": "மொழியைத் தேர்ந்தெடுக்கவும்",
  "Dashboard": "டாஷ்போர்டு",
  "BENEFITS": "நன்மைகள்",
  "Subscribe": "சந்தாதாரர் ஆகுங்கள்",
  "Weekly": "வாராந்திர",
  "Monthly": "மாதாந்திர",
  "Yearly": "வருடாந்திர",
  "week": "வாரம்",
  "months": "மாதங்கள்",
  "year": "வருடம்",
  "Terms & Condition": "விதிமுறைகள் & நிபந்தனைகள்",
  "No Commitment. Cancel anytime":
      "எந்த கட்டுப்பாடும் இல்லை. எப்போது வேண்டுமானாலும் ரத்து செய்யலாம்",
  "No Payment Now": "இப்போது கட்டணம் இல்லை",
  "3 days free": "3 நாட்கள் இலவசம்",
  "Start your free trial": "உங்கள் இலவச சோதனையைத் தொடங்குங்கள்",
  "More detailed answers": "மேலும் விரிவான பதில்கள்",
  "Instant responds": "உடனடி பதில்கள்",
  "Text recognition": "உரை அங்கீகாரம்",
  "Powered by AI": "AI மூலம் இயக்கப்படுகிறது",
  "Storytelleing": "கதை சொல்லுதல்",
  ' Power': "சக்தி",
  "Unlock your \nFill ": "உங்கள் \nநிரப்பவும் திறக்கவும்",
  "Your History": "உங்கள் வரலாறு",
  "Terms and Conditions": "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
  "Short": "குறுகிய",
  "Medium": "நடுத்தர",
  "Long": "நீண்ட",
  "Length": "நீளம்",
  "Describe your topic...": "உங்கள் தலைப்பை விவரிக்கவும்...",
  "Set Creativity": "படைப்பாற்றலை அமைக்கவும்",
  "Standard": "நிலையான",
  "Creative": "படைப்பாற்றல்",
  "Complex": "சிக்கலான",
  "Select Genre": "வகையைத் தேர்ந்தெடுக்கவும்",
  "Fantasy": "கற்பனை",
  "Mystery": "மர்மம்",
  "Thriller": "த்ரில்லர்",
  "Script Tone": "ஸ்கிரிப்ட் தொனி",
  "Script Type": "ஸ்கிரிப்ட் வகை",
  "Comedy": "நகைச்சுவை",
  "Drama": "நாடகம்",
  "Horror": "திகில்",
  "Action": "ஆக்ஷன்",
  "Romance": "காதல்",
  "Go Premium": "பிரீமியம் பெறுங்கள்",
  "Unlock Everything": "அனைத்தையும் திறக்கவும்",
  "Unlimited Story Generation": "வரம்பற்ற கதை உருவாக்கம்",
  "Write Longer & Detailed Essays":
      "நீண்ட மற்றும் விரிவான கட்டுரைகளை எழுதுங்கள்",
  "Advanced Script Writer": "மேம்பட்ட ஸ்கிரிப்ட் எழுத்தாளர்",
  "Unlock All Styles & Tones": "அனைத்து பாணிகளையும் தொனிகளையும் திறக்கவும்",
  "No Word/Length Limit": "வார்த்தை/நீள வரம்பு இல்லை",
  "Remove All Ads": "அனைத்து விளம்பரங்களையும் அகற்று",
  "Restore": "மீட்டெடுக்கவும்",
  "YouTube Video": "YouTube வீடியோ",
  "Podcast": "போட்காஸ்ட்",
  "Reel": "ரீல்",
  "Motivational": "ஊக்கமளிக்கும்",
  "Advertisement": "விளம்பரம்",
  "Fairy Tale": "தேவதை கதை",
  "Sci-Fi": "அறிவியல் புனைவு",
  "Select Style": "பாணியைத் தேர்ந்தெடுக்கவும்",
  "Imaginative": "கற்பனைத் திறன்",
  "Innovative": "புதுமையான",
  "AI Story Writer": "AI கதை எழுத்தாளர்",
  "Generate": "உருவாக்கு",
  "Please wait...": "தயவுசெய்து காத்திருங்கள்...",
  "Result": "முடிவு",
  "Regenerate": "மீண்டும் உருவாக்கு",
  "Download": "பதிவிறக்கு",
  "Text copied to clipboard!": "உரை கிளிப்போர்டில் நகலெடுக்கப்பட்டது!",
  "Please enter a topic": "தயவுசெய்து ஒரு தலைப்பை உள்ளிடவும்",
  "Story Magic": "கதை மேஜிக்",
  "Let AI bring your thoughts to a full story":
      "AI உங்கள் எண்ணங்களை முழு கதையாக மாற்ற அனுமதிக்கவும்",
  "Smart Scripts": "ஸ்மார்ட் ஸ்கிரிப்ட்கள்",
  "From concept to script—fast, easy, and creative":
      "கருத்திலிருந்து ஸ்கிரிப்ட் வரை—வேகமான, எளிதான, படைப்பாற்றல்",
  "Perfect Essays": "சரியான கட்டுரைகள்",
  "You have reached your free limit": "உங்கள் இலவச வரம்பை அடைந்துவிட்டீர்கள்",
  "Donwload": "பதிவிறக்கு",
  "Press again to exit app": "ஆப்பிலிருந்து வெளியேற மீண்டும் அழுத்தவும்",
  "Saved to files": "TXT கோப்பு வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "Error: Please try again": "பிழை: மீண்டும் முயற்சிக்கவும்",
  "Subscription expired": "சந்தா காலாவதியானது",
  "Purchase cancelled": "கொள்முதல் ரத்து செய்யப்பட்டது",
  "Purchase failed": "கொள்முதல் தோல்வியடைந்தது",
  "Restore failed": "மீட்டெடுப்பு தோல்வியடைந்தது",
  "Purchase Successful!": "கொள்முதல் வெற்றி!",
  "Short (200-500 words)": "குறுகிய (200-500 வார்த்தைகள்)",
  "Medium (500-1000 words)": "நடுத்தர (500-1000 வார்த்தைகள்)",
  "Large (1000+ words)": "பெரிய (1000+ வார்த்தைகள்)",
  "Academic Level": "கல்வி நிலை",
  "Type of Paper": "காகித வகை",
  "High School": "உயர்நிலைப் பள்ளி",
  "College": "கல்லூரி",
  "Short Film": "குறும்படம்",
  "University": "பல்கலைக்கழகம்",
  "Masters": "முதுகலை",
  "Custom": "தனிப்பயன்",
  "Tiktok Video": "Tiktok வீடியோ",
  "Movie": "திரைப்படம்",
  "Expository": "விளக்கமான",
  "Argumentative": "வாதமான",
  "Narrative": "கதையான",
  "Descriptive": "விவரணையான",
  "We're sorry to hear that 😔": "அதைக் கேட்க வருத்தமாக இருக்கிறது 😔",
  "We'll try to improve 🙁": "மேம்படுத்த முயற்சிப்போம் 🙁",
  "Thanks for your feedback 🙂": "உங்கள் கருத்துக்கு நன்றி 🙂",
  "Great! We're glad you like it 😊":
      "அருமை! உங்களுக்குப் பிடித்திருப்பதில் மகிழ்ச்சி 😊",
  "Awesome! Thank you so much! 🎉": "அற்புதம்! மிக்க நன்றி! 🎉",
  "Maybe Later": "ஒருவேளை பின்னர்",
  "Tap a star to rate your experience":
      "உங்கள் அனுபவத்தை மதிப்பிட நட்சத்திரத்தைத் தட்டவும்",
  "Enjoying AI Math Solver?": "AI Math Solver பிடித்திருக்கிறதா?",
  "Thank you for rating us": "எங்களை மதிப்பிட்டதற்கு நன்றி",
  "Submit Rating": "மதிப்பீட்டை சமர்ப்பிக்கவும்",
  "Hindi": "இந்தி",
  "Enjoying AI Story Generator?": "AI Story Generator பிடித்திருக்கிறதா?",
  "Adventure": "சாகசம்",
  "Inspired": "ஊக்கமளிக்கப்பட்ட",
  "Film Script": "திரைப்பட ஸ்கிரிப்ட்",
  "Stage Play": "மேடை நாடகம்",
  "Scene Breakdown": "காட்சி பகுப்பாய்வு",
  "Dialogue Only": "உரையாடல் மட்டும்",
  "Ad loading please wait..":
      "விளம்பரம் ஏற்றப்படுகிறது, தயவுசெய்து காத்திருங்கள்...",
  "Words:": "வார்த்தைகள்:",
  "Reading:": "படித்தல்:",

  AppKeys.arabic: "அரபு",
  AppKeys.chinese: "சீன",
  AppKeys.english: "ஆங்கிலம்",
  AppKeys.french: "பிரெஞ்சு",
  AppKeys.german: "ஜெர்மன்",
  AppKeys.hindi: "இந்தி",
  AppKeys.indonesian: "இந்தோனேசியன்",
  AppKeys.japanese: "ஜப்பானிய",
  AppKeys.korean: "கொரிய",
  AppKeys.portuguese: "போர்த்துகீசிய",
  AppKeys.russian: "ரஷ்ய",
  AppKeys.spanish: "ஸ்பானிஷ்",
  AppKeys.turkish: "துருக்கிய",

  'Download As': 'இவ்வாறு பதிவிறக்கவும்',
  'Choose format to download': 'பதிவிறக்க வடிவமைப்பைத் தேர்ந்தெடுக்கவும்',
  'Text File': 'உரை கோப்பு',
  'PDF File': 'PDF கோப்பு',
  'Copy': 'நகலெடு',
  'Share': 'பகிர்',
  'Text copied!': 'உரை நகலெடுக்கப்பட்டது!',
  'Copied to clipboard': 'கிளிப்போர்டில் நகலெடுக்கப்பட்டது',
  'File saved successfully': 'கோப்பு வெற்றிகரமாக சேமிக்கப்பட்டது',
  'Error saving file': 'கோப்பைச் சேமிப்பதில் பிழை',
  'Share Story': 'கதையைப் பகிர்',
  'Export': 'ஏற்றுமதி',
  "Character Story": "கதாபாத்திர கதை",
  "Create detailed character backstories":
      "கதாபாத்திரத்தின் விரிவான பின்னணி கதைகளை உருவாக்குங்கள்",
  "Create Character": "கதாபாத்திரம் உருவாக்கு",
  "Rewrite Story": "கதையை மீண்டும் எழுது",
  "Paste Your Story": "உங்கள் கதையை ஒட்டுங்கள்",
  "Paste your story here to rewrite...":
      "மீண்டும் எழுதுவதற்கு உங்கள் கதையை இங்கே ஒட்டுங்கள்...",
  "Transform and improve your existing stories":
      "உங்கள் தற்போதைய கதைகளை மாற்றி மேம்படுத்துங்கள்",
  "Title Generator": "தலைப்பு உருவாக்கி",
  "Generate catchy titles for your stories":
      "உங்கள் கதைகளுக்கு கவர்ச்சிகரமான தலைப்புகளை உருவாக்குங்கள்",
  "Generate Titles": "தலைப்புகளை உருவாக்கு",
  "Blog Writer": "வலைப்பதிவு எழுத்தாளர்",
  "Blog Topic": "வலைப்பதிவு தலைப்பு",
  "Target Keywords": "இலக்கு முக்கியச்சொற்கள்",
  "Target Audience (Optional)": "இலக்கு பார்வையாளர்கள் (விருப்பத்திற்குரியது)",
  "Enter your blog topic or title...":
      "உங்கள் வலைப்பதிவு தலைப்பு அல்லது பெயரை உள்ளிடுங்கள்...",
  "e.g., AI writing, content marketing, SEO tips":
      "எ.கா., AI எழுத்து, உள்ளடக்க சந்தைப்படுத்தல், SEO குறிப்புகள்",
  "e.g., small business owners, bloggers":
      "எ.கா., சிறு வணிக உரிமையாளர்கள், வலைப்பதிவர்கள்",
  "Article Type": "கட்டுரை வகை",
  "Writing Tone": "எழுத்து தொனி",
  "Article Length": "கட்டுரை நீளம்",
  "SEO Options": "SEO விருப்பங்கள்",
  "Include Meta Description": "மெட்டா விளக்கம் சேர்க்கவும்",
  "Include Keyword Suggestions": "முக்கியச்சொல் பரிந்துரைகள் சேர்க்கவும்",
  "Include FAQs Section": "அடிக்கடி கேட்கப்படும் கேள்விகள் பகுதி சேர்க்கவும்",
  "Please enter a blog topic": "தயவுசெய்து வலைப்பதிவு தலைப்பை உள்ளிடுங்கள்",
  "Generate Blog": "வலைப்பதிவை உருவாக்கு",
  "SEO optimized articles with keywords":
      "முக்கியச்சொற்களுடன் SEO மேம்படுத்தப்பட்ட கட்டுரைகள்",
  "Write Blog": "வலைப்பதிவு எழுது",
  "YouTube Script": "YouTube திரைக்கதை",
  "Video Topic": "வீடியோ தலைப்பு",
  "Key Points (Optional)": "முக்கிய புள்ளிகள் (விருப்பத்திற்குரியது)",
  "What is your video about?": "உங்கள் வீடியோ எதைப் பற்றியது?",
  "List key points to cover (optional)...":
      "உள்ளடக்க வேண்டிய முக்கிய புள்ளிகளை பட்டியலிடுங்கள் (விருப்பத்திற்குரியது)...",
  "Video Duration": "வீடியோ கால அளவு",
  "Script Options": "திரைக்கதை விருப்பங்கள்",
  "Include Hook/Intro": "ஹூக்/அறிமுகம் சேர்க்கவும்",
  "Include Call-to-Action": "செயல் வேண்டுகோள் சேர்க்கவும்",
  "Include Timestamps": "நேர முத்திரைகள் சேர்க்கவும்",
  "Please enter a video topic": "தயவுசெய்து வீடியோ தலைப்பை உள்ளிடுங்கள்",
  "Generate Script": "திரைக்கதையை உருவாக்கு",
  "Create scripts for videos & reels":
      "வீடியோக்கள் மற்றும் ரீல்களுக்கு திரைக்கதைகளை உருவாக்குங்கள்",
  "Create Script": "திரைக்கதை உருவாக்கு",
  "Character Details": "கதாபாத்திர விவரங்கள்",
  "Character Name": "கதாபாத்திர பெயர்",
  "Age (e.g., 25, Young Adult, Ancient)":
      "வயது (எ.கா., 25, இளம் வயதினர், பழங்காலம்)",
  "Personality (e.g., brave, shy, cunning)":
      "ஆளுமை (எ.கா., தைரியமான, கூச்சமான, புத்திசாலி)",
  "Role (e.g., Hero, Villain, Mentor)":
      "பாத்திரம் (எ.கா., நாயகன், வில்லன், வழிகாட்டி)",
  "Additional Details (optional)": "கூடுதல் விவரங்கள் (விருப்பத்திற்குரியது)",
  "Output Style": "வெளியீட்டு பாணி",
  "Generate Character": "கதாபாத்திரம் உருவாக்கு",
  "Please enter character name": "தயவுசெய்து கதாபாத்திர பெயரை உள்ளிடுங்கள்",
  "Please enter character role":
      "தயவுசெய்து கதாபாத்திர பாத்திரத்தை உள்ளிடுங்கள்",
  "Detailed": "விரிவான",
  "Brief": "சுருக்கமான",
  "Elaborate": "விளக்கமான",
  "Select Tone": "தொனியை தேர்ந்தெடுங்கள்",
  "Rewrite Style": "மீண்டும் எழுதும் பாணி",
  "Output Length": "வெளியீட்டு நீளம்",
  "Please paste your story": "தயவுசெய்து உங்கள் கதையை ஒட்டுங்கள்",
  "Story is too short. Please provide more content.":
      "கதை மிகவும் குறுகியது. தயவுசெய்து அதிக உள்ளடக்கம் வழங்குங்கள்.",
  "Same": "அதே",
  "More Dramatic": "மேலும் நாடகீயமான",
  "More Humorous": "மேலும் நகைச்சுவையான",
  "More Emotional": "மேலும் உணர்ச்சிமயமான",
  "More Suspenseful": "மேலும் பதட்டமான",
  "Lighter": "இலகுவான",
  "Improved": "மேம்படுத்தப்பட்ட",
  "Simplified": "எளிமைப்படுத்தப்பட்ட",
  "More Descriptive": "மேலும் விளக்கமான",
  "More Dialogue": "அதிக உரையாடல்",
  "More Action": "அதிக செயல்",
  "Literary": "இலக்கியமான",
  "Shorter": "குறுகியது",
  "Longer": "நீளமானது",
  "Much Longer": "மிகவும் நீளமானது",
  "Rewrite Now": "இப்போது மீண்டும் எழுது",
  "Story/Book Topic": "கதை/புத்தக தலைப்பு",
  "Keywords (Optional)": "முக்கியச்சொற்கள் (விருப்பத்திற்குரியது)",
  "Describe your story topic or theme...":
      "உங்கள் கதையின் தலைப்பு அல்லது கருப்பொருளை விவரிக்கவும்...",
  "e.g., magic, dragon, adventure": "எ.கா., மந்திரம், டிராகன், சாகசம்",
  "Title For": "தலைப்பு",
  "Title Style": "தலைப்பு பாணி",
  "Number of Titles": "தலைப்புகளின் எண்ணிக்கை",
  "Book": "புத்தகம்",
  "Short Story": "குறுகதை",
  "Novel": "நாவல்",
  "Chapter": "அத்தியாயம்",
  "Series": "தொடர்",
  "Simple": "எளிய",
  "Mysterious": "மர்மமான",
  "Dramatic": "நாடகீயமான",
  "Catchy": "கவர்ச்சிகரமான",
  "Poetic": "கவிதையான",
  "Kids": "குழந்தைகள்",
  "SEO Article": "SEO கட்டுரை",
  "How-To Guide": "எப்படி வழிகாட்டி",
  "Listicle": "பட்டியல் கட்டுரை",
  "Product Review": "தயாரிப்பு மதிப்பாய்வு",
  "Opinion Piece": "கருத்துக் கட்டுரை",
  "News Article": "செய்தி கட்டுரை",
  "Professional": "தொழில்முறை",
  "Casual": "சாதாரண",
  "Informative": "தகவல் தரும்",
  "Persuasive": "சமாதானப்படுத்தும்",
  "Friendly": "நட்பான",
  "Authoritative": "அதிகாரபூர்வமான",
  "Short (500-800)": "குறுகிய (500-800)",
  "Medium (800-1500)": "நடுத்தர (800-1500)",
  "Long (1500-2500)": "நீளமான (1500-2500)",
  "Detailed (2500+)": "விரிவான (2500+)",
  "Storytime": "கதை நேரம்",
  "Documentary": "ஆவணப்படம்",
  "Short Reel": "குறுகிய ரீல்",
  "Educational": "கல்வி சார்ந்த",
  "Review": "மதிப்பாய்வு",
  "Tutorial": "பயிற்சி",
  "< 1 min (Shorts)": "< 1 நிமிடம் (Shorts)",
  "1-3 min": "1-3 நிமிடம்",
  "5-10 min": "5-10 நிமிடம்",
  "10-20 min": "10-20 நிமிடம்",
  "20+ min": "20+ நிமிடம்",
  "Engaging": "கவர்ந்திழுக்கும்",
  "Energetic": "ஆற்றல்மிக்க",
  "Calm": "அமைதியான",
  "Funny": "வேடிக்கையான",
  "Next": "அடுத்து",
  "Get Started": "தொடங்குங்கள்",
  "Your tool for quick, high-quality essay writing":
      "விரைவான மற்றும் உயர்தர கட்டுரை எழுதுவதற்கான உங்கள் கருவி",
};
