import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> th = {
  AppKeys.lblChooseLanguage: "เลือกภาษา",
  "All": "ทั้งหมด",
  "AI Story Generator": "เครื่องสร้างเรื่องราว AI",
  "Story Generator": "เครื่องสร้างเรื่องราว",
  "Essay Writer": "นักเขียนเรียงความ",
  "Essay length": "ความยาวเรียงความ",
  "Script Generator": "เครื่องสร้างสคริปต์",
  "Create original stories in seconds": "สร้างเรื่องราวต้นฉบับในไม่กี่วินาที",
  "Academic writing made simple": "การเขียนวิชาการทำให้ง่าย",
  "Generate powerful scripts for any medium":
      "สร้างสคริปต์ที่ทรงพลังสำหรับสื่อใดก็ได้",
  "Start Writing": "เริ่มเขียน",
  "Create Now": "สร้างเดี๋ยวนี้",
  "Start Generating": "เริ่มสร้าง",
  "Your Stories": "เรื่องราวของคุณ",
  "No stories yet": "ยังไม่มีเรื่องราว",
  "Start creating your first story!": "เริ่มสร้างเรื่องราวแรกของคุณ!",
  "Your Story Space Awaits": "พื้นที่เรื่องราวของคุณรออยู่",
  "Start your first story and see it appear here":
      "เริ่มเรื่องราวแรกของคุณและดูมันปรากฏที่นี่",
  "Language": "ภาษา",
  "Rate us": "ให้คะแนนเรา",
  "Share us": "แชร์เรา",
  "Privacy Policy": "นโยบายความเป็นส่วนตัว",
  "Settings": "การตั้งค่า",
  "Select Language": "เลือกภาษา",
  "Dashboard": "แดชบอร์ด",
  "BENEFITS": "ประโยชน์",
  "Subscribe": "สมัครสมาชิก",
  "Weekly": "รายสัปดาห์",
  "Monthly": "รายเดือน",
  "Yearly": "รายปี",
  "week": "สัปดาห์",
  "months": "เดือน",
  "year": "ปี",
  "Terms & Condition": "ข้อกำหนดและเงื่อนไข",
  "No Commitment. Cancel anytime": "ไม่มีข้อผูกมัด ยกเลิกได้ทุกเมื่อ",
  "No Payment Now": "ไม่ต้องชำระเงินตอนนี้",
  "3 days free": "ฟรี 3 วัน",
  "Start your free trial": "เริ่มทดลองใช้ฟรี",
  "More detailed answers": "คำตอบที่ละเอียดมากขึ้น",
  "Instant responds": "ตอบกลับทันที",
  "Text recognition": "การรู้จำข้อความ",
  "Powered by AI": "ขับเคลื่อนโดย AI",
  "Storytelleing": "การเล่าเรื่อง",
  ' Power': "พลัง",
  "Unlock your \nFill ": "ปลดล็อคของคุณ \nกรอก",
  "Your History": "ประวัติของคุณ",
  "Terms and Conditions": "ข้อกำหนดและเงื่อนไข",
  "Short": "สั้น",
  "Medium": "กลาง",
  "Long": "ยาว",
  "Length": "ความยาว",
  "Describe your topic...": "อธิบายหัวข้อของคุณ...",
  "Set Creativity": "ตั้งค่าความคิดสร้างสรรค์",
  "Standard": "มาตรฐาน",
  "Creative": "สร้างสรรค์",
  "Complex": "ซับซ้อน",
  "Select Genre": "เลือกประเภท",
  "Fantasy": "แฟนตาซี",
  "Mystery": "ลึกลับ",
  "Thriller": "ระทึกขวัญ",
  "Script Tone": "โทนสคริปต์",
  "Script Type": "ประเภทสคริปต์",
  "Comedy": "ตลก",
  "Drama": "ดราม่า",
  "Horror": "สยองขวัญ",
  "Action": "แอ็คชั่น",
  "Romance": "โรแมนติก",
  "Go Premium": "รับพรีเมียม",
  "Unlock Everything": "ปลดล็อคทุกอย่าง",
  "Unlimited Story Generation": "สร้างเรื่องราวไม่จำกัด",
  "Write Longer & Detailed Essays": "เขียนเรียงความยาวและละเอียดมากขึ้น",
  "Advanced Script Writer": "นักเขียนสคริปต์ขั้นสูง",
  "Unlock All Styles & Tones": "ปลดล็อคสไตล์และโทนทั้งหมด",
  "No Word/Length Limit": "ไม่จำกัดคำ/ความยาว",
  "Remove All Ads": "ลบโฆษณาทั้งหมด",
  "Restore": "กู้คืน",
  "YouTube Video": "วิดีโอ YouTube",
  "Podcast": "พอดแคสต์",
  "Reel": "รีล",
  "Motivational": "สร้างแรงบันดาลใจ",
  "Advertisement": "โฆษณา",
  "Fairy Tale": "นิทาน",
  "Sci-Fi": "ไซไฟ",
  "Select Style": "เลือกสไตล์",
  "Imaginative": "จินตนาการ",
  "Innovative": "นวัตกรรม",
  "AI Story Writer": "นักเขียนเรื่องราว AI",
  "Generate": "สร้าง",
  "Please wait...": "กรุณารอสักครู่...",
  "Result": "ผลลัพธ์",
  "Regenerate": "สร้างใหม่",
  "Download": "ดาวน์โหลด",
  "Text copied to clipboard!": "คัดลอกข้อความไปยังคลิปบอร์ดแล้ว!",
  "Please enter a topic": "กรุณาใส่หัวข้อ",
  "Story Magic": "เวทมนตร์เรื่องราว",
  "Let AI bring your thoughts to a full story":
      "ให้ AI แปลงความคิดของคุณเป็นเรื่องราวที่สมบูรณ์",
  "Smart Scripts": "สคริปต์อัจฉริยะ",
  "From concept to script—fast, easy, and creative":
      "จากแนวคิดสู่สคริปต์—รวดเร็ว ง่าย และสร้างสรรค์",
  "Perfect Essays": "เรียงความสมบูรณ์แบบ",
  "You have reached your free limit": "คุณถึงขีดจำกัดฟรีแล้ว",
  "Donwload": "ดาวน์โหลด",
  "Press again to exit app": "กดอีกครั้งเพื่อออกจากแอป",
  "Saved to files": "บันทึกไฟล์ TXT สำเร็จ!",
  "Error: Please try again": "ข้อผิดพลาด: กรุณาลองอีกครั้ง",
  "Subscription expired": "การสมัครสมาชิกหมดอายุ",
  "Purchase cancelled": "ยกเลิกการซื้อ",
  "Purchase failed": "การซื้อล้มเหลว",
  "Restore failed": "การกู้คืนล้มเหลว",
  "Purchase Successful!": "ซื้อสำเร็จ!",
  "Short (200-500 words)": "สั้น (200-500 คำ)",
  "Medium (500-1000 words)": "กลาง (500-1000 คำ)",
  "Large (1000+ words)": "ยาว (1000+ คำ)",
  "Academic Level": "ระดับการศึกษา",
  "Type of Paper": "ประเภทของบทความ",
  "High School": "มัธยมปลาย",
  "College": "วิทยาลัย",
  "Short Film": "หนังสั้น",
  "University": "มหาวิทยาลัย",
  "Masters": "ปริญญาโท",
  "Custom": "กำหนดเอง",
  "Tiktok Video": "วิดีโอ Tiktok",
  "Movie": "ภาพยนตร์",
  "Expository": "อธิบาย",
  "Argumentative": "โต้แย้ง",
  "Narrative": "เล่าเรื่อง",
  "Descriptive": "บรรยาย",
  "We're sorry to hear that 😔": "เสียใจที่ได้ยิน 😔",
  "We'll try to improve 🙁": "เราจะพยายามปรับปรุง 🙁",
  "Thanks for your feedback 🙂": "ขอบคุณสำหรับความคิดเห็น 🙂",
  "Great! We're glad you like it 😊": "เยี่ยม! เราดีใจที่คุณชอบ 😊",
  "Awesome! Thank you so much! 🎉": "สุดยอด! ขอบคุณมาก! 🎉",
  "Maybe Later": "อาจจะทีหลัง",
  "Tap a star to rate your experience": "แตะดาวเพื่อให้คะแนนประสบการณ์ของคุณ",
  "Enjoying AI Math Solver?": "ชอบ AI Math Solver ไหม?",
  "Thank you for rating us": "ขอบคุณที่ให้คะแนนเรา",
  "Submit Rating": "ส่งคะแนน",
  "Hindi": "ฮินดี",
  "Enjoying AI Story Generator?": "ชอบ AI Story Generator ไหม?",
  "Adventure": "ผจญภัย",
  "Inspired": "แรงบันดาลใจ",
  "Film Script": "สคริปต์ภาพยนตร์",
  "Stage Play": "ละครเวที",
  "Scene Breakdown": "การวิเคราะห์ฉาก",
  "Dialogue Only": "บทสนทนาเท่านั้น",
  "Ad loading please wait..": "กำลังโหลดโฆษณา กรุณารอสักครู่...",
  "Words:": "คำ:",
  "Reading:": "การอ่าน:",

  AppKeys.arabic: "อาหรับ",
  AppKeys.chinese: "จีน",
  AppKeys.english: "อังกฤษ",
  AppKeys.french: "ฝรั่งเศส",
  AppKeys.german: "เยอรมัน",
  AppKeys.hindi: "ฮินดี",
  AppKeys.indonesian: "อินโดนีเซีย",
  AppKeys.japanese: "ญี่ปุ่น",
  AppKeys.korean: "เกาหลี",
  AppKeys.portuguese: "โปรตุเกส",
  AppKeys.russian: "รัสเซีย",
  AppKeys.spanish: "สเปน",
  AppKeys.turkish: "ตุรกี",

  'Download As': 'ดาวน์โหลดเป็น',
  'Choose format to download': 'เลือกรูปแบบที่จะดาวน์โหลด',
  'Text File': 'ไฟล์ข้อความ',
  'PDF File': 'ไฟล์ PDF',
  'Copy': 'คัดลอก',
  'Share': 'แชร์',
  'Text copied!': 'คัดลอกข้อความแล้ว!',
  'Copied to clipboard': 'คัดลอกไปยังคลิปบอร์ดแล้ว',
  'File saved successfully': 'บันทึกไฟล์สำเร็จ',
  'Error saving file': 'ข้อผิดพลาดในการบันทึกไฟล์',
  'Share Story': 'แชร์เรื่องราว',
  'Export': 'ส่งออก',
  "Character Story": "เรื่องราวของตัวละคร",
  "Create detailed character backstories":
      "สร้างประวัติเบื้องหลังของตัวละครอย่างละเอียด",
  "Create Character": "สร้างตัวละคร",
  "Rewrite Story": "เขียนเรื่องใหม่",
  "Paste Your Story": "วางเรื่องราวของคุณ",
  "Paste your story here to rewrite...":
      "วางเรื่องราวของคุณที่นี่เพื่อเขียนใหม่...",
  "Transform and improve your existing stories":
      "เปลี่ยนแปลงและปรับปรุงเรื่องราวที่มีอยู่ของคุณ",
  "Title Generator": "เครื่องมือสร้างชื่อเรื่อง",
  "Generate catchy titles for your stories":
      "สร้างชื่อเรื่องที่น่าสนใจสำหรับเรื่องราวของคุณ",
  "Generate Titles": "สร้างชื่อเรื่อง",
  "Blog Writer": "นักเขียนบล็อก",
  "Blog Topic": "หัวข้อบล็อก",
  "Target Keywords": "คำสำคัญเป้าหมาย",
  "Target Audience (Optional)": "กลุ่มเป้าหมาย (ไม่บังคับ)",
  "Enter your blog topic or title...": "ป้อนหัวข้อหรือชื่อบล็อกของคุณ...",
  "e.g., AI writing, content marketing, SEO tips":
      "เช่น การเขียน AI, การตลาดเนื้อหา, เคล็ดลับ SEO",
  "e.g., small business owners, bloggers":
      "เช่น เจ้าของธุรกิจขนาดเล็ก, บล็อกเกอร์",
  "Article Type": "ประเภทบทความ",
  "Writing Tone": "โทนการเขียน",
  "Article Length": "ความยาวบทความ",
  "SEO Options": "ตัวเลือก SEO",
  "Include Meta Description": "รวมคำอธิบาย Meta",
  "Include Keyword Suggestions": "รวมคำแนะนำคำสำคัญ",
  "Include FAQs Section": "รวมส่วน FAQ",
  "Please enter a blog topic": "กรุณาป้อนหัวข้อบล็อก",
  "Generate Blog": "สร้างบล็อก",
  "SEO optimized articles with keywords": "บทความที่ปรับปรุง SEO พร้อมคำสำคัญ",
  "Write Blog": "เขียนบล็อก",
  "YouTube Script": "สคริปต์ YouTube",
  "Video Topic": "หัวข้อวิดีโอ",
  "Key Points (Optional)": "ประเด็นสำคัญ (ไม่บังคับ)",
  "What is your video about?": "วิดีโอของคุณเกี่ยวกับอะไร?",
  "List key points to cover (optional)...":
      "แสดงรายการประเด็นสำคัญที่ต้องครอบคลุม (ไม่บังคับ)...",
  "Video Duration": "ระยะเวลาวิดีโอ",
  "Script Options": "ตัวเลือกสคริปต์",
  "Include Hook/Intro": "รวมตัวดึงดูด/บทนำ",
  "Include Call-to-Action": "รวมคำกระตุ้นให้ดำเนินการ",
  "Include Timestamps": "รวมการประทับเวลา",
  "Please enter a video topic": "กรุณาป้อนหัวข้อวิดีโอ",
  "Generate Script": "สร้างสคริปต์",
  "Create scripts for videos & reels": "สร้างสคริปต์สำหรับวิดีโอและรีล",
  "Create Script": "สร้างสคริปต์",
  "Character Details": "รายละเอียดตัวละคร",
  "Character Name": "ชื่อตัวละคร",
  "Age (e.g., 25, Young Adult, Ancient)": "อายุ (เช่น 25, วัยรุ่น, โบราณ)",
  "Personality (e.g., brave, shy, cunning)":
      "บุคลิกภาพ (เช่น กล้าหาญ, ขี้อาย, ฉลาดแกมโกง)",
  "Role (e.g., Hero, Villain, Mentor)":
      "บทบาท (เช่น วีรบุรุษ, ผู้ร้าย, ที่ปรึกษา)",
  "Additional Details (optional)": "รายละเอียดเพิ่มเติม (ไม่บังคับ)",
  "Output Style": "รูปแบบเอาต์พุต",
  "Generate Character": "สร้างตัวละคร",
  "Please enter character name": "กรุณาป้อนชื่อตัวละคร",
  "Please enter character role": "กรุณาป้อนบทบาทตัวละคร",
  "Detailed": "ละเอียด",
  "Brief": "สั้น",
  "Elaborate": "ขยายความ",
  "Select Tone": "เลือกโทน",
  "Rewrite Style": "สไตล์การเขียนใหม่",
  "Output Length": "ความยาวเอาต์พุต",
  "Please paste your story": "กรุณาวางเรื่องราวของคุณ",
  "Story is too short. Please provide more content.":
      "เรื่องราวสั้นเกินไป กรุณาเพิ่มเนื้อหา",
  "Same": "เหมือนเดิม",
  "More Dramatic": "ดราม่ามากขึ้น",
  "More Humorous": "ตลกมากขึ้น",
  "More Emotional": "อารมณ์มากขึ้น",
  "More Suspenseful": "ลุ้นระทึกมากขึ้น",
  "Lighter": "เบาลง",
  "Improved": "ปรับปรุงแล้ว",
  "Simplified": "เรียบง่ายขึ้น",
  "More Descriptive": "พรรณนามากขึ้น",
  "More Dialogue": "บทสนทนามากขึ้น",
  "More Action": "แอ็กชันมากขึ้น",
  "Literary": "วรรณกรรม",
  "Shorter": "สั้นลง",
  "Longer": "ยาวขึ้น",
  "Much Longer": "ยาวมากขึ้น",
  "Rewrite Now": "เขียนใหม่ตอนนี้",
  "Story/Book Topic": "หัวข้อเรื่อง/หนังสือ",
  "Keywords (Optional)": "คำสำคัญ (ไม่บังคับ)",
  "Describe your story topic or theme...":
      "อธิบายหัวข้อหรือธีมของเรื่องราวคุณ...",
  "e.g., magic, dragon, adventure": "เช่น เวทมนตร์, มังกร, การผจญภัย",
  "Title For": "ชื่อเรื่องสำหรับ",
  "Title Style": "รูปแบบชื่อเรื่อง",
  "Number of Titles": "จำนวนชื่อเรื่อง",
  "Book": "หนังสือ",
  "Short Story": "เรื่องสั้น",
  "Novel": "นิยาย",
  "Chapter": "บท",
  "Series": "ซีรีส์",
  "Simple": "เรียบง่าย",
  "Mysterious": "ลึกลับ",
  "Dramatic": "ดราม่า",
  "Catchy": "ดึงดูด",
  "Poetic": "บทกวี",
  "Kids": "เด็ก",
  "SEO Article": "บทความ SEO",
  "How-To Guide": "คู่มือวิธีทำ",
  "Listicle": "บทความรายการ",
  "Product Review": "รีวิวสินค้า",
  "Opinion Piece": "บทความความคิดเห็น",
  "News Article": "บทความข่าว",
  "Professional": "มืออาชีพ",
  "Casual": "ทั่วไป",
  "Informative": "ให้ข้อมูล",
  "Persuasive": "โน้มน้าว",
  "Friendly": "เป็นกันเอง",
  "Authoritative": "มีอำนาจ",
  "Short (500-800)": "สั้น (500-800)",
  "Medium (800-1500)": "กลาง (800-1500)",
  "Long (1500-2500)": "ยาว (1500-2500)",
  "Detailed (2500+)": "ละเอียด (2500+)",
  "Storytime": "เวลาเล่าเรื่อง",
  "Documentary": "สารคดี",
  "Short Reel": "รีลสั้น",
  "Educational": "การศึกษา",
  "Review": "รีวิว",
  "Tutorial": "บทเรียน",
  "< 1 min (Shorts)": "< 1 นาที (Shorts)",
  "1-3 min": "1-3 นาที",
  "5-10 min": "5-10 นาที",
  "10-20 min": "10-20 นาที",
  "20+ min": "20+ นาที",
  "Engaging": "น่าสนใจ",
  "Energetic": "กระตือรือร้น",
  "Calm": "สงบ",
  "Funny": "ตลก",
  "Next": "ถัดไป",
  "Get Started": "เริ่มต้น",
  "Your tool for quick, high-quality essay writing":
      "เครื่องมือของคุณสำหรับการเขียนเรียงความที่รวดเร็วและมีคุณภาพสูง",
};
