import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> tr = {
  AppKeys.lblChooseLanguage: "Dil Seçin",
  "All": "Tümü",
  "AI Story Generator": "AI Hikaye Oluşturucu",
  "Story Generator": "Hikaye Oluşturucu",
  "Essay Writer": "Makale Yazarı",
  "Essay length": "Makale uzunluğu",
  "Script Generator": "Senaryo Oluşturucu",
  "Create original stories in seconds":
      "Saniyeler içinde orijinal hikayeler oluşturun",
  "Academic writing made simple": "Akademik yazım kolaylaştırıldı",
  "Generate powerful scripts for any medium":
      "Her ortam için güçlü senaryolar oluşturun",
  "Start Writing": "Yazmaya Başla",
  "Create Now": "Şimdi Oluştur",
  "Start Generating": "Oluşturmaya Başla",
  "Your Stories": "Hikayeleriniz",
  "No stories yet": "Henüz hikaye yok",
  "Start creating your first story!": "İlk hikayenizi oluşturmaya başlayın!",
  "Your Story Space Awaits": "Hikaye Alanınız Bekliyor",
  "Start your first story and see it appear here":
      "İlk hikayenizi başlatın ve burada görün",
  "Language": "Dil",
  "Rate us": "Bizi değerlendirin",
  "Share us": "Bizi paylaşın",
  "Privacy Policy": "Gizlilik Politikası",
  "Settings": "Ayarlar",
  "Select Language": "Dil Seçin",
  "Dashboard": "Kontrol Paneli",
  "BENEFITS": "AVANTAJLAR",
  "Subscribe": "Abone Ol",
  "Weekly": "Haftalık",
  "Monthly": "Aylık",
  "Yearly": "Yıllık",
  "week": "hafta",
  "months": "ay",
  "year": "yıl",
  "Terms & Condition": "Şartlar ve Koşullar",
  "No Commitment. Cancel anytime": "Taahhüt yok. İstediğiniz zaman iptal edin",
  "No Payment Now": "Şimdi ödeme yok",
  "3 days free": "3 gün ücretsiz",
  "Start your free trial": "Ücretsiz denemenizi başlatın",
  "More detailed answers": "Daha detaylı cevaplar",
  "Instant responds": "Anında yanıtlar",
  "Text recognition": "Metin tanıma",
  "Powered by AI": "AI ile destekleniyor",
  "Storytelleing": "Hikaye Anlatımı",
  ' Power': "Güç",
  "Unlock your \nFill ": "Kilidi aç \nDoldur",
  "Your History": "Geçmişiniz",
  "Terms and Conditions": "Şartlar ve Koşullar",
  "Short": "Kısa",
  "Medium": "Orta",
  "Long": "Uzun",
  "Length": "Uzunluk",
  "Describe your topic...": "Konunuzu tanımlayın...",
  "Set Creativity": "Yaratıcılığı Ayarla",
  "Standard": "Standart",
  "Creative": "Yaratıcı",
  "Complex": "Karmaşık",
  "Select Genre": "Tür Seçin",
  "Fantasy": "Fantazi",
  "Mystery": "Gizem",
  "Thriller": "Gerilim",
  "Script Tone": "Senaryo Tonu",
  "Script Type": "Senaryo Türü",
  "Comedy": "Komedi",
  "Drama": "Drama",
  "Horror": "Korku",
  "Action": "Aksiyon",
  "Romance": "Romantik",
  "Go Premium": "Premium'a Geç",
  "Unlock Everything": "Her Şeyin Kilidini Aç",
  "Unlimited Story Generation": "Sınırsız Hikaye Oluşturma",
  "Write Longer & Detailed Essays": "Daha Uzun ve Detaylı Makaleler Yazın",
  "Advanced Script Writer": "Gelişmiş Senaryo Yazarı",
  "Unlock All Styles & Tones": "Tüm Stillerin ve Tonların Kilidini Aç",
  "No Word/Length Limit": "Kelime/Uzunluk Sınırı Yok",
  "Remove All Ads": "Tüm Reklamları Kaldır",
  "Restore": "Geri Yükle",
  "YouTube Video": "YouTube Videosu",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Motivasyonel",
  "Advertisement": "Reklam",
  "Fairy Tale": "Peri Masalı",
  "Sci-Fi": "Bilim Kurgu",
  "Select Style": "Stil Seçin",
  "Imaginative": "Hayal Gücü",
  "Innovative": "Yenilikçi",
  "AI Story Writer": "AI Hikaye Yazarı",
  "Generate": "Oluştur",
  "Please wait...": "Lütfen bekleyin...",
  "Result": "Sonuç",
  "Regenerate": "Yeniden Oluştur",
  "Download": "İndir",
  "Text copied to clipboard!": "Metin panoya kopyalandı!",
  "Please enter a topic": "Lütfen bir konu girin",
  "Story Magic": "Hikaye Büyüsü",
  "Let AI bring your thoughts to a full story":
      "AI'ın düşüncelerinizi tam bir hikayeye dönüştürmesine izin verin",
  "Smart Scripts": "Akıllı Senaryolar",
  "From concept to script—fast, easy, and creative":
      "Konseptten senaryoya—hızlı, kolay ve yaratıcı",
  "Perfect Essays": "Mükemmel Makaleler",
  "You have reached your free limit": "Ücretsiz limitinize ulaştınız",
  "Donwload": "İndir",
  "Press again to exit app": "Uygulamadan çıkmak için tekrar basın",
  "Saved to files": "TXT dosyası başarıyla kaydedildi!",
  "Error: Please try again": "Hata: Lütfen tekrar deneyin",
  "Subscription expired": "Abonelik süresi doldu",
  "Purchase cancelled": "Satın alma iptal edildi",
  "Purchase failed": "Satın alma başarısız oldu",
  "Restore failed": "Geri yükleme başarısız oldu",
  "Purchase Successful!": "Satın Alma Başarılı!",
  "Short (200-500 words)": "Kısa (200-500 kelime)",
  "Medium (500-1000 words)": "Orta (500-1000 kelime)",
  "Large (1000+ words)": "Uzun (1000+ kelime)",
  "Academic Level": "Akademik Seviye",
  "Type of Paper": "Yazı Türü",
  "High School": "Lise",
  "College": "Üniversite",
  "Short Film": "Kısa Film",
  "University": "Üniversite",
  "Masters": "Yüksek Lisans",
  "Custom": "Özel",
  "Tiktok Video": "Tiktok Videosu",
  "Movie": "Film",
  "Expository": "Açıklayıcı",
  "Argumentative": "Tartışmacı",
  "Narrative": "Anlatımsal",
  "Descriptive": "Betimleyici",
  "We're sorry to hear that 😔": "Bunu duyduğumuz için üzgünüz 😔",
  "We'll try to improve 🙁": "Geliştirmeye çalışacağız 🙁",
  "Thanks for your feedback 🙂": "Geri bildiriminiz için teşekkürler 🙂",
  "Great! We're glad you like it 😊": "Harika! Beğenmenize sevindik 😊",
  "Awesome! Thank you so much! 🎉": "Müthiş! Çok teşekkürler! 🎉",
  "Maybe Later": "Belki Daha Sonra",
  "Tap a star to rate your experience":
      "Deneyiminizi değerlendirmek için bir yıldıza dokunun",
  "Enjoying AI Math Solver?": "AI Math Solver'ı beğeniyor musunuz?",
  "Thank you for rating us": "Bizi değerlendirdiğiniz için teşekkürler",
  "Submit Rating": "Değerlendirmeyi Gönder",
  "Hindi": "Hintçe",
  "Enjoying AI Story Generator?": "AI Story Generator'ı beğeniyor musunuz?",
  "Adventure": "Macera",
  "Inspired": "İlham Almış",
  "Film Script": "Film Senaryosu",
  "Stage Play": "Sahne Oyunu",
  "Scene Breakdown": "Sahne Analizi",
  "Dialogue Only": "Sadece Diyalog",
  "Ad loading please wait..": "Reklam yükleniyor, lütfen bekleyin...",
  "Words:": "Kelimeler:",
  "Reading:": "Okuma:",

  AppKeys.arabic: "Arapça",
  AppKeys.chinese: "Çince",
  AppKeys.english: "İngilizce",
  AppKeys.french: "Fransızca",
  AppKeys.german: "Almanca",
  AppKeys.hindi: "Hintçe",
  AppKeys.indonesian: "Endonezce",
  AppKeys.japanese: "Japonca",
  AppKeys.korean: "Korece",
  AppKeys.portuguese: "Portekizce",
  AppKeys.russian: "Rusça",
  AppKeys.spanish: "İspanyolca",
  AppKeys.turkish: "Türkçe",

  'Download As': 'Farklı İndir',
  'Choose format to download': 'İndirmek için format seçin',
  'Text File': 'Metin Dosyası',
  'PDF File': 'PDF Dosyası',
  'Copy': 'Kopyala',
  'Share': 'Paylaş',
  'Text copied!': 'Metin kopyalandı!',
  'Copied to clipboard': 'Panoya kopyalandı',
  'File saved successfully': 'Dosya başarıyla kaydedildi',
  'Error saving file': 'Dosya kaydetme hatası',
  'Share Story': 'Hikayeyi Paylaş',
  'Export': 'Dışa Aktar',

  "Character Story": "Karakter Hikayesi",
  "Create detailed character backstories":
      "Karakterler için ayrıntılı arka plan hikayeleri oluşturun",
  "Create Character": "Karakter Oluştur",
  "Rewrite Story": "Hikayeyi Yeniden Yaz",
  "Paste Your Story": "Hikayenizi Yapıştırın",
  "Paste your story here to rewrite...":
      "Yeniden yazmak için hikayenizi buraya yapıştırın...",
  "Transform and improve your existing stories":
      "Mevcut hikayelerinizi dönüştürün ve geliştirin",
  "Title Generator": "Başlık Oluşturucu",
  "Generate catchy titles for your stories":
      "Hikayeleriniz için çekici başlıklar oluşturun",
  "Generate Titles": "Başlık Oluştur",
  "Blog Writer": "Blog Yazarı",
  "Blog Topic": "Blog Konusu",
  "Target Keywords": "Hedef Anahtar Kelimeler",
  "Target Audience (Optional)": "Hedef Kitle (İsteğe Bağlı)",
  "Enter your blog topic or title...":
      "Blog konunuzu veya başlığınızı girin...",
  "e.g., AI writing, content marketing, SEO tips":
      "örn. AI yazarlığı, içerik pazarlaması, SEO ipuçları",
  "e.g., small business owners, bloggers":
      "örn. küçük işletme sahipleri, blog yazarları",
  "Article Type": "Makale Türü",
  "Writing Tone": "Yazma Tonu",
  "Article Length": "Makale Uzunluğu",
  "SEO Options": "SEO Seçenekleri",
  "Include Meta Description": "Meta Açıklama Ekle",
  "Include Keyword Suggestions": "Anahtar Kelime Önerileri Ekle",
  "Include FAQs Section": "SSS Bölümü Ekle",
  "Please enter a blog topic": "Lütfen bir blog konusu girin",
  "Generate Blog": "Blog Oluştur",
  "SEO optimized articles with keywords":
      "Anahtar kelimelerle SEO optimize edilmiş makaleler",
  "Write Blog": "Blog Yaz",
  "YouTube Script": "YouTube Senaryosu",
  "Video Topic": "Video Konusu",
  "Key Points (Optional)": "Önemli Noktalar (İsteğe Bağlı)",
  "What is your video about?": "Videonuz ne hakkında?",
  "List key points to cover (optional)...":
      "Ele alınacak önemli noktaları listeleyin (isteğe bağlı)...",
  "Video Duration": "Video Süresi",
  "Script Options": "Senaryo Seçenekleri",
  "Include Hook/Intro": "Giriş/Kanca Ekle",
  "Include Call-to-Action": "Harekete Geçirici Mesaj Ekle",
  "Include Timestamps": "Zaman Damgaları Ekle",
  "Please enter a video topic": "Lütfen bir video konusu girin",
  "Generate Script": "Senaryo Oluştur",
  "Create scripts for videos & reels":
      "Videolar ve reels için senaryolar oluşturun",
  "Create Script": "Senaryo Oluştur",
  "Character Details": "Karakter Detayları",
  "Character Name": "Karakter Adı",
  "Age (e.g., 25, Young Adult, Ancient)": "Yaş (örn. 25, Genç Yetişkin, Antik)",
  "Personality (e.g., brave, shy, cunning)":
      "Kişilik (örn. cesur, utangaç, kurnaz)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Rol (örn. Kahraman, Kötü Adam, Mentor)",
  "Additional Details (optional)": "Ek Detaylar (isteğe bağlı)",
  "Output Style": "Çıktı Stili",
  "Generate Character": "Karakter Oluştur",
  "Please enter character name": "Lütfen karakter adını girin",
  "Please enter character role": "Lütfen karakter rolünü girin",
  "Detailed": "Ayrıntılı",
  "Brief": "Kısa",
  "Elaborate": "Kapsamlı",
  "Select Tone": "Ton Seç",
  "Rewrite Style": "Yeniden Yazma Stili",
  "Output Length": "Çıktı Uzunluğu",
  "Please paste your story": "Lütfen hikayenizi yapıştırın",
  "Story is too short. Please provide more content.":
      "Hikaye çok kısa. Lütfen daha fazla içerik ekleyin.",
  "Same": "Aynı",
  "More Dramatic": "Daha Dramatik",
  "More Humorous": "Daha Esprili",
  "More Emotional": "Daha Duygusal",
  "More Suspenseful": "Daha Gerilimli",
  "Lighter": "Daha Hafif",
  "Improved": "Geliştirilmiş",
  "Simplified": "Basitleştirilmiş",
  "More Descriptive": "Daha Açıklayıcı",
  "More Dialogue": "Daha Fazla Diyalog",
  "More Action": "Daha Fazla Aksiyon",
  "Literary": "Edebi",
  "Shorter": "Daha Kısa",
  "Longer": "Daha Uzun",
  "Much Longer": "Çok Daha Uzun",
  "Rewrite Now": "Şimdi Yeniden Yaz",
  "Story/Book Topic": "Hikaye/Kitap Konusu",
  "Keywords (Optional)": "Anahtar Kelimeler (İsteğe Bağlı)",
  "Describe your story topic or theme...":
      "Hikayenizin konusunu veya temasını açıklayın...",
  "e.g., magic, dragon, adventure": "örn. sihir, ejderha, macera",
  "Title For": "Başlık",
  "Title Style": "Başlık Stili",
  "Number of Titles": "Başlık Sayısı",
  "Book": "Kitap",
  "Short Story": "Kısa Hikaye",
  "Novel": "Roman",
  "Chapter": "Bölüm",
  "Series": "Seri",
  "Simple": "Sade",
  "Mysterious": "Gizemli",
  "Dramatic": "Dramatik",
  "Catchy": "Akılda Kalıcı",
  "Poetic": "Şiirsel",
  "Kids": "Çocuklar",
  "SEO Article": "SEO Makalesi",
  "How-To Guide": "Nasıl Yapılır Kılavuzu",
  "Listicle": "Liste Makalesi",
  "Product Review": "Ürün İncelemesi",
  "Opinion Piece": "Görüş Yazısı",
  "News Article": "Haber Makalesi",
  "Professional": "Profesyonel",
  "Casual": "Günlük",
  "Informative": "Bilgilendirici",
  "Persuasive": "İkna Edici",
  "Friendly": "Arkadaşça",
  "Authoritative": "Otoriter",
  "Short (500-800)": "Kısa (500-800)",
  "Medium (800-1500)": "Orta (800-1500)",
  "Long (1500-2500)": "Uzun (1500-2500)",
  "Detailed (2500+)": "Ayrıntılı (2500+)",
  "Storytime": "Hikaye Zamanı",
  "Documentary": "Belgesel",
  "Short Reel": "Kısa Reel",
  "Educational": "Eğitici",
  "Review": "İnceleme",
  "Tutorial": "Öğretici",
  "< 1 min (Shorts)": "< 1 dk (Kısa)",
  "1-3 min": "1-3 dk",
  "5-10 min": "5-10 dk",
  "10-20 min": "10-20 dk",
  "20+ min": "20+ dk",
  "Engaging": "İlgi Çekici",
  "Energetic": "Enerjik",
  "Calm": "Sakin",
  "Funny": "Komik",
  "Next": "Sonraki",
  "Get Started": "Başla",
  "Your tool for quick, high-quality essay writing":
      "Hızlı ve yüksek kaliteli makale yazımı için aracınız",
};
