import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> uk = {
  AppKeys.lblChooseLanguage: "Виберіть мову",
  "All": "Все",
  "AI Story Generator": "AI генератор історій",
  "Story Generator": "Генератор історій",
  "Essay Writer": "Письменник есе",
  "Essay length": "Довжина есе",
  "Script Generator": "Генератор сценаріїв",
  "Create original stories in seconds":
      "Створюйте оригінальні історії за лічені секунди",
  "Academic writing made simple": "Академічне письмо спрощене",
  "Generate powerful scripts for any medium":
      "Генеруйте потужні сценарії для будь-якого медіа",
  "Start Writing": "Почати писати",
  "Create Now": "Створити зараз",
  "Start Generating": "Почати генерувати",
  "Your Stories": "Ваші історії",
  "No stories yet": "Історій ще немає",
  "Start creating your first story!": "Почніть створювати свою першу історію!",
  "Your Story Space Awaits": "Ваш простір для історій чекає",
  "Start your first story and see it appear here":
      "Почніть свою першу історію і побачте її тут",
  "Language": "Мова",
  "Rate us": "Оцініть нас",
  "Share us": "Поділіться нами",
  "Privacy Policy": "Політика конфіденційності",
  "Settings": "Налаштування",
  "Select Language": "Виберіть мову",
  "Dashboard": "Панель керування",
  "BENEFITS": "ПЕРЕВАГИ",
  "Subscribe": "Підписатися",
  "Weekly": "Щотижня",
  "Monthly": "Щомісяця",
  "Yearly": "Щороку",
  "week": "тиждень",
  "months": "місяці",
  "year": "рік",
  "Terms & Condition": "Умови та правила",
  "No Commitment. Cancel anytime": "Без зобов'язань. Скасуйте будь-коли",
  "No Payment Now": "Без оплати зараз",
  "3 days free": "3 дні безкоштовно",
  "Start your free trial": "Почніть безкоштовну пробну версію",
  "More detailed answers": "Більш детальні відповіді",
  "Instant responds": "Миттєві відповіді",
  "Text recognition": "Розпізнавання тексту",
  "Powered by AI": "Працює на AI",
  "Storytelleing": "Розповідь",
  ' Power': "Сила",
  "Unlock your \nFill ": "Розблокуйте своє \nзаповнення",
  "Your History": "Ваша історія",
  "Terms and Conditions": "Умови та правила",
  "Short": "Короткий",
  "Medium": "Середній",
  "Long": "Довгий",
  "Length": "Довжина",
  "Describe your topic...": "Опишіть вашу тему...",
  "Set Creativity": "Встановити креативність",
  "Standard": "Стандартний",
  "Creative": "Креативний",
  "Complex": "Складний",
  "Select Genre": "Виберіть жанр",
  "Fantasy": "Фентезі",
  "Mystery": "Містерія",
  "Thriller": "Трилер",
  "Script Tone": "Тон сценарію",
  "Script Type": "Тип сценарію",
  "Comedy": "Комедія",
  "Drama": "Драма",
  "Horror": "Жахи",
  "Action": "Екшн",
  "Romance": "Романтика",
  "Go Premium": "Отримати Premium",
  "Unlock Everything": "Розблокувати все",
  "Unlimited Story Generation": "Необмежена генерація історій",
  "Write Longer & Detailed Essays": "Пишіть довші та детальніші есе",
  "Advanced Script Writer": "Розширений письменник сценаріїв",
  "Unlock All Styles & Tones": "Розблокувати всі стилі та тони",
  "No Word/Length Limit": "Без обмежень слів/довжини",
  "Remove All Ads": "Видалити всю рекламу",
  "Restore": "Відновити",
  "YouTube Video": "YouTube відео",
  "Podcast": "Подкаст",
  "Reel": "Рілс",
  "Motivational": "Мотиваційний",
  "Advertisement": "Реклама",
  "Fairy Tale": "Казка",
  "Sci-Fi": "Наукова фантастика",
  "Select Style": "Виберіть стиль",
  "Imaginative": "Уявний",
  "Innovative": "Інноваційний",
  "AI Story Writer": "AI письменник історій",
  "Generate": "Генерувати",
  "Please wait...": "Будь ласка, зачекайте...",
  "Result": "Результат",
  "Regenerate": "Регенерувати",
  "Download": "Завантажити",
  "Text copied to clipboard!": "Текст скопійовано в буфер обміну!",
  "Please enter a topic": "Будь ласка, введіть тему",
  "Story Magic": "Магія історій",
  "Let AI bring your thoughts to a full story":
      "Дозвольте AI перетворити ваші думки на повну історію",
  "Smart Scripts": "Розумні сценарії",
  "From concept to script—fast, easy, and creative":
      "Від концепції до сценарію—швидко, легко та креативно",
  "Perfect Essays": "Ідеальні есе",
  "You have reached your free limit": "Ви досягли безкоштовного ліміту",
  "Donwload": "Завантажити",
  "Press again to exit app": "Натисніть ще раз, щоб вийти з програми",
  "Saved to files": "TXT файл успішно збережено!",
  "Error: Please try again": "Помилка: Спробуйте ще раз",
  "Subscription expired": "Підписка закінчилася",
  "Purchase cancelled": "Покупку скасовано",
  "Purchase failed": "Покупка не вдалася",
  "Restore failed": "Відновлення не вдалося",
  "Purchase Successful!": "Покупка успішна!",
  "Short (200-500 words)": "Короткий (200-500 слів)",
  "Medium (500-1000 words)": "Середній (500-1000 слів)",
  "Large (1000+ words)": "Довгий (1000+ слів)",
  "Academic Level": "Академічний рівень",
  "Type of Paper": "Тип роботи",
  "High School": "Середня школа",
  "College": "Коледж",
  "Short Film": "Короткометражний фільм",
  "University": "Університет",
  "Masters": "Магістратура",
  "Custom": "Власний",
  "Tiktok Video": "Tiktok відео",
  "Movie": "Фільм",
  "Expository": "Пояснювальний",
  "Argumentative": "Аргументативний",
  "Narrative": "Оповідний",
  "Descriptive": "Описовий",
  "We're sorry to hear that 😔": "Нам шкода це чути 😔",
  "We'll try to improve 🙁": "Ми спробуємо покращитися 🙁",
  "Thanks for your feedback 🙂": "Дякуємо за відгук 🙂",
  "Great! We're glad you like it 😊": "Чудово! Раді, що вам подобається 😊",
  "Awesome! Thank you so much! 🎉": "Чудово! Дуже дякуємо! 🎉",
  "Maybe Later": "Можливо пізніше",
  "Tap a star to rate your experience":
      "Натисніть на зірку, щоб оцінити свій досвід",
  "Enjoying AI Math Solver?": "Подобається AI Math Solver?",
  "Thank you for rating us": "Дякуємо за оцінку",
  "Submit Rating": "Надіслати оцінку",
  "Hindi": "Гінді",
  "Enjoying AI Story Generator?": "Подобається AI Story Generator?",
  "Adventure": "Пригода",
  "Inspired": "Натхненний",
  "Film Script": "Кіносценарій",
  "Stage Play": "Театральна п'єса",
  "Scene Breakdown": "Аналіз сцени",
  "Dialogue Only": "Тільки діалог",
  "Ad loading please wait..": "Реклама завантажується, зачекайте...",
  "Words:": "Слова:",
  "Reading:": "Читання:",

  AppKeys.arabic: "Арабська",
  AppKeys.chinese: "Китайська",
  AppKeys.english: "Англійська",
  AppKeys.french: "Французька",
  AppKeys.german: "Німецька",
  AppKeys.hindi: "Гінді",
  AppKeys.indonesian: "Індонезійська",
  AppKeys.japanese: "Японська",
  AppKeys.korean: "Корейська",
  AppKeys.portuguese: "Португальська",
  AppKeys.russian: "Російська",
  AppKeys.spanish: "Іспанська",
  AppKeys.turkish: "Турецька",

  'Download As': 'Завантажити як',
  'Choose format to download': 'Виберіть формат для завантаження',
  'Text File': 'Текстовий файл',
  'PDF File': 'PDF файл',
  'Copy': 'Копіювати',
  'Share': 'Поділитися',
  'Text copied!': 'Текст скопійовано!',
  'Copied to clipboard': 'Скопійовано в буфер обміну',
  'File saved successfully': 'Файл успішно збережено',
  'Error saving file': 'Помилка збереження файлу',
  'Share Story': 'Поділитися історією',
  'Export': 'Експорт',

  "Character Story": "Історія персонажа",
  "Create detailed character backstories":
      "Створюйте детальні передісторії персонажів",
  "Create Character": "Створити персонажа",
  "Rewrite Story": "Переписати історію",
  "Paste Your Story": "Вставте вашу історію",
  "Paste your story here to rewrite...":
      "Вставте вашу історію сюди для переписування...",
  "Transform and improve your existing stories":
      "Трансформуйте та покращуйте свої наявні історії",
  "Title Generator": "Генератор заголовків",
  "Generate catchy titles for your stories":
      "Генеруйте яскраві заголовки для своїх історій",
  "Generate Titles": "Генерувати заголовки",
  "Blog Writer": "Автор блогу",
  "Blog Topic": "Тема блогу",
  "Target Keywords": "Цільові ключові слова",
  "Target Audience (Optional)": "Цільова аудиторія (Необов'язково)",
  "Enter your blog topic or title...": "Введіть тему або назву вашого блогу...",
  "e.g., AI writing, content marketing, SEO tips":
      "напр., написання з ШІ, контент-маркетинг, поради щодо SEO",
  "e.g., small business owners, bloggers":
      "напр., власники малого бізнесу, блогери",
  "Article Type": "Тип статті",
  "Writing Tone": "Тон написання",
  "Article Length": "Довжина статті",
  "SEO Options": "Параметри SEO",
  "Include Meta Description": "Включити мета-опис",
  "Include Keyword Suggestions": "Включити пропозиції ключових слів",
  "Include FAQs Section": "Включити розділ FAQ",
  "Please enter a blog topic": "Будь ласка, введіть тему блогу",
  "Generate Blog": "Створити блог",
  "SEO optimized articles with keywords":
      "SEO-оптимізовані статті з ключовими словами",
  "Write Blog": "Написати блог",
  "YouTube Script": "Сценарій YouTube",
  "Video Topic": "Тема відео",
  "Key Points (Optional)": "Ключові моменти (Необов'язково)",
  "What is your video about?": "Про що ваше відео?",
  "List key points to cover (optional)...":
      "Перелічіть ключові моменти (необов'язково)...",
  "Video Duration": "Тривалість відео",
  "Script Options": "Параметри сценарію",
  "Include Hook/Intro": "Включити зачіпку/вступ",
  "Include Call-to-Action": "Включити заклик до дії",
  "Include Timestamps": "Включити часові мітки",
  "Please enter a video topic": "Будь ласка, введіть тему відео",
  "Generate Script": "Створити сценарій",
  "Create scripts for videos & reels": "Створюйте сценарії для відео та рілсів",
  "Create Script": "Створити сценарій",
  "Character Details": "Деталі персонажа",
  "Character Name": "Ім'я персонажа",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Вік (напр., 25, Молодий дорослий, Давній)",
  "Personality (e.g., brave, shy, cunning)":
      "Особистість (напр., хоробрий, сором'язливий, хитрий)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Роль (напр., Герой, Лиходій, Наставник)",
  "Additional Details (optional)": "Додаткові відомості (необов'язково)",
  "Output Style": "Стиль виводу",
  "Generate Character": "Створити персонажа",
  "Please enter character name": "Будь ласка, введіть ім'я персонажа",
  "Please enter character role": "Будь ласка, введіть роль персонажа",
  "Detailed": "Детальний",
  "Brief": "Короткий",
  "Elaborate": "Розгорнутий",
  "Select Tone": "Вибрати тон",
  "Rewrite Style": "Стиль переписування",
  "Output Length": "Довжина виводу",
  "Please paste your story": "Будь ласка, вставте вашу історію",
  "Story is too short. Please provide more content.":
      "Історія занадто коротка. Будь ласка, додайте більше змісту.",
  "Same": "Такий самий",
  "More Dramatic": "Більш драматичний",
  "More Humorous": "Більш гумористичний",
  "More Emotional": "Більш емоційний",
  "More Suspenseful": "Більш напружений",
  "Lighter": "Легший",
  "Improved": "Покращений",
  "Simplified": "Спрощений",
  "More Descriptive": "Більш описовий",
  "More Dialogue": "Більше діалогів",
  "More Action": "Більше дій",
  "Literary": "Літературний",
  "Shorter": "Коротший",
  "Longer": "Довший",
  "Much Longer": "Набагато довший",
  "Rewrite Now": "Переписати зараз",
  "Story/Book Topic": "Тема історії/книги",
  "Keywords (Optional)": "Ключові слова (Необов'язково)",
  "Describe your story topic or theme...":
      "Опишіть тему або сюжет вашої історії...",
  "e.g., magic, dragon, adventure": "напр., магія, дракон, пригода",
  "Title For": "Заголовок для",
  "Title Style": "Стиль заголовка",
  "Number of Titles": "Кількість заголовків",
  "Book": "Книга",
  "Short Story": "Оповідання",
  "Novel": "Роман",
  "Chapter": "Розділ",
  "Series": "Серія",
  "Simple": "Простий",
  "Mysterious": "Таємничий",
  "Dramatic": "Драматичний",
  "Catchy": "Яскравий",
  "Poetic": "Поетичний",
  "Kids": "Для дітей",
  "SEO Article": "SEO-стаття",
  "How-To Guide": "Посібник",
  "Listicle": "Стаття-список",
  "Product Review": "Огляд продукту",
  "Opinion Piece": "Стаття з думками",
  "News Article": "Новинна стаття",
  "Professional": "Професійний",
  "Casual": "Неформальний",
  "Informative": "Інформативний",
  "Persuasive": "Переконливий",
  "Friendly": "Дружній",
  "Authoritative": "Авторитетний",
  "Short (500-800)": "Короткий (500-800)",
  "Medium (800-1500)": "Середній (800-1500)",
  "Long (1500-2500)": "Довгий (1500-2500)",
  "Detailed (2500+)": "Детальний (2500+)",
  "Storytime": "Час для історій",
  "Documentary": "Документальний",
  "Short Reel": "Короткий рілс",
  "Educational": "Освітній",
  "Review": "Огляд",
  "Tutorial": "Підручник",
  "< 1 min (Shorts)": "< 1 хв (Shorts)",
  "1-3 min": "1-3 хв",
  "5-10 min": "5-10 хв",
  "10-20 min": "10-20 хв",
  "20+ min": "20+ хв",
  "Engaging": "Захопливий",
  "Energetic": "Енергійний",
  "Calm": "Спокійний",
  "Funny": "Смішний",
  "Next": "Далі",
  "Get Started": "Почати",
  "Your tool for quick, high-quality essay writing":
      "Ваш інструмент для швидкого та якісного написання есе",
};
