import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> ur = {
  AppKeys.lblChooseLanguage: "زبان منتخب کریں",
  "All": "سب",
  "AI Story Generator": "AI کہانی جنریٹر",
  "Story Generator": "کہانی جنریٹر",
  "Essay Writer": "مضمون لکھنے والا",
  "Essay length": "مضمون کی لمبائی",
  "Script Generator": "اسکرپٹ جنریٹر",
  "Create original stories in seconds": "چند سیکنڈوں میں اصل کہانیاں بنائیں",
  "Academic writing made simple": "تعلیمی تحریر آسان بنائی گئی",
  "Generate powerful scripts for any medium":
      "کسی بھی میڈیم کے لیے طاقتور اسکرپٹس بنائیں",
  "Start Writing": "لکھنا شروع کریں",
  "Create Now": "ابھی بنائیں",
  "Start Generating": "بنانا شروع کریں",
  "Your Stories": "آپ کی کہانیاں",
  "No stories yet": "ابھی تک کوئی کہانیاں نہیں",
  "Start creating your first story!": "اپنی پہلی کہانی بنانا شروع کریں!",
  "Your Story Space Awaits": "آپ کی کہانی کی جگہ منتظر ہے",
  "Start your first story and see it appear here":
      "اپنی پہلی کہانی شروع کریں اور اسے یہاں دیکھیں",
  "Language": "زبان",
  "Rate us": "ہمیں ریٹ کریں",
  "Share us": "ہمیں شیئر کریں",
  "Privacy Policy": "رازداری کی پالیسی",
  "Settings": "ترتیبات",
  "Select Language": "زبان منتخب کریں",
  "Dashboard": "ڈیش بورڈ",
  "BENEFITS": "فوائد",
  "Subscribe": "سبسکرائب کریں",
  "Weekly": "ہفتہ وار",
  "Monthly": "ماہانہ",
  "Yearly": "سالانہ",
  "week": "ہفتہ",
  "months": "مہینے",
  "year": "سال",
  "Terms & Condition": "شرائط و ضوابط",
  "No Commitment. Cancel anytime": "کوئی پابندی نہیں۔ کسی بھی وقت منسوخ کریں",
  "No Payment Now": "ابھی کوئی ادائیگی نہیں",
  "3 days free": "3 دن مفت",
  "Start your free trial": "اپنا مفت ٹرائل شروع کریں",
  "More detailed answers": "مزید تفصیلی جوابات",
  "Instant responds": "فوری جوابات",
  "Text recognition": "متن کی شناخت",
  "Powered by AI": "AI سے چلتا ہے",
  "Storytelleing": "کہانی سنانا",
  ' Power': "طاقت",
  "Unlock your \nFill ": "اپنا \nبھریں کھولیں",
  "Your History": "آپ کی تاریخ",
  "Terms and Conditions": "شرائط و ضوابط",
  "Short": "چھوٹا",
  "Medium": "درمیانہ",
  "Long": "لمبا",
  "Length": "لمبائی",
  "Describe your topic...": "اپنے موضوع کی وضاحت کریں...",
  "Set Creativity": "تخلیقیت سیٹ کریں",
  "Standard": "معیاری",
  "Creative": "تخلیقی",
  "Complex": "پیچیدہ",
  "Select Genre": "صنف منتخب کریں",
  "Fantasy": "تصوراتی",
  "Mystery": "پراسرار",
  "Thriller": "سنسنی خیز",
  "Script Tone": "اسکرپٹ کا لہجہ",
  "Script Type": "اسکرپٹ کی قسم",
  "Comedy": "مزاحیہ",
  "Drama": "ڈرامہ",
  "Horror": "خوفناک",
  "Action": "ایکشن",
  "Romance": "رومانوی",
  "Go Premium": "پریمیم حاصل کریں",
  "Unlock Everything": "سب کچھ کھولیں",
  "Unlimited Story Generation": "لامحدود کہانی بنانا",
  "Write Longer & Detailed Essays": "لمبے اور تفصیلی مضامین لکھیں",
  "Advanced Script Writer": "ایڈوانسڈ اسکرپٹ لکھنے والا",
  "Unlock All Styles & Tones": "تمام اسٹائلز اور لہجے کھولیں",
  "No Word/Length Limit": "الفاظ/لمبائی کی کوئی حد نہیں",
  "Remove All Ads": "تمام اشتہارات ہٹائیں",
  "Restore": "بحال کریں",
  "YouTube Video": "یوٹیوب ویڈیو",
  "Podcast": "پوڈکاسٹ",
  "Reel": "ریل",
  "Motivational": "حوصلہ افزا",
  "Advertisement": "اشتہار",
  "Fairy Tale": "پریوں کی کہانی",
  "Sci-Fi": "سائنس فکشن",
  "Select Style": "اسٹائل منتخب کریں",
  "Imaginative": "تصوراتی",
  "Innovative": "جدید",
  "AI Story Writer": "AI کہانی لکھنے والا",
  "Generate": "بنائیں",
  "Please wait...": "براہ کرم انتظار کریں...",
  "Result": "نتیجہ",
  "Regenerate": "دوبارہ بنائیں",
  "Download": "ڈاؤن لوڈ",
  "Text copied to clipboard!": "متن کلپ بورڈ پر کاپی ہو گیا!",
  "Please enter a topic": "براہ کرم موضوع درج کریں",
  "Story Magic": "کہانی کا جادو",
  "Let AI bring your thoughts to a full story":
      "AI کو اپنے خیالات کو مکمل کہانی میں بدلنے دیں",
  "Smart Scripts": "سمارٹ اسکرپٹس",
  "From concept to script—fast, easy, and creative":
      "تصور سے اسکرپٹ تک—تیز، آسان، اور تخلیقی",
  "Perfect Essays": "کامل مضامین",
  "You have reached your free limit": "آپ نے اپنی مفت حد تک پہنچ گئے ہیں",
  "Donwload": "ڈاؤن لوڈ",
  "Press again to exit app": "ایپ سے باہر نکلنے کے لیے دوبارہ دبائیں",
  "Saved to files": "TXT فائل کامیابی سے محفوظ ہوگئی!",
  "Error: Please try again": "خرابی: براہ کرم دوبارہ کوشش کریں",
  "Subscription expired": "سبسکرپشن ختم ہو گئی",
  "Purchase cancelled": "خریداری منسوخ",
  "Purchase failed": "خریداری ناکام",
  "Restore failed": "بحالی ناکام",
  "Purchase Successful!": "خریداری کامیاب!",
  "Short (200-500 words)": "چھوٹا (200-500 الفاظ)",
  "Medium (500-1000 words)": "درمیانہ (500-1000 الفاظ)",
  "Large (1000+ words)": "بڑا (1000+ الفاظ)",
  "Academic Level": "تعلیمی سطح",
  "Type of Paper": "کاغذ کی قسم",
  "High School": "ہائی سکول",
  "College": "کالج",
  "Short Film": "مختصر فلم",
  "University": "یونیورسٹی",
  "Masters": "ماسٹرز",
  "Custom": "کسٹم",
  "Tiktok Video": "ٹک ٹاک ویڈیو",
  "Movie": "فلم",
  "Expository": "وضاحتی",
  "Argumentative": "دلائلی",
  "Narrative": "بیانیہ",
  "Descriptive": "وضاحتی",
  "We're sorry to hear that 😔": "ہمیں یہ سن کر افسوس ہوا 😔",
  "We'll try to improve 🙁": "ہم بہتر بنانے کی کوشش کریں گے 🙁",
  "Thanks for your feedback 🙂": "آپ کی رائے کا شکریہ 🙂",
  "Great! We're glad you like it 😊":
      "بہت اچھا! ہمیں خوشی ہے کہ آپ کو پسند آیا 😊",
  "Awesome! Thank you so much! 🎉": "شاندار! بہت شکریہ! 🎉",
  "Maybe Later": "شاید بعد میں",
  "Tap a star to rate your experience":
      "اپنے تجربے کی درجہ بندی کرنے کے لیے ستارے پر ٹیپ کریں",
  "Enjoying AI Math Solver?": "کیا AI Math Solver پسند آ رہا ہے?",
  "Thank you for rating us": "ہمیں ریٹ کرنے کا شکریہ",
  "Submit Rating": "ریٹنگ جمع کریں",
  "Hindi": "ہندی",
  "Enjoying AI Story Generator?": "کیا AI Story Generator پسند آ رہا ہے?",
  "Adventure": "ایڈونچر",
  "Inspired": "متاثر",
  "Film Script": "فلمی اسکرپٹ",
  "Stage Play": "اسٹیج ڈرامہ",
  "Scene Breakdown": "منظر کا تجزیہ",
  "Dialogue Only": "صرف مکالمہ",
  "Ad loading please wait..": "اشتہار لوڈ ہو رہا ہے، براہ کرم انتظار کریں...",
  "Words:": "الفاظ:",
  "Reading:": "پڑھنا:",

  AppKeys.arabic: "عربی",
  AppKeys.chinese: "چینی",
  AppKeys.english: "انگریزی",
  AppKeys.french: "فرانسیسی",
  AppKeys.german: "جرمن",
  AppKeys.hindi: "ہندی",
  AppKeys.indonesian: "انڈونیشیائی",
  AppKeys.japanese: "جاپانی",
  AppKeys.korean: "کورین",
  AppKeys.portuguese: "پرتگالی",
  AppKeys.russian: "روسی",
  AppKeys.spanish: "ہسپانوی",
  AppKeys.turkish: "ترکی",

  'Download As': 'اس طرح ڈاؤن لوڈ کریں',
  'Choose format to download': 'ڈاؤن لوڈ کے لیے فارمیٹ منتخب کریں',
  'Text File': 'ٹیکسٹ فائل',
  'PDF File': 'PDF فائل',
  'Copy': 'کاپی کریں',
  'Share': 'شیئر کریں',
  'Text copied!': 'متن کاپی ہو گیا!',
  'Copied to clipboard': 'کلپ بورڈ پر کاپی ہو گیا',
  'File saved successfully': 'فائل کامیابی سے محفوظ ہو گئی',
  'Error saving file': 'فائل محفوظ کرنے میں خرابی',
  'Share Story': 'کہانی شیئر کریں',
  'Export': 'ایکسپورٹ',
  "Character Story": "کردار کی کہانی",
  "Create detailed character backstories":
      "کردار کی تفصیلی پس منظر کی کہانیاں بنائیں",
  "Create Character": "کردار بنائیں",
  "Rewrite Story": "کہانی دوبارہ لکھیں",
  "Paste Your Story": "اپنی کہانی پیسٹ کریں",
  "Paste your story here to rewrite...":
      "دوبارہ لکھنے کے لیے اپنی کہانی یہاں پیسٹ کریں...",
  "Transform and improve your existing stories":
      "اپنی موجودہ کہانیوں کو تبدیل اور بہتر بنائیں",
  "Title Generator": "عنوان جنریٹر",
  "Generate catchy titles for your stories":
      "اپنی کہانیوں کے لیے دلکش عنوانات بنائیں",
  "Generate Titles": "عنوانات بنائیں",
  "Blog Writer": "بلاگ لکھاری",
  "Blog Topic": "بلاگ موضوع",
  "Target Keywords": "ہدف کلیدی الفاظ",
  "Target Audience (Optional)": "ہدف سامعین (اختیاری)",
  "Enter your blog topic or title...":
      "اپنے بلاگ کا موضوع یا عنوان درج کریں...",
  "e.g., AI writing, content marketing, SEO tips":
      "مثلاً، AI تحریر، مواد مارکیٹنگ، SEO تجاویز",
  "e.g., small business owners, bloggers":
      "مثلاً، چھوٹے کاروبار کے مالکان، بلاگرز",
  "Article Type": "مضمون کی قسم",
  "Writing Tone": "تحریر کا لہجہ",
  "Article Length": "مضمون کی لمبائی",
  "SEO Options": "SEO اختیارات",
  "Include Meta Description": "میٹا تفصیل شامل کریں",
  "Include Keyword Suggestions": "کلیدی الفاظ کی تجاویز شامل کریں",
  "Include FAQs Section": "اکثر پوچھے گئے سوالات کا حصہ شامل کریں",
  "Please enter a blog topic": "براہ کرم بلاگ موضوع درج کریں",
  "Generate Blog": "بلاگ بنائیں",
  "SEO optimized articles with keywords":
      "کلیدی الفاظ کے ساتھ SEO بہتر بنائے گئے مضامین",
  "Write Blog": "بلاگ لکھیں",
  "YouTube Script": "YouTube اسکرپٹ",
  "Video Topic": "ویڈیو موضوع",
  "Key Points (Optional)": "اہم نکات (اختیاری)",
  "What is your video about?": "آپ کی ویڈیو کس بارے میں ہے؟",
  "List key points to cover (optional)...":
      "شامل کرنے کے لیے اہم نکات درج کریں (اختیاری)...",
  "Video Duration": "ویڈیو کا دورانیہ",
  "Script Options": "اسکرپٹ اختیارات",
  "Include Hook/Intro": "ہک/تعارف شامل کریں",
  "Include Call-to-Action": "عمل کی دعوت شامل کریں",
  "Include Timestamps": "وقت کے نشانات شامل کریں",
  "Please enter a video topic": "براہ کرم ویڈیو موضوع درج کریں",
  "Generate Script": "اسکرپٹ بنائیں",
  "Create scripts for videos & reels": "ویڈیوز اور ریلز کے لیے اسکرپٹ بنائیں",
  "Create Script": "اسکرپٹ بنائیں",
  "Character Details": "کردار کی تفصیلات",
  "Character Name": "کردار کا نام",
  "Age (e.g., 25, Young Adult, Ancient)": "عمر (مثلاً، 25، نوجوان، قدیم)",
  "Personality (e.g., brave, shy, cunning)":
      "شخصیت (مثلاً، بہادر، شرمیلا، چالاک)",
  "Role (e.g., Hero, Villain, Mentor)": "کردار (مثلاً، ہیرو، ولن، رہنما)",
  "Additional Details (optional)": "اضافی تفصیلات (اختیاری)",
  "Output Style": "آؤٹ پٹ اسٹائل",
  "Generate Character": "کردار بنائیں",
  "Please enter character name": "براہ کرم کردار کا نام درج کریں",
  "Please enter character role": "براہ کرم کردار کا رول درج کریں",
  "Detailed": "تفصیلی",
  "Brief": "مختصر",
  "Elaborate": "وسیع",
  "Select Tone": "لہجہ منتخب کریں",
  "Rewrite Style": "دوبارہ لکھنے کا انداز",
  "Output Length": "آؤٹ پٹ کی لمبائی",
  "Please paste your story": "براہ کرم اپنی کہانی پیسٹ کریں",
  "Story is too short. Please provide more content.":
      "کہانی بہت مختصر ہے۔ براہ کرم مزید مواد فراہم کریں۔",
  "Same": "ایک جیسا",
  "More Dramatic": "زیادہ ڈرامائی",
  "More Humorous": "زیادہ مزاحیہ",
  "More Emotional": "زیادہ جذباتی",
  "More Suspenseful": "زیادہ سنسنی خیز",
  "Lighter": "ہلکا",
  "Improved": "بہتر",
  "Simplified": "سادہ",
  "More Descriptive": "زیادہ وضاحتی",
  "More Dialogue": "زیادہ مکالمہ",
  "More Action": "زیادہ عمل",
  "Literary": "ادبی",
  "Shorter": "چھوٹا",
  "Longer": "لمبا",
  "Much Longer": "بہت لمبا",
  "Rewrite Now": "ابھی دوبارہ لکھیں",
  "Story/Book Topic": "کہانی/کتاب کا موضوع",
  "Keywords (Optional)": "کلیدی الفاظ (اختیاری)",
  "Describe your story topic or theme...":
      "اپنی کہانی کا موضوع یا تھیم بیان کریں...",
  "e.g., magic, dragon, adventure": "مثلاً، جادو، اژدہا، مہم جوئی",
  "Title For": "عنوان",
  "Title Style": "عنوان کا انداز",
  "Number of Titles": "عنوانات کی تعداد",
  "Book": "کتاب",
  "Short Story": "مختصر کہانی",
  "Novel": "ناول",
  "Chapter": "باب",
  "Series": "سیریز",
  "Simple": "سادہ",
  "Mysterious": "پراسرار",
  "Dramatic": "ڈرامائی",
  "Catchy": "دلکش",
  "Poetic": "شاعرانہ",
  "Kids": "بچے",
  "SEO Article": "SEO مضمون",
  "How-To Guide": "طریقہ کار گائیڈ",
  "Listicle": "فہرست مضمون",
  "Product Review": "مصنوع کا جائزہ",
  "Opinion Piece": "رائے مضمون",
  "News Article": "خبری مضمون",
  "Professional": "پیشہ ورانہ",
  "Casual": "غیر رسمی",
  "Informative": "معلوماتی",
  "Persuasive": "قائل کرنے والا",
  "Friendly": "دوستانہ",
  "Authoritative": "مستند",
  "Short (500-800)": "مختصر (500-800)",
  "Medium (800-1500)": "درمیانہ (800-1500)",
  "Long (1500-2500)": "لمبا (1500-2500)",
  "Detailed (2500+)": "تفصیلی (2500+)",
  "Storytime": "کہانی کا وقت",
  "Documentary": "دستاویزی فلم",
  "Short Reel": "مختصر ریل",
  "Educational": "تعلیمی",
  "Review": "جائزہ",
  "Tutorial": "سبق",
  "< 1 min (Shorts)": "< 1 منٹ (مختصر)",
  "1-3 min": "1-3 منٹ",
  "5-10 min": "5-10 منٹ",
  "10-20 min": "10-20 منٹ",
  "20+ min": "20+ منٹ",
  "Engaging": "دلچسپ",
  "Energetic": "پرجوش",
  "Calm": "پرسکون",
  "Funny": "مضحکہ خیز",
  "Next": "اگلا",
  "Get Started": "شروع کریں",
  "Your tool for quick, high-quality essay writing":
      "تیز اور اعلیٰ معیار کی مضمون نویسی کے لیے آپ کا آلہ",
};
