import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> vi = {
  AppKeys.lblChooseLanguage: "Chọn ngôn ngữ",
  "All": "Tất cả",
  "AI Story Generator": "Trình tạo truyện AI",
  "Story Generator": "Trình tạo truyện",
  "Essay Writer": "Người viết luận văn",
  "Essay length": "Độ dài bài luận",
  "Script Generator": "Trình tạo kịch bản",
  "Create original stories in seconds": "Tạo các câu chuyện gốc trong vài giây",
  "Academic writing made simple": "Viết học thuật đơn giản hóa",
  "Generate powerful scripts for any medium":
      "Tạo các kịch bản mạnh mẽ cho bất kỳ phương tiện nào",
  "Start Writing": "Bắt đầu viết",
  "Create Now": "Tạo ngay",
  "Start Generating": "Bắt đầu tạo",
  "Your Stories": "Truyện của bạn",
  "No stories yet": "Chưa có truyện",
  "Start creating your first story!": "Bắt đầu tạo câu chuyện đầu tiên!",
  "Your Story Space Awaits": "Không gian truyện của bạn đang chờ",
  "Start your first story and see it appear here":
      "Bắt đầu câu chuyện đầu tiên và xem nó xuất hiện ở đây",
  "Language": "Ngôn ngữ",
  "Rate us": "Đánh giá chúng tôi",
  "Share us": "Chia sẻ chúng tôi",
  "Privacy Policy": "Chính sách bảo mật",
  "Settings": "Cài đặt",
  "Select Language": "Chọn ngôn ngữ",
  "Dashboard": "Bảng điều khiển",
  "BENEFITS": "LỢI ÍCH",
  "Subscribe": "Đăng ký",
  "Weekly": "Hàng tuần",
  "Monthly": "Hàng tháng",
  "Yearly": "Hàng năm",
  "week": "tuần",
  "months": "tháng",
  "year": "năm",
  "Terms & Condition": "Điều khoản & Điều kiện",
  "No Commitment. Cancel anytime": "Không ràng buộc. Hủy bất cứ lúc nào",
  "No Payment Now": "Không thanh toán ngay",
  "3 days free": "3 ngày miễn phí",
  "Start your free trial": "Bắt đầu dùng thử miễn phí",
  "More detailed answers": "Câu trả lời chi tiết hơn",
  "Instant responds": "Phản hồi tức thì",
  "Text recognition": "Nhận dạng văn bản",
  "Powered by AI": "Được hỗ trợ bởi AI",
  "Storytelleing": "Kể chuyện",
  ' Power': "Sức mạnh",
  "Unlock your \nFill ": "Mở khóa của bạn \nĐiền vào",
  "Your History": "Lịch sử của bạn",
  "Terms and Conditions": "Điều khoản và Điều kiện",
  "Short": "Ngắn",
  "Medium": "Trung bình",
  "Long": "Dài",
  "Length": "Độ dài",
  "Describe your topic...": "Mô tả chủ đề của bạn...",
  "Set Creativity": "Đặt sáng tạo",
  "Standard": "Tiêu chuẩn",
  "Creative": "Sáng tạo",
  "Complex": "Phức tạp",
  "Select Genre": "Chọn thể loại",
  "Fantasy": "Huyền bí",
  "Mystery": "Bí ẩn",
  "Thriller": "Ly kỳ",
  "Script Tone": "Giọng điệu kịch bản",
  "Script Type": "Loại kịch bản",
  "Comedy": "Hài kịch",
  "Drama": "Kịch",
  "Horror": "Kinh dị",
  "Action": "Hành động",
  "Romance": "Lãng mạn",
  "Go Premium": "Nâng cấp Premium",
  "Unlock Everything": "Mở khóa tất cả",
  "Unlimited Story Generation": "Tạo truyện không giới hạn",
  "Write Longer & Detailed Essays": "Viết bài luận dài và chi tiết hơn",
  "Advanced Script Writer": "Người viết kịch bản nâng cao",
  "Unlock All Styles & Tones": "Mở khóa tất cả phong cách và giọng điệu",
  "No Word/Length Limit": "Không giới hạn từ/độ dài",
  "Remove All Ads": "Loại bỏ tất cả quảng cáo",
  "Restore": "Khôi phục",
  "YouTube Video": "Video YouTube",
  "Podcast": "Podcast",
  "Reel": "Reel",
  "Motivational": "Truyền cảm hứng",
  "Advertisement": "Quảng cáo",
  "Fairy Tale": "Truyện cổ tích",
  "Sci-Fi": "Khoa học viễn tưởng",
  "Select Style": "Chọn phong cách",
  "Imaginative": "Giàu trí tưởng tượng",
  "Innovative": "Đổi mới",
  "AI Story Writer": "Người viết truyện AI",
  "Generate": "Tạo",
  "Please wait...": "Vui lòng chờ...",
  "Result": "Kết quả",
  "Regenerate": "Tạo lại",
  "Download": "Tải xuống",
  "Text copied to clipboard!": "Văn bản đã sao chép vào clipboard!",
  "Please enter a topic": "Vui lòng nhập chủ đề",
  "Story Magic": "Phép thuật truyện",
  "Let AI bring your thoughts to a full story":
      "Để AI biến suy nghĩ của bạn thành câu chuyện hoàn chỉnh",
  "Smart Scripts": "Kịch bản thông minh",
  "From concept to script—fast, easy, and creative":
      "Từ ý tưởng đến kịch bản—nhanh, dễ dàng và sáng tạo",
  "Perfect Essays": "Bài luận hoàn hảo",
  "You have reached your free limit": "Bạn đã đạt đến giới hạn miễn phí",
  "Donwload": "Tải xuống",
  "Press again to exit app": "Nhấn lại để thoát ứng dụng",
  "Saved to files": "Tệp TXT đã lưu thành công!",
  "Error: Please try again": "Lỗi: Vui lòng thử lại",
  "Subscription expired": "Đăng ký đã hết hạn",
  "Purchase cancelled": "Mua hàng đã hủy",
  "Purchase failed": "Mua hàng thất bại",
  "Restore failed": "Khôi phục thất bại",
  "Purchase Successful!": "Mua hàng thành công!",
  "Short (200-500 words)": "Ngắn (200-500 từ)",
  "Medium (500-1000 words)": "Trung bình (500-1000 từ)",
  "Large (1000+ words)": "Dài (1000+ từ)",
  "Academic Level": "Cấp độ học thuật",
  "Type of Paper": "Loại bài viết",
  "High School": "Trung học",
  "College": "Cao đẳng",
  "Short Film": "Phim ngắn",
  "University": "Đại học",
  "Masters": "Thạc sĩ",
  "Custom": "Tùy chỉnh",
  "Tiktok Video": "Video Tiktok",
  "Movie": "Phim",
  "Expository": "Giải thích",
  "Argumentative": "Lập luận",
  "Narrative": "Tường thuật",
  "Descriptive": "Miêu tả",
  "We're sorry to hear that 😔": "Chúng tôi rất tiếc khi nghe điều đó 😔",
  "We'll try to improve 🙁": "Chúng tôi sẽ cố gắng cải thiện 🙁",
  "Thanks for your feedback 🙂": "Cảm ơn phản hồi của bạn 🙂",
  "Great! We're glad you like it 😊": "Tuyệt! Chúng tôi vui vì bạn thích 😊",
  "Awesome! Thank you so much! 🎉": "Tuyệt vời! Cảm ơn rất nhiều! 🎉",
  "Maybe Later": "Có lẽ sau",
  "Tap a star to rate your experience":
      "Chạm vào ngôi sao để đánh giá trải nghiệm của bạn",
  "Enjoying AI Math Solver?": "Bạn có thích AI Math Solver?",
  "Thank you for rating us": "Cảm ơn bạn đã đánh giá",
  "Submit Rating": "Gửi đánh giá",
  "Hindi": "Tiếng Hindi",
  "Enjoying AI Story Generator?": "Bạn có thích AI Story Generator?",
  "Adventure": "Phiêu lưu",
  "Inspired": "Truyền cảm hứng",
  "Film Script": "Kịch bản phim",
  "Stage Play": "Vở kịch sân khấu",
  "Scene Breakdown": "Phân tích cảnh",
  "Dialogue Only": "Chỉ hội thoại",
  "Ad loading please wait..": "Quảng cáo đang tải, vui lòng chờ...",
  "Words:": "Từ:",
  "Reading:": "Đọc:",

  AppKeys.arabic: "Tiếng Ả Rập",
  AppKeys.chinese: "Tiếng Trung",
  AppKeys.english: "Tiếng Anh",
  AppKeys.french: "Tiếng Pháp",
  AppKeys.german: "Tiếng Đức",
  AppKeys.hindi: "Tiếng Hindi",
  AppKeys.indonesian: "Tiếng Indonesia",
  AppKeys.japanese: "Tiếng Nhật",
  AppKeys.korean: "Tiếng Hàn",
  AppKeys.portuguese: "Tiếng Bồ Đào Nha",
  AppKeys.russian: "Tiếng Nga",
  AppKeys.spanish: "Tiếng Tây Ban Nha",
  AppKeys.turkish: "Tiếng Thổ Nhĩ Kỳ",

  'Download As': 'Tải xuống dưới dạng',
  'Choose format to download': 'Chọn định dạng để tải xuống',
  'Text File': 'Tệp văn bản',
  'PDF File': 'Tệp PDF',
  'Copy': 'Sao chép',
  'Share': 'Chia sẻ',
  'Text copied!': 'Văn bản đã sao chép!',
  'Copied to clipboard': 'Đã sao chép vào clipboard',
  'File saved successfully': 'Tệp đã lưu thành công',
  'Error saving file': 'Lỗi khi lưu tệp',
  'Share Story': 'Chia sẻ truyện',
  'Export': 'Xuất',
  "Character Story": "Câu chuyện nhân vật",
  "Create detailed character backstories": "Tạo tiểu sử chi tiết cho nhân vật",
  "Create Character": "Tạo nhân vật",
  "Rewrite Story": "Viết lại câu chuyện",
  "Paste Your Story": "Dán câu chuyện của bạn",
  "Paste your story here to rewrite...":
      "Dán câu chuyện của bạn vào đây để viết lại...",
  "Transform and improve your existing stories":
      "Chuyển đổi và cải thiện những câu chuyện hiện có của bạn",
  "Title Generator": "Trình tạo tiêu đề",
  "Generate catchy titles for your stories":
      "Tạo tiêu đề hấp dẫn cho câu chuyện của bạn",
  "Generate Titles": "Tạo tiêu đề",
  "Blog Writer": "Người viết blog",
  "Blog Topic": "Chủ đề blog",
  "Target Keywords": "Từ khóa mục tiêu",
  "Target Audience (Optional)": "Đối tượng mục tiêu (Tùy chọn)",
  "Enter your blog topic or title...":
      "Nhập chủ đề hoặc tiêu đề blog của bạn...",
  "e.g., AI writing, content marketing, SEO tips":
      "vd., viết AI, tiếp thị nội dung, mẹo SEO",
  "e.g., small business owners, bloggers": "vd., chủ doanh nghiệp nhỏ, blogger",
  "Article Type": "Loại bài viết",
  "Writing Tone": "Giọng văn",
  "Article Length": "Độ dài bài viết",
  "SEO Options": "Tùy chọn SEO",
  "Include Meta Description": "Bao gồm mô tả meta",
  "Include Keyword Suggestions": "Bao gồm gợi ý từ khóa",
  "Include FAQs Section": "Bao gồm phần câu hỏi thường gặp",
  "Please enter a blog topic": "Vui lòng nhập chủ đề blog",
  "Generate Blog": "Tạo blog",
  "SEO optimized articles with keywords":
      "Bài viết được tối ưu hóa SEO với từ khóa",
  "Write Blog": "Viết blog",
  "YouTube Script": "Kịch bản YouTube",
  "Video Topic": "Chủ đề video",
  "Key Points (Optional)": "Điểm chính (Tùy chọn)",
  "What is your video about?": "Video của bạn nói về điều gì?",
  "List key points to cover (optional)...":
      "Liệt kê các điểm chính cần đề cập (tùy chọn)...",
  "Video Duration": "Thời lượng video",
  "Script Options": "Tùy chọn kịch bản",
  "Include Hook/Intro": "Bao gồm phần mở đầu/giới thiệu",
  "Include Call-to-Action": "Bao gồm lời kêu gọi hành động",
  "Include Timestamps": "Bao gồm dấu thời gian",
  "Please enter a video topic": "Vui lòng nhập chủ đề video",
  "Generate Script": "Tạo kịch bản",
  "Create scripts for videos & reels": "Tạo kịch bản cho video và reels",
  "Create Script": "Tạo kịch bản",
  "Character Details": "Chi tiết nhân vật",
  "Character Name": "Tên nhân vật",
  "Age (e.g., 25, Young Adult, Ancient)": "Tuổi (vd., 25, Thanh niên, Cổ đại)",
  "Personality (e.g., brave, shy, cunning)":
      "Tính cách (vd., dũng cảm, nhút nhát, ranh mãnh)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Vai trò (vd., Anh hùng, Phản diện, Người dẫn dắt)",
  "Additional Details (optional)": "Chi tiết thêm (tùy chọn)",
  "Output Style": "Phong cách đầu ra",
  "Generate Character": "Tạo nhân vật",
  "Please enter character name": "Vui lòng nhập tên nhân vật",
  "Please enter character role": "Vui lòng nhập vai trò nhân vật",
  "Detailed": "Chi tiết",
  "Brief": "Ngắn gọn",
  "Elaborate": "Mở rộng",
  "Select Tone": "Chọn giọng văn",
  "Rewrite Style": "Phong cách viết lại",
  "Output Length": "Độ dài đầu ra",
  "Please paste your story": "Vui lòng dán câu chuyện của bạn",
  "Story is too short. Please provide more content.":
      "Câu chuyện quá ngắn. Vui lòng cung cấp thêm nội dung.",
  "Same": "Giống nhau",
  "More Dramatic": "Kịch tính hơn",
  "More Humorous": "Hài hước hơn",
  "More Emotional": "Cảm xúc hơn",
  "More Suspenseful": "Hồi hộp hơn",
  "Lighter": "Nhẹ nhàng hơn",
  "Improved": "Được cải thiện",
  "Simplified": "Đơn giản hóa",
  "More Descriptive": "Mô tả nhiều hơn",
  "More Dialogue": "Nhiều hội thoại hơn",
  "More Action": "Nhiều hành động hơn",
  "Literary": "Văn học",
  "Shorter": "Ngắn hơn",
  "Longer": "Dài hơn",
  "Much Longer": "Dài hơn nhiều",
  "Rewrite Now": "Viết lại ngay",
  "Story/Book Topic": "Chủ đề câu chuyện/sách",
  "Keywords (Optional)": "Từ khóa (Tùy chọn)",
  "Describe your story topic or theme...":
      "Mô tả chủ đề hoặc chủ điểm câu chuyện của bạn...",
  "e.g., magic, dragon, adventure": "vd., phép thuật, rồng, phiêu lưu",
  "Title For": "Tiêu đề cho",
  "Title Style": "Phong cách tiêu đề",
  "Number of Titles": "Số lượng tiêu đề",
  "Book": "Sách",
  "Short Story": "Truyện ngắn",
  "Novel": "Tiểu thuyết",
  "Chapter": "Chương",
  "Series": "Bộ truyện",
  "Simple": "Đơn giản",
  "Mysterious": "Bí ẩn",
  "Dramatic": "Kịch tính",
  "Catchy": "Hấp dẫn",
  "Poetic": "Thơ mộng",
  "Kids": "Trẻ em",
  "SEO Article": "Bài viết SEO",
  "How-To Guide": "Hướng dẫn từng bước",
  "Listicle": "Bài danh sách",
  "Product Review": "Đánh giá sản phẩm",
  "Opinion Piece": "Bài quan điểm",
  "News Article": "Bài báo",
  "Professional": "Chuyên nghiệp",
  "Casual": "Thông thường",
  "Informative": "Thông tin",
  "Persuasive": "Thuyết phục",
  "Friendly": "Thân thiện",
  "Authoritative": "Quyền uy",
  "Short (500-800)": "Ngắn (500-800)",
  "Medium (800-1500)": "Vừa (800-1500)",
  "Long (1500-2500)": "Dài (1500-2500)",
  "Detailed (2500+)": "Chi tiết (2500+)",
  "Storytime": "Giờ kể chuyện",
  "Documentary": "Phim tài liệu",
  "Short Reel": "Reel ngắn",
  "Educational": "Giáo dục",
  "Review": "Đánh giá",
  "Tutorial": "Hướng dẫn",
  "< 1 min (Shorts)": "< 1 phút (Shorts)",
  "1-3 min": "1-3 phút",
  "5-10 min": "5-10 phút",
  "10-20 min": "10-20 phút",
  "20+ min": "20+ phút",
  "Engaging": "Cuốn hút",
  "Energetic": "Năng động",
  "Calm": "Bình tĩnh",
  "Funny": "Hài hước",
  "Next": "Tiếp theo",
  "Get Started": "Bắt đầu",
  "Your tool for quick, high-quality essay writing":
      "Công cụ viết bài nhanh và chất lượng cao của bạn",
};
