import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> zh = {
  AppKeys.lblChooseLanguage: "选择语言",
  "All": "全部",
  "AI Story Generator": "AI故事生成器",
  "Story Generator": "故事生成器",
  "Essay Writer": "论文写作",
  "Essay length": "论文长度",
  "Script Generator": "剧本生成器",
  "Create original stories in seconds": "几秒钟内创建原创故事",
  "Academic writing made simple": "学术写作变得简单",
  "Generate powerful scripts for any medium": "为任何媒介生成强大的剧本",
  "Start Writing": "开始写作",
  "Create Now": "立即创建",
  "Start Generating": "开始生成",
  "Your Stories": "你的故事",
  "No stories yet": "还没有故事",
  "Start creating your first story!": "开始创建你的第一个故事!",
  "Your Story Space Awaits": "你的故事空间等待着你",
  "Start your first story and see it appear here": "开始你的第一个故事并看到它出现在这里",
  "Language": "语言",
  "Rate us": "给我们评分",
  "Share us": "分享我们",
  "Privacy Policy": "隐私政策",
  "Settings": "设置",
  "Select Language": "选择语言",
  "Dashboard": "仪表板",
  "BENEFITS": "优势",
  "Subscribe": "订阅",
  "Weekly": "每周",
  "Monthly": "每月",
  "Yearly": "每年",
  "week": "周",
  "months": "月",
  "year": "年",
  "Terms & Condition": "条款和条件",
  "No Commitment. Cancel anytime": "无承诺。随时取消",
  "No Payment Now": "现在无需付款",
  "3 days free": "免费3天",
  "Start your free trial": "开始免费试用",
  "More detailed answers": "更详细的答案",
  "Instant responds": "即时响应",
  "Text recognition": "文本识别",
  "Powered by AI": "由AI驱动",
  "Storytelleing": "讲故事",
  ' Power': "力量",
  "Unlock your \nFill ": "解锁你的\nFill",
  "Your History": "你的历史",
  "Terms and Conditions": "条款和条件",
  "Short": "短",
  "Medium": "中",
  "Long": "长",
  "Length": "长度",
  "Describe your topic...": "描述你的主题...",
  "Set Creativity": "设置创造力",
  "Standard": "标准",
  "Creative": "创意",
  "Complex": "复杂",
  "Select Genre": "选择类型",
  "Fantasy": "幻想",
  "Mystery": "神秘",
  "Thriller": "惊悚",
  "Script Tone": "剧本基调",
  "Script Type": "剧本类型",
  "Comedy": "喜剧",
  "Drama": "剧情",
  "Horror": "恐怖",
  "Action": "动作",
  "Romance": "浪漫",
  "Motivational": "励志",
  "Advertisement": "广告",
  "Fairy Tale": "童话",
  "Sci-Fi": "科幻",
  "Select Style": "选择风格",
  "Imaginative": "富有想象力",
  "Innovative": "创新",
  "Generate": "生成",
  "Please wait...": "请稍候...",
  "Result": "结果",
  "Regenerate": "重新生成",
  "Download": "下载",
  "Text copied to clipboard!": "文本已复制到剪贴板!",
  "Please enter a topic": "请输入主题",
  "Story Magic": "故事魔法",
  "Let AI bring your thoughts to a full story": "让AI将你的想法变成完整的故事",
  "Smart Scripts": "智能剧本",
  "From concept to script—fast, easy, and creative": "从概念到剧本—快速、简单、有创意",
  "Perfect Essays": "完美论文",
  "You have reached your free limit": "你已达到免费限制",
  "Donwload": "下载",
  "Press again to exit app": "再次按下以退出应用",
  "Saved to files": "TXT文件保存成功!",
  "Error: Please try again": "错误：请重试",
  "Subscription expired": "订阅已过期",
  "Purchase cancelled": "购买已取消",
  "Purchase failed": "购买失败",
  "Restore failed": "恢复失败",
  "Purchase Successful!": "购买成功!",
  "Short (200-500 words)": "短（200-500字）",
  "Medium (500-1000 words)": "中（500-1000字）",
  "Large (1000+ words)": "长（1000+字）",
  "Academic Level": "学术水平",
  "Type of Paper": "论文类型",
  "High School": "高中",
  "College": "大学",
  "Short Film": "短片",
  "University": "大学",
  "Masters": "硕士",
  "Custom": "自定义",
  "YouTube Video": "YouTube视频",
  "Podcast": "播客",
  "Reel": "短视频",
  "Tiktok Video": "抖音视频",
  "Movie": "电影",
  "Expository": "说明性",
  "Argumentative": "议论性",
  "Narrative": "叙述性",
  "Descriptive": "描述性",

  AppKeys.arabic: "阿拉伯语",
  AppKeys.chinese: "中文",
  AppKeys.english: "英语",
  AppKeys.french: "法语",
  AppKeys.german: "德语",
  AppKeys.hindi: "印地语",
  AppKeys.indonesian: "印尼语",
  AppKeys.japanese: "日语",
  AppKeys.korean: "韩语",
  AppKeys.portuguese: "葡萄牙语",
  "Go Premium": "升级到高级",
  "Unlock Everything": "解锁所有功能",
  "Unlimited Story Generation": "无限故事生成",
  "Write Longer & Detailed Essays": "编写更长、更详细的文章",
  "Advanced Script Writer": "高级脚本编写器",
  "Unlock All Styles & Tones": "解锁所有风格和语气",
  "No Word/Length Limit": "无字数/长度限制",
  "Remove All Ads": "移除所有广告",
  "3 days free": "3天免费",
  "Restore": "恢复",
  "YouTube Video": "YouTube视频",
  "Podcast": "播客",
  "Reel": "短视频",
  AppKeys.russian: "俄语",
  AppKeys.spanish: "西班牙语",
  "AI Story Writer": "AI故事作家",
  AppKeys.turkish: "土耳其语",

  "We're sorry to hear that 😔": "很抱歉听到这个消息 😔",
  "We'll try to improve 🙁": "我们会努力改进 🙁",
  "Thanks for your feedback 🙂": "感谢您的反馈 🙂",
  "Great! We're glad you like it 😊": "太好了！很高兴您喜欢 😊",
  "Awesome! Thank you so much! 🎉": "太棒了！非常感谢！🎉",
  "Maybe Later": "稍后再说",
  "Tap a star to rate your experience": "点击星星为您的体验评分",
  "Enjoying AI Math Solver?": "喜欢 AI Math Solver 吗？",
  "Thank you for rating us": "感谢您的评分",
  "Submit Rating": "提交评分",
  "Hindi": "印地语",
  "Enjoying AI Story Generator?": "喜欢 AI 故事生成器吗？",
};
