import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> zh = {
  AppKeys.lblChooseLanguage: "选择语言",
  "All": "全部",
  "AI Story Generator": "AI故事生成器",
  "Story Generator": "故事生成器",
  "Essay Writer": "论文写作",
  "Essay length": "论文长度",
  "Script Generator": "剧本生成器",
  "Create original stories in seconds": "几秒钟内创建原创故事",
  "Academic writing made simple": "学术写作变得简单",
  "Generate powerful scripts for any medium": "为任何媒介生成强大的剧本",
  "Start Writing": "开始写作",
  "Create Now": "立即创建",
  "Start Generating": "开始生成",
  "Your Stories": "你的故事",
  "No stories yet": "还没有故事",
  "Start creating your first story!": "开始创建你的第一个故事!",
  "Your Story Space Awaits": "你的故事空间等待着你",
  "Start your first story and see it appear here": "开始你的第一个故事并看到它出现在这里",
  "Language": "语言",
  "Rate us": "给我们评分",
  "Share us": "分享我们",
  "Privacy Policy": "隐私政策",
  "Settings": "设置",
  "Select Language": "选择语言",
  "Dashboard": "仪表板",
  "BENEFITS": "优势",
  "Subscribe": "订阅",
  "Weekly": "每周",
  "Monthly": "每月",
  "Yearly": "每年",
  "week": "周",
  "months": "月",
  "year": "年",
  "Terms & Condition": "条款和条件",
  "No Commitment. Cancel anytime": "无承诺。随时取消",
  "No Payment Now": "现在无需付款",
  "3 days free": "免费3天",
  "Start your free trial": "开始免费试用",
  "More detailed answers": "更详细的答案",
  "Instant responds": "即时响应",
  "Text recognition": "文本识别",
  "Powered by AI": "由AI驱动",
  "Storytelleing": "讲故事",
  ' Power': "力量",
  "Unlock your \nFill ": "解锁你的\nFill",
  "Your History": "你的历史",
  "Terms and Conditions": "条款和条件",
  "Short": "短",
  "Medium": "中",
  "Long": "长",
  "Length": "长度",
  "Describe your topic...": "描述你的主题...",
  "Set Creativity": "设置创造力",
  "Standard": "标准",
  "Creative": "创意",
  "Complex": "复杂",
  "Select Genre": "选择类型",
  "Fantasy": "幻想",
  "Mystery": "神秘",
  "Thriller": "惊悚",
  "Script Tone": "剧本基调",
  "Script Type": "剧本类型",
  "Comedy": "喜剧",
  "Drama": "剧情",
  "Horror": "恐怖",
  "Action": "动作",
  "Romance": "浪漫",
  "Motivational": "励志",
  "Advertisement": "广告",
  "Fairy Tale": "童话",
  "Sci-Fi": "科幻",
  "Select Style": "选择风格",
  "Imaginative": "富有想象力",
  "Innovative": "创新",
  "Generate": "生成",
  "Please wait...": "请稍候...",
  "Result": "结果",
  "Regenerate": "重新生成",
  "Download": "下载",
  "Text copied to clipboard!": "文本已复制到剪贴板!",
  "Please enter a topic": "请输入主题",
  "Story Magic": "故事魔法",
  "Let AI bring your thoughts to a full story": "让AI将你的想法变成完整的故事",
  "Smart Scripts": "智能剧本",
  "From concept to script—fast, easy, and creative": "从概念到剧本—快速、简单、有创意",
  "Perfect Essays": "完美论文",
  "You have reached your free limit": "你已达到免费限制",
  "Donwload": "下载",
  "Press again to exit app": "再次按下以退出应用",
  "Saved to files": "TXT文件保存成功!",
  "Error: Please try again": "错误：请重试",
  "Subscription expired": "订阅已过期",
  "Purchase cancelled": "购买已取消",
  "Purchase failed": "购买失败",
  "Restore failed": "恢复失败",
  "Purchase Successful!": "购买成功!",
  "Short (200-500 words)": "短（200-500字）",
  "Medium (500-1000 words)": "中（500-1000字）",
  "Large (1000+ words)": "长（1000+字）",
  "Academic Level": "学术水平",
  "Type of Paper": "论文类型",
  "High School": "高中",
  "College": "大学",
  "Short Film": "短片",
  "University": "大学",
  "Masters": "硕士",
  "Custom": "自定义",
  "YouTube Video": "YouTube视频",
  "Podcast": "播客",
  "Reel": "短视频",
  "Tiktok Video": "抖音视频",
  "Movie": "电影",
  "Expository": "说明性",
  "Argumentative": "议论性",
  "Narrative": "叙述性",
  "Descriptive": "描述性",

  AppKeys.arabic: "阿拉伯语",
  AppKeys.chinese: "中文",
  AppKeys.english: "英语",
  AppKeys.french: "法语",
  AppKeys.german: "德语",
  AppKeys.hindi: "印地语",
  AppKeys.indonesian: "印尼语",
  AppKeys.japanese: "日语",
  AppKeys.korean: "韩语",
  AppKeys.portuguese: "葡萄牙语",
  "Go Premium": "升级到高级",
  "Unlock Everything": "解锁所有功能",
  "Unlimited Story Generation": "无限故事生成",
  "Write Longer & Detailed Essays": "编写更长、更详细的文章",
  "Advanced Script Writer": "高级脚本编写器",
  "Unlock All Styles & Tones": "解锁所有风格和语气",
  "No Word/Length Limit": "无字数/长度限制",
  "Remove All Ads": "移除所有广告",
  "Restore": "恢复",
  AppKeys.russian: "俄语",
  AppKeys.spanish: "西班牙语",
  "AI Story Writer": "AI故事作家",
  AppKeys.turkish: "土耳其语",

  "We're sorry to hear that 😔": "很抱歉听到这个消息 😔",
  "We'll try to improve 🙁": "我们会努力改进 🙁",
  "Thanks for your feedback 🙂": "感谢您的反馈 🙂",
  "Great! We're glad you like it 😊": "太好了！很高兴您喜欢 😊",
  "Awesome! Thank you so much! 🎉": "太棒了！非常感谢！🎉",
  "Maybe Later": "稍后再说",
  "Tap a star to rate your experience": "点击星星为您的体验评分",
  "Enjoying AI Math Solver?": "喜欢 AI Math Solver 吗？",
  "Thank you for rating us": "感谢您的评分",
  "Submit Rating": "提交评分",
  "Hindi": "印地语",
  "Enjoying AI Story Generator?": "喜欢 AI 故事生成器吗？",

  // New strings for download & actions
  'Download As': '下载为',
  'Choose format to download': '选择下载格式',
  'Text File': '文本文件',
  'PDF File': 'PDF文件',
  'Copy': '复制',
  'Share': '分享',
  'Text copied!': '文本已复制！',
  'PDF saved successfully!': 'PDF保存成功！',
  'Error creating PDF: Please try again': '创建PDF时出错：请重试',

  // Character Story Tool
  'Character Story': '角色故事',
  'Character Details': '角色详情',
  'Character Name': '角色名称',
  'Age (e.g., 25, Young Adult, Ancient)': '年龄（例如：25岁、青年、古老）',
  'Personality (e.g., brave, shy, cunning)': '性格（例如：勇敢、害羞、狡猾）',
  'Role (e.g., Hero, Villain, Mentor)': '角色定位（例如：英雄、反派、导师）',
  'Additional Details (optional)': '其他详情（可选）',
  'Output Style': '输出风格',
  'Generate Character': '生成角色',
  'Please enter character name': '请输入角色名称',
  'Please enter character role': '请输入角色定位',
  // Output Styles
  'Detailed': '详细',
  'Brief': '简短',
  'Elaborate': '精细',

  // Home Screen Tool Cards
  'Create detailed character backstories': '创建详细的角色背景故事',
  'Create Character': '创建角色',
  'Transform and improve your existing stories': '转换并改进您现有的故事',
  'Rewrite Now': '立即重写',
  'Generate catchy titles for your stories': '为您的故事生成吸引人的标题',
  'Generate Titles': '生成标题',

  // Rewrite Story Tool
  'Rewrite Story': '重写故事',
  'Paste Your Story': '粘贴您的故事',
  'Paste your story here to rewrite...': '在此粘贴您要重写的故事...',
  'Select Tone': '选择语气',
  'Rewrite Style': '重写风格',
  'Output Length': '输出长度',
  'Please paste your story': '请粘贴您的故事',
  'Story is too short. Please provide more content.': '故事太短。请提供更多内容。',
  // Tone options
  'Same': '相同',
  'More Dramatic': '更戏剧化',
  'More Humorous': '更幽默',
  'More Emotional': '更情感化',
  'More Suspenseful': '更悬疑',
  'Lighter': '更轻松',
  // Style options
  'Improved': '改进',
  'Simplified': '简化',
  'More Descriptive': '更描述性',
  'More Dialogue': '更多对话',
  'More Action': '更多动作',
  'Literary': '文学性',
  // Length options
  'Shorter': '更短',
  'Longer': '更长',
  'Much Longer': '更长得多',

  // Title Generator Tool
  'Title Generator': '标题生成器',
  'Story/Book Topic': '故事/书籍主题',
  'Keywords (Optional)': '关键词（可选）',
  'Describe your story topic or theme...': '描述您的故事主题或主旨...',
  'e.g., magic, dragon, adventure': '例如：魔法、龙、冒险',
  'Title For': '标题用于',
  'Title Style': '标题风格',
  'Number of Titles': '标题数量',
  // Type options
  'Book': '书籍',
  'Short Story': '短篇故事',
  'Novel': '小说',
  'Chapter': '章节',
  'Series': '系列',
  // Title Style options
  'Simple': '简单',
  'Mysterious': '神秘',
  'Dramatic': '戏剧性',
  'Catchy': '吸引眼球',
  'Poetic': '诗意',
  // Genre options
  'Kids': '儿童',

  // Blog Writer Tool
  'Blog Writer': '博客写手',
  'Blog Topic': '博客主题',
  'Target Keywords': '目标关键词',
  'Target Audience (Optional)': '目标受众（可选）',
  'Enter your blog topic or title...': '输入您的博客主题或标题...',
  'e.g., AI writing, content marketing, SEO tips': '例如：AI写作、内容营销、SEO技巧',
  'e.g., small business owners, bloggers': '例如：小企业主、博主',
  'Article Type': '文章类型',
  'Writing Tone': '写作语气',
  'Article Length': '文章长度',
  'SEO Options': 'SEO选项',
  'Include Meta Description': '包含元描述',
  'Include Keyword Suggestions': '包含关键词建议',
  'Include FAQs Section': '包含常见问题部分',
  'Please enter a blog topic': '请输入博客主题',
  'Generate Blog': '生成博客',
  'SEO optimized articles with keywords': '带关键词的SEO优化文章',
  'Write Blog': '撰写博客',
  // Article Types
  'SEO Article': 'SEO文章',
  'How-To Guide': '操作指南',
  'Listicle': '清单文章',
  'Product Review': '产品评测',
  'Opinion Piece': '观点文章',
  'News Article': '新闻文章',
  // Blog Tones
  'Professional': '专业',
  'Casual': '休闲',
  'Informative': '信息性',
  'Persuasive': '说服性',
  'Friendly': '友好',
  'Authoritative': '权威',
  // Blog Lengths
  'Short (500-800)': '短篇 (500-800)',
  'Medium (800-1500)': '中篇 (800-1500)',
  'Long (1500-2500)': '长篇 (1500-2500)',
  'Detailed (2500+)': '详细 (2500+)',

  // YouTube Script Tool
  'YouTube Script': 'YouTube脚本',
  'Video Topic': '视频主题',
  'Key Points (Optional)': '要点（可选）',
  'What is your video about?': '您的视频是关于什么的？',
  'List key points to cover (optional)...': '列出要涵盖的要点（可选）...',
  'Video Duration': '视频时长',
  'Script Options': '脚本选项',
  'Include Hook/Intro': '包含钩子/引言',
  'Include Call-to-Action': '包含行动号召',
  'Include Timestamps': '包含时间戳',
  'Please enter a video topic': '请输入视频主题',
  'Generate Script': '生成脚本',
  'Create scripts for videos & reels': '为视频和短视频创建脚本',
  'Create Script': '创建脚本',
  // Script Types
  'Storytime': '故事时间',
  'Documentary': '纪录片',
  'Short Reel': '短视频',
  'Educational': '教育',
  'Review': '评测',
  'Tutorial': '教程',
  // Durations
  '< 1 min (Shorts)': '< 1分钟 (短视频)',
  '1-3 min': '1-3分钟',
  '5-10 min': '5-10分钟',
  '10-20 min': '10-20分钟',
  '20+ min': '20+分钟',
  // Script Tones
  'Engaging': '引人入胜',
  'Energetic': '充满活力',
  'Calm': '平静',
  'Funny': '有趣',

  // Story Generator - Styles
  'Inspired': '灵感',

  // Script Writer - Script Tones (formats)
  'Film Script': '电影剧本',
  'Stage Play': '舞台剧',
  'Scene Breakdown': '场景分解',
  'Dialogue Only': '仅对话',

  // Ad & UI
  'Ad loading please wait..': '广告加载中，请稍候..',

  // Word Counter & Reading Time
  'Words:': '字数:',
  'Reading:': '阅读时间:',

  // Missing strings from hi.dart
  'Adventure': '冒险',
};
