import 'package:ai_story_writer/constant/app_Strings.dart';

Map<String, String> zu = {
  AppKeys.lblChooseLanguage: "Khetha Ulimi",
  "All": "Konke",
  "AI Story Generator": "Isakhiqizi Sendaba se-AI",
  "Story Generator": "Isakhiqizi Sendaba",
  "Essay Writer": "Umbhali We-essay",
  "Essay length": "Ubude be-essay",
  "Script Generator": "Isakhiqizi Seskripthi",
  "Create original stories in seconds": "Dala izindaba eziyinhloko ngomzuzwana",
  "Academic writing made simple": "Ukubhala kwezemfundo kwenziwe kwalula",
  "Generate powerful scripts for any medium":
      "Dala izikripthi ezinamandla kunoma yimuphi umthombo",
  "Start Writing": "Qala Ukubhala",
  "Create Now": "Dala Manje",
  "Start Generating": "Qala Ukukhiqiza",
  "Your Stories": "Izindaba Zakho",
  "No stories yet": "Azikho izindaba okwamanje",
  "Start creating your first story!": "Qala ukudala indaba yakho yokuqala!",
  "Your Story Space Awaits": "Isikhala Sendaba Yakho Silindile",
  "Start your first story and see it appear here":
      "Qala indaba yakho yokuqala uyibone lapha",
  "Language": "Ulimi",
  "Rate us": "Sinikeze amazinga",
  "Share us": "Sabelana ngathi",
  "Privacy Policy": "Inqubomgomo Yobumfihlo",
  "Settings": "Izilungiselelo",
  "Select Language": "Khetha Ulimi",
  "Dashboard": "Ibhodi Yokulawula",
  "BENEFITS": "IZINZUZO",
  "Subscribe": "Bhalisela",
  "Weekly": "Ngasonto",
  "Monthly": "Ngenyanga",
  "Yearly": "Ngonyaka",
  "week": "iviki",
  "months": "izinyanga",
  "year": "unyaka",
  "Terms & Condition": "Imigomo Nemibandela",
  "No Commitment. Cancel anytime": "Akukho ukuzibophezela. Khansela noma nini",
  "No Payment Now": "Akukho Ukukhokha Manje",
  "3 days free": "Izinsuku ezi-3 mahhala",
  "Start your free trial": "Qala ukuhlola kwakho kwamahhala",
  "More detailed answers": "Izimpendulo ezinemininingwane",
  "Instant responds": "Izimpendulo ezisheshayo",
  "Text recognition": "Ukubona kombhalo",
  "Powered by AI": "Iqhutshwa yi-AI",
  "Storytelleing": "Ukuxoxa Izindaba",
  ' Power': "Amandla",
  "Unlock your \nFill ": "Vula okwakho \nGcwalisa",
  "Your History": "Umlando Wakho",
  "Terms and Conditions": "Imigomo Nemibandela",
  "Short": "Emfushane",
  "Medium": "Ephakathi",
  "Long": "Ende",
  "Length": "Ubude",
  "Describe your topic...": "Chaza isihloko sakho...",
  "Set Creativity": "Setha Ukudala",
  "Standard": "Okujwayelekile",
  "Creative": "Obukhona",
  "Complex": "Okuyinkimbinkimbi",
  "Select Genre": "Khetha Uhlobo",
  "Fantasy": "Umbono",
  "Mystery": "Imfihlakalo",
  "Thriller": "Esabisayo",
  "Script Tone": "Ithoni Yeskripthi",
  "Script Type": "Uhlobo Lweskripthi",
  "Comedy": "Amahlaya",
  "Drama": "Idrama",
  "Horror": "Okwesabekayo",
  "Action": "Isenzo",
  "Romance": "Uthando",
  "Go Premium": "Thola i-Premium",
  "Unlock Everything": "Vula Konke",
  "Unlimited Story Generation": "Ukukhiqiza Izindaba Okungenamkhawulo",
  "Write Longer & Detailed Essays": "Bhala Ama-essay Amade Anemininingwane",
  "Advanced Script Writer": "Umbhali Weskripthi Ophezulu",
  "Unlock All Styles & Tones": "Vula Zonke Izitayela Namathoni",
  "No Word/Length Limit": "Akukho Umkhawulo Wamagama/Ubude",
  "Remove All Ads": "Susa Zonke Izikhangiso",
  "Restore": "Buyisela",
  "YouTube Video": "Ividiyo ye-YouTube",
  "Podcast": "Iphodikasti",
  "Reel": "I-Reel",
  "Motivational": "Okukhuthazayo",
  "Advertisement": "Isikhangiso",
  "Fairy Tale": "Inganekwane",
  "Sci-Fi": "I-Sci-Fi",
  "Select Style": "Khetha Isitayela",
  "Imaginative": "Okucabangayo",
  "Innovative": "Okwenza okusha",
  "AI Story Writer": "Umbhali Wendaba we-AI",
  "Generate": "Khiqiza",
  "Please wait...": "Sicela ulinde...",
  "Result": "Umphumela",
  "Regenerate": "Khiqiza kabusha",
  "Download": "Landa",
  "Text copied to clipboard!": "Umbhalo ukopishwe ku-clipboard!",
  "Please enter a topic": "Sicela ufake isihloko",
  "Story Magic": "Umlingo Wendaba",
  "Let AI bring your thoughts to a full story":
      "Vumela i-AI iphendule imicabango yakho ibe yindaba ephelele",
  "Smart Scripts": "Izikripthi Ezihlakaniphile",
  "From concept to script—fast, easy, and creative":
      "Kusukela emqondweni kuya eskripthini—ngokushesha, kalula, futhi ngobuciko",
  "Perfect Essays": "Ama-essay Aphelele",
  "You have reached your free limit": "Usufike kumkhawulo wakho wamahhala",
  "Donwload": "Landa",
  "Press again to exit app": "Cindezela futhi ukuphuma ku-app",
  "Saved to files": "Ifayela le-TXT lilondolozwe ngempumelelo!",
  "Error: Please try again": "Iphutha: Sicela uzame futhi",
  "Subscription expired": "Ukubhalisela kuphelelwe yisikhathi",
  "Purchase cancelled": "Ukuthenga kukhanseliwe",
  "Purchase failed": "Ukuthenga kuhlulekile",
  "Restore failed": "Ukubuyisela kuhlulekile",
  "Purchase Successful!": "Ukuthenga Kuphumelele!",
  "Short (200-500 words)": "Emfushane (amagama angu-200-500)",
  "Medium (500-1000 words)": "Ephakathi (amagama angu-500-1000)",
  "Large (1000+ words)": "Ende (amagama angu-1000+)",
  "Academic Level": "Izinga Lezemfundo",
  "Type of Paper": "Uhlobo Lwephepha",
  "High School": "Isikole Samabanga Aphezulu",
  "College": "Ikolishi",
  "Short Film": "Ifilimu Emfushane",
  "University": "Inyuvesi",
  "Masters": "Iziqu Zezifundo",
  "Custom": "Okulungisiwe",
  "Tiktok Video": "Ividiyo ye-Tiktok",
  "Movie": "Ifilimu",
  "Expository": "Okuchazayo",
  "Argumentative": "Okuphikisanayo",
  "Narrative": "Okuxoxayo",
  "Descriptive": "Okuchazayo",
  "We're sorry to hear that 😔": "Siyaxolisa ukuzwa lokho 😔",
  "We'll try to improve 🙁": "Sizozama ukuthuthuka 🙁",
  "Thanks for your feedback 🙂": "Siyabonga ngempendulo yakho 🙂",
  "Great! We're glad you like it 😊": "Kuhle! Siyajabula ukuthi uyakuthanda 😊",
  "Awesome! Thank you so much! 🎉": "Kuhle kakhulu! Siyabonga kakhulu! 🎉",
  "Maybe Later": "Mhlawumbe Kamuva",
  "Tap a star to rate your experience":
      "Thepha inkanyezi ukuze unikeze ulwazi lwakho amazinga",
  "Enjoying AI Math Solver?": "Uyakuthanda i-AI Math Solver?",
  "Thank you for rating us": "Siyabonga ngokunikeza amazinga",
  "Submit Rating": "Thumela Amazinga",
  "Hindi": "IsiHindi",
  "Enjoying AI Story Generator?": "Uyakuthanda i-AI Story Generator?",
  "Adventure": "Inhlobo",
  "Inspired": "Okukhuthazayo",
  "Film Script": "Iskripthi Sefilimu",
  "Stage Play": "Umdlalo Wesiteji",
  "Scene Breakdown": "Ukuhlaziya Isigcawu",
  "Dialogue Only": "Ingxoxo Kuphela",
  "Ad loading please wait..": "Isikhangiso silayisha, sicela ulinde...",
  "Words:": "Amagama:",
  "Reading:": "Ukufunda:",

  AppKeys.arabic: "Isi-Arabhu",
  AppKeys.chinese: "IsiShayina",
  AppKeys.english: "IsiNgisi",
  AppKeys.french: "IsiFulentshi",
  AppKeys.german: "IsiJalimane",
  AppKeys.hindi: "IsiHindi",
  AppKeys.indonesian: "Isi-Indonesian",
  AppKeys.japanese: "IsiJapani",
  AppKeys.korean: "IsiKorea",
  AppKeys.portuguese: "IsiPutukezi",
  AppKeys.russian: "IsiRashiya",
  AppKeys.spanish: "IsiSpanishi",
  AppKeys.turkish: "IsiTurkey",

  'Download As': 'Landa Njenge',
  'Choose format to download': 'Khetha ifomethi yokulanda',
  'Text File': 'Ifayela Lombhalo',
  'PDF File': 'Ifayela le-PDF',
  'Copy': 'Kopisha',
  'Share': 'Yabelana',
  'Text copied!': 'Umbhalo ukopishwe!',
  'Copied to clipboard': 'Kukopishwe ku-clipboard',
  'File saved successfully': 'Ifayela lilondolozwe ngempumelelo',
  'Error saving file': 'Iphutha lokulondoloza ifayela',
  'Share Story': 'Yabelana Ngendaba',
  'Export': 'Khiphela',
  "Character Story": "Indaba Yomulingisi",
  "Create detailed character backstories":
      "Dala izindaba ezinemininingo zasemuva zomulingisi",
  "Create Character": "Dala Umulingisi",
  "Rewrite Story": "Bhala Kabusha Indaba",
  "Paste Your Story": "Namathisela Indaba Yakho",
  "Paste your story here to rewrite...":
      "Namathisela indaba yakho lapha ukuze ubhale kabusha...",
  "Transform and improve your existing stories":
      "Guqula futhi uthuthukise izindaba zakho ezikhona",
  "Title Generator": "Isiqali Sikasihloko",
  "Generate catchy titles for your stories":
      "Khiqiza amasihloko aheha ezindabeni zakho",
  "Generate Titles": "Khiqiza Amasihloko",
  "Blog Writer": "Umbhali Webhulogi",
  "Blog Topic": "Isihloko Sewebhulogi",
  "Target Keywords": "Amagama Ambuliwe Ahlosiwe",
  "Target Audience (Optional)": "Izilaleli Ezihlosiwe (Okukhethwa)",
  "Enter your blog topic or title...":
      "Faka isihloko noma igama lewebhulogi yakho...",
  "e.g., AI writing, content marketing, SEO tips":
      "isb., ukubhala kwe-AI, ukumaketha okuqukethwe, amathiphu e-SEO",
  "e.g., small business owners, bloggers":
      "isb., abanikazi bamabhizinisi amancane, ababhali wewebhulogi",
  "Article Type": "Uhlobo Lwendatshana",
  "Writing Tone": "Ithoni Yokubhala",
  "Article Length": "Ubude Bendatshana",
  "SEO Options": "Izinketho ze-SEO",
  "Include Meta Description": "Faka Incazelo ye-Meta",
  "Include Keyword Suggestions": "Faka Iziphakamiso Zamagama Ambuliwe",
  "Include FAQs Section": "Faka Isigaba Semibuzo Ejwayelekile",
  "Please enter a blog topic": "Sicela ufake isihloko sewebhulogi",
  "Generate Blog": "Khiqiza Iwebhulogi",
  "SEO optimized articles with keywords":
      "Izindatshana ezihlelelwe i-SEO ngamagama ambuliwe",
  "Write Blog": "Bhala Iwebhulogi",
  "YouTube Script": "Umbhalo we-YouTube",
  "Video Topic": "Isihloko Sevidiyo",
  "Key Points (Optional)": "Amaphuzu Abalulekile (Okukhethwa)",
  "What is your video about?": "Ividiyo yakho imayelana nani?",
  "List key points to cover (optional)...":
      "Bala amaphuzu abalulekile okuwagubha (okukhethwa)...",
  "Video Duration": "Ubude Bevidiyo",
  "Script Options": "Izinketho Zombhalo",
  "Include Hook/Intro": "Faka Isandulelo/Isingeniso",
  "Include Call-to-Action": "Faka Isimemo Sokwenza",
  "Include Timestamps": "Faka Izimpawu Zesikhathi",
  "Please enter a video topic": "Sicela ufake isihloko sevidiyo",
  "Generate Script": "Khiqiza Umbhalo",
  "Create scripts for videos & reels": "Dala imibhalo yamavidiyo nama-reels",
  "Create Script": "Dala Umbhalo",
  "Character Details": "Imininingwane Komulingisi",
  "Character Name": "Igama Lomulingisi",
  "Age (e.g., 25, Young Adult, Ancient)":
      "Iminyaka (isb., 25, Umuntu Omncane, Wasendulo)",
  "Personality (e.g., brave, shy, cunning)":
      "Isimo (isb., isibindi, ukumahluleka, ubuhlakani)",
  "Role (e.g., Hero, Villain, Mentor)":
      "Indima (isb., Iqhawe, Isitha, Umeluleki)",
  "Additional Details (optional)": "Imininingwane Eyengeziwe (okukhethwa)",
  "Output Style": "Isitayela Sokukhipha",
  "Generate Character": "Khiqiza Umulingisi",
  "Please enter character name": "Sicela ufake igama lomulingisi",
  "Please enter character role": "Sicela ufake indima yomulingisi",
  "Detailed": "Enemininingwane",
  "Brief": "Emfushane",
  "Elaborate": "Eningi",
  "Select Tone": "Khetha Ithoni",
  "Rewrite Style": "Isitayela Sokubhala Kabusha",
  "Output Length": "Ubude Bokukhipha",
  "Please paste your story": "Sicela unamathisele indaba yakho",
  "Story is too short. Please provide more content.":
      "Indaba imfushane kakhulu. Sicela unikeze okuqukethwe okuningi.",
  "Same": "Okufanayo",
  "More Dramatic": "Okudramatiki Kakhulu",
  "More Humorous": "Okuhlakatyelwe Kakhulu",
  "More Emotional": "Okuzwelayo Kakhulu",
  "More Suspenseful": "Okushaqisayo Kakhulu",
  "Lighter": "Ukukhanya Kakhulu",
  "Improved": "Ithuthukisiwe",
  "Simplified": "Isenziwe Lula",
  "More Descriptive": "Echazayo Kakhulu",
  "More Dialogue": "Ingxoxo Eningi",
  "More Action": "Isenzo Esiningi",
  "Literary": "Yezincwadi",
  "Shorter": "Emfushane",
  "Longer": "Ende",
  "Much Longer": "Ende Kakhulu",
  "Rewrite Now": "Bhala Kabusha Manje",
  "Story/Book Topic": "Isihloko Sendaba/Incwadi",
  "Keywords (Optional)": "Amagama Ambuliwe (Okukhethwa)",
  "Describe your story topic or theme...":
      "Chaza isihloko noma ithiyamu yendaba yakho...",
  "e.g., magic, dragon, adventure":
      "isb., umthakathi, udrako, ukulwa nobungozi",
  "Title For": "Isihloko",
  "Title Style": "Isitayela Sesihloko",
  "Number of Titles": "Inani Lamasihloko",
  "Book": "Incwadi",
  "Short Story": "Indaba Emfushane",
  "Novel": "Inoveli",
  "Chapter": "Isahluko",
  "Series": "Uchungechunge",
  "Simple": "Elula",
  "Mysterious": "Enigiwe",
  "Dramatic": "Edramatiki",
  "Catchy": "Eheha",
  "Poetic": "Yezinkondlo",
  "Kids": "Izingane",
  "SEO Article": "Indatshana ye-SEO",
  "How-To Guide": "Umhlahlandlela Wokwenza",
  "Listicle": "Indatshana Yohlu",
  "Product Review": "Ukuhlolwa Komkhiqizo",
  "Opinion Piece": "Indatshana Yombono",
  "News Article": "Indatshana Yezindaba",
  "Professional": "Ubuchwepheshe",
  "Casual": "Okwejwayelekile",
  "Informative": "Enikezela Ulwazi",
  "Persuasive": "Ekhuthazayo",
  "Friendly": "Obuhlobo",
  "Authoritative": "Enegunya",
  "Short (500-800)": "Emfushane (500-800)",
  "Medium (800-1500)": "Phakathi (800-1500)",
  "Long (1500-2500)": "Ende (1500-2500)",
  "Detailed (2500+)": "Enemininingwane (2500+)",
  "Storytime": "Isikhathi Sendaba",
  "Documentary": "Ifilimu Yemibono",
  "Short Reel": "I-Reel Emfushane",
  "Educational": "Yemfundo",
  "Review": "Ukuhlola",
  "Tutorial": "Isifundo",
  "< 1 min (Shorts)": "< 1 iminithi (Emifushane)",
  "1-3 min": "1-3 iminithi",
  "5-10 min": "5-10 iminithi",
  "10-20 min": "10-20 iminithi",
  "20+ min": "20+ iminithi",
  "Engaging": "Eheha",
  "Energetic": "Enomthombo",
  "Calm": "Thulile",
  "Funny": "Hlekisayo",
  "Next": "Okulandelayo",
  "Get Started": "Qala",
  "Your tool for quick, high-quality essay writing":
      "Ithuluzi lakho lokubhala ngokushesha nangekhwalithi ephezulu",
};
